// Auto-generated mapping: curated exerciseLibrary.ts exercise id -> exerciseDbId
// (the free-exercise-db animated GIF identifier used by getExerciseGifUrl).
//
// The main exercise library (src/lib/exerciseLibrary.ts) is a hand-curated,
// coach-quality set of ~270 exercises with real descriptions, tips and body
// part categorisation. It predates and is separate from the raw 1500-exercise
// dataset in public/data/exercises.json, which only supplies animated demo
// GIFs. This map links the two -- but only where the match is a confident,
// same-exercise match (exact or near-exact name + matching equipment). Where
// no confident match exists, the exercise simply has no demo GIF and falls
// back to the placeholder icon, rather than risk showing the wrong movement.
export const EXERCISE_GIF_IDS: Record<string, string> = {
  'arnold-press': 'Xy4jlWA',
  'assisted-pull-up-machine': 'kiJ4Z2K',
  'barbell-bent-over-row': 'eZyBC3j',
  'barbell-bicep-curl': 'Yza7XrQ',
  'barbell-calf-raises': 'ipvgBnC',
  'barbell-front-raise': 'b2Uoz54',
  'barbell-front-squat': 'zG0zs85',
  'barbell-glute-bridge': 'qKBpF7I',
  'barbell-good-mornings': 'XlZ4lAC',
  'barbell-lunges': 't8iSghb',
  'barbell-overhead-press': 'kTbSH9h',
  'barbell-preacher-curl': 'qOgPVf6',
  'barbell-pullover': 'i6LWjok',
  'barbell-reverse-curl': 'xNrS20v',
  'barbell-reverse-wrist-curl': 'LsZkfU6',
  'barbell-romanian-deadlift': 'wQ2c4XD',
  'barbell-shrugs': 'dG7tG5y',
  'barbell-split-squat': 'W31mMjd',
  'barbell-thrusters': 'f7Y9eDZ',
  'barbell-upright-row': 'UDlhcO8',
  'barbell-wrist-curl': '82LxxkW',
  'bear-crawl': '0Yz8WdV',
  'bear-crawls': '0Yz8WdV',
  'behind-neck-press': 'xDh0lJr',
  'bench-dips': 'DQ0cqkT',
  'bodyweight-tricep-extension': 's0HKO2I',
  'burpees': 'dK9394r',
  'burpees-full': 'dK9394r',
  'cable-bicep-curl': 'QTXKWPh',
  'cable-concentration-curl': 'NvfE43H',
  'cable-crunch': '8xUv4J7',
  'cable-front-raise': 'u2X71Np',
  'cable-kickback-glutes': 'HEJ6DIX',
  'cable-lateral-raises': 'goJ6ezq',
  'cable-pull-through': 'OM46QHm',
  'cable-rope-hammer-curl': 'HPlPoQA',
  'cable-rope-pushdown': '3ZflifB',
  'cable-shrugs': 'Eg98Ft9',
  'cable-side-bend': 'wPypxFY',
  'cable-tricep-pushdown': '3ZflifB',
  'cable-upright-row': 'cALKspW',
  'calf-raises-bodyweight': 'bJYHBIN',
  'chest-dips': '9WTm7dq',
  'circuit-bear-crawls': '0Yz8WdV',
  'circuit-burpees': 'dK9394r',
  'circuit-jump-squats': 'LIlE5Tn',
  'circuit-kettlebell-swings': 'UHJlbu3',
  'circuit-medicine-ball-slams': 'oHg8eop',
  'circuit-mountain-climbers': 'RJgzwny',
  'circuit-skipping': 'e1e76I2',
  'clean-and-press': 'SGY8Zui',
  'close-grip-barbell-bench': 'J6Dx1Mu',
  'close-grip-bench-press': 'J6Dx1Mu',
  'dead-bug': 'iny3m5y',
  'decline-barbell-bench-press': 'GrO65fd',
  'decline-dumbbell-bench-press': 'DwhEmmE',
  'dumbbell-bicep-curl': 'NbVPDMW',
  'dumbbell-clean-and-press': '7Hg55JG',
  'dumbbell-concentration-curl': 'gvsWLQw',
  'dumbbell-deadlift': 'nUwVh7b',
  'dumbbell-flyes-incline': '1PLE8e9',
  'dumbbell-front-raises': '3eGE2JC',
  'dumbbell-hammer-curls': 'slDvUAU',
  'dumbbell-incline-curl': 'ae9UoXQ',
  'dumbbell-kickbacks': 'W6PxUkg',
  'dumbbell-lateral-raises': 'DsgkuIt',
  'dumbbell-lunges': 'RRWFUcw',
  'dumbbell-preacher-curl': 'jivWf8n',
  'dumbbell-pullover': '9XjtHvS',
  'dumbbell-romanian-deadlift': 'rR0LJzx',
  'dumbbell-shrugs': 'NJzBsGJ',
  'dumbbell-side-bend': 'IpONWYv',
  'dumbbell-sumo-deadlift': 'nUwVh7b',
  'dumbbell-sumo-squat': 'HsvHqgf',
  'dumbbell-upright-row': 'ainizkb',
  'dumbbell-wrist-curl': 'BLCvwr2',
  'farmers-walk': 'qPEzJjA',
  'flat-barbell-bench-press': 'EIeI8Vf',
  'flat-dumbbell-bench-press': 'SpYC0Kp',
  'flutter-kicks': 'UVo2Qs2',
  'glute-bridge': 'GibBPPg',
  'goblet-squat': 'yn8yg1r',
  'hanging-knee-raises': '03lzqwk',
  'hanging-leg-raises': 'I3tsCnC',
  'inchworms': 'ZgsNQ6d',
  'incline-barbell-bench-press': '3TZduzM',
  'incline-dumbbell-bench-press': 'ns0SIbU',
  'inverted-rows': 'bZGHsAZ',
  'jump-squats': 'LIlE5Tn',
  'kettlebell-swings': 'UHJlbu3',
  'leg-press': '7zdxRTl',
  'machine-chest-press': 'wDN97Ca',
  'mountain-climbers': 'RJgzwny',
  'pendlay-row': 'r0z6xzQ',
  'plank-shoulder-taps': 'yRpV5TC',
  'power-clean': 'SiWCcTN',
  'rack-pulls': 'za9Ni4z',
  'seated-cable-row': 'fUBheHs',
  'seated-dumbbell-shoulder-press': 'znQUdHY',
  'smith-machine-bench-press': 'trqKQv2',
  'smith-machine-shoulder-press': '903mzG8',
  'smith-machine-squat': 'jFtipLl',
  'snatch': 'dG5Smob',
  'stationary-bike': 'H1PESYI',
  'straight-arm-pulldown': 'x69MAlq',
  'sumo-deadlift': 'KgI0tqW',
  'sumo-deadlift-glutes': 'KgI0tqW',
  'tricep-dips': 'X6C6i5Y',
  'walking-lunges': 'IZVHb27',
  'zercher-squat': 'LSTChY9',
};
