import type { UnitAssessment } from '../types';

export const level4Unit3Assessment: UnitAssessment = {
  unitNumber: 3,
  title: 'Sport-Specific Strength & Conditioning — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the purpose of a needs analysis in sport?', options: ['To impress athletes', 'To make training harder', 'To create complex programmes', 'To ensure training targets the specific demands of the sport and athlete weaknesses'], correctAnswer: 3, explanation: 'Needs analysis connects training directly to sport performance demands.' },
    { type: 'multiple_choice', question: 'What separates agility from change of direction speed?', options: ['Speed', 'Strength', 'Endurance', 'The addition of perception and decision-making to physical movement'], correctAnswer: 3, explanation: 'True agility requires reading and responding to unpredictable stimuli.' },
    { type: 'multiple_choice', question: 'How can the interference effect be minimised?', options: ['Separate strength and endurance sessions by at least 6 hours', 'Only do strength training', 'Avoid all endurance training', 'Train both in the same session always'], correctAnswer: 0, explanation: 'Temporal separation reduces molecular conflict between adaptation pathways.' },
    { type: 'multiple_choice', question: 'What determines plyometric exercise progression?', options: ['How high you can jump', 'Age', 'Body weight', 'Mastery of landing mechanics, then progressive increase in ground contact intensity'], correctAnswer: 3, explanation: 'Safe force absorption must be mastered before progressing to higher-intensity jumps.' },
    { type: 'multiple_choice', question: 'What is the fundamental principle of sport-specific programming?', options: ['Maximise gym time', 'Train sport skills in the gym', 'The gym supports the field — never let gym training interfere with practice quality', 'Do as much as possible'], correctAnswer: 2, explanation: 'Gym work complements sport performance, not competes with it.' },
    { type: 'multiple_choice', question: 'What endurance method best replicates team sport demands?', options: ['Yoga', 'Repeated sprint ability (RSA) training', 'Swimming', 'Long slow distance'], correctAnswer: 1, explanation: 'RSA directly simulates the repeated sprint demands of match play.' },
    { type: 'multiple_choice', question: 'When should the heaviest gym session occur relative to match day?', options: ['Match morning', 'At least 3 days before', 'Day before', 'Does not matter'], correctAnswer: 1, explanation: 'Heavy training must have sufficient separation from competition for recovery.' },
    { type: 'multiple_choice', question: 'What is the minimum effective dose (MED)?', options: ['Two sessions per week for everything', 'Maximum possible volume', 'Whatever the athlete wants', 'The smallest stimulus that produces meaningful adaptation'], correctAnswer: 3, explanation: 'Training near the MED for each quality maximises concurrent training capacity.' },
    { type: 'multiple_choice', question: 'In what order should qualities be trained within a session?', options: ['Strength always first', 'Random order', 'Speed/power first (highest neural demand), conditioning last', 'Endurance first'], correctAnswer: 2, explanation: 'Neural demands dictate session sequencing for optimal quality expression.' },
    { type: 'multiple_choice', question: 'What is the acute:chronic workload ratio used for?', options: ['Tracking body weight', 'Monitoring training load to optimise adaptation and minimise injury risk', 'Counting calories', 'Measuring flexibility'], correctAnswer: 1, explanation: 'The ACWR helps ensure weekly load increases are safe and manageable.' },
    { type: 'multiple_choice', question: 'Why is deceleration training important for field sport athletes?', options: ['It is not important', 'The ability to stop and change direction safely prevents injury and improves sport performance', 'Only goalkeepers need it', 'It replaces sprint training'], correctAnswer: 1, explanation: 'Deceleration is critical for both performance and ACL/hamstring injury prevention.' },
    { type: 'multiple_choice', question: 'What makes in-season training different from off-season?', options: ['All gym work stops', 'Nothing should change', 'Volume reduces 40-60% while intensity is maintained to preserve adaptations', 'Volume increases to compensate for match fatigue'], correctAnswer: 2, explanation: 'In-season training maintains qualities with reduced volume to manage total load.' },
  ],
};