import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the three foundations of a coaching philosophy?', options: ['Speed, strength, power', 'Evidence-based practice, practical experience, and values alignment', 'Money, fame, success', 'Education, certification, experience'], correctAnswer: 1, explanation: 'A philosophy integrates evidence, experience, and values.' },
    { type: 'multiple_choice', question: 'What is the primary ethical obligation of a fitness professional?', options: ['Making money', 'Looking good', 'Do no harm', 'Being popular'], correctAnswer: 2, explanation: 'Never prescribing training that exceeds capacity or ignores wellbeing.' },
    { type: 'multiple_choice', question: 'What does scope of practice mean?', options: ['Training as many people as possible', 'Knowing where your competence ends and referring appropriately', 'Only training beginners', 'Avoiding all risk'], correctAnswer: 1, explanation: 'Working within your qualifications protects both you and your clients.' },
    { type: 'multiple_choice', question: 'How often should you revisit your coaching philosophy?', options: ['Never — once written it is final', 'Annually — it should evolve as you gain experience', 'Every day', 'Only when forced to'], correctAnswer: 1, explanation: 'A philosophy that never changes suggests you have stopped learning.' },
    { type: 'multiple_choice', question: 'What distinguishes a coach with a philosophy from one without?', options: ['Revenue', 'The ability to guide through any situation based on deeper principles, not just templates', 'Certification level', 'Number of clients'], correctAnswer: 1, explanation: 'Philosophy-driven coaches lead; technicians follow templates.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'Which type of cueing produces better movement outcomes?', options: ['Internal cues focusing on body parts', 'External cues focusing on movement effects', 'No cueing at all', 'Shouting louder'], correctAnswer: 1, explanation: 'External cues allow natural self-organisation of movement patterns.' },
    { type: 'multiple_choice', question: 'What are the three stages of motor learning?', options: ['Easy, medium, hard', 'Cognitive, associative, autonomous', 'Beginner, intermediate, advanced', 'Learning, practising, competing'], correctAnswer: 1, explanation: 'Each stage requires different coaching approaches.' },
    { type: 'multiple_choice', question: 'What happens when you over-coach an autonomous learner?', options: ['They improve faster', 'Excessive coaching can disrupt their automatic movement patterns', 'Nothing changes', 'They become dependent'], correctAnswer: 1, explanation: 'Advanced performers move best with minimal conscious interference.' },
    { type: 'multiple_choice', question: 'How often should you give feedback for best long-term learning?', options: ['Every single rep', 'Every 3rd to 5th rep — reduced frequency builds self-correction ability', 'Only once per session', 'Never'], correctAnswer: 1, explanation: 'Reduced feedback frequency forces learners to develop error detection skills.' },
    { type: 'multiple_choice', question: 'Convert this internal cue to external: Extend your knees', options: ['Push harder', 'Drive the floor away', 'Straighten your legs more', 'Use your quads'], correctAnswer: 1, explanation: 'External cues direct attention to movement outcomes, not body mechanics.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is the foundation of effective coaching communication?', options: ['Giving great advice', 'Active listening — fully concentrating on what someone is saying', 'Talking confidently', 'Having all the answers'], correctAnswer: 1, explanation: 'Clients who feel heard develop more trust and show better compliance.' },
    { type: 'multiple_choice', question: 'Why do most clients quit?', options: ['Bad programmes', 'They feel unsupported, unheard, or unrealistically judged', 'Programmes are too easy', 'They run out of money'], correctAnswer: 1, explanation: 'Communication and expectation management drive retention more than programming.' },
    { type: 'multiple_choice', question: 'What is the best approach to difficult conversations about non-compliance?', options: ['Blame the client', 'Address the behaviour not the person, using specific observations and offering support', 'Ignore the issue', 'Threaten to stop coaching them'], correctAnswer: 1, explanation: 'Non-judgemental, specific observations open dialogue rather than triggering defensiveness.' },
    { type: 'multiple_choice', question: 'What should you set from the first consultation?', options: ['Unrealistic goals to motivate', 'Realistic expectations with honest timelines', 'No expectations', 'Only short-term goals'], correctAnswer: 1, explanation: 'Unrealistic expectations are the primary reason clients quit.' },
    { type: 'multiple_choice', question: 'How should you celebrate client progress?', options: ['Only celebrate outcome metrics like weight loss', 'Reframe success around behaviour metrics: sessions attended, nutrition compliance', 'Wait until goals are fully achieved', 'Compare them to other clients'], correctAnswer: 1, explanation: 'Process-focused celebration sustains motivation regardless of outcome fluctuations.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'Is resistance training safe for adolescents?', options: ['No — it stunts growth', 'Dangerous at any age', 'Yes — it is safe and beneficial when properly supervised', 'Only after age 18'], correctAnswer: 2, explanation: 'The growth-stunting myth has been comprehensively debunked by research.' },
    { type: 'multiple_choice', question: 'What is the primary training goal for older adults?', options: ['Aesthetic improvement', 'Compound movements that build functional strength for daily life independence', 'Weight loss only', 'Flexibility only'], correctAnswer: 1, explanation: 'Resistance training combats sarcopenia and reduces fall risk.' },
    { type: 'multiple_choice', question: 'When should you obtain medical clearance for a client?', options: ['Never', 'Before training anyone with a diagnosed chronic condition', 'Only for athletes', 'Only if they are over 70'], correctAnswer: 1, explanation: 'Medical clearance protects both you and the client when conditions are present.' },
    { type: 'multiple_choice', question: 'What should never be assumed about older adult clients?', options: ['That they need special equipment', 'That they cannot squat, deadlift, or press — never assume limitation', 'That they are motivated', 'That they are healthy'], correctAnswer: 1, explanation: 'Many older adults can train with excellent form — do not patronise.' },
    { type: 'multiple_choice', question: 'What is the primary goal for adolescent training?', options: ['Maximum strength gains', 'Competition preparation', 'Developing a positive relationship with exercise while building skills', 'Bodybuilding'], correctAnswer: 2, explanation: 'Enjoyment and skill development should be prioritised over intensity and load.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'Why do most personal trainers leave the industry within two years?', options: ['Lack of fitness knowledge', 'Lack of business skills — pricing, marketing, and client retention', 'The work is too physical', 'Too much competition'], correctAnswer: 1, explanation: 'Technical competence without business acumen leads to unsustainable careers.' },
    { type: 'multiple_choice', question: 'What costs 5-7 times more than retaining an existing client?', options: ['New equipment', 'Acquiring a new client', 'Continuing education', 'Gym rent'], correctAnswer: 1, explanation: 'Client retention is far more cost-effective than constant acquisition.' },
    { type: 'multiple_choice', question: 'What three factors drive client retention?', options: ['Price, location, equipment', 'Results, relationships, and experience', 'Marketing, branding, social media', 'Discounts, promotions, free sessions'], correctAnswer: 1, explanation: 'Clients who see progress, feel cared about, and enjoy training stay for years.' },
    { type: 'multiple_choice', question: 'Which revenue model is most scalable?', options: ['One-to-one PT only', 'Online coaching — no time-for-money ceiling', 'Group classes only', 'Selling supplements'], correctAnswer: 1, explanation: 'Online coaching removes the geographic and time constraints of in-person work.' },
    { type: 'multiple_choice', question: 'What two numbers should every fitness business track?', options: ['Followers and likes', 'Client retention rate and client results', 'Revenue and expenses only', 'Hours worked and sessions delivered'], correctAnswer: 1, explanation: 'Retention and results are the most important health metrics for a fitness business.' },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Why is continuing professional development an ethical obligation?', options: ['It is required by law', 'Clients trust you to provide guidance based on current evidence, not outdated methods', 'It makes you more money', 'It is not — it is optional'], correctAnswer: 1, explanation: 'Using disproven methods while current evidence exists is not serving clients well.' },
    { type: 'multiple_choice', question: 'What is at the top of the evidence hierarchy?', options: ['Expert opinion', 'Case studies', 'A single randomised controlled trial', 'Systematic reviews and meta-analyses'], correctAnswer: 3, explanation: 'Systematic reviews synthesise findings from multiple studies for strongest conclusions.' },
    { type: 'multiple_choice', question: 'Why should supplement company-funded research be viewed carefully?', options: ['It is always wrong', 'Studies with conflicts of interest are more likely to produce favourable results for funders', 'It is always perfect', 'Only university research matters'], correctAnswer: 1, explanation: 'Funding conflicts can bias study design, interpretation, and publication.' },
    { type: 'multiple_choice', question: 'What should you do before changing practice based on a new study?', options: ['Change immediately', 'Wait for replication across multiple studies', 'Ignore all new research', 'Ask social media'], correctAnswer: 1, explanation: 'A single study is a data point; consistent findings across multiple studies are evidence.' },
    { type: 'multiple_choice', question: 'What is the practical difference between statistical and practical significance?', options: ['They are the same', 'A result can be statistically significant but too small to matter in real-world practice', 'Practical significance is more important than statistical', 'Only statistical significance matters'], correctAnswer: 1, explanation: 'Always ask how big the actual difference is — small effects may be meaningless in practice.' },
  ]),
  cq(4, 7, [
    { type: 'multiple_choice', question: 'What are the three pillars of evidence-based practice?', options: ['Research, research, research', 'Scientific evidence, professional experience, and client values/preferences', 'Textbooks, courses, certifications', 'Training, nutrition, recovery'], correctAnswer: 1, explanation: 'All three must inform decisions — none alone is sufficient.' },
    { type: 'multiple_choice', question: 'What happens when a coach ignores client preferences?', options: ['Nothing', 'Programmes look great on paper but fail because the client will not follow them', 'Results improve', 'Clients train harder'], correctAnswer: 1, explanation: 'A programme a client will not follow is worse than an imperfect one they will.' },
    { type: 'multiple_choice', question: 'When your experience contradicts research, what should you consider?', options: ['Your experience is always right', 'Research is always right', 'Is your experience based on representative samples, or memorable cases? Does the research match your context?', 'Flip a coin'], correctAnswer: 2, explanation: 'Mature practitioners hold both perspectives and test systematically.' },
    { type: 'multiple_choice', question: 'What determines whether research findings apply to your client?', options: ['The journal it was published in', "Whether the study population and context match your client\'s situation", 'How famous the researchers are', 'How recently it was published'], correctAnswer: 1, explanation: 'Population match and context relevance determine practical applicability.' },
    { type: 'multiple_choice', question: 'What makes evidence-based practice different from just following studies?', options: ['Nothing', 'EBP integrates evidence with experience and client needs, not blind adherence', 'EBP ignores research', 'EBP only uses the newest studies'], correctAnswer: 1, explanation: 'Integration of all three pillars produces the best coaching decisions.' },
  ]),
  cq(4, 8, [
    { type: 'multiple_choice', question: 'What makes a great coach beyond knowledge?', options: ['Certifications alone', 'The ability to apply knowledge to real people with empathy, adaptability, and integrity', 'Physical fitness', 'Social media following'], correctAnswer: 1, explanation: 'Knowledge is necessary but insufficient — application with human skills defines greatness.' },
    { type: 'multiple_choice', question: 'Why should you identify your coaching niche?', options: ['To limit yourself', 'Serving a specific population deeply is more valuable than serving everyone superficially', 'It is not important', 'To exclude potential clients'], correctAnswer: 1, explanation: 'Depth of service in a niche creates more value than breadth of shallow service.' },
    { type: 'multiple_choice', question: 'What does the Unbreakable standard represent?', options: ['Being physically unbreakable', 'Knowledge in service of others, applied with integrity, refined through lifelong practice', 'Never showing weakness', 'Extreme training'], correctAnswer: 1, explanation: 'The standard is about ethical service and continuous improvement, not physical invincibility.' },
    { type: 'multiple_choice', question: 'How does the best coaching career develop?', options: ['Peaks at 25 and declines', 'Through decades of practice, reflection, and genuine care — producing wisdom courses cannot teach', 'Only through more certifications', 'By copying successful coaches'], correctAnswer: 1, explanation: 'Experience and reflection produce wisdom that formal education cannot replicate.' },
    { type: 'multiple_choice', question: 'What is the lifelong commitment of a coach?', options: ['Making money', 'Learning, serving, and growing — coaching is a practice, not a destination', 'Winning competitions', 'Becoming famous'], correctAnswer: 1, explanation: 'Coaching is a lifelong practice of improvement, not a career destination.' },
  ]),
];