import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What primarily determines optimal squat technique?', options: ['Shoe brand', 'The lifter\'s anthropometry (limb lengths, joint structure)', 'Social media advice', 'Always the same for everyone'], correctAnswer: 1, explanation: 'Individual anatomy dictates optimal technique — one size does not fit all.' },
    { type: 'multiple_choice', question: 'What does a long femur-to-torso ratio require in the squat?', options: ['More upright torso', 'More forward lean to keep the bar over mid-foot', 'Narrower stance always', 'Less depth'], correctAnswer: 1, explanation: 'Long femurs necessitate more forward lean — this is structural, not a fault.' },
    { type: 'multiple_choice', question: 'What determines whether conventional or sumo deadlift is better for an individual?', options: ['Personal preference only', 'Arm-to-leg ratio and hip structure', 'Which looks harder', 'Coach instruction only'], correctAnswer: 1, explanation: 'Limb proportions directly influence which stance provides the shortest bar path.' },
    { type: 'multiple_choice', question: 'Why might squat shoes with an elevated heel help some lifters?', options: ['They look professional', 'They compensate for limited ankle dorsiflexion', 'They add weight to the lift', 'They are required by competition rules'], correctAnswer: 1, explanation: 'Heel elevation addresses ankle mobility limitations without being a crutch.' },
    { type: 'multiple_choice', question: 'What should you ask before correcting someone\'s technique?', options: ['Is this a genuine fault or an adaptation to their structure?', 'Are they wearing the right shoes?', 'How much can they lift?', 'How long have they been training?'], correctAnswer: 0, explanation: 'Distinguishing structural adaptation from actual faults prevents incorrect corrections.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What type of lever is most common in the human body?', options: ['First class', 'Second class', 'Third class — effort between fulcrum and load', 'Fourth class'], correctAnswer: 2, explanation: 'Third class levers sacrifice mechanical advantage for speed and range of motion.' },
    { type: 'multiple_choice', question: 'What is a moment arm?', options: ['A type of bicep curl', 'The perpendicular distance from force line to joint', 'The length of your arm', 'A training tool'], correctAnswer: 1, explanation: 'Longer moment arms create greater torque demand for a given force.' },
    { type: 'multiple_choice', question: 'Why does the bench press have a sticking point when the upper arm is horizontal?', options: ['Muscles are weakest there', 'The moment arm at the shoulder is longest at that position', 'Gravity changes direction', 'You need to breathe'], correctAnswer: 1, explanation: 'The sticking point occurs where leverage demand is highest, not where muscles are weakest.' },
    { type: 'multiple_choice', question: 'What do third class levers prioritise over mechanical advantage?', options: ['Muscle size', 'Speed and range of motion', 'Stability', 'Endurance'], correctAnswer: 1, explanation: 'Third class levers sacrifice force efficiency for speed and movement range.' },
    { type: 'multiple_choice', question: 'How can you use moment arm knowledge in exercise selection?', options: ['Select exercises that modify moment arms to change the training stimulus', 'Ignore it — only muscle size matters', 'Always use the longest moment arms', 'It only applies to Olympic lifts'], correctAnswer: 0, explanation: 'Changing body position or exercise variation alters moment arms and shifts muscle emphasis.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What is the single most important concept in injury prevention?', options: ['Perfect form', 'Stretching', 'Load management — the relationship between training load and tissue tolerance', 'Warming up'], correctAnswer: 2, explanation: 'Most injuries result from load exceeding tissue tolerance, not form issues alone.' },
    { type: 'multiple_choice', question: 'What is the acute:chronic workload ratio?', options: ['This week\'s load compared to the 4-week rolling average', 'Morning vs evening training', 'Warm-up vs working sets', 'Cardio vs weights ratio'], correctAnswer: 0, explanation: 'When the ratio exceeds 1.3-1.5, injury risk increases significantly.' },
    { type: 'multiple_choice', question: 'What is the most common cause of shoulder injuries in lifting?', options: ['One bad rep', 'Excessive pressing volume with insufficient pulling volume', 'Overhead pressing only', 'Cold weather'], correctAnswer: 1, explanation: 'Volume imbalance between pressing and pulling is the primary shoulder injury mechanism.' },
    { type: 'multiple_choice', question: 'What role does form play relative to load management in injury prevention?', options: ['Form is everything', 'Load management is far more predictive of injury risk than technique perfection', 'Neither matters', 'They are equally important always'], correctAnswer: 1, explanation: 'Research shows load management predicts injury better than form quality.' },
    { type: 'multiple_choice', question: 'What is the safest approach to volume increases?', options: ['Double volume each week', 'Gradual, consistent progression keeping acute:chronic ratio below 1.3', 'Random variation', 'Same volume forever'], correctAnswer: 1, explanation: 'Gradual progression keeps the workload ratio in the safe zone.' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What is prehabilitation?', options: ['Treatment after injury', 'Proactive work to strengthen vulnerable structures before injury', 'Physical therapy', 'Massage'], correctAnswer: 1, explanation: 'Prehab targets at-risk structures to prevent problems before they start.' },
    { type: 'multiple_choice', question: 'What pulling-to-pressing ratio is recommended for shoulder health?', options: ['1:1', '1:2', '2:1 pulling-to-pressing', '3:1'], correctAnswer: 2, explanation: 'A 2:1 pulling-to-pressing ratio balances the pressing dominance of most programmes.' },
    { type: 'multiple_choice', question: 'When should prehab be performed in a session?', options: ['After the main workout', 'During warm-up or as filler between main lift sets', 'On separate days only', 'Never during training'], correctAnswer: 1, explanation: 'Integrating prehab into warm-ups ensures it gets done without adding session time.' },
    { type: 'multiple_choice', question: 'What intensity should prehab work use?', options: ['Maximum effort', 'Light to moderate — preparing for training, not fatiguing before it', 'Only bodyweight', 'As heavy as possible'], correctAnswer: 1, explanation: 'Prehab aims for activation and gradual tendon strengthening, not exhaustion.' },
    { type: 'multiple_choice', question: 'What is the cheapest insurance policy in strength training?', options: ['Supplements', 'Five minutes of targeted prehab before each session', 'Expensive equipment', 'Hiring a physiotherapist full-time'], correctAnswer: 1, explanation: 'Consistent prehab prevents injuries that would cost weeks or months of training.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What is the biggest mistake when returning from injury?', options: ['Training too cautiously forever', 'Either returning too quickly (re-injury) or waiting too long (detraining)', 'Changing exercises', 'Seeing a physiotherapist'], correctAnswer: 1, explanation: 'Both extremes are harmful — the goal is finding the earliest productive point.' },
    { type: 'multiple_choice', question: 'What pain level is generally acceptable during rehabilitation?', options: ['Any pain means stop', 'Up to 3/10 if it settles within 24 hours', 'Up to 8/10', 'Pain should be completely ignored'], correctAnswer: 1, explanation: 'Mild pain that resolves quickly is normal during structured return to training.' },
    { type: 'multiple_choice', question: 'What is kinesiophobia?', options: ['Fear of exercise equipment', 'Fear of re-injury that persists after physical healing', 'Fear of the gym', 'A type of injury'], correctAnswer: 1, explanation: 'Kinesiophobia can persist long after physical recovery and requires graded exposure.' },
    { type: 'multiple_choice', question: 'How should you overcome fear of re-injury?', options: ['Avoid the movement permanently', 'Gradual exposure starting well below pre-injury capacity', 'Immediately return to previous weights', 'Only train with machines'], correctAnswer: 1, explanation: 'Graded exposure builds confidence through successful repetitions at progressing loads.' },
    { type: 'multiple_choice', question: 'What is the most important question after injury?', options: ['When can I lift heavy again?', 'What can I do right now that does not make this worse?', 'Should I quit training?', 'Who is at fault?'], correctAnswer: 1, explanation: 'There is almost always something productive you can do while recovering.' },
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'What is the difference between flexibility and mobility?', options: ['They are the same', 'Flexibility is passive range; mobility is active controlled range', 'Mobility is only for athletes', 'Flexibility is more important'], correctAnswer: 1, explanation: 'Mobility (active control) matters more for training than passive flexibility.' },
    { type: 'multiple_choice', question: 'Why should static stretching be avoided before strength training?', options: ['It is boring', 'It reduces force production by 2-5%', 'It causes injuries', 'It takes too long'], correctAnswer: 1, explanation: 'Extended static stretching before training impairs force production.' },
    { type: 'multiple_choice', question: 'What is loaded stretching?', options: ['Using exercises at full range under moderate load to improve both mobility and strength', 'Stretching with heavy weights dangerously', 'Stretching after loading', 'Only for advanced athletes'], correctAnswer: 0, explanation: 'Loaded stretching simultaneously improves mobility and end-range strength.' },
    { type: 'multiple_choice', question: 'How long should an effective mobility routine take?', options: ['5-10 minutes targeting specific limitations', '30+ minutes of generic stretching', 'At least one hour', 'No time at all — skip it'], correctAnswer: 0, explanation: 'Targeted, efficient mobility work produces better results than lengthy generic routines.' },
    { type: 'multiple_choice', question: 'How should you evaluate a mobility drill?', options: ['By how much it hurts', 'Test-retest: do the drill for 2 minutes then check if target movement improved', 'By how long you hold it', 'By social media popularity'], correctAnswer: 1, explanation: 'If a drill does not measurably improve your training movement, try a different one.' },
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What is the primary purpose of movement screening?', options: ['To diagnose injuries', 'To identify gross movement limitations and guide programme design', 'To predict future injuries precisely', 'To determine 1RM potential'], correctAnswer: 1, explanation: 'Screens inform exercise selection and identify starting points, not predict injuries.' },
    { type: 'multiple_choice', question: 'What does heels rising during an overhead squat indicate?', options: ['Weak quads', 'Limited ankle dorsiflexion', 'Poor motivation', 'Tight hamstrings'], correctAnswer: 1, explanation: 'Heel rise is a classic sign of insufficient ankle mobility.' },
    { type: 'multiple_choice', question: 'What does research say about movement screens predicting injury?', options: ['They perfectly predict all injuries', 'Scoring poorly does not reliably predict injury in strength athletes', 'They should replace all other assessments', 'Only the FMS works'], correctAnswer: 1, explanation: 'Screens identify limitations but do not reliably predict injury risk.' },
    { type: 'multiple_choice', question: 'Should a screen ever be used to tell someone they cannot train?', options: ['Yes — safety first', 'No — use it to determine the most appropriate starting point', 'Only for beginners', 'Only for older adults'], correctAnswer: 1, explanation: 'Every limitation is the next thing to work on — never a reason to stop training.' },
    { type: 'multiple_choice', question: 'How many angles should you film an overhead squat assessment from?', options: ['One is enough', 'Front, side, and rear — compensations are only visible from certain angles', 'Only the front', 'No filming needed'], correctAnswer: 1, explanation: 'Multiple angles reveal compensations that are invisible from a single viewpoint.' },
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'Why is gradual progression essential for joint health?', options: ['To avoid getting too strong', 'Muscles adapt in weeks but tendons and cartilage take months to years', 'Joints cannot adapt at all', 'It is only important for beginners'], correctAnswer: 1, explanation: 'The adaptation mismatch between tissues makes gradual loading essential.' },
    { type: 'multiple_choice', question: 'How long do tendons need to recover between heavy loading sessions?', options: ['12 hours', '24 hours', '48-72 hours', 'One week'], correctAnswer: 2, explanation: 'Tendon tissue turnover is slower than muscle, requiring 48-72 hours between heavy sessions.' },
    { type: 'multiple_choice', question: 'What type of loading stimulates tendon remodelling with minimal risk?', options: ['Maximal dynamic lifts', 'Isometric holds at moderate intensity', 'Plyometric jumps', 'Ballistic throws'], correctAnswer: 1, explanation: 'Isometric loading provides tendon stimulus with minimal risk.' },
    { type: 'multiple_choice', question: 'What lifestyle factor is most critical for tissue repair?', options: ['Supplements', 'Sleep — 7-9 hours for growth hormone release', 'Saunas', 'Compression garments'], correctAnswer: 1, explanation: 'Growth hormone released during deep sleep drives tendon and cartilage remodelling.' },
    { type: 'multiple_choice', question: 'What is the goal of training for joint longevity?', options: ['Maximum strength now regardless of consequences', 'Still training productively in 30 years', 'Avoiding all heavy weights', 'Only training with machines'], correctAnswer: 1, explanation: 'Long-term joint health means decades of productive training, not just short-term gains.' },
  ]),
];