import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What primarily determines optimal squat technique?', options: ['Shoe brand', "The lifter\'s anthropometry (limb lengths, joint structure)", 'Social media advice', 'Always the same for everyone'], correctAnswer: 1, explanation: 'Individual anatomy dictates optimal technique — one size does not fit all.' },
    { type: 'multiple_choice', question: 'What does a long femur-to-torso ratio require in the squat?', options: ['More upright torso', 'Less depth', 'Narrower stance always', 'More forward lean to keep the bar over mid-foot'], correctAnswer: 3, explanation: 'Long femurs necessitate more forward lean — this is structural, not a fault.' },
    { type: 'multiple_choice', question: 'What determines whether conventional or sumo deadlift is better for an individual?', options: ['Arm-to-leg ratio and hip structure', 'Personal preference only', 'Which looks harder', 'Coach instruction only'], correctAnswer: 0, explanation: 'Limb proportions directly influence which stance provides the shortest bar path.' },
    { type: 'multiple_choice', question: 'Why might squat shoes with an elevated heel help some lifters?', options: ['They look professional', 'They compensate for limited ankle dorsiflexion', 'They are required by competition rules', 'They add weight to the lift'], correctAnswer: 1, explanation: 'Heel elevation addresses ankle mobility limitations without being a crutch.' },
    { type: 'multiple_choice', question: "What should you ask before correcting someone\'s technique?", options: ['How long have they been training?', 'How much can they lift?', 'Is this a genuine fault or an adaptation to their structure?', 'Are they wearing the right shoes?'], correctAnswer: 2, explanation: 'Distinguishing structural adaptation from actual faults prevents incorrect corrections.' },
    { type: 'multiple_choice', question: 'What is the moment arm in biomechanics?', options: ['A type of exercise', 'The bar path', 'The perpendicular distance from the line of force to the joint centre — determines torque', 'The length of your arm'], correctAnswer: 2, explanation: 'The moment arm determines how much torque a force creates at a joint — longer moment arms mean greater difficulty, which is why squat depth matters.' },
    { type: 'multiple_choice', question: 'Why does squat stance width affect muscle recruitment?', options: ['Wider stances increase hip abductor and adductor involvement while reducing knee extensor demand', 'It does not', 'Only narrow stances work muscles', 'Stance width is aesthetic only'], correctAnswer: 0, explanation: 'Wider stances shift the hip-to-knee moment arm ratio — increasing demand on hip musculature (glutes, adductors) relative to quadriceps.' },
    { type: 'multiple_choice', question: 'What determines optimal deadlift grip width?', options: ['Limb proportions — grip should minimise the distance the bar needs to travel while maintaining a stable position', 'Hand size only', 'Always as narrow as possible', 'Always as wide as possible'], correctAnswer: 0, explanation: 'Optimal grip width balances range of motion reduction (narrower = shorter pull) against shoulder and upper back stability.' },
    { type: 'multiple_choice', question: 'What is the line of force and why does it matter?', options: ['The direction gravity acts on the barbell — the bar should remain over the midfoot for optimal balance and efficiency', 'A stretching technique', 'The path of a cable', 'A type of machine'], correctAnswer: 0, explanation: 'Gravity pulls the bar straight down — keeping the bar over the midfoot (base of support) ensures balance and minimises energy waste from corrective movements.' },
    { type: 'multiple_choice', question: 'How do femur-to-torso proportions affect squat mechanics?', options: ['Only height matters', 'Longer femurs require more forward lean to keep the bar over midfoot — affecting muscle demands and stance selection', 'Proportions can be trained away', 'They have no effect'], correctAnswer: 1, explanation: 'Longer femurs create longer moment arms at the hip — requiring more forward lean, which shifts demand toward the posterior chain and often favours a wider stance.' },
  
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What type of lever is most common in the human body?', options: ['First class', 'Second class', 'Fourth class', 'Third class — effort between fulcrum and load'], correctAnswer: 3, explanation: 'Third class levers sacrifice mechanical advantage for speed and range of motion.' },
    { type: 'multiple_choice', question: 'What is a moment arm?', options: ['The length of your arm', 'A type of bicep curl', 'A training tool', 'The perpendicular distance from force line to joint'], correctAnswer: 3, explanation: 'Longer moment arms create greater torque demand for a given force.' },
    { type: 'multiple_choice', question: 'Why does the bench press have a sticking point when the upper arm is horizontal?', options: ['The moment arm at the shoulder is longest at that position', 'Muscles are weakest there', 'You need to breathe', 'Gravity changes direction'], correctAnswer: 0, explanation: 'The sticking point occurs where leverage demand is highest, not where muscles are weakest.' },
    { type: 'multiple_choice', question: 'What do third class levers prioritise over mechanical advantage?', options: ['Endurance', 'Stability', 'Speed and range of motion', 'Muscle size'], correctAnswer: 2, explanation: 'Third class levers sacrifice force efficiency for speed and movement range.' },
    { type: 'multiple_choice', question: 'How can you use moment arm knowledge in exercise selection?', options: ['Ignore it — only muscle size matters', 'Select exercises that modify moment arms to change the training stimulus', 'It only applies to Olympic lifts', 'Always use the longest moment arms'], correctAnswer: 1, explanation: 'Changing body position or exercise variation alters moment arms and shifts muscle emphasis.' },
    { type: 'multiple_choice', question: 'What is rate of force development (RFD)?', options: ['How quickly you can produce force — critical for explosive movements like jumping, sprinting, and Olympic lifts', 'Maximum force output', 'A flexibility measure', 'A recovery metric'], correctAnswer: 0, explanation: 'RFD measures how rapidly force increases from the onset of contraction — explosive sports depend more on RFD than maximum force.' },
    { type: 'multiple_choice', question: 'What is a sticking point?', options: ['Where you stop training', 'A grip technique', 'The weakest mechanical position in a lift where the moment arm is longest and muscular leverage is poorest', 'A warm-up issue'], correctAnswer: 2, explanation: 'Sticking points occur at the mechanically weakest position — where the moment arm is longest relative to the muscles producing force.' },
    { type: 'multiple_choice', question: 'How can sticking points be addressed in training?', options: ['Only train through the strong range', 'Sticking points cannot be improved', 'Overloading the specific range with pin presses, pause reps, or tempo work at the weak position', 'Avoid the lift entirely'], correctAnswer: 2, explanation: 'Targeted training at the sticking point (paused reps, pin work, isometric holds) specifically strengthens the weakest position in the lift.' },
    { type: 'multiple_choice', question: 'What is the stretch-shortening cycle?', options: ['A stretching protocol', 'The rapid transition from eccentric to concentric contraction that stores and releases elastic energy', 'A flexibility routine', 'A warm-up technique'], correctAnswer: 1, explanation: 'The stretch-shortening cycle (SSC) stores elastic energy during the eccentric phase and releases it during the concentric — like a rubber band. This is why bounce is powerful.' },
    { type: 'multiple_choice', question: 'What is mechanical advantage in lifting?', options: ['The leverage position where joint angles allow muscles to produce force most efficiently', 'Having long arms', 'Wearing a belt', 'Using machines'], correctAnswer: 0, explanation: 'Mechanical advantage changes through the range of motion — lifts are easiest where leverage is best (lockout) and hardest where it is worst (bottom position).' },
  
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What is the single most important concept in injury prevention?', options: ['Warming up', 'Perfect form', 'Load management — the relationship between training load and tissue tolerance', 'Stretching'], correctAnswer: 2, explanation: 'Most injuries result from load exceeding tissue tolerance, not form issues alone.' },
    { type: 'multiple_choice', question: 'What is the acute:chronic workload ratio?', options: ["This week\'s load compared to the 4-week rolling average", 'Morning vs evening training', 'Warm-up vs working sets', 'Cardio vs weights ratio'], correctAnswer: 0, explanation: 'When the ratio exceeds 1.3-1.5, injury risk increases significantly.' },
    { type: 'multiple_choice', question: 'What is the most common cause of shoulder injuries in lifting?', options: ['Excessive pressing volume with insufficient pulling volume', 'Overhead pressing only', 'Cold weather', 'One bad rep'], correctAnswer: 0, explanation: 'Volume imbalance between pressing and pulling is the primary shoulder injury mechanism.' },
    { type: 'multiple_choice', question: 'What role does form play relative to load management in injury prevention?', options: ['They are equally important always', 'Neither matters', 'Load management is far more predictive of injury risk than technique perfection', 'Form is everything'], correctAnswer: 2, explanation: 'Research shows load management predicts injury better than form quality.' },
    { type: 'multiple_choice', question: 'What is the safest approach to volume increases?', options: ['Gradual, consistent progression keeping acute:chronic ratio below 1.3', 'Random variation', 'Double volume each week', 'Same volume forever'], correctAnswer: 0, explanation: 'Gradual progression keeps the workload ratio in the safe zone.' },
    { type: 'multiple_choice', question: 'What is the most common cause of lifting injuries?', options: ['Using free weights', 'Accumulated fatigue, poor load management, and technique breakdown under fatigue — not the weight itself', 'Single traumatic events', 'Heavy weights'], correctAnswer: 1, explanation: 'Most lifting injuries are overuse — accumulated fatigue, insufficient recovery, and gradual technique degradation under fatigue. Single traumatic events are relatively rare.' },
    { type: 'multiple_choice', question: 'What is the acute-to-chronic workload ratio?', options: ['A rest ratio', 'A nutrition ratio', 'A supplement timing ratio', 'The ratio of recent training load (1 week) to average training load (4 weeks) — spikes above 1.5 increase injury risk'], correctAnswer: 3, explanation: 'The acute:chronic ratio tracks training load changes — rapid increases (ratio >1.5) significantly increase injury risk because tissue has not adapted to the new demand.' },
    { type: 'multiple_choice', question: 'What role does sleep play in injury prevention?', options: ['No role', 'Sleep deprivation impairs coordination, increases reaction time, reduces tissue repair, and significantly increases injury risk', 'Only affects mood', 'Only extreme deprivation matters'], correctAnswer: 1, explanation: 'Less than 7 hours of sleep increases injury risk by 1.7× — sleep supports tissue repair, coordination, reaction time, and decision-making under fatigue.' },
    { type: 'multiple_choice', question: 'What is the difference between a strain and a sprain?', options: ['Only muscles can be injured', 'A strain affects muscles or tendons; a sprain affects ligaments', 'They are the same', 'A sprain is always worse'], correctAnswer: 1, explanation: 'Strains are muscle/tendon injuries (e.g., hamstring strain); sprains are ligament injuries (e.g., ankle sprain). Both range from mild stretching to complete tears.' },
    { type: 'multiple_choice', question: 'Why is technique maintenance under fatigue critical for injury prevention?', options: ['Fatigue degrades motor control, shifting load to passive structures (joints, ligaments) instead of active structures (muscles)', 'Fatigue improves technique', 'Only heavy weights cause technique breakdown', 'Technique does not matter when fatigued'], correctAnswer: 0, explanation: 'As muscles fatigue, compensatory movement patterns shift load to joints and ligaments — which are not designed for the forces that muscles normally absorb.' },
  
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What is prehabilitation?', options: ['Massage', 'Physical therapy', 'Treatment after injury', 'Proactive work to strengthen vulnerable structures before injury'], correctAnswer: 3, explanation: 'Prehab targets at-risk structures to prevent problems before they start.' },
    { type: 'multiple_choice', question: 'What pulling-to-pressing ratio is recommended for shoulder health?', options: ['2:1 pulling-to-pressing', '1:2', '1:1', '3:1'], correctAnswer: 0, explanation: 'A 2:1 pulling-to-pressing ratio balances the pressing dominance of most programmes.' },
    { type: 'multiple_choice', question: 'When should prehab be performed in a session?', options: ['After the main workout', 'Never during training', 'During warm-up or as filler between main lift sets', 'On separate days only'], correctAnswer: 2, explanation: 'Integrating prehab into warm-ups ensures it gets done without adding session time.' },
    { type: 'multiple_choice', question: 'What intensity should prehab work use?', options: ['As heavy as possible', 'Light to moderate — preparing for training, not fatiguing before it', 'Only bodyweight', 'Maximum effort'], correctAnswer: 1, explanation: 'Prehab aims for activation and gradual tendon strengthening, not exhaustion.' },
    { type: 'multiple_choice', question: 'What is the cheapest insurance policy in strength training?', options: ['Expensive equipment', 'Hiring a physiotherapist full-time', 'Five minutes of targeted prehab before each session', 'Supplements'], correctAnswer: 2, explanation: 'Consistent prehab prevents injuries that would cost weeks or months of training.' },
    { type: 'multiple_choice', question: 'What is prehabilitation?', options: ['Rehabilitation after injury', 'Proactive exercises targeting common weak points and injury-prone areas to prevent injuries before they occur', 'General warm-up', 'Stretching before training'], correctAnswer: 1, explanation: 'Prehab proactively strengthens commonly injured areas (rotator cuff, lower back, knees) and addresses individual movement deficits before they become injuries.' },
    { type: 'multiple_choice', question: 'What are the most important areas for prehab in strength athletes?', options: ['Only biceps', 'Only the areas that hurt', 'Prehab is unnecessary for strong athletes', 'Shoulders (rotator cuff), hips (glute activation), lower back (core stability), and knees (VMO/posterior chain)'], correctAnswer: 3, explanation: 'Common injury sites in strength athletes: shoulder impingement, lower back strain, hip impingement, and knee pain — proactive strengthening of these areas prevents most injuries.' },
    { type: 'multiple_choice', question: 'When should prehab exercises be performed?', options: ['Integrated into warm-ups, between sets as fillers, or in dedicated sessions — consistency matters more than timing', 'Only when injured', 'Only on rest days', 'Only before competition'], correctAnswer: 0, explanation: 'Prehab is most effective when done consistently — adding it to warm-ups or using it as active rest between heavy sets maximises compliance.' },
    { type: 'multiple_choice', question: 'What is the rotator cuff and why is it important for lifters?', options: ['A back muscle', 'Only important for swimmers', 'A cardio muscle', 'Four small shoulder muscles that stabilise the humeral head in the socket during pressing and overhead movements'], correctAnswer: 3, explanation: 'The rotator cuff (supraspinatus, infraspinatus, teres minor, subscapularis) stabilises the shoulder during all pressing and overhead movements — weakness causes impingement.' },
    { type: 'multiple_choice', question: 'Why should prehab exercises be low-intensity?', options: ['Low-intensity does not work', 'The goal is to activate and strengthen stabilisers without adding significant fatigue to the main training session', 'Prehab should be exhausting', 'High-intensity prehab is better'], correctAnswer: 1, explanation: 'Prehab targets small stabilisers that fatigue quickly — high-intensity work exhausts them before the main session, reducing stability when it matters most.' },
  
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What is the biggest mistake when returning from injury?', options: ['Changing exercises', 'Seeing a physiotherapist', 'Either returning too quickly (re-injury) or waiting too long (detraining)', 'Training too cautiously forever'], correctAnswer: 2, explanation: 'Both extremes are harmful — the goal is finding the earliest productive point.' },
    { type: 'multiple_choice', question: 'What pain level is generally acceptable during rehabilitation?', options: ['Any pain means stop', 'Up to 3/10 if it settles within 24 hours', 'Up to 8/10', 'Pain should be completely ignored'], correctAnswer: 1, explanation: 'Mild pain that resolves quickly is normal during structured return to training.' },
    { type: 'multiple_choice', question: 'What is kinesiophobia?', options: ['Fear of re-injury that persists after physical healing', 'Fear of the gym', 'A type of injury', 'Fear of exercise equipment'], correctAnswer: 0, explanation: 'Kinesiophobia can persist long after physical recovery and requires graded exposure.' },
    { type: 'multiple_choice', question: 'How should you overcome fear of re-injury?', options: ['Immediately return to previous weights', 'Avoid the movement permanently', 'Gradual exposure starting well below pre-injury capacity', 'Only train with machines'], correctAnswer: 2, explanation: 'Graded exposure builds confidence through successful repetitions at progressing loads.' },
    { type: 'multiple_choice', question: 'What is the most important question after injury?', options: ['When can I lift heavy again?', 'Who is at fault?', 'Should I quit training?', 'What can I do right now that does not make this worse?'], correctAnswer: 3, explanation: 'There is almost always something productive you can do while recovering.' },
    { type: 'multiple_choice', question: 'What is the most important principle of return-to-training after injury?', options: ['Gradual progressive loading — starting well below capacity and increasing based on pain-free performance', 'Complete rest until 100%', 'Ignore pain and push through', 'Rush back as fast as possible'], correctAnswer: 0, explanation: 'Return-to-training should be gradual: start at 40–50% of pre-injury capacity and progress 10–15% per week based on pain-free performance.' },
    { type: 'multiple_choice', question: 'What is pain monitoring during return to training?', options: ['Ignoring all pain', 'Rating pain 0–10 during and after sessions — staying below 3/10 during exercise and ensuring pain resolves within 24 hours', 'Only monitoring severe pain', 'Pain always means stop completely'], correctAnswer: 1, explanation: 'The 0–10 pain scale guides progression: mild discomfort (0–3) during training is acceptable if it resolves within 24 hours. Worsening pain signals regression.' },
    { type: 'multiple_choice', question: 'Should you train around an injury?', options: ['Yes — maintaining training for unaffected body parts preserves fitness and supports mental health during recovery', 'Never — complete rest only', 'Only if the doctor says so', 'Only cardiovascular training'], correctAnswer: 0, explanation: 'Training unaffected areas maintains cardiovascular fitness, hormonal health, and mental wellbeing — complete rest often leads to deconditioning and poorer recovery.' },
    { type: 'multiple_choice', question: 'What is kinesiophobia?', options: ['Fear of movement or re-injury that can persist after physical healing and significantly delay return to full training', 'A coaching method', 'A flexibility disorder', 'A type of exercise'], correctAnswer: 0, explanation: 'Kinesiophobia (fear of movement/re-injury) often persists long after physical healing — it must be addressed through gradual exposure and confidence-building.' },
    { type: 'multiple_choice', question: 'What role does a physiotherapist play in return-to-training?', options: ['They assess injury, guide rehabilitation, clear for training progression, and provide exercise modifications', 'Only for surgery recovery', 'They are not needed', 'Only for professional athletes'], correctAnswer: 0, explanation: 'Physiotherapists provide clinical assessment, rehabilitation programming, and clearance for training progression — their expertise reduces re-injury risk significantly.' },
  
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'What is the difference between flexibility and mobility?', options: ['Flexibility is passive range; mobility is active controlled range', 'They are the same', 'Mobility is only for athletes', 'Flexibility is more important'], correctAnswer: 0, explanation: 'Mobility (active control) matters more for training than passive flexibility.' },
    { type: 'multiple_choice', question: 'Why should static stretching be avoided before strength training?', options: ['It is boring', 'It causes injuries', 'It takes too long', 'It reduces force production by 2-5%'], correctAnswer: 3, explanation: 'Extended static stretching before training impairs force production.' },
    { type: 'multiple_choice', question: 'What is loaded stretching?', options: ['Using exercises at full range under moderate load to improve both mobility and strength', 'Only for advanced athletes', 'Stretching with heavy weights dangerously', 'Stretching after loading'], correctAnswer: 0, explanation: 'Loaded stretching simultaneously improves mobility and end-range strength.' },
    { type: 'multiple_choice', question: 'How long should an effective mobility routine take?', options: ['5-10 minutes targeting specific limitations', 'No time at all — skip it', '30+ minutes of generic stretching', 'At least one hour'], correctAnswer: 0, explanation: 'Targeted, efficient mobility work produces better results than lengthy generic routines.' },
    { type: 'multiple_choice', question: 'How should you evaluate a mobility drill?', options: ['By social media popularity', 'By how long you hold it', 'By how much it hurts', 'Test-retest: do the drill for 2 minutes then check if target movement improved'], correctAnswer: 3, explanation: 'If a drill does not measurably improve your training movement, try a different one.' },
    { type: 'multiple_choice', question: 'What is the difference between mobility and flexibility?', options: ['Mobility is only about joints', 'They are the same', 'Flexibility is more important', 'Flexibility is passive range of motion; mobility is active range of motion with strength and control'], correctAnswer: 3, explanation: 'Flexibility is range available passively (being stretched); mobility is range you can actively access and control — strength through range is what matters for performance.' },
    { type: 'multiple_choice', question: 'Should static stretching be done before heavy lifting?', options: ['Only before squats', 'It has no effect', 'Always — it prevents injury', 'Generally no — prolonged static stretching can temporarily reduce force production; save it for post-training'], correctAnswer: 3, explanation: 'Static stretching >60 seconds can temporarily reduce force production by 5–10% — use dynamic warm-ups pre-training and static stretching post-training.' },
    { type: 'multiple_choice', question: 'What type of mobility work is most beneficial before training?', options: ['Passive stretching', 'Dynamic movements that take joints through their full range under control — specific to the session\'s exercises', 'Foam rolling only', 'No mobility work needed'], correctAnswer: 1, explanation: 'Dynamic mobility drills specific to the session\'s movements prepare joints, activate stabilisers, and rehearse movement patterns without reducing force production.' },
    { type: 'multiple_choice', question: 'Why is ankle mobility important for squats?', options: ['It is not important', 'Only for front squats', 'Limited ankle dorsiflexion forces excessive forward lean or heel rise, compromising squat depth and mechanics', 'Only for flexibility athletes'], correctAnswer: 2, explanation: 'Restricted ankle dorsiflexion prevents the knee tracking forward appropriately — the body compensates with excessive forward lean, butt wink, or heel rise.' },
    { type: 'multiple_choice', question: 'What is the recommended approach to improving mobility long-term?', options: ['Only stretch when tight', 'Consistent daily practice of targeted mobility work — 5–10 minutes daily is more effective than 30 minutes weekly', 'Stretch aggressively once', 'Mobility cannot be improved'], correctAnswer: 1, explanation: 'Mobility improves with frequency, not duration — 5–10 minutes of daily targeted work produces better long-term results than occasional longer sessions.' },
  
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What is the primary purpose of movement screening?', options: ['To diagnose injuries', 'To predict future injuries precisely', 'To determine 1RM potential', 'To identify gross movement limitations and guide programme design'], correctAnswer: 3, explanation: 'Screens inform exercise selection and identify starting points, not predict injuries.' },
    { type: 'multiple_choice', question: 'What does heels rising during an overhead squat indicate?', options: ['Poor motivation', 'Weak quads', 'Limited ankle dorsiflexion', 'Tight hamstrings'], correctAnswer: 2, explanation: 'Heel rise is a classic sign of insufficient ankle mobility.' },
    { type: 'multiple_choice', question: 'What does research say about movement screens predicting injury?', options: ['They should replace all other assessments', 'Scoring poorly does not reliably predict injury in strength athletes', 'Only the FMS works', 'They perfectly predict all injuries'], correctAnswer: 1, explanation: 'Screens identify limitations but do not reliably predict injury risk.' },
    { type: 'multiple_choice', question: 'Should a screen ever be used to tell someone they cannot train?', options: ['Only for beginners', 'No — use it to determine the most appropriate starting point', 'Only for older adults', 'Yes — safety first'], correctAnswer: 1, explanation: 'Every limitation is the next thing to work on — never a reason to stop training.' },
    { type: 'multiple_choice', question: 'How many angles should you film an overhead squat assessment from?', options: ['No filming needed', 'Only the front', 'One is enough', 'Front, side, and rear — compensations are only visible from certain angles'], correctAnswer: 3, explanation: 'Multiple angles reveal compensations that are invisible from a single viewpoint.' },
    { type: 'multiple_choice', question: 'What is the purpose of movement screening?', options: ['Determining training age', 'Testing maximum strength', 'Identifying movement limitations, asymmetries, and injury risk factors before they cause problems', 'Measuring fitness level'], correctAnswer: 2, explanation: 'Movement screening identifies restrictions, compensations, and asymmetries that may predispose to injury or limit performance — allowing targeted intervention.' },
    { type: 'multiple_choice', question: 'What is the Functional Movement Screen (FMS)?', options: ['A flexibility test only', 'A cardio test', 'A standardised 7-movement assessment that identifies fundamental movement pattern limitations', 'A strength test'], correctAnswer: 2, explanation: 'The FMS uses 7 fundamental movements (deep squat, hurdle step, lunge, shoulder mobility, leg raise, push-up, rotary stability) scored 0–3 to identify limitations.' },
    { type: 'multiple_choice', question: 'What is a movement asymmetry and why does it matter?', options: ['Asymmetry is always normal', 'Only for bilateral exercises', 'A significant difference in movement quality or range between left and right sides — associated with increased injury risk', 'It does not matter'], correctAnswer: 2, explanation: 'Asymmetries greater than 15–20% between sides are associated with increased injury risk — the weaker/less mobile side is more vulnerable under load.' },
    { type: 'multiple_choice', question: 'How often should movement screening be repeated?', options: ['Daily', 'Only after injury', 'Only once ever', 'Every 3–6 months to track changes and evaluate the effectiveness of corrective strategies'], correctAnswer: 3, explanation: 'Periodic re-screening (every 3–6 months) tracks improvement, identifies new issues, and verifies that corrective exercises are working.' },
    { type: 'multiple_choice', question: 'What should you do if a movement screen reveals a painful pattern?', options: ['Refer to a physiotherapist for clinical assessment — pain during screening indicates potential pathology', 'Ignore it and train around it', 'Stretch more aggressively', 'Push through it'], correctAnswer: 0, explanation: 'Pain during movement screening is a red flag for potential pathology — it requires clinical assessment by a qualified practitioner before training interventions.' },
  
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'Why is gradual progression essential for joint health?', options: ['Muscles adapt in weeks but tendons and cartilage take months to years', 'Joints cannot adapt at all', 'It is only important for beginners', 'To avoid getting too strong'], correctAnswer: 0, explanation: 'The adaptation mismatch between tissues makes gradual loading essential.' },
    { type: 'multiple_choice', question: 'How long do tendons need to recover between heavy loading sessions?', options: ['48-72 hours', 'One week', '12 hours', '24 hours'], correctAnswer: 0, explanation: 'Tendon tissue turnover is slower than muscle, requiring 48-72 hours between heavy sessions.' },
    { type: 'multiple_choice', question: 'What type of loading stimulates tendon remodelling with minimal risk?', options: ['Isometric holds at moderate intensity', 'Maximal dynamic lifts', 'Ballistic throws', 'Plyometric jumps'], correctAnswer: 0, explanation: 'Isometric loading provides tendon stimulus with minimal risk.' },
    { type: 'multiple_choice', question: 'What lifestyle factor is most critical for tissue repair?', options: ['Sleep — 7-9 hours for growth hormone release', 'Compression garments', 'Supplements', 'Saunas'], correctAnswer: 0, explanation: 'Growth hormone released during deep sleep drives tendon and cartilage remodelling.' },
    { type: 'multiple_choice', question: 'What is the goal of training for joint longevity?', options: ['Avoiding all heavy weights', 'Still training productively in 30 years', 'Only training with machines', 'Maximum strength now regardless of consequences'], correctAnswer: 1, explanation: 'Long-term joint health means decades of productive training, not just short-term gains.' },
    { type: 'multiple_choice', question: 'What is the most important factor for training longevity?', options: ['Using the heaviest weights possible', 'Training through pain', 'Maximum intensity always', 'Consistent injury prevention through intelligent load management, recovery, and listening to your body'], correctAnswer: 3, explanation: 'Training longevity requires smart load management — the lifters who train for decades are those who manage fatigue, prevent injuries, and prioritise long-term consistency.' },
    { type: 'multiple_choice', question: 'How does tendon adaptation differ from muscle adaptation?', options: ['Tendons do not adapt', 'Tendons adapt much more slowly than muscles — taking weeks to months longer, which can create a strength-structure mismatch', 'Tendons adapt faster', 'They adapt at the same rate'], correctAnswer: 1, explanation: 'Muscles can strengthen in weeks; tendons take months — rapid strength gains without tendon adaptation create vulnerability to tendinopathy and rupture.' },
    { type: 'multiple_choice', question: 'Why is training variation important for joint health?', options: ['Only for advanced lifters', 'Repeated identical stress on the same joint surfaces causes wear — variation distributes load across different angles and tissues', 'Variation weakens joints', 'It is not important'], correctAnswer: 1, explanation: 'The same movement pattern with the same load thousands of times creates cumulative tissue stress — variation distributes forces across different joint surfaces.' },
    { type: 'multiple_choice', question: 'What role does nutrition play in joint health?', options: ['Only calcium matters', 'None', 'Adequate protein, omega-3 fats, vitamin C, collagen, and hydration all support cartilage maintenance and repair', 'Supplements replace the need for food'], correctAnswer: 2, explanation: 'Joint health nutrition: omega-3s reduce inflammation, vitamin C supports collagen synthesis, protein provides building blocks, and hydration maintains synovial fluid.' },
    { type: 'multiple_choice', question: 'What is the concept of minimum effective dose in training?', options: ['Maximum volume always', 'The least amount of training stimulus needed to produce the desired adaptation — doing more is not always better', 'There is no minimum', 'Always do as much as possible'], correctAnswer: 1, explanation: 'Minimum effective dose maximises the stimulus-to-fatigue ratio — especially important for long-term joint health, as excess volume accumulates wear without proportional benefit.' },
  
  ]),
];