import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the three foundations of a coaching philosophy?', options: ['Speed, strength, power', 'Evidence-based practice, practical experience, and values alignment', 'Money, fame, success', 'Education, certification, experience'], correctAnswer: 1, explanation: 'A philosophy integrates evidence, experience, and values.' },
    { type: 'multiple_choice', question: 'What is the primary ethical obligation of a fitness professional?', options: ['Making money', 'Looking good', 'Do no harm', 'Being popular'], correctAnswer: 2, explanation: 'Never prescribing training that exceeds capacity or ignores wellbeing.' },
    { type: 'multiple_choice', question: 'What does scope of practice mean?', options: ['Training as many people as possible', 'Knowing where your competence ends and referring appropriately', 'Only training beginners', 'Avoiding all risk'], correctAnswer: 1, explanation: 'Working within qualifications protects everyone involved.' },
    { type: 'multiple_choice', question: 'How often should you revisit your coaching philosophy?', options: ['Never — once written it is final', 'Annually — it should evolve as you gain experience', 'Every day', 'Only when forced to'], correctAnswer: 1, explanation: 'A philosophy that never changes suggests you have stopped learning.' },
    { type: 'multiple_choice', question: 'What distinguishes a coach with a philosophy from one without?', options: ['Revenue', 'The ability to guide through any situation based on deeper principles, not just templates', 'Certification level', 'Number of clients'], correctAnswer: 1, explanation: 'Philosophy-driven coaches lead; technicians follow templates.' },
    { type: 'multiple_choice', question: 'What is a coaching philosophy?', options: ['A business plan', 'Your core beliefs about training, athlete development, and the coach-athlete relationship that guide all decisions', 'A marketing statement', 'A training programme'], correctAnswer: 1, explanation: 'A coaching philosophy defines your fundamental beliefs about how athletes develop, what matters most, and how you interact — it guides decisions when the textbook does not apply.' },
    { type: 'multiple_choice', question: 'Why is ethical practice important in coaching?', options: ['Only for legal reasons', 'Trust is the foundation of effective coaching — ethical practice protects athletes and maintains the professional relationship', 'Ethics do not affect results', 'Only for team sports'], correctAnswer: 1, explanation: 'Ethical practice (honesty, confidentiality, appropriate boundaries, duty of care) builds the trust without which no coaching relationship can be effective.' },
    { type: 'multiple_choice', question: 'What is duty of care in a coaching context?', options: ['Optional goodwill', 'The legal and moral obligation to ensure athlete safety, wellbeing, and appropriate support during training', 'Only applies to children', 'A marketing term'], correctAnswer: 1, explanation: 'Duty of care is both legal and moral — you are responsible for providing a safe training environment, appropriate programming, and recognising when to refer.' },
    { type: 'multiple_choice', question: 'What are appropriate professional boundaries in coaching?', options: ['No boundaries needed with adults', 'Clear limits on the coaching relationship including physical contact, communication, social boundaries, and scope of practice', 'Boundaries create distance', 'Only for youth coaches'], correctAnswer: 1, explanation: 'Professional boundaries protect both coach and athlete — clear expectations around communication, physical contact, social media, and scope of practice prevent misunderstandings.' },
    { type: 'multiple_choice', question: 'What should you do if an athlete asks for nutrition advice beyond your scope?', options: ['Give advice anyway', 'Acknowledge their question, provide general healthy eating guidance, and refer to a qualified nutrition professional', 'Refuse to discuss nutrition at all', 'Pretend to be qualified'], correctAnswer: 1, explanation: 'Working within scope of practice: acknowledge the question, provide what you are qualified to offer, and refer to the appropriate professional — this builds credibility.' },
  
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'Which type of cueing produces better movement outcomes?', options: ['Internal cues focusing on body parts', 'External cues focusing on movement effects', 'No cueing at all', 'Shouting louder'], correctAnswer: 1, explanation: 'External cues allow natural self-organisation of movement patterns.' },
    { type: 'multiple_choice', question: 'What are the three stages of motor learning?', options: ['Easy, medium, hard', 'Cognitive, associative, autonomous', 'Beginner, intermediate, advanced', 'Learning, practising, competing'], correctAnswer: 1, explanation: 'Each stage requires different coaching approaches.' },
    { type: 'multiple_choice', question: 'What happens when you over-coach an autonomous learner?', options: ['They improve faster', 'Excessive coaching can disrupt their automatic movement patterns', 'Nothing changes', 'They become dependent'], correctAnswer: 1, explanation: 'Advanced performers move best with minimal conscious interference.' },
    { type: 'multiple_choice', question: 'How often should you give feedback for best long-term learning?', options: ['Every single rep', 'Every 3rd to 5th rep — reduced frequency builds self-correction ability', 'Only once per session', 'Never'], correctAnswer: 1, explanation: 'Reduced feedback frequency forces learners to develop error detection skills.' },
    { type: 'multiple_choice', question: 'Convert this internal cue to external: Extend your knees', options: ['Push harder', 'Drive the floor away', 'Straighten your legs more', 'Use your quads'], correctAnswer: 1, explanation: 'External cues direct attention to movement outcomes, not body mechanics.' },
    { type: 'multiple_choice', question: 'What is external cueing?', options: ['Coaching from outside the gym', 'Directing an athlete\'s attention to the effect of their movement on the environment rather than their body', 'A type of exercise', 'Only for beginners'], correctAnswer: 1, explanation: 'External cues ("push the floor away" vs "extend your legs") consistently produce better motor learning outcomes than internal cues in research.' },
    { type: 'multiple_choice', question: 'Why is external cueing generally more effective than internal cueing?', options: ['It is not more effective', 'External focus promotes automatic motor control; internal focus causes conscious interference ("paralysis by analysis")', 'Internal cues are always better', 'Only for advanced athletes'], correctAnswer: 1, explanation: 'External cueing allows the motor system to self-organise movement naturally — internal cueing disrupts automatic processes by creating conscious interference.' },
    { type: 'multiple_choice', question: 'What is a movement demonstration and when should you use one?', options: ['Never demonstrate', 'Showing the complete movement before cueing details — visual learning is the fastest way to convey movement patterns', 'Only demonstrate incorrect form', 'Only for children'], correctAnswer: 1, explanation: 'Visual demonstration provides a mental model before verbal cueing — most people learn movements faster from seeing them than from hearing descriptions.' },
    { type: 'multiple_choice', question: 'What is the constraints-led approach to teaching movement?', options: ['Restricting athletes', 'Manipulating task, environmental, or individual constraints to guide athletes toward discovering solutions themselves', 'Giving detailed instructions', 'A rehabilitation method'], correctAnswer: 1, explanation: 'The constraints-led approach changes the environment (narrower stance, tempo requirement, implement variation) to guide movement discovery — producing more robust learning.' },
    { type: 'multiple_choice', question: 'What is the optimal number of coaching cues to give at once?', options: ['As many as possible', 'One — maybe two — at a time; the athlete can only process one correction per set', 'Five or more', 'Zero — let them figure it out'], correctAnswer: 1, explanation: 'Attentional capacity is limited — one clear cue per set produces better outcomes than overwhelming the athlete with multiple corrections simultaneously.' },
  
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is the foundation of effective coaching communication?', options: ['Giving great advice', 'Active listening — fully concentrating on what someone is saying', 'Talking confidently', 'Having all the answers'], correctAnswer: 1, explanation: 'Clients who feel heard develop more trust and show better compliance.' },
    { type: 'multiple_choice', question: 'Why do most people quit fitness programmes?', options: ['Bad programmes', 'They feel unsupported, unheard, or unrealistically judged', 'Programmes are too easy', 'They run out of money'], correctAnswer: 1, explanation: 'Communication and expectation management drive retention more than programming.' },
    { type: 'multiple_choice', question: 'What is the best approach to difficult conversations about non-compliance?', options: ['Blame the person', 'Address the behaviour not the person, using specific observations and offering support', 'Ignore the issue', 'Threaten to stop coaching them'], correctAnswer: 1, explanation: 'Non-judgemental, specific observations open dialogue rather than triggering defensiveness.' },
    { type: 'multiple_choice', question: 'What should you set from the first consultation?', options: ['Unrealistic goals to motivate', 'Realistic expectations with honest timelines', 'No expectations', 'Only short-term goals'], correctAnswer: 1, explanation: 'Unrealistic expectations are the primary reason people quit.' },
    { type: 'multiple_choice', question: 'How should progress be celebrated effectively?', options: ['Only celebrate outcome metrics like weight loss', 'Reframe success around behaviour metrics: sessions attended, nutrition compliance', 'Wait until goals are fully achieved', 'Compare them to other people'], correctAnswer: 1, explanation: 'Process-focused celebration sustains motivation regardless of outcome fluctuations.' },
    { type: 'multiple_choice', question: 'What is the most important communication skill for a coach?', options: ['Talking loudly', 'Active listening — understanding what the athlete is actually saying and feeling before responding', 'Giving more instructions', 'Using technical language'], correctAnswer: 1, explanation: 'Active listening (full attention, reflecting, not interrupting) is the foundation — you cannot coach effectively if you do not understand the athlete\'s perspective.' },
    { type: 'multiple_choice', question: 'How should you deliver negative feedback to an athlete?', options: ['Avoid all negative feedback', 'Use a sandwich approach: acknowledge effort, provide specific constructive feedback, end with encouragement', 'Be blunt and critical', 'Only give negative feedback in writing'], correctAnswer: 1, explanation: 'Effective feedback is specific, timely, and balanced — acknowledging effort before constructive correction maintains motivation while driving improvement.' },
    { type: 'multiple_choice', question: 'How should expectations be managed in a training environment?', options: ['Promise rapid results', 'Set realistic timelines from the start, celebrate small wins, and educate about the process of long-term development', 'Under-promise everything', 'Avoid discussing timelines'], correctAnswer: 1, explanation: 'Managing expectations prevents disappointment — realistic timelines, process-focused goals, and celebrating progress build trust and long-term commitment.' },
    { type: 'multiple_choice', question: 'What should you do when an athlete disagrees with your programming?', options: ['Ignore their opinion', 'Listen to their concerns, explain your rationale, and collaboratively find a solution that maintains training effectiveness', 'Change everything they want', 'Drop them from the programme'], correctAnswer: 1, explanation: 'Collaborative coaching: listen to concerns, explain the reasoning, and find solutions together — athletes who understand and buy into the programme are more adherent.' },
    { type: 'multiple_choice', question: 'What is psychological safety in a coaching environment?', options: ['Being soft on athletes', 'An environment where athletes feel safe to ask questions, make mistakes, and express concerns without judgement', 'A weakness', 'Only relevant in therapy'], correctAnswer: 1, explanation: 'Psychological safety enables athletes to attempt new skills, report injuries honestly, and communicate openly — all essential for effective development.' },
  
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'Is resistance training safe for adolescents?', options: ['No — it stunts growth', 'Dangerous at any age', 'Yes — it is safe and beneficial when properly supervised', 'Only after age 18'], correctAnswer: 2, explanation: 'The growth-stunting myth has been comprehensively debunked by research.' },
    { type: 'multiple_choice', question: 'What is the primary training goal for older adults?', options: ['Aesthetic improvement', 'Compound movements that build functional strength for daily life independence', 'Weight loss only', 'Flexibility only'], correctAnswer: 1, explanation: 'Resistance training combats sarcopenia and reduces fall risk.' },
    { type: 'multiple_choice', question: 'When should medical clearance be obtained before training?', options: ['Never', 'Before training anyone with a diagnosed chronic condition', 'Only for athletes', 'Only if they are over 70'], correctAnswer: 1, explanation: 'Medical clearance protects everyone when chronic conditions are present.' },
    { type: 'multiple_choice', question: 'What should never be assumed about older adults in training?', options: ['That they need special equipment', 'That they cannot squat, deadlift, or press — never assume limitation', 'That they are motivated', 'That they are healthy'], correctAnswer: 1, explanation: 'Many older adults can train with excellent form — do not patronise.' },
    { type: 'multiple_choice', question: 'What is the primary goal for adolescent training?', options: ['Maximum strength gains', 'Competition preparation', 'Developing a positive relationship with exercise while building skills', 'Bodybuilding'], correctAnswer: 2, explanation: 'Enjoyment and skill development should be prioritised over intensity and load.' },
    { type: 'multiple_choice', question: 'What adaptations are needed when programming for older adults?', options: ['They should not train', 'Longer warm-ups, more joint-friendly exercises, gradual progression, emphasis on balance and bone density', 'Same programme as young athletes', 'Only cardio'], correctAnswer: 1, explanation: 'Older adults benefit enormously from strength training but need longer warm-ups, more recovery, emphasis on balance/bone density, and awareness of joint limitations.' },
    { type: 'multiple_choice', question: 'What considerations exist for training pregnant women?', options: ['No training during pregnancy', 'Avoid supine positions after first trimester, moderate intensity, avoid contact sports, and adjust for changing centre of gravity', 'Train exactly the same', 'Only walk during pregnancy'], correctAnswer: 1, explanation: 'Pregnant women can and should train — with modifications: avoid supine positions after 16 weeks, moderate intensity, no contact risk, and awareness of relaxin effects on joint stability.' },
    { type: 'multiple_choice', question: 'What is the key principle for training youth athletes?', options: ['Maximum intensity from age 10', 'Develop a broad movement base before specialisation — technical competence and fun should precede intensity', 'Same as adult programming', 'Only sport practice'], correctAnswer: 1, explanation: 'Youth development prioritises: fundamental movement skills, multi-sport participation, technical competence, and enjoyment — early specialisation and high intensity increase burnout and injury.' },
    { type: 'multiple_choice', question: 'What modifications are needed for training people with disabilities?', options: ['They should not train', 'Individualised adaptations based on their specific needs — focusing on what they CAN do rather than limitations', 'One programme fits all', 'Only rehabilitation exercises'], correctAnswer: 1, explanation: 'Training for people with disabilities requires individual assessment and creative adaptation — focusing on capabilities, not limitations, while addressing specific needs.' },
    { type: 'multiple_choice', question: 'What is important when programming for someone returning to training after a long break?', options: ['Start where they left off', 'Begin at a significantly reduced level (40–50% of previous capacity) and progress conservatively to allow tissue re-adaptation', 'Maximum intensity from day one', 'Only stretching for the first month'], correctAnswer: 1, explanation: 'Detraining means tissues have adapted to reduced demand — starting at 40–50% of previous capacity and progressing 10% per week prevents the excessive soreness and injury risk of overzealous returns.' },
  
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'Why do most personal trainers leave the industry within two years?', options: ['Lack of fitness knowledge', 'Lack of business skills — pricing, marketing, and member retention', 'The work is too physical', 'Too much competition'], correctAnswer: 1, explanation: 'Understanding this helps you evaluate the fitness industry — technical competence alone does not make a sustainable business.' },
    { type: 'multiple_choice', question: 'Why do budget gyms remain profitable even when most members stop attending?', options: ['They have great equipment', 'Their business model relies on members paying but NOT attending — if everyone showed up, the gym would be overcrowded', 'They invest in marketing', 'They sell supplements'], correctAnswer: 1, explanation: 'Understanding gym business models helps you make smarter decisions as a consumer.' },
    { type: 'multiple_choice', question: 'What three factors keep people committed to a fitness service long-term?', options: ['Price, location, equipment', 'Seeing measurable progress, feeling genuinely supported, and enjoying the process', 'Marketing, branding, social media', 'Discounts, promotions, free sessions'], correctAnswer: 1, explanation: 'These three factors — results, relationships, and experience — drive long-term adherence in any fitness setting.' },
    { type: 'multiple_choice', question: 'Which fitness business model is most scalable?', options: ['One-to-one personal training', 'Online coaching — it removes geographic and time limitations', 'Group classes only', 'Selling supplements'], correctAnswer: 1, explanation: 'Understanding scalability helps you evaluate the quality and incentives of different fitness services.' },
    { type: 'multiple_choice', question: 'What is the biggest predictor of long-term fitness results?', options: ['The programme itself', 'Adherence — sticking with it consistently over time', 'The gym or equipment used', 'How much you pay'], correctAnswer: 1, explanation: 'Research consistently shows that consistency trumps programme design — the best programme is one you actually follow.' },
    { type: 'multiple_choice', question: 'When evaluating a fitness service, what three questions should you ask?', options: ['What do they charge?', 'Do they measure progress objectively, adapt to individual needs, and create an environment you want to return to?', 'How many followers do they have?', 'What celebrities use them?'], correctAnswer: 1, explanation: 'These three questions help you cut through marketing and identify genuine value in any fitness service.' },
    { type: 'multiple_choice', question: 'Why does it cost businesses 5-7 times more to acquire a new customer than retain an existing one?', options: ['It does not', 'Marketing, advertising, and trust-building with new customers is expensive — existing customers already trust you and refer others', 'Only applies to gyms', 'This is a myth'], correctAnswer: 1, explanation: 'This principle explains why the best fitness services focus on delivering results rather than aggressive marketing.' },
    { type: 'multiple_choice', question: 'What should you look for in a personal trainer or coach?', options: ['The cheapest price', 'Qualifications, evidence of results, communication skills, and alignment with your goals and values', 'The biggest social media following', 'The most impressive physique'], correctAnswer: 1, explanation: 'Evaluating coaches on substance rather than marketing helps you invest in genuine quality.' },
    { type: 'multiple_choice', question: 'Why is understanding business models useful even if you are not a fitness professional?', options: ['It is not useful', 'It helps you evaluate what you are paying for, avoid poor-value services, and understand industry incentives', 'Only for entrepreneurs', 'Only for investors'], correctAnswer: 1, explanation: 'An informed consumer makes better decisions — understanding how fitness businesses make money reveals their true incentives.' },
    { type: 'multiple_choice', question: 'What is the most reliable way to find a good coach or trainer?', options: ['Social media following', 'Referrals from people who have achieved measurable results, verified qualifications, and a clear evidence-based approach', 'Price — more expensive is always better', 'Location convenience'], correctAnswer: 1, explanation: 'Real results from real people are the strongest indicator of quality — not marketing, follower counts, or price tags.' },
  
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Why is staying current with fitness science an ethical responsibility?', options: ['It is required by law', 'People rely on fitness guidance based on current evidence, not outdated methods — using disproven approaches can cause harm', 'It makes you more money', 'It is not — it is optional'], correctAnswer: 1, explanation: 'Whether you are guiding yourself or others, using outdated methods when better evidence exists is irresponsible.' },
    { type: 'multiple_choice', question: 'What is at the top of the evidence hierarchy?', options: ['Expert opinion', 'Case studies', 'A single randomised controlled trial', 'Systematic reviews and meta-analyses'], correctAnswer: 3, explanation: 'Systematic reviews synthesise findings from multiple studies for strongest conclusions.' },
    { type: 'multiple_choice', question: 'Why should supplement company-funded research be viewed carefully?', options: ['It is always wrong', 'Studies with conflicts of interest are more likely to produce favourable results for funders', 'It is always perfect', 'Only university research matters'], correctAnswer: 1, explanation: 'Funding conflicts can bias study design, interpretation, and publication.' },
    { type: 'multiple_choice', question: 'What should you do before changing practice based on a new study?', options: ['Change immediately', 'Wait for replication across multiple studies', 'Ignore all new research', 'Ask social media'], correctAnswer: 1, explanation: 'A single study is a data point; consistent findings across multiple studies are evidence.' },
    { type: 'multiple_choice', question: 'What is the practical difference between statistical and practical significance?', options: ['They are the same', 'A result can be statistically significant but too small to matter in real-world practice', 'Practical significance is more important than statistical', 'Only statistical significance matters'], correctAnswer: 1, explanation: 'Always ask how big the actual difference is — small effects may be meaningless in practice.' },
    { type: 'multiple_choice', question: 'Why do professional bodies require ongoing learning (CPD) for fitness professionals?', options: ['It is not required', 'Exercise science evolves rapidly — ongoing learning ensures practice stays current, competent, and evidence-based', 'Only for new coaches', 'CPD is unnecessary after certification'], correctAnswer: 1, explanation: 'This is why the best fitness professionals and self-directed learners never stop learning — the science evolves every year.' },
    { type: 'multiple_choice', question: 'What counts as valid CPD?', options: ['Only formal courses', 'Courses, workshops, mentoring, reading peer-reviewed research, attending conferences, and reflective practice', 'Only university degrees', 'Social media learning only'], correctAnswer: 1, explanation: 'CPD includes formal (courses, workshops) and informal (reading research, mentoring, reflective practice) learning — the key is deliberate professional growth.' },
    { type: 'multiple_choice', question: 'How should you record CPD activities?', options: ['No records needed', 'Maintain a CPD log documenting date, activity, provider, what was learned, and how it will be applied in practice', 'Only keep certificates', 'Memory is sufficient'], correctAnswer: 1, explanation: 'A structured CPD log provides evidence for registration bodies, helps identify learning gaps, and demonstrates professional commitment..' },
    { type: 'multiple_choice', question: 'What is a reflective journal in coaching?', options: ['A diary', 'A structured record of coaching experiences, what worked, what did not, and how you will adjust your practice', 'A workout log', 'A session log'], correctAnswer: 1, explanation: 'Reflective journaling turns experience into expertise — systematically recording what happened, what you learned, and how you will apply it drives continuous improvement.' },
    { type: 'multiple_choice', question: 'How much structured learning per year do professional bodies typically require of fitness professionals?', options: ['None', 'A minimum of 20–30 hours per year — combining courses, reading, and reflective practice', '1 hour per year', '200 hours per year'], correctAnswer: 1, explanation: 'Knowing this standard helps you evaluate whether your own learning rate matches professional expectations — and whether a coach you hire is staying current.' },
  
  ]),
  cq(4, 7, [
    { type: 'multiple_choice', question: 'What are the three pillars of evidence-based practice?', options: ['Research, research, research', 'Scientific evidence, professional experience, and individual values/preferences', 'Textbooks, courses, certifications', 'Training, nutrition, recovery'], correctAnswer: 1, explanation: 'All three must inform decisions — none alone is sufficient.' },
    { type: 'multiple_choice', question: 'What happens when individual preferences are ignored?', options: ['Nothing', 'Programmes look great on paper but fail because the person will not follow them', 'Results improve', 'Clients train harder'], correctAnswer: 1, explanation: 'A programme nobody follows is worse than an imperfect one they actually stick to.' },
    { type: 'multiple_choice', question: 'When your experience contradicts research, what should you consider?', options: ['Your experience is always right', 'Research is always right', 'Is your experience based on representative samples, or memorable cases? Does the research match your context?', 'Flip a coin'], correctAnswer: 2, explanation: 'Mature practitioners hold both perspectives and test systematically.' },
    { type: 'multiple_choice', question: 'What determines whether research findings apply to your situation?', options: ['The journal it was published in', "Whether the study population and context match your specific situation", 'How famous the researchers are', 'How recently it was published'], correctAnswer: 1, explanation: 'Population match and context relevance determine practical applicability.' },
    { type: 'multiple_choice', question: 'What makes evidence-based practice different from just following studies?', options: ['Nothing', 'EBP integrates evidence with experience and individual needs, not blind adherence', 'EBP ignores research', 'EBP only uses the newest studies'], correctAnswer: 1, explanation: 'Integration of all three pillars produces the best coaching decisions.' },
    { type: 'multiple_choice', question: 'What does evidence-based practice mean in coaching?', options: ['Only using peer-reviewed studies', 'Integrating the best available research with professional expertise and individual individual values/preferences', 'Ignoring science and using experience only', 'Following every new study exactly'], correctAnswer: 1, explanation: 'Evidence-based practice combines three pillars: best available research + professional experience/expertise + individual context and preferences.' },
    { type: 'multiple_choice', question: 'Why should you not change your practice based on a single study?', options: ['Single studies are always wrong', 'Individual studies can have methodological flaws, small samples, or be outliers — systematic reviews of multiple studies are more reliable', 'Always follow new studies immediately', 'No studies are relevant to coaching'], correctAnswer: 1, explanation: 'Single studies can be misleading — small samples, poor methodology, or unique populations. Multiple studies (systematic reviews) provide more reliable evidence for practice changes.' },
    { type: 'multiple_choice', question: 'What is confirmation bias in coaching?', options: ['A positive trait', 'The tendency to seek and remember evidence that supports your existing beliefs while ignoring contradicting evidence', 'Being confident in your methods', 'A research method'], correctAnswer: 1, explanation: 'Confirmation bias leads coaches to cherry-pick research supporting their methods — actively seeking contradicting evidence and being willing to update beliefs is essential.' },
    { type: 'multiple_choice', question: 'How should anecdotal evidence be weighted against research?', options: ['Anecdotes are stronger than research', 'Anecdotes generate hypotheses; research tests them — personal experience is valuable but can be misleading without systematic evidence', 'They are equally valid', 'Anecdotes should be ignored completely'], correctAnswer: 1, explanation: 'Anecdotal evidence ("it worked for me/my clients") is useful for generating ideas but is not proof — survivorship bias, placebo effects, and confounding variables limit its reliability.' },
    { type: 'multiple_choice', question: 'What is the Dunning-Kruger effect and how does it affect coaches?', options: ['A training programme', 'The tendency for those with little knowledge to overestimate their competence, while experts tend to underestimate theirs', 'A stretching technique', 'A positive cognitive bias'], correctAnswer: 1, explanation: 'New coaches often overestimate their knowledge; experienced coaches recognise how much they do not know — awareness of this bias promotes humility and continued learning.' },
  
  ]),
  cq(4, 8, [
    { type: 'multiple_choice', question: 'What makes a great coach beyond knowledge?', options: ['Certifications alone', 'The ability to apply knowledge to real people with empathy, adaptability, and integrity', 'Physical fitness', 'Social media following'], correctAnswer: 1, explanation: 'Knowledge is necessary but insufficient — application with human skills defines greatness.' },
    { type: 'multiple_choice', question: 'Why is focusing on a specific fitness area more effective than trying to master everything?', options: ['To limit yourself', 'Depth in a specific area creates more expertise and better results than surface-level knowledge across everything', 'It is not important', 'Specialisation is overrated'], correctAnswer: 1, explanation: 'This applies to your own training and to evaluating coaches — depth beats breadth.' },
    { type: 'multiple_choice', question: 'What does the Unbreakable standard represent?', options: ['Being physically unbreakable', 'Knowledge in service of others, applied with integrity, refined through lifelong practice', 'Never showing weakness', 'Extreme training'], correctAnswer: 1, explanation: 'The standard is about ethical service and continuous improvement, not physical invincibility.' },
    { type: 'multiple_choice', question: 'How does fitness expertise develop over a lifetime?', options: ['Peaks at 25 and declines', 'Through decades of practice, reflection, and genuine commitment — producing wisdom that courses alone cannot teach', 'Only through more certifications', 'By copying successful athletes'], correctAnswer: 1, explanation: 'Experience and reflection produce wisdom that formal education cannot replicate — this is true for athletes, coaches, and lifelong learners alike.' },
    { type: 'multiple_choice', question: 'What is the lifelong commitment that the Unbreakable standard represents?', options: ['Physical perfection', 'Learning, growing, and showing up — fitness is a practice, not a destination', 'Winning competitions', 'Becoming famous'], correctAnswer: 1, explanation: 'Fitness is a lifelong practice of improvement, not a destination to reach.' },
    { type: 'multiple_choice', question: 'Why is having a specific fitness focus more valuable than a generic approach?', options: ['Generic approaches work for everyone', 'Depth in a specific area (e.g., strength for over-40s, running performance, injury prevention) produces deeper expertise and better results', 'Focus limits your options', 'Only generalists succeed'], correctAnswer: 1, explanation: 'Whether training yourself or helping others, depth of knowledge in a specific area produces better results than shallow knowledge across everything.' },
    { type: 'multiple_choice', question: 'Why is authenticity important in fitness leadership?', options: ['Authenticity is overrated', 'Genuine leaders build deeper trust, attract like-minded people, and maintain motivation long-term', 'Only results matter', 'Copy successful people exactly'], correctAnswer: 1, explanation: 'Being genuinely yourself — in your training approach, your values, and how you help others — builds trust and sustains long-term commitment.' },
    { type: 'multiple_choice', question: 'Why is learning from mentors valuable in fitness development?', options: ['It is not important', 'Learning from experienced people accelerates development, provides perspective, and prevents common mistakes', 'Only for beginners', 'Books are sufficient'], correctAnswer: 1, explanation: 'Mentoring provides contextualised learning that books cannot — learning from someone who has navigated real challenges accelerates development dramatically.' },
    { type: 'multiple_choice', question: 'What separates knowledge from wisdom in fitness?', options: ['Nothing — they are the same', 'Wisdom comes from applying knowledge to real situations over time, learning from mistakes, and refining your approach through experience', 'Wisdom is innate', 'More certifications equal more wisdom'], correctAnswer: 1, explanation: 'Knowledge can be taught; wisdom must be earned through years of practice, reflection, and genuine engagement with the work.' },
    { type: 'multiple_choice', question: 'What does "the practice is the work of a lifetime" mean?', options: ['You should never stop exercising', 'Fitness mastery is a continuous journey of learning, applying, reflecting, and growing — there is no finish line', 'Train harder every year', 'Only professionals need lifelong practice'], correctAnswer: 1, explanation: 'The Unbreakable philosophy: the foundation is built through education, but the real work — and the real growth — happens over a lifetime of consistent practice.' },
  
  ]),
];