import type { UnitAssessment } from '../types';

export const level4Unit4Assessment: UnitAssessment = {
  unitNumber: 4,
  title: 'Leadership, Communication & Lifelong Learning — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most effective type of cueing for movement performance?', options: ['Internal cues', 'External cues focusing on movement effects', 'No cueing', 'Verbal punishment'], correctAnswer: 1, explanation: 'External cues allow natural self-organisation of efficient movement.' },
    { type: 'multiple_choice', question: 'What keeps people committed to fitness more than the programme itself?', options: ['Price', 'Feeling supported, heard, and genuinely cared about', 'Equipment quality', 'Location'], correctAnswer: 1, explanation: 'People quit because they feel unsupported, not because of bad programmes.' },
    { type: 'multiple_choice', question: 'What is the primary ethical obligation of a fitness professional?', options: ['Revenue generation', 'Do no harm', 'Client acquisition', 'Social media presence'], correctAnswer: 1, explanation: 'Safety and wellbeing must always be the first priority.' },
    { type: 'multiple_choice', question: 'When should a coach refer someone to a specialist?', options: ['Never — coaches can handle everything', 'When the situation exceeds their scope of practice or qualifications', 'Only when asked', 'Only for serious injuries'], correctAnswer: 1, explanation: 'Recognising scope of practice is a professional strength, not a weakness.' },
    { type: 'multiple_choice', question: 'What is the best approach to evidence-based practice?', options: ['Follow research blindly', 'Integrate scientific evidence with practical experience and individual preferences', 'Ignore research — experience is everything', 'Only use the newest studies'], correctAnswer: 1, explanation: 'EBP combines three pillars for the best training decisions.' },
    { type: 'multiple_choice', question: 'What is the myth about resistance training and adolescents?', options: ['It is too easy for them', 'That it stunts growth — which has been comprehensively debunked', 'That it is too expensive', 'That they cannot learn technique'], correctAnswer: 1, explanation: 'Research supports safe, supervised resistance training for adolescents.' },
    { type: 'multiple_choice', question: 'Which fitness business model is most scalable?', options: ['One-to-one training only', 'Online coaching — it removes geographic and time constraints', 'Group classes only', 'Selling supplements'], correctAnswer: 1, explanation: 'Understanding business models helps you evaluate fitness services as an informed consumer.' },
    { type: 'multiple_choice', question: 'What characterises the hierarchy of evidence?', options: ['All evidence is equal', 'Systematic reviews > RCTs > cohort studies > case studies > expert opinion', 'Expert opinion is highest', 'Case studies are most reliable'], correctAnswer: 1, explanation: 'Higher-level evidence provides more confidence in findings.' },
    { type: 'multiple_choice', question: 'How should feedback frequency change as a learner becomes more skilled?', options: ['Increase constantly', 'Decrease — reduced feedback builds self-correction ability', 'Stay the same', 'Stop entirely'], correctAnswer: 1, explanation: 'Advanced learners benefit from less frequent feedback to develop independence.' },
    { type: 'multiple_choice', question: 'What is the best way to evaluate if a new training method works?', options: ['Try it once', 'Test it systematically and let measurable outcomes guide your decision', 'Ask social media', 'Assume it works because a study supports it'], correctAnswer: 1, explanation: 'Systematic testing with measurable outcomes provides the most relevant personal evidence.' },
    { type: 'multiple_choice', question: 'Where does the most meaningful fitness impact often happen?', options: ['Training competitive athletes exclusively', 'Helping anyone — from the 65-year-old gaining independence to the teenager finding confidence', 'Only working with genetically gifted people', 'Focusing on aesthetics only'], correctAnswer: 1, explanation: 'Transformations in quality of life and confidence matter more than any personal record.' },
    { type: 'multiple_choice', question: 'What is the Unbreakable standard for professional practice?', options: ['Physical invincibility', 'Knowledge in service of others, applied with integrity, refined through lifelong learning', 'Never showing weakness', 'Maximum revenue'], correctAnswer: 1, explanation: 'The standard combines ethical service with continuous professional growth.' },
  ],
};