import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the three foundations of a coaching philosophy?', options: ['Speed, strength, power', 'Evidence-based practice, practical experience, and values alignment', 'Money, fame, success', 'Education, certification, experience'], correctAnswer: 1, explanation: 'A philosophy integrates evidence, experience, and values.' },
    { type: 'multiple_choice', question: 'What is the primary ethical obligation of a fitness professional?', options: ['Making money', 'Looking good', 'Do no harm', 'Being popular'], correctAnswer: 2, explanation: 'Never prescribing training that exceeds capacity or ignores wellbeing.' },
    { type: 'multiple_choice', question: 'What does scope of practice mean?', options: ['Training as many people as possible', 'Knowing where your competence ends and referring appropriately', 'Only training beginners', 'Avoiding all risk'], correctAnswer: 1, explanation: 'Working within your qualifications protects both you and your clients.' },
    { type: 'multiple_choice', question: 'How often should you revisit your coaching philosophy?', options: ['Never — once written it is final', 'Annually — it should evolve as you gain experience', 'Every day', 'Only when forced to'], correctAnswer: 1, explanation: 'A philosophy that never changes suggests you have stopped learning.' },
    { type: 'multiple_choice', question: 'What distinguishes a coach with a philosophy from one without?', options: ['Revenue', 'The ability to guide through any situation based on deeper principles, not just templates', 'Certification level', 'Number of clients'], correctAnswer: 1, explanation: 'Philosophy-driven coaches lead; technicians follow templates.' },
    { type: 'multiple_choice', question: 'What is a coaching philosophy?', options: ['A business plan', 'Your core beliefs about training, athlete development, and the coach-athlete relationship that guide all decisions', 'A marketing statement', 'A training programme'], correctAnswer: 1, explanation: 'A coaching philosophy defines your fundamental beliefs about how athletes develop, what matters most, and how you interact — it guides decisions when the textbook does not apply.' },
    { type: 'multiple_choice', question: 'Why is ethical practice important in coaching?', options: ['Only for legal reasons', 'Trust is the foundation of effective coaching — ethical practice protects athletes and maintains the professional relationship', 'Ethics do not affect results', 'Only for team sports'], correctAnswer: 1, explanation: 'Ethical practice (honesty, confidentiality, appropriate boundaries, duty of care) builds the trust without which no coaching relationship can be effective.' },
    { type: 'multiple_choice', question: 'What is duty of care in a coaching context?', options: ['Optional goodwill', 'The legal and moral obligation to ensure athlete safety, wellbeing, and appropriate support during training', 'Only applies to children', 'A marketing term'], correctAnswer: 1, explanation: 'Duty of care is both legal and moral — you are responsible for providing a safe training environment, appropriate programming, and recognising when to refer.' },
    { type: 'multiple_choice', question: 'What are appropriate professional boundaries in coaching?', options: ['No boundaries needed with adults', 'Clear limits on the coaching relationship including physical contact, communication, social boundaries, and scope of practice', 'Boundaries create distance', 'Only for youth coaches'], correctAnswer: 1, explanation: 'Professional boundaries protect both coach and athlete — clear expectations around communication, physical contact, social media, and scope of practice prevent misunderstandings.' },
    { type: 'multiple_choice', question: 'What should you do if an athlete asks for nutrition advice beyond your scope?', options: ['Give advice anyway', 'Acknowledge their question, provide general healthy eating guidance, and refer to a qualified nutrition professional', 'Refuse to discuss nutrition at all', 'Pretend to be qualified'], correctAnswer: 1, explanation: 'Working within scope of practice: acknowledge the question, provide what you are qualified to offer, and refer to the appropriate professional — this builds credibility.' },
  
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'Which type of cueing produces better movement outcomes?', options: ['Internal cues focusing on body parts', 'External cues focusing on movement effects', 'No cueing at all', 'Shouting louder'], correctAnswer: 1, explanation: 'External cues allow natural self-organisation of movement patterns.' },
    { type: 'multiple_choice', question: 'What are the three stages of motor learning?', options: ['Easy, medium, hard', 'Cognitive, associative, autonomous', 'Beginner, intermediate, advanced', 'Learning, practising, competing'], correctAnswer: 1, explanation: 'Each stage requires different coaching approaches.' },
    { type: 'multiple_choice', question: 'What happens when you over-coach an autonomous learner?', options: ['They improve faster', 'Excessive coaching can disrupt their automatic movement patterns', 'Nothing changes', 'They become dependent'], correctAnswer: 1, explanation: 'Advanced performers move best with minimal conscious interference.' },
    { type: 'multiple_choice', question: 'How often should you give feedback for best long-term learning?', options: ['Every single rep', 'Every 3rd to 5th rep — reduced frequency builds self-correction ability', 'Only once per session', 'Never'], correctAnswer: 1, explanation: 'Reduced feedback frequency forces learners to develop error detection skills.' },
    { type: 'multiple_choice', question: 'Convert this internal cue to external: Extend your knees', options: ['Push harder', 'Drive the floor away', 'Straighten your legs more', 'Use your quads'], correctAnswer: 1, explanation: 'External cues direct attention to movement outcomes, not body mechanics.' },
    { type: 'multiple_choice', question: 'What is external cueing?', options: ['Coaching from outside the gym', 'Directing an athlete\'s attention to the effect of their movement on the environment rather than their body', 'A type of exercise', 'Only for beginners'], correctAnswer: 1, explanation: 'External cues ("push the floor away" vs "extend your legs") consistently produce better motor learning outcomes than internal cues in research.' },
    { type: 'multiple_choice', question: 'Why is external cueing generally more effective than internal cueing?', options: ['It is not more effective', 'External focus promotes automatic motor control; internal focus causes conscious interference ("paralysis by analysis")', 'Internal cues are always better', 'Only for advanced athletes'], correctAnswer: 1, explanation: 'External cueing allows the motor system to self-organise movement naturally — internal cueing disrupts automatic processes by creating conscious interference.' },
    { type: 'multiple_choice', question: 'What is a movement demonstration and when should you use one?', options: ['Never demonstrate', 'Showing the complete movement before cueing details — visual learning is the fastest way to convey movement patterns', 'Only demonstrate incorrect form', 'Only for children'], correctAnswer: 1, explanation: 'Visual demonstration provides a mental model before verbal cueing — most people learn movements faster from seeing them than from hearing descriptions.' },
    { type: 'multiple_choice', question: 'What is the constraints-led approach to teaching movement?', options: ['Restricting athletes', 'Manipulating task, environmental, or individual constraints to guide athletes toward discovering solutions themselves', 'Giving detailed instructions', 'A rehabilitation method'], correctAnswer: 1, explanation: 'The constraints-led approach changes the environment (narrower stance, tempo requirement, implement variation) to guide movement discovery — producing more robust learning.' },
    { type: 'multiple_choice', question: 'What is the optimal number of coaching cues to give at once?', options: ['As many as possible', 'One — maybe two — at a time; the athlete can only process one correction per set', 'Five or more', 'Zero — let them figure it out'], correctAnswer: 1, explanation: 'Attentional capacity is limited — one clear cue per set produces better outcomes than overwhelming the athlete with multiple corrections simultaneously.' },
  
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is the foundation of effective coaching communication?', options: ['Giving great advice', 'Active listening — fully concentrating on what someone is saying', 'Talking confidently', 'Having all the answers'], correctAnswer: 1, explanation: 'Clients who feel heard develop more trust and show better compliance.' },
    { type: 'multiple_choice', question: 'Why do most clients quit?', options: ['Bad programmes', 'They feel unsupported, unheard, or unrealistically judged', 'Programmes are too easy', 'They run out of money'], correctAnswer: 1, explanation: 'Communication and expectation management drive retention more than programming.' },
    { type: 'multiple_choice', question: 'What is the best approach to difficult conversations about non-compliance?', options: ['Blame the client', 'Address the behaviour not the person, using specific observations and offering support', 'Ignore the issue', 'Threaten to stop coaching them'], correctAnswer: 1, explanation: 'Non-judgemental, specific observations open dialogue rather than triggering defensiveness.' },
    { type: 'multiple_choice', question: 'What should you set from the first consultation?', options: ['Unrealistic goals to motivate', 'Realistic expectations with honest timelines', 'No expectations', 'Only short-term goals'], correctAnswer: 1, explanation: 'Unrealistic expectations are the primary reason clients quit.' },
    { type: 'multiple_choice', question: 'How should you celebrate client progress?', options: ['Only celebrate outcome metrics like weight loss', 'Reframe success around behaviour metrics: sessions attended, nutrition compliance', 'Wait until goals are fully achieved', 'Compare them to other clients'], correctAnswer: 1, explanation: 'Process-focused celebration sustains motivation regardless of outcome fluctuations.' },
    { type: 'multiple_choice', question: 'What is the most important communication skill for a coach?', options: ['Talking loudly', 'Active listening — understanding what the athlete is actually saying and feeling before responding', 'Giving more instructions', 'Using technical language'], correctAnswer: 1, explanation: 'Active listening (full attention, reflecting, not interrupting) is the foundation — you cannot coach effectively if you do not understand the athlete\'s perspective.' },
    { type: 'multiple_choice', question: 'How should you deliver negative feedback to an athlete?', options: ['Avoid all negative feedback', 'Use a sandwich approach: acknowledge effort, provide specific constructive feedback, end with encouragement', 'Be blunt and critical', 'Only give negative feedback in writing'], correctAnswer: 1, explanation: 'Effective feedback is specific, timely, and balanced — acknowledging effort before constructive correction maintains motivation while driving improvement.' },
    { type: 'multiple_choice', question: 'How do you manage client expectations effectively?', options: ['Promise rapid results', 'Set realistic timelines from the start, celebrate small wins, and educate about the process of long-term development', 'Under-promise everything', 'Avoid discussing timelines'], correctAnswer: 1, explanation: 'Managing expectations prevents disappointment — realistic timelines, process-focused goals, and celebrating progress build trust and long-term commitment.' },
    { type: 'multiple_choice', question: 'What should you do when an athlete disagrees with your programming?', options: ['Ignore their opinion', 'Listen to their concerns, explain your rationale, and collaboratively find a solution that maintains training effectiveness', 'Change everything they want', 'Drop them as a client'], correctAnswer: 1, explanation: 'Collaborative coaching: listen to concerns, explain the reasoning, and find solutions together — athletes who understand and buy into the programme are more adherent.' },
    { type: 'multiple_choice', question: 'What is psychological safety in a coaching environment?', options: ['Being soft on athletes', 'An environment where athletes feel safe to ask questions, make mistakes, and express concerns without judgement', 'A weakness', 'Only relevant in therapy'], correctAnswer: 1, explanation: 'Psychological safety enables athletes to attempt new skills, report injuries honestly, and communicate openly — all essential for effective development.' },
  
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'Is resistance training safe for adolescents?', options: ['No — it stunts growth', 'Dangerous at any age', 'Yes — it is safe and beneficial when properly supervised', 'Only after age 18'], correctAnswer: 2, explanation: 'The growth-stunting myth has been comprehensively debunked by research.' },
    { type: 'multiple_choice', question: 'What is the primary training goal for older adults?', options: ['Aesthetic improvement', 'Compound movements that build functional strength for daily life independence', 'Weight loss only', 'Flexibility only'], correctAnswer: 1, explanation: 'Resistance training combats sarcopenia and reduces fall risk.' },
    { type: 'multiple_choice', question: 'When should you obtain medical clearance for a client?', options: ['Never', 'Before training anyone with a diagnosed chronic condition', 'Only for athletes', 'Only if they are over 70'], correctAnswer: 1, explanation: 'Medical clearance protects both you and the client when conditions are present.' },
    { type: 'multiple_choice', question: 'What should never be assumed about older adult clients?', options: ['That they need special equipment', 'That they cannot squat, deadlift, or press — never assume limitation', 'That they are motivated', 'That they are healthy'], correctAnswer: 1, explanation: 'Many older adults can train with excellent form — do not patronise.' },
    { type: 'multiple_choice', question: 'What is the primary goal for adolescent training?', options: ['Maximum strength gains', 'Competition preparation', 'Developing a positive relationship with exercise while building skills', 'Bodybuilding'], correctAnswer: 2, explanation: 'Enjoyment and skill development should be prioritised over intensity and load.' },
    { type: 'multiple_choice', question: 'What adaptations are needed when programming for older adults?', options: ['They should not train', 'Longer warm-ups, more joint-friendly exercises, gradual progression, emphasis on balance and bone density', 'Same programme as young athletes', 'Only cardio'], correctAnswer: 1, explanation: 'Older adults benefit enormously from strength training but need longer warm-ups, more recovery, emphasis on balance/bone density, and awareness of joint limitations.' },
    { type: 'multiple_choice', question: 'What considerations exist for training pregnant women?', options: ['No training during pregnancy', 'Avoid supine positions after first trimester, moderate intensity, avoid contact sports, and adjust for changing centre of gravity', 'Train exactly the same', 'Only walk during pregnancy'], correctAnswer: 1, explanation: 'Pregnant women can and should train — with modifications: avoid supine positions after 16 weeks, moderate intensity, no contact risk, and awareness of relaxin effects on joint stability.' },
    { type: 'multiple_choice', question: 'What is the key principle for training youth athletes?', options: ['Maximum intensity from age 10', 'Develop a broad movement base before specialisation — technical competence and fun should precede intensity', 'Same as adult programming', 'Only sport practice'], correctAnswer: 1, explanation: 'Youth development prioritises: fundamental movement skills, multi-sport participation, technical competence, and enjoyment — early specialisation and high intensity increase burnout and injury.' },
    { type: 'multiple_choice', question: 'What modifications are needed for training people with disabilities?', options: ['They should not train', 'Individualised adaptations based on their specific needs — focusing on what they CAN do rather than limitations', 'One programme fits all', 'Only rehabilitation exercises'], correctAnswer: 1, explanation: 'Training for people with disabilities requires individual assessment and creative adaptation — focusing on capabilities, not limitations, while addressing specific needs.' },
    { type: 'multiple_choice', question: 'What is important when programming for someone returning to training after a long break?', options: ['Start where they left off', 'Begin at a significantly reduced level (40–50% of previous capacity) and progress conservatively to allow tissue re-adaptation', 'Maximum intensity from day one', 'Only stretching for the first month'], correctAnswer: 1, explanation: 'Detraining means tissues have adapted to reduced demand — starting at 40–50% of previous capacity and progressing 10% per week prevents the excessive soreness and injury risk of overzealous returns.' },
  
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'Why do most personal trainers leave the industry within two years?', options: ['Lack of fitness knowledge', 'Lack of business skills — pricing, marketing, and client retention', 'The work is too physical', 'Too much competition'], correctAnswer: 1, explanation: 'Technical competence without business acumen leads to unsustainable careers.' },
    { type: 'multiple_choice', question: 'What costs 5-7 times more than retaining an existing client?', options: ['New equipment', 'Acquiring a new client', 'Continuing education', 'Gym rent'], correctAnswer: 1, explanation: 'Client retention is far more cost-effective than constant acquisition.' },
    { type: 'multiple_choice', question: 'What three factors drive client retention?', options: ['Price, location, equipment', 'Results, relationships, and experience', 'Marketing, branding, social media', 'Discounts, promotions, free sessions'], correctAnswer: 1, explanation: 'Clients who see progress, feel cared about, and enjoy training stay for years.' },
    { type: 'multiple_choice', question: 'Which revenue model is most scalable?', options: ['One-to-one PT only', 'Online coaching — no time-for-money ceiling', 'Group classes only', 'Selling supplements'], correctAnswer: 1, explanation: 'Online coaching removes the geographic and time constraints of in-person work.' },
    { type: 'multiple_choice', question: 'What two numbers should every fitness business track?', options: ['Followers and likes', 'Client retention rate and client results', 'Revenue and expenses only', 'Hours worked and sessions delivered'], correctAnswer: 1, explanation: 'Retention and results are the most important health metrics for a fitness business.' },
    { type: 'multiple_choice', question: 'What is the most important factor for building a coaching business?', options: ['Social media followers', 'Consistently delivering results for clients — word of mouth from satisfied clients is the strongest marketing', 'Expensive equipment', 'A large facility'], correctAnswer: 1, explanation: 'Results and relationships drive referrals — the most successful coaches build businesses through consistently delivering outcomes and genuine client care.' },
    { type: 'multiple_choice', question: 'What should a coaching business plan include?', options: ['Only revenue targets', 'Target market, services offered, pricing strategy, marketing plan, financial projections, and professional development plan', 'Only social media strategy', 'A business plan is unnecessary'], correctAnswer: 1, explanation: 'A business plan provides direction: who you serve, what you offer, how you reach them, what you charge, and how you develop professionally.' },
    { type: 'multiple_choice', question: 'How should you price coaching services?', options: ['As cheap as possible', 'Based on your qualifications, experience, the value delivered, market rates, and your target client demographic', 'Copy competitor prices exactly', 'Charge maximum immediately'], correctAnswer: 1, explanation: 'Pricing reflects value: qualifications + experience + results + market research. Under-pricing undermines perceived value; overpricing without evidence loses clients.' },
    { type: 'multiple_choice', question: 'What insurance do personal trainers need in the UK?', options: ['None', 'Professional indemnity insurance and public liability insurance — both are essential and often legally required', 'Only car insurance', 'Insurance is optional'], correctAnswer: 1, explanation: 'Professional indemnity (covers your advice) and public liability (covers accidents) are essential — most gyms and facilities require proof before allowing you to operate.' },
    { type: 'multiple_choice', question: 'What is the most effective form of marketing for a new coach?', options: ['Paid advertising only', 'Providing genuine value through free content, testimonials from early clients, and building relationships in your local community', 'Cold calling', 'Waiting for clients to come to you'], correctAnswer: 1, explanation: 'New coaches build best through value-first marketing: free workshops, social media education, client testimonials, and local networking — building trust before asking for business.' },
  
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Why is continuing professional development an ethical obligation?', options: ['It is required by law', 'Clients trust you to provide guidance based on current evidence, not outdated methods', 'It makes you more money', 'It is not — it is optional'], correctAnswer: 1, explanation: 'Using disproven methods while current evidence exists is not serving clients well.' },
    { type: 'multiple_choice', question: 'What is at the top of the evidence hierarchy?', options: ['Expert opinion', 'Case studies', 'A single randomised controlled trial', 'Systematic reviews and meta-analyses'], correctAnswer: 3, explanation: 'Systematic reviews synthesise findings from multiple studies for strongest conclusions.' },
    { type: 'multiple_choice', question: 'Why should supplement company-funded research be viewed carefully?', options: ['It is always wrong', 'Studies with conflicts of interest are more likely to produce favourable results for funders', 'It is always perfect', 'Only university research matters'], correctAnswer: 1, explanation: 'Funding conflicts can bias study design, interpretation, and publication.' },
    { type: 'multiple_choice', question: 'What should you do before changing practice based on a new study?', options: ['Change immediately', 'Wait for replication across multiple studies', 'Ignore all new research', 'Ask social media'], correctAnswer: 1, explanation: 'A single study is a data point; consistent findings across multiple studies are evidence.' },
    { type: 'multiple_choice', question: 'What is the practical difference between statistical and practical significance?', options: ['They are the same', 'A result can be statistically significant but too small to matter in real-world practice', 'Practical significance is more important than statistical', 'Only statistical significance matters'], correctAnswer: 1, explanation: 'Always ask how big the actual difference is — small effects may be meaningless in practice.' },
    { type: 'multiple_choice', question: 'Why is CPD mandatory for fitness professionals?', options: ['It is not mandatory', 'Industry knowledge evolves rapidly — CPD ensures coaches stay current, maintain insurance requirements, and improve practice', 'Only for new coaches', 'CPD is unnecessary after certification'], correctAnswer: 1, explanation: 'Exercise science evolves continuously — CPD maintains competence, meets insurance/registration requirements, and demonstrates professionalism to clients.' },
    { type: 'multiple_choice', question: 'What counts as valid CPD?', options: ['Only formal courses', 'Courses, workshops, mentoring, reading peer-reviewed research, attending conferences, and reflective practice', 'Only university degrees', 'Social media learning only'], correctAnswer: 1, explanation: 'CPD includes formal (courses, workshops) and informal (reading research, mentoring, reflective practice) learning — the key is deliberate professional growth.' },
    { type: 'multiple_choice', question: 'How should you record CPD activities?', options: ['No records needed', 'Maintain a CPD log documenting date, activity, provider, what was learned, and how it will be applied in practice', 'Only keep certificates', 'Memory is sufficient'], correctAnswer: 1, explanation: 'A structured CPD log provides evidence for registration bodies, helps identify learning gaps, and demonstrates professional commitment to clients and employers.' },
    { type: 'multiple_choice', question: 'What is a reflective journal in coaching?', options: ['A diary', 'A structured record of coaching experiences, what worked, what did not, and how you will adjust your practice', 'A workout log', 'A client file'], correctAnswer: 1, explanation: 'Reflective journaling turns experience into expertise — systematically recording what happened, what you learned, and how you will apply it drives continuous improvement.' },
    { type: 'multiple_choice', question: 'How much CPD should a fitness professional complete annually?', options: ['None', 'A minimum of 20–30 hours per year, combining formal courses with informal learning and reflective practice', '1 hour per year', '200 hours per year'], correctAnswer: 1, explanation: 'Most registration bodies require 20–30 hours annually — but the best coaches far exceed this through ongoing reading, mentoring, and reflective practice.' },
  
  ]),
  cq(4, 7, [
    { type: 'multiple_choice', question: 'What are the three pillars of evidence-based practice?', options: ['Research, research, research', 'Scientific evidence, professional experience, and client values/preferences', 'Textbooks, courses, certifications', 'Training, nutrition, recovery'], correctAnswer: 1, explanation: 'All three must inform decisions — none alone is sufficient.' },
    { type: 'multiple_choice', question: 'What happens when a coach ignores client preferences?', options: ['Nothing', 'Programmes look great on paper but fail because the client will not follow them', 'Results improve', 'Clients train harder'], correctAnswer: 1, explanation: 'A programme a client will not follow is worse than an imperfect one they will.' },
    { type: 'multiple_choice', question: 'When your experience contradicts research, what should you consider?', options: ['Your experience is always right', 'Research is always right', 'Is your experience based on representative samples, or memorable cases? Does the research match your context?', 'Flip a coin'], correctAnswer: 2, explanation: 'Mature practitioners hold both perspectives and test systematically.' },
    { type: 'multiple_choice', question: 'What determines whether research findings apply to your client?', options: ['The journal it was published in', "Whether the study population and context match your client\'s situation", 'How famous the researchers are', 'How recently it was published'], correctAnswer: 1, explanation: 'Population match and context relevance determine practical applicability.' },
    { type: 'multiple_choice', question: 'What makes evidence-based practice different from just following studies?', options: ['Nothing', 'EBP integrates evidence with experience and client needs, not blind adherence', 'EBP ignores research', 'EBP only uses the newest studies'], correctAnswer: 1, explanation: 'Integration of all three pillars produces the best coaching decisions.' },
    { type: 'multiple_choice', question: 'What does evidence-based practice mean in coaching?', options: ['Only using peer-reviewed studies', 'Integrating the best available research with professional expertise and individual client values/preferences', 'Ignoring science and using experience only', 'Following every new study exactly'], correctAnswer: 1, explanation: 'Evidence-based practice combines three pillars: best available research + professional experience/expertise + individual client context and preferences.' },
    { type: 'multiple_choice', question: 'Why should you not change your practice based on a single study?', options: ['Single studies are always wrong', 'Individual studies can have methodological flaws, small samples, or be outliers — systematic reviews of multiple studies are more reliable', 'Always follow new studies immediately', 'No studies are relevant to coaching'], correctAnswer: 1, explanation: 'Single studies can be misleading — small samples, poor methodology, or unique populations. Multiple studies (systematic reviews) provide more reliable evidence for practice changes.' },
    { type: 'multiple_choice', question: 'What is confirmation bias in coaching?', options: ['A positive trait', 'The tendency to seek and remember evidence that supports your existing beliefs while ignoring contradicting evidence', 'Being confident in your methods', 'A research method'], correctAnswer: 1, explanation: 'Confirmation bias leads coaches to cherry-pick research supporting their methods — actively seeking contradicting evidence and being willing to update beliefs is essential.' },
    { type: 'multiple_choice', question: 'How should anecdotal evidence be weighted against research?', options: ['Anecdotes are stronger than research', 'Anecdotes generate hypotheses; research tests them — personal experience is valuable but can be misleading without systematic evidence', 'They are equally valid', 'Anecdotes should be ignored completely'], correctAnswer: 1, explanation: 'Anecdotal evidence ("it worked for me/my clients") is useful for generating ideas but is not proof — survivorship bias, placebo effects, and confounding variables limit its reliability.' },
    { type: 'multiple_choice', question: 'What is the Dunning-Kruger effect and how does it affect coaches?', options: ['A training programme', 'The tendency for those with little knowledge to overestimate their competence, while experts tend to underestimate theirs', 'A stretching technique', 'A positive cognitive bias'], correctAnswer: 1, explanation: 'New coaches often overestimate their knowledge; experienced coaches recognise how much they do not know — awareness of this bias promotes humility and continued learning.' },
  
  ]),
  cq(4, 8, [
    { type: 'multiple_choice', question: 'What makes a great coach beyond knowledge?', options: ['Certifications alone', 'The ability to apply knowledge to real people with empathy, adaptability, and integrity', 'Physical fitness', 'Social media following'], correctAnswer: 1, explanation: 'Knowledge is necessary but insufficient — application with human skills defines greatness.' },
    { type: 'multiple_choice', question: 'Why should you identify your coaching niche?', options: ['To limit yourself', 'Serving a specific population deeply is more valuable than serving everyone superficially', 'It is not important', 'To exclude potential clients'], correctAnswer: 1, explanation: 'Depth of service in a niche creates more value than breadth of shallow service.' },
    { type: 'multiple_choice', question: 'What does the Unbreakable standard represent?', options: ['Being physically unbreakable', 'Knowledge in service of others, applied with integrity, refined through lifelong practice', 'Never showing weakness', 'Extreme training'], correctAnswer: 1, explanation: 'The standard is about ethical service and continuous improvement, not physical invincibility.' },
    { type: 'multiple_choice', question: 'How does the best coaching career develop?', options: ['Peaks at 25 and declines', 'Through decades of practice, reflection, and genuine care — producing wisdom courses cannot teach', 'Only through more certifications', 'By copying successful coaches'], correctAnswer: 1, explanation: 'Experience and reflection produce wisdom that formal education cannot replicate.' },
    { type: 'multiple_choice', question: 'What is the lifelong commitment of a coach?', options: ['Making money', 'Learning, serving, and growing — coaching is a practice, not a destination', 'Winning competitions', 'Becoming famous'], correctAnswer: 1, explanation: 'Coaching is a lifelong practice of improvement, not a career destination.' },
    { type: 'multiple_choice', question: 'What makes a coaching niche valuable?', options: ['Serving everyone equally', 'Specialising in a specific population or goal allows deeper expertise and stronger positioning in the market', 'Niches limit your income', 'Only generalists succeed'], correctAnswer: 1, explanation: 'A niche (e.g., powerlifting for over-40s, return-to-sport after ACL reconstruction) enables deeper expertise, clearer marketing, and stronger client attraction than being a generalist.' },
    { type: 'multiple_choice', question: 'What is personal branding for coaches?', options: ['Having a logo', 'The consistent communication of your values, expertise, and coaching approach across all platforms and interactions', 'Social media posts only', 'A business expense'], correctAnswer: 1, explanation: 'Personal branding is how the world perceives you professionally — it should authentically communicate your values, expertise, and unique approach across all touchpoints.' },
    { type: 'multiple_choice', question: 'Why is mentoring important for coaching development?', options: ['It is not important', 'Learning from experienced coaches accelerates development, provides perspective, and prevents common mistakes', 'Only for beginners', 'Books are sufficient'], correctAnswer: 1, explanation: 'Mentoring provides contextualised learning that books and courses cannot — watching experienced coaches navigate real situations accelerates professional development dramatically.' },
    { type: 'multiple_choice', question: 'What is the importance of authenticity in coaching?', options: ['Authenticity is unprofessional', 'Genuine coaches build deeper trust, attract compatible clients, and maintain motivation long-term', 'Only results matter', 'Copy successful coaches exactly'], correctAnswer: 1, explanation: 'Authentic coaching — being genuinely yourself — builds deeper client relationships, attracts people aligned with your values, and sustains your passion for coaching.' },
    { type: 'multiple_choice', question: 'What is the long-term vision for a coaching career?', options: ['Maximise income immediately', 'Build progressively from individual coaching to mentoring, education, content creation, and industry leadership', 'Stay at the same level forever', 'Only coach athletes'], correctAnswer: 1, explanation: 'A coaching career evolves: individual coaching → group coaching → mentoring other coaches → education/content → industry leadership — each stage builds on the last.' },
  
  ]),
];