import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the two questions a needs analysis answers?', options: ['When to train and when to rest', 'What supplements to take', 'What does the sport require and where does the athlete fall short?', 'How much and how often'], correctAnswer: 2, explanation: 'A needs analysis maps sport demands against athlete abilities.' },
    { type: 'multiple_choice', question: 'Why is a needs analysis important?', options: ['It only matters for professionals', 'It replaces training', 'It is required by law', 'It makes training specific to sport demands rather than generic'], correctAnswer: 3, explanation: 'Without it, training becomes generic and fails to address sport-specific needs.' },
    { type: 'multiple_choice', question: 'What determines exercise selection in a sport-specific programme?', options: ['What the coach enjoys', 'The dominant movement patterns identified in the needs analysis', 'What equipment is available', 'Social media trends'], correctAnswer: 1, explanation: 'Exercise selection must reflect the movements that dominate the sport.' },
    { type: 'multiple_choice', question: 'In team sports, do all positions have the same physical demands?', options: ['Only in rugby', 'Only in football', 'Yes — they play the same sport', 'No — different positions have different needs analyses'], correctAnswer: 3, explanation: 'A goalkeeper and midfielder have vastly different physical demands.' },
    { type: 'multiple_choice', question: 'What is the most common mistake in sport-specific training?', options: ['Not enough cardio', 'Training too little', 'Using too much variety', 'Training what athletes are already good at while neglecting actual needs'], correctAnswer: 3, explanation: 'Athletes often gravitate toward their strengths rather than addressing weaknesses.' },
    { type: 'multiple_choice', question: 'What is a needs analysis in sport?', options: ['A systematic assessment of the physical demands, energy systems, movement patterns, and injury risks of a specific sport', 'Identifying equipment needs', 'A psychological assessment', 'A budget review'], correctAnswer: 0, explanation: 'A needs analysis breaks down exactly what the sport demands: energy systems, movement patterns, muscle groups, common injuries, and competition schedule.' },
    { type: 'multiple_choice', question: 'Why must strength and conditioning programmes be sport-specific?', options: ['All sports need the same training', 'General fitness is always sufficient', 'Sport-specificity is overrated', 'Different sports have unique physical demands — training must develop the specific qualities needed for that sport'], correctAnswer: 3, explanation: 'A rugby player and a marathon runner have vastly different physical demands — S&C must develop the specific qualities (power, endurance, speed) relevant to each sport.' },
    { type: 'multiple_choice', question: 'What are the key components of a sport needs analysis?', options: ['Only cardiovascular demands', 'Movement patterns, energy systems, force requirements, common injuries, competition calendar, and individual athlete assessment', 'Only strength demands', 'Only the coach\'s opinion'], correctAnswer: 1, explanation: 'A comprehensive needs analysis examines multiple dimensions: biomechanical demands, energy system contributions, injury epidemiology, and individual athlete strengths/weaknesses.' },
    { type: 'multiple_choice', question: 'How does a needs analysis inform exercise selection?', options: ['Exercises are selected to develop the specific movement patterns, force profiles, and energy systems identified in the analysis', 'Only use sport movements', 'It does not', 'Select exercises randomly'], correctAnswer: 0, explanation: 'Exercise selection flows directly from the needs analysis — if the sport demands lateral power, programming includes lateral plyometrics and single-leg strength work.' },
    { type: 'multiple_choice', question: 'What is the principle of specificity in S&C?', options: ['Train the same as the sport', 'Specificity does not exist', 'All training transfers equally', 'Training adaptations are specific to the demands imposed — force, velocity, direction, and energy system must match sport requirements'], correctAnswer: 3, explanation: 'Specificity (SAID principle) means the body adapts specifically to the demands placed on it — heavy squats develop different qualities than box jumps, even though both train legs.' },
  
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What is the primary determinant of sprint speed?', options: ['How much force you can apply to the ground per stride', 'Leg length', 'Breathing technique', 'Arm swing speed'], correctAnswer: 0, explanation: 'Ground reaction force during the brief contact time determines speed.' },
    { type: 'multiple_choice', question: 'Why does maximal strength improve sprint performance?', options: ['Heavier muscles move faster', 'Stronger athletes apply more force per ground contact', 'It does not improve sprinting', 'Strength makes you lighter'], correctAnswer: 1, explanation: 'Greater force production per ground contact increases stride length and acceleration.' },
    { type: 'multiple_choice', question: 'What is the minimum rest between maximal sprints for speed development?', options: ['30 seconds', '3-5 minutes', 'No rest needed', '1 minute'], correctAnswer: 1, explanation: 'Full neural recovery requires 3-5 minutes; shorter rest trains conditioning, not speed.' },
    { type: 'multiple_choice', question: 'What is rate of force development?', options: ['How long you can sustain force', 'Maximum force you can produce', 'Force per bodyweight', 'How quickly you can reach peak force'], correctAnswer: 3, explanation: 'In sport, how fast you develop force matters more than absolute peak force.' },
    { type: 'multiple_choice', question: 'What trains deceleration ability?', options: ['Progressive deceleration drills and eccentric strength work', 'Static stretching', 'Isometric holds only', 'Long slow runs'], correctAnswer: 0, explanation: 'Deceleration requires eccentric strength and neuromuscular control.' },
    { type: 'multiple_choice', question: 'What is the force-velocity curve?', options: ['A flexibility test', 'A nutrition concept', 'A cardio metric', 'The inverse relationship between force and velocity — maximum force is produced at low speeds, maximum speed at low forces'], correctAnswer: 3, explanation: 'The force-velocity curve shows that as speed increases, force capacity decreases — training different points on this curve develops different athletic qualities.' },
    { type: 'multiple_choice', question: 'What is the difference between strength-speed and speed-strength?', options: ['They are not real terms', 'Only one exists', 'Strength-speed: high force at moderate velocity (heavy cleans); Speed-strength: moderate force at high velocity (jump squats)', 'They are the same'], correctAnswer: 2, explanation: 'Strength-speed (60–80% 1RM moved with intent) develops the high-force end; speed-strength (30–50% 1RM) develops the high-velocity end of the force-velocity curve.' },
    { type: 'multiple_choice', question: 'Why is intent to move fast as important as actual speed?', options: ['Only actual speed matters', 'Intent does not matter', 'Intent is psychological only', 'Maximum effort against heavy loads recruits high-threshold motor units even when the bar moves slowly'], correctAnswer: 3, explanation: 'Maximal intent to accelerate recruits the highest-threshold motor units — even if the heavy load moves slowly, the neural drive and fibre recruitment are maximal.' },
    { type: 'multiple_choice', question: 'What is reactive strength?', options: ['Responding to a coach\'s signal', 'The ability to rapidly switch from eccentric to concentric contraction — critical for jumping, sprinting, and change of direction', 'A flexibility quality', 'Reaction time only'], correctAnswer: 1, explanation: 'Reactive strength is the ability to utilise the stretch-shortening cycle — rapidly absorbing and re-applying force during ground contact.' },
    { type: 'multiple_choice', question: 'How should power training be programmed differently from strength training?', options: ['Power work uses lower reps (1–5), longer rest (2–5 min), and maximum velocity intent — never train power under fatigue', 'Power training is the same as cardio', 'No difference needed', 'Power uses high reps and short rest'], correctAnswer: 0, explanation: 'Power training requires neural freshness — low reps, full recovery, and maximum intent. Training power under fatigue trains fatigue, not power.' },
  
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What distinguishes agility from change of direction speed?', options: ['CODS requires more skill', 'Nothing — they are the same', 'Agility is slower', 'Agility adds perception and decision-making to physical direction change'], correctAnswer: 3, explanation: 'True agility requires reading and reacting to unpredictable stimuli.' },
    { type: 'multiple_choice', question: 'What is the most important physical quality for direction change?', options: ['Endurance', 'Eccentric braking strength — the ability to decelerate', 'Flexibility', 'Concentric quad strength'], correctAnswer: 1, explanation: 'Deceleration is the foundation of safe, effective direction change.' },
    { type: 'multiple_choice', question: 'Why are elite athletes faster in reactive agility tests but not pre-planned tests?', options: ['They train more hours', 'They are stronger', 'They read cues earlier and process information faster', 'They are just fitter'], correctAnswer: 2, explanation: 'Perceptual speed — not physical speed — separates elite from average in sport.' },
    { type: 'multiple_choice', question: 'What should agility drills include to be effective?', options: ['Timed laps', 'Maximum distance', 'An unpredictable stimulus requiring read-and-react', 'Only cones'], correctAnswer: 2, explanation: 'Reactive elements transform physical drills into true agility training.' },
    { type: 'multiple_choice', question: 'What is the role of ankle stiffness in direction change?', options: ['Stiff ankles transmit force efficiently during rapid cuts', 'Flexibility is more important', 'It should be minimised', 'Only matters for runners'], correctAnswer: 0, explanation: 'Ankle stiffness enables rapid force transmission during sharp direction changes.' },
    { type: 'multiple_choice', question: 'What is the difference between agility and change of direction speed (CODS)?', options: ['They are the same', 'CODS is planned direction change; agility includes a reactive decision-making component in response to a stimulus', 'Agility is slower', 'CODS requires more thinking'], correctAnswer: 1, explanation: 'CODS is pre-planned (cone drills); agility requires reacting to a stimulus (defender movement) — both need training but agility is more sport-specific.' },
    { type: 'multiple_choice', question: 'What physical qualities underpin change of direction ability?', options: ['Only cardiovascular fitness', 'Eccentric strength (deceleration), concentric power (re-acceleration), and reactive strength (ground contact time)', 'Only speed', 'Only flexibility'], correctAnswer: 1, explanation: 'COD requires eccentric strength to decelerate, reactive strength at the cut, and concentric power to re-accelerate — all trainable through targeted S&C.' },
    { type: 'multiple_choice', question: 'Why is deceleration training important for injury prevention?', options: ['Deceleration cannot be trained', 'It is not important', 'Only acceleration matters', 'Most non-contact injuries (ACL tears) occur during deceleration — the ability to absorb force safely is critical'], correctAnswer: 3, explanation: 'Most non-contact knee and ankle injuries occur during deceleration and cutting — training eccentric strength and deceleration mechanics reduces ACL injury risk significantly.' },
    { type: 'multiple_choice', question: 'How should agility be progressed in training?', options: ['Maximum intensity from day one', 'Only sport practice', 'Pre-planned CODS → semi-reactive drills → fully reactive drills with sport-specific stimuli', 'Random drills only'], correctAnswer: 2, explanation: 'Progress from closed (pre-planned cones) → open (reacting to light/partner) → sport-specific (reacting to ball/opponent) — building physical capacity before adding cognitive demand.' },
    { type: 'multiple_choice', question: 'What role does single-leg strength play in change of direction?', options: ['Single-leg work is dangerous', 'Only for runners', 'None — bilateral strength is sufficient', 'Most COD occurs on one leg — single-leg strength provides the stability and force production needed for effective cuts'], correctAnswer: 3, explanation: 'Cutting, planting, and pushing off all occur on one leg — single-leg strength (split squats, step-ups) directly transfers to COD performance and injury resilience.' },
  
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What is the interference effect?', options: ['Two exercises interfering with each other', 'Simultaneous strength and endurance training can produce inferior adaptations in both', 'Radio interference in the gym', 'Muscle confusion'], correctAnswer: 1, explanation: 'The mTOR and AMPK pathways partially inhibit each other during concurrent training.' },
    { type: 'multiple_choice', question: 'How can you minimise interference between strength and endurance?', options: ['Never do both', 'Only do endurance training', 'Do them in the same session always', 'Separate sessions by at least 6 hours or train on different days'], correctAnswer: 3, explanation: 'Temporal separation reduces molecular conflict between adaptation pathways.' },
    { type: 'multiple_choice', question: 'What endurance method best simulates team sport demands?', options: ['Swimming', 'Long slow distance running', 'Repeated sprint ability training', 'Yoga'], correctAnswer: 2, explanation: 'RSA directly simulates the repeated high-intensity efforts of match play.' },
    { type: 'multiple_choice', question: 'Why might cycling be preferred over running for aerobic development?', options: ['It burns more calories', 'Lower eccentric stress means less interference with strength adaptations', 'It is easier', 'It does not work the legs'], correctAnswer: 1, explanation: 'Cycling removes the eccentric muscle damage that running produces.' },
    { type: 'multiple_choice', question: 'If an athlete is losing strength despite training, what should you check first?', options: ['Their gym shoes', 'Their endurance training volume', 'Their music playlist', 'Their supplement stack'], correctAnswer: 1, explanation: 'Excessive running volume is the most common reason for strength loss in field sport athletes.' },
    { type: 'multiple_choice', question: 'What is the interference effect?', options: ['Concurrent training of strength and endurance can compromise maximal gains in both — especially when endurance volume is high', 'A myth', 'Radio interference', 'A positive training effect'], correctAnswer: 0, explanation: 'The interference effect (molecular level: AMPK vs mTOR signalling) means high-volume endurance training can blunt strength and hypertrophy adaptations.' },
    { type: 'multiple_choice', question: 'How can the interference effect be minimised?', options: ['The interference effect cannot be managed', 'Avoid all endurance training', 'Separate strength and endurance sessions by 6+ hours, prioritise the primary goal, and use low-impact endurance modes', 'Only train one quality'], correctAnswer: 2, explanation: 'Minimise interference: separate sessions by 6+ hours, do strength before endurance, use cycling (less eccentric damage) over running, and manage total volume.' },
    { type: 'multiple_choice', question: 'What is concurrent training?', options: ['Training both strength and endurance qualities within the same programme', 'Only endurance training', 'Training with a partner', 'Only strength training'], correctAnswer: 0, explanation: 'Concurrent training develops both strength and endurance — necessary for most sports but requiring careful programming to manage the interference effect.' },
    { type: 'multiple_choice', question: 'When should endurance training be prioritised over strength?', options: ['Only in pre-season', 'Always', 'When the sport has high endurance demands — e.g., football, rugby, combat sports — endurance supports match fitness', 'Never'], correctAnswer: 2, explanation: 'Endurance is prioritised when sport demands it — most field sports require both aerobic capacity for match duration and repeated sprint ability for key moments.' },
    { type: 'multiple_choice', question: 'What type of endurance training has the least interference with strength?', options: ['High-intensity interval training (HIIT) and cycling — shorter duration and less eccentric damage than running', 'All endurance interferes equally', 'Marathon training', 'Long slow distance running'], correctAnswer: 0, explanation: 'HIIT and cycling minimise interference: HIIT is time-efficient with similar signalling pathways to strength; cycling avoids the eccentric damage of running.' },
  
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'What is the stretch-shortening cycle?', options: ['A cardio workout', 'A yoga sequence', 'Muscles produce more concentric force when preceded by rapid eccentric contraction', 'A stretching routine'], correctAnswer: 2, explanation: 'The SSC stores and releases elastic energy like a spring.' },
    { type: 'multiple_choice', question: 'What is the prerequisite before progressing to depth jumps?', options: ['Being tall', 'A solid strength base — minimum 1.5x bodyweight squat', 'Good flexibility', 'Having long legs'], correctAnswer: 1, explanation: 'Depth jumps require sufficient strength to absorb and redirect high forces safely.' },
    { type: 'multiple_choice', question: 'What indicates good reactive strength during plyometrics?', options: ['Slow heavy ground contacts', 'Loud landing sounds', 'Quick sharp ground contacts like a basketball bouncing', 'Maximum height only'], correctAnswer: 2, explanation: 'Quick, sharp contacts indicate efficient elastic energy use.' },
    { type: 'multiple_choice', question: 'When should plyometrics be performed in a session?', options: ['Early when the nervous system is fresh', 'At the end of training', 'After strength work', 'During cardio'], correctAnswer: 0, explanation: 'Plyometrics require peak neural drive, which diminishes with fatigue.' },
    { type: 'multiple_choice', question: 'What is the total foot contact guideline for advanced athletes?', options: ['500+ per session', '10 per session', 'Unlimited', '120-140 per session'], correctAnswer: 3, explanation: 'Managing total contacts ensures quality and reduces injury risk.' },
    { type: 'multiple_choice', question: 'What is a plyometric exercise?', options: ['Slow controlled movements', 'A rapid stretch-shortening cycle movement that develops the ability to produce maximum force in minimum time', 'Only depth jumps', 'Any jumping exercise'], correctAnswer: 1, explanation: 'Plyometrics specifically train the stretch-shortening cycle — the rapid eccentric-to-concentric transition that produces elastic rebound force.' },
    { type: 'multiple_choice', question: 'What is ground contact time and why does it matter?', options: ['It does not matter', 'A running metric only', 'The duration of foot contact during plyometric exercises — shorter contact times indicate better reactive strength', 'How long you stand'], correctAnswer: 2, explanation: 'Ground contact time reflects the efficiency of the stretch-shortening cycle — elite sprinters have contact times under 100ms, requiring exceptional reactive strength.' },
    { type: 'multiple_choice', question: 'What strength prerequisites should be met before high-intensity plyometrics?', options: ['Only bodyweight exercises needed', 'Minimum 1.5× bodyweight squat — insufficient strength means the body cannot safely absorb plyometric landing forces', 'Flexibility is the only prerequisite', 'None needed'], correctAnswer: 1, explanation: 'A strength base (typically 1.5× BW squat) ensures the musculoskeletal system can safely absorb the high eccentric forces of plyometric landings.' },
    { type: 'multiple_choice', question: 'How should plyometric volume be managed?', options: ['Volume does not matter', 'Maximum jumps every session', 'Only one set is needed', 'Track total foot contacts per session (60–100 for beginners, 100–150 advanced) and allow full recovery between sets'], correctAnswer: 3, explanation: 'Plyometric volume is measured in foot contacts — excessive volume under fatigue increases injury risk and trains fatigue, not power. Quality over quantity.' },
    { type: 'multiple_choice', question: 'When should plyometrics be performed in a training session?', options: ['Early in the session after warm-up — when the nervous system is fresh and can produce maximum force', 'Any time is fine', 'Between strength sets', 'At the end when fatigued'], correctAnswer: 0, explanation: 'Plyometrics require neural freshness for maximum force production — perform after warm-up but before strength work or conditioning when fatigue is lowest.' },
  
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'What is the fundamental principle of sport-specific programming?', options: ['Maximise gym time', 'Train what you need most, maintain what you have enough of, never interfere with practice quality', 'Always do more volume', "Copy professional athletes\' programmes"], correctAnswer: 1, explanation: 'The gym supports the field — not the other way around.' },
    { type: 'multiple_choice', question: 'In what order should training qualities be programmed within a session?', options: ['Conditioning → strength → power', 'Random order', 'Strength first always', 'Speed → power → strength → hypertrophy/conditioning'], correctAnswer: 3, explanation: 'Neurological demand determines order: speed and power require the freshest nervous system.' },
    { type: 'multiple_choice', question: 'When should the last heavy gym session occur relative to competition?', options: ['Match morning', 'Does not matter', 'At least 3 days before match day', 'The day before'], correctAnswer: 2, explanation: 'Heavy training close to competition interferes with match performance.' },
    { type: 'multiple_choice', question: 'What should you ask about every training session?', options: ['Is this making the athlete better at their sport or just more tired?', 'Did they sweat enough?', 'How long did it take?', 'Was it hard enough?'], correctAnswer: 0, explanation: 'If gym training creates fatigue for practice, the programme has failed.' },
    { type: 'multiple_choice', question: 'Why should exercise variety be limited in sport programmes?', options: ['Variety causes injury', 'Athletes get confused easily', 'Consistent exercises progressed over months transfer better than constantly rotating novel exercises', 'To save time'], correctAnswer: 2, explanation: 'Getting strong at specific patterns produces more sport transfer than exercise variety.' },
    { type: 'multiple_choice', question: 'What is the training hierarchy for sport-specific S&C?', options: ['Sport practice only', 'Start with sport-specific work', 'No hierarchy exists', 'General strength → sport-specific strength → power/speed → sport practice — building a foundation then specialising'], correctAnswer: 3, explanation: 'The training hierarchy builds foundations first: general strength (squat, deadlift) → specific strength (single-leg, rotation) → power/speed → sport practice integration.' },
    { type: 'multiple_choice', question: 'How should exercise selection differ between off-season and in-season?', options: ['Only train in the off-season', 'No difference', 'Off-season: higher volume, more general exercises, building capacity; In-season: lower volume, more specific, maintaining fitness', 'In-season should have more volume'], correctAnswer: 2, explanation: 'Off-season builds the base with higher volume and variety; in-season maintains adaptations with reduced volume but maintained intensity, prioritising sport practice.' },
    { type: 'multiple_choice', question: 'What is the principle of transfer in sport S&C?', options: ['All exercises transfer equally', 'The degree to which a training exercise improves sport performance — high transfer exercises closely match sport demands', 'Transfer is a myth', 'Moving equipment between gyms'], correctAnswer: 1, explanation: 'Transfer depends on how closely an exercise matches the sport\'s force, velocity, direction, and contraction type — high transfer exercises share these characteristics.' },
    { type: 'multiple_choice', question: 'How many S&C sessions per week should an in-season athlete complete?', options: ['2–3 sessions is typically optimal — enough to maintain adaptations without competing with sport practice recovery', 'None — only play the sport', '6 sessions', '1 session per month'], correctAnswer: 0, explanation: '2–3 S&C sessions per week maintains strength and power during the season while leaving sufficient recovery capacity for sport practice and competition.' },
    { type: 'multiple_choice', question: 'What is the concept of readiness in sport S&C?', options: ['Being mentally prepared only', 'Assessing an athlete\'s physical and psychological state before training to adjust session demands accordingly', 'Always training at maximum', 'A warm-up routine'], correctAnswer: 1, explanation: 'Readiness assessment (wellness questionnaires, jump testing, HRV) allows daily training adjustments — maximising stimulus on good days and reducing load when recovery is incomplete.' },
  
  ]),
  cq(3, 7, [
    { type: 'multiple_choice', question: 'What are the three phases of an annual training plan?', options: ['Weeks, months, years', 'Easy, medium, hard', 'Morning, afternoon, evening', 'Off-season (build), pre-season (transition), in-season (maintain)'], correctAnswer: 3, explanation: 'Each phase has different priorities for volume, intensity, and physical development.' },
    { type: 'multiple_choice', question: 'During in-season training, what should be maintained?', options: ['Neither — focus on competition only', 'Both equally', 'Intensity — reducing it causes detraining faster than reducing volume', 'Volume'], correctAnswer: 2, explanation: 'Maintaining intensity with reduced volume preserves adaptations with less fatigue.' },
    { type: 'multiple_choice', question: 'How much volume is needed to maintain a physical quality?', options: ['No volume — qualities maintain themselves', 'Double the development volume', 'The same as was used to develop it', 'About one-third of the development volume'], correctAnswer: 3, explanation: 'Research shows one-third of development volume is often sufficient for maintenance.' },
    { type: 'multiple_choice', question: 'What is the priority during the off-season?', options: ['Rest only', 'Technical skill work only', 'Competition preparation', 'Physical development — building strength, muscle, and addressing weaknesses'], correctAnswer: 3, explanation: 'Off-season is when you build the physical qualities that support in-season performance.' },
    { type: 'multiple_choice', question: 'How should gym volume change from off-season to in-season?', options: ['Reduce by 40-60%', 'Eliminate completely', 'Stay the same', 'Increase by 50%'], correctAnswer: 0, explanation: 'In-season volume drops significantly to accommodate competition and practice demands.' },
    { type: 'multiple_choice', question: 'What is the primary goal of in-season S&C?', options: ['Building maximum strength', 'Maximum volume training', 'Maintaining the physical qualities built in the off-season while supporting sport performance and managing fatigue', 'Peaking for every game'], correctAnswer: 2, explanation: 'In-season S&C maintains fitness, prevents injury, and manages fatigue — building new qualities is secondary to supporting performance and recovery.' },
    { type: 'multiple_choice', question: 'How should training volume change from off-season to in-season?', options: ['Increase volume', 'Reduce volume by 30–50% while maintaining intensity — sufficient stimulus to maintain adaptations without excessive fatigue', 'No change needed', 'Stop training entirely'], correctAnswer: 1, explanation: 'Volume reduction (30–50%) is the primary in-season adjustment — intensity maintenance preserves strength adaptations while reduced volume manages total stress.' },
    { type: 'multiple_choice', question: 'What is a common mistake in in-season training?', options: ['Only stretching', 'Either stopping S&C entirely (losing fitness) or maintaining off-season volume (accumulating fatigue that impairs performance)', 'Training too specifically', 'Training too little'], correctAnswer: 1, explanation: 'Both extremes are problematic — stopping S&C leads to detraining while maintaining off-season volume on top of games creates excessive fatigue.' },
    { type: 'multiple_choice', question: 'How should training be adjusted around game days?', options: ['No adjustment needed', 'Maximum training the day before games', 'Only train on game days', 'Heavy sessions 48–72 hours before games; post-game recovery sessions; structure weekly around the competition schedule'], correctAnswer: 3, explanation: 'The weekly plan revolves around games: heavy S&C early in the week (48–72h before), lighter sessions closer to games, and recovery protocols post-game.' },
    { type: 'multiple_choice', question: 'What is the transition period between seasons?', options: ['A period of maximum intensity', 'A 2–4 week active recovery period with reduced training that allows physical and psychological regeneration', 'A complete break from all activity', 'Immediately start off-season training'], correctAnswer: 1, explanation: 'The transition period (2–4 weeks) allows physical healing and mental refreshment — light activity (cross-training, recreational sport) maintains basic fitness without structured training.' },
  
  ]),
  cq(3, 8, [
    { type: 'multiple_choice', question: 'What is the minimum effective dose (MED)?', options: ['A medical term only', 'The average training load', 'The smallest stimulus that produces meaningful adaptation', 'The maximum training possible'], correctAnswer: 2, explanation: 'Training close to the MED for each quality frees recovery capacity for other priorities.' },
    { type: 'multiple_choice', question: 'How should training qualities be sequenced within a session?', options: ['In any order', 'Conditioning first, speed last', 'Speed/power first (highest neural demand), conditioning last', 'Only one quality per session'], correctAnswer: 2, explanation: 'Neural demands determine optimal sequencing within a single session.' },
    { type: 'multiple_choice', question: 'What is session load calculated as?', options: ['Weight × reps', 'Sets × reps', 'Distance × time', 'RPE × duration in minutes'], correctAnswer: 3, explanation: 'Session RPE × duration provides a simple total load metric across all modalities.' },
    { type: 'multiple_choice', question: 'What acute:chronic workload ratio range minimises injury risk?', options: ['Any ratio is fine', '0.1-0.3', '2.0-3.0', '0.8-1.3'], correctAnswer: 3, explanation: 'Ratios between 0.8 and 1.3 balance adaptation stimulus with manageable injury risk.' },
    { type: 'multiple_choice', question: 'What characterises the naive approach to concurrent training?', options: ['Only focusing on one quality', 'Training everything at maximum volume — leading to overtraining', 'Minimal volume', 'Smart sequencing'], correctAnswer: 1, explanation: 'Maximum volume in everything exceeds recovery capacity and produces mediocre results.' },
    { type: 'multiple_choice', question: 'What is the molecular basis of the interference effect?', options: ['AMPK (activated by endurance) and mTOR (activated by strength) pathways partially inhibit each other', 'It is psychological', 'It does not have a molecular basis', 'Only hormonal'], correctAnswer: 0, explanation: 'AMPK (endurance signalling) can inhibit mTOR (protein synthesis signalling) — this molecular competition underlies the interference effect.' },
    { type: 'multiple_choice', question: 'What is the recommended order when both strength and endurance are trained on the same day?', options: ['Alternate randomly', 'It does not matter', 'Strength before endurance — prioritising the quality most affected by fatigue', 'Endurance first always'], correctAnswer: 2, explanation: 'Strength before endurance is generally recommended — strength and power require neural freshness, while endurance can be performed somewhat fatigued.' },
    { type: 'multiple_choice', question: 'How can you monitor training load in concurrent programmes?', options: ['Track total load using session RPE × duration for both S&C and sport sessions combined', 'Count only gym sessions', 'Only monitor one quality', 'Load monitoring is unnecessary'], correctAnswer: 0, explanation: 'Session RPE × duration provides a total load score — tracking both S&C and sport sessions prevents accumulated overload that neither coach may recognise in isolation.' },
    { type: 'multiple_choice', question: 'What is polarised training and how does it apply to concurrent programmes?', options: ['Training at maximum always', 'Training at medium intensity only', 'The majority of endurance work at low intensity (80%) with small amounts at high intensity (20%) — avoiding the moderate zone', 'Only for elite athletes'], correctAnswer: 2, explanation: 'Polarised training (80% easy / 20% hard) minimises the interference effect — moderate-intensity endurance causes the most interference with strength adaptations.' },
    { type: 'multiple_choice', question: 'What is the key principle for managing concurrent training?', options: ['Prioritise the most important quality, manage total volume, and ensure adequate recovery between conflicting stimuli', 'Train everything maximally', 'Only train one quality per season', 'Ignore the interference effect'], correctAnswer: 0, explanation: 'Successful concurrent training requires clear prioritisation, total volume management, adequate separation between sessions, and recovery monitoring.' },
  
  ]),
];