import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the two questions a needs analysis answers?', options: ['How much and how often', 'What does the sport require and where does the athlete fall short?', 'When to train and when to rest', 'What supplements to take'], correctAnswer: 1, explanation: 'A needs analysis maps sport demands against athlete abilities.' },
    { type: 'multiple_choice', question: 'Why is a needs analysis important?', options: ['It makes training specific to sport demands rather than generic', 'It is required by law', 'It only matters for professionals', 'It replaces training'], correctAnswer: 0, explanation: 'Without it, training becomes generic and fails to address sport-specific needs.' },
    { type: 'multiple_choice', question: 'What determines exercise selection in a sport-specific programme?', options: ['What the coach enjoys', 'The dominant movement patterns identified in the needs analysis', 'What equipment is available', 'Social media trends'], correctAnswer: 1, explanation: 'Exercise selection must reflect the movements that dominate the sport.' },
    { type: 'multiple_choice', question: 'In team sports, do all positions have the same physical demands?', options: ['Yes — they play the same sport', 'No — different positions have different needs analyses', 'Only in football', 'Only in rugby'], correctAnswer: 1, explanation: 'A goalkeeper and midfielder have vastly different physical demands.' },
    { type: 'multiple_choice', question: 'What is the most common mistake in sport-specific training?', options: ['Training too little', 'Training what athletes are already good at while neglecting actual needs', 'Using too much variety', 'Not enough cardio'], correctAnswer: 1, explanation: 'Athletes often gravitate toward their strengths rather than addressing weaknesses.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What is the primary determinant of sprint speed?', options: ['Leg length', 'How much force you can apply to the ground per stride', 'Arm swing speed', 'Breathing technique'], correctAnswer: 1, explanation: 'Ground reaction force during the brief contact time determines speed.' },
    { type: 'multiple_choice', question: 'Why does maximal strength improve sprint performance?', options: ['Stronger athletes apply more force per ground contact', 'Heavier muscles move faster', 'Strength makes you lighter', 'It does not improve sprinting'], correctAnswer: 0, explanation: 'Greater force production per ground contact increases stride length and acceleration.' },
    { type: 'multiple_choice', question: 'What is the minimum rest between maximal sprints for speed development?', options: ['30 seconds', '1 minute', '3-5 minutes', 'No rest needed'], correctAnswer: 2, explanation: 'Full neural recovery requires 3-5 minutes; shorter rest trains conditioning, not speed.' },
    { type: 'multiple_choice', question: 'What is rate of force development?', options: ['Maximum force you can produce', 'How quickly you can reach peak force', 'How long you can sustain force', 'Force per bodyweight'], correctAnswer: 1, explanation: 'In sport, how fast you develop force matters more than absolute peak force.' },
    { type: 'multiple_choice', question: 'What trains deceleration ability?', options: ['Long slow runs', 'Progressive deceleration drills and eccentric strength work', 'Static stretching', 'Isometric holds only'], correctAnswer: 1, explanation: 'Deceleration requires eccentric strength and neuromuscular control.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What distinguishes agility from change of direction speed?', options: ['Nothing — they are the same', 'Agility adds perception and decision-making to physical direction change', 'Agility is slower', 'CODS requires more skill'], correctAnswer: 1, explanation: 'True agility requires reading and reacting to unpredictable stimuli.' },
    { type: 'multiple_choice', question: 'What is the most important physical quality for direction change?', options: ['Concentric quad strength', 'Eccentric braking strength — the ability to decelerate', 'Flexibility', 'Endurance'], correctAnswer: 1, explanation: 'Deceleration is the foundation of safe, effective direction change.' },
    { type: 'multiple_choice', question: 'Why are elite athletes faster in reactive agility tests but not pre-planned tests?', options: ['They are just fitter', 'They read cues earlier and process information faster', 'They are stronger', 'They train more hours'], correctAnswer: 1, explanation: 'Perceptual speed — not physical speed — separates elite from average in sport.' },
    { type: 'multiple_choice', question: 'What should agility drills include to be effective?', options: ['Only cones', 'An unpredictable stimulus requiring read-and-react', 'Maximum distance', 'Timed laps'], correctAnswer: 1, explanation: 'Reactive elements transform physical drills into true agility training.' },
    { type: 'multiple_choice', question: 'What is the role of ankle stiffness in direction change?', options: ['It should be minimised', 'Stiff ankles transmit force efficiently during rapid cuts', 'Only matters for runners', 'Flexibility is more important'], correctAnswer: 1, explanation: 'Ankle stiffness enables rapid force transmission during sharp direction changes.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What is the interference effect?', options: ['Simultaneous strength and endurance training can produce inferior adaptations in both', 'Two exercises interfering with each other', 'Radio interference in the gym', 'Muscle confusion'], correctAnswer: 0, explanation: 'The mTOR and AMPK pathways partially inhibit each other during concurrent training.' },
    { type: 'multiple_choice', question: 'How can you minimise interference between strength and endurance?', options: ['Never do both', 'Separate sessions by at least 6 hours or train on different days', 'Do them in the same session always', 'Only do endurance training'], correctAnswer: 1, explanation: 'Temporal separation reduces molecular conflict between adaptation pathways.' },
    { type: 'multiple_choice', question: 'What endurance method best simulates team sport demands?', options: ['Long slow distance running', 'Yoga', 'Repeated sprint ability training', 'Swimming'], correctAnswer: 2, explanation: 'RSA directly simulates the repeated high-intensity efforts of match play.' },
    { type: 'multiple_choice', question: 'Why might cycling be preferred over running for aerobic development?', options: ['It is easier', 'Lower eccentric stress means less interference with strength adaptations', 'It burns more calories', 'It does not work the legs'], correctAnswer: 1, explanation: 'Cycling removes the eccentric muscle damage that running produces.' },
    { type: 'multiple_choice', question: 'If an athlete is losing strength despite training, what should you check first?', options: ['Their supplement stack', 'Their endurance training volume', 'Their gym shoes', 'Their music playlist'], correctAnswer: 1, explanation: 'Excessive running volume is the most common reason for strength loss in field sport athletes.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'What is the stretch-shortening cycle?', options: ['A stretching routine', 'Muscles produce more concentric force when preceded by rapid eccentric contraction', 'A yoga sequence', 'A cardio workout'], correctAnswer: 1, explanation: 'The SSC stores and releases elastic energy like a spring.' },
    { type: 'multiple_choice', question: 'What is the prerequisite before progressing to depth jumps?', options: ['Good flexibility', 'A solid strength base — minimum 1.5x bodyweight squat', 'Being tall', 'Having long legs'], correctAnswer: 1, explanation: 'Depth jumps require sufficient strength to absorb and redirect high forces safely.' },
    { type: 'multiple_choice', question: 'What indicates good reactive strength during plyometrics?', options: ['Slow heavy ground contacts', 'Quick sharp ground contacts like a basketball bouncing', 'Loud landing sounds', 'Maximum height only'], correctAnswer: 1, explanation: 'Quick, sharp contacts indicate efficient elastic energy use.' },
    { type: 'multiple_choice', question: 'When should plyometrics be performed in a session?', options: ['After strength work', 'At the end of training', 'Early when the nervous system is fresh', 'During cardio'], correctAnswer: 2, explanation: 'Plyometrics require peak neural drive, which diminishes with fatigue.' },
    { type: 'multiple_choice', question: 'What is the total foot contact guideline for advanced athletes?', options: ['Unlimited', '120-140 per session', '500+ per session', '10 per session'], correctAnswer: 1, explanation: 'Managing total contacts ensures quality and reduces injury risk.' },
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'What is the fundamental principle of sport-specific programming?', options: ['Maximise gym time', 'Train what you need most, maintain what you have enough of, never interfere with practice quality', 'Always do more volume', 'Copy professional athletes\' programmes'], correctAnswer: 1, explanation: 'The gym supports the field — not the other way around.' },
    { type: 'multiple_choice', question: 'In what order should training qualities be programmed within a session?', options: ['Conditioning → strength → power', 'Random order', 'Speed → power → strength → hypertrophy/conditioning', 'Strength first always'], correctAnswer: 2, explanation: 'Neurological demand determines order: speed and power require the freshest nervous system.' },
    { type: 'multiple_choice', question: 'When should the last heavy gym session occur relative to competition?', options: ['The day before', 'At least 3 days before match day', 'Match morning', 'Does not matter'], correctAnswer: 1, explanation: 'Heavy training close to competition interferes with match performance.' },
    { type: 'multiple_choice', question: 'What should you ask about every training session?', options: ['How long did it take?', 'Is this making the athlete better at their sport or just more tired?', 'Did they sweat enough?', 'Was it hard enough?'], correctAnswer: 1, explanation: 'If gym training creates fatigue for practice, the programme has failed.' },
    { type: 'multiple_choice', question: 'Why should exercise variety be limited in sport programmes?', options: ['To save time', 'Consistent exercises progressed over months transfer better than constantly rotating novel exercises', 'Variety causes injury', 'Athletes get confused easily'], correctAnswer: 1, explanation: 'Getting strong at specific patterns produces more sport transfer than exercise variety.' },
  ]),
  cq(3, 7, [
    { type: 'multiple_choice', question: 'What are the three phases of an annual training plan?', options: ['Morning, afternoon, evening', 'Easy, medium, hard', 'Off-season (build), pre-season (transition), in-season (maintain)', 'Weeks, months, years'], correctAnswer: 2, explanation: 'Each phase has different priorities for volume, intensity, and physical development.' },
    { type: 'multiple_choice', question: 'During in-season training, what should be maintained?', options: ['Volume', 'Intensity — reducing it causes detraining faster than reducing volume', 'Both equally', 'Neither — focus on competition only'], correctAnswer: 1, explanation: 'Maintaining intensity with reduced volume preserves adaptations with less fatigue.' },
    { type: 'multiple_choice', question: 'How much volume is needed to maintain a physical quality?', options: ['The same as was used to develop it', 'About one-third of the development volume', 'Double the development volume', 'No volume — qualities maintain themselves'], correctAnswer: 1, explanation: 'Research shows one-third of development volume is often sufficient for maintenance.' },
    { type: 'multiple_choice', question: 'What is the priority during the off-season?', options: ['Competition preparation', 'Physical development — building strength, muscle, and addressing weaknesses', 'Rest only', 'Technical skill work only'], correctAnswer: 1, explanation: 'Off-season is when you build the physical qualities that support in-season performance.' },
    { type: 'multiple_choice', question: 'How should gym volume change from off-season to in-season?', options: ['Increase by 50%', 'Stay the same', 'Reduce by 40-60%', 'Eliminate completely'], correctAnswer: 2, explanation: 'In-season volume drops significantly to accommodate competition and practice demands.' },
  ]),
  cq(3, 8, [
    { type: 'multiple_choice', question: 'What is the minimum effective dose (MED)?', options: ['The maximum training possible', 'The smallest stimulus that produces meaningful adaptation', 'The average training load', 'A medical term only'], correctAnswer: 1, explanation: 'Training close to the MED for each quality frees recovery capacity for other priorities.' },
    { type: 'multiple_choice', question: 'How should training qualities be sequenced within a session?', options: ['Conditioning first, speed last', 'Speed/power first (highest neural demand), conditioning last', 'In any order', 'Only one quality per session'], correctAnswer: 1, explanation: 'Neural demands determine optimal sequencing within a single session.' },
    { type: 'multiple_choice', question: 'What is session load calculated as?', options: ['Sets × reps', 'Weight × reps', 'RPE × duration in minutes', 'Distance × time'], correctAnswer: 2, explanation: 'Session RPE × duration provides a simple total load metric across all modalities.' },
    { type: 'multiple_choice', question: 'What acute:chronic workload ratio range minimises injury risk?', options: ['0.1-0.3', '0.8-1.3', '2.0-3.0', 'Any ratio is fine'], correctAnswer: 1, explanation: 'Ratios between 0.8 and 1.3 balance adaptation stimulus with manageable injury risk.' },
    { type: 'multiple_choice', question: 'What characterises the naive approach to concurrent training?', options: ['Smart sequencing', 'Training everything at maximum volume — leading to overtraining', 'Minimal volume', 'Only focusing on one quality'], correctAnswer: 1, explanation: 'Maximum volume in everything exceeds recovery capacity and produces mediocre results.' },
  ]),
];