import type { UnitAssessment } from '../types';

export const level4Unit4Assessment: UnitAssessment = {
  unitNumber: 4,
  title: 'Leadership, Communication & Lifelong Learning — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most effective type of cueing for movement performance?', options: ['No cueing', 'Verbal punishment', 'Internal cues', 'External cues focusing on movement effects'], correctAnswer: 3, explanation: 'External cues allow natural self-organisation of efficient movement.' },
    { type: 'multiple_choice', question: 'What keeps people committed to fitness more than the programme itself?', options: ['Location', 'Equipment quality', 'Price', 'Feeling supported, heard, and genuinely cared about'], correctAnswer: 3, explanation: 'People quit because they feel unsupported, not because of bad programmes.' },
    { type: 'multiple_choice', question: 'What is the primary ethical obligation of a fitness professional?', options: ['Social media presence', 'Client acquisition', 'Revenue generation', 'Do no harm'], correctAnswer: 3, explanation: 'Safety and wellbeing must always be the first priority.' },
    { type: 'multiple_choice', question: 'When should a coach refer someone to a specialist?', options: ['Only when asked', 'When the situation exceeds their scope of practice or qualifications', 'Never — coaches can handle everything', 'Only for serious injuries'], correctAnswer: 1, explanation: 'Recognising scope of practice is a professional strength, not a weakness.' },
    { type: 'multiple_choice', question: 'What is the best approach to evidence-based practice?', options: ['Only use the newest studies', 'Follow research blindly', 'Ignore research — experience is everything', 'Integrate scientific evidence with practical experience and individual preferences'], correctAnswer: 3, explanation: 'EBP combines three pillars for the best training decisions.' },
    { type: 'multiple_choice', question: 'What is the myth about resistance training and adolescents?', options: ['That they cannot learn technique', 'It is too easy for them', 'That it stunts growth — which has been comprehensively debunked', 'That it is too expensive'], correctAnswer: 2, explanation: 'Research supports safe, supervised resistance training for adolescents.' },
    { type: 'multiple_choice', question: 'Which fitness business model is most scalable?', options: ['Selling supplements', 'Group classes only', 'Online coaching — it removes geographic and time constraints', 'One-to-one training only'], correctAnswer: 2, explanation: 'Understanding business models helps you evaluate fitness services as an informed consumer.' },
    { type: 'multiple_choice', question: 'What characterises the hierarchy of evidence?', options: ['All evidence is equal', 'Case studies are most reliable', 'Systematic reviews > RCTs > cohort studies > case studies > expert opinion', 'Expert opinion is highest'], correctAnswer: 2, explanation: 'Higher-level evidence provides more confidence in findings.' },
    { type: 'multiple_choice', question: 'How should feedback frequency change as a learner becomes more skilled?', options: ['Stop entirely', 'Decrease — reduced feedback builds self-correction ability', 'Stay the same', 'Increase constantly'], correctAnswer: 1, explanation: 'Advanced learners benefit from less frequent feedback to develop independence.' },
    { type: 'multiple_choice', question: 'What is the best way to evaluate if a new training method works?', options: ['Ask social media', 'Assume it works because a study supports it', 'Test it systematically and let measurable outcomes guide your decision', 'Try it once'], correctAnswer: 2, explanation: 'Systematic testing with measurable outcomes provides the most relevant personal evidence.' },
    { type: 'multiple_choice', question: 'Where does the most meaningful fitness impact often happen?', options: ['Focusing on aesthetics only', 'Training competitive athletes exclusively', 'Only working with genetically gifted people', 'Helping anyone — from the 65-year-old gaining independence to the teenager finding confidence'], correctAnswer: 3, explanation: 'Transformations in quality of life and confidence matter more than any personal record.' },
    { type: 'multiple_choice', question: 'What is the Unbreakable standard for professional practice?', options: ['Knowledge in service of others, applied with integrity, refined through lifelong learning', 'Maximum revenue', 'Never showing weakness', 'Physical invincibility'], correctAnswer: 0, explanation: 'The standard combines ethical service with continuous professional growth.' },
  ],
};