import type { UnitAssessment } from '../types';

export const level4Unit2Assessment: UnitAssessment = {
  unitNumber: 2,
  title: 'Biomechanics & Injury Prevention — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most predictive factor for lifting injuries?', options: ['Load management — training load exceeding tissue tolerance', 'Body composition', 'Age', 'Imperfect technique'], correctAnswer: 0, explanation: 'Load management predicts injury risk better than technique quality.' },
    { type: 'multiple_choice', question: 'Why is prehabilitation more effective than rehabilitation?', options: ['It does not require knowledge', 'It is cheaper', 'Proactively strengthening vulnerable structures prevents injuries before they occur', 'It requires no equipment'], correctAnswer: 2, explanation: 'Prevention is always more effective and less costly than treatment.' },
    { type: 'multiple_choice', question: 'What determines whether conventional or sumo deadlift suits a lifter?', options: ['Personal preference only', 'Arm-to-leg ratio and hip structure', 'Which is more impressive', 'Whichever the coach recommends'], correctAnswer: 1, explanation: 'Limb proportions determine the most mechanically efficient pulling style.' },
    { type: 'multiple_choice', question: 'How long do tendons need to recover between heavy loading sessions?', options: ['48-72 hours', '24 hours', 'No specific time needed', 'One week'], correctAnswer: 0, explanation: 'Tendon tissue turnover is slower than muscle, requiring extended recovery.' },
    { type: 'multiple_choice', question: 'What is the role of eccentric strength in sport?', options: ['Enables safe deceleration and direction change, reducing injury risk', 'Only matters for rehabilitation', 'It is not important', 'It slows athletes down'], correctAnswer: 0, explanation: 'Eccentric strength is the foundation of deceleration and injury prevention.' },
    { type: 'multiple_choice', question: 'What mobility work is most effective for long-term gains?', options: ['30-minute flexibility routines', 'Loaded stretching — exercises at full range under moderate load', 'No mobility work is effective', 'Extended static stretching before training'], correctAnswer: 1, explanation: 'Loaded stretching simultaneously improves mobility and end-range strength.' },
    { type: 'multiple_choice', question: 'What does a movement screen reliably identify?', options: ['Optimal 1RM predictions', 'Exact injury mechanisms', 'Future injuries', 'Movement limitations that can be addressed through programming'], correctAnswer: 3, explanation: 'Screens guide programme design by identifying limitations, not predicting injuries.' },
    { type: 'multiple_choice', question: 'What happens if muscles adapt faster than tendons?', options: ['Nothing — the body self-regulates', 'Muscles become strong enough to overload tendons, increasing injury risk', 'Tendons always adapt first', 'Only affects beginners'], correctAnswer: 1, explanation: 'The adaptation mismatch makes gradual progression essential for joint safety.' },
    { type: 'multiple_choice', question: 'What nutrition supports tendon health?', options: ['Creatine only', 'Carbohydrates only', 'Collagen with vitamin C 30-60 minutes before training, adequate protein, omega-3s', 'No nutrition affects tendons'], correctAnswer: 2, explanation: 'Specific nutrients support connective tissue repair and remodelling.' },
    { type: 'multiple_choice', question: 'Pain during rehabilitation up to what level is generally acceptable?', options: ['3/10 if it settles within 24 hours', 'Any level is fine', '7/10', '0/10 — no pain allowed'], correctAnswer: 0, explanation: 'Mild pain that resolves quickly is normal during structured return to training.' },
    { type: 'multiple_choice', question: 'What is the recommended pulling-to-pressing ratio for shoulder health?', options: ['3:1', '2:1 pulling to pressing', '1:1', '1:2'], correctAnswer: 1, explanation: 'Doubling pulling volume relative to pressing balances shoulder mechanics.' },
    { type: 'multiple_choice', question: 'What is the primary benefit of movement variation for joint health?', options: ['Different angles reduce repetitive loading patterns that accelerate wear', 'It improves flexibility only', 'It builds more muscle', 'It is more interesting'], correctAnswer: 0, explanation: 'Varied loading patterns distribute stress across joint surfaces more evenly.' },
  ],
};