import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const level4Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What is the main limitation of linear periodisation for advanced lifters?', options: ['It requires too much equipment', 'Too easy to follow', 'It only works for beginners', 'Extended sub-maximal phases can lead to detraining of earlier qualities'], correctAnswer: 3, explanation: 'By the time you reach peak strength, you may have lost muscle from the hypertrophy phase.' },
    { type: 'multiple_choice', question: 'Which periodisation model varies training variables daily?', options: ['Daily undulating periodisation', 'Block periodisation', 'Conjugate method', 'Linear periodisation'], correctAnswer: 0, explanation: 'DUP varies rep schemes each session within a training week.' },
    { type: 'multiple_choice', question: 'For a beginner with less than 2 years of training, which model is most appropriate?', options: ['Linear periodisation with 4-6 week phases', 'Conjugate method', 'Daily undulating periodisation', 'Block periodisation'], correctAnswer: 0, explanation: 'Linear periodisation suits beginners due to its predictable progressive structure.' },
    { type: 'multiple_choice', question: 'What is the key advantage of non-linear periodisation?', options: ['It is easier to follow', 'It requires less planning', 'Stimulus variation keeps the adaptive signal strong across multiple qualities', 'It uses lighter weights'], correctAnswer: 2, explanation: 'Varying rep ranges and intensities prevents diminishing returns from repeated identical stimuli.' },
    { type: 'multiple_choice', question: 'What determines the best periodisation model for an individual?', options: ['Training age, goals, competition schedule, and individual response', 'Social media recommendations', 'Whatever is most popular', 'Always use the most complex model'], correctAnswer: 0, explanation: 'The best model depends on individual factors, not universal superiority.' },
    { type: 'multiple_choice', question: 'What is periodisation?', options: ['Random training variation', 'Training the same way every day', 'Only resting periodically', 'The systematic planning of training variables across defined time periods to optimise adaptation'], correctAnswer: 3, explanation: 'Periodisation systematically manipulates volume, intensity, and exercise selection across time periods (microcycles, mesocycles, macrocycles) to optimise long-term progress.' },
    { type: 'multiple_choice', question: 'What is a mesocycle?', options: ['A full year of training', 'A warm-up protocol', 'A single workout', 'A training block typically lasting 3–6 weeks with a specific focus'], correctAnswer: 3, explanation: 'A mesocycle is a training block of 3–6 weeks with a primary focus (e.g., hypertrophy, strength, or peaking) — the building block of periodised programmes.' },
    { type: 'multiple_choice', question: 'Why does linear periodisation become less effective for advanced lifters?', options: ['Training one quality for weeks causes others to detrain — advanced lifters need concurrent stimulus maintenance', 'It is always effective', 'It is too hard', 'Advanced lifters do not need periodisation'], correctAnswer: 0, explanation: 'Advanced lifters lose adaptations faster — spending 4–6 weeks in a hypertrophy phase can detrain maximal strength, and vice versa.' },
    { type: 'multiple_choice', question: 'What is a macrocycle?', options: ['A type of warm-up', 'A long-term training plan typically spanning several months to a full year', 'A short workout', 'A single exercise'], correctAnswer: 1, explanation: 'A macrocycle is the largest planning unit — typically 6–12 months — encompassing multiple mesocycles that build toward a primary goal or competition.' },
    { type: 'multiple_choice', question: 'What is a microcycle?', options: ['A three-month block', 'A single rep', 'A yearly plan', 'The smallest training unit, typically one training week'], correctAnswer: 3, explanation: 'A microcycle is typically one training week — the smallest unit of periodisation containing individual training sessions.' },
  
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'In a typical DUP structure, what does the hypertrophy day target?', options: ['1-3 reps at 90%+', '5 reps at 80%', '8-12 reps at 65-75%', '20+ reps at 50%'], correctAnswer: 2, explanation: 'DUP hypertrophy days use moderate loads for higher reps.' },
    { type: 'multiple_choice', question: 'What is a common mistake in DUP training?', options: ['Varying rep ranges', 'Treating every session with maximal effort instead of respecting RPE targets', 'Training three times per week', 'Using compound movements'], correctAnswer: 1, explanation: 'Consistently hitting RPE 10 on every session defeats the purpose of undulation.' },
    { type: 'multiple_choice', question: 'What should you track to ensure DUP is working?', options: ['RPE alongside load in a logbook', 'Social media followers', 'Only bodyweight', 'Time in the gym'], correctAnswer: 0, explanation: 'Honest RPE tracking is essential for DUP to regulate intensity properly.' },
    { type: 'multiple_choice', question: 'How often should you deload in a DUP programme?', options: ['Every 4th week', 'Every week', 'Every 8 weeks', 'Never'], correctAnswer: 0, explanation: 'A deload every 4th week manages accumulated fatigue.' },
    { type: 'multiple_choice', question: 'What is the progression strategy in DUP?', options: ['Always lift the same weight', 'Decrease weights each week', 'Increase loads by 2.5-5% every 2-3 weeks if RPE targets are met', 'Random weight selection'], correctAnswer: 2, explanation: 'Progressive overload in DUP follows RPE-guided load increases.' },
    { type: 'multiple_choice', question: 'What is a typical DUP weekly structure?', options: ['High reps every day', 'Varying rep ranges across the week — e.g., Monday: 3×5 heavy, Wednesday: 3×10 hypertrophy, Friday: 3×3 strength', 'Same reps every day', 'Only training once per week'], correctAnswer: 1, explanation: 'DUP changes the stimulus each session — a common structure alternates hypertrophy (8–12), strength (3–6), and power (1–3) days within each week.' },
    { type: 'multiple_choice', question: 'What is the main advantage of DUP over linear periodisation?', options: ['Multiple training qualities are developed simultaneously within each week, preventing detraining', 'It is easier to programme', 'It uses lighter weights', 'It requires less recovery'], correctAnswer: 0, explanation: 'DUP trains all qualities within each microcycle — preventing the detraining that occurs in linear models where one quality is neglected for weeks.' },
    { type: 'multiple_choice', question: 'Who benefits most from DUP?', options: ['Only bodybuilders', 'Only powerlifters', 'Intermediate to advanced lifters who need to maintain multiple qualities simultaneously', 'Complete beginners'], correctAnswer: 2, explanation: 'Intermediate-to-advanced lifters benefit most from DUP — beginners respond to almost any programme, but advanced lifters need varied stimuli to continue adapting.' },
    { type: 'multiple_choice', question: 'How should volume be managed across DUP sessions?', options: ['Only track sets, not reps', 'Total weekly volume matters most — individual session volume varies based on intensity and rep range', 'Maximum volume every session', 'Equal volume every session'], correctAnswer: 1, explanation: 'Weekly volume is the primary driver — heavy days have fewer total reps but higher intensity, while hypertrophy days have more reps at lower intensity.' },
    { type: 'multiple_choice', question: 'How does DUP handle progressive overload?', options: ['Only increase volume', 'No overload is needed', 'Randomly change weights', 'Progress is applied within each rep range across weeks — e.g., adding 2.5kg to the 5-rep day each week'], correctAnswer: 3, explanation: 'Progressive overload in DUP occurs within each rep-range bracket — gradually increasing load or reps at each intensity level across microcycles.' },
  
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Who developed block periodisation?', options: ['Mike Tuchscherer', 'Louie Simmons', 'Carol Dweck', 'Vladimir Issurin'], correctAnswer: 3, explanation: 'Block periodisation was developed by Vladimir Issurin.' },
    { type: 'multiple_choice', question: 'What is the correct sequence of blocks?', options: ['Realisation → Transmutation → Accumulation', 'Accumulation → Transmutation → Realisation', 'Transmutation → Accumulation → Realisation', 'Any order works'], correctAnswer: 1, explanation: 'Blocks progress from volume (accumulation) through intensity (transmutation) to peak (realisation).' },
    { type: 'multiple_choice', question: 'What are residual training effects?', options: ['Injuries from overtraining', 'Effects of caffeine on training', 'The persistence of adaptations after training stops', 'Side effects of supplements'], correctAnswer: 2, explanation: 'After you stop training a quality, its adaptations persist for a predictable period.' },
    { type: 'multiple_choice', question: 'Which quality decays fastest after training ceases?', options: ['Muscle mass', 'Flexibility', 'Aerobic endurance', 'Speed and power'], correctAnswer: 3, explanation: 'Speed and power decay in 5-10 days, which is why they are trained last.' },
    { type: 'multiple_choice', question: 'What is the accumulation block designed to build?', options: ['Competition readiness', 'Muscle mass, work capacity, and general strength through high volume', 'Peak performance', 'Speed and power'], correctAnswer: 1, explanation: 'Accumulation uses high volume at moderate intensity to build the foundation.' },
    { type: 'multiple_choice', question: 'What defines block periodisation?', options: ['Random exercise selection', 'Only training for 1 week', 'Training all qualities equally', 'Concentrating on one primary training quality per block while maintaining others with minimal volume'], correctAnswer: 3, explanation: 'Block periodisation focuses training stress on one quality (accumulation → transmutation → realisation) while maintaining others with reduced volume.' },
    { type: 'multiple_choice', question: 'What are the three phases in Issurin\'s block periodisation model?', options: ['Warm-up, training, cool-down', 'Accumulation (high volume), transmutation (sport-specific intensity), and realisation (peaking/competition)', 'Strength, power, endurance', 'Beginner, intermediate, advanced'], correctAnswer: 1, explanation: 'Accumulation builds general fitness with high volume; transmutation converts it to sport-specific capacity; realisation peaks performance for competition.' },
    { type: 'multiple_choice', question: 'Why is block periodisation suited to advanced athletes?', options: ['It is simpler', 'It uses lighter weights', 'It requires less time', 'Advanced athletes need concentrated loading to overcome higher adaptation thresholds'], correctAnswer: 3, explanation: 'Advanced athletes have higher adaptation thresholds — concentrated loading in block periodisation provides sufficient overload to drive continued progress.' },
    { type: 'multiple_choice', question: 'What is the residual training effect?', options: ['Fatigue after training', 'The duration a training quality is retained after direct training ceases — varies by quality', 'Delayed onset muscle soreness', 'A warm-up effect'], correctAnswer: 1, explanation: 'Residual effects vary: aerobic endurance lasts 25–30 days, maximal strength 25–30 days, but speed/power only 5–8 days — informing block sequencing.' },
    { type: 'multiple_choice', question: 'How long is a typical block in block periodisation?', options: ['6 months', '2–4 weeks, with each block having a primary training emphasis', '1 year', '1 day'], correctAnswer: 1, explanation: 'Blocks typically last 2–4 weeks — short enough to prevent excessive detraining of non-emphasised qualities while allowing concentrated adaptation.' },
  
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What is the defining feature of the conjugate method?', options: ['Concurrent development of maximal strength and speed-strength', 'Only using machines', 'Training only once per week', 'Always using the same exercises'], correctAnswer: 0, explanation: 'The conjugate method trains multiple strength qualities simultaneously.' },
    { type: 'multiple_choice', question: 'Why does the conjugate method rotate max effort exercises?', options: ['To make training more fun', 'To prevent accommodation from repeated maximal loading of the same pattern', 'To confuse muscles', 'Because coaches get bored'], correctAnswer: 1, explanation: 'Accommodation (diminishing returns) occurs after 1-3 weeks of the same exercise at max loads.' },
    { type: 'multiple_choice', question: 'What percentage range is used for dynamic effort work?', options: ['30-40%', '80-90%', '90-100%', '50-65% with accommodating resistance'], correctAnswer: 3, explanation: 'Dynamic effort uses 50-65% with bands/chains to develop speed-strength.' },
    { type: 'multiple_choice', question: 'How often do dynamic effort exercises change?', options: ['Every 3-week wave', 'Never', 'Every session', 'Every 6 months'], correctAnswer: 0, explanation: 'DE exercises use 3-week waves with incrementally increasing percentages.' },
    { type: 'multiple_choice', question: 'What modification is needed for raw lifters using the conjugate method?', options: ['No modifications needed', 'Only use machines', 'Slightly higher DE percentages and more muscular development emphasis', 'Train once per week'], correctAnswer: 2, explanation: 'Raw lifters need higher DE percentages and more hypertrophy work without gear protection.' },
    { type: 'multiple_choice', question: 'What is the conjugate method?', options: ['A system using max effort, dynamic effort, and repetition effort methods within each training week', 'A bodybuilding programme', 'Only heavy singles', 'Training with a partner'], correctAnswer: 0, explanation: 'The conjugate method (Westside Barbell) trains maximal strength (max effort), speed-strength (dynamic effort), and hypertrophy (repetition effort) within each week.' },
    { type: 'multiple_choice', question: 'What is a max effort day?', options: ['Training to failure on every set', 'Working up to a 1–3 rep max on a main lift or variation — rotated every 1–3 weeks to prevent accommodation', 'High rep training', 'Cardio only'], correctAnswer: 1, explanation: 'Max effort days involve working to a 1–3RM on a main lift variation — the exercise rotates every 1–3 weeks to prevent neural accommodation.' },
    { type: 'multiple_choice', question: 'What is dynamic effort training?', options: ['Slow controlled reps', 'High rep sets', 'Lifting submaximal loads (50–60% 1RM) with maximum speed to develop rate of force development', 'Only bodyweight exercises'], correctAnswer: 2, explanation: 'Dynamic effort uses submaximal loads moved at maximal velocity — developing rate of force development and compensatory acceleration.' },
    { type: 'multiple_choice', question: 'Why are exercise variations rotated in the conjugate system?', options: ['To prevent accommodation — the body adapts to specific movement patterns after 1–3 weeks at high intensity', 'To prevent boredom only', 'It is not necessary', 'Random variety'], correctAnswer: 0, explanation: 'The law of accommodation: the body stops adapting to repeated identical stimuli — rotating exercises maintains the adaptive stimulus.' },
    { type: 'multiple_choice', question: 'What role do accommodating resistance tools play in the conjugate method?', options: ['They are only for rehabilitation', 'Bands and chains alter the strength curve, increasing load at lockout where leverage is greatest', 'They replace free weights', 'None'], correctAnswer: 1, explanation: 'Bands and chains increase resistance through the range of motion — matching the natural strength curve and training lockout strength and acceleration.' },
  
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What does RPE 8 mean in resistance training?', options: ['Eight sets remaining', '80% of 1RM', '8 reps completed', 'Two reps left in reserve'], correctAnswer: 3, explanation: 'RPE 8 means the set was hard but two more reps could have been performed.' },
    { type: 'multiple_choice', question: 'Why is percentage-based programming limited?', options: ['It is too simple', 'It requires maths', 'It only works for beginners', 'It assumes 1RM is fixed and daily capacity is constant, which is untrue'], correctAnswer: 3, explanation: 'Strength fluctuates 5-15% daily based on sleep, stress, and fatigue.' },
    { type: 'multiple_choice', question: 'What does velocity-based training measure?', options: ['Heart rate', 'Bar speed during each rep', 'Body temperature', 'Time between sets'], correctAnswer: 1, explanation: 'VBT uses devices to measure bar velocity as an objective effort indicator.' },
    { type: 'multiple_choice', question: 'How long does it typically take to calibrate RPE accurately?', options: ['It cannot be learned', 'One session', '4-6 weeks of conscious practice', 'One year'], correctAnswer: 2, explanation: 'Most people need 4-6 weeks of practice before RPE becomes reliably accurate.' },
    { type: 'multiple_choice', question: 'What is a fatigue stop in autoregulated training?', options: ['A mandatory rest day', 'Stopping when RPE reaches a target, naturally adjusting volume to daily readiness', 'Stopping when you feel tired', 'A type of deload'], correctAnswer: 1, explanation: 'Fatigue stops adjust volume based on actual daily performance.' },
    { type: 'multiple_choice', question: 'What is RPE in strength training?', options: ['Repetition Programming Effect', 'Rate of Perceived Exertion — a subjective scale indicating how close a set was to failure', 'Rest Period Estimation', 'Reps Per Exercise'], correctAnswer: 1, explanation: 'RPE (typically 1–10 scale) measures proximity to failure: RPE 10 = failure, RPE 8 = could have done 2 more reps. It allows daily autoregulation.' },
    { type: 'multiple_choice', question: 'What is Reps in Reserve (RIR)?', options: ['The estimated number of additional reps you could perform before failure', 'A recovery protocol', 'A supplement timing system', 'The number of sets remaining'], correctAnswer: 0, explanation: 'RIR is the inverse of RPE proximity to failure — RIR 2 means you could do 2 more reps (equivalent to RPE 8).' },
    { type: 'multiple_choice', question: 'Why is autoregulation superior to fixed percentages for advanced lifters?', options: ['Fixed percentages are always better', 'It is not superior', 'Daily readiness varies — autoregulation accounts for sleep, stress, nutrition, and recovery that fixed percentages cannot', 'Only for beginners'], correctAnswer: 2, explanation: 'Daily performance fluctuates by 5–10% based on sleep, stress, and recovery — autoregulation adjusts loading to match actual daily capacity.' },
    { type: 'multiple_choice', question: 'What RPE should most working sets be performed at for strength development?', options: ['RPE 7–9 — hard enough to drive adaptation but leaving a buffer to manage fatigue', 'RPE 3–5', 'RPE 10 always', 'RPE does not matter'], correctAnswer: 0, explanation: 'Most productive strength work occurs at RPE 7–9 — challenging enough to stimulate adaptation while managing fatigue accumulation and injury risk.' },
    { type: 'multiple_choice', question: 'How do you calibrate RPE accuracy?', options: ['Ask someone else', 'Regular AMRAP sets and singles at RPE 10 help calibrate your subjective effort perception against actual performance', 'It is always accurate', 'Only use fixed weights'], correctAnswer: 1, explanation: 'Periodic AMRAP (As Many Reps As Possible) sets test actual capacity against estimated — improving the accuracy of day-to-day RPE ratings.' },
  
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'In the fitness-fatigue model, what is observed performance?', options: ['Neither', 'Just fitness', 'Just fatigue', 'The difference between accumulated fitness and accumulated fatigue'], correctAnswer: 3, explanation: 'Performance = fitness minus fatigue. Deloads allow fitness to be expressed.' },
    { type: 'multiple_choice', question: 'Which deload type is most common and effective?', options: ['Intensity deload only', 'Volume deload — reduce sets by 40-60% while maintaining intensity', 'Complete rest', 'Active recovery only'], correctAnswer: 1, explanation: 'Volume deloads maintain neural patterns while reducing mechanical stress.' },
    { type: 'multiple_choice', question: 'What happens if you delay deloading too long?', options: ['You get stronger faster', 'Your joints become healthier', 'Nothing — deloads are unnecessary', 'A slightly premature deload costs one easy week; delayed deloading can cost months of recovery'], correctAnswer: 3, explanation: 'It is always better to deload slightly early than to risk overtraining.' },
    { type: 'multiple_choice', question: 'How often should advanced lifters typically deload?', options: ['Every 3-4 weeks', 'Never', 'Only when injured', 'Every 12 weeks'], correctAnswer: 0, explanation: 'Advanced lifters training at high intensities may need deloads every 3-4 weeks.' },
    { type: 'multiple_choice', question: 'What is supercompensation?', options: ['Performance exceeding baseline when fatigue dissipates faster than fitness during a deload', 'Taking extra supplements', 'Training twice per day', 'A type of periodisation'], correctAnswer: 0, explanation: 'When fatigue clears during a deload, the underlying fitness temporarily exceeds baseline.' },
    { type: 'multiple_choice', question: 'What is the purpose of a deload week?', options: ['To dissipate accumulated fatigue while maintaining fitness — allowing supercompensation', 'To test maximal strength', 'It is unnecessary', 'To skip training'], correctAnswer: 0, explanation: 'Deloads reduce training stress to allow fatigue dissipation — fitness is maintained while accumulated fatigue drops, resulting in supercompensation.' },
    { type: 'multiple_choice', question: 'What is the fitness-fatigue model?', options: ['Performance = fitness minus fatigue — both accumulate from training, but fatigue dissipates faster during deloads', 'A body composition model', 'A cardio programme', 'A nutrition framework'], correctAnswer: 0, explanation: 'The fitness-fatigue model shows that training simultaneously builds fitness and fatigue — during a deload, fatigue drops faster than fitness, revealing true performance.' },
    { type: 'multiple_choice', question: 'How should volume and intensity change during a deload?', options: ['Increase both', 'Reduce intensity but increase volume', 'Stop training entirely', 'Reduce volume by 40–60% while maintaining or slightly reducing intensity to preserve neural adaptations'], correctAnswer: 3, explanation: 'Volume reduction (40–60%) is the primary deload mechanism — intensity can be maintained or slightly reduced to preserve strength and neural adaptations.' },
    { type: 'multiple_choice', question: 'How often should deloads be programmed?', options: ['Every week', 'Every 3–6 weeks depending on training intensity, individual recovery capacity, and training age', 'Only once a year', 'Never'], correctAnswer: 1, explanation: 'Deload frequency depends on training intensity and individual recovery — typically every 3–4 weeks for advanced lifters, every 5–6 for intermediates.' },
    { type: 'multiple_choice', question: 'What is proactive vs reactive deloading?', options: ['Only reactive deloads work', 'Only proactive deloads work', 'Proactive deloads are pre-planned; reactive deloads are triggered by performance decline or fatigue symptoms', 'They are the same'], correctAnswer: 2, explanation: 'Proactive deloads (planned every 3–4 weeks) prevent overreaching; reactive deloads respond to signs of excessive fatigue. Both have their place.' },
  
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'During a taper, what should happen to training volume and intensity?', options: ['Volume decreases 40-60% while intensity is maintained or slightly increased', 'Both decrease', 'Both increase', 'Both stay the same'], correctAnswer: 0, explanation: 'Effective tapers reduce volume while preserving intensity for neural sharpness.' },
    { type: 'multiple_choice', question: 'What should a first competition attempt (opener) be?', options: ['A weight you can hit confidently on your worst day (90-92% of third attempt)', 'The heaviest weight possible', 'A personal record attempt', 'Whatever feels good on the day'], correctAnswer: 0, explanation: 'Openers get you on the board and build confidence for later attempts.' },
    { type: 'multiple_choice', question: 'If you miss a second attempt, what should you do?', options: ['Reduce to your opener weight', 'Skip the lift entirely', 'Repeat the second attempt rather than jumping', 'Take a bigger jump to your third'], correctAnswer: 2, explanation: 'Repeating a missed second is safer than an ambitious jump to a third attempt.' },
    { type: 'multiple_choice', question: 'How many days before competition should the last heavy session occur?', options: ['The morning of competition', '3 or more days out', 'The day before', 'One week before'], correctAnswer: 1, explanation: 'The last heavy session should be at least 3 days out to allow fatigue dissipation.' },
    { type: 'multiple_choice', question: 'What is the purpose of establishing a competition day routine?', options: ['To impress judges', 'To look professional', 'It is not important', 'Uncertainty creates anxiety; preparation eliminates it'], correctAnswer: 3, explanation: 'A rehearsed routine removes uncertainty and reduces competition anxiety.' },
    { type: 'multiple_choice', question: 'What is a taper?', options: ['A planned reduction in training volume while maintaining or increasing intensity in the final weeks before competition', 'A warm-up protocol', 'Increasing volume before competing', 'Stopping training completely'], correctAnswer: 0, explanation: 'A taper reduces volume (typically 40–60% over 1–3 weeks) while keeping intensity high — allowing fatigue to dissipate while maintaining peak fitness.' },
    { type: 'multiple_choice', question: 'How long should a peaking phase typically last?', options: ['1 day', '3 months', '6 months', '1–3 weeks depending on the sport, training age, and accumulated fatigue'], correctAnswer: 3, explanation: 'Peaking phases typically last 1–3 weeks — shorter for less fatigued athletes, longer for those with significant accumulated training stress.' },
    { type: 'multiple_choice', question: 'Why is it important to practise competition conditions during peaking?', options: ['It causes unnecessary fatigue', 'It is not important', 'Only for professional athletes', 'It familiarises the nervous system with competition-specific timing, environment, and performance demands'], correctAnswer: 3, explanation: 'Competition simulation reduces anxiety and prepares neural and psychological systems — practising warm-up routines, timing, and commands transfers directly to competition day.' },
    { type: 'multiple_choice', question: 'What should happen to training specificity during peaking?', options: ['Decrease specificity', 'Increase specificity — focus on competition lifts with competition-like sets, reps, and commands', 'Remove all specificity', 'Add more variety'], correctAnswer: 1, explanation: 'Peaking narrows training focus to competition movements with competition-specific parameters — eliminating accessories that add fatigue without directly improving competition performance.' },
    { type: 'multiple_choice', question: 'What is supercompensation?', options: ['Using supplements', 'Extra training sessions', 'Overeating before competition', 'The temporary performance increase above baseline that occurs when training stress is followed by adequate recovery'], correctAnswer: 3, explanation: 'Supercompensation is the temporary performance peak above baseline after a period of overload followed by recovery — peaking aims to time this for competition day.' },
  
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'What is training age?', options: ['How old you were when you started', 'Your biological age', 'Your chronological age', 'The number of years of consistent, structured training'], correctAnswer: 3, explanation: 'Training age counts years of consistent, progressive, structured training.' },
    { type: 'multiple_choice', question: 'During the Foundation stage (Years 1-2), what should be prioritised?', options: ['Maximal lifting', 'Competition', 'Specialisation in one sport', 'Movement quality, consistency, and general physical preparation'], correctAnswer: 3, explanation: 'Beginners should build movement quality and training habits before specialising.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of long-term athletic development?', options: ['Decades of healthy, productive training', 'Maximum muscle mass', 'A single peak performance', 'Winning one competition'], correctAnswer: 0, explanation: 'LTAD aims for lifelong training sustainability, not a single peak.' },
    { type: 'multiple_choice', question: 'Why might a 40-year-old still be programmed as a beginner?', options: ['Because they cannot train hard', 'Because training age (years of structured training) matters more than chronological age', 'They should not be', 'Because they are old'], correctAnswer: 1, explanation: 'A 40-year-old with 2 years of structured training is a beginner in training terms.' },
    { type: 'multiple_choice', question: 'Who accumulates more total training volume over a lifetime?', options: ['Neither — volume does not matter', 'Both equally', 'The person who trains consistently at moderate intensity for 30 years', 'The person who trains at maximum intensity for 5 years then stops'], correctAnswer: 2, explanation: 'Consistent moderate training over decades vastly outperforms short intense bursts.' },
    { type: 'multiple_choice', question: 'What is the general adaptation syndrome (GAS)?', options: ['A breathing disorder', 'Selye\'s model: alarm (initial stress), resistance (adaptation), and exhaustion (overtraining if stress is excessive)', 'A training programme', 'A recovery protocol'], correctAnswer: 1, explanation: 'GAS describes how the body responds to stress: initial alarm, then adaptation (resistance), then exhaustion if stress continues without recovery.' },
    { type: 'multiple_choice', question: 'Why does training age affect programming decisions?', options: ['Training age is the same as chronological age', 'It does not', 'Beginners need the most complex programmes', 'More experienced lifters need greater stimulus variation, higher specificity, and more sophisticated periodisation'], correctAnswer: 3, explanation: 'Training age determines adaptation thresholds — beginners adapt to almost anything, while advanced lifters need precise programming manipulation.' },
    { type: 'multiple_choice', question: 'What is the principle of diminishing returns in training?', options: ['Returns increase over time', 'Training always produces equal results', 'Progress becomes increasingly difficult as training age increases — more effort is needed for smaller gains', 'Only affects endurance athletes'], correctAnswer: 2, explanation: 'Beginners can add 2.5kg per week; advanced lifters may add 2.5kg per month. The same training effort produces progressively smaller adaptations.' },
    { type: 'multiple_choice', question: 'What is the difference between overreaching and overtraining?', options: ['They are the same', 'Overtraining is less serious', 'Neither exists', 'Overreaching is short-term fatigue that resolves with 1–2 weeks rest; overtraining is chronic exhaustion requiring months of recovery'], correctAnswer: 3, explanation: 'Functional overreaching is planned and recoverable (1–2 weeks); overtraining syndrome involves months of performance decline, hormonal disruption, and psychological symptoms.' },
    { type: 'multiple_choice', question: 'Why is training consistency more important than any single programme variable?', options: ['Programme design is everything', 'Years of consistent training accumulate adaptations that no short-term programme variable can replicate', 'Only intensity matters', 'It is not'], correctAnswer: 1, explanation: 'Long-term athletic development is built on years of consistent training — adherence to a decent programme beats perfect programming with poor consistency.' },
  
  ]),
];