import type { UnitAssessment } from '../types';

export const level4Unit4Assessment: UnitAssessment = {
  unitNumber: 4,
  title: 'Coaching, Communication & Professional Practice — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most effective type of cueing for movement performance?', options: ['Internal cues', 'External cues focusing on movement effects', 'No cueing', 'Verbal punishment'], correctAnswer: 1, explanation: 'External cues allow natural self-organisation of efficient movement.' },
    { type: 'multiple_choice', question: 'What drives client retention more than programming?', options: ['Price', 'Communication skills — making clients feel supported and heard', 'Equipment quality', 'Location'], correctAnswer: 1, explanation: 'People quit because they feel unsupported, not because of bad programmes.' },
    { type: 'multiple_choice', question: 'What is the primary ethical obligation of a fitness professional?', options: ['Revenue generation', 'Do no harm', 'Client acquisition', 'Social media presence'], correctAnswer: 1, explanation: 'Safety and wellbeing must always be the first priority.' },
    { type: 'multiple_choice', question: 'When should a coach refer a client to a specialist?', options: ['Never — coaches can handle everything', 'When the situation exceeds their scope of practice or qualifications', 'Only when the client asks', 'Only for serious injuries'], correctAnswer: 1, explanation: 'Referring is a professional responsibility, not a failure.' },
    { type: 'multiple_choice', question: 'What is the best approach to evidence-based practice?', options: ['Follow research blindly', 'Integrate scientific evidence with professional experience and client preferences', 'Ignore research — experience is everything', 'Only use the newest studies'], correctAnswer: 1, explanation: 'EBP combines three pillars for the best coaching decisions.' },
    { type: 'multiple_choice', question: 'What is the myth about resistance training and adolescents?', options: ['It is too easy for them', 'That it stunts growth — which has been comprehensively debunked', 'That it is too expensive', 'That they cannot learn technique'], correctAnswer: 1, explanation: 'Research supports safe, supervised resistance training for adolescents.' },
    { type: 'multiple_choice', question: 'What revenue model is most scalable for fitness professionals?', options: ['One-to-one training only', 'Online coaching', 'Group classes only', 'Selling supplements'], correctAnswer: 1, explanation: 'Online coaching removes the time-for-money ceiling.' },
    { type: 'multiple_choice', question: 'What characterises the hierarchy of evidence?', options: ['All evidence is equal', 'Systematic reviews > RCTs > cohort studies > case studies > expert opinion', 'Expert opinion is highest', 'Case studies are most reliable'], correctAnswer: 1, explanation: 'Higher-level evidence provides more confidence in findings.' },
    { type: 'multiple_choice', question: 'How should feedback frequency change as a learner becomes more skilled?', options: ['Increase constantly', 'Decrease — reduced feedback builds self-correction ability', 'Stay the same', 'Stop entirely'], correctAnswer: 1, explanation: 'Advanced learners benefit from less frequent feedback to develop independence.' },
    { type: 'multiple_choice', question: 'What is the best way to evaluate if a new training method works?', options: ['Try it once', 'Test it systematically with clients and let outcomes guide decisions', 'Ask social media', 'Assume it works because a study supports it'], correctAnswer: 1, explanation: 'Systematic testing with actual clients provides the most relevant evidence.' },
    { type: 'multiple_choice', question: 'What is the most impactful coaching a fitness professional can do?', options: ['Training competitive athletes exclusively', 'Helping anyone — from the 65-year-old gaining independence to the teenager finding confidence', 'Only working with genetically gifted clients', 'Focusing on aesthetics only'], correctAnswer: 1, explanation: 'Transformations in quality of life and confidence matter more than any PR.' },
    { type: 'multiple_choice', question: 'What is the Unbreakable standard for professional practice?', options: ['Physical invincibility', 'Knowledge in service of others, applied with integrity, refined through lifelong learning', 'Never showing weakness', 'Maximum revenue'], correctAnswer: 1, explanation: 'The standard combines ethical service with continuous professional growth.' },
  ],
};