import type { UnitAssessment } from '../types';

export const level2Unit1Assessment: UnitAssessment = {
  unitNumber: 1,
  title: 'Understanding the Body — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    {
      type: 'multiple_choice',
      question: 'Which plane of movement does a squat primarily occur in?',
      options: ['Coronal plane', 'Sagittal plane', 'Frontal plane', 'Transverse plane'],
      correctAnswer: 1,
      explanation: 'Squats involve flexion and extension at the hip and knee, which are forward-and-backward movements in the sagittal plane.',
    },
    {
      type: 'multiple_choice',
      question: 'What does the term "posterior" mean in anatomical language?',
      options: ['Towards the back', 'Towards the midline', 'Away from the midline', 'Towards the front'],
      correctAnswer: 0,
      explanation: 'Posterior refers to the back of the body. For example, the hamstrings are on the posterior side of the thigh.',
    },
    {
      type: 'multiple_choice',
      question: 'What does the anatomical term "proximal" mean?',
      options: ['Towards the back', 'Further from the trunk', 'Closer to the trunk', 'Towards the surface'],
      correctAnswer: 2,
      explanation: 'Proximal means closer to the point of attachment or the trunk. The elbow is proximal to the wrist.',
    },
    {
      type: 'multiple_choice',
      question: 'Which anatomical term describes a position closer to the surface of the body?',
      options: ['Deep', 'Superficial', 'Medial', 'Inferior'],
      correctAnswer: 1,
      explanation: 'Superficial means closer to the surface. For example, the skin is superficial to the muscles beneath it.',
    },
    {
      type: 'multiple_choice',
      question: 'Which type of joint allows movement in all directions?',
      options: ['Gliding joint', 'Hinge joint', 'Pivot joint', 'Ball-and-socket joint'],
      correctAnswer: 3,
      explanation: 'Ball-and-socket joints (shoulder, hip) allow the greatest range of movement in all directions.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is a function of the skeletal system?',
      options: ['Storing fat for energy', 'Producing hormones', 'Protecting vital organs', 'Regulating body temperature'],
      correctAnswer: 2,
      explanation: 'The skeletal system protects vital organs — the ribcage protects the lungs and heart, and the skull protects the brain.',
    },
    {
      type: 'multiple_choice',
      question: 'Which type of bone is primarily found in the wrist and ankle?',
      options: ['Short bones', 'Long bones', 'Irregular bones', 'Flat bones'],
      correctAnswer: 0,
      explanation: 'Short bones are roughly cube-shaped and are found in the wrist (carpals) and ankle (tarsals). They provide stability with limited movement.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the role of articular cartilage in a synovial joint?',
      options: ['To connect muscle to bone', 'To store calcium for bone growth', 'To produce red blood cells', 'To reduce friction between bone surfaces'],
      correctAnswer: 3,
      explanation: 'Articular (hyaline) cartilage covers the ends of bones in a synovial joint, providing a smooth surface that reduces friction during movement.',
    },
    {
      type: 'multiple_choice',
      question: 'What is an eccentric muscle contraction?',
      options: [
        'The muscle relaxes completely',
        'The muscle lengthens under load',
        'The muscle shortens under load',
        'The muscle produces force without changing length',
      ],
      correctAnswer: 1,
      explanation: 'Eccentric contraction occurs when a muscle lengthens while under tension — such as lowering a dumbbell during a bicep curl.',
    },
    {
      type: 'multiple_choice',
      question: 'Which muscle group is the antagonist to the quadriceps?',
      options: ['Hamstrings', 'Glutes', 'Hip flexors', 'Calves'],
      correctAnswer: 0,
      explanation: 'The hamstrings oppose the quadriceps. When the quads extend the knee, the hamstrings must relax, and vice versa.',
    },
    {
      type: 'multiple_choice',
      question: 'Which muscle fibre type is best suited for endurance activities such as marathon running?',
      options: ['Type IIx (fast-twitch)', 'Type IIa (intermediate)', 'Type I (slow-twitch)', 'Type III (super-fast)'],
      correctAnswer: 2,
      explanation: 'Type I (slow-twitch) fibres are fatigue-resistant and rely on aerobic metabolism, making them ideal for sustained, low-intensity activities.',
    },
    {
      type: 'scenario',
      question: 'Which muscle is acting as the agonist during the lowering phase?',
      scenario: 'You perform a controlled 4-second lowering phase on a Romanian deadlift. You maintain tension in the back of your legs throughout the movement.',
      options: ['Calves', 'Hamstrings', 'Erector spinae', 'Quadriceps'],
      correctAnswer: 1,
      explanation: 'During the lowering (eccentric) phase of a Romanian deadlift, the hamstrings are the primary agonist — they lengthen under tension to control the descent.',
    },
    {
      type: 'multiple_choice',
      question: 'What is stroke volume?',
      options: [
        'The speed at which blood flows through arteries',
        'The total blood volume in the body',
        'The number of heartbeats per minute',
        'The amount of blood pumped per heartbeat',
      ],
      correctAnswer: 3,
      explanation: 'Stroke volume is the amount of blood the heart pumps out with each contraction. It increases with cardiovascular training.',
    },
    {
      type: 'multiple_choice',
      question: 'What is a chronic adaptation of regular cardiovascular training?',
      options: [
        'Increased resting heart rate',
        'Decreased capillary density',
        'Increased stroke volume',
        'Decreased VO2 max',
      ],
      correctAnswer: 2,
      explanation: 'Regular cardiovascular training increases stroke volume — the heart becomes stronger and pumps more blood per beat, which lowers resting heart rate.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the correct formula for cardiac output?',
      options: [
        'Stroke volume × heart rate',
        'VO2 max × heart rate',
        'Blood volume ÷ heart rate',
        'Heart rate × blood pressure',
      ],
      correctAnswer: 0,
      explanation: 'Cardiac output = stroke volume × heart rate. It represents the total volume of blood the heart pumps per minute.',
    },
    {
      type: 'multiple_choice',
      question: 'Which blood vessels carry deoxygenated blood back to the heart?',
      options: ['Arterioles', 'Capillaries', 'Arteries', 'Veins'],
      correctAnswer: 3,
      explanation: 'Veins carry deoxygenated blood back to the heart (with the exception of the pulmonary veins, which carry oxygenated blood from the lungs).',
    },
    {
      type: 'multiple_choice',
      question: 'Which energy system is primarily used during a heavy single repetition on the deadlift?',
      options: ['Aerobic system', 'ATP-PC system', 'Anaerobic glycolysis', 'Lactic acid system'],
      correctAnswer: 1,
      explanation: 'Maximal efforts lasting under 10 seconds rely primarily on the ATP-PC (phosphocreatine) system for immediate energy.',
    },
    {
      type: 'multiple_choice',
      question: 'How long does the ATP-PC system typically provide energy for?',
      options: ['8-12 seconds', '2-5 minutes', '30-60 seconds', '15-30 minutes'],
      correctAnswer: 0,
      explanation: 'The ATP-PC system provides immediate, high-intensity energy for approximately 8-12 seconds before it needs to be replenished.',
    },
    {
      type: 'multiple_choice',
      question: 'Which energy system is the primary source of ATP during a 30-minute steady-state jog?',
      options: ['Anaerobic glycolysis', 'All three equally', 'Aerobic system', 'ATP-PC system'],
      correctAnswer: 2,
      explanation: 'The aerobic system is the dominant energy provider for sustained, lower-intensity activities lasting longer than 2-3 minutes, using oxygen to metabolise fats and carbohydrates.',
    },
    {
      type: 'scenario',
      question: 'Based on this scenario, which training adjustment would be most appropriate?',
      scenario: 'You perform 5 sets of 3 reps on bench press with 90 seconds rest between sets. Your performance drops significantly after the second set and you cannot complete your target reps.',
      options: [
        'Add more warm-up sets',
        'Increase rest periods to 3-5 minutes',
        'Switch to higher reps with lighter weight',
        'Reduce the weight by 20%',
      ],
      correctAnswer: 1,
      explanation: "Heavy sets of 3 reps primarily use the ATP-PC system, which requires 2-5 minutes to fully recover. With only 90 seconds rest, the system hasn\'t replenished, leading to performance decline.",
    }
  ],
};
