import type { UnitAssessment } from '../types';

export const level2FinalAssessment: UnitAssessment = {
  unitNumber: 0,
  title: 'Level 2 Final Assessment',
  passMarkPercent: 80,
  pickCount: 20,
  questions: [
    {
      type: 'multiple_choice',
      question: 'A woodchop exercise involves rotating your torso while moving a weight diagonally across your body. Which plane of movement is dominant?',
      options: ['Frontal plane', 'Coronal plane', 'Transverse plane', 'Sagittal plane'],
      correctAnswer: 2,
      explanation: 'The woodchop involves torso rotation, which is a transverse plane movement. While there is some sagittal plane contribution from the diagonal path, the primary movement pattern is rotational.',
    },
    {
      type: 'scenario',
      question: 'What is the most likely explanation?',
      scenario: 'You twisted your ankle while running. The area around the outside of the ankle is swollen and painful, but you can still bear weight. An X-ray shows no fracture.',
      options: [      'You have dislocated the ankle joint',
      'You have fractured a bone that the X-ray missed',
      'You have likely sprained the lateral ligaments of the ankle',
      'You have torn a tendon',
    ],
      correctAnswer: 2,
      explanation: 'A lateral ankle sprain involves damage to the ligaments on the outside of the ankle — most commonly the anterior talofibular ligament. Swelling and pain without fracture after an inversion injury is a classic presentation.',
    },
    {
      type: 'scenario',
      question: 'What acute cardiovascular response explains this?',
      scenario: 'You begin a set of heavy barbell squats. Within the first few reps, your heart rate increases rapidly from 70 bpm to 140 bpm, your breathing rate increases, and you feel your face flush.',
      options: [      'Your cardiovascular system is failing to cope with the load',
      'Your blood pressure has dropped dangerously',
      'Your body temperature is causing heat stroke',
      'Sympathetic nervous system activation increases heart rate and cardiac output to deliver oxygen to working muscles',
    ],
      correctAnswer: 3,
      explanation: 'The sympathetic nervous system triggers an acute cardiovascular response to exercise: increased heart rate, stroke volume, cardiac output, blood pressure, and vasodilation to working muscles. This is a normal, healthy response.',
    },
    {
      type: 'multiple_choice',
      question: 'What is VO₂ max?',
      options: [      'The maximum heart rate a person can achieve',
      'The maximum amount of oxygen the body can utilise during intense exercise',
      'The maximum weight a person can lift',
      'The maximum number of reps before failure',
    ],
      correctAnswer: 1,
      explanation: 'VO₂ max represents the maximum rate at which the body can consume and utilise oxygen during exercise. It is widely considered the gold standard measure of cardiovascular fitness.',
    },
    {
      type: 'multiple_choice',
      question: 'Why is Vitamin D particularly important for people who train regularly?',
      options: [      'It prevents all forms of illness',
      'It increases appetite',
      'It supports bone health, immune function, and muscle function',
      'It directly builds muscle tissue',
    ],
      correctAnswer: 2,
      explanation: 'Vitamin D supports calcium absorption for bone health, immune system function, and muscle contraction efficiency. Deficiency is associated with increased injury risk, impaired recovery, and reduced strength — particularly concerning for active individuals.',
    },
    {
      type: 'scenario',
      question: 'Which product is higher in protein per serving and which has less sugar?',
      scenario: 'You are comparing two protein bars. Bar A: per 60g serving — 250 cal, 20g protein, 28g carbs (15g sugar), 8g fat. Bar B: per 45g serving — 180 cal, 15g protein, 16g carbs (4g sugar), 7g fat.',
      options: [      'Bar A is better in every way because it has more protein',
      'Bar A has more protein per serving (20g vs 15g), but Bar B has significantly less sugar (4g vs 15g). Per 100g comparison would give a fairer assessment.',
      'Bar B is better because it has fewer calories',
      'Both bars are identical nutritionally',
    ],
      correctAnswer: 1,
      explanation: 'Comparing per serving can be misleading due to different serving sizes (60g vs 45g). Bar A has more absolute protein but also far more sugar. Per 100g: Bar A has 33g protein and 25g sugar; Bar B has 33g protein and 9g sugar — making Bar B the better choice for a lower-sugar option with equivalent protein density.',
    },
    {
      type: 'multiple_choice',
      question: 'How much protein per kilogram of bodyweight is generally recommended for someone who trains regularly?',
      options: ['3.0–4.0g per kg', '1.6–2.2g per kg', '0.5–0.8g per kg', '5.0+ g per kg'],
      correctAnswer: 1,
      explanation: 'Current evidence supports 1.6–2.2g of protein per kg of bodyweight for individuals who train regularly. This range supports muscle protein synthesis, recovery, and body composition goals.',
    },
    {
      type: 'scenario',
      question: 'What is the most effective warm-up approach?',
      scenario: 'You arrive at the gym for an upper-body session focused on bench press and overhead press. You have 10 minutes for your warm-up.',
      options: [      'Skip the warm-up to save time for more working sets',
      '10 minutes of leg stretches',
      'RAMP: 3 min rowing (Raise), band pull-aparts and face pulls (Activate), shoulder circles and thoracic rotations (Mobilise), empty bar presses ramping to working weight (Potentiate)',
      '10 minutes of static chest stretches',
    ],
      correctAnswer: 2,
      explanation: "An effective warm-up is specific to the session. RAMP ensures elevated heart rate, activated stabilisers, mobilised working joints, and progressive loading to the session\'s demands — all within 10 minutes.",
    },
    {
      type: 'scenario',
      question: 'Which type of stretching is most appropriate BEFORE a heavy deadlift session?',
      scenario: 'You are about to perform heavy deadlifts and want to prepare your hamstrings and hips without compromising force production.',
      options: [      'Dynamic stretches (leg swings, hip circles, inchworms) combined with progressive loading',
      'Hold static hamstring stretches for 60 seconds each leg',
      'PNF stretching for maximum range of motion',
      'No stretching — just start lifting heavy immediately',
    ],
      correctAnswer: 0,
      explanation: 'Dynamic stretching increases blood flow, ROM, and neuromuscular readiness without the temporary force-reduction effects associated with prolonged static stretching before heavy lifting.',
    },
    {
      type: 'multiple_choice',
      question: 'What is osteoporosis, and which type of training helps prevent it?',
      options: [      'Loss of muscle mass — cardiovascular training',
      'Loss of bone density — weight-bearing and resistance training',
      'Loss of flexibility — stretching only',
      'Loss of cardiovascular fitness — HIIT only',
    ],
      correctAnswer: 1,
      explanation: 'Osteoporosis is the progressive loss of bone mineral density. Weight-bearing exercises and resistance training stimulate osteoblast activity (bone-building cells), maintaining and improving bone density. This is particularly important for post-menopausal women.',
    },
    {
      type: 'scenario',
      question: 'What is the most appropriate training split?',
      scenario: 'You are a beginner who can train 3 days per week (Monday, Wednesday, Friday). You want to build overall strength and muscle.',
      options: [      'Chest on Monday, back on Wednesday, legs on Friday (body-part split)',
      'Upper body all 3 days — legs do not need training for general fitness',
      'Full-body sessions all 3 days, training each major movement pattern each session',
      'Push on Monday, pull on Wednesday, legs on Friday',
    ],
      correctAnswer: 2,
      explanation: "Full-body training 3 days per week is optimal for beginners: it provides high training frequency per muscle group (3× per week), maximises motor learning through repetition, and matches the beginner\'s lower recovery demands.",
    },
    {
      type: 'multiple_choice',
      question: 'What is a superset?',
      options: [      'A set performed above your maximum capacity',
      'Performing the same exercise twice in one session',
      'Performing two exercises back-to-back with minimal rest between them',
      'Performing one set of an exercise with very long rest',
    ],
      correctAnswer: 2,
      explanation: 'A superset involves performing two exercises consecutively with minimal rest between them, typically pairing opposing muscle groups (e.g., bicep curl + tricep extension) or unrelated movements to increase training density.',
    },
    {
      type: 'multiple_choice',
      question: 'What is "environment design" in the context of habit formation?',
      options: [      'Structuring your physical environment to make desired behaviours easier and undesired behaviours harder',
      'Designing a training programme',
      'Choosing which gym to join',
      'Choosing the right workout clothes',
    ],
      correctAnswer: 0,
      explanation: 'Environment design involves reducing friction for good habits and increasing friction for bad ones. Examples: keeping a gym bag packed by the door, preparing meals in advance, removing junk food from the house, setting a phone curfew for better sleep.',
    },
    {
      type: 'multiple_choice',
      question: 'Which plane of movement does a lateral lunge primarily occur in?',
      options: ['Transverse plane', 'Frontal plane', 'Longitudinal plane', 'Sagittal plane'],
      correctAnswer: 1,
      explanation: 'A lateral lunge involves side-to-side movement — abduction and adduction at the hip — which occurs in the frontal (coronal) plane.',
    },
    {
      type: 'multiple_choice',
      question: 'Which muscle fibre type has the highest fatigue resistance?',
      options: ['Type I', 'Type IIa', 'Type IIx', 'All fibre types fatigue equally'],
      correctAnswer: 0,
      explanation: 'Type I (slow-twitch) fibres are the most fatigue-resistant due to their high mitochondrial density and reliance on aerobic metabolism. They are recruited for sustained, low-intensity activities.',
    },
    {
      type: 'multiple_choice',
      question: 'Which vitamin is fat-soluble?',
      options: ['Folate', 'Vitamin C', 'Vitamin D', 'Vitamin B12'],
      correctAnswer: 2,
      explanation: 'Vitamins A, D, E, and K are fat-soluble — they require dietary fat for absorption and are stored in the body. Vitamins C and B-complex are water-soluble and need regular replenishment.',
    },
    {
      type: 'scenario',
      question: 'What is the best strategy?',
      scenario: 'You are training for a half marathon in 8 weeks. Your current diet is high in protein (2.5g/kg) but very low in carbohydrates (1g/kg). You are struggling with energy during long runs.',
      options: [      'Take more caffeine before runs',
      'Reduce protein and add more fat for energy',
      'Increase carbohydrate intake to 3–5g/kg to fuel endurance training while maintaining adequate protein at 1.6–2.0g/kg',
      'Run slower to conserve energy',
    ],
      correctAnswer: 2,
      explanation: 'Endurance training requires adequate glycogen stores, which come from carbohydrates. At 1g/kg, carb intake is insufficient for half-marathon training. Increasing to 3–5g/kg ensures fuel availability for long runs while maintaining protein for recovery.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the primary benefit of static stretching after training?',
      options: [      'It promotes flexibility, aids venous return, and helps transition the body from a training state to a recovery state',
      'It increases strength immediately',
      'It prevents all injuries',
      'It builds muscle',
    ],
      correctAnswer: 0,
      explanation: 'Post-training static stretching promotes flexibility, assists in returning heart rate and blood pressure to resting levels, aids venous return, and helps shift the nervous system towards parasympathetic (recovery) dominance.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the specificity principle?',
      options: [      'All training produces the same results',
      'You must train every muscle in every session',
      'Training adaptations are specific to the type of stimulus applied — you get what you train for',
      'Specificity only applies to professional athletes',
    ],
      correctAnswer: 2,
      explanation: 'The specificity principle (SAID: Specific Adaptation to Imposed Demands) means your body adapts specifically to the type of training you do. Heavy lifting improves strength; endurance training improves aerobic capacity. Training must match your goals.',
    },
    {
      type: 'scenario',
      question: 'Which goal is SMART?',
      scenario: 'You are setting training goals for the next 8 weeks. Consider these options carefully.',
      options: [      '"I will try to exercise more"',
      '"I will increase my barbell back squat from 60 kg × 5 to 70 kg × 5 within 8 weeks by squatting twice per week with progressive overload"',
      '"I will be the strongest person in my gym"',
      '"I want to get stronger"',
    ],
      correctAnswer: 1,
      explanation: 'This goal is Specific (back squat improvement), Measurable (60→70 kg × 5), Achievable (realistic in 8 weeks), Relevant (directly addresses strength), and Time-bound (8-week deadline with a clear plan).',
    }
  ],
};
