import type { ChapterQuiz } from '../types';

export const unit4ChapterQuizzes: ChapterQuiz[] = [
  // ─── Chapter 1: Setting SMART Goals ───
  {
    unitNumber: 4, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'The "S" in SMART stands for:', options: ['Specific', 'Sustainable', 'Strong', 'Simple'], correctAnswer: 0, explanation: 'Specific means clearly defined — "I want to squat 100 kg" is specific; "I want to get stronger" is not.' },
      { type: 'multiple_choice', question: 'A measurable goal includes:', options: ['Only emotional motivation', 'A vague aspiration', 'A quantifiable target that can be tracked', 'No deadline'], correctAnswer: 2, explanation: 'Measurable goals include numbers or criteria you can track — weight lifted, distance run, body measurements, etc.' },
      { type: 'multiple_choice', question: 'What is a process goal?', options: ['A goal focused on the final result only', 'A goal with no deadline', 'A goal set by someone else', 'A goal focused on the actions and behaviours that lead to results'], correctAnswer: 3, explanation: 'Process goals focus on what you DO (training 4× per week, eating protein at every meal) rather than the outcome itself.' },
      { type: 'scenario', question: 'How would you make this goal SMART?', scenario: 'You set the goal: "I want to lose weight."', options: ['"I want to lose 4 kg of body fat in 8 weeks by training 4 times per week and eating in a moderate deficit"', '"I want to lose lots of weight quickly"', '"I want to be thinner"', '"I\'ll try to eat less"'], correctAnswer: 0, explanation: 'The SMART version is specific (4 kg fat), measurable (weight/body fat tracking), achievable (realistic rate), relevant (aligned with goals), and time-bound (8 weeks).' },
      { type: 'multiple_choice', question: 'The "T" in SMART stands for:', options: ['Trendy', 'Tough', 'Time-bound', 'Total'], correctAnswer: 2, explanation: 'Time-bound means setting a deadline. Without one, goals lack urgency and are harder to track progress against.' },
      { type: 'multiple_choice', question: 'An outcome goal is:', options: ['A result you want to achieve (e.g., running a 5K in under 25 minutes)', 'A behaviour you control directly', 'Always within your control', 'The same as a process goal'], correctAnswer: 0, explanation: 'Outcome goals define the end result. They are motivating but not entirely within your control — process goals bridge the gap.' },
      { type: 'multiple_choice', question: 'Why is regular goal review important?', options: ['It is not important', 'Only review annually', 'Goals may need adjusting based on progress, setbacks, or changing priorities', 'You should never change a goal once set'], correctAnswer: 2, explanation: 'Regular review allows you to adjust goals based on reality — celebrating progress, recalibrating timelines, or shifting focus as needed.' },
      { type: 'scenario', question: 'What type of goal is this?', scenario: 'Your goal is: "Train legs twice per week for the next 6 weeks."', options: ['A dream, not a goal', 'Neither — it is not a real goal', 'Outcome goal', 'Process goal'], correctAnswer: 3, explanation: 'This is a process goal — it focuses on the behaviour (training legs twice weekly) rather than a specific outcome.' },
      { type: 'multiple_choice', question: 'The "A" in SMART stands for:', options: ['Absolute', 'Aggressive', 'Achievable', 'Automatic'], correctAnswer: 2, explanation: 'Achievable means the goal is realistic given your current situation, resources, and time. Stretch goals are fine, but impossible targets cause demotivation.' },
      { type: 'multiple_choice', question: 'Short-term goals typically span:', options: ['10+ years', '6–12 months', '1–5 years', '1–4 weeks'], correctAnswer: 3, explanation: 'Short-term goals cover days to weeks and serve as stepping stones towards medium and long-term targets.' },
    ],
  },

  // ─── Chapter 2: Training Splits and Frequency ───
  {
    unitNumber: 4, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'A "full-body" training split means:', options: ['Training 7 days per week', 'Only training upper body', 'Training one muscle group per session', 'Training all major muscle groups in every session'], correctAnswer: 3, explanation: 'Full-body splits train all major muscle groups in each session, typically done 2–4 times per week.' },
      { type: 'multiple_choice', question: 'An upper/lower split divides training into:', options: ['Chest and back days', 'Push and pull days', 'Cardio and weights days', 'Upper body sessions and lower body sessions'], correctAnswer: 3, explanation: 'Upper/lower splits alternate between upper body and lower body sessions, typically run over 4 days per week.' },
      { type: 'multiple_choice', question: 'Training frequency refers to:', options: ['How heavy you lift', 'The number of reps per set', 'How many times per week you train a muscle group or body part', 'The speed of each repetition'], correctAnswer: 2, explanation: 'Training frequency is how often you train a particular muscle group per week — e.g., training legs twice per week.' },
      { type: 'scenario', question: 'Which training split would suit them best?', scenario: 'A beginner can train 3 days per week and wants to build overall strength.', options: ['Training once per month', 'A chest-only programme', 'A 6-day body-part split', 'A 3-day full-body programme'], correctAnswer: 3, explanation: 'A 3-day full-body programme maximises training frequency for each muscle group within the available schedule — ideal for beginners.' },
      { type: 'multiple_choice', question: 'A push/pull/legs (PPL) split typically runs over:', options: ['3 or 6 days per week', '2 days per week', '7 days per week with no rest', '1 day per week'], correctAnswer: 0, explanation: 'PPL is a 3-day rotation (push, pull, legs) that can be run once (3 days) or twice (6 days) per week.' },
      { type: 'multiple_choice', question: 'Training a muscle group twice per week compared to once is generally:', options: ['Less effective', 'More effective for hypertrophy in most research', 'Only for advanced lifters', 'Dangerous'], correctAnswer: 1, explanation: 'Research suggests training each muscle group at least twice per week may optimise hypertrophy by distributing volume and maintaining elevated muscle protein synthesis.' },
      { type: 'multiple_choice', question: 'Rest days are important because:', options: ['They reduce fitness', 'They allow recovery, repair, and adaptation to occur', 'They are only needed by beginners', 'They are a sign of laziness'], correctAnswer: 1, explanation: 'Adaptation happens during recovery, not during training. Rest days are essential for muscle repair, nervous system recovery, and long-term progress.' },
      { type: 'scenario', question: 'What change would improve their results?', scenario: 'An intermediate lifter trains chest on Monday, back on Tuesday, and legs on Friday. Each muscle is trained once per week. Progress has stalled.', options: ['Reduce training to once per week', 'Keep the same routine', 'Add more exercises to each session only', 'Increase frequency by training each muscle group twice per week using a different split'], correctAnswer: 3, explanation: 'Increasing frequency to twice per week per muscle group allows more volume distribution and more frequent growth stimulus, which often breaks plateaus.' },
      { type: 'multiple_choice', question: 'A "bro split" typically involves:', options: ['Training one muscle group per day across 5–6 sessions', 'Only training arms', 'Full-body training 3 times per week', 'Training each muscle group twice per week'], correctAnswer: 0, explanation: 'The "bro split" dedicates each session to one muscle group (e.g., chest Monday, back Tuesday). While it works, frequency per muscle is typically low.' },
      { type: 'multiple_choice', question: 'For most people, the optimal number of training days per week is:', options: ['It does not matter', '3–5 days, depending on experience and recovery capacity', '1–2 days', '7 days with no rest'], correctAnswer: 1, explanation: '3–5 days per week balances stimulus and recovery for most people. The exact number depends on training age, goals, and recovery capacity.' },
    ],
  },

  // ─── Chapter 3: Periodisation Basics ───
  {
    unitNumber: 4, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Periodisation is the:', options: ['Training the same way indefinitely', 'Random variation of exercises each session', 'Planned, systematic variation of training over time', 'Avoidance of progressive overload'], correctAnswer: 2, explanation: 'Periodisation is the strategic organisation of training into phases to manage fatigue, optimise adaptation, and prevent plateaus.' },
      { type: 'multiple_choice', question: 'A mesocycle typically lasts:', options: ['1 session', '3–6 weeks', '1 week', '12 months'], correctAnswer: 1, explanation: 'A mesocycle is a training block lasting approximately 3–6 weeks, usually focused on a specific training goal (e.g., hypertrophy, strength).' },
      { type: 'multiple_choice', question: 'Linear periodisation involves:', options: ['Gradually increasing intensity while decreasing volume over time', 'Random intensity changes', 'Keeping everything the same', 'Only training in one rep range'], correctAnswer: 0, explanation: 'Linear periodisation progressively increases load and decreases volume across mesocycles — e.g., starting with higher reps and lighter weight, moving to lower reps and heavier weight.' },
      { type: 'scenario', question: 'What approach should you take?', scenario: 'You have been lifting the same weight for 3 months with no plan for progression or variation.', options: ['Implement a periodised plan with planned progression and deload weeks', 'Stop training for a month', 'Double your weight immediately', 'Keep going — consistency alone is enough'], correctAnswer: 0, explanation: 'Without planned progression and variation, adaptation stalls. A periodised plan ensures continual challenge and structured recovery.' },
      { type: 'multiple_choice', question: 'A deload week in periodisation serves to:', options: ['Allow accumulated fatigue to dissipate so the body can supercompensate', 'Eliminate all gains', 'Test your 1RM', 'Replace regular training permanently'], correctAnswer: 0, explanation: 'Deloads reduce volume and/or intensity, allowing fatigue to clear and enabling the body to express the fitness it has built.' },
      { type: 'multiple_choice', question: 'Undulating periodisation varies training variables:', options: ['Annually only', 'Within each week or between sessions', 'Only at the end of a programme', 'Never'], correctAnswer: 1, explanation: 'Daily undulating periodisation (DUP) varies rep ranges, loads, and intensities within the same week — e.g., heavy Monday, light Wednesday, moderate Friday.' },
      { type: 'multiple_choice', question: 'A macrocycle refers to:', options: ['A single set', 'A warm-up protocol', 'The overall long-term training plan (typically 6–12 months)', 'A single session'], correctAnswer: 2, explanation: 'A macrocycle is the largest training cycle — the overarching plan spanning months to a year, containing multiple mesocycles.' },
      { type: 'multiple_choice', question: 'A microcycle is typically:', options: ['One month of training', 'One training session', 'One week of training', 'One year of training'], correctAnswer: 2, explanation: 'A microcycle is the smallest training cycle, usually representing one week of sessions.' },
      { type: 'scenario', question: 'Which periodisation model fits best?', scenario: 'You want to compete in a powerlifting meet in 16 weeks. You need to peak your squat, bench, and deadlift for a single day.', options: ['Linear or block periodisation building from volume to intensity, peaking for the competition', 'No periodisation — just train heavy every day', 'Random exercise selection each session', 'Only train light for 16 weeks'], correctAnswer: 0, explanation: 'A structured periodised plan moving from higher volume to higher intensity, culminating in a peak week, is the standard approach for competition preparation.' },
      { type: 'multiple_choice', question: 'Block periodisation concentrates training into phases of:', options: ['Focused blocks targeting one primary quality (e.g., accumulation, intensification, realisation)', 'No structure whatsoever', 'Random variety', 'Only cardio'], correctAnswer: 0, explanation: 'Block periodisation dedicates each mesocycle to a primary training quality — accumulation (volume), intensification (load), and realisation (peaking).' },
    ],
  },

  // ─── Chapter 4: Session Structure ───
  {
    unitNumber: 4, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'A well-structured training session should include:', options: ['Random exercises in any order', 'Cool-down only', 'Warm-up, main work, accessory work, and cool-down', 'Only the main lifts'], correctAnswer: 2, explanation: 'A complete session flows from warm-up → main compound lifts → accessory work → cool-down for optimal performance and recovery.' },
      { type: 'multiple_choice', question: 'Main lifts should be performed:', options: ['Early in the session when energy and focus are highest', 'Only on weekends', 'After isolation exercises', 'At the end of the session when fatigued'], correctAnswer: 0, explanation: 'Compound main lifts demand the most neural drive and energy, so they should be performed first when you are freshest.' },
      { type: 'multiple_choice', question: 'Accessory exercises serve to:', options: ['Replace main lifts', 'Support main lifts by targeting weak points, imbalances, or underdeveloped areas', 'Waste time after the important work is done', 'Be the only exercises in a programme'], correctAnswer: 1, explanation: 'Accessory work addresses specific muscle groups, weaknesses, or imbalances that support progress on the main lifts.' },
      { type: 'scenario', question: 'How should you restructure this session?', scenario: 'Your current session: bicep curls → squats → abs → deadlifts → warm-up.', options: ['Warm-up → deadlifts → squats → abs → bicep curls → cool-down', 'Deadlifts → squats → more deadlifts → skip warm-up', 'This order is fine', 'Only do bicep curls'], correctAnswer: 0, explanation: 'Correct order: warm-up first, then heavy compounds (deadlifts, squats), then accessories (abs, curls), then cool-down.' },
      { type: 'multiple_choice', question: 'A training session for most people should last approximately:', options: ['15 minutes', '3 hours', '2–3 hours minimum', '45–75 minutes'], correctAnswer: 3, explanation: '45–75 minutes is sufficient for a productive session. Quality and intensity matter more than duration.' },
      { type: 'multiple_choice', question: 'Supersets involve:', options: ['Performing two exercises back-to-back with minimal rest', 'Only using superheroes as exercise names', 'Only one exercise per session', 'Very long rest periods'], correctAnswer: 0, explanation: 'Supersets pair two exercises performed consecutively with minimal rest, improving training efficiency and density.' },
      { type: 'multiple_choice', question: 'Rest periods between accessory exercises (hypertrophy range) are typically:', options: ['No rest at all', '30 seconds or less', '5+ minutes', '60–90 seconds'], correctAnswer: 3, explanation: '60–90 seconds of rest is standard for hypertrophy-focused accessory work, allowing partial recovery while maintaining metabolic stress.' },
      { type: 'scenario', question: 'What is wrong with this programme?', scenario: 'You spend 30 minutes warming up, 15 minutes on main lifts, and 45 minutes on bicep and tricep isolation exercises.', options: ['The warm-up is disproportionately long and too much time is spent on isolation versus compound work', 'Nothing — this is optimal', 'You need a longer warm-up', 'You should skip the main lifts entirely'], correctAnswer: 0, explanation: 'Warm-ups should be 5–15 minutes, with the majority of training time dedicated to main compound lifts and balanced accessory work.' },
      { type: 'multiple_choice', question: 'Drop sets involve:', options: ['Dropping the weight and immediately continuing reps until failure, repeated multiple times', 'Resting for 5 minutes between sets', 'Only using heavy weights', 'Dropping the bar on the floor'], correctAnswer: 0, explanation: 'Drop sets reduce the weight immediately after reaching failure, then continue for more reps — an intensity technique for hypertrophy.' },
      { type: 'multiple_choice', question: 'Training logs are useful because:', options: ['They are only for advanced lifters', 'They track progress, identify patterns, and ensure progressive overload', 'They replace coaching entirely', 'They are not useful'], correctAnswer: 1, explanation: 'Training logs provide objective data on your progress, help identify stalling points, and ensure you are consistently applying progressive overload.' },
    ],
  },

  // ─── Chapter 5: Tracking Progress ───
  {
    unitNumber: 4, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'The most reliable way to track body composition changes is:', options: ['BMI alone', 'How tight your jeans feel on one day', 'Daily scale weight only', 'A combination of weekly weight averages, measurements, photos, and performance data'], correctAnswer: 3, explanation: 'No single metric tells the full story. Combining weight trends, measurements, progress photos, and performance data gives the most accurate picture.' },
      { type: 'multiple_choice', question: 'Body weight can fluctuate daily by as much as:', options: ['0.1 kg', '5+ kg', '1–3 kg due to water, food, and glycogen', 'It never fluctuates'], correctAnswer: 2, explanation: 'Daily weight fluctuations of 1–3 kg are completely normal, driven by hydration, food volume, sodium, glycogen stores, and hormones.' },
      { type: 'multiple_choice', question: 'Progressive overload can be tracked through:', options: ['Increases in weight lifted, reps completed, sets performed, or volume over time', 'Social media likes', 'Only body weight', 'Only how you feel'], correctAnswer: 0, explanation: 'Progressive overload is measurable through training log data — heavier weights, more reps, additional sets, or increased total volume over weeks and months.' },
      { type: 'scenario', question: 'How should you interpret this?', scenario: 'Your scale weight has not changed in 4 weeks, but your lifts have increased and your clothes fit better.', options: ['You are likely gaining muscle and losing fat (recomposition) — multiple metrics show improvement', 'The scale is broken', 'You need to eat less immediately', 'You are making no progress'], correctAnswer: 0, explanation: 'Stable weight with improved performance and fit suggests body recomposition — gaining lean tissue while losing fat. This is positive progress.' },
      { type: 'multiple_choice', question: 'Progress photos should be taken:', options: ['At consistent intervals with the same lighting, angle, and time of day', 'Only when you look your best', 'Never — they are not useful', 'At random times with different lighting and poses'], correctAnswer: 0, explanation: 'Consistency in timing, lighting, posing, and angle ensures progress photos are comparable and provide genuine visual feedback.' },
      { type: 'multiple_choice', question: 'Measuring body circumferences (waist, hips, arms) is useful for:', options: ['Replacing all other tracking methods', 'Tracking changes in body composition that the scale may not show', 'Only bodybuilders', 'Nothing — it is outdated'], correctAnswer: 1, explanation: 'Circumference measurements reveal where you are gaining or losing size — a waist decrease with stable weight suggests fat loss and muscle gain.' },
      { type: 'multiple_choice', question: 'How often should you reassess your training programme?', options: ['Never — stick with it forever', 'Every single session', 'Once per year', 'Every 4–8 weeks based on progress and goals'], correctAnswer: 3, explanation: 'Reviewing and adjusting your programme every 4–8 weeks ensures it remains aligned with your progress and goals.' },
      { type: 'scenario', question: 'What is the best way to identify the issue?', scenario: 'Your squat has not improved in 6 weeks. You are unsure why.', options: ['Review your training log — check volume, intensity, recovery, sleep, and nutrition for patterns', 'Give up squatting', 'Add more squat sessions immediately', 'Only do leg extensions instead'], correctAnswer: 0, explanation: 'Your training log holds the answers — reviewing load, volume, frequency, sleep, and nutrition data helps identify what needs adjusting.' },
      { type: 'multiple_choice', question: 'Rate of Perceived Exertion (RPE) is a useful tracking tool because:', options: ['It provides a subjective measure of training difficulty that accounts for daily readiness', 'It replaces all other tracking', 'It is only for professional athletes', 'It requires expensive equipment'], correctAnswer: 0, explanation: 'RPE captures how hard a session or set felt, helping account for day-to-day variation in energy, stress, and recovery.' },
      { type: 'multiple_choice', question: 'A training plateau most often indicates:', options: ['A need for programme adjustment — change stimulus, volume, intensity, or recovery', 'You should stop training for 6 months', 'That training does not work', 'You have reached your genetic maximum'], correctAnswer: 0, explanation: 'Plateaus usually mean the current stimulus is no longer novel. Adjusting one or more variables typically restarts progress.' },
    ],
  },

  // ─── Chapter 6: Sleep, Stress, and Recovery Lifestyle ───
  {
    unitNumber: 4, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Growth hormone is primarily released during:', options: ['Deep (slow-wave) sleep', 'While eating', 'Light napping', 'Intense exercise only'], correctAnswer: 0, explanation: 'The majority of growth hormone release occurs during deep (slow-wave) sleep — critical for muscle repair and recovery.' },
      { type: 'multiple_choice', question: 'Chronic sleep deprivation affects training by:', options: ['Only making you tired', 'Having no effect', 'Improving mental toughness', 'Reducing performance, impairing recovery, increasing injury risk, and promoting fat storage'], correctAnswer: 3, explanation: 'Sleep deprivation reduces strength, endurance, and reaction time, impairs protein synthesis, and increases cortisol — all detrimental to training.' },
      { type: 'scenario', question: 'What should you prioritise?', scenario: 'You train 6 days per week but average 5 hours of sleep per night. Progress has stalled and you feel constantly tired.', options: ['Prioritise sleep — aim for 7–9 hours per night even if it means reducing training days', 'Train harder to break through the plateau', 'Add a 7th training day', 'Take more caffeine'], correctAnswer: 0, explanation: 'Sleep is the single most important recovery tool. Training more on insufficient sleep deepens the recovery deficit. Prioritising sleep will likely restart progress.' },
      { type: 'multiple_choice', question: 'Cortisol is known as the:', options: ['Growth hormone', 'Sleep hormone', 'Stress hormone', 'Muscle-building hormone'], correctAnswer: 2, explanation: 'Cortisol is released in response to stress. Chronically elevated cortisol impairs recovery, promotes fat storage, and can break down muscle tissue.' },
      { type: 'multiple_choice', question: 'Good sleep hygiene includes:', options: ['Drinking alcohol before bed to relax', 'Using your phone in bed until you fall asleep', 'Sleeping whenever you feel like it', 'Consistent bedtime, dark room, cool temperature, and limiting screens before bed'], correctAnswer: 3, explanation: 'Good sleep hygiene — consistent schedule, dark environment, cool temperature, and limited blue light exposure — significantly improves sleep quality.' },
      { type: 'multiple_choice', question: 'How does chronic psychological stress affect body composition?', options: ['It has no effect', 'Elevated cortisol can promote fat storage (especially abdominal) and impair muscle growth', 'Stress always helps you lose weight', 'Only physical stress matters'], correctAnswer: 1, explanation: 'Chronic stress elevates cortisol, which promotes visceral fat storage, impairs protein synthesis, and can increase appetite for calorie-dense foods.' },
      { type: 'multiple_choice', question: 'Alcohol consumption affects recovery by:', options: ['Having no effect at all', 'Impairing protein synthesis, disrupting sleep architecture, and dehydrating the body', 'Improving muscle repair', 'Improving sleep quality'], correctAnswer: 1, explanation: 'Alcohol reduces muscle protein synthesis by up to 37%, disrupts REM sleep, causes dehydration, and impairs hormone balance — all detrimental to recovery.' },
      { type: 'scenario', question: 'What is the most effective stress management strategy?', scenario: 'You have a demanding job and notice your recovery is suffering despite a solid training and nutrition plan.', options: ['Train harder to blow off steam', 'Ignore stress — it is not relevant to fitness', 'Stop training until work calms down', 'Incorporate stress management techniques: walking, breathing exercises, time in nature, or mindfulness'], correctAnswer: 3, explanation: 'Active stress management (walking, breathing exercises, meditation, time in nature) helps lower cortisol and improve overall recovery capacity.' },
      { type: 'multiple_choice', question: 'Blue light from screens affects sleep by:', options: ['Suppressing melatonin production, making it harder to fall asleep', 'Having no effect', 'Improving sleep quality', 'Only affecting children'], correctAnswer: 0, explanation: 'Blue light from phones, tablets, and computers suppresses melatonin — the hormone that signals sleep. Limiting screen time 1–2 hours before bed supports better sleep.' },
      { type: 'multiple_choice', question: 'The recommended minimum sleep for athletic recovery is:', options: ['6 hours maximum', '10–12 hours always', '7–9 hours, with 8+ hours ideal for athletes', '4–5 hours'], correctAnswer: 2, explanation: '7–9 hours is the general recommendation, with many sports science guidelines suggesting 8+ hours for optimal athletic performance and recovery.' },
    ],
  },

  // ─── Chapter 7: Habits and Consistency ───
  {
    unitNumber: 4, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'The habit loop consists of:', options: ['Planning and execution', 'Motivation and willpower only', 'Cue, routine, and reward', 'Only repetition'], correctAnswer: 2, explanation: 'The habit loop (cue → routine → reward) is the neurological framework that drives automatic behaviours. Understanding it helps build positive habits.' },
      { type: 'multiple_choice', question: 'Habit stacking involves:', options: ['Linking a new habit to an existing one (e.g., "After I make my coffee, I will do 5 minutes of stretching")', 'Removing all old habits', 'Only focusing on one habit per year', 'Doing everything at once'], correctAnswer: 0, explanation: 'Habit stacking uses existing routines as anchors for new behaviours, leveraging established neural pathways to make new habits stick.' },
      { type: 'scenario', question: 'What approach is most effective?', scenario: 'You want to start training consistently but struggle with motivation. You often skip sessions.', options: ['Set a non-negotiable schedule, remove decision-making, and start with small commitments', 'Wait until you feel motivated', 'Only train when you feel 100%', 'Find a completely new hobby instead'], correctAnswer: 0, explanation: 'Consistency comes from systems, not motivation. Scheduling sessions, reducing friction, and starting small builds the habit before relying on willpower.' },
      { type: 'multiple_choice', question: 'The "2-minute rule" for habits suggests:', options: ['Start with a version of the habit that takes 2 minutes or less to lower the barrier to starting', 'Only do 2 minutes of exercise per day', 'Habits form in exactly 2 minutes', 'All habits take 2 minutes to form'], correctAnswer: 0, explanation: 'The 2-minute rule makes starting easy — "put on your gym clothes" is easier than "do a full workout." Small starts build momentum.' },
      { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['1 year minimum', '18–254 days, with an average of around 66 days', '7 days', '21 days exactly'], correctAnswer: 1, explanation: 'Research shows habit formation varies widely — the average is around 66 days, but it can range from 18 to 254 days depending on the complexity of the behaviour.' },
      { type: 'multiple_choice', question: 'Identity-based habits focus on:', options: ['What you want to achieve', 'What other people think of you', 'Who you want to become (e.g., "I am someone who trains consistently")', 'Only external rewards'], correctAnswer: 2, explanation: 'Identity-based habits shift focus from outcomes to identity — "I am someone who trains" is more powerful than "I want to lose weight."' },
      { type: 'scenario', question: 'What would you recommend?', scenario: 'You miss one training session and feel like the entire week is ruined, so you skip the rest of the week too.', options: ['Never miss twice — one missed session does not ruin a week. Get back on track at the next opportunity', 'This is the right approach — start fresh next week', 'Train double next week to compensate', 'Give up entirely'], correctAnswer: 0, explanation: 'The "never miss twice" rule prevents one missed session from snowballing. Missing once is normal; missing twice is the start of a new habit.' },
      { type: 'multiple_choice', question: 'Environment design for habits means:', options: ['Moving to a new city', 'Only training in perfect conditions', 'Ignoring your surroundings', 'Shaping your environment to make good habits easier and bad habits harder'], correctAnswer: 3, explanation: 'Environment design removes friction for good habits (e.g., laying out gym clothes the night before) and adds friction for bad ones (e.g., not keeping junk food at home).' },
      { type: 'multiple_choice', question: 'Willpower is:', options: ['Not real', 'Unlimited and always reliable', 'The only factor in success', 'A finite resource that depletes throughout the day — systems and habits reduce reliance on it'], correctAnswer: 3, explanation: 'Willpower is limited and fluctuates with stress, fatigue, and decision fatigue. Building habits and systems reduces the need to rely on willpower.' },
      { type: 'multiple_choice', question: 'Tracking habits (e.g., with a habit diary) is effective because:', options: ['It wastes time', 'It replaces actual training', 'It creates visual accountability, highlights patterns, and reinforces the habit loop', 'It is only useful for beginners'], correctAnswer: 2, explanation: 'Habit tracking provides visual feedback, creates accountability, and the act of recording itself reinforces the behaviour through the satisfaction of marking it complete.' },
    ],
  },

  // ─── Chapter 8: Putting It All Together ───
  {
    unitNumber: 4, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'A complete training programme should consider:', options: ['Only how many days per week you train', 'Goals, frequency, exercise selection, volume, intensity, progression, and recovery', 'Only exercise selection', 'Only nutrition'], correctAnswer: 1, explanation: 'Effective programme design integrates all variables — goals, training split, exercise selection, volume, intensity, progressive overload, and recovery management.' },
      { type: 'multiple_choice', question: 'The principle of specificity states that:', options: ['Only general fitness matters', 'You should never specialise', 'Your body adapts specifically to the type of training you do', 'All exercise produces the same result'], correctAnswer: 2, explanation: 'Specificity means your body adapts to the specific demands placed on it. If you want to get stronger at squatting, you need to squat.' },
      { type: 'scenario', question: 'What is the most effective approach?', scenario: 'You have completed all units in this course. You want to design your first programme.', options: ['Copy a random programme from the internet', 'Only do cardio', 'Use the principles you have learned — set SMART goals, choose an appropriate split, select compound and accessory exercises, plan progression, and schedule recovery', 'Ask a friend with no training knowledge to design it'], correctAnswer: 2, explanation: 'Applying the principles from this course — goal setting, exercise selection, progressive overload, periodisation, and recovery — gives you the tools to design an evidence-based programme.' },
      { type: 'multiple_choice', question: 'The principle of reversibility means:', options: ['You should never take rest days', 'Training effects are permanent after 12 weeks', 'If you stop training, adaptations will gradually be lost', 'You can never lose fitness'], correctAnswer: 2, explanation: 'Reversibility (the "use it or lose it" principle) means that fitness adaptations are lost if training is discontinued. Consistency is essential for maintaining progress.' },
      { type: 'multiple_choice', question: 'The principle of individuality recognises that:', options: ['Everyone responds to training in exactly the same way', "Genetics, training history, lifestyle, and recovery capacity make each person\'s response unique", 'Only one programme works for everyone', 'Age and gender have no effect on training'], correctAnswer: 1, explanation: 'Individual differences in genetics, training age, recovery capacity, and lifestyle mean that the "best" programme is the one tailored to the individual.' },
      { type: 'multiple_choice', question: 'When designing a programme, you should start with:', options: ['Defining clear goals and working backwards to determine the appropriate training variables', 'Choosing exercises randomly', 'The most advanced techniques available', "Copying a professional athlete\'s programme"], correctAnswer: 0, explanation: 'Goal-first programming ensures every variable (exercise selection, volume, intensity, frequency) is aligned with what you are trying to achieve.' },
      { type: 'scenario', question: 'Which principle should you apply?', scenario: 'You have been running the same programme for 6 months with no changes. You are no longer making progress.', options: ['Add random exercises each session', 'Stop training entirely', 'Continue as you are — patience is key', 'Apply the principle of progressive overload and consider periodising your programme'], correctAnswer: 3, explanation: 'After 6 months without change, the stimulus is stale. Progressive overload and periodisation ensure continued adaptation.' },
      { type: 'multiple_choice', question: 'Sustainable training means:', options: ['Training at maximum intensity every session', 'Following extreme diets and programmes', 'Balancing training, recovery, nutrition, and lifestyle in a way you can maintain long-term', 'Only training when you feel perfect'], correctAnswer: 2, explanation: 'Sustainability is the foundation of long-term results. A programme you can maintain consistently for months and years will always outperform an extreme approach you abandon after weeks.' },
      { type: 'multiple_choice', question: 'The most important factor for long-term fitness results is:', options: ['Training at the most expensive gym', 'Finding the perfect programme', 'Having the best supplements', 'Consistency over time'], correctAnswer: 3, explanation: 'Consistency — showing up, training, eating well, recovering, and doing it repeatedly over months and years — is the single greatest predictor of long-term results.' },
      { type: 'multiple_choice', question: 'This course has covered anatomy, nutrition, exercise science, and programme design. The next step is:', options: ['Apply what you have learned — set goals, build a programme, start training, track progress, and adjust as needed', 'Wait for someone to tell you what to do', 'Forget everything and wing it', 'Never exercise again'], correctAnswer: 0, explanation: 'Knowledge without action is useless. The purpose of this course is to equip you with the understanding to take ownership of your own fitness journey.' },
    ],
  },
];
