import type { ChapterQuiz } from '../types';

export const unit2ChapterQuizzes: ChapterQuiz[] = [
  // ─── Chapter 1: Understanding Macronutrients ───
  {
    unitNumber: 2,
    chapterNumber: 1,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'How many calories does one gram of protein provide?',
        options: ['7 kcal', '4 kcal', '2 kcal', '9 kcal'],
        correctAnswer: 1,
        explanation: 'Protein provides 4 kcal per gram, the same as carbohydrates.',
      },
      {
        type: 'multiple_choice',
        question: 'Which macronutrient provides the most calories per gram?',
        options: ['Protein', 'Fibre', 'Carbohydrates', 'Fat'],
        correctAnswer: 3,
        explanation: 'Fat provides 9 kcal per gram — more than double the energy density of protein or carbohydrates (4 kcal each).',
      },
      {
        type: 'multiple_choice',
        question: 'What is the primary role of protein in the body?',
        options: ['Hormone regulation only', 'Muscle repair and growth', 'Hydration', 'Quick energy supply'],
        correctAnswer: 1,
        explanation: 'Protein is essential for repairing and building muscle tissue, as well as producing enzymes and hormones.',
      },
      {
        type: 'multiple_choice',
        question: 'Which of the following is a complex carbohydrate?',
        options: ['Oats', 'White bread', 'Fruit juice', 'Table sugar'],
        correctAnswer: 0,
        explanation: 'Oats are a complex carbohydrate containing long chains of glucose that digest slowly, providing sustained energy.',
      },
      {
        type: 'scenario',
        question: 'What should you focus on to improve recovery?',
        scenario: 'You have been training hard but notice slow recovery and persistent muscle soreness. Your diet is mostly carbohydrate-based with minimal protein.',
        options: ['Eat more carbohydrates', 'Increase your protein intake', 'Eliminate fats completely', 'Reduce training volume only'],
        correctAnswer: 1,
        explanation: 'Insufficient protein impairs muscle repair. Increasing protein intake (alongside adequate overall nutrition) supports faster recovery from training.',
      },
      {
        type: 'multiple_choice',
        question: 'Which fat source is considered a healthy unsaturated fat?',
        options: ['Palm oil', 'Olive oil', 'Butter', 'Lard'],
        correctAnswer: 1,
        explanation: 'Olive oil is rich in monounsaturated fatty acids, which support cardiovascular health and reduce inflammation.',
      },
      {
        type: 'multiple_choice',
        question: 'Simple carbohydrates are characterised by:',
        options: ['High fat content', 'Slow digestion and sustained energy', 'High protein content', 'Rapid digestion and quick energy release'],
        correctAnswer: 3,
        explanation: 'Simple carbohydrates (sugars) are quickly digested and absorbed, causing a rapid rise in blood sugar.',
      },
      {
        type: 'multiple_choice',
        question: 'Which of the following is a complete protein source?',
        options: ['Lentils', 'Rice', 'Bread', 'Chicken breast'],
        correctAnswer: 3,
        explanation: 'Chicken breast contains all essential amino acids, making it a complete protein source. Plant sources often need combining for a full amino acid profile.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely nutritional issue?',
        scenario: 'You feel lethargic during workouts despite sleeping well. Your daily diet is very low in carbohydrates.',
        options: ['Insufficient carbohydrates for training energy', 'Excess fat intake', 'Too much protein', 'Too much fibre'],
        correctAnswer: 0,
        explanation: "Carbohydrates are the body\'s preferred fuel source for moderate-to-high intensity exercise. Very low carb intake often causes fatigue during training.",
      },
      {
        type: 'multiple_choice',
        question: 'Trans fats are considered unhealthy because they:',
        options: ['Taste unpleasant', 'Increase LDL cholesterol and inflammation', 'Provide too many calories', 'Contain no energy'],
        correctAnswer: 1,
        explanation: 'Trans fats raise LDL ("bad") cholesterol, lower HDL ("good") cholesterol, and increase inflammation — all risk factors for cardiovascular disease.',
      },
    ],
  },

  // ─── Chapter 2: Understanding Micronutrients ───
  {
    unitNumber: 2,
    chapterNumber: 2,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Micronutrients are needed by the body in:',
        options: ['Large quantities (grams per day)', 'Only during illness', 'Small quantities (milligrams or micrograms)', 'Equal amounts to macronutrients'],
        correctAnswer: 2,
        explanation: 'Micronutrients (vitamins and minerals) are required in small amounts but are essential for hundreds of bodily processes.',
      },
      {
        type: 'multiple_choice',
        question: 'Which vitamin is primarily obtained through sunlight exposure?',
        options: ['Vitamin C', 'Vitamin A', 'Vitamin D', 'Vitamin B12'],
        correctAnswer: 2,
        explanation: 'Vitamin D is synthesised in the skin when exposed to UVB sunlight. Many people in northern climates are deficient and may benefit from supplementation.',
      },
      {
        type: 'multiple_choice',
        question: 'Iron deficiency most commonly results in:',
        options: ['Stronger bones', 'Fatigue and reduced oxygen transport', 'Better sleep quality', 'Improved immunity'],
        correctAnswer: 1,
        explanation: 'Iron is essential for haemoglobin production. Deficiency reduces oxygen-carrying capacity, causing fatigue, weakness, and poor exercise performance.',
      },
      {
        type: 'multiple_choice',
        question: 'Which mineral is most important for bone health?',
        options: ['Calcium', 'Magnesium', 'Potassium', 'Zinc'],
        correctAnswer: 0,
        explanation: 'Calcium is the primary mineral in bones and teeth. Adequate calcium intake, combined with vitamin D, supports bone density and strength.',
      },
      {
        type: 'scenario',
        question: 'Which micronutrient deficiency is most likely?',
        scenario: 'You frequently get ill and notice your immune system seems weaker than usual. Your diet lacks fresh fruit and vegetables.',
        options: ['Vitamin B12', 'Vitamin D and vitamin C', 'Sodium', 'Iron only'],
        correctAnswer: 1,
        explanation: 'Vitamins C and D both play crucial roles in immune function. A diet lacking fresh produce is likely low in vitamin C, and inadequate sunlight can cause low vitamin D.',
      },
      {
        type: 'multiple_choice',
        question: 'Fat-soluble vitamins include:',
        options: ['Vitamins B and C', 'Vitamins B6, B12, and folate', 'Vitamins A, D, E, and K', 'Only vitamin D'],
        correctAnswer: 2,
        explanation: 'Vitamins A, D, E, and K are fat-soluble — they are stored in body fat and the liver, and require dietary fat for absorption.',
      },
      {
        type: 'multiple_choice',
        question: 'Which food is a strong source of vitamin C?',
        options: ['Cheese', 'Chicken breast', 'Red peppers', 'White rice'],
        correctAnswer: 2,
        explanation: 'Red peppers are one of the richest sources of vitamin C, containing more per gram than oranges.',
      },
      {
        type: 'multiple_choice',
        question: 'Magnesium plays a key role in:',
        options: ['Fat digestion', 'Muscle function, nerve signalling, and sleep quality', 'Blood clotting only', 'Red blood cell production only'],
        correctAnswer: 1,
        explanation: 'Magnesium is involved in over 300 enzymatic reactions, including muscle contraction, nerve function, and supporting sleep quality.',
      },
      {
        type: 'scenario',
        question: 'What is the best dietary approach?',
        scenario: 'You want to improve your micronutrient intake but prefer not to take supplements.',
        options: ['Drink more water instead', 'Focus only on protein-rich foods', 'Eat the same foods every day for consistency', 'Eat a varied diet with colourful fruits, vegetables, lean proteins, and whole grains'],
        correctAnswer: 3,
        explanation: 'A varied, colourful diet naturally provides a wide range of vitamins and minerals. Different colours in fruits and vegetables indicate different micronutrient profiles.',
      },
      {
        type: 'multiple_choice',
        question: 'Zinc is important for:',
        options: ['Hydration', 'Immune function, wound healing, and protein synthesis', 'Bone density only', 'Carbohydrate storage'],
        correctAnswer: 1,
        explanation: 'Zinc supports immune function, wound healing, protein synthesis, and cell division. Good sources include meat, shellfish, seeds, and legumes.',
      },
    ],
  },

  // ─── Chapter 3: Hydration ───
  {
    unitNumber: 2,
    chapterNumber: 3,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Approximately what percentage of the human body is water?',
        options: ['70–80%', '90–95%', '30–40%', '50–60%'],
        correctAnswer: 3,
        explanation: 'The human body is approximately 50–60% water, varying by age, sex, and body composition.',
      },
      {
        type: 'multiple_choice',
        question: 'A general daily water intake guideline for active adults is approximately:',
        options: ['1 litre', '2–3 litres', '5 litres', '500 ml'],
        correctAnswer: 1,
        explanation: 'Most active adults should aim for approximately 2–3 litres of water per day, with more needed during intense exercise or hot weather.',
      },
      {
        type: 'multiple_choice',
        question: 'Dehydration of just 2% of body weight can:',
        options: ['Only affect endurance athletes', 'Improve focus', 'Significantly impair physical and mental performance', 'Have no noticeable effect'],
        correctAnswer: 2,
        explanation: 'Even mild dehydration (2% body weight loss) can reduce strength, endurance, cognitive function, and reaction time.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely cause?',
        scenario: 'During a long training session, you notice a headache, dry mouth, and dark-coloured urine.',
        options: ['Dehydration', 'Overhydration', 'Low blood sugar only', 'Excess protein intake'],
        correctAnswer: 0,
        explanation: 'Headache, dry mouth, and dark urine are classic signs of dehydration. Sipping water regularly throughout training prevents this.',
      },
      {
        type: 'multiple_choice',
        question: 'Electrolytes include which of the following?',
        options: ['Protein, carbohydrates, and fats', 'Iron and zinc only', 'Vitamins A, C, and D', 'Sodium, potassium, and magnesium'],
        correctAnswer: 3,
        explanation: 'Electrolytes are minerals that carry electrical charges — sodium, potassium, magnesium, and calcium are the key electrolytes involved in hydration and muscle function.',
      },
      {
        type: 'multiple_choice',
        question: 'The colour of your urine is a practical indicator of:',
        options: ['Sleep quality', 'Protein intake', 'Calorie intake', 'Hydration status'],
        correctAnswer: 3,
        explanation: 'Pale straw-coloured urine generally indicates good hydration, while dark yellow or amber urine suggests dehydration.',
      },
      {
        type: 'multiple_choice',
        question: 'Which drink is most effective for basic hydration during moderate exercise?',
        options: ['Fruit juice concentrate', 'Milk', 'Energy drinks with caffeine', 'Water'],
        correctAnswer: 3,
        explanation: 'For most moderate-intensity exercise, water is the most effective and practical hydration choice.',
      },
      {
        type: 'scenario',
        question: 'When is the best time to hydrate?',
        scenario: 'You are preparing for a 90-minute football match on a warm day.',
        options: ['Before, during, and after the match', 'Only during half-time', 'Drink 2 litres just before kick-off', 'Only after the match'],
        correctAnswer: 0,
        explanation: 'Optimal hydration involves drinking before (pre-hydration), during (regular sips), and after (rehydration) prolonged exercise, especially in warm conditions.',
      },
      {
        type: 'multiple_choice',
        question: 'Hyponatraemia (overhydration) occurs when:',
        options: ['You eat too much salt', 'You drink too little water', 'You drink excessive water without replacing electrolytes, diluting blood sodium', 'You exercise in cold weather'],
        correctAnswer: 2,
        explanation: 'Hyponatraemia is a dangerous condition where excessive water intake dilutes blood sodium levels. It is rare but can occur during prolonged endurance events.',
      },
      {
        type: 'multiple_choice',
        question: 'Coffee and tea contribute to daily fluid intake:',
        options: ['Only in cold weather', 'Only if decaffeinated', 'Yes — they contribute to hydration despite mild diuretic effects', 'Not at all — caffeine is purely dehydrating'],
        correctAnswer: 2,
        explanation: 'While caffeine has a mild diuretic effect, the water content of coffee and tea still contributes positively to overall fluid intake.',
      },
    ],
  },

  // ─── Chapter 4: Energy Balance ───
  {
    unitNumber: 2,
    chapterNumber: 4,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'A caloric surplus means:',
        options: ['You consume fewer calories than you burn', 'You consume more calories than you burn', 'You consume exactly the same as you burn', 'You skip meals regularly'],
        correctAnswer: 1,
        explanation: 'A caloric surplus occurs when energy intake exceeds energy expenditure, leading to weight gain (ideally muscle mass if training appropriately).',
      },
      {
        type: 'multiple_choice',
        question: 'BMR stands for:',
        options: ['Body Mass Ratio', 'Base Muscle Recovery', 'Basal Metabolic Rate', 'Balanced Macro Requirement'],
        correctAnswer: 2,
        explanation: 'Basal Metabolic Rate (BMR) is the number of calories your body burns at complete rest to maintain basic life functions like breathing and circulation.',
      },
      {
        type: 'multiple_choice',
        question: 'TDEE stands for:',
        options: ['Total Daily Energy Expenditure', 'Training Duration and Exercise Effort', 'Total Dietary Energy Estimate', 'Tracked Daily Eating Evaluation'],
        correctAnswer: 0,
        explanation: 'Total Daily Energy Expenditure is the total number of calories you burn per day, including BMR, physical activity, and the thermic effect of food.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely reason?',
        scenario: 'You have been eating in what you believe is a caloric deficit for 4 weeks but have not lost any weight.',
        options: ['Deficits never work', 'You are gaining muscle at the exact same rate as losing fat', 'Your metabolism has permanently shut down', 'You may be underestimating your calorie intake or overestimating your expenditure'],
        correctAnswer: 3,
        explanation: 'The most common reason for stalled fat loss is inaccurate tracking — underestimating food intake or overestimating calories burned through exercise.',
      },
      {
        type: 'multiple_choice',
        question: 'The thermic effect of food (TEF) refers to:',
        options: ['Calories burned during exercise', 'Heat produced during sleep', 'Calories stored as body fat', 'Calories burned digesting and processing food'],
        correctAnswer: 3,
        explanation: 'TEF is the energy required to digest, absorb, and process nutrients. Protein has the highest TEF (20–30%), meaning more energy is used digesting protein than carbs or fats.',
      },
      {
        type: 'multiple_choice',
        question: 'To lose approximately 0.5 kg of body fat per week, you need a weekly deficit of roughly:',
        options: ['1,000 kcal', '2,000 kcal', '3,500 kcal', '5,000 kcal'],
        correctAnswer: 2,
        explanation: 'One pound (approximately 0.5 kg) of body fat contains roughly 3,500 kcal. A deficit of 500 kcal per day creates a weekly deficit of 3,500 kcal.',
      },
      {
        type: 'scenario',
        question: 'What approach should you take?',
        scenario: 'You want to build muscle but are worried about gaining excess body fat.',
        options: ['Eat at maintenance only', 'Eat in a moderate surplus of 200–400 kcal per day with adequate protein', 'Eat in a deficit to stay lean', 'Eat in a large surplus of 1,000+ kcal per day'],
        correctAnswer: 1,
        explanation: 'A moderate surplus (200–400 kcal above TDEE) with adequate protein supports muscle growth while minimising unnecessary fat gain — sometimes called a "lean bulk".',
      },
      {
        type: 'multiple_choice',
        question: 'NEAT stands for:',
        options: ['Natural Energy Absorption Total', 'Non-Exercise Activity Thermogenesis', 'Necessary Eating and Training', 'Nutrition and Exercise Assessment Tool'],
        correctAnswer: 1,
        explanation: 'NEAT includes all the calories burned through non-exercise movement — walking, fidgeting, cleaning, standing. It can vary by hundreds of calories per day between individuals.',
      },
      {
        type: 'multiple_choice',
        question: 'Which component makes up the largest portion of TDEE for most people?',
        options: ['NEAT', 'Thermic effect of food', 'BMR', 'Exercise activity'],
        correctAnswer: 2,
        explanation: 'BMR typically accounts for 60–70% of total daily energy expenditure — your body burns the majority of its calories just maintaining basic functions.',
      },
      {
        type: 'multiple_choice',
        question: 'Maintenance calories are:',
        options: ['The minimum calories needed to survive', 'The number of calories where weight remains stable', 'A fixed number for all people', 'The maximum calories before gaining fat'],
        correctAnswer: 1,
        explanation: 'Maintenance calories equal your TDEE — the point where energy intake matches energy expenditure and body weight remains relatively stable.',
      },
    ],
  },

  // ─── Chapter 5: Reading Food Labels ───
  {
    unitNumber: 2,
    chapterNumber: 5,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'On a UK food label, nutritional values are typically displayed per:',
        options: ['Per item only', 'Per 100g and per serving', 'Per meal', 'Per kilogram'],
        correctAnswer: 1,
        explanation: 'UK food labels standardise nutritional information per 100g (for comparison) and often per serving (for practical use).',
      },
      {
        type: 'multiple_choice',
        question: 'The "traffic light" labelling system uses which colours?',
        options: ['Red, amber, green', 'Black, white, grey', 'Blue, yellow, purple', 'Orange, blue, green'],
        correctAnswer: 0,
        explanation: 'The traffic light system uses red (high), amber (medium), and green (low) to quickly indicate levels of fat, saturated fat, sugar, and salt.',
      },
      {
        type: 'scenario',
        question: 'What should you check first?',
        scenario: 'You are comparing two protein bars. Bar A shows 20g protein per bar. Bar B shows 25g protein per 100g. Bar A weighs 60g, Bar B weighs 50g.',
        options: ['Assume Bar B is better because 25 > 20', 'Choose whichever is cheaper', 'Calculate the actual protein per bar for a fair comparison', 'Ignore protein and check calories only'],
        correctAnswer: 2,
        explanation: 'Bar A has 20g per 60g bar. Bar B has 25g per 100g = 12.5g per 50g bar. Bar A actually delivers more protein per bar. Always compare like-for-like.',
      },
      {
        type: 'multiple_choice',
        question: 'Ingredients on a food label are listed in order of:',
        options: ['Alphabetical order', 'Weight (highest first)', 'Nutritional importance', 'Calorie content'],
        correctAnswer: 1,
        explanation: 'Ingredients are listed in descending order by weight. The first ingredient is present in the highest quantity.',
      },
      {
        type: 'multiple_choice',
        question: 'A food labelled "low fat" in the UK must contain no more than:',
        options: ['3g fat per 100g', '1g fat per 100g', '10g fat per 100g', '5g fat per 100g'],
        correctAnswer: 0,
        explanation: 'In the UK, "low fat" means the product contains no more than 3g of fat per 100g (or 1.5g per 100ml for liquids).',
      },
      {
        type: 'multiple_choice',
        question: '"Of which sugars" on a food label refers to:',
        options: ['Artificial sweeteners', 'Sugar alcohols only', 'Total sugars including natural and added', 'Only added sugars'],
        correctAnswer: 2,
        explanation: '"Of which sugars" includes all sugars — both naturally occurring (e.g., lactose in milk) and added sugars.',
      },
      {
        type: 'scenario',
        question: 'Which is the better choice for a lower-sugar option?',
        scenario: 'You are choosing between two yoghurts. Yoghurt A: 12g sugar per 100g. Yoghurt B: 5g sugar per 100g but has artificial sweeteners listed.',
        options: ['Yoghurt B — it has less sugar per serving', 'Neither — all yoghurt is unhealthy', 'Yoghurt A — natural sugar is always better', 'It depends on your personal goals and preferences'],
        correctAnswer: 3,
        explanation: 'Both are valid choices. If reducing sugar intake is your goal, Yoghurt B has less sugar. If you prefer avoiding sweeteners, Yoghurt A is fine in moderation. Context matters.',
      },
      {
        type: 'multiple_choice',
        question: 'The Reference Intake (RI) on food labels is based on:',
        options: ['Individual personalised requirements', 'A 2,000 kcal diet for an average adult', 'A 1,500 kcal diet', 'A 3,000 kcal diet for athletes'],
        correctAnswer: 1,
        explanation: 'Reference Intakes are based on a general 2,000 kcal daily diet. Individual needs may be higher or lower depending on activity level, size, and goals.',
      },
      {
        type: 'multiple_choice',
        question: 'Fibre content on a food label is useful because:',
        options: ['It tells you the protein quality', 'It has no practical use', 'Higher fibre foods tend to be more filling and support digestive health', 'It indicates how processed the food is'],
        correctAnswer: 2,
        explanation: 'Fibre supports digestive health, blood sugar regulation, and satiety. Choosing higher-fibre options is generally beneficial.',
      },
      {
        type: 'multiple_choice',
        question: 'Salt content on food labels is important because:',
        options: ['All foods contain the same amount of salt', 'Excessive salt intake is linked to high blood pressure', 'Salt only matters for athletes', 'Salt has no health implications'],
        correctAnswer: 1,
        explanation: 'High salt (sodium) intake is associated with increased blood pressure and cardiovascular risk. Adults should aim for no more than 6g of salt per day.',
      },
    ],
  },

  // ─── Chapter 6: Nutrient Timing Basics ───
  {
    unitNumber: 2,
    chapterNumber: 6,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'The "anabolic window" is often described as:',
        options: ['The first meal of the day', 'A 30–60 minute period after training where nutrient uptake may be enhanced', 'A myth with no basis in science', 'A 10-minute period before sleep'],
        correctAnswer: 1,
        explanation: 'The anabolic window refers to the post-exercise period where muscles are primed for nutrient uptake. While the window is wider than once thought, eating protein and carbs after training does support recovery.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the most important factor for body composition results?',
        options: ['Never eating after 8 pm', 'Eating within 15 minutes of waking', 'Total daily calorie and macronutrient intake', 'Exact meal timing'],
        correctAnswer: 2,
        explanation: 'Total daily intake of calories and macronutrients matters far more than the exact timing of meals. Consistency with overall nutrition trumps precise timing.',
      },
      {
        type: 'scenario',
        question: 'What is the most practical approach?',
        scenario: 'You train at 6 am and struggle to eat a large meal beforehand. You worry this will reduce your performance.',
        options: ['Skip training until you can eat first', 'Have a small, easily digestible snack like a banana, or train fasted and eat well afterwards', 'Force yourself to eat a large meal at 5 am', 'Drink a mass gainer shake at 4 am'],
        correctAnswer: 1,
        explanation: 'A small, easily digestible snack provides some fuel without discomfort. Training fasted is also fine for most people if you eat well post-workout.',
      },
      {
        type: 'multiple_choice',
        question: 'Pre-workout nutrition should ideally include:',
        options: ['A large meal eaten immediately before training', 'Carbohydrates for energy and some protein', 'Only water', 'Only fats for slow energy'],
        correctAnswer: 1,
        explanation: 'A balanced pre-workout meal or snack with carbohydrates (for energy) and some protein (for muscle support) 1–3 hours before training is ideal.',
      },
      {
        type: 'multiple_choice',
        question: 'Post-workout nutrition should prioritise:',
        options: ['Fat only, for hormone production', 'Fasting for 4 hours to maximise fat burn', 'Only water', 'Protein for muscle repair and carbohydrates for glycogen replenishment'],
        correctAnswer: 3,
        explanation: 'After training, protein supports muscle repair and carbohydrates replenish glycogen stores. This combination accelerates recovery.',
      },
      {
        type: 'multiple_choice',
        question: 'Eating protein before bed is:',
        options: ['Potentially beneficial for overnight muscle protein synthesis', 'Completely irrelevant', 'Only beneficial for bodybuilders', 'Always harmful'],
        correctAnswer: 0,
        explanation: 'A protein-rich snack before bed (e.g., casein, Greek yoghurt) can support overnight muscle protein synthesis, especially if daily protein targets are not yet met.',
      },
      {
        type: 'scenario',
        question: 'What is the best advice?',
        scenario: 'A friend tells you that eating carbohydrates after 6 pm will make you gain fat.',
        options: ['They are correct — avoid carbs after 6 pm', 'Carbs should only be eaten during exercise', 'This is a myth — total daily intake matters more than the time you eat carbs', 'Only eat carbs before noon'],
        correctAnswer: 2,
        explanation: 'There is no evidence that eating carbohydrates after a specific time causes fat gain. What matters is your total daily calorie and macronutrient intake relative to your needs.',
      },
      {
        type: 'multiple_choice',
        question: 'How many meals per day is optimal for muscle growth?',
        options: ['It makes no difference at all', 'Exactly 6 small meals', 'One large meal', '3–5 meals, distributed across the day'],
        correctAnswer: 3,
        explanation: 'Distributing protein across 3–5 meals helps maintain elevated muscle protein synthesis throughout the day, though total daily intake remains the primary driver.',
      },
      {
        type: 'multiple_choice',
        question: 'Glycogen is primarily stored in:',
        options: ['The bloodstream', 'The brain', 'Muscles and the liver', 'Body fat'],
        correctAnswer: 2,
        explanation: 'Glycogen (stored carbohydrate) is found primarily in skeletal muscles and the liver. It serves as a readily available energy source during exercise.',
      },
      {
        type: 'multiple_choice',
        question: 'The concept of "nutrient timing" is most important for:',
        options: ['Anyone eating fewer than 1,000 kcal per day', 'Competitive athletes with optimised diets', 'People who never exercise', 'Complete beginners only'],
        correctAnswer: 1,
        explanation: 'Nutrient timing becomes more relevant for competitive athletes who have already optimised total intake. For most people, nailing total daily nutrition comes first.',
      },
    ],
  },

  // ─── Chapter 7: Building a Balanced Plate ───
  {
    unitNumber: 2,
    chapterNumber: 7,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'A balanced meal should ideally contain:',
        options: ['Supplements only', 'Protein, carbohydrates, fats, and vegetables', 'Only protein', 'Only carbohydrates for energy'],
        correctAnswer: 1,
        explanation: 'A balanced meal includes all macronutrients — protein for repair, carbohydrates for energy, healthy fats, and vegetables for micronutrients and fibre.',
      },
      {
        type: 'multiple_choice',
        question: 'The "plate model" typically suggests vegetables should make up approximately:',
        options: ['Half the plate', '10% of the plate', 'The entire plate', 'A quarter of the plate'],
        correctAnswer: 0,
        explanation: 'The balanced plate model typically recommends filling half your plate with vegetables and salad, with the other half split between protein and carbohydrates.',
      },
      {
        type: 'scenario',
        question: 'How could you improve this meal?',
        scenario: 'Your typical lunch is a large portion of white pasta with tomato sauce. You feel hungry again within an hour.',
        options: ['Eat more pasta', 'Add a protein source and some vegetables to increase satiety', 'Skip lunch entirely', 'Replace with a protein shake only'],
        correctAnswer: 1,
        explanation: 'Adding protein and vegetables increases satiety (fullness) and improves the nutritional balance of the meal, keeping you satisfied for longer.',
      },
      {
        type: 'multiple_choice',
        question: 'Meal prep is beneficial because it:',
        options: ['Helps control portions, saves time, and supports dietary consistency', 'Is only useful for bodybuilders', 'Eliminates the need for fresh food', 'Requires professional cooking skills'],
        correctAnswer: 0,
        explanation: 'Meal prepping helps you plan portions, control ingredients, save time during busy days, and stay consistent with your nutritional goals.',
      },
      {
        type: 'multiple_choice',
        question: 'Which approach is most sustainable for long-term healthy eating?',
        options: ['Eating only "clean" foods with zero treats', 'Following the latest social media diet trend', 'Flexible eating that includes mostly whole foods with room for enjoyment', 'Strict elimination diets'],
        correctAnswer: 2,
        explanation: 'Sustainable nutrition is built on consistency, not perfection. An 80/20 approach — mostly whole foods with flexibility — supports both health and long-term adherence.',
      },
      {
        type: 'multiple_choice',
        question: 'A portion of protein is roughly equivalent to:',
        options: ['The size of your forearm', 'The size of your head', 'The size of your fist', 'The size of your palm'],
        correctAnswer: 3,
        explanation: 'A palm-sized portion of protein (about 20–30g) is a practical visual guide for estimating protein at meals without weighing food.',
      },
      {
        type: 'scenario',
        question: 'What is the simplest improvement?',
        scenario: 'You eat well during the week but struggle at weekends, often consuming takeaways and large amounts of snack food.',
        options: ['Only eat during the week and fast at weekends', 'Accept that weekends will always undo your progress', 'Plan and prep some balanced meals for the weekend too, while allowing occasional treats', 'Restrict all food at weekends'],
        correctAnswer: 2,
        explanation: 'Having some planned meals at weekends maintains structure without requiring perfection. Allowing occasional treats prevents binge-restrict cycles.',
      },
      {
        type: 'multiple_choice',
        question: 'Ultra-processed foods are characterised by:',
        options: ['Being always healthy because they are convenient', 'Being fresh and minimally altered', 'Containing long ingredient lists with additives, preservatives, and artificial flavourings', 'Having high micronutrient density'],
        correctAnswer: 2,
        explanation: 'Ultra-processed foods typically contain many artificial additives and offer low nutritional value relative to their calorie content. Minimising these supports better health outcomes.',
      },
      {
        type: 'multiple_choice',
        question: 'Fibre-rich foods include:',
        options: ['White bread and pasta', 'Butter and cream', 'Chicken and fish', 'Vegetables, legumes, oats, and whole grains'],
        correctAnswer: 3,
        explanation: 'Fibre is found in plant-based foods — vegetables, fruits, legumes, oats, and whole grains are excellent sources.',
      },
      {
        type: 'multiple_choice',
        question: 'The best way to assess if your diet is working is to:',
        options: ['Only check the scales daily', 'Compare yourself to social media influencers', 'Rely on how you feel after one meal', 'Track a combination of weight trends, energy levels, performance, and how clothes fit'],
        correctAnswer: 3,
        explanation: 'A holistic approach — tracking weight trends over weeks, monitoring energy and performance, and noting how clothes fit — gives a more accurate picture than any single metric.',
      },
    ],
  },
  // ─── Chapter 8: Common Nutrition Myths & Misconceptions ───
  {
    unitNumber: 2,
    chapterNumber: 8,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Why is the claim "eating fat makes you fat" considered a myth?',
        options: ['Fat has no calories', 'Body fat storage is primarily determined by total energy balance, not dietary fat alone', 'Fat is immediately burned for energy', 'Only saturated fat causes weight gain'],
        correctAnswer: 1,
        explanation: 'Body fat storage depends on total calorie intake vs expenditure (energy balance), not specifically on how much dietary fat you eat. You can gain fat from any macronutrient in surplus.',
      },
      {
        type: 'multiple_choice',
        question: 'Does eating six small meals instead of three larger meals boost your metabolism?',
        options: ['No — the thermic effect of food is proportional to total intake, not meal frequency', 'No, but it reduces fat storage', 'Yes, it keeps the metabolic fire burning', 'Yes, but only if you eat protein at every meal'],
        correctAnswer: 0,
        explanation: 'Research consistently shows that meal frequency has minimal impact on metabolic rate when total daily intake is the same. The thermic effect of food is proportional to total calories consumed.',
      },
      {
        type: 'scenario',
        question: 'What is the best evidence-based response?',
        scenario: 'A friend tells you they avoid all carbohydrates after 6pm because they believe carbs eaten in the evening automatically turn to fat.',
        options: ['They should avoid carbs entirely', 'They are correct — carbs after 6pm are stored as fat', 'Carbs should only be eaten at breakfast', 'The time you eat carbs does not determine fat storage — total daily intake relative to expenditure is what matters'],
        correctAnswer: 3,
        explanation: 'Your body does not have a clock that switches to fat-storage mode at a specific time. Fat gain depends on total energy balance across the day, not when specific macronutrients are consumed.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the "30g protein per meal" myth?',
        options: ['Protein above 30g is converted to fat', 'You need 30g of protein per kg of bodyweight', 'Your body can only absorb 30g of protein per sitting — this is false', 'You should eat exactly 30g at every meal'],
        correctAnswer: 2,
        explanation: 'The body can absorb far more than 30g of protein per meal. While distributing protein across meals may optimise muscle protein synthesis, there is no hard absorption ceiling at 30g.',
      },
      {
        type: 'multiple_choice',
        question: 'Which of these is the best way to evaluate a nutrition claim you see online?',
        options: ['Check who benefits financially, look for multiple studies, and assess whether it sounds too good to be true', 'Trust it if the person has lots of followers', 'Only trust claims from supplement companies', 'Believe it if it has a scientific-sounding name'],
        correctAnswer: 0,
        explanation: 'Critical evaluation involves checking for financial incentives, looking at the body of evidence (not just one study), distinguishing correlation from causation, and applying the "too good to be true" test.',
      },
      {
        type: 'multiple_choice',
        question: 'Why are "detox diets" considered ineffective by evidence-based nutrition science?',
        options: ['Your liver and kidneys already detoxify your body effectively — detox products mostly cause water loss', 'They are effective but only if combined with exercise', 'They work but only for specific toxins', 'They are too expensive'],
        correctAnswer: 0,
        explanation: 'Your liver and kidneys are highly effective detoxification systems that work 24/7. Most "detox" products act as laxatives or diuretics, causing temporary water weight loss that returns when normal eating resumes.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the difference between correlation and causation in nutrition research?',
        options: ['Correlation is only found in animal studies', 'Correlation means two things happen together; causation means one directly causes the other', 'Causation is less reliable than correlation', 'They mean the same thing'],
        correctAnswer: 1,
        explanation: 'Correlation means two variables are associated (happen together) but one does not necessarily cause the other. For example, breakfast eaters may weigh less not because breakfast causes weight loss, but because health-conscious people tend to eat breakfast.',
      },
    ],
  },
];
