import type { ChapterQuiz } from '../types';

export const unit3ChapterQuizzes: ChapterQuiz[] = [
  // ─── Chapter 1: Types of Training ───
  {
    unitNumber: 3, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Resistance training primarily develops:', options: ['Muscular strength and hypertrophy', 'Balance only', 'Cardiovascular endurance', 'Flexibility only'], correctAnswer: 0, explanation: 'Resistance training uses external load to stimulate muscular strength, size (hypertrophy), and endurance adaptations.' },
      { type: 'multiple_choice', question: 'Which training type uses sustained, rhythmic activity to improve heart and lung function?', options: ['Plyometric training', 'Cardiovascular training', 'Flexibility training', 'Resistance training'], correctAnswer: 1, explanation: 'Cardiovascular (aerobic) training involves sustained activity — running, cycling, swimming — that challenges the heart and lungs.' },
      { type: 'multiple_choice', question: 'HIIT stands for:', options: ['Heavy Impact Isolation Training', 'High Intensity Interval Training', 'Hybrid Integrated Intensity Technique', 'Heart Induced Interval Threshold'], correctAnswer: 1, explanation: 'High-Intensity Interval Training alternates between short bursts of intense effort and rest or low-intensity periods.' },
      { type: 'scenario', question: 'Which training type should you add?', scenario: 'Your programme consists only of heavy lifting. You notice poor cardiovascular fitness and get breathless walking upstairs.', options: ['Cardiovascular training', 'Reduce all training', 'Only stretching', 'More heavy lifting'], correctAnswer: 0, explanation: 'Adding cardiovascular training improves aerobic fitness, heart health, and general endurance — complementing strength work.' },
      { type: 'multiple_choice', question: 'Flexibility training helps to:', options: ['Burn the most calories', 'Replace cardiovascular training', 'Increase range of motion and reduce injury risk', 'Build maximum strength'], correctAnswer: 2, explanation: 'Flexibility training improves joint range of motion, reduces stiffness, and can help prevent injury when combined with strength training.' },
      { type: 'multiple_choice', question: 'A balanced training programme should include:', options: ['Only flexibility training', 'Only cardiovascular training', 'Only one type of training', 'A combination of resistance, cardiovascular, and flexibility work'], correctAnswer: 3, explanation: 'Combining resistance, cardiovascular, and flexibility training addresses all components of fitness for overall health and performance.' },
      { type: 'multiple_choice', question: 'Plyometric training involves:', options: ['Static stretching holds', 'Slow, controlled movements', 'Long-duration steady-state exercise', 'Explosive, jump-based movements'], correctAnswer: 3, explanation: 'Plyometrics use the stretch-shortening cycle — explosive jumps, bounds, and throws — to develop power and reactive strength.' },
      { type: 'scenario', question: 'What is the best approach?', scenario: 'You want to improve both your 5K running time and your squat strength.', options: ['Only squat more', 'Choose one goal and abandon the other', 'Include both cardiovascular and resistance training, managing recovery', 'Only run more'], correctAnswer: 2, explanation: 'Concurrent training (combining both) is effective when programmed with adequate recovery. Prioritise based on which goal matters more.' },
      { type: 'multiple_choice', question: 'Isometric exercise involves:', options: ['Only using body weight', 'Holding a static position under tension without joint movement', 'Only using machines', 'Moving through a full range of motion'], correctAnswer: 1, explanation: 'Isometric exercises (like a plank or wall sit) involve holding a position — the muscle contracts but does not change length.' },
      { type: 'multiple_choice', question: 'Which training type is best suited for improving bone density?', options: ['Meditation', 'Flexibility training', 'Swimming only', 'Resistance and weight-bearing training'], correctAnswer: 3, explanation: 'Weight-bearing and resistance training apply mechanical stress to bones, stimulating increased bone density over time.' },
    ],
  },

  // ─── Chapter 2: Warm-Up and Cool-Down ───
  {
    unitNumber: 3, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'The primary purpose of a warm-up is to:', options: ['Improve flexibility permanently', 'Gradually increase heart rate, blood flow, and prepare muscles and joints for exercise', 'Burn maximum calories before training', 'Replace the main workout on easy days'], correctAnswer: 1, explanation: 'A warm-up prepares the body by increasing core temperature, blood flow to muscles, joint lubrication, and neural readiness.' },
      { type: 'multiple_choice', question: 'A RAMP warm-up protocol stands for:', options: ['Run, Assess, Move, Push', 'Raise, Activate, Mobilise, Potentiate', 'Relax, Align, Mobilise, Prepare', 'Rest, Activate, Move, Perform'], correctAnswer: 1, explanation: 'RAMP: Raise (heart rate and temperature), Activate (key muscles), Mobilise (joints through range), Potentiate (prime for the specific session).' },
      { type: 'multiple_choice', question: 'Static stretching before resistance training is generally:', options: ['The best warm-up method', 'Not recommended — it can temporarily reduce force production', 'Essential for injury prevention', 'Only harmful for beginners'], correctAnswer: 1, explanation: 'Static stretching before heavy lifting can reduce power output and force production. Dynamic warm-ups are preferred before training.' },
      { type: 'scenario', question: 'What is the best warm-up approach?', scenario: 'You are about to perform heavy squats. You currently just walk on the treadmill for 5 minutes and then load the bar.', options: ['Do 30 minutes of cycling instead', 'Continue as you are', 'Skip the warm-up to save time', 'Add dynamic leg swings, bodyweight squats, and warm-up sets with progressively heavier loads'], correctAnswer: 3, explanation: 'A squat-specific warm-up should include dynamic mobility, activation drills, and ramping sets with increasing weight to prepare the muscles and joints.' },
      { type: 'multiple_choice', question: 'The cool-down after training should include:', options: ['Light activity to gradually lower heart rate, followed by static stretching', 'Nothing — cool-downs are unnecessary', 'Heavy lifting at reduced volume', 'Immediately sitting down'], correctAnswer: 0, explanation: 'A cool-down gradually lowers heart rate, prevents blood pooling, and supports recovery. Static stretching is appropriate here for flexibility.' },
      { type: 'multiple_choice', question: 'Dynamic stretching involves:', options: ['Holding a stretch for 30+ seconds', 'Bouncing aggressively at end range', 'Moving through a range of motion in a controlled, rhythmic manner', 'Only static holds'], correctAnswer: 2, explanation: 'Dynamic stretching uses controlled movements through the range of motion — leg swings, arm circles, walking lunges — to prepare for exercise.' },
      { type: 'multiple_choice', question: 'Warm-up sets for a main lift should:', options: ['Be at your working weight from the first set', 'Progressively increase in weight while decreasing in reps', 'Be skipped if you feel warmed up', 'Only use an empty bar regardless of working weight'], correctAnswer: 1, explanation: 'Ramping sets gradually increase the load, preparing your muscles, joints, and nervous system for the heavier working sets.' },
      { type: 'scenario', question: 'What is the likely issue?', scenario: 'You regularly skip your cool-down after intense training and notice increased muscle stiffness the following day.', options: ['Skipping the cool-down may contribute to increased DOMS and stiffness', 'You need more sleep only', 'Stiffness is unrelated to cool-downs', 'The training is too hard'], correctAnswer: 0, explanation: 'While DOMS has multiple causes, a proper cool-down with light movement and stretching can help reduce post-exercise stiffness.' },
      { type: 'multiple_choice', question: 'Foam rolling before training is considered a form of:', options: ['Static stretching', 'Cardiovascular exercise', 'Self-myofascial release', 'Resistance training'], correctAnswer: 2, explanation: 'Foam rolling is a self-myofascial release technique that can improve tissue quality and range of motion without the force reduction associated with static stretching.' },
      { type: 'multiple_choice', question: 'A proper warm-up typically lasts:', options: ['Exactly 3 minutes', '30+ minutes', '30 seconds', '5–15 minutes depending on the session'], correctAnswer: 3, explanation: 'A thorough warm-up generally takes 5–15 minutes, depending on the intensity and complexity of the training session ahead.' },
    ],
  },

  // ─── Chapter 3: Reps, Sets, and Load ───
  {
    unitNumber: 3, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'For maximum strength development, the recommended rep range is typically:', options: ['15–20 reps', '8–12 reps', '25–30 reps', '1–5 reps'], correctAnswer: 3, explanation: 'Strength is best developed with heavy loads in the 1–5 rep range, allowing high neural drive and maximal force production.' },
      { type: 'multiple_choice', question: 'The hypertrophy (muscle growth) rep range is generally:', options: ['6–12 reps', '1–3 reps', '20–30 reps', '50+ reps'], correctAnswer: 0, explanation: 'The 6–12 rep range provides the mechanical tension, metabolic stress, and time under tension most associated with muscle hypertrophy.' },
      { type: 'multiple_choice', question: 'RPE stands for:', options: ['Rate of Perceived Exertion', 'Reps Per Exercise', 'Rapid Power Expenditure', 'Required Performance Evaluation'], correctAnswer: 0, explanation: 'Rate of Perceived Exertion is a subjective scale (typically 1–10) used to gauge how hard a set feels, helping autoregulate training intensity.' },
      { type: 'scenario', question: 'What adjustment should you make?', scenario: 'You are performing 3 sets of 10 on the bench press. You can complete all sets easily with 3–4 reps left in reserve.', options: ['Add 5 more sets at the same weight', 'Increase the weight slightly to bring you closer to 1–2 reps in reserve', 'Keep the same weight — consistency matters', 'Drop the weight and do more reps'], correctAnswer: 1, explanation: 'If you consistently finish sets with many reps in reserve, the stimulus is insufficient for adaptation. Gradually increasing load ensures progressive overload.' },
      { type: 'multiple_choice', question: 'Progressive overload means:', options: ['Doing the same workout every week', 'Lifting your maximum weight every session', 'Training to failure on every set', 'Gradually increasing the demands placed on the body over time'], correctAnswer: 3, explanation: 'Progressive overload is the gradual increase of stress (weight, reps, sets, or tempo) to continuously challenge the body and drive adaptation.' },
      { type: 'multiple_choice', question: 'Muscular endurance is best developed in the rep range of:', options: ['1–3 reps', '8–10 reps only', '4–6 reps', '15–25+ reps'], correctAnswer: 3, explanation: 'Higher rep ranges (15–25+) with lighter loads train the muscles to sustain repeated contractions over longer durations.' },
      { type: 'multiple_choice', question: 'A "1RM" refers to:', options: ['One repetition maximum — the heaviest weight you can lift for a single rep', 'One recommended movement', 'One round of a circuit', 'One rest minute'], correctAnswer: 0, explanation: 'Your 1RM is the maximum amount of weight you can lift for one complete repetition with proper form. It is used to calculate training percentages.' },
      { type: 'scenario', question: 'What does this most likely indicate?', scenario: 'You have been training with the same weight and reps for 6 weeks and have stopped making progress.', options: ['You should take 3 months off', 'You have reached your genetic limit', 'Training does not work for you', 'You need to apply progressive overload — increase weight, reps, or sets'], correctAnswer: 3, explanation: 'A plateau after weeks of no change usually means the stimulus is no longer novel. Applying progressive overload restarts adaptation.' },
      { type: 'multiple_choice', question: 'Rest periods between sets for strength training (1–5 reps) should typically be:', options: ['60 seconds', '10+ minutes', '2–5 minutes', '30 seconds'], correctAnswer: 2, explanation: 'Strength training requires full ATP-PC recovery between sets. Rest periods of 2–5 minutes allow the nervous system and phosphocreatine stores to recover.' },
      { type: 'multiple_choice', question: 'Training to failure means:', options: ['Choosing a weight you cannot lift at all', 'Performing reps until you cannot complete another with proper form', 'Always training with maximum weight', 'Giving up during a set'], correctAnswer: 1, explanation: 'Training to failure means continuing until you cannot perform another full rep with good form. It is a tool — not required on every set.' },
    ],
  },

  // ─── Chapter 4: Cardiovascular Training Principles ───
  {
    unitNumber: 3, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Steady-state cardiovascular training is characterised by:', options: ['Continuous activity at a consistent moderate intensity', 'Lifting weights in a circuit', 'Stretching for extended periods', 'Short bursts of maximum effort'], correctAnswer: 0, explanation: 'Steady-state cardio involves maintaining a consistent, moderate intensity throughout the session — e.g., jogging at a conversational pace.' },
      { type: 'multiple_choice', question: 'Maximum heart rate (MHR) is commonly estimated using the formula:', options: ['220 − age', 'Age × 2', '200 − age', '220 + age'], correctAnswer: 0, explanation: 'The standard estimation is 220 minus your age. While not perfectly accurate for everyone, it provides a useful starting point for calculating training zones.' },
      { type: 'multiple_choice', question: 'Zone 2 heart rate training (60–70% MHR) primarily develops:', options: ['Anaerobic power', 'Aerobic base and fat oxidation', 'Muscular hypertrophy', 'Maximum sprint speed'], correctAnswer: 1, explanation: "Zone 2 training builds your aerobic base, improves mitochondrial density, and enhances the body\'s ability to use fat as fuel." },
      { type: 'scenario', question: 'What should you adjust?', scenario: 'You can only run fast or walk — you find it impossible to maintain a steady jogging pace for more than 5 minutes.', options: ['Give up running', 'Only walk — jogging is not necessary', 'Only sprint from now on', 'Use a run/walk approach, gradually increasing running intervals as aerobic fitness improves'], correctAnswer: 3, explanation: 'The run/walk method is an effective strategy for building aerobic fitness gradually, progressively increasing the running intervals over time.' },
      { type: 'multiple_choice', question: 'Interval training involves:', options: ['Alternating between periods of higher and lower intensity', 'Static stretching between cardio', 'Only one continuous pace', 'Only resting between exercises'], correctAnswer: 0, explanation: 'Interval training alternates between work and rest (or high and low intensity), improving both aerobic and anaerobic capacity.' },
      { type: 'multiple_choice', question: 'The "talk test" is a simple way to gauge:', options: ['Strength levels', 'Exercise intensity — if you can talk, you are likely in an aerobic zone', 'Hydration status', 'Flexibility'], correctAnswer: 1, explanation: 'If you can hold a conversation during exercise, you are likely working at a moderate, aerobic intensity. Inability to talk suggests higher intensity.' },
      { type: 'multiple_choice', question: 'For general cardiovascular health, adults should aim for a minimum of:', options: ['10 minutes per month', '30 minutes of activity per week', '300 minutes of vigorous activity daily', '75 minutes of vigorous or 150 minutes of moderate activity per week'], correctAnswer: 3, explanation: 'UK and WHO guidelines recommend at least 150 minutes of moderate-intensity or 75 minutes of vigorous-intensity cardiovascular activity per week.' },
      { type: 'scenario', question: 'Which approach is most appropriate?', scenario: 'You want to improve your cardiovascular fitness but dislike running.', options: ['Choose any activity you enjoy that elevates your heart rate — cycling, swimming, rowing, or brisk walking', 'You must run — there is no alternative', 'Skip cardio entirely and only lift weights', 'Use supplements to improve fitness instead'], correctAnswer: 0, explanation: 'The best cardiovascular exercise is one you enjoy and will do consistently. Swimming, cycling, rowing, and brisk walking are all excellent alternatives to running.' },
      { type: 'multiple_choice', question: 'Fartlek training is a form of:', options: ['Unstructured speed play with varying intensities during a continuous run', 'Resistance circuit training', 'Static stretching routine', 'Structured interval training with fixed work/rest ratios'], correctAnswer: 0, explanation: 'Fartlek (Swedish for "speed play") involves varying your pace during a run — mixing faster efforts with recovery — in an unstructured, intuitive way.' },
      { type: 'multiple_choice', question: 'Overtraining in cardiovascular exercise can lead to:', options: ['Fatigue, elevated resting heart rate, poor performance, and increased injury risk', 'Unlimited fitness gains', 'Improved immunity always', 'Faster recovery'], correctAnswer: 0, explanation: 'Overtraining without adequate recovery causes chronic fatigue, elevated resting heart rate, mood disturbances, and increased susceptibility to illness and injury.' },
    ],
  },

  // ─── Chapter 5: Flexibility and Mobility ───
  {
    unitNumber: 3, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Flexibility is defined as:', options: ['The ability to generate force', 'The speed of a movement', 'Cardiovascular efficiency', 'The range of motion available at a joint'], correctAnswer: 3, explanation: 'Flexibility refers to the range of motion available at a joint or group of joints, influenced by muscles, tendons, and joint structures.' },
      { type: 'multiple_choice', question: 'Mobility differs from flexibility because it includes:', options: ['Only passive range of motion', 'Speed of movement only', 'Cardiovascular endurance', 'Active control and strength through the range of motion'], correctAnswer: 3, explanation: 'Mobility combines flexibility with the ability to actively control movement through the full range — it is flexibility plus strength and motor control.' },
      { type: 'multiple_choice', question: 'Static stretching is best performed:', options: ['Never — it has no benefits', 'After training or as a dedicated session', 'Only in the morning', 'Before heavy lifting'], correctAnswer: 1, explanation: 'Static stretching is most beneficial post-training when muscles are warm, or as a separate flexibility session. It can temporarily reduce force production if done before lifting.' },
      { type: 'scenario', question: 'What is the most effective approach?', scenario: 'You cannot touch your toes and your hamstrings feel tight. You want to improve this.', options: ['Only stretch once a month', 'Avoid all hamstring exercises', 'Incorporate regular, gentle hamstring stretching and mobility work over weeks', 'Force yourself into the stretch aggressively'], correctAnswer: 2, explanation: 'Flexibility improves with consistent, gentle practice over time. Aggressive stretching can cause injury — gradual progression is key.' },
      { type: 'multiple_choice', question: 'PNF stretching stands for:', options: ['Passive Neutral Flexibility', 'Progressive Neuromuscular Facilitation', 'Primary Nerve Function', 'Proprioceptive Neuromuscular Facilitation'], correctAnswer: 3, explanation: 'PNF stretching uses a contract-relax technique to increase range of motion, typically involving a partner or fixed object.' },
      { type: 'multiple_choice', question: 'Ankle mobility is important for which exercise?', options: ['Bicep curls', 'Lat pulldowns', 'Bench press', 'Squats'], correctAnswer: 3, explanation: 'Limited ankle dorsiflexion restricts squat depth and can cause compensations like excessive forward lean or heel lifting.' },
      { type: 'multiple_choice', question: 'How long should a static stretch typically be held for?', options: ['5 minutes', '60 seconds minimum', '2–3 seconds', '15–30 seconds'], correctAnswer: 3, explanation: 'Holding a static stretch for 15–30 seconds is effective for improving flexibility. Longer holds can be beneficial but are not necessary for most people.' },
      { type: 'scenario', question: 'What type of training would help most?', scenario: 'You can lift your leg to 90 degrees when a partner pushes it (passive flexibility), but you can only actively raise it to 70 degrees on your own.', options: ['No training needed — this is normal', 'Mobility work that builds strength and control through the range', 'Heavy squats only', 'More passive stretching only'], correctAnswer: 1, explanation: 'The gap between passive and active range indicates a strength deficit. Mobility work builds active control through the available range.' },
      { type: 'multiple_choice', question: 'Foam rolling primarily targets:', options: ['Internal organs', 'Ligaments only', 'Fascia and muscle tissue', 'Bones'], correctAnswer: 2, explanation: 'Foam rolling applies pressure to fascia and muscle tissue to improve tissue quality, reduce tightness, and improve range of motion.' },
      { type: 'multiple_choice', question: 'Hypermobility (excessive flexibility) can be:', options: ['Always beneficial', 'Only found in gymnasts', 'The goal of all flexibility training', 'A risk factor for joint instability and injury'], correctAnswer: 3, explanation: 'While some flexibility is desirable, excessive joint laxity (hypermobility) can increase injury risk. Stability training is especially important for hypermobile individuals.' },
    ],
  },

  // ─── Chapter 6: Exercise Selection and Movement Patterns ───
  {
    unitNumber: 3, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Compound exercises are movements that:', options: ['Are always done with body weight', 'Involve multiple joints and muscle groups', 'Isolate a single muscle', 'Only use machines'], correctAnswer: 1, explanation: 'Compound exercises (squats, deadlifts, bench press, rows) involve multiple joints and recruit several muscle groups simultaneously.' },
      { type: 'multiple_choice', question: 'Which of the following is an isolation exercise?', options: ['Bicep curl', 'Squat', 'Deadlift', 'Bench press'], correctAnswer: 0, explanation: 'A bicep curl isolates the elbow joint and primarily targets the biceps, making it a single-joint isolation exercise.' },
      { type: 'multiple_choice', question: 'The six fundamental movement patterns include:', options: ['Bench, squat, deadlift, row, press, curl', 'Run, jump, throw, swim, climb, crawl', 'Push, pull, squat, hinge, lunge, and carry', 'Only push and pull'], correctAnswer: 2, explanation: 'The six fundamental patterns — push, pull, squat, hinge, lunge, and carry — cover all the basic human movements and form the foundation of programme design.' },
      { type: 'scenario', question: 'Which exercise would best fill this gap?', scenario: 'Your programme includes bench press (push), squats (squat), and lunges (lunge) but no pulling or hinge movements.', options: ['More lunges', 'Barbell rows (pull) and Romanian deadlifts (hinge)', 'Lateral raises only', 'More bench press'], correctAnswer: 1, explanation: 'Adding rows addresses the pulling pattern and Romanian deadlifts address the hinge pattern, creating a balanced programme.' },
      { type: 'multiple_choice', question: 'A hip hinge movement pattern is best represented by:', options: ['Bicep curl', 'Leg extension', 'Romanian deadlift', 'Lateral raise'], correctAnswer: 2, explanation: 'The hip hinge involves bending at the hips while maintaining a neutral spine — the Romanian deadlift is the classic example.' },
      { type: 'multiple_choice', question: 'Why should compound exercises generally be performed first in a session?', options: ['Order does not matter', 'They are easier', 'They are less important', 'They require the most neural drive and energy, which should be done when freshest'], correctAnswer: 3, explanation: 'Compound lifts recruit more muscle mass and demand more from the nervous system, so performing them first when you are freshest maximises performance.' },
      { type: 'multiple_choice', question: 'A vertical push exercise example is:', options: ['Pull-up', 'Overhead press', 'Bench press', 'Barbell row'], correctAnswer: 1, explanation: 'Overhead press is a vertical push — pressing weight overhead. Bench press is a horizontal push.' },
      { type: 'scenario', question: 'What should you prioritise?', scenario: 'You are a beginner with 3 days per week to train. You want to build overall strength.', options: ['Full-body sessions built around compound movements', 'Only cardio', 'Advanced techniques like drop sets and supersets', 'Isolation exercises targeting small muscles'], correctAnswer: 0, explanation: 'Beginners benefit most from full-body sessions centred on compound movements, which provide the most stimulus per session and build a strong foundation.' },
      { type: 'multiple_choice', question: "A carry exercise (e.g., farmer\'s walk) primarily develops:", options: ['Flexibility', 'Chest size', 'Grip strength, core stability, and total-body conditioning', 'Only forearm endurance'], correctAnswer: 2, explanation: 'Loaded carries challenge grip, core stability, posture, and total-body strength — making them one of the most functional exercises available.' },
      { type: 'multiple_choice', question: 'Unilateral exercises (single-limb) are valuable because they:', options: ['Identify and correct strength imbalances between sides', 'Should replace all bilateral work', 'Are only for rehabilitation', 'Are always easier than bilateral exercises'], correctAnswer: 0, explanation: 'Unilateral exercises (single-leg squats, one-arm rows) expose and correct side-to-side imbalances that bilateral movements can mask.' },
    ],
  },

  // ─── Chapter 7: Recovery and Adaptation ───
  {
    unitNumber: 3, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Supercompensation is the process where:', options: ['You become weaker after training', 'You should train before recovery is complete', 'Training has no effect on performance', 'The body recovers from training and adapts to a level above the previous baseline'], correctAnswer: 3, explanation: 'After training causes fatigue, the body repairs and adapts — temporarily reaching a level of fitness above the starting point (supercompensation).' },
      { type: 'multiple_choice', question: 'DOMS stands for:', options: ['Delayed Onset Muscle Soreness', 'Dynamic Overtraining Muscle State', 'Direct Output Muscle Stimulus', 'Daily Overload Movement Syndrome'], correctAnswer: 0, explanation: 'Delayed Onset Muscle Soreness is the stiffness and discomfort felt 24–72 hours after training, caused by micro-damage to muscle fibres during exercise.' },
      { type: 'multiple_choice', question: 'Sleep is important for recovery because:', options: ['Only mental recovery happens during sleep', 'It has no impact on recovery', 'You should sleep less to train more', 'Growth hormone release, tissue repair, and neural recovery occur primarily during sleep'], correctAnswer: 3, explanation: "Sleep is the body\'s primary recovery period — growth hormone peaks during deep sleep, supporting muscle repair, immune function, and cognitive recovery." },
      { type: 'scenario', question: 'What is the most likely issue?', scenario: 'You train 6 days per week at high intensity and notice declining performance, persistent fatigue, and irritability.', options: ['This is normal and will pass', 'Your diet is perfect', 'You are likely overtraining — insufficient recovery between sessions', 'You need to train harder'], correctAnswer: 2, explanation: 'Declining performance, persistent fatigue, and mood changes are classic signs of overtraining or under-recovery. Reducing volume or adding rest days is essential.' },
      { type: 'multiple_choice', question: 'A deload week involves:', options: ['Reducing training volume and/or intensity for a planned recovery period', 'Only stretching', 'Stopping all exercise', 'Doubling your training volume'], correctAnswer: 0, explanation: 'A deload typically reduces volume (sets/reps) and/or intensity (weight) by 40–60% for one week, allowing accumulated fatigue to dissipate.' },
      { type: 'multiple_choice', question: 'Active recovery involves:', options: ['Complete bed rest', 'Only foam rolling', 'Training at maximum intensity', 'Light, low-intensity movement like walking, swimming, or gentle cycling'], correctAnswer: 3, explanation: 'Active recovery uses light movement to promote blood flow and reduce stiffness without adding significant training stress.' },
      { type: 'multiple_choice', question: 'How many hours of sleep per night is generally recommended for active adults?', options: ['7–9 hours', '10–12 hours', '4–5 hours', '6 hours maximum'], correctAnswer: 0, explanation: 'Most adults need 7–9 hours of quality sleep per night for optimal recovery, hormonal balance, and cognitive function.' },
      { type: 'scenario', question: 'Should you train today?', scenario: 'You slept poorly (4 hours), feel exhausted, and have a heavy squat session planned.', options: ['Double your volume to make up for feeling tired', 'Take pre-workout and train as normal', 'Push through — never miss a session', 'Replace with a lighter session or active recovery — quality matters more than checking a box'], correctAnswer: 3, explanation: 'Training heavy on inadequate sleep increases injury risk and impairs performance. Adjusting the session or resting is the smarter long-term choice.' },
      { type: 'multiple_choice', question: 'Stress (psychological) affects recovery by:', options: ['Only affecting flexibility', 'Always improving performance', 'Elevating cortisol, which can impair muscle repair and sleep quality', 'Having no effect whatsoever'], correctAnswer: 2, explanation: 'Chronic psychological stress raises cortisol levels, which can impair protein synthesis, sleep quality, immune function, and overall recovery from training.' },
      { type: 'multiple_choice', question: 'The minimum recommended rest between training the same muscle group is:', options: ['2–4 hours', '30 minutes', '7 days', '24–48 hours'], correctAnswer: 3, explanation: 'Most muscle groups need 24–48 hours of recovery before being trained again to allow repair and adaptation.' },
    ],
  },

  // ─── Chapter 8: Training Considerations for Different Populations ───
  {
    unitNumber: 3, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Older adults (65+) should include which type of training?', options: ['No exercise — rest is best', 'Resistance training to maintain muscle mass and bone density', 'Only high-impact plyometrics', 'Only flexibility training'], correctAnswer: 1, explanation: 'Resistance training is crucial for older adults to combat age-related muscle loss (sarcopenia), maintain bone density, and support independence.' },
      { type: 'multiple_choice', question: 'During pregnancy, exercise is generally:', options: ['Completely forbidden', 'Safe and beneficial when appropriately modified, with medical clearance', 'Harmful to the baby', 'Only safe in the first trimester'], correctAnswer: 1, explanation: 'Exercise during pregnancy is encouraged by health guidelines, provided it is appropriately modified and cleared by a healthcare professional.' },
      { type: 'scenario', question: 'What is the most appropriate approach?', scenario: 'A 16-year-old wants to start resistance training. Their parent is concerned it will damage their growth plates.', options: ['Weightlifting always damages growth plates in young people', 'Properly supervised resistance training is safe and beneficial for adolescents', 'They should only use machines, never free weights', 'They should not lift weights until age 18'], correctAnswer: 1, explanation: 'Research consistently shows that properly supervised resistance training is safe for adolescents and does not damage growth plates when appropriate technique and loads are used.' },
      { type: 'multiple_choice', question: 'For individuals with Type 2 diabetes, exercise helps by:', options: ['Having no effect on blood sugar', 'Improving insulin sensitivity and blood glucose management', 'Replacing medication entirely', 'Increasing blood sugar levels'], correctAnswer: 1, explanation: 'Exercise improves insulin sensitivity, helps regulate blood glucose, and is a key component of Type 2 diabetes management alongside medical treatment.' },
      { type: 'multiple_choice', question: 'Someone with high blood pressure should avoid:', options: ['Walking', 'Light resistance training', 'Heavy isometric holds and Valsalva manoeuvre (breath holding under strain)', 'All exercise'], correctAnswer: 2, explanation: 'Heavy isometric contractions and breath-holding (Valsalva) can cause dangerous spikes in blood pressure. Moderate exercise with controlled breathing is safe and beneficial.' },
      { type: 'multiple_choice', question: 'Post-natal exercise should prioritise:', options: ['Only running', 'Maximum-intensity training from day one', 'Core and pelvic floor rehabilitation before progressing intensity', 'Returning to pre-pregnancy exercise immediately'], correctAnswer: 2, explanation: 'Post-natal recovery should focus on rebuilding core stability and pelvic floor strength before gradually returning to higher-intensity exercise.' },
      { type: 'scenario', question: 'What is the safest initial approach?', scenario: 'You have been sedentary for 5 years and want to start exercising. You are overweight and have mild joint pain.', options: ['Only stretch — exercise will make joints worse', 'Start with high-intensity interval training', 'Join an advanced CrossFit class immediately', 'Begin with low-impact activities like walking, swimming, or cycling, and progress gradually'], correctAnswer: 3, explanation: 'Starting with low-impact activities minimises joint stress while building a fitness base. Gradual progression is key for safety and long-term adherence.' },
      { type: 'multiple_choice', question: 'Individuals with asthma can safely exercise provided they:', options: ['Avoid all exercise', 'Have their inhaler available, warm up properly, and monitor symptoms', 'Push through any breathing difficulties', 'Only swim — no other exercise is safe'], correctAnswer: 1, explanation: 'People with asthma can and should exercise. Having a reliever inhaler available, warming up thoroughly, and avoiding known triggers supports safe participation.' },
      { type: 'multiple_choice', question: 'Resistance training for older adults should focus on:', options: ['Only seated exercises', 'Avoiding any challenging movements', 'Maximum weight, low reps only', 'Functional movements with moderate loads, emphasising balance and stability'], correctAnswer: 3, explanation: 'Functional, moderate-load resistance training that includes balance and stability work supports daily living activities and reduces fall risk in older adults.' },
      { type: 'multiple_choice', question: 'Before starting an exercise programme, individuals with medical conditions should:', options: ['Only follow generic online programmes', 'Begin immediately without guidance', 'Obtain medical clearance and consider working with a qualified professional', 'Avoid exercise entirely'], correctAnswer: 2, explanation: 'Medical clearance ensures exercise is safe and appropriate. A qualified professional can adapt programmes to individual needs and conditions.' },
    ],
  },
];
