import type { UnitAssessment } from '../types';

export const level2Unit2Assessment: UnitAssessment = {
  unitNumber: 2,
  title: 'Principles of Nutrition — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    {
      type: 'multiple_choice',
      question: 'How many calories does one gram of protein provide?',
      options: ['2 calories', '4 calories', '9 calories', '7 calories'],
      correctAnswer: 1,
      explanation: 'Protein provides 4 calories per gram, the same as carbohydrates. Fats provide 9 calories per gram.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the stored form of carbohydrate in the muscles and liver called?',
      options: ['Glucose', 'Fructose', 'Sucrose', 'Glycogen'],
      correctAnswer: 3,
      explanation: 'Glycogen is the stored form of carbohydrate. It is stored in the muscles and liver and is broken down into glucose during exercise to fuel activity.',
    },
    {
      type: 'multiple_choice',
      question: 'How many essential amino acids must be obtained from the diet?',
      options: ['12', '9', '6', '20'],
      correctAnswer: 1,
      explanation: 'There are 9 essential amino acids that the body cannot produce and must be obtained from dietary protein. There are 20 amino acids in total.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is a fat-soluble vitamin?',
      options: ['Vitamin B6', 'Vitamin B12', 'Vitamin C', 'Vitamin D'],
      correctAnswer: 3,
      explanation: "Vitamins A, D, E, and K are fat-soluble — they are stored in the body\'s fat tissues and require dietary fat for absorption. Vitamins B and C are water-soluble.",
    },
    {
      type: 'multiple_choice',
      question: 'Which population group is at highest risk of Vitamin D deficiency in the UK?',
      options: [
        'Only vegetarians',
        'The general population, especially during autumn and winter',
        'Only elderly adults over 70',
        'Only professional athletes',
      ],
      correctAnswer: 1,
      explanation: 'Vitamin D deficiency is extremely common in the UK due to limited sunlight, especially during autumn and winter months. The NHS recommends everyone in the UK consider a Vitamin D supplement during these months.',
    },
    {
      type: 'multiple_choice',
      question: 'Which mineral is involved in over 300 enzymatic reactions and supports sleep quality and muscle relaxation?',
      options: ['Sodium', 'Iron', 'Calcium', 'Magnesium'],
      correctAnswer: 3,
      explanation: 'Magnesium is involved in over 300 enzymatic reactions including energy production, muscle relaxation, and nervous system regulation. Good sources include nuts, seeds, dark chocolate, and leafy greens.',
    },
    {
      type: 'multiple_choice',
      question: 'At what level of dehydration does exercise performance typically decrease significantly?',
      options: ['10% body weight loss', '3-5% body weight loss', '0.5% body weight loss', '1-2% body weight loss'],
      correctAnswer: 1,
      explanation: 'At 3-5% body weight loss through dehydration, exercise performance can decrease by up to 25%. Even mild dehydration (1-2%) can impair concentration and increase perceived effort.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the recommended fluid replacement after exercise?',
      options: [
        'Replace 50% of fluid lost',
        'Replace 100% of fluid lost',
        'Drink as much as possible',
        'Replace 150% of fluid lost',
      ],
      correctAnswer: 3,
      explanation: 'Post-exercise rehydration guidelines recommend replacing 150% of fluid lost to account for ongoing losses through urine and continued sweating. Weigh yourself before and after to estimate loss.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the general daily water intake recommendation per kilogram of bodyweight?',
      options: ['15ml per kg', '35ml per kg', '25ml per kg', '50ml per kg'],
      correctAnswer: 1,
      explanation: 'A baseline recommendation is approximately 35ml per kg of bodyweight per day (e.g., an 80kg person should aim for about 2.8 litres). This should be increased with exercise and heat.',
    },
    {
      type: 'multiple_choice',
      question: 'Which component of TDEE accounts for the largest proportion of daily energy expenditure?',
      options: ['Non-Exercise Activity Thermogenesis (NEAT)', 'Thermic Effect of Food (TEF)', 'Exercise Activity Thermogenesis (EAT)', 'Basal Metabolic Rate (BMR)'],
      correctAnswer: 3,
      explanation: 'BMR accounts for 60-70% of TDEE for most people. It represents the energy required to maintain basic physiological functions at rest.',
    },
    {
      type: 'multiple_choice',
      question: 'By how much do studies suggest people typically underreport their calorie intake?',
      options: ['30-50%', '5-10%', '60-80%', '10-20%'],
      correctAnswer: 0,
      explanation: 'Research consistently shows that people underreport their calorie consumption by 30-50%. This is the single most common reason individuals believe they "can\'t lose weight" despite being in a supposed deficit.',
    },
    {
      type: 'scenario',
      question: 'What is the most appropriate action?',
      scenario: 'You have been in a caloric deficit of 800 calories per day for 8 weeks. You initially lost weight rapidly but have now plateaued. You feel constantly tired, irritable, and are losing motivation to train.',
      options: [
        'Reduce calories further to restart weight loss',
        'Switch to a liquid-only diet for faster results',
        'Increase calories to a moderate deficit (300-500 below maintenance) and prioritise recovery',
        'Add an extra gym session per day to burn more calories',
      ],
      correctAnswer: 2,
      explanation: 'An aggressive 800-calorie deficit over 8 weeks has likely caused metabolic adaptation, hormonal disruption, and psychological fatigue. The appropriate response is to increase calories to a more sustainable moderate deficit, prioritise sleep and recovery, and accept a slower rate of fat loss for better long-term outcomes.',
    },
    {
      type: 'multiple_choice',
      question: 'Under UK food labelling law, what does a "low fat" claim mean?',
      options: [
        'The product contains ≤3g fat per 100g',
        'The product contains ≤10g fat per 100g',
        'The product has 50% less fat than the original',
        'The product contains no fat at all',
      ],
      correctAnswer: 0,
      explanation: 'In the UK, "low fat" legally means the product contains no more than 3g of fat per 100g. However, low-fat products often compensate with added sugar to maintain flavour.',
    },
    {
      type: 'multiple_choice',
      question: 'What is considered "high sugar" on a UK food label per 100g?',
      options: ['More than 30g', 'More than 10g', 'More than 22.5g', 'More than 5g'],
      correctAnswer: 2,
      explanation: 'Under UK food labelling guidelines, a product is considered high in sugar if it contains more than 22.5g of sugars per 100g. Low sugar is less than 5g per 100g.',
    },
    {
      type: 'scenario',
      question: 'What should you be aware of?',
      scenario: 'You are trying to lose weight and switch to a "low fat" yoghurt because it claims to be healthy. The original yoghurt has 5g fat and 8g sugar per 100g. The "low fat" version has 1.5g fat and 18g sugar per 100g.',
      options: [
        'The low-fat version has significantly more sugar, likely added to compensate for reduced fat and flavour',
        'Both yoghurts are equally unhealthy',
        'The low-fat version is clearly healthier because it has less fat',
        'Fat content does not matter at all',
      ],
      correctAnswer: 0,
      explanation: 'This is a classic example of how "low fat" marketing can be misleading. The reduced fat has been compensated with more than double the sugar. The additional sugar contributes to calorie intake without improving satiety, potentially making the "healthier" option worse for your fat loss goal.',
    },
    {
      type: 'multiple_choice',
      question: 'According to current evidence, how wide is the post-workout "anabolic window"?',
      options: ['It does not exist at all', 'Exactly 30 minutes', 'Several hours (unless training fasted)', '30-60 minutes only'],
      correctAnswer: 2,
      explanation: 'Current research suggests the post-workout anabolic window is much wider than previously claimed — several hours rather than 30 minutes. The exception is fasted training, where consuming protein sooner is beneficial.',
    },
    {
      type: 'multiple_choice',
      question: 'For optimising muscle protein synthesis, how should protein ideally be distributed throughout the day?',
      options: [
        'Distributed across 3-5 meals with 20-40g per serving',
        'All in one meal',
        'Two large doses morning and evening',
        'Only consumed post-workout',
      ],
      correctAnswer: 0,
      explanation: 'Research suggests that distributing protein intake across 3-5 meals, with 20-40g per serving, optimises muscle protein synthesis throughout the day. Consuming all protein in one meal is less effective for muscle building.',
    },
    {
      type: 'scenario',
      question: 'Which aspect of nutrition would have the biggest impact on results?',
      scenario: 'You are obsessed with nutrient timing. You eat within exactly 30 minutes of training, time your carbohydrates precisely, and set alarms for meal times. However, your total daily protein intake is only 60g (you weigh 80kg), and you rarely eat vegetables.',
      options: [
        'Your vegetable intake does not matter at Level 2',
        'You need to time your carbohydrates even more precisely',
        'You should focus on increasing total protein intake and food quality before worrying about timing',
        'Your meal timing is already optimal — you just need to train harder',
      ],
      correctAnswer: 2,
      explanation: 'You have prioritised timing (an advanced optimisation) while neglecting the fundamentals — inadequate protein (should be 128-176g at 80kg) and poor food quality. Fixing total protein intake and adding vegetables would have a far greater impact than perfecting meal timing.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the recommended daily fibre intake for adults?',
      options: ['30g', '20g', '10g', '50g'],
      correctAnswer: 0,
      explanation: 'The NHS recommends adults consume 30g of fibre per day. Most people in the UK fall short of this target. Good sources include vegetables, fruits, whole grains, legumes, nuts, and seeds.',
    },
    {
      type: 'multiple_choice',
      question: 'Why is meal preparation considered an effective adherence strategy?',
      options: [
        'It eliminates the need for food tracking entirely',
        'It guarantees perfect macronutrient ratios',
        'It reduces decision fatigue and reliance on convenience food',
        'It is the only way to eat healthy',
      ],
      correctAnswer: 2,
      explanation: 'Meal preparation reduces decision fatigue — when healthy meals are already prepared, you are far less likely to reach for convenience or processed food. It is one of the most effective practical strategies for consistent nutrition.',
    }
  ],
};
