import type { ChapterQuiz } from '../types';

export const unit1ChapterQuizzes: ChapterQuiz[] = [
  // ─── Chapter 1: Basic Anatomy for Training ───
  {
    unitNumber: 1,
    chapterNumber: 1,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which anatomical plane divides the body into left and right halves?',
        options: ['Transverse plane', 'Sagittal plane', 'Coronal plane', 'Frontal plane'],
        correctAnswer: 1,
        explanation: 'The sagittal plane runs vertically from front to back, dividing the body into left and right sections.',
      },
      {
        type: 'multiple_choice',
        question: 'A bicep curl primarily occurs in which plane of movement?',
        options: ['Frontal plane', 'Diagonal plane', 'Sagittal plane', 'Transverse plane'],
        correctAnswer: 2,
        explanation: 'A bicep curl involves flexion at the elbow, which occurs in the sagittal plane.',
      },
      {
        type: 'multiple_choice',
        question: 'What does the term "posterior" mean in anatomical terminology?',
        options: ['Towards the back of the body', 'Towards the front of the body', 'Towards the midline', 'Away from the midline'],
        correctAnswer: 0,
        explanation: 'Posterior refers to the back of the body. For example, your hamstrings are on the posterior side of your thigh.',
      },
      {
        type: 'multiple_choice',
        question: 'Lateral raises primarily involve movement in which plane?',
        options: ['Transverse plane', 'Horizontal plane', 'Frontal plane', 'Sagittal plane'],
        correctAnswer: 2,
        explanation: 'Lateral raises involve abduction of the shoulder, which occurs in the frontal (coronal) plane.',
      },
      {
        type: 'scenario',
        question: 'Which directional term best describes the position of the shoulders relative to the hips?',
        scenario: 'You are labelling a body diagram for a training log and need to describe the position of different body parts.',
        options: ['Superior', 'Lateral', 'Medial', 'Inferior'],
        correctAnswer: 0,
        explanation: 'Superior means above or higher. The shoulders are superior to the hips.',
      },
      {
        type: 'multiple_choice',
        question: 'Which plane of movement would a Russian twist primarily occur in?',
        options: ['Sagittal plane', 'Transverse plane', 'Vertical plane', 'Frontal plane'],
        correctAnswer: 1,
        explanation: 'The transverse plane divides the body into upper and lower halves. Rotational movements like a Russian twist occur in this plane.',
      },
      {
        type: 'multiple_choice',
        question: 'What does "medial" mean in anatomical terminology?',
        options: ['Towards the midline of the body', 'Towards the feet', 'Towards the outside of the body', 'Towards the head'],
        correctAnswer: 0,
        explanation: 'Medial means closer to the midline of the body. For example, the inner thigh is medial to the outer thigh.',
      },
      {
        type: 'scenario',
        question: 'Which movement plane should you focus on to address this imbalance?',
        scenario: 'You notice your training programme only includes squats, lunges, and bicep curls — all forward-and-back movements.',
        options: ['More sagittal plane work', 'More frontal plane work', 'More sagittal and transverse work', 'No change needed'],
        correctAnswer: 1,
        explanation: 'All the listed exercises occur in the sagittal plane. Adding frontal plane movements (like lateral lunges or lateral raises) would create better balance.',
      },
      {
        type: 'multiple_choice',
        question: 'Which of the following is an example of a transverse plane exercise?',
        options: ['Deadlift', 'Squat', 'Cable woodchop', 'Lateral raise'],
        correctAnswer: 2,
        explanation: 'A cable woodchop involves rotation through the torso, making it a transverse plane movement.',
      },
      {
        type: 'multiple_choice',
        question: 'The term "anterior" refers to which side of the body?',
        options: ['The top', 'The left side', 'The back', 'The front'],
        correctAnswer: 3,
        explanation: 'Anterior means the front of the body. Your quadriceps are on the anterior side of your thigh.',
      },
    ],
  },

  // ─── Chapter 2: Joints and Movement ───
  {
    unitNumber: 1,
    chapterNumber: 2,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which type of joint allows the greatest range of movement?',
        options: ['Ball-and-socket joint', 'Pivot joint', 'Hinge joint', 'Gliding joint'],
        correctAnswer: 0,
        explanation: 'Ball-and-socket joints (like the shoulder and hip) allow movement in all planes and the greatest range of motion.',
      },
      {
        type: 'multiple_choice',
        question: 'The knee is classified as which type of synovial joint?',
        options: ['Pivot', 'Ball-and-socket', 'Hinge', 'Saddle'],
        correctAnswer: 2,
        explanation: 'The knee is a hinge joint, primarily allowing flexion and extension.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the primary role of synovial fluid in a joint?',
        options: ['To store energy for movement', 'To connect muscle to bone', 'To strengthen the joint capsule', 'To reduce friction and nourish cartilage'],
        correctAnswer: 3,
        explanation: 'Synovial fluid lubricates the joint, reducing friction between cartilage surfaces and providing nutrients.',
      },
      {
        type: 'multiple_choice',
        question: 'Which movement describes bringing a limb closer to the midline of the body?',
        options: ['Adduction', 'Extension', 'Abduction', 'Circumduction'],
        correctAnswer: 0,
        explanation: 'Adduction is the movement of a limb towards the midline. For example, bringing your arm back to your side after a lateral raise.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely cause of this discomfort?',
        scenario: 'You feel a clicking sensation in your shoulder during overhead pressing. There is no pain, but it happens every rep.',
        options: ['Synovial fluid movement or tendon gliding over bone', 'Excessive synovial fluid production', 'Fractured joint capsule', 'Torn muscle fibres'],
        correctAnswer: 0,
        explanation: 'Painless clicking during shoulder movements is commonly caused by synovial fluid shifting or tendons gliding over bony surfaces. It is usually harmless.',
      },
      {
        type: 'multiple_choice',
        question: 'What type of joint is found in the spine between vertebrae?',
        options: ['Ball-and-socket', 'Condyloid', 'Hinge', 'Gliding (plane)'],
        correctAnswer: 3,
        explanation: 'The facet joints between vertebrae are gliding (plane) joints, allowing small sliding movements that together create spinal flexibility.',
      },
      {
        type: 'multiple_choice',
        question: 'Which joint action occurs when you straighten your arm from a bent position?',
        options: ['Abduction', 'Extension', 'Rotation', 'Flexion'],
        correctAnswer: 1,
        explanation: 'Extension is the increase of the angle at a joint — straightening the arm is extension at the elbow.',
      },
      {
        type: 'scenario',
        question: 'Which approach best addresses this issue?',
        scenario: 'You struggle to reach full depth in a squat because your ankles feel tight and your heels lift off the ground.',
        options: ['Stop squatting — it is not safe', 'Switch to only machine-based leg work', 'Add more weight to force depth', 'Improve ankle dorsiflexion through mobility work'],
        correctAnswer: 3,
        explanation: 'Limited ankle dorsiflexion is a common barrier to squat depth. Targeted mobility work (calf stretches, ankle circles, elevated heel drills) improves this over time.',
      },
      {
        type: 'multiple_choice',
        question: 'What does "range of motion" (ROM) refer to?',
        options: ['The number of joints involved in a movement', 'The full extent of movement available at a joint', 'The speed at which a joint moves', 'The strength of the muscles around a joint'],
        correctAnswer: 1,
        explanation: 'Range of motion is the full extent of movement that a joint can achieve, from full flexion to full extension (or other relevant movements).',
      },
      {
        type: 'multiple_choice',
        question: 'Rotation at the hip joint is possible because it is a:',
        options: ['Pivot joint', 'Hinge joint', 'Ball-and-socket joint', 'Gliding joint'],
        correctAnswer: 2,
        explanation: 'The hip is a ball-and-socket joint, allowing flexion, extension, abduction, adduction, and rotation.',
      },
    ],
  },

  // ─── Chapter 3: Major Muscle Groups ───
  {
    unitNumber: 1,
    chapterNumber: 3,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which muscle group is primarily responsible for extending the knee?',
        options: ['Quadriceps', 'Hamstrings', 'Calves', 'Glutes'],
        correctAnswer: 0,
        explanation: 'The quadriceps (front of the thigh) are the primary knee extensors, working during squats, leg extensions, and walking upstairs.',
      },
      {
        type: 'multiple_choice',
        question: 'The latissimus dorsi is located in which area of the body?',
        options: ['Front of the shoulder', 'Front of the thigh', 'Upper back and sides', 'Lower leg'],
        correctAnswer: 2,
        explanation: 'The latissimus dorsi (lats) are large muscles spanning the mid and lower back, responsible for pulling movements.',
      },
      {
        type: 'multiple_choice',
        question: 'Which muscle is the primary hip extensor?',
        options: ['Tibialis anterior', 'Gluteus maximus', 'Deltoid', 'Rectus femoris'],
        correctAnswer: 1,
        explanation: 'The gluteus maximus is the largest muscle in the body and the primary driver of hip extension — essential for squats, deadlifts, and sprinting.',
      },
      {
        type: 'scenario',
        question: 'Which muscle group should you prioritise strengthening?',
        scenario: 'You experience lower back discomfort after long periods of sitting. A physiotherapist suggests your glutes may be underactive.',
        options: ['Hamstrings', 'Quadriceps', 'Calves', 'Gluteus maximus and medius'],
        correctAnswer: 3,
        explanation: 'Weak or underactive glutes often contribute to lower back pain because the lower back compensates for poor hip extension. Strengthening the glutes reduces this compensation.',
      },
      {
        type: 'multiple_choice',
        question: 'Which muscle group acts as the antagonist to the quadriceps?',
        options: ['Glutes', 'Calves', 'Hip flexors', 'Hamstrings'],
        correctAnswer: 3,
        explanation: 'The hamstrings oppose the quadriceps — when the quads extend the knee, the hamstrings act as the antagonist. This agonist-antagonist relationship is key to balanced training.',
      },
      {
        type: 'multiple_choice',
        question: 'The deltoid muscle is responsible for which primary movement?',
        options: ['Elbow flexion', 'Spinal rotation', 'Shoulder abduction and flexion', 'Knee extension'],
        correctAnswer: 2,
        explanation: 'The deltoids are the cap-shaped muscles on your shoulders, responsible for raising your arms in various directions.',
      },
      {
        type: 'multiple_choice',
        question: 'Which muscle group is located on the posterior side of the upper arm?',
        options: ['Brachialis', 'Forearm flexors', 'Biceps brachii', 'Triceps brachii'],
        correctAnswer: 3,
        explanation: 'The triceps are on the back of the upper arm and are responsible for elbow extension (straightening the arm).',
      },
      {
        type: 'scenario',
        question: 'What adjustment would create better muscular balance?',
        scenario: 'Your weekly programme includes bench press, push-ups, and shoulder press, but no pulling movements.',
        options: ['Add more chest exercises', 'Remove shoulder press', 'Add rows and pull-ups to balance push and pull', 'Add only bicep curls'],
        correctAnswer: 2,
        explanation: 'A balanced programme should include roughly equal pushing and pulling volume to prevent muscular imbalances and postural issues.',
      },
      {
        type: 'multiple_choice',
        question: 'The core muscles include which of the following?',
        options: ['Only the rectus abdominis (six-pack)', 'Only the obliques', 'Transverse abdominis, obliques, rectus abdominis, and erector spinae', 'Only the lower back muscles'],
        correctAnswer: 2,
        explanation: 'The core is a group of muscles including the deep transverse abdominis, the obliques, the rectus abdominis, and the erector spinae — working together for stability.',
      },
      {
        type: 'multiple_choice',
        question: 'Which exercise primarily targets the hamstrings?',
        options: ['Leg press', 'Romanian deadlift', 'Calf raise', 'Leg extension'],
        correctAnswer: 1,
        explanation: 'The Romanian deadlift places significant stretch and load on the hamstrings through hip hinge mechanics.',
      },
    ],
  },

  // ─── Chapter 4: The Cardiovascular System ───
  {
    unitNumber: 1,
    chapterNumber: 4,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'What is the primary function of the cardiovascular system?',
        options: ['To digest food', 'To produce hormones', 'To transport oxygen, nutrients, and waste products around the body', 'To protect against infection'],
        correctAnswer: 2,
        explanation: 'The cardiovascular system circulates blood, delivering oxygen and nutrients to working tissues and removing waste products like carbon dioxide.',
      },
      {
        type: 'multiple_choice',
        question: 'What happens to your heart rate during steady-state cardiovascular exercise?',
        options: ['It stays the same as at rest', 'It fluctuates randomly', 'It decreases', 'It increases and reaches a plateau'],
        correctAnswer: 3,
        explanation: 'During steady-state exercise, your heart rate increases to meet oxygen demand and then plateaus at a sustainable level.',
      },
      {
        type: 'multiple_choice',
        question: 'Which chamber of the heart pumps oxygenated blood to the body?',
        options: ['Left atrium', 'Right atrium', 'Right ventricle', 'Left ventricle'],
        correctAnswer: 3,
        explanation: 'The left ventricle is the strongest chamber and pumps oxygenated blood out through the aorta to the entire body.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely explanation?',
        scenario: 'After 8 weeks of consistent running, you notice your resting heart rate has dropped from 72 bpm to 64 bpm.',
        options: ['You are overtraining', 'Your heart has become more efficient (cardiac adaptation)', 'You are dehydrated', 'Your blood pressure has increased'],
        correctAnswer: 1,
        explanation: "A lower resting heart rate is a sign of improved cardiovascular fitness — your heart pumps more blood per beat (increased stroke volume), so it doesn\'t need to beat as often.",
      },
      {
        type: 'multiple_choice',
        question: 'What is stroke volume?',
        options: ['The amount of blood pumped per heartbeat', 'The speed at which blood flows through arteries', 'The oxygen content of blood', 'The number of heartbeats per minute'],
        correctAnswer: 0,
        explanation: 'Stroke volume is the amount of blood ejected from the left ventricle with each heartbeat. Training increases stroke volume, improving cardiac efficiency.',
      },
      {
        type: 'multiple_choice',
        question: 'Which type of blood vessel carries blood away from the heart?',
        options: ['Arteries', 'Capillaries', 'Venules', 'Veins'],
        correctAnswer: 0,
        explanation: 'Arteries carry blood away from the heart. They have thick, elastic walls to handle the high pressure of blood being pumped.',
      },
      {
        type: 'multiple_choice',
        question: 'During exercise, blood is redistributed primarily to which area?',
        options: ['The working skeletal muscles', 'The skin only', 'The brain only', 'The digestive system'],
        correctAnswer: 0,
        explanation: 'During exercise, blood is shunted away from non-essential organs (like the gut) and directed to working muscles that need more oxygen and fuel.',
      },
      {
        type: 'scenario',
        question: 'What is the best explanation for this?',
        scenario: 'You feel lightheaded when you suddenly stop running at high intensity without a cool-down.',
        options: ['Overtraining syndrome', 'Low blood sugar', 'Dehydration only', 'Blood pooling in the legs due to sudden stop'],
        correctAnswer: 3,
        explanation: 'When you stop suddenly, the muscle pump in your legs stops helping return blood to the heart, causing blood to pool in the lower body and reducing blood flow to the brain.',
      },
      {
        type: 'multiple_choice',
        question: 'Cardiac output is calculated by:',
        options: ['Blood pressure × stroke volume', 'Heart rate × blood pressure', 'Stroke volume ÷ heart rate', 'Heart rate × stroke volume'],
        correctAnswer: 3,
        explanation: 'Cardiac output = heart rate × stroke volume. It represents the total volume of blood the heart pumps per minute.',
      },
      {
        type: 'multiple_choice',
        question: 'Regular cardiovascular training leads to which long-term adaptation?',
        options: ['Increased stroke volume and lower resting heart rate', 'Decreased lung capacity', 'Reduced capillary density', 'Increased resting heart rate'],
        correctAnswer: 0,
        explanation: 'Consistent cardio training increases stroke volume and capillary density while decreasing resting heart rate — all signs of improved cardiovascular efficiency.',
      },
    ],
  },

  // ─── Chapter 5: Energy Systems ───
  {
    unitNumber: 1,
    chapterNumber: 5,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which energy system provides fuel for short, explosive efforts lasting up to 10 seconds?',
        options: ['Aerobic system', 'Oxidative system', 'Lactic acid system', 'ATP-PC (phosphocreatine) system'],
        correctAnswer: 3,
        explanation: 'The ATP-PC system provides immediate energy for very short, high-intensity efforts like a 1-rep max or a 40-metre sprint.',
      },
      {
        type: 'multiple_choice',
        question: 'ATP stands for:',
        options: ['Adenosine triphosphate', 'Amino transfer process', 'Active tissue protein', 'Aerobic training pathway'],
        correctAnswer: 0,
        explanation: "Adenosine triphosphate (ATP) is the body\'s energy currency — all movement requires ATP, regardless of which system produces it.",
      },
      {
        type: 'multiple_choice',
        question: 'The lactic acid system primarily fuels efforts lasting approximately:',
        options: ['5–30 minutes', '10 seconds to 2 minutes', '1–5 seconds', 'Over 60 minutes'],
        correctAnswer: 1,
        explanation: 'The lactic acid (anaerobic glycolysis) system kicks in for high-intensity efforts lasting roughly 10 seconds to 2 minutes, such as a 400-metre sprint.',
      },
      {
        type: 'scenario',
        question: 'Which energy system is primarily being used?',
        scenario: 'You are performing a heavy set of 3 reps on the bench press, taking about 8 seconds to complete.',
        options: ['ATP-PC system', 'All three equally', 'Lactic acid system', 'Aerobic system'],
        correctAnswer: 0,
        explanation: 'A heavy set lasting under 10 seconds relies primarily on the ATP-PC system, which provides immediate energy without needing oxygen.',
      },
      {
        type: 'multiple_choice',
        question: 'Which energy system uses oxygen to produce ATP?',
        options: ['All systems use oxygen', 'ATP-PC system', 'Lactic acid system', 'Aerobic (oxidative) system'],
        correctAnswer: 3,
        explanation: 'The aerobic system requires oxygen to break down carbohydrates and fats for energy. It fuels sustained, lower-intensity activities.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the by-product of the lactic acid system that contributes to muscle fatigue?',
        options: ['Urea', 'Creatine phosphate', 'Lactate and hydrogen ions', 'Carbon dioxide'],
        correctAnswer: 2,
        explanation: 'Anaerobic glycolysis produces lactate and hydrogen ions. The accumulation of hydrogen ions lowers muscle pH, contributing to the burning sensation and fatigue.',
      },
      {
        type: 'scenario',
        question: 'Which energy system is dominant during this activity?',
        scenario: 'You are jogging at a comfortable pace for 30 minutes, able to hold a conversation throughout.',
        options: ['ATP-PC system', 'Lactic acid system', 'None — the body uses stored fat only', 'Aerobic system'],
        correctAnswer: 3,
        explanation: 'A comfortable, sustained jog lasting 30 minutes is powered by the aerobic system, which efficiently uses oxygen to produce energy from carbohydrates and fats.',
      },
      {
        type: 'multiple_choice',
        question: 'The ATP-PC system does NOT require which of the following?',
        options: ['Creatine phosphate', 'Enzymes', 'Oxygen', 'Stored ATP'],
        correctAnswer: 2,
        explanation: 'The ATP-PC system is anaerobic — it does not require oxygen. It uses stored ATP and creatine phosphate for rapid energy production.',
      },
      {
        type: 'multiple_choice',
        question: 'Which fuel sources does the aerobic system use?',
        options: ['Only carbohydrates', 'Only creatine phosphate', 'Only fats', 'Carbohydrates, fats, and sometimes protein'],
        correctAnswer: 3,
        explanation: 'The aerobic system is versatile, primarily using carbohydrates and fats, and occasionally protein during prolonged exercise or when other fuel sources are depleted.',
      },
      {
        type: 'multiple_choice',
        question: 'As exercise intensity increases, the body shifts from which system to which?',
        options: ['There is no shift between systems', 'Aerobic to anaerobic (lactic acid and ATP-PC)', 'Lactic acid to aerobic', 'ATP-PC to aerobic'],
        correctAnswer: 1,
        explanation: 'As intensity rises, the aerobic system cannot supply energy fast enough, so the body increasingly relies on anaerobic systems (lactic acid and ATP-PC).',
      },
    ],
  },
  // ─── Chapter 6: The Respiratory System ───
  {
    unitNumber: 1,
    chapterNumber: 6,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Where does gas exchange primarily occur in the lungs?',
        options: ['The bronchioles', 'The trachea', 'The alveoli', 'The bronchi'],
        correctAnswer: 2,
        explanation: 'The alveoli are tiny air sacs at the end of the bronchioles where oxygen diffuses into the blood and carbon dioxide diffuses out.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the general breathing rule during resistance training?',
        options: ['Only breathe between reps', 'Breathe as fast as possible', 'Exhale during the effort phase and inhale during the lowering phase', 'Hold your breath throughout the entire set'],
        correctAnswer: 2,
        explanation: 'The standard guideline is to exhale during the concentric (effort) phase and inhale during the eccentric (lowering) phase to maintain appropriate intra-abdominal pressure.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the Valsalva manoeuvre?',
        options: ['A relaxation breathing method', 'Holding your breath against a closed glottis to maximise core pressure', 'A breathing technique for cardio', 'Rapid breathing to increase oxygen'],
        correctAnswer: 1,
        explanation: 'The Valsalva manoeuvre involves holding a deep breath against a closed glottis to create maximum intra-abdominal pressure, used by experienced lifters during heavy maximal efforts.',
      },
      {
        type: 'multiple_choice',
        question: 'Approximately how many alveoli are in the human lungs?',
        options: ['30 million', '3 billion', '300 thousand', '300 million'],
        correctAnswer: 3,
        explanation: 'There are roughly 300 million alveoli in the lungs, creating a surface area about the size of a tennis court for efficient gas exchange.',
      },
      {
        type: 'multiple_choice',
        question: 'What causes your breathing rate to increase during exercise?',
        options: ['Increased oxygen in the blood', 'Lower body temperature', 'Muscle contraction alone', 'Rising CO2 levels detected by chemoreceptors'],
        correctAnswer: 3,
        explanation: 'Rising carbon dioxide levels in the blood are detected by chemoreceptors, which signal the brain to increase breathing rate to expel CO2 and bring in more oxygen.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely cause of their light-headedness?',
        scenario: 'During a set of heavy overhead presses, a gym member reports feeling dizzy and light-headed after every set.',
        options: ['They are breathing too slowly', 'They are not eating enough before training', 'They are holding their breath for the entire set', 'They need more caffeine'],
        correctAnswer: 2,
        explanation: 'Holding your breath through entire sets causes excessive blood pressure spikes and reduces oxygen supply to the brain, leading to dizziness. They should exhale during the press and inhale during the lowering.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the difference between diaphragmatic breathing and shallow chest breathing?',
        options: ['Chest breathing is more efficient for exercise', 'Diaphragmatic breathing is only used during sleep', 'Diaphragmatic breathing uses the belly and draws more air; chest breathing only uses the upper chest', 'There is no difference'],
        correctAnswer: 2,
        explanation: 'Diaphragmatic (belly) breathing draws the diaphragm downward to fill the lungs more completely, while shallow chest breathing only uses the upper chest and limits air intake.',
      },
    ],
  },
  // ─── Chapter 7: The Nervous System & Movement Control ───
  {
    unitNumber: 1,
    chapterNumber: 7,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'What are the two main divisions of the nervous system?',
        options: ['Sympathetic and parasympathetic', 'Somatic and autonomic', 'Central and peripheral', 'Motor and sensory'],
        correctAnswer: 2,
        explanation: 'The nervous system is divided into the Central Nervous System (brain and spinal cord) and the Peripheral Nervous System (nerves extending to muscles, joints, and organs).',
      },
      {
        type: 'multiple_choice',
        question: 'What is a motor unit?',
        options: ['A joint receptor', 'A single motor neuron and all the muscle fibres it controls', 'A type of muscle fibre', 'The brain area responsible for movement'],
        correctAnswer: 1,
        explanation: 'A motor unit consists of one motor neuron and all the muscle fibres it innervates. When the neuron fires, all fibres in that motor unit contract.',
      },
      {
        type: 'multiple_choice',
        question: 'Why do beginners get stronger before their muscles visibly grow?',
        options: ['They are building muscle but it is hidden by water retention', 'Early strength gains are neural — better motor unit recruitment and coordination', 'It is an illusion caused by motivation', 'They are losing fat which reveals existing muscle'],
        correctAnswer: 1,
        explanation: 'Initial strength gains are predominantly neural adaptations: improved motor unit recruitment, faster firing rates, and better muscle coordination, rather than increased muscle size.',
      },
      {
        type: 'multiple_choice',
        question: 'What is proprioception?',
        options: ['The ability to see your muscles in a mirror', "The body\'s sense of its own position in space without visual input", 'A type of stretching technique', 'The sensation of muscle soreness after training'],
        correctAnswer: 1,
        explanation: "Proprioception is the body\'s ability to sense its position, movement, and force without relying on vision, using specialised receptors in muscles, tendons, and joints.",
      },
      {
        type: 'scenario',
        question: 'What is the most likely explanation for this strength increase?',
        scenario: 'A new lifter has been squatting for 4 weeks. Their squat has increased from 40kg to 65kg, but their leg measurements have not changed at all.',
        options: ['They are using momentum to lift more', 'Neural adaptations — better motor unit recruitment and coordination', 'They are gaining muscle but it is being hidden', 'The weight plates are inaccurate'],
        correctAnswer: 1,
        explanation: 'In the first weeks of training, strength gains are almost entirely neural. The nervous system learns to recruit more motor units and coordinate the movement more efficiently, producing more force without visible muscle growth.',
      },
      {
        type: 'multiple_choice',
        question: 'What type of training best improves motor unit recruitment?',
        options: ['Heavy lifting at 85%+ of 1RM', 'Light weights for high reps', 'Static stretching', 'Long-distance running'],
        correctAnswer: 0,
        explanation: 'Heavy lifting (85%+ of 1RM) forces the nervous system to recruit large motor units that are not activated during lighter efforts, improving maximal force production.',
      },
      {
        type: 'multiple_choice',
        question: 'What do Golgi tendon organs detect?',
        options: ['Joint position', 'Muscle length', 'Body temperature', 'Changes in muscle tension'],
        correctAnswer: 3,
        explanation: 'Golgi tendon organs are located at the muscle-tendon junction and detect changes in muscle tension, providing a protective mechanism against excessive force.',
      },
    ],
  },
  // ─── Chapter 8: Posture, Alignment & Mobility ───
  {
    unitNumber: 1,
    chapterNumber: 8,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'What is Upper Crossed Syndrome?',
        options: ['A type of shoulder impingement', 'A condition causing hip pain', 'Excessive lower back curvature', 'Tight chest and neck muscles with weak upper back and deep neck flexors, causing rounded shoulders'],
        correctAnswer: 3,
        explanation: 'Upper Crossed Syndrome involves tight pectorals and upper trapezius paired with weak rhomboids, lower traps, and deep neck flexors, resulting in rounded shoulders and forward head posture.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the key difference between flexibility and mobility?',
        options: ['Flexibility is passive range of motion; mobility is active range under control', 'Flexibility is more important for athletes', 'Mobility is only about joints while flexibility is about muscles', 'They are the same thing'],
        correctAnswer: 0,
        explanation: 'Flexibility is the passive range available at a joint, while mobility is the active range of motion you can control with strength — mobility is what matters under load.',
      },
      {
        type: 'scenario',
        question: 'Which mobility restriction is most likely causing this issue?',
        scenario: 'A gym member cannot squat below parallel without their heels lifting off the floor. Their hip flexibility seems adequate when tested lying down.',
        options: ['Limited wrist flexibility', 'Limited thoracic spine extension', 'Limited ankle dorsiflexion', 'Limited shoulder mobility'],
        correctAnswer: 2,
        explanation: 'Limited ankle dorsiflexion prevents the shin from travelling forward enough during a squat, forcing the torso excessively forward or the heels to lift. Hip flexibility is adequate, so the ankles are the limiting factor.',
      },
      {
        type: 'multiple_choice',
        question: 'What causes Lower Crossed Syndrome?',
        options: ['Weak shoulders and tight chest', 'Tight hip flexors and lower back with weak glutes and abdominals', 'Tight hamstrings and weak quadriceps', 'Tight calves and weak ankles'],
        correctAnswer: 1,
        explanation: 'Lower Crossed Syndrome involves tight hip flexors and erector spinae paired with weak gluteals and abdominals, resulting in excessive anterior pelvic tilt and lumbar lordosis.',
      },
      {
        type: 'multiple_choice',
        question: 'What is loaded stretching?',
        options: ['Stretching while someone pushes you further', 'Stretching after adding weight plates to your body', 'Using light weight through a full range of motion to build usable mobility', 'Stretching a muscle until it is sore'],
        correctAnswer: 2,
        explanation: 'Loaded stretching uses light weights through a full range of motion (e.g., deep pause squats, Romanian deadlifts) to build strength and control at end ranges — one of the most effective methods for building mobility.',
      },
      {
        type: 'multiple_choice',
        question: 'Which four areas should gym users prioritise for mobility work?',
        options: ['Lower back, quadriceps, triceps, forearms', 'Thoracic spine, hips, ankles, shoulders', 'Hamstrings, biceps, calves, chest', 'Wrists, elbows, knees, neck'],
        correctAnswer: 1,
        explanation: 'The thoracic spine, hips, ankles, and shoulders are the four key areas where restrictions most commonly limit exercise performance and create compensatory movement patterns.',
      },
      {
        type: 'multiple_choice',
        question: 'How long should a dynamic warm-up mobility routine take before training?',
        options: ['5-10 minutes', 'Mobility work is not needed before training', '30-45 minutes', '1-2 minutes'],
        correctAnswer: 0,
        explanation: 'A 5-10 minute dynamic warm-up targeting the joints about to be loaded is sufficient. Longer, sustained mobility work is best done separately on rest days or in the evening.',
      },
    ],
  },
];
