import type { UnitAssessment } from '../types';

export const level2Unit3Assessment: UnitAssessment = {
  unitNumber: 3,
  title: 'Unit 3 Assessment: Introduction to Exercise',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    {
      type: 'multiple_choice',
      question: 'Which type of training primarily develops muscular strength, hypertrophy, and muscular endurance through working against an external force?',
      options: [
        'Balance training',
        'Cardiovascular training',
        'Flexibility training',
        'Resistance training',
      ],
      correctAnswer: 3,
      explanation: 'Resistance training involves working muscles against an external force (weights, bands, bodyweight) and is the primary method for developing muscular strength, hypertrophy, and muscular endurance.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is NOT a physiological benefit of cardiovascular training?',
      options: [
        'Improved cardiac output and stroke volume',
        'Increased maximal force production',
        'Increased capillary density in working muscles',
        'Reduced resting heart rate over time',
      ],
      correctAnswer: 1,
      explanation: 'Increased maximal force production is a benefit of resistance training, not cardiovascular training. Cardio training improves heart function, blood flow, and aerobic capacity.',
    },
    {
      type: 'multiple_choice',
      question: 'Why is HIIT not suitable for daily use in most programmes?',
      options: [
        'It does not produce cardiovascular adaptations',
        'It requires specialist equipment not available in most gyms',
        'It only develops flexibility, not fitness',
        'It places high recovery demands on the body and can lead to overtraining',
      ],
      correctAnswer: 3,
      explanation: 'HIIT places significant stress on the neuromuscular and metabolic systems, requiring adequate recovery between sessions. Daily HIIT without sufficient recovery can lead to overtraining, fatigue, and injury.',
    },
    {
      type: 'multiple_choice',
      question: 'Why is dynamic stretching preferred over static stretching during a warm-up?',
      options: [
        'Static stretching can temporarily reduce force production before training',
        'Static stretching increases heart rate too much before training',
        'Dynamic stretching is easier to perform',
        'Dynamic stretching builds more muscle than static stretching',
      ],
      correctAnswer: 0,
      explanation: 'Research shows static stretching before training can temporarily reduce strength and power output by 5-10%. Dynamic stretching increases blood flow, ROM, and neuromuscular readiness without this force-reduction effect.',
    },
    {
      type: 'scenario',
      question: 'Design the Potentiate phase of your warm-up. Which approach is most appropriate?',
      scenario: 'You are preparing for a heavy lower body session starting with barbell back squats at 100kg working weight.',
      options: [
        '10 minutes of static hamstring stretches',
        'Sprint intervals on the treadmill for 5 minutes',
        'Bodyweight squats → goblet squats → empty bar squats → ramping sets (60kg → 80kg → 90kg)',
        'Upper body activation work with band pull-aparts',
      ],
      correctAnswer: 2,
      explanation: 'The Potentiate phase bridges into the main session with movements that progressively load the upcoming exercises. Starting with bodyweight and ramping up through goblet squats to progressively heavier barbell sets prepares the neuromuscular system specifically for heavy squats.',
    },
    {
      type: 'multiple_choice',
      question: 'According to the rep range continuum, which rep range is most commonly associated with hypertrophy training?',
      options: [
        '30–50 reps',
        '15–25 reps',
        '1–5 reps',
        '6–12 reps',
      ],
      correctAnswer: 3,
      explanation: 'The 6-12 rep range at 65-85% of 1RM is most commonly associated with hypertrophy (muscle growth), balancing mechanical tension and metabolic stress for optimal muscle-building stimulus.',
    },
    {
      type: 'multiple_choice',
      question: 'Why are rest periods of 3–5 minutes recommended for strength training (1–5 reps)?',
      options: [
        'To allow the muscles to cool down completely',
        'To allow full ATP-PC recovery for maximal force production on the next set',
        'To increase metabolic stress and promote hypertrophy',
        'To reduce the total training volume of the session',
      ],
      correctAnswer: 1,
      explanation: 'Strength training relies heavily on the ATP-PC energy system, which takes 3-5 minutes to fully replenish. Shorter rest would compromise force production on subsequent sets.',
    },
    {
      type: 'multiple_choice',
      question: 'What does RIR 2 mean in the context of resistance training?',
      options: [
        'You should perform 2 repetitions per set',
        'You should rest for 2 minutes between sets',
        'You have completed 2 rounds of the exercise',
        'You could complete 2 more reps before reaching failure',
      ],
      correctAnswer: 3,
      explanation: 'RIR (Reps in Reserve) indicates how many additional reps could be performed before failure. RIR 2 means you finish the set with approximately 2 reps remaining before you would fail.',
    },
    {
      type: 'multiple_choice',
      question: 'Heart rate Zone 2 (60–70% MHR) is primarily associated with which adaptation?',
      options: [
        'Aerobic base building and fat oxidation',
        'Anaerobic threshold development',
        'VO₂ max improvement',
        'Maximal power output',
      ],
      correctAnswer: 0,
      explanation: 'Zone 2 training develops the aerobic base, improves fat oxidation as a fuel source, and builds cardiac efficiency. It is characterised by a conversational pace and is the foundation of cardiovascular fitness.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the "80/20 rule" in cardiovascular training?',
      options: [
        '80% of training should be resistance and 20% cardio',
        '80% of the session should be warm-up and 20% working sets',
        '80% of cardio should be low intensity and 20% high intensity',
        '80% of gains come from the first 20% of effort',
      ],
      correctAnswer: 2,
      explanation: 'The 80/20 rule suggests 80% of cardiovascular training should be at low intensity (Zone 2) and 20% at high intensity (Zones 4-5). This polarised approach is well-supported by research and used by elite endurance athletes.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the key difference between flexibility and mobility?',
      options: [
        'Flexibility applies to muscles; mobility applies only to cardiovascular fitness',
        'Flexibility is active; mobility is passive',
        'There is no difference — the terms are interchangeable',
        'Flexibility is the passive ability of a muscle to lengthen; mobility is the active ability to control movement through a range of motion',
      ],
      correctAnswer: 3,
      explanation: 'Flexibility is passive muscle lengthening (e.g., someone pushing your leg into a stretch), while mobility is the active ability to move a joint through its ROM with control, requiring strength and coordination at end ranges.',
    },
    {
      type: 'multiple_choice',
      question: 'What does PNF stretching involve?',
      options: [
        'Bouncing in and out of a stretched position rapidly',
        'Alternating between muscle contraction and stretching to achieve greater ROM',
        'Using electrical stimulation to lengthen muscles',
        'Holding a stretch for 5 minutes without movement',
      ],
      correctAnswer: 1,
      explanation: 'PNF (Proprioceptive Neuromuscular Facilitation) uses the contract-relax method: the muscle is stretched, then isometrically contracted for 5-10 seconds, relaxed, and then stretched further. This produces the greatest acute ROM improvements.',
    },
    {
      type: 'multiple_choice',
      question: 'When is foam rolling most appropriately used?',
      options: [
        'Only for competitive athletes, not general gym users',
        'Only after training, never before',
        'Only when you are injured',
        'Pre-exercise or post-exercise — it does not reduce force production like static stretching',
      ],
      correctAnswer: 3,
      explanation: 'Foam rolling can be used pre-exercise (to improve ROM without the force-reduction effects of static stretching) or post-exercise (to aid recovery). It is appropriate for all populations.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is NOT one of the six fundamental movement patterns?',
      options: [
        'Rotation',
        'Hinge',
        'Carry',
        'Push',
      ],
      correctAnswer: 0,
      explanation: 'The six fundamental movement patterns are: Push, Pull, Squat, Hinge, Lunge, and Carry. Rotation is sometimes considered an additional pattern but is not one of the core six in most frameworks.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the primary benefit of including unilateral exercises in a programme?',
      options: [
        'They are easier to learn than bilateral exercises',
        'They allow heavier loads than bilateral exercises',
        'They expose and correct left-right strength imbalances',
        'They only target the core muscles',
      ],
      correctAnswer: 2,
      explanation: 'Unilateral exercises work one limb at a time, exposing and helping to correct strength imbalances between sides. They also demand greater stabilisation, improving balance and proprioception.',
    },
    {
      type: 'multiple_choice',
      question: 'What does the SAID principle state?',
      options: [
        'Systematic Approach to Individual Design',
        'Sleep Always Improves Development',
        'Strength And Intensity Determine results',
        'Specific Adaptation to Imposed Demands',
      ],
      correctAnswer: 3,
      explanation: 'SAID (Specific Adaptation to Imposed Demands) states that the body adapts specifically to the type of stress placed upon it. Train for strength → get stronger. Train for endurance → improve endurance.',
    },
    {
      type: 'scenario',
      question: 'What is the most appropriate recommendation?',
      scenario: 'You are experiencing persistent fatigue, declining performance over 3 weeks, disturbed sleep, and increased irritability despite training consistently 6 days per week.',
      options: [
        'Switch entirely to flexibility training for the next month',
        'Implement a deload week and review sleep, nutrition, and overall recovery strategy',
        'Increase training frequency to 7 days to push through the plateau',
        'Add a pre-workout supplement for more energy',
      ],
      correctAnswer: 1,
      explanation: 'These symptoms indicate under-recovery or early overtraining. A deload week (reduced volume/intensity) combined with improved sleep, nutrition, and recovery strategies is the appropriate response — not more training stress.',
    },
    {
      type: 'multiple_choice',
      question: 'What is a deload and how is it typically implemented?',
      options: [
        'A complete week off from all training',
        'Doubling training volume to shock the body into adaptation',
        'Switching from resistance training to only cardiovascular work',
        'A planned reduction of 40-60% in training volume while maintaining the training habit',
      ],
      correctAnswer: 3,
      explanation: 'A deload is a planned reduction in training volume and/or intensity (typically 40-60% reduction) lasting one week. Training continues but at reduced stress, allowing accumulated fatigue to dissipate while maintaining the training habit.',
    },
    {
      type: 'multiple_choice',
      question: 'What is sarcopenia, and what is the primary countermeasure?',
      options: [
        'Age-related muscle mass loss — resistance training',
        'Age-related bone loss — calcium supplementation',
        'Age-related joint stiffness — daily yoga',
        'Age-related cardiovascular decline — steady-state cardio',
      ],
      correctAnswer: 0,
      explanation: 'Sarcopenia is the age-related loss of skeletal muscle mass and function. Resistance training is the primary evidence-based countermeasure, helping maintain muscle mass, strength, and functional capacity in older adults.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the PAR-Q used for?',
      options: [
        'Determining which training split is most appropriate',
        'Calculating your macronutrient requirements',
        'Screening for health conditions that may require medical clearance before exercise',
        'Measuring your 1 rep max on all exercises',
      ],
      correctAnswer: 2,
      explanation: 'The Physical Activity Readiness Questionnaire (PAR-Q) is a standardised health screening tool that identifies individuals who may need medical clearance before beginning an exercise programme. It should be completed before starting a new training programme.',
    }
  ],
};
