import type { UnitAssessment } from '../types';

export const mindsetL3Unit1Assessment: UnitAssessment = {
  unitNumber: 1, title: 'Unit 1 Assessment — Advanced Stress Physiology & Emotional Mastery',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What does the HPA axis stand for?', options: ['Heart-Pulse-Adrenaline', 'High-Performance-Activation', 'Hormone-Production-Axis', 'Hypothalamic-Pituitary-Adrenal'], correctAnswer: 3, explanation: 'The hypothalamic-pituitary-adrenal axis is the central stress response system.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['The weight of stress hormones', 'Cumulative wear and tear from chronic stress', 'A measure of cortisol levels', 'The maximum stress you can handle'], correctAnswer: 1, explanation: 'Allostatic load describes the cumulative physiological damage from chronic stress.' },
    { type: 'multiple_choice', question: 'How does cognitive reappraisal differ from emotional suppression?', options: ['Suppression is more effective', 'Reappraisal changes the emotion at its source; suppression tries to push it down', 'Reappraisal avoids the emotion entirely', 'They are the same thing'], correctAnswer: 1, explanation: 'Reappraisal changes interpretation to alter the emotion; suppression tries to inhibit the response after it occurs.' },
    { type: 'multiple_choice', question: 'What does affect labelling do to amygdala activity?', options: ['Reduces it by up to 50%', 'Has no effect', 'Increases it by 50%', 'Completely eliminates it'], correctAnswer: 0, explanation: 'Naming emotions reduces amygdala activation by recruiting prefrontal cortex regulation.' },
    { type: 'multiple_choice', question: 'What neurochemicals are released during flow state?', options: ['Norepinephrine, dopamine, endorphins, anandamide, and serotonin', 'Only dopamine', 'Only serotonin', 'Cortisol and adrenaline'], correctAnswer: 0, explanation: 'Flow involves a cascade of five key neurochemicals that enhance performance.' },
    { type: 'multiple_choice', question: 'What is the ideal challenge-skill balance for flow?', options: ['Task should be approximately 4% beyond current ability', 'Challenge level does not matter', 'Task should be well within comfort zone', 'Task should be far beyond ability'], correctAnswer: 0, explanation: 'Research suggests the optimal stretch is approximately 4% beyond current ability.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Appreciation, relationships, strength, possibilities, existential clarity', 'Physical, mental, emotional, social, spiritual', 'Denial, anger, bargaining, depression, acceptance', 'Strength, speed, power, endurance, flexibility'], correctAnswer: 0, explanation: 'Tedeschi and Calhoun identified these five domains of positive change after trauma.' },
    { type: 'multiple_choice', question: 'Which is the strongest source of self-efficacy according to Bandura?', options: ['Vicarious experience', 'Verbal persuasion', 'Physiological state', 'Mastery experience'], correctAnswer: 3, explanation: 'Actually doing the thing successfully is the strongest foundation for believing you can do it.' },
    { type: 'multiple_choice', question: 'What are the three states in polyvagal theory?', options: ['Ventral vagal, sympathetic, dorsal vagal', 'Fight, flight, freeze', 'Rest, active, exhausted', 'Calm, alert, panicked'], correctAnswer: 0, explanation: 'Polyvagal theory describes ventral vagal (safety), sympathetic (mobilisation), and dorsal vagal (shutdown).' },
    { type: 'scenario', scenario: 'Someone is in dorsal vagal shutdown — feeling numb, disconnected, and foggy.', question: 'Which intervention is most appropriate?', options: ['Slow breathing only', 'Gentle movement and environmental orienting', 'Intense breathwork', 'Telling them to "snap out of it"'], correctAnswer: 1, explanation: 'In shutdown, gentle movement and orienting to the environment helps shift toward mobilisation before calm.' },
    { type: 'multiple_choice', question: 'What effect does chronic cortisol have on the hippocampus?', options: ['It enlarges it', 'It improves memory', 'No effect', 'It shrinks it'], correctAnswer: 3, explanation: 'Chronic cortisol causes hippocampal atrophy, impairing memory and learning.' },
    { type: 'multiple_choice', question: 'What is the TIPP technique used for?', options: ['Improving flexibility', 'Improving sleep', 'Managing intense emotional distress', 'Building muscle'], correctAnswer: 2, explanation: 'TIPP (Temperature, Intense exercise, Paced breathing, Progressive relaxation) is a distress tolerance technique.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "The HPA axis refers to:", options: ["Heart, Pectorals, Arms \u2014 muscle groups for training", "Hypothalamic-Pituitary-Adrenal axis \u2014 the body's central stress response system", "A breathing technique for performance", "The main energy system for sprinting"], correctAnswer: 1, explanation: "The HPA (Hypothalamic-Pituitary-Adrenal) axis is the body's primary neuroendocrine stress response system, regulating cortisol release and stress adaptation." },
    { type: 'multiple_choice', question: "Flow states are characterised by:", options: ['Boredom and distraction', 'Anxiety and overwhelm', 'Multitasking across several activities', 'Total absorption, effortless focus, and loss of time awareness'], correctAnswer: 3, explanation: 'Flow (Csikszentmihalyi) occurs when skill level matches challenge level \u2014 producing deep immersion, intrinsic motivation, and optimal performance.' },
    { type: 'multiple_choice', question: "Post-traumatic growth refers to:", options: ["Pretending trauma didn't happen", "Positive psychological transformation following adversity", "Developing PTSD", "Avoiding all future challenges"], correctAnswer: 1, explanation: "Post-traumatic growth is the documented phenomenon where individuals experience positive change \u2014 stronger relationships, new priorities, personal strength \u2014 after struggling with highly challenging life crises." },
    { type: 'multiple_choice', question: "Polyvagal theory suggests the nervous system has:", options: ['Two states: fight or flight', 'States that cannot be influenced', 'One state that controls everything', 'Three hierarchical states: social engagement, sympathetic activation, and dorsal vagal shutdown'], correctAnswer: 3, explanation: "Stephen Porges' polyvagal theory describes three hierarchical nervous system states: ventral vagal (social/safe), sympathetic (fight/flight), and dorsal vagal (freeze/shutdown)." },
    { type: 'multiple_choice', question: "Confidence is best understood as:", options: ["A fixed personality trait you're born with", 'A skill built through preparation, exposure, and evidence-based self-talk', 'Something that only comes from success', 'Arrogance disguised as positivity'], correctAnswer: 1, explanation: "Confidence is not fixed \u2014 it's a skill developed through competence, preparation, repeated exposure to challenges, and constructive self-talk grounded in evidence." },
    { type: 'multiple_choice', question: "Which strategy most effectively regulates emotional responses?", options: ["Suppressing all negative emotions", "Cognitive reappraisal \u2014 reframing the meaning of a situation", "Avoiding all emotional situations", "Only expressing emotions when alone"], correctAnswer: 1, explanation: "Cognitive reappraisal \u2014 changing how you interpret a situation \u2014 is one of the most effective emotion regulation strategies, reducing negative emotional intensity without suppression." },
    { type: 'multiple_choice', question: "Allostatic load refers to:", options: ["The weight you can lift in one rep", "The cumulative wear and tear on the body from chronic stress", "A type of training periodisation", "The body's resting metabolic rate"], correctAnswer: 1, explanation: "Allostatic load is the cumulative physiological cost of chronic stress. High allostatic load is linked to cardiovascular disease, immune dysfunction, and cognitive decline." },
    { type: 'multiple_choice', question: "The 'challenge vs threat' appraisal model suggests:", options: ['Whether we perceive a stressor as a challenge or threat affects our physiological response', 'All stress is harmful', 'Threats always improve performance', 'Challenges should be avoided'], correctAnswer: 0, explanation: "Research shows that appraising a stressor as a 'challenge' (I can handle this) produces a more efficient cardiovascular response than a 'threat' appraisal (I can't cope), improving performance." },

  ],
};
