import type { UnitAssessment, ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

// ── Unit Assessments ──

export const mindsetL3Unit1Assessment: UnitAssessment = {
  unitNumber: 1, title: 'Unit 1 Assessment — Advanced Stress Physiology & Emotional Mastery',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What does the HPA axis stand for?', options: ['Heart-Pulse-Adrenaline', 'Hypothalamic-Pituitary-Adrenal', 'Hormone-Production-Axis', 'High-Performance-Activation'], correctAnswer: 1, explanation: 'The hypothalamic-pituitary-adrenal axis is the central stress response system.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['Cumulative wear and tear from chronic stress', 'The weight of stress hormones', 'A measure of cortisol levels', 'The maximum stress you can handle'], correctAnswer: 0, explanation: 'Allostatic load describes the cumulative physiological damage from chronic stress.' },
    { type: 'multiple_choice', question: 'How does cognitive reappraisal differ from emotional suppression?', options: ['Suppression is more effective', 'They are the same thing', 'Reappraisal avoids the emotion entirely', 'Reappraisal changes the emotion at its source; suppression tries to push it down'], correctAnswer: 3, explanation: 'Reappraisal changes interpretation to alter the emotion; suppression tries to inhibit the response after it occurs.' },
    { type: 'multiple_choice', question: 'What does affect labelling do to amygdala activity?', options: ['Increases it by 50%', 'Has no effect', 'Reduces it by up to 50%', 'Completely eliminates it'], correctAnswer: 2, explanation: 'Naming emotions reduces amygdala activation by recruiting prefrontal cortex regulation.' },
    { type: 'multiple_choice', question: 'What neurochemicals are released during flow state?', options: ['Only dopamine', 'Norepinephrine, dopamine, endorphins, anandamide, and serotonin', 'Only serotonin', 'Cortisol and adrenaline'], correctAnswer: 1, explanation: 'Flow involves a cascade of five key neurochemicals that enhance performance.' },
    { type: 'multiple_choice', question: 'What is the ideal challenge-skill balance for flow?', options: ['Task should be approximately 4% beyond current ability', 'Challenge level does not matter', 'Task should be well within comfort zone', 'Task should be far beyond ability'], correctAnswer: 0, explanation: 'Research suggests the optimal stretch is approximately 4% beyond current ability.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Strength, speed, power, endurance, flexibility', 'Physical, mental, emotional, social, spiritual', 'Denial, anger, bargaining, depression, acceptance', 'Appreciation, relationships, strength, possibilities, existential clarity'], correctAnswer: 3, explanation: 'Tedeschi and Calhoun identified these five domains of positive change after trauma.' },
    { type: 'multiple_choice', question: 'Which is the strongest source of self-efficacy according to Bandura?', options: ['Vicarious experience', 'Verbal persuasion', 'Mastery experience', 'Physiological state'], correctAnswer: 2, explanation: 'Actually doing the thing successfully is the strongest foundation for believing you can do it.' },
    { type: 'multiple_choice', question: 'What are the three states in polyvagal theory?', options: ['Fight, flight, freeze', 'Ventral vagal, sympathetic, dorsal vagal', 'Rest, active, exhausted', 'Calm, alert, panicked'], correctAnswer: 1, explanation: 'Polyvagal theory describes ventral vagal (safety), sympathetic (mobilisation), and dorsal vagal (shutdown).' },
    { type: 'scenario', scenario: 'Someone is in dorsal vagal shutdown — feeling numb, disconnected, and foggy.', question: 'Which intervention is most appropriate?', options: ['Gentle movement and environmental orienting', 'Slow breathing only', 'Intense breathwork', 'Telling them to "snap out of it"'], correctAnswer: 0, explanation: 'In shutdown, gentle movement and orienting to the environment helps shift toward mobilisation before calm.' },
    { type: 'multiple_choice', question: 'What effect does chronic cortisol have on the hippocampus?', options: ['It enlarges it', 'It improves memory', 'No effect', 'It shrinks it'], correctAnswer: 3, explanation: 'Chronic cortisol causes hippocampal atrophy, impairing memory and learning.' },
    { type: 'multiple_choice', question: 'What is the TIPP technique used for?', options: ['Improving flexibility', 'Improving sleep', 'Managing intense emotional distress', 'Building muscle'], correctAnswer: 2, explanation: 'TIPP (Temperature, Intense exercise, Paced breathing, Progressive relaxation) is a distress tolerance technique.' },
  ],
};

export const mindsetL3Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Advanced Breathing & Exposure Science',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What happens to blood CO2 during cyclic hyperventilation?', options: ['It increases', 'It decreases (respiratory alkalosis)', 'It fluctuates randomly', 'It stays the same'], correctAnswer: 1, explanation: 'Rapid breathing blows off CO2, lowering blood CO2 and raising pH.' },
    { type: 'multiple_choice', question: 'What is resonance frequency breathing?', options: ['Breathing at the rate that maximises heart rate variability', 'Breathing only through the mouth', 'Holding your breath for maximum time', 'Breathing as fast as possible'], correctAnswer: 0, explanation: 'Resonance frequency breathing (typically 4.5–7 breaths/min) maximises HRV.' },
    { type: 'multiple_choice', question: 'By how much does cold exposure increase dopamine levels?', options: ['1000%', '50%', '10%', '250%'], correctAnswer: 3, explanation: 'Cold exposure can increase dopamine by approximately 250%, lasting 2–3 hours.' },
    { type: 'multiple_choice', question: 'What is the cold shock response?', options: ['Numbness in extremities', 'Feeling cold', 'Involuntary gasp, rapid breathing, and increased heart rate on cold contact', 'Shivering'], correctAnswer: 2, explanation: 'The cold shock response is a sympathetic nervous system reaction to sudden cold exposure.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Hormones released during fever', 'Molecular chaperones that repair damaged proteins and protect cells', 'Proteins that cause heat stroke', 'Muscle-building proteins'], correctAnswer: 1, explanation: 'HSPs repair damaged proteins and increase cellular stress resistance.' },
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['The inverted-U relationship between arousal and performance', 'The relationship between sleep and performance', 'The effect of nutrition on cognition', 'The stages of learning'], correctAnswer: 0, explanation: 'The Yerkes-Dodson Law shows performance peaks at moderate arousal and declines at extremes.' },
    { type: 'multiple_choice', question: 'What is the Valsalva manoeuvre used for in training?', options: ['Improving endurance', 'Improving flexibility', 'Reducing heart rate', 'Maximising intra-abdominal pressure for heavy lifts'], correctAnswer: 3, explanation: 'The Valsalva manoeuvre creates core stability through held breath and bracing during heavy lifts.' },
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['Chronic stress damage', 'A type of breathing technique', 'Beneficial adaptation from low-to-moderate stress doses', 'A disease caused by hormones'], correctAnswer: 2, explanation: 'Hormesis describes how moderate stressors trigger beneficial adaptive responses.' },
    { type: 'multiple_choice', question: 'Finnish sauna studies found frequent sauna use reduced all-cause mortality by approximately how much?', options: ['10%', '40%', '80%', '20%'], correctAnswer: 1, explanation: 'Frequent sauna use (4–7x/week) was associated with approximately 40% reduction in all-cause mortality.' },
    { type: 'scenario', scenario: 'Someone wants to start cold exposure but has never tried it before.', question: 'What is the safest starting protocol?', options: ['30 seconds of cold water at the end of a normal shower', 'Jump into an ice bath for 5 minutes', 'Hold ice on your skin for 10 minutes', 'Swim in a cold lake'], correctAnswer: 0, explanation: 'Starting with brief cold at the end of a warm shower allows safe habituation before progression.' },
    { type: 'multiple_choice', question: 'What BOLT score should you achieve before progressing to intense cyclic hyperventilation?', options: ['60 seconds', '15 seconds', '10 seconds', '25 seconds'], correctAnswer: 3, explanation: 'A BOLT score above 25 indicates sufficient CO2 tolerance for advanced protocols.' },
    { type: 'multiple_choice', question: 'How does contrast therapy reduce DOMS?', options: ['By numbing the muscles', 'It does not reduce DOMS', 'Through vascular pumping — alternating vasodilation and vasoconstriction', 'By eliminating lactic acid'], correctAnswer: 2, explanation: 'Temperature oscillation creates a vascular pump effect that enhances circulation and reduces inflammation.' },
  ],
};

export const mindsetL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Advanced Focus, Discipline & Cognitive Performance',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is attention residue?', options: ['Leftover attention from sleep', 'Cognitive cost of task-switching — part of your focus remains on the previous task', 'Attention deficit disorder', 'A type of meditation'], correctAnswer: 1, explanation: 'Attention residue means part of your cognitive focus remains on the previous task after switching.' },
    { type: 'multiple_choice', question: 'How many hours of genuine deep work can most people sustain per day?', options: ['3–4 hours', '1–2 hours', '10+ hours', '6–8 hours'], correctAnswer: 0, explanation: 'Research suggests most people can sustain 3–4 hours of truly deep cognitive work daily.' },
    { type: 'multiple_choice', question: 'What does the ego depletion model propose?', options: ['Ego has no effect on decisions', 'Willpower is unlimited', 'The ego grows with use', 'Willpower is a finite resource that gets depleted'], correctAnswer: 3, explanation: 'Baumeister\'s model proposed willpower is a depletable resource, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is the most effective solution to decision fatigue?', options: ['Making more decisions to build stamina', 'Drinking coffee', 'Designing systems that eliminate unnecessary decisions', 'Sleeping more'], correctAnswer: 2, explanation: 'Systems and pre-commitment remove the need for decisions, preserving cognitive resources.' },
    { type: 'multiple_choice', question: 'What does BDNF stand for and why is it important?', options: ['Basic Daily Nutritional Formula', 'Brain-Derived Neurotrophic Factor — supports neuron growth and plasticity', 'Body-Dependent Nutritional Factor', 'Brain-Disrupting Neural Function'], correctAnswer: 1, explanation: 'BDNF supports neuronal growth, survival, and synaptic plasticity — critical for learning and brain health.' },
    { type: 'multiple_choice', question: 'What clears metabolic waste from the brain during sleep?', options: ['The glymphatic system', 'Blood circulation', 'The lymphatic system', 'Cerebrospinal breathing'], correctAnswer: 0, explanation: 'The glymphatic system is 10x more active during sleep, clearing amyloid-beta and other waste.' },
    { type: 'multiple_choice', question: 'What are the three basic psychological needs in Self-Determination Theory?', options: ['Physical, emotional, spiritual', 'Food, shelter, safety', 'Power, achievement, affiliation', 'Autonomy, competence, relatedness'], correctAnswer: 3, explanation: 'Deci and Ryan identified autonomy, competence, and relatedness as essential for intrinsic motivation.' },
    { type: 'multiple_choice', question: 'According to James Clear, what is the most effective layer to start behaviour change?', options: ['Outcomes', 'Environment', 'Identity', 'Processes'], correctAnswer: 2, explanation: 'Starting with identity ("I am someone who...") creates lasting change because behaviour follows belief.' },
    { type: 'multiple_choice', question: 'What type of visualisation is most effective for performance?', options: ['Not visualising at all', 'Process visualisation combined with brief outcome visualisation', 'Outcome visualisation only', 'Visualising relaxation'], correctAnswer: 1, explanation: 'Process visualisation primes neural pathways; brief outcome visualisation sets direction.' },
    { type: 'scenario', scenario: 'An athlete keeps saying "I just need to find my motivation" before training.', question: 'What does motivation science suggest?', options: ['Action precedes motivation — start training and motivation follows', 'They should wait until motivation arrives', 'They need a new programme', 'They should take a month off'], correctAnswer: 0, explanation: 'Motivation follows action, not the other way around. Starting creates the motivation to continue.' },
    { type: 'multiple_choice', question: 'What does creatine supplementation improve cognitively?', options: ['Nothing — it only affects muscles', 'Long-term memory only', 'Emotional regulation', 'Short-term memory and reasoning, especially under stress or sleep deprivation'], correctAnswer: 3, explanation: 'Creatine has cognitive benefits for short-term memory and reasoning, particularly when cognitively stressed.' },
    { type: 'multiple_choice', question: 'What is the motivation spectrum in SDT from least to most self-determined?', options: ['Passive → active', 'Low energy → high energy', 'Amotivation → external → introjected → identified → integrated → intrinsic', 'Intrinsic → extrinsic'], correctAnswer: 2, explanation: 'SDT describes a continuum from amotivation through external regulation to intrinsic motivation.' },
  ],
};

export const mindsetL3Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Resilience Integration & Lifelong Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Breathing, cold, heat, journaling, meditation', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Strength, speed, endurance, flexibility, balance', 'Eat, sleep, train, repeat, rest'], correctAnswer: 1, explanation: 'A complete system addresses physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'What is the AAAA Setback Protocol?', options: ['Assess, Accept, Adapt, Act', 'Avoid, Analyse, Attempt, Achieve', 'Assess, Avoid, Accept, Achieve', 'Acknowledge, Apologise, Adjust, Advance'], correctAnswer: 0, explanation: 'Assess the reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does rumination differ from reflection?', options: ['Reflection is unhealthy', 'Rumination is more productive', 'They are the same', 'Reflection produces action points; rumination is circular without resolution'], correctAnswer: 3, explanation: 'Reflection moves toward insight and action; rumination repeats without progress.' },
    { type: 'multiple_choice', question: 'How harmful is loneliness compared to other health risks?', options: ['Equivalent to mild dehydration', 'No measurable health effect', 'Equivalent to smoking 15 cigarettes per day', 'Minor effect'], correctAnswer: 2, explanation: 'Meta-analysis of 300,000+ participants found loneliness as harmful as smoking 15 cigarettes daily.' },
    { type: 'multiple_choice', question: 'What characterises an effective boundary?', options: ['Only set when convenient', 'Clear, consistent, compassionate, with known consequences', 'Vague and flexible', 'Aggressive and punishing'], correctAnswer: 1, explanation: 'Effective boundaries are specific, consistently enforced, compassionate, and have clear consequences.' },
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['Hedonic is pleasure-based; eudaimonic is meaning and purpose-based', 'They are identical', 'Eudaimonic is about physical health', 'Hedonic is long-lasting; eudaimonic is temporary'], correctAnswer: 0, explanation: 'Hedonic wellbeing seeks pleasure; eudaimonic wellbeing seeks meaning, purpose, and self-realisation.' },
    { type: 'multiple_choice', question: 'What is the difference between coaching and therapy?', options: ['Therapy is for weak people', 'Coaching is more effective', 'No difference', 'Coaching helps find answers through questions; therapy treats clinical conditions'], correctAnswer: 3, explanation: 'Coaching facilitates self-discovery; therapy provides clinical treatment for mental health conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Agree 80% of the time', 'Practise 80 minutes daily', 'Listen 80%, speak 20%', 'Speak 80%, listen 20%'], correctAnswer: 2, explanation: 'Effective coaching involves listening far more than speaking — approximately 80% listening.' },
    { type: 'scenario', scenario: 'Someone you are coaching describes persistent low mood for three weeks, loss of interest in activities, and difficulty getting out of bed.', question: 'What should you do?', options: ['Give them a harder training programme', 'Encourage them to seek professional mental health support', 'Suggest cold exposure therapy', 'Tell them to be more positive'], correctAnswer: 1, explanation: 'These symptoms suggest possible depression — this exceeds peer coaching scope and requires professional help.' },
    { type: 'multiple_choice', question: 'What does "periodising mental training" mean?', options: ['Alternating between higher stress phases and recovery phases in mental practices', 'Only training mentally on weekdays', 'Training the same way every day', 'Only practising when motivated'], correctAnswer: 0, explanation: 'Like physical training, mental training benefits from cycling intensity with adequate recovery periods.' },
    { type: 'multiple_choice', question: 'According to the course, what is the ultimate performance metric?', options: ['Perfect execution', 'Maximum intensity', 'Speed of progress', 'Sustainability'], correctAnswer: 3, explanation: 'Sustainability — consistency over years — beats short-term intensity every time.' },
    { type: 'multiple_choice', question: 'What is a values clarification exercise designed to reveal?', options: ['Your career path', 'Your personality type', 'Your core values that should guide decision-making', 'Your fitness level'], correctAnswer: 2, explanation: 'Values clarification identifies your deepest priorities to guide consistent, meaningful decision-making.' },
  ],
};

// ── Final Assessment ──

export const mindsetL3FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 3 Final Assessment — Advanced Mindset',
  passMarkPercent: 80, pickCount: 20,
  questions: [
    { type: 'multiple_choice', question: 'What feedback mechanism regulates the HPA axis?', options: ['Serotonin suppresses the adrenals', 'Cortisol feeds back to shut down CRH and ACTH release', 'Dopamine activates the pituitary', 'Adrenaline increases CRH'], correctAnswer: 1, explanation: 'Cortisol provides negative feedback to the hypothalamus and pituitary to terminate the stress response.' },
    { type: 'multiple_choice', question: 'What brain change does chronic cortisol cause to the amygdala?', options: ['Enlarges it (increasing anxiety)', 'No effect', 'Improves its function', 'Shrinks it'], correctAnswer: 0, explanation: 'Chronic cortisol enlarges the amygdala, increasing anxiety and threat sensitivity.' },
    { type: 'multiple_choice', question: 'What is hypofrontality in flow state?', options: ['Heightened self-consciousness', 'Complete brain shutdown', 'Increased prefrontal activity', 'Temporary partial deactivation of the prefrontal cortex'], correctAnswer: 3, explanation: 'Hypofrontality silences the inner critic by partially deactivating the prefrontal cortex during flow.' },
    { type: 'multiple_choice', question: 'What minimum BOLT score indicates adequate CO2 tolerance for advanced breathwork?', options: ['10 seconds', '15 seconds', '25 seconds', '45 seconds'], correctAnswer: 2, explanation: 'A BOLT score above 25 indicates sufficient tolerance for more intense protocols.' },
    { type: 'multiple_choice', question: 'How long does the dopamine increase from cold exposure typically last?', options: ['1 week', '2–3 hours', '30 minutes', '24 hours'], correctAnswer: 1, explanation: 'Cold exposure produces a gradual, sustained dopamine increase lasting 2–3 hours.' },
    { type: 'multiple_choice', question: 'What does attention residue mean for gym performance?', options: ['Checking your phone between sets reduces focus for 10–20 minutes', 'Nothing', 'It improves multi-tasking', 'It only affects work performance'], correctAnswer: 0, explanation: 'Attention residue from phone-checking reduces training quality for an extended period.' },
    { type: 'multiple_choice', question: 'Which SDT need does rigid externally imposed programming undermine?', options: ['All equally', 'Relatedness', 'Competence', 'Autonomy'], correctAnswer: 3, explanation: 'Rigid external programmes remove choice, undermining the autonomy need.' },
    { type: 'multiple_choice', question: 'What is the most effective type of goal for daily behaviour?', options: ['Outcome goals', 'Dream goals', 'Process goals', 'Performance goals'], correctAnswer: 2, explanation: 'Process goals (daily actions) are fully controllable and build identity through consistent votes.' },
    { type: 'scenario', scenario: 'Someone trains 7 days a week, does cold plunges daily, and advanced breathwork twice daily. Their sleep is deteriorating and motivation is dropping.', question: 'What is the most likely issue?', options: ['Not training hard enough', 'Hormetic stress overload without adequate recovery', 'They need more cold exposure', 'Their nutrition is wrong'], correctAnswer: 1, explanation: 'Stacking too many stressors without recovery leads to overload — reduce frequency and periodise.' },
    { type: 'multiple_choice', question: 'How does process visualisation differ from outcome visualisation?', options: ['Process imagines the steps and effort; outcome imagines the end result', 'Outcome visualisation primes motor pathways', 'They are the same', 'Process is less effective'], correctAnswer: 0, explanation: 'Process visualisation primes the neural pathways for execution; outcome visualisation sets direction.' },
    { type: 'multiple_choice', question: 'What is the single strongest predictor of happiness and longevity?', options: ['Income', 'Physical fitness', 'Career success', 'Social connection quality'], correctAnswer: 3, explanation: 'Quality social connection is the strongest predictor of both happiness and longevity.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional mental health support?', options: ['Only in emergencies', 'Only if they ask', 'When symptoms persist for 2+ weeks and impair daily functioning', 'Never — you can handle everything'], correctAnswer: 2, explanation: 'Persistent symptoms impairing daily life exceed peer coaching scope and require professional intervention.' },
    { type: 'multiple_choice', question: 'What makes identified motivation more resilient than external motivation?', options: ['It is always enjoyable', 'It connects to personal values rather than external rewards', 'It is driven by guilt', 'It requires no effort'], correctAnswer: 1, explanation: 'Identified motivation is resilient because it connects behaviour to personal values and identity.' },
    { type: 'multiple_choice', question: 'What percentage of daily energy does the brain consume?', options: ['20%', '10%', '50%', '5%'], correctAnswer: 0, explanation: 'The brain uses approximately 20% of total body energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the most important factor for long-term brain health?', options: ['Supplements', 'Brain training games', 'Caffeine', 'Sleep'], correctAnswer: 3, explanation: 'Sleep enables glymphatic clearance, memory consolidation, and neural repair — irreplaceable for brain health.' },
    { type: 'scenario', scenario: 'A training partner asks you to help them "find their motivation." They feel stuck but have no clinical symptoms.', question: 'What approach aligns with motivation science?', options: ['Give them a motivational speech', 'Tell them to wait until they feel motivated', 'Help them identify their values and design systems that reduce reliance on willpower', 'Suggest they take a month off'], correctAnswer: 2, explanation: 'Values-based systems and environmental design create sustainable motivation without relying on feelings.' },
    { type: 'multiple_choice', question: 'What does the Unbreakable Philosophy ultimately emphasise?', options: ['Being better than everyone else', 'Consistent, values-aligned living with tools for recovery', 'Never showing weakness', 'Training every day without rest'], correctAnswer: 1, explanation: 'Being unbreakable means having the knowledge and tools to recover and grow — consistently, not perfectly.' },
    { type: 'multiple_choice', question: 'What is the key difference between assertive and aggressive boundary-setting?', options: ['Assertive states needs clearly without attacking; aggressive attacks the person', 'No difference', 'Aggressive is more effective', 'Assertive is passive'], correctAnswer: 0, explanation: 'Assertive communication protects the relationship while setting clear limits; aggression damages it.' },
    { type: 'multiple_choice', question: 'What is the recommended approach for mental training deload weeks?', options: ['Stop all practices entirely', 'Increase intensity', 'Only deload if injured', 'Reduce intensity, extend sleep, focus on enjoyment every 4–6 weeks'], correctAnswer: 3, explanation: 'Periodic deloads prevent psychological burnout and maintain long-term practice sustainability.' },
    { type: 'multiple_choice', question: 'According to growth mindset research, what characterises the most resilient approach to failure?', options: ['Viewing failure as evidence of fixed limitations', 'Ignoring failure completely', 'Viewing failure as information and an opportunity for learning', 'Avoiding failure at all costs'], correctAnswer: 2, explanation: 'Growth mindset treats failure as feedback — data for adjustment, not evidence of inability.' },
    { type: 'scenario', scenario: 'You have completed both Level 2 and Level 3 Mindset courses. A friend asks what the single most important takeaway is.', question: 'Which answer best captures the course philosophy?', options: ['Knowledge is enough — no practice needed', 'Build systems and practices that make resilience automatic, then apply them consistently', 'Avoid all discomfort', 'Learn to never feel stressed'], correctAnswer: 1, explanation: 'The course teaches that resilience is built through consistent practice of evidence-based systems — not perfection.' },
  ],
};

// ── Chapter Quizzes ──

// Unit 1 — Advanced Stress Physiology & Emotional Mastery
export const mindsetL3Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What hormone does the hypothalamus release to start the HPA cascade?', options: ['CRH (corticotropin-releasing hormone)', 'Cortisol', 'ACTH', 'Adrenaline'], correctAnswer: 0, explanation: 'CRH from the hypothalamus triggers the pituitary to release ACTH.' },
    { type: 'multiple_choice', question: 'What is eustress?', options: ['Stress from exercise only', 'Chronic damaging stress', 'Stress you cannot control', 'Positive stress that drives adaptation and growth'], correctAnswer: 3, explanation: 'Eustress is beneficial stress that is short-duration and within coping capacity.' },
    { type: 'multiple_choice', question: 'What does chronic cortisol do to the prefrontal cortex?', options: ['Has no effect', 'Makes it larger', 'Disrupts it, reducing decision-making and impulse control', 'Enhances it'], correctAnswer: 2, explanation: 'Chronic cortisol impairs prefrontal function, reducing rational decision-making capacity.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['A type of training', 'Cumulative physiological damage from chronic stress', 'A breathing technique', 'Maximum weight you can lift'], correctAnswer: 1, explanation: 'Allostatic load is the total wear and tear from sustained stress on body systems.' },
    { type: 'multiple_choice', question: 'Can the same stressor be both eustress and distress?', options: ['Yes, depending on perception and recovery state', 'Only physical stressors', 'No, stressors are always one or the other', 'Only psychological stressors'], correctAnswer: 0, explanation: 'Perception and recovery capacity determine whether a stressor is beneficial or harmful.' },
    { type: 'multiple_choice', question: 'What metabolic effect does chronic cortisol promote?', options: ['Improved digestion', 'Muscle growth', 'Fat loss', 'Insulin resistance and visceral fat storage'], correctAnswer: 3, explanation: 'Sustained cortisol promotes insulin resistance and preferential abdominal fat deposition.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Avoiding stressful situations', 'Ignoring your emotions', 'Deliberately reinterpreting a situation to change your emotional response', 'Suppressing feelings'], correctAnswer: 2, explanation: 'Reappraisal changes the meaning of a situation, altering the emotion at its source.' },
    { type: 'multiple_choice', question: 'What brain effect does affect labelling produce?', options: ['Increases amygdala activity', 'Reduces amygdala activity by recruiting prefrontal cortex', 'No measurable effect', 'Activates fight-or-flight'], correctAnswer: 1, explanation: 'Naming emotions engages the prefrontal cortex, which dampens amygdala reactivity.' },
    { type: 'multiple_choice', question: 'What does TIPP stand for in distress tolerance?', options: ['Temperature, Intense exercise, Paced breathing, Progressive relaxation', 'Train, Improve, Persist, Perform', 'Time, Intention, Practice, Patience', 'Think, Imagine, Plan, Proceed'], correctAnswer: 0, explanation: 'TIPP uses physiological interventions to change body state and therefore emotional state.' },
    { type: 'multiple_choice', question: 'What is third-person affect labelling?', options: ['Labelling emotions in a group', 'Talking about someone else', 'Writing emotions anonymously', 'Referring to yourself by name for additional psychological distance'], correctAnswer: 3, explanation: 'Using your own name creates psychological distance that enhances emotional regulation.' },
    { type: 'multiple_choice', question: 'How does suppression compare to reappraisal long-term?', options: ['They are equally effective', 'Suppression is better', 'Reappraisal produces better outcomes with less physiological cost', 'Neither is effective'], correctAnswer: 2, explanation: 'Suppression requires ongoing effort and does not reduce the underlying emotion; reappraisal does.' },
    { type: 'multiple_choice', question: 'Which form of labelling produces the strongest regulation?', options: ['Saying "I feel bad"', 'Written detailed labelling through journaling', 'Talking to no one', 'Thinking silently'], correctAnswer: 1, explanation: 'Written labelling forces precise articulation, producing the strongest and most lasting regulatory effect.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Who coined the concept of "flow state"?', options: ['Mihaly Csikszentmihalyi', 'B.F. Skinner', 'Carl Jung', 'Sigmund Freud'], correctAnswer: 0, explanation: 'Csikszentmihalyi described and researched flow as a state of complete absorption.' },
    { type: 'multiple_choice', question: 'What happens to the prefrontal cortex during flow?', options: ['It shuts down completely', 'It becomes hyperactive', 'No change occurs', 'It partially deactivates (hypofrontality)'], correctAnswer: 3, explanation: 'Temporary hypofrontality silences the inner critic, allowing implicit systems to drive performance.' },
    { type: 'multiple_choice', question: 'How much can flow increase productivity?', options: ['50–100%', 'No measurable increase', '200–500%', '10–20%'], correctAnswer: 2, explanation: 'Research suggests flow can increase productivity by 200–500%.' },
    { type: 'multiple_choice', question: 'What is the minimum uninterrupted focus time to enter flow?', options: ['5 minutes', '20 minutes', '10 minutes', '60 minutes'], correctAnswer: 1, explanation: 'Most people need at least 20 minutes of uninterrupted focus before flow state becomes possible.' },
    { type: 'multiple_choice', question: 'What comes before the flow state in the flow cycle?', options: ['The struggle phase', 'Recovery', 'Sleep', 'Relaxation'], correctAnswer: 0, explanation: 'The struggle phase (difficulty and frustration) precedes the release into flow.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'How is trauma defined in this context?', options: ['Only childhood events', 'Any negative experience', 'Only severe physical injury', 'By how the nervous system responded and whether the response became stuck'], correctAnswer: 3, explanation: 'Trauma is defined by the nervous system response, not the severity of the event itself.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Speed, strength, flexibility, endurance, coordination', 'Physical recovery, mental clarity, emotional balance, social skills, career success', 'Appreciation, relationships, personal strength, new possibilities, existential clarity', 'Acceptance, anger, denial, bargaining, depression'], correctAnswer: 2, explanation: 'PTG manifests as greater appreciation, deeper relationships, personal strength, new possibilities, and existential understanding.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional help?', options: ['Only in life-threatening situations', 'When daily functioning is significantly impaired for more than two weeks', 'Only if they ask', 'Never — peer support is always sufficient'], correctAnswer: 1, explanation: 'Persistent functional impairment exceeds peer coaching scope and requires professional intervention.' },
    { type: 'multiple_choice', question: 'Does PTG mean trauma was necessary for growth?', options: ['No — it means growth can emerge from the struggle, not that trauma was beneficial', 'Only for some people', 'Yes', 'PTG is not real'], correctAnswer: 0, explanation: 'PTG does not justify trauma — it acknowledges that growth can emerge from adversity under the right conditions.' },
    { type: 'multiple_choice', question: 'What brain change occurs with PTSD?', options: ['No structural changes', 'Improved memory', 'Enhanced emotional regulation', 'Overactive amygdala, suppressed prefrontal cortex, hippocampal processing issues'], correctAnswer: 3, explanation: 'PTSD involves an overactive threat system, reduced rational processing, and unprocessed traumatic memories.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What is the strongest source of self-efficacy?', options: ['Verbal persuasion', 'Reading about success', 'Mastery experience', 'Vicarious experience'], correctAnswer: 2, explanation: 'Actually succeeding at progressively harder challenges provides the most powerful evidence of capability.' },
    { type: 'multiple_choice', question: 'What is the T/C ratio related to?', options: ['Training/Competition split', 'Testosterone/Cortisol ratio correlating with behavioural confidence', 'Training/Coaching balance', 'Time/Cost efficiency'], correctAnswer: 1, explanation: 'The testosterone-to-cortisol ratio correlates with assertiveness and behavioural confidence.' },
    { type: 'multiple_choice', question: 'How does avoidance affect confidence?', options: ['It reinforces the belief that you cannot handle the situation', 'It protects confidence', 'It builds confidence over time', 'It has no effect'], correctAnswer: 0, explanation: 'Every avoidance strengthens the fear and weakens self-efficacy.' },
    { type: 'multiple_choice', question: 'What is the confidence exposure ladder?', options: ['A gym exercise', 'A supplement protocol', 'A breathing technique', 'A ranked list of feared situations to work through progressively'], correctAnswer: 3, explanation: 'The exposure ladder ranks situations from mildly uncomfortable to genuinely frightening for progressive desensitisation.' },
    { type: 'multiple_choice', question: 'What distinguishes genuine self-efficacy from performative confidence?', options: ['Performative confidence is stronger', 'Self-efficacy requires no experience', 'Self-efficacy is built through progressive competence; performative confidence collapses under pressure', 'They are identical'], correctAnswer: 2, explanation: 'Genuine self-efficacy is evidence-based; performative confidence lacks substance and fails when tested.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What are the three polyvagal states?', options: ['Alert, relaxed, asleep', 'Ventral vagal, sympathetic, dorsal vagal', 'Fight, flight, freeze', 'Happy, sad, angry'], correctAnswer: 1, explanation: 'Polyvagal theory describes safety (ventral vagal), mobilisation (sympathetic), and shutdown (dorsal vagal).' },
    { type: 'multiple_choice', question: 'What is the ventral vagal state associated with?', options: ['Social engagement, safety, and calm', 'Numbness and shutdown', 'Panic', 'Fight or flight'], correctAnswer: 0, explanation: 'Ventral vagal is the state of safety — connection, calm, and complex cognitive function.' },
    { type: 'multiple_choice', question: 'What works best for shifting out of dorsal vagal shutdown?', options: ['Caffeine', 'Forcing yourself to socialise', 'Intense breathwork', 'Gentle movement and orienting to the environment'], correctAnswer: 3, explanation: 'In shutdown, gentle stimulation (movement, sensory awareness) helps shift toward mobilisation before safety.' },
    { type: 'multiple_choice', question: 'What does co-regulation mean?', options: ['Regulating your own emotions', 'Exercising with a partner', 'Using connection with another person\'s calm nervous system to regulate your own', 'Taking medication'], correctAnswer: 2, explanation: 'Co-regulation uses social connection — a calm voice, presence — to help regulate your own nervous system.' },
    { type: 'multiple_choice', question: 'Can you be in mixed autonomic states?', options: ['No, only one state at a time', 'Yes — you can be sympathetically activated while partially in dorsal vagal', 'Only during sleep', 'Only during exercise'], correctAnswer: 1, explanation: 'Mixed states are common — you can feel anxious (sympathetic) and helpless (dorsal vagal) simultaneously.' },
  ]),
];

// Unit 2 — Advanced Breathing & Exposure Science
export const mindsetL3Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What happens to blood pH during cyclic hyperventilation?', options: ['It increases (respiratory alkalosis)', 'It stays the same', 'It fluctuates unpredictably', 'It decreases (more acidic)'], correctAnswer: 0, explanation: 'Blowing off CO2 raises blood pH, creating respiratory alkalosis.' },
    { type: 'multiple_choice', question: 'What is a CO2 table?', options: ['A nutrition reference chart', 'A breathing speed test', 'A carbon dioxide detector', 'Repeated breath holds with decreasing rest intervals'], correctAnswer: 3, explanation: 'CO2 tables progressively challenge your tolerance by reducing rest between holds.' },
    { type: 'multiple_choice', question: 'What breathing rate typically achieves resonance frequency?', options: ['20+ breaths/min', '1 breath/min', '4.5–7 breaths/min', '12–15 breaths/min'], correctAnswer: 2, explanation: 'Most people\'s resonance frequency falls between 4.5 and 7 breaths per minute.' },
    { type: 'multiple_choice', question: 'What does improved CO2 tolerance correlate with?', options: ['Higher blood pressure', 'Reduced anxiety and better performance under pressure', 'Increased breathing rate', 'Lower oxygen levels'], correctAnswer: 1, explanation: 'Better CO2 tolerance means a less reactive respiratory drive, directly reducing anxiety symptoms.' },
    { type: 'multiple_choice', question: 'What is the benefit of the breath hold after hyperventilation rounds?', options: ['It creates a powerful sympathetic-to-parasympathetic transition', 'It increases CO2 only', 'It builds lung capacity', 'It has no specific benefit'], correctAnswer: 0, explanation: 'The recovery phase after holds triggers a strong parasympathetic shift, enhancing vagal tone.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What triggers the cold shock response?', options: ['Muscle cooling', 'Low body temperature', 'Brain temperature drop', 'Cutaneous cold receptors signalling the sympathetic nervous system'], correctAnswer: 3, explanation: 'Skin cold receptors trigger the involuntary sympathetic response upon cold contact.' },
    { type: 'multiple_choice', question: 'How long does the cold shock response typically last?', options: ['5–10 seconds', '5 minutes', '30–60 seconds', '30 minutes'], correctAnswer: 2, explanation: 'The cold shock response is most intense in the first 30–60 seconds and diminishes with habituation.' },
    { type: 'multiple_choice', question: 'What does cold exposure do to noradrenaline?', options: ['No effect', 'Increases it by 200–300%', 'Increases it by 10%', 'Decreases it'], correctAnswer: 1, explanation: 'Cold exposure significantly increases noradrenaline, improving alertness, focus, and mood.' },
    { type: 'multiple_choice', question: 'What is brown adipose tissue (BAT)?', options: ['Metabolically active fat that generates heat by burning calories', 'A type of muscle', 'Scar tissue', 'Unhealthy body fat'], correctAnswer: 0, explanation: 'BAT produces heat through thermogenesis, activated by cold exposure.' },
    { type: 'multiple_choice', question: 'What is the primary psychological benefit of cold exposure?', options: ['Weight loss', 'Better skin', 'Improved flexibility', 'Proving you can choose discomfort and handle it — transferable mental toughness'], correctAnswer: 3, explanation: 'Choosing voluntary discomfort builds the psychological habit of doing hard things.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What cardiovascular response does sauna use create?', options: ['No cardiovascular effect', 'Blood pressure increases sharply and stays elevated', 'Heart rate increases to 100–150 bpm with vasodilation', 'Heart rate decreases'], correctAnswer: 2, explanation: 'Heat exposure creates cardiovascular stress similar to moderate exercise.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Proteins that cause overheating', 'Molecular chaperones that repair proteins and protect cells', 'Digestive enzymes', 'Proteins destroyed by heat'], correctAnswer: 1, explanation: 'HSPs repair damaged proteins and increase cellular resilience to all forms of stress.' },
    { type: 'multiple_choice', question: 'By how much can sauna increase growth hormone acutely?', options: ['200–300%', '50%', '10–20%', '1000%'], correctAnswer: 0, explanation: 'Studies show up to 200–300% acute growth hormone increase with 20-minute sauna sessions.' },
    { type: 'multiple_choice', question: 'What is contrast therapy?', options: ['Training at different intensities', 'Using light and dark rooms', 'Comparing two training programmes', 'Alternating heat and cold exposure for amplified benefits'], correctAnswer: 3, explanation: 'Contrast therapy combines heat and cold to enhance vascular, hormonal, and neurological benefits.' },
    { type: 'multiple_choice', question: 'How much sweat can be lost in a single sauna session?', options: ['A few millilitres', '3–5 litres', '0.5–1 litre', '10 litres'], correctAnswer: 2, explanation: 'Significant fluid loss (0.5–1L per session) makes hydration before and after essential.' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['Higher arousal always means better performance', 'Performance peaks at moderate arousal; declines at both extremes', 'Rest is always optimal', 'The relationship between sleep and memory'], correctAnswer: 1, explanation: 'The inverted-U shows optimal performance at moderate arousal, with decline at under- and over-arousal.' },
    { type: 'multiple_choice', question: 'What breathing is best before a heavy lift?', options: ['Short sharp breaths to increase sympathetic activation', 'Extended exhale to calm down', 'Holding breath for 2 minutes', 'Hyperventilation for 5 minutes'], correctAnswer: 0, explanation: 'Power events benefit from moderate sympathetic activation to increase force readiness.' },
    { type: 'multiple_choice', question: 'When should you exhale during a precision task?', options: ['It does not matter', 'During the preparation phase', 'After completing the action', 'At the moment of execution'], correctAnswer: 3, explanation: 'Exhale at execution (e.g., releasing an arrow) provides maximum stability and calm.' },
    { type: 'multiple_choice', question: 'What is tactical breathing?', options: ['Breathing only through one nostril', 'Breathing as fast as possible', '4-count inhale, 4-count hold, 4-count exhale, 4-count hold', 'Not breathing during performance'], correctAnswer: 2, explanation: 'Tactical breathing (box breathing) manages anxiety during competition breaks and transitions.' },
    { type: 'multiple_choice', question: 'How can post-performance breathing reduce heart rate recovery time?', options: ['It cannot', 'Slow nasal breathing (4 in, 8 out) can reduce recovery time by 30%', 'Only medication works', 'Only cold water helps'], correctAnswer: 1, explanation: 'Deliberate parasympathetic breathing accelerates cardiovascular recovery after intense performance.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['Beneficial adaptation from controlled low-to-moderate stress', 'Damage from excessive stress', 'A disease process', 'A type of hormone'], correctAnswer: 0, explanation: 'Hormesis describes how moderate stressors trigger positive adaptive responses.' },
    { type: 'multiple_choice', question: 'By how much can contrast therapy reduce DOMS?', options: ['50–70%', '5%', '100%', '20–30%'], correctAnswer: 3, explanation: 'Studies show contrast therapy can reduce delayed-onset muscle soreness by 20–30%.' },
    { type: 'multiple_choice', question: 'What signs indicate hormetic stress overload?', options: ['No signs — overload is not possible', 'Better performance', 'Deteriorating sleep, dropping motivation, rising resting heart rate', 'Increased energy and motivation'], correctAnswer: 2, explanation: 'Sleep disruption, motivational decline, and elevated resting HR indicate too much stress without recovery.' },
    { type: 'multiple_choice', question: 'How should you end a contrast therapy session for alertness?', options: ['Order does not matter', 'On cold', 'On a warm-up', 'On heat'], correctAnswer: 1, explanation: 'Ending on cold promotes alertness through noradrenaline and dopamine elevation.' },
    { type: 'multiple_choice', question: 'How often should you include a full rest day from exposure stressors?', options: ['At least one per week', 'Only when injured', 'Never', 'Once per month'], correctAnswer: 0, explanation: 'Minimum one full rest day per week prevents cumulative stress overload.' },
  ]),
];

// Unit 3 — Advanced Focus, Discipline & Cognitive Performance
export const mindsetL3Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the three attention networks?', options: ['Visual, auditory, tactile', 'Short-term, long-term, working', 'Conscious, subconscious, unconscious', 'Alerting, orienting, executive'], correctAnswer: 3, explanation: 'Alerting (readiness), orienting (directing focus), and executive (conflict resolution) networks.' },
    { type: 'multiple_choice', question: 'How long does attention residue affect focus after a phone check?', options: ['No effect', '1 hour', '10–20 minutes', '1–2 minutes'], correctAnswer: 2, explanation: 'Part of attention remains on the previous task for 10–20 minutes after switching.' },
    { type: 'multiple_choice', question: 'What percentage of body energy does the brain consume?', options: ['10%', '20%', '5%', '40%'], correctAnswer: 1, explanation: 'The brain uses approximately 20% of total energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the recommended starting block for deep work training?', options: ['25-minute Pomodoro blocks', '3-hour blocks', '5-minute blocks', '8-hour blocks'], correctAnswer: 0, explanation: 'Start with 25-minute focused blocks and gradually extend as capacity develops.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for maintaining focus?', options: ['Positive thinking', 'Motivation', 'Caffeine', 'Environmental design — removing distractions'], correctAnswer: 3, explanation: 'Removing distractions beats trying to resist them — environment design trumps willpower.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What did Baumeister\'s ego depletion theory propose?', options: ['Willpower grows with use', 'Willpower only applies to diet', 'Willpower is a finite resource that gets depleted through decisions', 'Willpower is unlimited'], correctAnswer: 2, explanation: 'The theory proposed willpower is finite and gets used up, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is decision fatigue?', options: ['A medical condition', 'Declining decision quality as the number of decisions increases', 'Tiredness from exercise', 'Fatigue from too much sleep'], correctAnswer: 1, explanation: 'More decisions = worse later decisions, which is well-documented even if the mechanism is debated.' },
    { type: 'multiple_choice', question: 'What did James Clear call "making the right thing the default"?', options: ['System design that removes the need for willpower', 'Motivation technique', 'Positive affirmation', 'Goal setting'], correctAnswer: 0, explanation: 'Designing environments where desired behaviour requires less effort than undesired alternatives.' },
    { type: 'multiple_choice', question: 'Which type of decision is easiest to make?', options: ['Emotional decisions', 'Open-ended choices', 'Multi-option decisions', 'Binary decisions (yes/no)'], correctAnswer: 3, explanation: 'Binary decisions are simpler and consume less cognitive resources than open-ended choices.' },
    { type: 'multiple_choice', question: 'How does meal prep reduce decision fatigue?', options: ['It does not', 'It only helps with cooking time', 'It eliminates the daily "what should I eat?" decision entirely', 'It saves money only'], correctAnswer: 2, explanation: 'Pre-committing food choices eliminates daily nutrition decisions when willpower may be depleted.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What does BDNF do in the brain?', options: ['Damages neurons', 'Supports growth, survival, and plasticity of neurons', 'Produces cortisol', 'Clears waste'], correctAnswer: 1, explanation: 'BDNF is essential for neuronal growth, survival, and synaptic plasticity.' },
    { type: 'multiple_choice', question: 'What system clears brain waste during sleep?', options: ['Glymphatic system', 'Lymphatic system', 'Respiratory system', 'Digestive system'], correctAnswer: 0, explanation: 'The glymphatic system is 10x more active during sleep, clearing proteins linked to neurodegeneration.' },
    { type: 'multiple_choice', question: 'What cognitive effect does even 2% dehydration have?', options: ['None', 'Better memory', 'Improved focus', 'Impaired cognitive performance'], correctAnswer: 3, explanation: 'Even mild dehydration measurably impairs cognitive performance and mood.' },
    { type: 'multiple_choice', question: 'What supplement has evidence for cognitive benefits under stress?', options: ['Vitamin C', 'Calcium', 'Creatine (3–5g daily)', 'Iron'], correctAnswer: 2, explanation: 'Creatine improves short-term memory and reasoning, especially under stress or sleep deprivation.' },
    { type: 'multiple_choice', question: 'How does exercise affect the hippocampus?', options: ['Damages it', 'Physically grows it through increased BDNF and neurogenesis', 'Shrinks it', 'No effect'], correctAnswer: 1, explanation: 'Regular exercise increases hippocampal volume through BDNF-driven neurogenesis.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What are the three needs in Self-Determination Theory?', options: ['Autonomy, competence, relatedness', 'Food, water, shelter', 'Power, achievement, affiliation', 'Safety, belonging, esteem'], correctAnswer: 0, explanation: 'SDT identifies autonomy (control), competence (capability), and relatedness (connection) as essential.' },
    { type: 'multiple_choice', question: 'What type of motivation is "I train because it is who I am"?', options: ['External regulation', 'Introjected regulation', 'Amotivation', 'Integrated regulation'], correctAnswer: 3, explanation: 'Integrated regulation means the behaviour is fully aligned with your sense of identity.' },
    { type: 'multiple_choice', question: 'Why do rigid externally imposed programmes often fail?', options: ['They are too short', 'The exercises are wrong', 'They undermine autonomy', 'They are too easy'], correctAnswer: 2, explanation: 'Removing choice undermines the autonomy need, which is essential for sustained intrinsic motivation.' },
    { type: 'multiple_choice', question: 'What is the relationship between action and motivation?', options: ['They are unrelated', 'Action generates motivation — not the other way around', 'Motivation is purely genetic', 'Motivation always comes first'], correctAnswer: 1, explanation: 'Starting the action creates the motivation to continue — waiting for motivation leads to inaction.' },
    { type: 'multiple_choice', question: 'How can you support competence in training?', options: ['Track progressive overload and celebrate small wins', 'Make the programme too easy', 'Never change the programme', 'Avoid challenging exercises'], correctAnswer: 0, explanation: 'Visible progress and acknowledged achievements satisfy the competence need.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'According to James Clear, what are the three layers of behaviour change?', options: ['Thought, feeling, behaviour', 'Input, process, output', 'Goal, plan, action', 'Identity, process, outcome'], correctAnswer: 3, explanation: 'Clear describes behaviour change as three concentric layers: identity (core), process, and outcome.' },
    { type: 'multiple_choice', question: 'How is identity actually changed?', options: ['Through a single dramatic event', 'Through declarations and affirmations', 'Through accumulated evidence — consistent actions that "vote" for the new identity', 'It cannot be changed'], correctAnswer: 2, explanation: 'Identity shifts through accumulated votes — small consistent actions that provide evidence.' },
    { type: 'multiple_choice', question: 'What is more powerful: "I should train today" or "I don\'t skip training"?', options: ['They are equally effective', '"I don\'t skip training" — because it is identity-based', 'Neither is effective', '"I should train today"'], correctAnswer: 1, explanation: 'Identity-based framing is more powerful because it connects the action to who you are, not just what you should do.' },
    { type: 'multiple_choice', question: 'What are identity conflicts during personal change?', options: ['Resistance from others and feelings of impostor syndrome as you adopt new behaviours', 'Financial difficulties', 'Arguments with friends', 'Physical pain'], correctAnswer: 0, explanation: 'Others may resist your changes, and you may feel like an imposter in your new identity — both are normal.' },
    { type: 'multiple_choice', question: 'What is the best response to identity conflicts?', options: ['Pretend nothing has changed', 'Avoid everyone who knew the old you', 'Return to old behaviours', 'Continue voting for the new identity while accepting discomfort is temporary'], correctAnswer: 3, explanation: 'Continue consistent action toward the new identity — the transition discomfort is temporary.' },
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Why does mental rehearsal improve physical performance?', options: ['It replaces the need for training', 'It only works for elite athletes', 'It activates similar motor cortex regions as physical practice, strengthening neural pathways', 'It is a placebo effect'], correctAnswer: 2, explanation: 'Mental imagery activates motor cortex regions, strengthening the neural pathways used in actual performance.' },
    { type: 'multiple_choice', question: 'Why can outcome visualisation alone reduce effort?', options: ['It cannot', 'The brain partially "experiences" the reward, reducing motivation to earn it', 'It only affects beginners', 'Outcome visualisation is always harmful'], correctAnswer: 1, explanation: 'Premature reward experience from outcome visualisation can reduce the drive to actually achieve it.' },
    { type: 'multiple_choice', question: 'What makes visualisation more effective?', options: ['Multi-sensory detail — sight, sound, feel, even smell', 'Doing it once', 'Keeping it vague', 'Only visualising success'], correctAnswer: 0, explanation: 'Richer, more detailed imagery creates a stronger neural effect.' },
    { type: 'multiple_choice', question: 'Should you include adversity in your visualisation?', options: ['Adversity visualisation is harmful', 'No — only visualise perfect execution', 'Only negative scenarios', 'Yes — visualising overcoming obstacles improves real-world resilience'], correctAnswer: 3, explanation: 'Including challenges and your response to them prepares you for real-world imperfection.' },
    { type: 'multiple_choice', question: 'How long should daily mental rehearsal practice be?', options: ['2 hours', '1 minute', '5–10 minutes', '60 minutes'], correctAnswer: 2, explanation: '5–10 minutes daily is sufficient for measurable performance benefits from mental rehearsal.' },
  ]),
];

// Unit 4 — Resilience Integration & Lifelong Practice
export const mindsetL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Breathing, cold, heat, journaling, meditation', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Strength, cardio, flexibility, diet, sleep', 'Work, rest, play, eat, sleep'], correctAnswer: 1, explanation: 'The five pillars cover physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'How should you approach implementing the five pillars?', options: ['One pillar per week, building gradually', 'All five simultaneously from day one', 'Only the pillars you enjoy', 'Only during training days'], correctAnswer: 0, explanation: 'Gradual stacking prevents overwhelm and builds sustainable habits.' },
    { type: 'multiple_choice', question: 'What is mental training periodisation?', options: ['Only practising when stressed', 'Only training mentally on weekdays', 'Always pushing to maximum', 'Alternating high-intensity and recovery phases, with deload weeks every 4–6 weeks'], correctAnswer: 3, explanation: 'Like physical training, mental training needs intensity cycling with scheduled recovery.' },
    { type: 'multiple_choice', question: 'What should your protocol specify for difficult life periods?', options: ['Only exercise more', 'Stop all practices', 'Minimum viable doses — even 5 minutes of breathing is better than nothing', 'Double the intensity'], correctAnswer: 2, explanation: 'Minimum viable doses maintain the habit even when full practice is not possible.' },
    { type: 'multiple_choice', question: 'How often should you review your resilience system?', options: ['Only when something goes wrong', 'Weekly quick review, with monthly and quarterly deeper reviews', 'Annually', 'Never — set it and forget it'], correctAnswer: 1, explanation: 'Regular reviews at multiple intervals ensure the system stays relevant and effective.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What does the A-A-A-A setback protocol stand for?', options: ['Assess, Accept, Adapt, Act', 'Assess, Avoid, Accept, Achieve', 'Acknowledge, Adjust, Apply, Advance', 'Avoid, Analyse, Attempt, Achieve'], correctAnswer: 0, explanation: 'Assess reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does reflection differ from rumination?', options: ['They are the same process', 'Reflection is unhealthy', 'Rumination is more productive', 'Reflection produces action points; rumination is circular without resolution'], correctAnswer: 3, explanation: 'Reflection has direction and produces conclusions; rumination loops without progress.' },
    { type: 'multiple_choice', question: 'What should you do if you have been thinking about a setback for 20+ minutes without new insight?', options: ['Go to sleep', 'Keep thinking harder', 'Write down three controllable actions and do one immediately', 'Call a friend to discuss'], correctAnswer: 2, explanation: 'Breaking the rumination cycle requires shifting to concrete, controllable action.' },
    { type: 'multiple_choice', question: 'Is setback recovery a linear process?', options: ['Yes — it follows clear stages', 'No — it oscillates between emotional states with gradually decreasing intensity', 'It happens instantly', 'It only occurs with therapy'], correctAnswer: 1, explanation: 'Recovery is messy and non-linear — good days and bad days are normal throughout the process.' },
    { type: 'multiple_choice', question: 'What is the first practical step after a major setback?', options: ['Take the smallest meaningful action — one constructive thing today', 'Make a comprehensive recovery plan', 'Ignore it and carry on', 'Wait until you feel better'], correctAnswer: 0, explanation: 'The smallest step breaks paralysis and begins momentum — do not wait for a complete plan.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'How harmful is loneliness to health?', options: ['Mildly inconvenient', 'Only affects mental health', 'Has no measurable health impact', 'Equivalent to smoking 15 cigarettes per day'], correctAnswer: 3, explanation: 'Meta-analysis of 300,000+ people found loneliness as damaging as heavy smoking.' },
    { type: 'multiple_choice', question: 'What matters more — relationship quantity or quality?', options: ['Only professional relationships matter', 'Neither matters', 'Quality — one deeply supportive relationship outweighs a hundred superficial ones', 'Quantity — more connections is always better'], correctAnswer: 2, explanation: 'Relationship quality — trust, reciprocity, emotional safety — is more protective than quantity.' },
    { type: 'multiple_choice', question: 'What characterises assertive (not aggressive) communication?', options: ['Yelling your needs', 'Stating needs clearly without attacking the other person', 'Saying nothing to avoid conflict', 'Manipulating others to get what you want'], correctAnswer: 1, explanation: 'Assertive communication is clear and direct while respecting both parties.' },
    { type: 'multiple_choice', question: 'What makes boundaries effective?', options: ['Being clear, consistent, compassionate, with known consequences', 'Being vague so others can interpret them', 'Only setting them when angry', 'Changing them based on others\' reactions'], correctAnswer: 0, explanation: 'Effective boundaries are specific, consistently enforced, kind in delivery, and backed by consequences.' },
    { type: 'multiple_choice', question: 'How should you approach curating your social environment?', options: ['Only socialise with successful people', 'Ruthlessly cut everyone who is not perfect', 'Isolate yourself for focus', 'Deliberately add growth-supportive connections while managing existing relationships with boundaries'], correctAnswer: 3, explanation: 'The approach is additive — bring in supportive people while setting appropriate boundaries with others.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['Eudaimonic is about physical health', 'No difference', 'Hedonic = pleasure/comfort; Eudaimonic = meaning/purpose/potential', 'Hedonic is better long-term'], correctAnswer: 2, explanation: 'Hedonic seeks pleasure; eudaimonic seeks meaning — research shows eudaimonic produces deeper, lasting satisfaction.' },
    { type: 'multiple_choice', question: 'How are values best identified?', options: ['By what you say matters', 'By what you consistently prioritise when things get difficult', 'By personality tests', 'By what others value'], correctAnswer: 1, explanation: 'True values are revealed by behaviour under pressure, not by stated preferences.' },
    { type: 'multiple_choice', question: 'What is values-based decision-making?', options: ['Asking "which option aligns with my core values?" when facing decisions', 'Always choosing the easiest option', 'Only making decisions when calm', 'Following rules set by others'], correctAnswer: 0, explanation: 'Using your identified core values as a decision framework cuts through analysis paralysis.' },
    { type: 'multiple_choice', question: 'Why does values-aligned living sustain motivation?', options: ['It requires no effort', 'It eliminates all difficulty', 'It does not', 'It creates a sense of coherence — you are acting in line with who you truly are'], correctAnswer: 3, explanation: 'When actions align with deepest values, intrinsic motivation sustains effort far longer than external rewards.' },
    { type: 'multiple_choice', question: 'What is the values clarification "end of life" exercise?', options: ['Planning your funeral', 'A medical assessment', 'Imagining looking back at your life and asking what you want to have been true', 'A legal document'], correctAnswer: 2, explanation: 'This reflection exercise reveals your deepest values by considering what would matter most in retrospect.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is the key difference between coaching and therapy?', options: ['Therapy is for everyone; coaching is for athletes only', 'Coaching helps find answers through questions; therapy treats clinical conditions', 'Coaching is superior', 'No difference'], correctAnswer: 1, explanation: 'Coaching facilitates self-discovery; therapy provides evidence-based treatment for clinical conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Listen 80%, speak 20%', 'Talk 80%, listen 20%', 'Agree with 80% of what is said', 'Use 80% of the session for exercises'], correctAnswer: 0, explanation: 'Effective coaching involves far more listening than speaking.' },
    { type: 'multiple_choice', question: 'What is a "powerful question"?', options: ['A yes/no question', 'A trick question', 'A demanding question', 'An open-ended, non-judgemental question that promotes self-discovery'], correctAnswer: 3, explanation: 'Powerful questions help others find their own answers, which are more impactful than advice.' },
    { type: 'multiple_choice', question: 'When must you refer to professional help?', options: ['Only if they request it', 'Only in emergencies', 'When someone describes persistent low mood, self-harm, panic attacks, or trauma responses', 'Never'], correctAnswer: 2, explanation: 'Clinical symptoms exceed peer coaching scope and require trained professional intervention.' },
    { type: 'multiple_choice', question: 'Why is resisting the urge to give advice important in coaching?', options: ['Advice is always wrong', 'People\'s own discoveries are more powerful and lasting than being told what to do', 'Advice makes you liable', 'You should never help anyone'], correctAnswer: 1, explanation: 'Self-discovered insights create stronger commitment and lasting change than externally given advice.' },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'What does "unbreakable" mean in the course philosophy?', options: ['Having the tools and self-awareness to recover from anything and grow stronger', 'Being physically invincible', 'Never failing', 'Never feeling pain'], correctAnswer: 0, explanation: 'Unbreakable means having resilience systems that enable recovery and growth, not invulnerability.' },
    { type: 'multiple_choice', question: 'What is the ultimate performance metric according to the course?', options: ['Speed of progress', 'Maximum intensity', 'Perfect technique', 'Sustainability — consistency over years'], correctAnswer: 3, explanation: '3x/week for 10 years beats 7x/week for 3 months. Sustainability is the ultimate metric.' },
    { type: 'multiple_choice', question: 'What should a lifelong maintenance plan include?', options: ['Whatever you feel like each day', 'Only training', 'Daily non-negotiables, weekly practices, and periodic reviews', 'Only cold exposure'], correctAnswer: 2, explanation: 'A structured plan with daily, weekly, and periodic elements maintains resilience long-term.' },
    { type: 'multiple_choice', question: 'What is the purpose of deload weeks in mental training?', options: ['They are unnecessary', 'To prevent psychological burnout and maintain long-term sustainability', 'To test maximum capacity', 'To lose progress'], correctAnswer: 1, explanation: 'Deload weeks prevent burnout and allow recovery, ensuring practices remain sustainable.' },
    { type: 'multiple_choice', question: 'Where does resilience ultimately live?', options: ['In the accumulated evidence of who you choose to be, every single day', 'In supplements', 'In genetic potential', 'In textbooks'], correctAnswer: 0, explanation: 'Resilience is demonstrated through daily consistent action, not theoretical knowledge.' },
  ]),
];
