import type { UnitAssessment } from '../types';

export const mindsetL3FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 3 Final Assessment — Advanced Mindset',
  passMarkPercent: 80, pickCount: 20,
  questions: [
    { type: 'multiple_choice', question: 'What feedback mechanism regulates the HPA axis?', options: ['Dopamine activates the pituitary', 'Cortisol feeds back to shut down CRH and ACTH release', 'Serotonin suppresses the adrenals', 'Adrenaline increases CRH'], correctAnswer: 1, explanation: 'Cortisol provides negative feedback to the hypothalamus and pituitary to terminate the stress response.' },
    { type: 'multiple_choice', question: 'What brain change does chronic cortisol cause to the amygdala?', options: ['Shrinks it', 'No effect', 'Improves its function', 'Enlarges it (increasing anxiety)'], correctAnswer: 3, explanation: 'Chronic cortisol enlarges the amygdala, increasing anxiety and threat sensitivity.' },
    { type: 'multiple_choice', question: 'What is hypofrontality in flow state?', options: ['Increased prefrontal activity', 'Temporary partial deactivation of the prefrontal cortex', 'Heightened self-consciousness', 'Complete brain shutdown'], correctAnswer: 1, explanation: 'Hypofrontality silences the inner critic by partially deactivating the prefrontal cortex during flow.' },
    { type: 'multiple_choice', question: 'What minimum BOLT score indicates adequate CO2 tolerance for advanced breathwork?', options: ['15 seconds', '45 seconds', '10 seconds', '25 seconds'], correctAnswer: 3, explanation: 'A BOLT score above 25 indicates sufficient tolerance for more intense protocols.' },
    { type: 'multiple_choice', question: 'How long does the dopamine increase from cold exposure typically last?', options: ['24 hours', '30 minutes', '2–3 hours', '1 week'], correctAnswer: 2, explanation: 'Cold exposure produces a gradual, sustained dopamine increase lasting 2–3 hours.' },
    { type: 'multiple_choice', question: 'What does attention residue mean for gym performance?', options: ['It improves multi-tasking', 'Checking your phone between sets reduces focus for 10–20 minutes', 'It only affects work performance', 'Nothing'], correctAnswer: 1, explanation: 'Attention residue from phone-checking reduces training quality for an extended period.' },
    { type: 'multiple_choice', question: 'Which SDT need does rigid externally imposed programming undermine?', options: ['Relatedness', 'All equally', 'Competence', 'Autonomy'], correctAnswer: 3, explanation: 'Rigid external programmes remove choice, undermining the autonomy need.' },
    { type: 'multiple_choice', question: 'What is the most effective type of goal for daily behaviour?', options: ['Performance goals', 'Outcome goals', 'Process goals', 'Dream goals'], correctAnswer: 2, explanation: 'Process goals (daily actions) are fully controllable and build identity through consistent votes.' },
    { type: 'scenario', scenario: 'Someone trains 7 days a week, does cold plunges daily, and advanced breathwork twice daily. Their sleep is deteriorating and motivation is dropping.', question: 'What is the most likely issue?', options: ['Not training hard enough', 'Their nutrition is wrong', 'Hormetic stress overload without adequate recovery', 'They need more cold exposure'], correctAnswer: 2, explanation: 'Stacking too many stressors without recovery leads to overload — reduce frequency and periodise.' },
    { type: 'multiple_choice', question: 'How does process visualisation differ from outcome visualisation?', options: ['Outcome visualisation primes motor pathways', 'They are the same', 'Process imagines the steps and effort; outcome imagines the end result', 'Process is less effective'], correctAnswer: 2, explanation: 'Process visualisation primes the neural pathways for execution; outcome visualisation sets direction.' },
    { type: 'multiple_choice', question: 'What is the single strongest predictor of happiness and longevity?', options: ['Social connection quality', 'Physical fitness', 'Career success', 'Income'], correctAnswer: 0, explanation: 'Quality social connection is the strongest predictor of both happiness and longevity.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional mental health support?', options: ['Only if they ask', 'Only in emergencies', 'Never — you can handle everything', 'When symptoms persist for 2+ weeks and impair daily functioning'], correctAnswer: 3, explanation: 'Persistent symptoms impairing daily life exceed peer coaching scope and require professional intervention.' },
    { type: 'multiple_choice', question: 'What makes identified motivation more resilient than external motivation?', options: ['It connects to personal values rather than external rewards', 'It requires no effort', 'It is always enjoyable', 'It is driven by guilt'], correctAnswer: 0, explanation: 'Identified motivation is resilient because it connects behaviour to personal values and identity.' },
    { type: 'multiple_choice', question: 'What percentage of daily energy does the brain consume?', options: ['20%', '10%', '50%', '5%'], correctAnswer: 0, explanation: 'The brain uses approximately 20% of total body energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the most important factor for long-term brain health?', options: ['Brain training games', 'Caffeine', 'Supplements', 'Sleep'], correctAnswer: 3, explanation: 'Sleep enables glymphatic clearance, memory consolidation, and neural repair — irreplaceable for brain health.' },
    { type: 'scenario', scenario: 'A training partner asks you to help them "find their motivation." They feel stuck but have no clinical symptoms.', question: 'What approach aligns with motivation science?', options: ['Give them a motivational speech', 'Suggest they take a month off', 'Help them identify their values and design systems that reduce reliance on willpower', 'Tell them to wait until they feel motivated'], correctAnswer: 2, explanation: 'Values-based systems and environmental design create sustainable motivation without relying on feelings.' },
    { type: 'multiple_choice', question: 'What does the Unbreakable Philosophy ultimately emphasise?', options: ['Being better than everyone else', 'Consistent, values-aligned living with tools for recovery', 'Training every day without rest', 'Never showing weakness'], correctAnswer: 1, explanation: 'Being unbreakable means having the knowledge and tools to recover and grow — consistently, not perfectly.' },
    { type: 'multiple_choice', question: 'What is the key difference between assertive and aggressive boundary-setting?', options: ['No difference', 'Assertive states needs clearly without attacking; aggressive attacks the person', 'Aggressive is more effective', 'Assertive is passive'], correctAnswer: 1, explanation: 'Assertive communication protects the relationship while setting clear limits; aggression damages it.' },
    { type: 'multiple_choice', question: 'What is the recommended approach for mental training deload weeks?', options: ['Stop all practices entirely', 'Only deload if injured', 'Reduce intensity, extend sleep, focus on enjoyment every 4–6 weeks', 'Increase intensity'], correctAnswer: 2, explanation: 'Periodic deloads prevent psychological burnout and maintain long-term practice sustainability.' },
    { type: 'multiple_choice', question: 'According to growth mindset research, what characterises the most resilient approach to failure?', options: ['Viewing failure as information and an opportunity for learning', 'Viewing failure as evidence of fixed limitations', 'Ignoring failure completely', 'Avoiding failure at all costs'], correctAnswer: 0, explanation: 'Growth mindset treats failure as feedback — data for adjustment, not evidence of inability.' },
    { type: 'scenario', scenario: 'You have completed both Level 2 and Level 3 Mindset courses. A friend asks what the single most important takeaway is.', question: 'Which answer best captures the course philosophy?', options: ['Learn to never feel stressed', 'Knowledge is enough — no practice needed', 'Avoid all discomfort', 'Build systems and practices that make resilience automatic, then apply them consistently'], correctAnswer: 3, explanation: 'The course teaches that resilience is built through consistent practice of evidence-based systems — not perfection.' },
  ],
};
