import type { UnitAssessment } from '../types';

export const mindsetL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Advanced Focus, Discipline & Cognitive Performance',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is attention residue?', options: ['Leftover attention from sleep', 'Cognitive cost of task-switching — part of your focus remains on the previous task', 'Attention deficit disorder', 'A type of meditation'], correctAnswer: 1, explanation: 'Attention residue means part of your cognitive focus remains on the previous task after switching.' },
    { type: 'multiple_choice', question: 'How many hours of genuine deep work can most people sustain per day?', options: ['3–4 hours', '1–2 hours', '10+ hours', '6–8 hours'], correctAnswer: 0, explanation: 'Research suggests most people can sustain 3–4 hours of truly deep cognitive work daily.' },
    { type: 'multiple_choice', question: 'What does the ego depletion model propose?', options: ['Ego has no effect on decisions', 'Willpower is unlimited', 'The ego grows with use', 'Willpower is a finite resource that gets depleted'], correctAnswer: 3, explanation: 'Baumeister\'s model proposed willpower is a depletable resource, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is the most effective solution to decision fatigue?', options: ['Making more decisions to build stamina', 'Drinking coffee', 'Designing systems that eliminate unnecessary decisions', 'Sleeping more'], correctAnswer: 2, explanation: 'Systems and pre-commitment remove the need for decisions, preserving cognitive resources.' },
    { type: 'multiple_choice', question: 'What does BDNF stand for and why is it important?', options: ['Basic Daily Nutritional Formula', 'Brain-Derived Neurotrophic Factor — supports neuron growth and plasticity', 'Body-Dependent Nutritional Factor', 'Brain-Disrupting Neural Function'], correctAnswer: 1, explanation: 'BDNF supports neuronal growth, survival, and synaptic plasticity — critical for learning and brain health.' },
    { type: 'multiple_choice', question: 'What clears metabolic waste from the brain during sleep?', options: ['The glymphatic system', 'Blood circulation', 'The lymphatic system', 'Cerebrospinal breathing'], correctAnswer: 0, explanation: 'The glymphatic system is 10x more active during sleep, clearing amyloid-beta and other waste.' },
    { type: 'multiple_choice', question: 'What are the three basic psychological needs in Self-Determination Theory?', options: ['Physical, emotional, spiritual', 'Food, shelter, safety', 'Power, achievement, affiliation', 'Autonomy, competence, relatedness'], correctAnswer: 3, explanation: 'Deci and Ryan identified autonomy, competence, and relatedness as essential for intrinsic motivation.' },
    { type: 'multiple_choice', question: 'According to James Clear, what is the most effective layer to start behaviour change?', options: ['Outcomes', 'Environment', 'Identity', 'Processes'], correctAnswer: 2, explanation: 'Starting with identity ("I am someone who...") creates lasting change because behaviour follows belief.' },
    { type: 'multiple_choice', question: 'What type of visualisation is most effective for performance?', options: ['Not visualising at all', 'Process visualisation combined with brief outcome visualisation', 'Outcome visualisation only', 'Visualising relaxation'], correctAnswer: 1, explanation: 'Process visualisation primes neural pathways; brief outcome visualisation sets direction.' },
    { type: 'scenario', scenario: 'An athlete keeps saying "I just need to find my motivation" before training.', question: 'What does motivation science suggest?', options: ['Action precedes motivation — start training and motivation follows', 'They should wait until motivation arrives', 'They need a new programme', 'They should take a month off'], correctAnswer: 0, explanation: 'Motivation follows action, not the other way around. Starting creates the motivation to continue.' },
    { type: 'multiple_choice', question: 'What does creatine supplementation improve cognitively?', options: ['Nothing — it only affects muscles', 'Long-term memory only', 'Emotional regulation', 'Short-term memory and reasoning, especially under stress or sleep deprivation'], correctAnswer: 3, explanation: 'Creatine has cognitive benefits for short-term memory and reasoning, particularly when cognitively stressed.' },
    { type: 'multiple_choice', question: 'What is the motivation spectrum in SDT from least to most self-determined?', options: ['Passive → active', 'Low energy → high energy', 'Amotivation → external → introjected → identified → integrated → intrinsic', 'Intrinsic → extrinsic'], correctAnswer: 2, explanation: 'SDT describes a continuum from amotivation through external regulation to intrinsic motivation.' },
  ],
};
