import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What hormone does the hypothalamus release to start the HPA cascade?', options: ['CRH (corticotropin-releasing hormone)', 'Cortisol', 'ACTH', 'Adrenaline'], correctAnswer: 0, explanation: 'CRH from the hypothalamus triggers the pituitary to release ACTH.' },
    { type: 'multiple_choice', question: 'What is eustress?', options: ['Positive stress that drives adaptation and growth', 'Chronic damaging stress', 'Stress you cannot control', 'Stress from exercise only'], correctAnswer: 0, explanation: 'Eustress is beneficial stress that is short-duration and within coping capacity.' },
    { type: 'multiple_choice', question: 'What does chronic cortisol do to the prefrontal cortex?', options: ['Has no effect', 'Makes it larger', 'Enhances it', 'Disrupts it, reducing decision-making and impulse control'], correctAnswer: 3, explanation: 'Chronic cortisol impairs prefrontal function, reducing rational decision-making capacity.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['Cumulative physiological damage from chronic stress', 'A type of training', 'A breathing technique', 'Maximum weight you can lift'], correctAnswer: 0, explanation: 'Allostatic load is the total wear and tear from sustained stress on body systems.' },
    { type: 'multiple_choice', question: 'Can the same stressor be both eustress and distress?', options: ['Yes, depending on perception and recovery state', 'Only physical stressors', 'No, stressors are always one or the other', 'Only psychological stressors'], correctAnswer: 0, explanation: 'Perception and recovery capacity determine whether a stressor is beneficial or harmful.' },
    { type: 'multiple_choice', question: 'What metabolic effect does chronic cortisol promote?', options: ['Improved digestion', 'Muscle growth', 'Insulin resistance and visceral fat storage', 'Fat loss'], correctAnswer: 2, explanation: 'Sustained cortisol promotes insulin resistance and preferential abdominal fat deposition.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Avoiding stressful situations', 'Ignoring your emotions', 'Suppressing feelings', 'Deliberately reinterpreting a situation to change your emotional response'], correctAnswer: 3, explanation: 'Reappraisal changes the meaning of a situation, altering the emotion at its source.' },
    { type: 'multiple_choice', question: 'What brain effect does affect labelling produce?', options: ['Increases amygdala activity', 'No measurable effect', 'Reduces amygdala activity by recruiting prefrontal cortex', 'Activates fight-or-flight'], correctAnswer: 2, explanation: 'Naming emotions engages the prefrontal cortex, which dampens amygdala reactivity.' },
    { type: 'multiple_choice', question: 'What does TIPP stand for in distress tolerance?', options: ['Train, Improve, Persist, Perform', 'Temperature, Intense exercise, Paced breathing, Progressive relaxation', 'Time, Intention, Practice, Patience', 'Think, Imagine, Plan, Proceed'], correctAnswer: 1, explanation: 'TIPP uses physiological interventions to change body state and therefore emotional state.' },
    { type: 'multiple_choice', question: 'What is third-person affect labelling?', options: ['Labelling emotions in a group', 'Talking about someone else', 'Writing emotions anonymously', 'Referring to yourself by name for additional psychological distance'], correctAnswer: 3, explanation: 'Using your own name creates psychological distance that enhances emotional regulation.' },
    { type: 'multiple_choice', question: 'How does suppression compare to reappraisal long-term?', options: ['They are equally effective', 'Suppression is better', 'Reappraisal produces better outcomes with less physiological cost', 'Neither is effective'], correctAnswer: 2, explanation: 'Suppression requires ongoing effort and does not reduce the underlying emotion; reappraisal does.' },
    { type: 'multiple_choice', question: 'Which form of labelling produces the strongest regulation?', options: ['Saying "I feel bad"', 'Written detailed labelling through journaling', 'Talking to no one', 'Thinking silently'], correctAnswer: 1, explanation: 'Written labelling forces precise articulation, producing the strongest and most lasting regulatory effect.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Who coined the concept of "flow state"?', options: ['Carl Jung', 'B.F. Skinner', 'Mihaly Csikszentmihalyi', 'Sigmund Freud'], correctAnswer: 2, explanation: 'Csikszentmihalyi described and researched flow as a state of complete absorption.' },
    { type: 'multiple_choice', question: 'What happens to the prefrontal cortex during flow?', options: ['It shuts down completely', 'It partially deactivates (hypofrontality)', 'No change occurs', 'It becomes hyperactive'], correctAnswer: 1, explanation: 'Temporary hypofrontality silences the inner critic, allowing implicit systems to drive performance.' },
    { type: 'multiple_choice', question: 'How much can flow increase productivity?', options: ['50–100%', 'No measurable increase', '200–500%', '10–20%'], correctAnswer: 2, explanation: 'Research suggests flow can increase productivity by 200–500%.' },
    { type: 'multiple_choice', question: 'What is the minimum uninterrupted focus time to enter flow?', options: ['5 minutes', '10 minutes', '20 minutes', '60 minutes'], correctAnswer: 2, explanation: 'Most people need at least 20 minutes of uninterrupted focus before flow state becomes possible.' },
    { type: 'multiple_choice', question: 'What comes before the flow state in the flow cycle?', options: ['Relaxation', 'Recovery', 'Sleep', 'The struggle phase'], correctAnswer: 3, explanation: 'The struggle phase (difficulty and frustration) precedes the release into flow.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'How is trauma defined in this context?', options: ['By how the nervous system responded and whether the response became stuck', 'Any negative experience', 'Only severe physical injury', 'Only childhood events'], correctAnswer: 0, explanation: 'Trauma is defined by the nervous system response, not the severity of the event itself.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Appreciation, relationships, personal strength, new possibilities, existential clarity', 'Physical recovery, mental clarity, emotional balance, social skills, career success', 'Speed, strength, flexibility, endurance, coordination', 'Acceptance, anger, denial, bargaining, depression'], correctAnswer: 0, explanation: 'PTG manifests as greater appreciation, deeper relationships, personal strength, new possibilities, and existential understanding.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional help?', options: ['Only in life-threatening situations', 'When daily functioning is significantly impaired for more than two weeks', 'Only if they ask', 'Never — peer support is always sufficient'], correctAnswer: 1, explanation: 'Persistent functional impairment exceeds peer coaching scope and requires professional intervention.' },
    { type: 'multiple_choice', question: 'Does PTG mean trauma was necessary for growth?', options: ['No — it means growth can emerge from the struggle, not that trauma was beneficial', 'Only for some people', 'Yes', 'PTG is not real'], correctAnswer: 0, explanation: 'PTG does not justify trauma — it acknowledges that growth can emerge from adversity under the right conditions.' },
    { type: 'multiple_choice', question: 'What brain change occurs with PTSD?', options: ['No structural changes', 'Improved memory', 'Enhanced emotional regulation', 'Overactive amygdala, suppressed prefrontal cortex, hippocampal processing issues'], correctAnswer: 3, explanation: 'PTSD involves an overactive threat system, reduced rational processing, and unprocessed traumatic memories.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What is the strongest source of self-efficacy?', options: ['Verbal persuasion', 'Mastery experience', 'Reading about success', 'Vicarious experience'], correctAnswer: 1, explanation: 'Actually succeeding at progressively harder challenges provides the most powerful evidence of capability.' },
    { type: 'multiple_choice', question: 'What is the T/C ratio related to?', options: ['Testosterone/Cortisol ratio correlating with behavioural confidence', 'Training/Competition split', 'Training/Coaching balance', 'Time/Cost efficiency'], correctAnswer: 0, explanation: 'The testosterone-to-cortisol ratio correlates with assertiveness and behavioural confidence.' },
    { type: 'multiple_choice', question: 'How does avoidance affect confidence?', options: ['It reinforces the belief that you cannot handle the situation', 'It protects confidence', 'It builds confidence over time', 'It has no effect'], correctAnswer: 0, explanation: 'Every avoidance strengthens the fear and weakens self-efficacy.' },
    { type: 'multiple_choice', question: 'What is the confidence exposure ladder?', options: ['A gym exercise', 'A ranked list of feared situations to work through progressively', 'A breathing technique', 'A supplement protocol'], correctAnswer: 1, explanation: 'The exposure ladder ranks situations from mildly uncomfortable to genuinely frightening for progressive desensitisation.' },
    { type: 'multiple_choice', question: 'What distinguishes genuine self-efficacy from performative confidence?', options: ['Self-efficacy is built through progressive competence; performative confidence collapses under pressure', 'Self-efficacy requires no experience', 'Performative confidence is stronger', 'They are identical'], correctAnswer: 0, explanation: 'Genuine self-efficacy is evidence-based; performative confidence lacks substance and fails when tested.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What are the three polyvagal states?', options: ['Ventral vagal, sympathetic, dorsal vagal', 'Alert, relaxed, asleep', 'Fight, flight, freeze', 'Happy, sad, angry'], correctAnswer: 0, explanation: 'Polyvagal theory describes safety (ventral vagal), mobilisation (sympathetic), and shutdown (dorsal vagal).' },
    { type: 'multiple_choice', question: 'What is the ventral vagal state associated with?', options: ['Numbness and shutdown', 'Social engagement, safety, and calm', 'Panic', 'Fight or flight'], correctAnswer: 1, explanation: 'Ventral vagal is the state of safety — connection, calm, and complex cognitive function.' },
    { type: 'multiple_choice', question: 'What works best for shifting out of dorsal vagal shutdown?', options: ['Caffeine', 'Forcing yourself to socialise', 'Intense breathwork', 'Gentle movement and orienting to the environment'], correctAnswer: 3, explanation: 'In shutdown, gentle stimulation (movement, sensory awareness) helps shift toward mobilisation before safety.' },
    { type: 'multiple_choice', question: 'What does co-regulation mean?', options: ['Using connection with another person\', 'Exercising with a partner', 'Regulating your own emotions', ', '], correctAnswer: 0, explanation: 'Co-regulation uses social connection — a calm voice, presence — to help regulate your own nervous system.' },
    { type: 'multiple_choice', question: 'Can you be in mixed autonomic states?', options: ['Yes — you can be sympathetically activated while partially in dorsal vagal', 'No, only one state at a time', 'Only during sleep', 'Only during exercise'], correctAnswer: 0, explanation: 'Mixed states are common — you can feel anxious (sympathetic) and helpless (dorsal vagal) simultaneously.' },
  ]),
];

// Unit 2 — Advanced Breathing & Exposure Science
