import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What happens to blood pH during cyclic hyperventilation?', options: ['It fluctuates unpredictably', 'It stays the same', 'It increases (respiratory alkalosis)', 'It decreases (more acidic)'], correctAnswer: 2, explanation: 'Blowing off CO2 raises blood pH, creating respiratory alkalosis.' },
    { type: 'multiple_choice', question: 'What is a CO2 table?', options: ['Repeated breath holds with decreasing rest intervals', 'A breathing speed test', 'A carbon dioxide detector', 'A nutrition reference chart'], correctAnswer: 0, explanation: 'CO2 tables progressively challenge your tolerance by reducing rest between holds.' },
    { type: 'multiple_choice', question: 'What breathing rate typically achieves resonance frequency?', options: ['20+ breaths/min', '4.5–7 breaths/min', '1 breath/min', '12–15 breaths/min'], correctAnswer: 1, explanation: "Most people\'s resonance frequency falls between 4.5 and 7 breaths per minute." },
    { type: 'multiple_choice', question: 'What does improved CO2 tolerance correlate with?', options: ['Reduced anxiety and better performance under pressure', 'Higher blood pressure', 'Increased breathing rate', 'Lower oxygen levels'], correctAnswer: 0, explanation: 'Better CO2 tolerance means a less reactive respiratory drive, directly reducing anxiety symptoms.' },
    { type: 'multiple_choice', question: 'What is the benefit of the breath hold after hyperventilation rounds?', options: ['It creates a powerful sympathetic-to-parasympathetic transition', 'It increases CO2 only', 'It builds lung capacity', 'It has no specific benefit'], correctAnswer: 0, explanation: 'The recovery phase after holds triggers a strong parasympathetic shift, enhancing vagal tone.' },
    { type: 'multiple_choice', question: 'What is the physiological sigh and when is it most effective?', options: ['A deep sigh of frustration', 'A double inhale through the nose followed by an extended exhale — the fastest known way to reduce real-time stress', 'A yawn', 'A cough'], correctAnswer: 1, explanation: 'The physiological sigh (double nasal inhale + extended exhale) reinflates collapsed lung alveoli and maximises CO2 expulsion — reducing arousal within one breath cycle.' },
    { type: 'multiple_choice', question: 'How does cyclic hyperventilation differ from panic hyperventilation?', options: ['There is no difference', 'Cyclic hyperventilation is deliberate and controlled; panic hyperventilation is involuntary and escalating', 'Panic hyperventilation is beneficial', 'Cyclic hyperventilation is dangerous'], correctAnswer: 1, explanation: 'Deliberate hyperventilation (Unbreakable Breathwork, Tummo) is controlled and time-limited with a clear purpose; panic hyperventilation is involuntary and self-reinforcing.' },
    { type: 'multiple_choice', question: 'What is CO2 tolerance training?', options: ['Holding your breath until you pass out', 'Deliberately extending breath holds and slowing breathing to increase comfort with elevated CO2 levels', 'Breathing pure CO2', 'Hyperventilating regularly'], correctAnswer: 1, explanation: 'CO2 tolerance training gradually extends comfortable breath-hold times, improving breathing efficiency and reducing the panic reflex during exertion.' },
    { type: 'multiple_choice', question: 'What is the difference between parasympathetic and sympathetic breathwork?', options: ['There is no difference — all breathing is the same', 'Parasympathetic uses slow exhale-dominant patterns for calming; sympathetic uses rapid inhale-dominant patterns for activation', 'Only one type exists', 'The difference is imaginary'], correctAnswer: 1, explanation: 'Extended exhales activate the parasympathetic brake; rapid, powerful inhales activate the sympathetic accelerator — different tools for different states.' },
    { type: 'multiple_choice', question: 'Why should advanced breathwork be periodised like physical training?', options: ['It should not be', 'The nervous system adapts — variety and progression prevent plateau and maintain development', 'Only beginners need periodisation', 'Periodisation reduces effectiveness'], correctAnswer: 1, explanation: 'Like physical training, the nervous system adapts to repeated stimuli — periodising breathwork (changing protocols, increasing intensity) drives continued adaptation.' },
  
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What triggers the cold shock response?', options: ['Cutaneous cold receptors signalling the sympathetic nervous system', 'Low body temperature', 'Brain temperature drop', 'Muscle cooling'], correctAnswer: 0, explanation: 'Skin cold receptors trigger the involuntary sympathetic response upon cold contact.' },
    { type: 'multiple_choice', question: 'How long does the cold shock response typically last?', options: ['5–10 seconds', '5 minutes', '30 minutes', '30–60 seconds'], correctAnswer: 3, explanation: 'The cold shock response is most intense in the first 30–60 seconds and diminishes with habituation.' },
    { type: 'multiple_choice', question: 'What does cold exposure do to noradrenaline?', options: ['No effect', 'Decreases it', 'Increases it by 10%', 'Increases it by 200–300%'], correctAnswer: 3, explanation: 'Cold exposure significantly increases noradrenaline, improving alertness, focus, and mood.' },
    { type: 'multiple_choice', question: 'What is brown adipose tissue (BAT)?', options: ['A type of muscle', 'Metabolically active fat that generates heat by burning calories', 'Scar tissue', 'Unhealthy body fat'], correctAnswer: 1, explanation: 'BAT produces heat through thermogenesis, activated by cold exposure.' },
    { type: 'multiple_choice', question: 'What is the primary psychological benefit of cold exposure?', options: ['Weight loss', 'Better skin', 'Proving you can choose discomfort and handle it — transferable mental toughness', 'Improved flexibility'], correctAnswer: 2, explanation: 'Choosing voluntary discomfort builds the psychological habit of doing hard things.' },
    { type: 'multiple_choice', question: 'What is cold shock response?', options: ['Feeling cold', 'The involuntary gasp, hyperventilation, and cardiovascular changes that occur upon sudden cold immersion', 'A type of hypothermia', 'Shivering'], correctAnswer: 1, explanation: 'Cold shock response includes involuntary gasping, hyperventilation, and rapid heart rate increase — this is where most cold water drownings actually occur, not from hypothermia.' },
    { type: 'multiple_choice', question: 'How does repeated cold exposure change the cold shock response?', options: ['It gets worse each time', 'The response diminishes — habituation reduces the initial gasp and cardiovascular spike', 'It stays the same', 'It disappears completely after one exposure'], correctAnswer: 1, explanation: 'Cold habituation reduces the cold shock response over 5–6 exposures — your body learns to manage the initial shock more calmly.' },
    { type: 'multiple_choice', question: 'What is brown adipose tissue (BAT) and how does cold activate it?', options: ['A type of muscle', 'Metabolically active fat that generates heat by burning calories — activated and increased by cold exposure', 'A skin condition', 'A type of blood vessel'], correctAnswer: 1, explanation: 'Brown fat generates heat through non-shivering thermogenesis — regular cold exposure increases BAT volume and activity, improving metabolic function.' },
    { type: 'multiple_choice', question: 'Why should cold exposure timing matter for training adaptations?', options: ['Timing is irrelevant', 'Cold immediately after strength training may blunt the inflammatory signalling needed for muscle adaptation', 'Cold before training improves performance', 'Cold is always beneficial regardless of timing'], correctAnswer: 1, explanation: 'Post-training inflammation drives adaptation — cold water immersion immediately after strength training may suppress this beneficial inflammation.' },
    { type: 'multiple_choice', question: 'What is the minimum effective dose for cold exposure benefits?', options: ['30 minutes in ice', '11 minutes total per week spread across 2–4 sessions', '1 hour daily', '5 minutes once a month'], correctAnswer: 1, explanation: 'Research suggests approximately 11 minutes of cold exposure per week (spread across several sessions) provides most of the neurochemical and metabolic benefits.' },
  
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What cardiovascular response does sauna use create?', options: ['No cardiovascular effect', 'Heart rate increases to 100–150 bpm with vasodilation', 'Blood pressure increases sharply and stays elevated', 'Heart rate decreases'], correctAnswer: 1, explanation: 'Heat exposure creates cardiovascular stress similar to moderate exercise.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Proteins that cause overheating', 'Digestive enzymes', 'Molecular chaperones that repair proteins and protect cells', 'Proteins destroyed by heat'], correctAnswer: 2, explanation: 'HSPs repair damaged proteins and increase cellular resilience to all forms of stress.' },
    { type: 'multiple_choice', question: 'By how much can sauna increase growth hormone acutely?', options: ['200–300%', '50%', '10–20%', '1000%'], correctAnswer: 0, explanation: 'Studies show up to 200–300% acute growth hormone increase with 20-minute sauna sessions.' },
    { type: 'multiple_choice', question: 'What is contrast therapy?', options: ['Alternating heat and cold exposure for amplified benefits', 'Using light and dark rooms', 'Comparing two training programmes', 'Training at different intensities'], correctAnswer: 0, explanation: 'Contrast therapy combines heat and cold to enhance vascular, hormonal, and neurological benefits.' },
    { type: 'multiple_choice', question: 'How much sweat can be lost in a single sauna session?', options: ['A few millilitres', '3–5 litres', '0.5–1 litre', '10 litres'], correctAnswer: 2, explanation: 'Significant fluid loss (0.5–1L per session) makes hydration before and after essential.' },
    { type: 'multiple_choice', question: 'What cardiovascular benefits does regular sauna use provide?', options: ['None', 'Increased heart rate, improved blood vessel function, and reduced cardiovascular disease risk', 'It only relaxes muscles', 'It dehydrates you'], correctAnswer: 1, explanation: 'Regular sauna use mimics moderate cardiovascular exercise — increasing heart rate, improving endothelial function, and reducing cardiovascular mortality by up to 40%.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Proteins that cause heat stroke', 'Protective proteins produced during heat stress that repair damaged proteins and protect cells', 'A type of supplement', 'Proteins in hot food'], correctAnswer: 1, explanation: 'Heat shock proteins (HSPs) are cellular repair mechanisms activated by heat stress — they protect against protein damage and may have anti-ageing effects.' },
    { type: 'multiple_choice', question: 'What is the recommended sauna protocol for health benefits?', options: ['5 minutes once a month', '15–20 minutes at 80–100°C, 2–4 times per week', '1 hour daily', '30 seconds at maximum heat'], correctAnswer: 1, explanation: 'Research shows 15–20 minutes at 80–100°C, performed 2–4 times per week, provides optimal cardiovascular, immune, and mood benefits.' },
    { type: 'multiple_choice', question: 'How does sauna use affect growth hormone release?', options: ['It has no effect', 'Heat stress can increase growth hormone release by up to 200–300%', 'It decreases growth hormone', 'Only in the elderly'], correctAnswer: 1, explanation: 'Deliberate heat exposure triggers significant growth hormone release — particularly with multiple sauna sessions in a single day.' },
    { type: 'multiple_choice', question: 'What is the main safety consideration for sauna use?', options: ['There are no risks', 'Hydration — significant fluid and electrolyte loss requires replacement before, during, and after', 'It causes skin damage', 'It weakens bones'], correctAnswer: 1, explanation: 'Sauna causes significant sweating — adequate hydration with electrolytes is essential to prevent dehydration and electrolyte imbalance.' },
  
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['Higher arousal always means better performance', 'The relationship between sleep and memory', 'Rest is always optimal', 'Performance peaks at moderate arousal; declines at both extremes'], correctAnswer: 3, explanation: 'The inverted-U shows optimal performance at moderate arousal, with decline at under- and over-arousal.' },
    { type: 'multiple_choice', question: 'What breathing is best before a heavy lift?', options: ['Short sharp breaths to increase sympathetic activation', 'Extended exhale to calm down', 'Holding breath for 2 minutes', 'Hyperventilation for 5 minutes'], correctAnswer: 0, explanation: 'Power events benefit from moderate sympathetic activation to increase force readiness.' },
    { type: 'multiple_choice', question: 'When should you exhale during a precision task?', options: ['At the moment of execution', 'During the preparation phase', 'After completing the action', 'It does not matter'], correctAnswer: 0, explanation: 'Exhale at execution (e.g., releasing an arrow) provides maximum stability and calm.' },
    { type: 'multiple_choice', question: 'What is tactical breathing?', options: ['Breathing only through one nostril', 'Breathing as fast as possible', '4-count inhale, 4-count hold, 4-count exhale, 4-count hold', 'Not breathing during performance'], correctAnswer: 2, explanation: 'Tactical breathing (box breathing) manages anxiety during competition breaks and transitions.' },
    { type: 'multiple_choice', question: 'How can post-performance breathing reduce heart rate recovery time?', options: ['It cannot', 'Only cold water helps', 'Only medication works', 'Slow nasal breathing (4 in, 8 out) can reduce recovery time by 30%'], correctAnswer: 3, explanation: 'Deliberate parasympathetic breathing accelerates cardiovascular recovery after intense performance.' },
    { type: 'multiple_choice', question: 'How should breathing change during heavy resistance training?', options: ['Hold your breath the entire set', 'Exhale during the concentric (effort) phase and inhale during the eccentric (lowering) phase', 'Breathe as fast as possible', 'Breathing does not matter during lifting'], correctAnswer: 1, explanation: 'The standard pattern is exhale during effort (concentric) and inhale during the easier phase (eccentric) — maintaining intra-abdominal pressure while preventing excessive blood pressure spikes.' },
    { type: 'multiple_choice', question: 'What is the Valsalva manoeuvre and when is it appropriate?', options: ['A breathing exercise for relaxation', 'A forced exhale against a closed airway to maximise intra-abdominal pressure — used during maximal lifts', 'A warm-up technique', 'A cooling down technique'], correctAnswer: 1, explanation: 'The Valsalva manoeuvre creates maximum trunk stability during heavy lifts — but should only be used by experienced lifters on near-maximal attempts.' },
    { type: 'multiple_choice', question: 'What breathing pattern is optimal for endurance performance?', options: ['Mouth breathing at all intensities', 'Nasal breathing at low-moderate intensity, transitioning to mouth as intensity increases', 'Holding your breath', 'Random breathing'], correctAnswer: 1, explanation: 'Nasal breathing at low-moderate intensity maximises efficiency; mouth breathing supplements at higher intensities when oxygen demand exceeds nasal capacity.' },
    { type: 'multiple_choice', question: 'What is pre-competition breathing strategy?', options: ['Hyperventilate to maximise oxygen', 'Use calming breathwork (box breathing) to manage arousal, then short activation breathing before start', 'Hold your breath', 'Breathe normally — no strategy needed'], correctAnswer: 1, explanation: 'Pre-competition breathing manages the arousal curve — calming techniques to prevent over-arousal, followed by short activation breathing to reach optimal performance state.' },
    { type: 'multiple_choice', question: 'What is inter-set breathing?', options: ['Breathing between sets to optimise recovery and manage fatigue', 'Holding your breath between sets', 'A type of sprint training', 'Breathing only during rest'], correctAnswer: 0, explanation: 'Deliberate inter-set breathing (slow nasal exhales) accelerates recovery between sets by promoting parasympathetic activation and faster heart rate recovery.' },
  
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['A disease process', 'Damage from excessive stress', 'Beneficial adaptation from controlled low-to-moderate stress', 'A type of hormone'], correctAnswer: 2, explanation: 'Hormesis describes how moderate stressors trigger positive adaptive responses.' },
    { type: 'multiple_choice', question: 'By how much can contrast therapy reduce DOMS?', options: ['50–70%', '20–30%', '100%', '5%'], correctAnswer: 1, explanation: 'Studies show contrast therapy can reduce delayed-onset muscle soreness by 20–30%.' },
    { type: 'multiple_choice', question: 'What signs indicate hormetic stress overload?', options: ['No signs — overload is not possible', 'Better performance', 'Deteriorating sleep, dropping motivation, rising resting heart rate', 'Increased energy and motivation'], correctAnswer: 2, explanation: 'Sleep disruption, motivational decline, and elevated resting HR indicate too much stress without recovery.' },
    { type: 'multiple_choice', question: 'How should you end a contrast therapy session for alertness?', options: ['Order does not matter', 'On cold', 'On a warm-up', 'On heat'], correctAnswer: 1, explanation: 'Ending on cold promotes alertness through noradrenaline and dopamine elevation.' },
    { type: 'multiple_choice', question: 'How often should you include a full rest day from exposure stressors?', options: ['Never', 'Only when injured', 'At least one per week', 'Once per month'], correctAnswer: 2, explanation: 'Minimum one full rest day per week prevents cumulative stress overload.' },
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['A disease', 'The principle that small doses of stress produce beneficial adaptations, while large doses are harmful', 'A type of hormone', 'An exercise technique'], correctAnswer: 1, explanation: 'Hormesis explains why controlled stress (exercise, cold, heat, fasting) triggers beneficial adaptations — the dose makes the poison.' },
    { type: 'multiple_choice', question: 'What is contrast therapy?', options: ['Comparing two exercises', 'Alternating between hot (sauna/hot water) and cold (cold water) exposure to challenge the cardiovascular system', 'A type of stretching', 'A visual training method'], correctAnswer: 1, explanation: 'Contrast therapy alternates vasodilation (heat) and vasoconstriction (cold) — training cardiovascular flexibility and accelerating recovery.' },
    { type: 'multiple_choice', question: 'What is the recommended contrast therapy protocol?', options: ['30 seconds each, once', '3–5 rounds of 3–5 minutes hot followed by 1–2 minutes cold, ending on cold', '1 hour hot only', 'Cold only, no heat'], correctAnswer: 1, explanation: 'Standard protocol: 3–5 rounds of hot (3–5 min) then cold (1–2 min), always ending on cold to leave the nervous system in a sympathetic-activated state.' },
    { type: 'multiple_choice', question: 'Why should you end contrast therapy on cold rather than hot?', options: ['Personal preference only', 'Cold activates the sympathetic system, producing sustained alertness and elevated mood through noradrenaline', 'Hot is better to end on', 'It does not matter'], correctAnswer: 1, explanation: 'Ending on cold triggers noradrenaline and dopamine release, producing sustained alertness and elevated mood — ending on hot promotes sleepiness.' },
    { type: 'multiple_choice', question: 'What is the hormetic dose-response curve?', options: ['More stress is always better', 'Low doses of stress produce positive adaptations; beyond the optimal dose, benefits decrease and harm increases', 'All stress is equally beneficial', 'Stress never produces benefits'], correctAnswer: 1, explanation: 'The hormetic curve shows an inverted-U — too little stress produces no adaptation, optimal stress produces maximum benefit, and excessive stress causes damage.' },
  
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'Why does the air at altitude contain fewer oxygen molecules per breath despite the same percentage of oxygen?', options: ['Oxygen percentage decreases at altitude', 'Reduced atmospheric pressure means fewer molecules per breath', 'There is more CO2 at altitude', 'Wind removes oxygen from the air'], correctAnswer: 1, explanation: 'At altitude the air still contains 20.9% oxygen, but reduced atmospheric pressure means each breath delivers fewer total molecules of oxygen to the lungs.' },
    { type: 'multiple_choice', question: 'What hormone increases during chronic altitude exposure to boost red blood cell production?', options: ['Testosterone', 'Cortisol', 'Erythropoietin (EPO)', 'Growth hormone'], correctAnswer: 2, explanation: 'Erythropoietin (EPO) is produced by the kidneys in response to hypoxia and stimulates the bone marrow to produce more red blood cells, increasing oxygen-carrying capacity.' },
    { type: 'multiple_choice', question: 'What is the "Live High / Train Low" method?', options: ['Living at sea level and training in the mountains', 'Living at altitude to trigger adaptations while training at low altitude to maintain intensity', 'Training at altitude only during competitions', 'Living and training at the same altitude'], correctAnswer: 1, explanation: 'The LHTL method combines chronic altitude exposure (living at 2,000-2,500m) for physiological adaptations with low-altitude training to maintain high exercise intensity.' },
    { type: 'scenario', question: 'What adaptation is most likely responsible for this improvement?', scenario: 'After 6 weeks of regular breath-hold walking, a person notices their step count during holds has increased from 20 to 35 steps and they feel less out of breath during running.', options: ['Improved leg strength', 'Improved CO2 tolerance and oxygen efficiency from repeated transient hypoxic exposure', 'Better shoes', 'Placebo effect'], correctAnswer: 1, explanation: 'Repeated breath-hold walking creates transient drops in blood oxygen, training chemoreceptors to tolerate higher CO2 levels and improving cellular oxygen efficiency — transferable to all aerobic performance.' },
    { type: 'multiple_choice', question: 'Why should you never practise breath holds in water?', options: ['Water reduces lung capacity', 'Shallow water blackout can cause unconscious drowning — even in experienced swimmers', 'Water makes breath holds too easy', 'It is ineffective in water'], correctAnswer: 1, explanation: 'Shallow water blackout occurs when oxygen drops below consciousness threshold during or after breath holds — on land you would simply start breathing again, but in water this causes drowning.' },
    { type: 'multiple_choice', question: 'What does altitude training simulate?', options: ['Training underwater', 'Reduced oxygen availability, forcing the body to produce more red blood cells and improve oxygen efficiency', 'Training in heat', 'Zero gravity training'], correctAnswer: 1, explanation: 'Altitude (real or simulated) reduces available oxygen, triggering erythropoietin (EPO) release and increased red blood cell production for better oxygen transport.' },
    { type: 'multiple_choice', question: 'How can breathwork simulate some altitude training effects?', options: ['It cannot', 'Breath-hold walking and hypoventilation training create intermittent hypoxia similar to altitude', 'Only by holding breath for 10 minutes', 'Through hyperventilation'], correctAnswer: 1, explanation: 'Breath-hold walking (walking while holding breath) creates intermittent hypoxia, stimulating some of the same adaptations as altitude training.' },
    { type: 'multiple_choice', question: 'What is the primary breathwork technique for sleep preparation?', options: ['Energising breathwork', 'Extended exhale patterns (4-7-8 or 2:1 exhale ratio) that maximise parasympathetic activation', 'Hyperventilation', 'Breath holding'], correctAnswer: 1, explanation: 'Extended exhale patterns activate the parasympathetic system, reducing heart rate and arousal to facilitate sleep onset.' },
    { type: 'multiple_choice', question: 'What is non-sleep deep rest (NSDR)?', options: ['A nap', 'A guided relaxation protocol using breathwork and body scanning to achieve deep rest without sleeping', 'Watching TV', 'Light exercise'], correctAnswer: 1, explanation: 'NSDR protocols use breathwork and body scanning to achieve restorative states similar to sleep — useful for recovery without the grogginess of napping.' },
    { type: 'multiple_choice', question: 'How does 4-7-8 breathing activate the parasympathetic system?', options: ['Through oxygen increase', 'The extended exhale (8 counts) maximises the time spent stimulating the vagus nerve during each breath cycle', 'It does not activate parasympathetic', 'Through CO2 increase only'], correctAnswer: 1, explanation: 'The 4-7-8 pattern ensures the exhale phase (vagus nerve stimulation) occupies the majority of each breath cycle, strongly promoting relaxation.' },
  
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What is the physiological sigh?', options: ['A long yawn', 'Two quick nasal inhales followed by a long mouth exhale', 'Holding your breath for 30 seconds', 'Breathing through the left nostril only'], correctAnswer: 1, explanation: 'The physiological sigh (double inhale + long exhale) is one of the fastest ways to reduce sympathetic arousal.' },
    { type: 'multiple_choice', question: 'Why is extended exhale breathing effective for recovery?', options: ['It increases heart rate', 'The extended exhale directly stimulates the vagus nerve and shifts toward parasympathetic dominance', 'It builds lung capacity', 'It increases adrenaline'], correctAnswer: 1, explanation: 'Extended exhale breathing (e.g., 4-count inhale, 6–8-count exhale) stimulates the vagus nerve, shifting cardiac rhythm toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: 'What is the 4-7-8 breathing protocol used for?', options: ['Pre-training activation', 'Pre-sleep — the long hold and extended exhale create a powerful parasympathetic signal', 'Building CO2 tolerance', 'Emergency situations'], correctAnswer: 1, explanation: '4-7-8 breathing (inhale 4, hold 7, exhale 8) creates a strong parasympathetic signal ideal for promoting sleep onset.' },
    { type: 'multiple_choice', question: 'When should you begin your pre-sleep breathing protocol?', options: ['Immediately as you get into bed', '10–15 minutes before your target sleep time', '2 hours before bed', 'Only if you cannot sleep'], correctAnswer: 1, explanation: 'Begin the protocol 10–15 minutes before target sleep time for best results — consistency trains the association with sleep onset.' },
    { type: 'multiple_choice', question: 'What is crocodile breathing?', options: ['Breathing while swimming', 'Lying face down with forehead on hands, breathing into the belly to force diaphragmatic patterns', 'Very fast breathing', 'Breathing with mouth wide open'], correctAnswer: 1, explanation: 'Crocodile breathing uses the prone position to restrict chest breathing and enforce diaphragmatic breathing patterns.' },
    { type: 'multiple_choice', question: 'What is nasal breathing during sleep and why does it matter?', options: ['It does not matter', 'Nasal breathing during sleep maintains nitric oxide production, filters air, and prevents snoring', 'Mouth breathing during sleep is better', 'Everyone naturally breathes through their nose during sleep'], correctAnswer: 1, explanation: 'Nasal breathing during sleep improves sleep quality through nitric oxide production, air filtration, and reduced snoring/sleep apnoea symptoms.' },
    { type: 'multiple_choice', question: 'What is a recovery breathing protocol?', options: ['Breathing normally', 'A structured post-training breathwork session designed to accelerate the shift from sympathetic to parasympathetic state', 'Breathing into a paper bag', 'Hyperventilating after exercise'], correctAnswer: 1, explanation: 'Recovery breathing uses slow nasal breathing with extended exhales immediately after training to accelerate parasympathetic recovery.' },
    { type: 'multiple_choice', question: 'How long should a post-training recovery breathing session last?', options: ['30 seconds', '3–5 minutes of slow nasal breathing with extended exhales', '30 minutes', '1 hour'], correctAnswer: 1, explanation: '3–5 minutes of deliberate slow breathing immediately post-training significantly accelerates heart rate recovery and parasympathetic reactivation.' },
    { type: 'multiple_choice', question: 'What is the relationship between breathing and heart rate variability (HRV)?', options: ['No relationship', 'Slow, controlled breathing directly increases HRV — a key marker of recovery capacity and stress resilience', 'Fast breathing increases HRV', 'HRV cannot be changed by breathing'], correctAnswer: 1, explanation: 'Slow breathing (especially with extended exhales) directly increases HRV by enhancing respiratory sinus arrhythmia — improving recovery and resilience markers.' },
    { type: 'multiple_choice', question: 'What is the ideal breathing rate for maximising HRV and recovery?', options: ['30 breaths per minute', 'Approximately 6 breaths per minute (5-second inhale, 5-second exhale)', '1 breath per minute', 'As fast as possible'], correctAnswer: 1, explanation: 'Research shows approximately 6 breaths per minute (0.1 Hz) maximises respiratory sinus arrhythmia and HRV — this is the resonance frequency for most adults.' },
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['A type of hormone', 'The principle that controlled moderate stress triggers adaptive responses that increase resilience', 'A breathing technique', 'A disease caused by stress'], correctAnswer: 1, explanation: 'Hormesis is the biological principle that controlled stress exposure triggers adaptation, making you more resilient.' },
    { type: 'multiple_choice', question: 'What is the recommended progression approach for stress tolerance training?', options: ['Increase duration, intensity, and frequency simultaneously', 'Increase one variable at a time — never all three simultaneously', 'Always train at maximum intensity', 'No progression is needed'], correctAnswer: 1, explanation: 'Progress one variable at a time to prevent overexposure and identify what drives adaptation.' },
    { type: 'multiple_choice', question: 'What periodisation pattern works well for stress tolerance training?', options: ['7 days on, 7 days off', '3 weeks progressive, 1 week deload (3:1)', 'Constant maximum intensity', '1 week on, 3 weeks off'], correctAnswer: 1, explanation: 'A 3:1 pattern — three weeks of progressive exposure followed by one week of reduced volume — works well for most people.' },
    { type: 'multiple_choice', question: 'What are signs of stress overexposure?', options: ['Feeling energised and motivated', 'Persistent fatigue, sleep disruption, elevated resting heart rate, mood disturbance', 'Improved performance', 'Increased appetite only'], correctAnswer: 1, explanation: 'Overexposure signs include persistent fatigue, sleep disruption, elevated resting heart rate, mood disturbance, and increased illness.' },
    { type: 'multiple_choice', question: 'What is the recommended starting cold exposure for beginners?', options: ['5 minutes in an ice bath', '30 seconds of cold water at the end of a shower, 3 times per week', 'Jumping into a frozen lake', '10 minutes of cold immersion daily'], correctAnswer: 1, explanation: 'Start conservative — a 30-second cold finish on showers, 3 times per week, is sufficient to trigger initial adaptation.' },
    { type: 'multiple_choice', question: 'What is the goal of environmental stress tolerance training?', options: ['To suffer as much as possible', 'To eliminate all discomfort', 'To systematically expand the range of conditions under which you can function well', 'To prove toughness to others'], correctAnswer: 2, explanation: 'The goal is expanding your functional range — not suffering for its own sake, but building broader resilience.' },
    { type: 'multiple_choice', question: 'What is environmental stress tolerance?', options: ['Tolerating a messy environment', 'The ability to maintain performance and composure under challenging environmental conditions (cold, heat, altitude)', 'Weather forecasting', 'Air conditioning'], correctAnswer: 1, explanation: 'Environmental stress tolerance is the trained ability to function effectively under physical environmental stressors — cold, heat, altitude, and their combinations.' },
    { type: 'multiple_choice', question: 'How should environmental stress training be periodised?', options: ['Maximum intensity always', 'Start with single stressors at low intensity, gradually increase, then combine stressors at advanced levels', 'Random exposure', 'Only practise one type'], correctAnswer: 1, explanation: 'Like physical training: master individual stressors at low intensity before increasing, then combine stressors (contrast therapy) at advanced levels.' },
    { type: 'multiple_choice', question: 'What is cross-adaptation in stress tolerance?', options: ['Adapting to one stress only', 'Adaptation to one type of stress improving tolerance to other types of stress', 'Stress that crosses national borders', 'Training in multiple sports'], correctAnswer: 1, explanation: 'Cross-adaptation means cold tolerance can improve heat tolerance and vice versa — because the underlying nervous system regulation mechanisms overlap.' },
    { type: 'multiple_choice', question: 'What makes environmental stress training transferable to mental resilience?', options: ['It does not transfer', 'Practising composure under physical stress builds neural pathways that generalise to psychological stress', 'Only physical benefits occur', 'Only if combined with therapy'], correctAnswer: 1, explanation: 'The nervous system regulation skills developed through physical stress (calm breathing, composure, discomfort tolerance) transfer to psychological stress situations.' },
  
  ]),
];

// Unit 3 — Advanced Focus, Discipline & Cognitive Performance
