import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What hormone does the hypothalamus release to start the HPA cascade?', options: ['CRH (corticotropin-releasing hormone)', 'Cortisol', 'ACTH', 'Adrenaline'], correctAnswer: 0, explanation: 'CRH from the hypothalamus triggers the pituitary to release ACTH.' },
    { type: 'multiple_choice', question: 'What is eustress?', options: ['Positive stress that drives adaptation and growth', 'Chronic damaging stress', 'Stress you cannot control', 'Stress from exercise only'], correctAnswer: 0, explanation: 'Eustress is beneficial stress that is short-duration and within coping capacity.' },
    { type: 'multiple_choice', question: 'What does chronic cortisol do to the prefrontal cortex?', options: ['Has no effect', 'Makes it larger', 'Enhances it', 'Disrupts it, reducing decision-making and impulse control'], correctAnswer: 3, explanation: 'Chronic cortisol impairs prefrontal function, reducing rational decision-making capacity.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['Cumulative physiological damage from chronic stress', 'A type of training', 'A breathing technique', 'Maximum weight you can lift'], correctAnswer: 0, explanation: 'Allostatic load is the total wear and tear from sustained stress on body systems.' },
    { type: 'multiple_choice', question: 'Can the same stressor be both eustress and distress?', options: ['Yes, depending on perception and recovery state', 'Only physical stressors', 'No, stressors are always one or the other', 'Only psychological stressors'], correctAnswer: 0, explanation: 'Perception and recovery capacity determine whether a stressor is beneficial or harmful.' },
    { type: 'multiple_choice', question: 'What metabolic effect does chronic cortisol promote?', options: ['Improved digestion', 'Muscle growth', 'Insulin resistance and visceral fat storage', 'Fat loss'], correctAnswer: 2, explanation: 'Sustained cortisol promotes insulin resistance and preferential abdominal fat deposition.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['A type of exercise', 'The cumulative wear and tear on the body from chronic stress', 'A breathing technique', 'A measure of strength'], correctAnswer: 1, explanation: 'Allostatic load represents the total physiological cost of chronic stress — affecting cardiovascular, immune, and metabolic systems.' },
    { type: 'multiple_choice', question: 'What role does the hippocampus play in stress?', options: ['It triggers the stress response', 'It is responsible for contextualising threats and helping to regulate the HPA axis', 'It produces cortisol', 'It has no role in stress'], correctAnswer: 1, explanation: 'The hippocampus provides context ("is this actually dangerous?") and helps shut down the HPA axis when the threat has passed.' },
    { type: 'multiple_choice', question: 'How does chronic stress affect the prefrontal cortex?', options: ['It strengthens it', 'It impairs its function — reducing decision-making, emotional regulation, and impulse control', 'It has no effect', 'It only affects the amygdala'], correctAnswer: 1, explanation: 'Chronic cortisol exposure shrinks prefrontal cortex neurons and weakens their connections, impairing executive function.' },
    { type: 'multiple_choice', question: 'What is neuroplasticity in the context of stress?', options: ['The brain cannot change', 'The brain physically rewires itself based on repeated experiences — chronic stress creates maladaptive patterns', 'A personality trait', 'Only relevant in children'], correctAnswer: 1, explanation: 'Neuroplasticity means the brain adapts to repeated experiences — chronic stress wires the brain for hypervigilance, but deliberate practices can rewire it.' },
  
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Avoiding stressful situations', 'Ignoring your emotions', 'Suppressing feelings', 'Deliberately reinterpreting a situation to change your emotional response'], correctAnswer: 3, explanation: 'Reappraisal changes the meaning of a situation, altering the emotion at its source.' },
    { type: 'multiple_choice', question: 'What brain effect does affect labelling produce?', options: ['Increases amygdala activity', 'No measurable effect', 'Reduces amygdala activity by recruiting prefrontal cortex', 'Activates fight-or-flight'], correctAnswer: 2, explanation: 'Naming emotions engages the prefrontal cortex, which dampens amygdala reactivity.' },
    { type: 'multiple_choice', question: 'What does TIPP stand for in distress tolerance?', options: ['Train, Improve, Persist, Perform', 'Temperature, Intense exercise, Paced breathing, Progressive relaxation', 'Time, Intention, Practice, Patience', 'Think, Imagine, Plan, Proceed'], correctAnswer: 1, explanation: 'TIPP uses physiological interventions to change body state and therefore emotional state.' },
    { type: 'multiple_choice', question: 'What is third-person affect labelling?', options: ['Labelling emotions in a group', 'Talking about someone else', 'Writing emotions anonymously', 'Referring to yourself by name for additional psychological distance'], correctAnswer: 3, explanation: 'Using your own name creates psychological distance that enhances emotional regulation.' },
    { type: 'multiple_choice', question: 'How does suppression compare to reappraisal long-term?', options: ['They are equally effective', 'Suppression is better', 'Reappraisal produces better outcomes with less physiological cost', 'Neither is effective'], correctAnswer: 2, explanation: 'Suppression requires ongoing effort and does not reduce the underlying emotion; reappraisal does.' },
    { type: 'multiple_choice', question: 'Which form of labelling produces the strongest regulation?', options: ['Saying "I feel bad"', 'Written detailed labelling through journaling', 'Talking to no one', 'Thinking silently'], correctAnswer: 1, explanation: 'Written labelling forces precise articulation, producing the strongest and most lasting regulatory effect.' },
    { type: 'multiple_choice', question: 'What is the difference between suppression and regulation of emotions?', options: ['They are the same', 'Suppression blocks emotions (harmful); regulation processes and manages them (healthy)', 'Suppression is always better', 'Regulation means ignoring emotions'], correctAnswer: 1, explanation: 'Suppression pushes emotions down (increasing physiological stress); regulation processes them through awareness, reappraisal, and expression.' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Avoiding negative thoughts', 'Reinterpreting the meaning of a situation to change its emotional impact', 'Positive thinking', 'Denial'], correctAnswer: 1, explanation: 'Cognitive reappraisal changes how you interpret an event — "this is threatening" becomes "this is challenging but manageable."' },
    { type: 'multiple_choice', question: 'What is the window of tolerance?', options: ['How long you can hold your breath', 'The zone of arousal where you can function effectively — too high or too low impairs performance', 'A type of stretching', 'A breathing technique'], correctAnswer: 1, explanation: 'The window of tolerance is the optimal arousal zone — above it (hyperarousal) causes panic, below it (hypoarousal) causes shutdown.' },
    { type: 'multiple_choice', question: 'Why is emotional granularity important?', options: ['It is not important', 'The more precisely you can label emotions, the better you can regulate them', 'Only therapists need it', 'It increases emotional intensity'], correctAnswer: 1, explanation: 'Emotional granularity — distinguishing "frustrated" from "disappointed" from "angry" — activates the prefrontal cortex and improves regulation.' },
  
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Who coined the concept of "flow state"?', options: ['Carl Jung', 'B.F. Skinner', 'Mihaly Csikszentmihalyi', 'Sigmund Freud'], correctAnswer: 2, explanation: 'Csikszentmihalyi described and researched flow as a state of complete absorption.' },
    { type: 'multiple_choice', question: 'What happens to the prefrontal cortex during flow?', options: ['It shuts down completely', 'It partially deactivates (hypofrontality)', 'No change occurs', 'It becomes hyperactive'], correctAnswer: 1, explanation: 'Temporary hypofrontality silences the inner critic, allowing implicit systems to drive performance.' },
    { type: 'multiple_choice', question: 'How much can flow increase productivity?', options: ['50–100%', 'No measurable increase', '200–500%', '10–20%'], correctAnswer: 2, explanation: 'Research suggests flow can increase productivity by 200–500%.' },
    { type: 'multiple_choice', question: 'What is the minimum uninterrupted focus time to enter flow?', options: ['5 minutes', '10 minutes', '20 minutes', '60 minutes'], correctAnswer: 2, explanation: 'Most people need at least 20 minutes of uninterrupted focus before flow state becomes possible.' },
    { type: 'multiple_choice', question: 'What comes before the flow state in the flow cycle?', options: ['Relaxation', 'Recovery', 'Sleep', 'The struggle phase'], correctAnswer: 3, explanation: 'The struggle phase (difficulty and frustration) precedes the release into flow.' },
    { type: 'multiple_choice', question: 'What brain waves are associated with flow state?', options: ['Beta only', 'A shift from beta to alpha-theta borderline', 'Delta only', 'No specific pattern'], correctAnswer: 1, explanation: 'Flow involves a shift from high-beta (anxious thinking) to the alpha-theta borderline — associated with relaxed focus and creativity.' },
    { type: 'multiple_choice', question: 'What is transient hypofrontality?', options: ['A disease', 'Temporary deactivation of the prefrontal cortex during flow, silencing the inner critic', 'Hyperactivity of the frontal lobe', 'A meditation technique'], correctAnswer: 1, explanation: 'During flow, the prefrontal cortex temporarily quiets — silencing self-doubt, time awareness, and the inner critic.' },
    { type: 'multiple_choice', question: 'What is the ideal challenge-to-skill ratio for flow?', options: ['Challenge far exceeds skill', 'Challenge is 4% above current skill level', 'Skill far exceeds challenge', 'They should be equal'], correctAnswer: 1, explanation: 'Flow occurs when the challenge is approximately 4% beyond current skill — enough to stretch but not overwhelm.' },
    { type: 'multiple_choice', question: 'What are the prerequisites for entering flow?', options: ['Talent and luck', 'Clear goals, immediate feedback, and the right challenge-skill balance', 'Caffeine and motivation', 'A quiet room only'], correctAnswer: 1, explanation: 'Flow requires clear goals (knowing what to do), immediate feedback (knowing how you are doing), and the right challenge level.' },
    { type: 'multiple_choice', question: 'Why is flow addictive in a positive way?', options: ['It releases caffeine', 'It triggers a neurochemical cocktail of dopamine, norepinephrine, endorphins, anandamide, and serotonin', 'It is not actually pleasurable', 'Only because of the results it produces'], correctAnswer: 1, explanation: 'Flow produces a potent mix of five neurochemicals that enhance focus, creativity, pain tolerance, and wellbeing — naturally driving repeated engagement.' },
  
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'How is trauma defined in this context?', options: ['By how the nervous system responded and whether the response became stuck', 'Any negative experience', 'Only severe physical injury', 'Only childhood events'], correctAnswer: 0, explanation: 'Trauma is defined by the nervous system response, not the severity of the event itself.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Appreciation, relationships, personal strength, new possibilities, existential clarity', 'Physical recovery, mental clarity, emotional balance, social skills, career success', 'Speed, strength, flexibility, endurance, coordination', 'Acceptance, anger, denial, bargaining, depression'], correctAnswer: 0, explanation: 'PTG manifests as greater appreciation, deeper relationships, personal strength, new possibilities, and existential understanding.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional help?', options: ['Only in life-threatening situations', 'When daily functioning is significantly impaired for more than two weeks', 'Only if they ask', 'Never — peer support is always sufficient'], correctAnswer: 1, explanation: 'Persistent functional impairment exceeds peer coaching scope and requires professional intervention.' },
    { type: 'multiple_choice', question: 'Does PTG mean trauma was necessary for growth?', options: ['No — it means growth can emerge from the struggle, not that trauma was beneficial', 'Only for some people', 'Yes', 'PTG is not real'], correctAnswer: 0, explanation: 'PTG does not justify trauma — it acknowledges that growth can emerge from adversity under the right conditions.' },
    { type: 'multiple_choice', question: 'What brain change occurs with PTSD?', options: ['No structural changes', 'Improved memory', 'Enhanced emotional regulation', 'Overactive amygdala, suppressed prefrontal cortex, hippocampal processing issues'], correctAnswer: 3, explanation: 'PTSD involves an overactive threat system, reduced rational processing, and unprocessed traumatic memories.' },
    { type: 'multiple_choice', question: 'What is post-traumatic growth (PTG)?', options: ['Recovering to your previous level', 'Positive psychological change that emerges from struggling with highly challenging life circumstances', 'Denial of trauma', 'Physical growth after injury'], correctAnswer: 1, explanation: 'PTG is not returning to baseline — it is developing new strengths, perspectives, and meaning that would not have existed without the adversity.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Physical, mental, emotional, social, spiritual', 'Personal strength, new possibilities, relating to others, appreciation of life, spiritual change', 'Speed, strength, endurance, flexibility, coordination', 'Work, family, health, money, relationships'], correctAnswer: 1, explanation: 'PTG manifests in five domains: greater personal strength, recognition of new possibilities, improved relationships, enhanced appreciation of life, and spiritual development.' },
    { type: 'multiple_choice', question: 'Does everyone experience growth from adversity?', options: ['Yes — always', 'No — growth requires deliberate processing, support, and meaning-making', 'Only strong people do', 'Growth happens automatically'], correctAnswer: 1, explanation: 'PTG is not automatic — it requires deliberate cognitive processing, social support, and the ability to construct meaning from the experience.' },
    { type: 'multiple_choice', question: 'What is the role of narrative in processing adversity?', options: ['Telling your story in a coherent way helps the brain process and integrate the experience', 'Narratives are irrelevant to healing', 'You should never talk about trauma', 'Only written narratives work'], correctAnswer: 0, explanation: 'Creating a coherent narrative of adversity helps the brain organise fragmented emotional memories and find meaning.' },
    { type: 'multiple_choice', question: 'What is the difference between resilience and post-traumatic growth?', options: ['They are the same', 'Resilience is bouncing back to baseline; PTG is growing beyond your previous level', 'PTG is weaker than resilience', 'Only one involves adversity'], correctAnswer: 1, explanation: 'Resilience returns you to where you were; PTG takes you beyond — developing capacities and perspectives you did not have before.' },
  
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What is the strongest source of self-efficacy?', options: ['Verbal persuasion', 'Mastery experience', 'Reading about success', 'Vicarious experience'], correctAnswer: 1, explanation: 'Actually succeeding at progressively harder challenges provides the most powerful evidence of capability.' },
    { type: 'multiple_choice', question: 'What is the T/C ratio related to?', options: ['Testosterone/Cortisol ratio correlating with behavioural confidence', 'Training/Competition split', 'Training/Coaching balance', 'Time/Cost efficiency'], correctAnswer: 0, explanation: 'The testosterone-to-cortisol ratio correlates with assertiveness and behavioural confidence.' },
    { type: 'multiple_choice', question: 'How does avoidance affect confidence?', options: ['It reinforces the belief that you cannot handle the situation', 'It protects confidence', 'It builds confidence over time', 'It has no effect'], correctAnswer: 0, explanation: 'Every avoidance strengthens the fear and weakens self-efficacy.' },
    { type: 'multiple_choice', question: 'What is the confidence exposure ladder?', options: ['A gym exercise', 'A ranked list of feared situations to work through progressively', 'A breathing technique', 'A supplement protocol'], correctAnswer: 1, explanation: 'The exposure ladder ranks situations from mildly uncomfortable to genuinely frightening for progressive desensitisation.' },
    { type: 'multiple_choice', question: 'What distinguishes genuine self-efficacy from performative confidence?', options: ['Self-efficacy is built through progressive competence; performative confidence collapses under pressure', 'Self-efficacy requires no experience', 'Performative confidence is stronger', 'They are identical'], correctAnswer: 0, explanation: 'Genuine self-efficacy is evidence-based; performative confidence lacks substance and fails when tested.' },
    { type: 'multiple_choice', question: 'How does body posture affect confidence?', options: ['It has no effect', 'Expansive postures increase testosterone and decrease cortisol, genuinely shifting confidence', 'Only if others are watching', 'Posture only affects back pain'], correctAnswer: 1, explanation: 'Research shows expansive body postures physiologically shift hormone profiles — increasing testosterone and reducing cortisol — genuinely affecting confidence.' },
    { type: 'multiple_choice', question: 'What is the competence-confidence loop?', options: ['A circular argument', 'Competence builds confidence, and confidence enables further competence development', 'Confidence without competence', 'A personality trait'], correctAnswer: 1, explanation: 'Genuine confidence grows from proven competence — which then enables you to take on new challenges that build more competence.' },
    { type: 'multiple_choice', question: 'What is an exposure ladder?', options: ['A type of equipment', 'A graduated series of increasingly challenging situations that systematically build confidence', 'A confidence test', 'A social media strategy'], correctAnswer: 1, explanation: 'An exposure ladder starts with mildly uncomfortable situations and progressively increases difficulty — building evidence-based confidence at each step.' },
    { type: 'multiple_choice', question: 'Why is false confidence dangerous?', options: ['It is not dangerous', 'Confidence without competence leads to poor decisions, injury, and loss of credibility', 'False confidence is impossible', 'It always converts to real confidence'], correctAnswer: 1, explanation: 'Confidence must be grounded in competence — false confidence leads to overestimating ability, taking inappropriate risks, and damaging trust.' },
    { type: 'multiple_choice', question: 'What is the role of self-talk in confidence?', options: ['Self-talk has no measurable effect', 'Instructional and motivational self-talk improve performance by directing attention and managing arousal', 'Only negative self-talk matters', 'Self-talk is a sign of weakness'], correctAnswer: 1, explanation: 'Strategic self-talk — both instructional ("head still, follow through") and motivational ("I have trained for this") — measurably improves performance.' },
  
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What are the three polyvagal states?', options: ['Ventral vagal, sympathetic, dorsal vagal', 'Alert, relaxed, asleep', 'Fight, flight, freeze', 'Happy, sad, angry'], correctAnswer: 0, explanation: 'Polyvagal theory describes safety (ventral vagal), mobilisation (sympathetic), and shutdown (dorsal vagal).' },
    { type: 'multiple_choice', question: 'What is the ventral vagal state associated with?', options: ['Numbness and shutdown', 'Social engagement, safety, and calm', 'Panic', 'Fight or flight'], correctAnswer: 1, explanation: 'Ventral vagal is the state of safety — connection, calm, and complex cognitive function.' },
    { type: 'multiple_choice', question: 'What works best for shifting out of dorsal vagal shutdown?', options: ['Caffeine', 'Forcing yourself to socialise', 'Intense breathwork', 'Gentle movement and orienting to the environment'], correctAnswer: 3, explanation: 'In shutdown, gentle stimulation (movement, sensory awareness) helps shift toward mobilisation before safety.' },
    { type: 'multiple_choice', question: 'What does co-regulation mean?', options: ['Using connection with another person to help regulate emotional states', 'Exercising with a partner', 'Regulating your own emotions independently', 'Following a strict routine'], correctAnswer: 0, explanation: 'Co-regulation involves using the calming presence and connection of another person to help manage emotional arousal and return to a balanced state.' },
    { type: 'multiple_choice', question: 'Can you be in mixed autonomic states?', options: ['Yes — you can be sympathetically activated while partially in dorsal vagal', 'No, only one state at a time', 'Only during sleep', 'Only during exercise'], correctAnswer: 0, explanation: 'Mixed states are common — you can feel anxious (sympathetic) and helpless (dorsal vagal) simultaneously.' },
    { type: 'multiple_choice', question: 'What is polyvagal theory?', options: ['A theory about the heart', 'Stephen Porges\' model explaining three nervous system states: safe, mobilised, and shutdown', 'A breathing technique', 'A fitness programme'], correctAnswer: 1, explanation: 'Polyvagal theory describes three hierarchical states: ventral vagal (safe/social), sympathetic (fight/flight), and dorsal vagal (freeze/shutdown).' },
    { type: 'multiple_choice', question: 'What is the ventral vagal state?', options: ['Fight or flight', 'The state of safety, social connection, and optimal function', 'Freeze and shutdown', 'Unconsciousness'], correctAnswer: 1, explanation: 'The ventral vagal state is where you feel safe, connected, and able to think clearly — the optimal state for learning, performance, and recovery.' },
    { type: 'multiple_choice', question: 'How does psychoneuroimmunology (PNI) connect mind and body?', options: ['It does not', 'It studies how psychological states directly influence immune function through neural and hormonal pathways', 'It is only about nutrition', 'It is theoretical with no evidence'], correctAnswer: 1, explanation: 'PNI demonstrates that thoughts, emotions, and stress directly modulate immune function — chronic stress suppresses immunity while positive states enhance it.' },
    { type: 'multiple_choice', question: 'What is neuroception?', options: ['A thinking skill', 'The subconscious process of evaluating safety and threat without conscious awareness', 'A type of meditation', 'A brain scan'], correctAnswer: 1, explanation: 'Neuroception is the nervous system\'s continuous subconscious assessment of safety — influencing your state before you consciously register a threat or feel safe.' },
    { type: 'multiple_choice', question: 'How does chronic stress affect the immune system according to PNI research?', options: ['It strengthens immunity', 'It suppresses immune function — reducing natural killer cell activity and increasing susceptibility to illness', 'No effect on immunity', 'It only affects allergies'], correctAnswer: 1, explanation: 'Chronic stress suppresses immune surveillance, reduces natural killer cell activity, and increases vulnerability to infection — demonstrating the mind-body connection.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'What is psychoneuroimmunology (PNI)?', options: ['A type of medication', 'The study of how psychological processes interact with the nervous and immune systems', 'A brain scanning technique', 'A form of psychotherapy'], correctAnswer: 1, explanation: 'PNI studies the bidirectional interactions between psychological states, the nervous system, and the immune system.' },
    { type: 'multiple_choice', question: 'How much can chronic stress slow wound healing?', options: ['It has no effect', '5–10%', '25–40%', 'It speeds healing up'], correctAnswer: 2, explanation: 'Chronic psychological stress measurably slows wound healing by 25–40% through sustained cortisol elevation.' },
    { type: 'multiple_choice', question: 'How much can one night of poor sleep reduce natural killer cell activity?', options: ['5%', '20%', 'It has no effect', 'Up to 70%'], correctAnswer: 3, explanation: 'Even one night of poor sleep can reduce natural killer cell activity by up to 70%.' },
    { type: 'multiple_choice', question: 'What percentage of the immune system resides in or around the gut?', options: ['10%', '30%', '70%', '95%'], correctAnswer: 2, explanation: 'Approximately 70% of the immune system resides in or around the gut, linking gut health directly to immune function.' },
    { type: 'multiple_choice', question: 'Which mental practice is associated with increased telomerase activity?', options: ['Competitive sports', 'Regular meditation', 'Social media use', 'Video games'], correctAnswer: 1, explanation: 'Regular meditation is associated with increased telomerase activity, reduced inflammatory markers, and enhanced immune responses.' },
    { type: 'multiple_choice', question: 'What inflammatory profile does loneliness produce?', options: ['No inflammatory effect', 'Similar to chronic stress — elevated CRP and interleukin-6', 'Reduced inflammation', 'Only affects mental health'], correctAnswer: 1, explanation: 'Loneliness produces inflammatory profiles similar to chronic stress, elevating C-reactive protein and interleukin-6.' },
    { type: 'multiple_choice', question: 'What are the four components of emotional intelligence?', options: ['Speed, strength, power, endurance', 'Self-awareness, self-management, social awareness, relationship management', 'IQ, EQ, SQ, PQ', 'Thinking, feeling, doing, being'], correctAnswer: 1, explanation: 'Daniel Goleman\'s model: self-awareness (knowing your emotions), self-management (controlling them), social awareness (reading others), and relationship management (influencing interactions).' },
    { type: 'multiple_choice', question: 'What is empathy?', options: ['Feeling sorry for someone', 'The ability to understand and share the feelings of another person', 'Agreeing with everyone', 'A weakness'], correctAnswer: 1, explanation: 'Empathy is understanding another\'s perspective and emotional state — a strength that enables effective communication and leadership.' },
    { type: 'multiple_choice', question: 'Why is emotional intelligence considered more important than IQ for life success?', options: ['IQ does not exist', 'EQ predicts relationship quality, leadership effectiveness, and wellbeing more strongly than IQ', 'It is not more important', 'Only in social situations'], correctAnswer: 1, explanation: 'Research consistently shows EQ is a stronger predictor of success in relationships, leadership, health outcomes, and overall life satisfaction than IQ.' },
    { type: 'multiple_choice', question: 'Can emotional intelligence be developed?', options: ['No — it is entirely innate', 'Yes — it is a learnable set of skills that improves with deliberate practice', 'Only in childhood', 'Only with therapy'], correctAnswer: 1, explanation: 'Unlike IQ (largely fixed), emotional intelligence is highly trainable — improving with self-awareness practice, feedback, and social skill development.' },
  
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'What are the four domains of emotional intelligence?', options: ['Speed, Strength, Power, Endurance', 'Self-awareness, Self-management, Social awareness, Relationship management', 'IQ, EQ, AQ, SQ', 'Thinking, Feeling, Sensing, Intuiting'], correctAnswer: 1, explanation: 'Goleman identifies self-awareness, self-management, social awareness, and relationship management as the four EI domains.' },
    { type: 'multiple_choice', question: 'What is cognitive empathy?', options: ['Feeling what another person feels', 'Understanding what another person thinks or feels without necessarily sharing that feeling', 'Being unable to understand others', 'Ignoring others\' emotions'], correctAnswer: 1, explanation: 'Cognitive empathy is understanding another\'s perspective without necessarily sharing their emotional state — essential for communication and leadership.' },
    { type: 'multiple_choice', question: 'What is the recommended listening ratio in a first consultation?', options: ['50% client, 50% practitioner', '70% client, 30% practitioner', '30% client, 70% practitioner', '90% client, 10% practitioner'], correctAnswer: 1, explanation: 'The ideal ratio in a first consultation is approximately 70% client, 30% practitioner — understanding before advising.' },
    { type: 'multiple_choice', question: 'What should you do if a conversation becomes emotionally escalated?', options: ['Continue pushing your point', 'Take a break and return when regulated', 'Blame the other person', 'Ignore the conflict'], correctAnswer: 1, explanation: 'When either person is in a heightened sympathetic state, nothing productive happens — take a break and return when regulated.' },
    { type: 'multiple_choice', question: 'What is empathy fatigue?', options: ['Being too empathetic', 'Emotional depletion from constant exposure to others\' distress without recovery', 'Not caring about others', 'Physical exhaustion from listening'], correctAnswer: 1, explanation: 'Empathy fatigue occurs when constant exposure to others\' emotional distress depletes your own resources — boundaries are essential.' },
    { type: 'multiple_choice', question: 'What is active listening?', options: ['Hearing words while thinking about your response', 'Fully concentrating on what is being said, reflecting back, and suspending judgement', 'Listening to music during conversations', 'Nodding while checking your phone'], correctAnswer: 1, explanation: 'Active listening means giving full attention, reflecting back what you hear, and suspending your own agenda — it is the foundation of genuine connection.' },
    { type: 'multiple_choice', question: 'What is a healthy boundary?', options: ['A wall that keeps everyone out', 'A clear limit that protects your wellbeing while maintaining respectful relationships', 'Never saying no', 'Avoiding all conflict'], correctAnswer: 1, explanation: 'Healthy boundaries communicate your limits clearly and respectfully — they protect your energy without damaging relationships.' },
    { type: 'multiple_choice', question: 'How does conflict avoidance damage relationships?', options: ['It does not — avoiding conflict is always best', 'Unresolved issues accumulate resentment, and important conversations never happen', 'Conflict avoidance strengthens bonds', 'It only matters in romantic relationships'], correctAnswer: 1, explanation: 'Avoiding conflict prevents resolution — issues fester, resentment builds, and the relationship deteriorates from unspoken problems.' },
    { type: 'multiple_choice', question: 'What is the difference between assertiveness and aggression?', options: ['They are the same', 'Assertiveness expresses needs respectfully; aggression imposes needs at others\' expense', 'Assertiveness is weakness', 'Aggression is always effective'], correctAnswer: 1, explanation: 'Assertiveness communicates your needs clearly while respecting others; aggression dominates without regard for the other person.' },
    { type: 'multiple_choice', question: 'Why is giving and receiving feedback an emotional intelligence skill?', options: ['It is not', 'It requires self-awareness, empathy, and communication skills to deliver feedback constructively and receive it without defensiveness', 'Only managers need this skill', 'Feedback is always negative'], correctAnswer: 1, explanation: 'Effective feedback requires emotional awareness (reading the situation), empathy (framing sensitively), and self-regulation (receiving without defensiveness).' },
  
  ]),
];

// Unit 2 — Advanced Breathing & Exposure Science
