import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the three attention networks?', options: ['Visual, auditory, tactile', 'Short-term, long-term, working', 'Conscious, subconscious, unconscious', 'Alerting, orienting, executive'], correctAnswer: 3, explanation: 'Alerting (readiness), orienting (directing focus), and executive (conflict resolution) networks.' },
    { type: 'multiple_choice', question: 'How long does attention residue affect focus after a phone check?', options: ['No effect', '1 hour', '10–20 minutes', '1–2 minutes'], correctAnswer: 2, explanation: 'Part of attention remains on the previous task for 10–20 minutes after switching.' },
    { type: 'multiple_choice', question: 'What percentage of body energy does the brain consume?', options: ['10%', '20%', '5%', '40%'], correctAnswer: 1, explanation: 'The brain uses approximately 20% of total energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the recommended starting block for deep work training?', options: ['25-minute Pomodoro blocks', '3-hour blocks', '5-minute blocks', '8-hour blocks'], correctAnswer: 0, explanation: 'Start with 25-minute focused blocks and gradually extend as capacity develops.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for maintaining focus?', options: ['Positive thinking', 'Motivation', 'Caffeine', 'Environmental design — removing distractions'], correctAnswer: 3, explanation: 'Removing distractions beats trying to resist them — environment design trumps willpower.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What did Baumeister\'s ego depletion theory propose?', options: ['Willpower grows with use', 'Willpower only applies to diet', 'Willpower is a finite resource that gets depleted through decisions', 'Willpower is unlimited'], correctAnswer: 2, explanation: 'The theory proposed willpower is finite and gets used up, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is decision fatigue?', options: ['A medical condition', 'Declining decision quality as the number of decisions increases', 'Tiredness from exercise', 'Fatigue from too much sleep'], correctAnswer: 1, explanation: 'More decisions = worse later decisions, which is well-documented even if the mechanism is debated.' },
    { type: 'multiple_choice', question: 'What did James Clear call "making the right thing the default"?', options: ['System design that removes the need for willpower', 'Motivation technique', 'Positive affirmation', 'Goal setting'], correctAnswer: 0, explanation: 'Designing environments where desired behaviour requires less effort than undesired alternatives.' },
    { type: 'multiple_choice', question: 'Which type of decision is easiest to make?', options: ['Emotional decisions', 'Open-ended choices', 'Multi-option decisions', 'Binary decisions (yes/no)'], correctAnswer: 3, explanation: 'Binary decisions are simpler and consume less cognitive resources than open-ended choices.' },
    { type: 'multiple_choice', question: 'How does meal prep reduce decision fatigue?', options: ['It does not', 'It only helps with cooking time', 'It eliminates the daily "what should I eat?" decision entirely', 'It saves money only'], correctAnswer: 2, explanation: 'Pre-committing food choices eliminates daily nutrition decisions when willpower may be depleted.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What does BDNF do in the brain?', options: ['Damages neurons', 'Supports growth, survival, and plasticity of neurons', 'Produces cortisol', 'Clears waste'], correctAnswer: 1, explanation: 'BDNF is essential for neuronal growth, survival, and synaptic plasticity.' },
    { type: 'multiple_choice', question: 'What system clears brain waste during sleep?', options: ['Glymphatic system', 'Lymphatic system', 'Respiratory system', 'Digestive system'], correctAnswer: 0, explanation: 'The glymphatic system is 10x more active during sleep, clearing proteins linked to neurodegeneration.' },
    { type: 'multiple_choice', question: 'What cognitive effect does even 2% dehydration have?', options: ['None', 'Better memory', 'Improved focus', 'Impaired cognitive performance'], correctAnswer: 3, explanation: 'Even mild dehydration measurably impairs cognitive performance and mood.' },
    { type: 'multiple_choice', question: 'What supplement has evidence for cognitive benefits under stress?', options: ['Vitamin C', 'Calcium', 'Creatine (3–5g daily)', 'Iron'], correctAnswer: 2, explanation: 'Creatine improves short-term memory and reasoning, especially under stress or sleep deprivation.' },
    { type: 'multiple_choice', question: 'How does exercise affect the hippocampus?', options: ['Damages it', 'Physically grows it through increased BDNF and neurogenesis', 'Shrinks it', 'No effect'], correctAnswer: 1, explanation: 'Regular exercise increases hippocampal volume through BDNF-driven neurogenesis.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What are the three needs in Self-Determination Theory?', options: ['Autonomy, competence, relatedness', 'Food, water, shelter', 'Power, achievement, affiliation', 'Safety, belonging, esteem'], correctAnswer: 0, explanation: 'SDT identifies autonomy (control), competence (capability), and relatedness (connection) as essential.' },
    { type: 'multiple_choice', question: 'What type of motivation is "I train because it is who I am"?', options: ['External regulation', 'Introjected regulation', 'Amotivation', 'Integrated regulation'], correctAnswer: 3, explanation: 'Integrated regulation means the behaviour is fully aligned with your sense of identity.' },
    { type: 'multiple_choice', question: 'Why do rigid externally imposed programmes often fail?', options: ['They are too short', 'The exercises are wrong', 'They undermine autonomy', 'They are too easy'], correctAnswer: 2, explanation: 'Removing choice undermines the autonomy need, which is essential for sustained intrinsic motivation.' },
    { type: 'multiple_choice', question: 'What is the relationship between action and motivation?', options: ['They are unrelated', 'Action generates motivation — not the other way around', 'Motivation is purely genetic', 'Motivation always comes first'], correctAnswer: 1, explanation: 'Starting the action creates the motivation to continue — waiting for motivation leads to inaction.' },
    { type: 'multiple_choice', question: 'How can you support competence in training?', options: ['Track progressive overload and celebrate small wins', 'Make the programme too easy', 'Never change the programme', 'Avoid challenging exercises'], correctAnswer: 0, explanation: 'Visible progress and acknowledged achievements satisfy the competence need.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'According to James Clear, what are the three layers of behaviour change?', options: ['Thought, feeling, behaviour', 'Input, process, output', 'Goal, plan, action', 'Identity, process, outcome'], correctAnswer: 3, explanation: 'Clear describes behaviour change as three concentric layers: identity (core), process, and outcome.' },
    { type: 'multiple_choice', question: 'How is identity actually changed?', options: ['Through a single dramatic event', 'Through declarations and affirmations', 'Through accumulated evidence — consistent actions that "vote" for the new identity', 'It cannot be changed'], correctAnswer: 2, explanation: 'Identity shifts through accumulated votes — small consistent actions that provide evidence.' },
    { type: 'multiple_choice', question: 'What is more powerful: "I should train today" or "I don\'t skip training"?', options: ['They are equally effective', '"I don\'t skip training" — because it is identity-based', 'Neither is effective', '"I should train today"'], correctAnswer: 1, explanation: 'Identity-based framing is more powerful because it connects the action to who you are, not just what you should do.' },
    { type: 'multiple_choice', question: 'What are identity conflicts during personal change?', options: ['Resistance from others and feelings of impostor syndrome as you adopt new behaviours', 'Financial difficulties', 'Arguments with friends', 'Physical pain'], correctAnswer: 0, explanation: 'Others may resist your changes, and you may feel like an imposter in your new identity — both are normal.' },
    { type: 'multiple_choice', question: 'What is the best response to identity conflicts?', options: ['Pretend nothing has changed', 'Avoid everyone who knew the old you', 'Return to old behaviours', 'Continue voting for the new identity while accepting discomfort is temporary'], correctAnswer: 3, explanation: 'Continue consistent action toward the new identity — the transition discomfort is temporary.' },
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Why does mental rehearsal improve physical performance?', options: ['It replaces the need for training', 'It only works for elite athletes', 'It activates similar motor cortex regions as physical practice, strengthening neural pathways', 'It is a placebo effect'], correctAnswer: 2, explanation: 'Mental imagery activates motor cortex regions, strengthening the neural pathways used in actual performance.' },
    { type: 'multiple_choice', question: 'Why can outcome visualisation alone reduce effort?', options: ['It cannot', 'The brain partially "experiences" the reward, reducing motivation to earn it', 'It only affects beginners', 'Outcome visualisation is always harmful'], correctAnswer: 1, explanation: 'Premature reward experience from outcome visualisation can reduce the drive to actually achieve it.' },
    { type: 'multiple_choice', question: 'What makes visualisation more effective?', options: ['Multi-sensory detail — sight, sound, feel, even smell', 'Doing it once', 'Keeping it vague', 'Only visualising success'], correctAnswer: 0, explanation: 'Richer, more detailed imagery creates a stronger neural effect.' },
    { type: 'multiple_choice', question: 'Should you include adversity in your visualisation?', options: ['Adversity visualisation is harmful', 'No — only visualise perfect execution', 'Only negative scenarios', 'Yes — visualising overcoming obstacles improves real-world resilience'], correctAnswer: 3, explanation: 'Including challenges and your response to them prepares you for real-world imperfection.' },
    { type: 'multiple_choice', question: 'How long should daily mental rehearsal practice be?', options: ['2 hours', '1 minute', '5–10 minutes', '60 minutes'], correctAnswer: 2, explanation: '5–10 minutes daily is sufficient for measurable performance benefits from mental rehearsal.' },
  ]),
];

// Unit 4 — Resilience Integration & Lifelong Practice
