import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What happens to blood pH during cyclic hyperventilation?', options: ['It fluctuates unpredictably', 'It stays the same', 'It increases (respiratory alkalosis)', 'It decreases (more acidic)'], correctAnswer: 2, explanation: 'Blowing off CO2 raises blood pH, creating respiratory alkalosis.' },
    { type: 'multiple_choice', question: 'What is a CO2 table?', options: ['Repeated breath holds with decreasing rest intervals', 'A breathing speed test', 'A carbon dioxide detector', 'A nutrition reference chart'], correctAnswer: 0, explanation: 'CO2 tables progressively challenge your tolerance by reducing rest between holds.' },
    { type: 'multiple_choice', question: 'What breathing rate typically achieves resonance frequency?', options: ['20+ breaths/min', '4.5–7 breaths/min', '1 breath/min', '12–15 breaths/min'], correctAnswer: 1, explanation: "Most people\'s resonance frequency falls between 4.5 and 7 breaths per minute." },
    { type: 'multiple_choice', question: 'What does improved CO2 tolerance correlate with?', options: ['Reduced anxiety and better performance under pressure', 'Higher blood pressure', 'Increased breathing rate', 'Lower oxygen levels'], correctAnswer: 0, explanation: 'Better CO2 tolerance means a less reactive respiratory drive, directly reducing anxiety symptoms.' },
    { type: 'multiple_choice', question: 'What is the benefit of the breath hold after hyperventilation rounds?', options: ['It creates a powerful sympathetic-to-parasympathetic transition', 'It increases CO2 only', 'It builds lung capacity', 'It has no specific benefit'], correctAnswer: 0, explanation: 'The recovery phase after holds triggers a strong parasympathetic shift, enhancing vagal tone.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What triggers the cold shock response?', options: ['Cutaneous cold receptors signalling the sympathetic nervous system', 'Low body temperature', 'Brain temperature drop', 'Muscle cooling'], correctAnswer: 0, explanation: 'Skin cold receptors trigger the involuntary sympathetic response upon cold contact.' },
    { type: 'multiple_choice', question: 'How long does the cold shock response typically last?', options: ['5–10 seconds', '5 minutes', '30 minutes', '30–60 seconds'], correctAnswer: 3, explanation: 'The cold shock response is most intense in the first 30–60 seconds and diminishes with habituation.' },
    { type: 'multiple_choice', question: 'What does cold exposure do to noradrenaline?', options: ['No effect', 'Decreases it', 'Increases it by 10%', 'Increases it by 200–300%'], correctAnswer: 3, explanation: 'Cold exposure significantly increases noradrenaline, improving alertness, focus, and mood.' },
    { type: 'multiple_choice', question: 'What is brown adipose tissue (BAT)?', options: ['A type of muscle', 'Metabolically active fat that generates heat by burning calories', 'Scar tissue', 'Unhealthy body fat'], correctAnswer: 1, explanation: 'BAT produces heat through thermogenesis, activated by cold exposure.' },
    { type: 'multiple_choice', question: 'What is the primary psychological benefit of cold exposure?', options: ['Weight loss', 'Better skin', 'Proving you can choose discomfort and handle it — transferable mental toughness', 'Improved flexibility'], correctAnswer: 2, explanation: 'Choosing voluntary discomfort builds the psychological habit of doing hard things.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What cardiovascular response does sauna use create?', options: ['No cardiovascular effect', 'Heart rate increases to 100–150 bpm with vasodilation', 'Blood pressure increases sharply and stays elevated', 'Heart rate decreases'], correctAnswer: 1, explanation: 'Heat exposure creates cardiovascular stress similar to moderate exercise.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Proteins that cause overheating', 'Digestive enzymes', 'Molecular chaperones that repair proteins and protect cells', 'Proteins destroyed by heat'], correctAnswer: 2, explanation: 'HSPs repair damaged proteins and increase cellular resilience to all forms of stress.' },
    { type: 'multiple_choice', question: 'By how much can sauna increase growth hormone acutely?', options: ['200–300%', '50%', '10–20%', '1000%'], correctAnswer: 0, explanation: 'Studies show up to 200–300% acute growth hormone increase with 20-minute sauna sessions.' },
    { type: 'multiple_choice', question: 'What is contrast therapy?', options: ['Alternating heat and cold exposure for amplified benefits', 'Using light and dark rooms', 'Comparing two training programmes', 'Training at different intensities'], correctAnswer: 0, explanation: 'Contrast therapy combines heat and cold to enhance vascular, hormonal, and neurological benefits.' },
    { type: 'multiple_choice', question: 'How much sweat can be lost in a single sauna session?', options: ['A few millilitres', '3–5 litres', '0.5–1 litre', '10 litres'], correctAnswer: 2, explanation: 'Significant fluid loss (0.5–1L per session) makes hydration before and after essential.' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['Higher arousal always means better performance', 'The relationship between sleep and memory', 'Rest is always optimal', 'Performance peaks at moderate arousal; declines at both extremes'], correctAnswer: 3, explanation: 'The inverted-U shows optimal performance at moderate arousal, with decline at under- and over-arousal.' },
    { type: 'multiple_choice', question: 'What breathing is best before a heavy lift?', options: ['Short sharp breaths to increase sympathetic activation', 'Extended exhale to calm down', 'Holding breath for 2 minutes', 'Hyperventilation for 5 minutes'], correctAnswer: 0, explanation: 'Power events benefit from moderate sympathetic activation to increase force readiness.' },
    { type: 'multiple_choice', question: 'When should you exhale during a precision task?', options: ['At the moment of execution', 'During the preparation phase', 'After completing the action', 'It does not matter'], correctAnswer: 0, explanation: 'Exhale at execution (e.g., releasing an arrow) provides maximum stability and calm.' },
    { type: 'multiple_choice', question: 'What is tactical breathing?', options: ['Breathing only through one nostril', 'Breathing as fast as possible', '4-count inhale, 4-count hold, 4-count exhale, 4-count hold', 'Not breathing during performance'], correctAnswer: 2, explanation: 'Tactical breathing (box breathing) manages anxiety during competition breaks and transitions.' },
    { type: 'multiple_choice', question: 'How can post-performance breathing reduce heart rate recovery time?', options: ['It cannot', 'Only cold water helps', 'Only medication works', 'Slow nasal breathing (4 in, 8 out) can reduce recovery time by 30%'], correctAnswer: 3, explanation: 'Deliberate parasympathetic breathing accelerates cardiovascular recovery after intense performance.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['A disease process', 'Damage from excessive stress', 'Beneficial adaptation from controlled low-to-moderate stress', 'A type of hormone'], correctAnswer: 2, explanation: 'Hormesis describes how moderate stressors trigger positive adaptive responses.' },
    { type: 'multiple_choice', question: 'By how much can contrast therapy reduce DOMS?', options: ['50–70%', '20–30%', '100%', '5%'], correctAnswer: 1, explanation: 'Studies show contrast therapy can reduce delayed-onset muscle soreness by 20–30%.' },
    { type: 'multiple_choice', question: 'What signs indicate hormetic stress overload?', options: ['No signs — overload is not possible', 'Better performance', 'Deteriorating sleep, dropping motivation, rising resting heart rate', 'Increased energy and motivation'], correctAnswer: 2, explanation: 'Sleep disruption, motivational decline, and elevated resting HR indicate too much stress without recovery.' },
    { type: 'multiple_choice', question: 'How should you end a contrast therapy session for alertness?', options: ['Order does not matter', 'On cold', 'On a warm-up', 'On heat'], correctAnswer: 1, explanation: 'Ending on cold promotes alertness through noradrenaline and dopamine elevation.' },
    { type: 'multiple_choice', question: 'How often should you include a full rest day from exposure stressors?', options: ['Never', 'Only when injured', 'At least one per week', 'Once per month'], correctAnswer: 2, explanation: 'Minimum one full rest day per week prevents cumulative stress overload.' },
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'Why does the air at altitude contain fewer oxygen molecules per breath despite the same percentage of oxygen?', options: ['Oxygen percentage decreases at altitude', 'Reduced atmospheric pressure means fewer molecules per breath', 'There is more CO2 at altitude', 'Wind removes oxygen from the air'], correctAnswer: 1, explanation: 'At altitude the air still contains 20.9% oxygen, but reduced atmospheric pressure means each breath delivers fewer total molecules of oxygen to the lungs.' },
    { type: 'multiple_choice', question: 'What hormone increases during chronic altitude exposure to boost red blood cell production?', options: ['Testosterone', 'Cortisol', 'Erythropoietin (EPO)', 'Growth hormone'], correctAnswer: 2, explanation: 'Erythropoietin (EPO) is produced by the kidneys in response to hypoxia and stimulates the bone marrow to produce more red blood cells, increasing oxygen-carrying capacity.' },
    { type: 'multiple_choice', question: 'What is the "Live High / Train Low" method?', options: ['Living at sea level and training in the mountains', 'Living at altitude to trigger adaptations while training at low altitude to maintain intensity', 'Training at altitude only during competitions', 'Living and training at the same altitude'], correctAnswer: 1, explanation: 'The LHTL method combines chronic altitude exposure (living at 2,000-2,500m) for physiological adaptations with low-altitude training to maintain high exercise intensity.' },
    { type: 'scenario', question: 'What adaptation is most likely responsible for this improvement?', scenario: 'After 6 weeks of regular breath-hold walking, a person notices their step count during holds has increased from 20 to 35 steps and they feel less out of breath during running.', options: ['Improved leg strength', 'Improved CO2 tolerance and oxygen efficiency from repeated transient hypoxic exposure', 'Better shoes', 'Placebo effect'], correctAnswer: 1, explanation: 'Repeated breath-hold walking creates transient drops in blood oxygen, training chemoreceptors to tolerate higher CO2 levels and improving cellular oxygen efficiency — transferable to all aerobic performance.' },
    { type: 'multiple_choice', question: 'Why should you never practise breath holds in water?', options: ['Water reduces lung capacity', 'Shallow water blackout can cause unconscious drowning — even in experienced swimmers', 'Water makes breath holds too easy', 'It is ineffective in water'], correctAnswer: 1, explanation: 'Shallow water blackout occurs when oxygen drops below consciousness threshold during or after breath holds — on land you would simply start breathing again, but in water this causes drowning.' },
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What is the physiological sigh?', options: ['A long yawn', 'Two quick nasal inhales followed by a long mouth exhale', 'Holding your breath for 30 seconds', 'Breathing through the left nostril only'], correctAnswer: 1, explanation: 'The physiological sigh (double inhale + long exhale) is one of the fastest ways to reduce sympathetic arousal.' },
    { type: 'multiple_choice', question: 'Why is extended exhale breathing effective for recovery?', options: ['It increases heart rate', 'The extended exhale directly stimulates the vagus nerve and shifts toward parasympathetic dominance', 'It builds lung capacity', 'It increases adrenaline'], correctAnswer: 1, explanation: 'Extended exhale breathing (e.g., 4-count inhale, 6–8-count exhale) stimulates the vagus nerve, shifting cardiac rhythm toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: 'What is the 4-7-8 breathing protocol used for?', options: ['Pre-training activation', 'Pre-sleep — the long hold and extended exhale create a powerful parasympathetic signal', 'Building CO2 tolerance', 'Emergency situations'], correctAnswer: 1, explanation: '4-7-8 breathing (inhale 4, hold 7, exhale 8) creates a strong parasympathetic signal ideal for promoting sleep onset.' },
    { type: 'multiple_choice', question: 'When should you begin your pre-sleep breathing protocol?', options: ['Immediately as you get into bed', '10–15 minutes before your target sleep time', '2 hours before bed', 'Only if you cannot sleep'], correctAnswer: 1, explanation: 'Begin the protocol 10–15 minutes before target sleep time for best results — consistency trains the association with sleep onset.' },
    { type: 'multiple_choice', question: 'What is crocodile breathing?', options: ['Breathing while swimming', 'Lying face down with forehead on hands, breathing into the belly to force diaphragmatic patterns', 'Very fast breathing', 'Breathing with mouth wide open'], correctAnswer: 1, explanation: 'Crocodile breathing uses the prone position to restrict chest breathing and enforce diaphragmatic breathing patterns.' },
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['A type of hormone', 'The principle that controlled moderate stress triggers adaptive responses that increase resilience', 'A breathing technique', 'A disease caused by stress'], correctAnswer: 1, explanation: 'Hormesis is the biological principle that controlled stress exposure triggers adaptation, making you more resilient.' },
    { type: 'multiple_choice', question: 'What is the recommended progression approach for stress tolerance training?', options: ['Increase duration, intensity, and frequency simultaneously', 'Increase one variable at a time — never all three simultaneously', 'Always train at maximum intensity', 'No progression is needed'], correctAnswer: 1, explanation: 'Progress one variable at a time to prevent overexposure and identify what drives adaptation.' },
    { type: 'multiple_choice', question: 'What periodisation pattern works well for stress tolerance training?', options: ['7 days on, 7 days off', '3 weeks progressive, 1 week deload (3:1)', 'Constant maximum intensity', '1 week on, 3 weeks off'], correctAnswer: 1, explanation: 'A 3:1 pattern — three weeks of progressive exposure followed by one week of reduced volume — works well for most people.' },
    { type: 'multiple_choice', question: 'What are signs of stress overexposure?', options: ['Feeling energised and motivated', 'Persistent fatigue, sleep disruption, elevated resting heart rate, mood disturbance', 'Improved performance', 'Increased appetite only'], correctAnswer: 1, explanation: 'Overexposure signs include persistent fatigue, sleep disruption, elevated resting heart rate, mood disturbance, and increased illness.' },
    { type: 'multiple_choice', question: 'What is the recommended starting cold exposure for beginners?', options: ['5 minutes in an ice bath', '30 seconds of cold water at the end of a shower, 3 times per week', 'Jumping into a frozen lake', '10 minutes of cold immersion daily'], correctAnswer: 1, explanation: 'Start conservative — a 30-second cold finish on showers, 3 times per week, is sufficient to trigger initial adaptation.' },
    { type: 'multiple_choice', question: 'What is the goal of environmental stress tolerance training?', options: ['To suffer as much as possible', 'To eliminate all discomfort', 'To systematically expand the range of conditions under which you can function well', 'To prove toughness to others'], correctAnswer: 2, explanation: 'The goal is expanding your functional range — not suffering for its own sake, but building broader resilience.' },
  ]),
];

// Unit 3 — Advanced Focus, Discipline & Cognitive Performance
