import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Breathing, cold, heat, journaling, meditation', 'Strength, cardio, flexibility, diet, sleep', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Work, rest, play, eat, sleep'], correctAnswer: 2, explanation: 'The five pillars cover physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'How should you approach implementing the five pillars?', options: ['Only the pillars you enjoy', 'All five simultaneously from day one', 'One pillar per week, building gradually', 'Only during training days'], correctAnswer: 2, explanation: 'Gradual stacking prevents overwhelm and builds sustainable habits.' },
    { type: 'multiple_choice', question: 'What is mental training periodisation?', options: ['Alternating high-intensity and recovery phases, with deload weeks every 4–6 weeks', 'Only training mentally on weekdays', 'Always pushing to maximum', 'Only practising when stressed'], correctAnswer: 0, explanation: 'Like physical training, mental training needs intensity cycling with scheduled recovery.' },
    { type: 'multiple_choice', question: 'What should your protocol specify for difficult life periods?', options: ['Only exercise more', 'Minimum viable doses — even 5 minutes of breathing is better than nothing', 'Stop all practices', 'Double the intensity'], correctAnswer: 1, explanation: 'Minimum viable doses maintain the habit even when full practice is not possible.' },
    { type: 'multiple_choice', question: 'How often should you review your resilience system?', options: ['Only when something goes wrong', 'Never — set it and forget it', 'Annually', 'Weekly quick review, with monthly and quarterly deeper reviews'], correctAnswer: 3, explanation: 'Regular reviews at multiple intervals ensure the system stays relevant and effective.' },
    { type: 'multiple_choice', question: 'What is the difference between tools and a system?', options: ['They are the same', 'Tools are individual techniques; a system integrates them into a structured daily practice', 'Systems are more complicated', 'Tools are always better'], correctAnswer: 1, explanation: 'Individual tools (breathwork, journaling, cold exposure) become powerful only when integrated into a coherent, sustainable daily system.' },
    { type: 'multiple_choice', question: 'What are the four pillars of a complete resilience system?', options: ['Sleep, food, water, air', 'Stress management, recovery practices, physical training, and cognitive development', 'Work, rest, play, sleep', 'Morning routine only'], correctAnswer: 1, explanation: 'A complete system addresses all dimensions: managing stress inputs, optimising recovery, maintaining physical capacity, and developing cognitive skills.' },
    { type: 'multiple_choice', question: 'How should you prioritise practices when time is limited?', options: ['Do everything shorter', 'Focus on the highest-impact practices first — sleep, breathing, and movement', 'Skip everything', 'Only do what is enjoyable'], correctAnswer: 1, explanation: 'When time is constrained, prioritise the foundational practices (sleep hygiene, daily breathing, basic movement) that have the broadest positive impact.' },
    { type: 'multiple_choice', question: 'What is the role of tracking in a resilience system?', options: ['It creates pressure', 'Measurement provides feedback, reveals patterns, and sustains motivation through visible progress', 'Tracking is unnecessary', 'Only track outcomes'], correctAnswer: 1, explanation: 'Without measurement, you cannot evaluate what is working — simple daily tracking (yes/no completion, 1–10 ratings) provides essential feedback for system refinement.' },
    { type: 'multiple_choice', question: 'Why should a resilience system evolve over time?', options: ['It should stay exactly the same forever', 'Life circumstances change, you adapt, and your needs evolve — the system must evolve with you', 'Only change it when it fails completely', 'Change everything monthly'], correctAnswer: 1, explanation: 'A static system eventually stops serving you — quarterly reviews ensure your practices remain relevant, challenging, and aligned with current needs.' },
  
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What does the A-A-A-A setback protocol stand for?', options: ['Assess, Avoid, Accept, Achieve', 'Assess, Accept, Adapt, Act', 'Acknowledge, Adjust, Apply, Advance', 'Avoid, Analyse, Attempt, Achieve'], correctAnswer: 1, explanation: 'Assess reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does reflection differ from rumination?', options: ['They are the same process', 'Reflection is unhealthy', 'Rumination is more productive', 'Reflection produces action points; rumination is circular without resolution'], correctAnswer: 3, explanation: 'Reflection has direction and produces conclusions; rumination loops without progress.' },
    { type: 'multiple_choice', question: 'What should you do if you have been thinking about a setback for 20+ minutes without new insight?', options: ['Go to sleep', 'Keep thinking harder', 'Call a friend to discuss', 'Write down three controllable actions and do one immediately'], correctAnswer: 3, explanation: 'Breaking the rumination cycle requires shifting to concrete, controllable action.' },
    { type: 'multiple_choice', question: 'Is setback recovery a linear process?', options: ['Yes — it follows clear stages', 'It only occurs with therapy', 'It happens instantly', 'No — it oscillates between emotional states with gradually decreasing intensity'], correctAnswer: 3, explanation: 'Recovery is messy and non-linear — good days and bad days are normal throughout the process.' },
    { type: 'multiple_choice', question: 'What is the first practical step after a major setback?', options: ['Ignore it and carry on', 'Make a comprehensive recovery plan', 'Take the smallest meaningful action — one constructive thing today', 'Wait until you feel better'], correctAnswer: 2, explanation: 'The smallest step breaks paralysis and begins momentum — do not wait for a complete plan.' },
    { type: 'multiple_choice', question: 'What distinguishes advanced setback navigation from basic resilience?', options: ['They are the same', 'Advanced navigation involves anticipating setbacks, having pre-planned responses, and extracting maximum learning', 'Advanced means never having setbacks', 'It requires professional help'], correctAnswer: 1, explanation: 'Advanced setback navigation is proactive — anticipating potential failures, pre-planning responses, and systematically extracting lessons for improvement.' },
    { type: 'multiple_choice', question: 'What is a pre-mortem?', options: ['A medical procedure', 'Imagining a project has failed before starting, then identifying what could cause that failure', 'An autopsy', 'A type of meditation'], correctAnswer: 1, explanation: 'A pre-mortem ("imagine we have already failed — why?") identifies vulnerabilities before they become problems, enabling preventive action.' },
    { type: 'multiple_choice', question: 'What is the optimal response timeline after a setback?', options: ['Immediately analyse and fix', 'Allow emotional processing first (24–48 hours), then analyse with clarity', 'Wait 6 months', 'Never look back'], correctAnswer: 1, explanation: 'Immediate analysis during emotional dysregulation produces poor conclusions — allow processing time, then analyse objectively within 48 hours.' },
    { type: 'multiple_choice', question: 'What is the difference between a victim narrative and a growth narrative?', options: ['There is no difference', 'Victim: "this happened TO me"; Growth: "this happened and here is what I learned and how I grew"', 'Victim narratives are always false', 'Growth narratives deny pain'], correctAnswer: 1, explanation: 'The narrative you construct determines your trajectory — growth narratives acknowledge pain while actively seeking learning and meaning.' },
    { type: 'multiple_choice', question: 'Why is the "two-list" technique effective after setbacks?', options: ['It is not effective', 'Separating what you CAN control from what you CANNOT control focuses energy productively', 'It creates more lists', 'It avoids the real problem'], correctAnswer: 1, explanation: 'The two-list technique (controllable vs uncontrollable) redirects energy from rumination about things you cannot change toward actions you can take.' },
  
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'How harmful is loneliness to health?', options: ['Mildly inconvenient', 'Only affects mental health', 'Has no measurable health impact', 'Equivalent to smoking 15 cigarettes per day'], correctAnswer: 3, explanation: 'Meta-analysis of 300,000+ people found loneliness as damaging as heavy smoking.' },
    { type: 'multiple_choice', question: 'What matters more — relationship quantity or quality?', options: ['Only professional relationships matter', 'Quality — one deeply supportive relationship outweighs a hundred superficial ones', 'Neither matters', 'Quantity — more connections is always better'], correctAnswer: 1, explanation: 'Relationship quality — trust, reciprocity, emotional safety — is more protective than quantity.' },
    { type: 'multiple_choice', question: 'What characterises assertive (not aggressive) communication?', options: ['Yelling your needs', 'Saying nothing to avoid conflict', 'Stating needs clearly without attacking the other person', 'Manipulating others to get what you want'], correctAnswer: 2, explanation: 'Assertive communication is clear and direct while respecting both parties.' },
    { type: 'multiple_choice', question: 'What makes boundaries effective?', options: ['Only setting them when angry', 'Being vague so others can interpret them', 'Being clear, consistent, compassionate, with known consequences', 'Changing them based on others'], correctAnswer: 2, explanation: "Effective boundaries are specific, consistently enforced, kind in delivery, and backed by consequences." },
    { type: 'multiple_choice', question: 'How should you approach curating your social environment?', options: ['Deliberately add growth-supportive connections while managing existing relationships with boundaries', 'Ruthlessly cut everyone who is not perfect', 'Isolate yourself for focus', 'Only socialise with successful people'], correctAnswer: 0, explanation: 'The approach is additive — bring in supportive people while setting appropriate boundaries with others.' },
    { type: 'multiple_choice', question: 'What is social resilience?', options: ['Having many social media followers', 'The capacity of your relationships and social network to support you through adversity', 'Being popular', 'Never needing others'], correctAnswer: 1, explanation: 'Social resilience is the strength and quality of your relational network — it is one of the strongest predictors of how well you navigate adversity.' },
    { type: 'multiple_choice', question: 'What makes a boundary healthy rather than rigid?', options: ['Healthy boundaries are flexible — they adapt to context while protecting core needs', 'All boundaries should be rigid', 'Healthy boundaries mean saying yes to everything', 'Boundaries are unnecessary in close relationships'], correctAnswer: 0, explanation: 'Healthy boundaries are flexible and context-dependent — they protect your core needs while allowing genuine connection and reasonable negotiation.' },
    { type: 'multiple_choice', question: 'What is the difference between codependency and healthy interdependence?', options: ['They are the same', 'Codependency sacrifices self for others\' approval; interdependence maintains individual identity while supporting each other', 'Interdependence is weakness', 'Codependency is always positive'], correctAnswer: 1, explanation: 'Healthy interdependence means two whole people supporting each other; codependency means losing yourself in another person\'s needs.' },
    { type: 'multiple_choice', question: 'How does social isolation affect stress physiology?', options: ['No physiological effect', 'It increases cortisol baseline, inflammatory markers, and cardiovascular risk', 'It reduces stress', 'It only affects mood'], correctAnswer: 1, explanation: 'Social isolation is not just psychologically harmful — it measurably increases cortisol, inflammatory markers, blood pressure, and mortality risk.' },
    { type: 'multiple_choice', question: 'What is a "relationship audit" and why is it valuable?', options: ['Judging your relationships', 'Honestly evaluating which relationships energise you and which drain you — then acting accordingly', 'Ending all relationships', 'Only for romantic relationships'], correctAnswer: 1, explanation: 'A relationship audit identifies energy-giving vs energy-draining relationships — enabling conscious decisions about where to invest your limited social energy.' },
  
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['Eudaimonic is about physical health', 'No difference', 'Hedonic is better long-term', 'Hedonic = pleasure/comfort; Eudaimonic = meaning/purpose/potential'], correctAnswer: 3, explanation: 'Hedonic seeks pleasure; eudaimonic seeks meaning — research shows eudaimonic produces deeper, lasting satisfaction.' },
    { type: 'multiple_choice', question: 'How are values best identified?', options: ['By what you say matters', 'By personality tests', 'By what you consistently prioritise when things get difficult', 'By what others value'], correctAnswer: 2, explanation: 'True values are revealed by behaviour under pressure, not by stated preferences.' },
    { type: 'multiple_choice', question: 'What is values-based decision-making?', options: ['Always choosing the easiest option', 'Asking "which option aligns with my core values?" when facing decisions', 'Only making decisions when calm', 'Following rules set by others'], correctAnswer: 1, explanation: 'Using your identified core values as a decision framework cuts through analysis paralysis.' },
    { type: 'multiple_choice', question: 'Why does values-aligned living sustain motivation?', options: ['It requires no effort', 'It eliminates all difficulty', 'It does not', 'It creates a sense of coherence — you are acting in line with who you truly are'], correctAnswer: 3, explanation: 'When actions align with deepest values, intrinsic motivation sustains effort far longer than external rewards.' },
    { type: 'multiple_choice', question: 'What is the values clarification "end of life" exercise?', options: ['Planning your funeral', 'A medical assessment', 'A legal document', 'Imagining looking back at your life and asking what you want to have been true'], correctAnswer: 3, explanation: 'This reflection exercise reveals your deepest values by considering what would matter most in retrospect.' },
    { type: 'multiple_choice', question: 'Why is having a sense of purpose protective against stress?', options: ['It is not protective', 'Purpose provides a framework for interpreting adversity — suffering with meaning is bearable; suffering without meaning is not', 'Purpose eliminates all stress', 'Only religious purpose works'], correctAnswer: 1, explanation: 'Viktor Frankl demonstrated that meaning transforms suffering — people with strong purpose tolerate greater adversity because it serves something beyond themselves.' },
    { type: 'multiple_choice', question: 'What is the difference between values and goals?', options: ['They are the same', 'Values are directions you travel continuously; goals are destinations you reach and complete', 'Goals are more important', 'Values change weekly'], correctAnswer: 1, explanation: 'Values are ongoing directions ("be kind", "grow continuously"); goals are specific destinations. Values guide which goals to set and sustain motivation when goals feel distant.' },
    { type: 'multiple_choice', question: 'What is values-based decision making?', options: ['Deciding based on money', 'Using your core values as criteria for important decisions — does this align with who I want to be?', 'Following rules', 'Letting others decide'], correctAnswer: 1, explanation: 'Values-based decisions ask "does this align with my core values?" — providing clarity when options are complex and preventing regret from misaligned choices.' },
    { type: 'multiple_choice', question: 'What is ikigai?', options: ['A martial art', 'The Japanese concept of finding purpose at the intersection of what you love, are good at, and what the world needs', 'A type of sushi', 'A meditation technique'], correctAnswer: 1, explanation: 'Ikigai is the intersection of passion (what you love), vocation (what you are good at), mission (what the world needs), and profession (what you can be paid for).' },
    { type: 'multiple_choice', question: 'How does meaning differ from happiness?', options: ['They are the same', 'Happiness is a momentary emotional state; meaning provides enduring satisfaction even through difficulty', 'Meaning is always unpleasant', 'Happiness is more important'], correctAnswer: 1, explanation: 'Happiness fluctuates with circumstances; meaning provides a stable foundation — meaningful activities may involve short-term discomfort but long-term fulfilment.' },
  
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is the key difference between coaching and therapy?', options: ['Therapy is for everyone; coaching is for athletes only', 'Coaching helps find answers through questions; therapy treats clinical conditions', 'Coaching is superior', 'No difference'], correctAnswer: 1, explanation: 'Coaching facilitates self-discovery; therapy provides evidence-based treatment for clinical conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Talk 80%, listen 20%', 'Listen 80%, speak 20%', 'Agree with 80% of what is said', 'Use 80% of the session for exercises'], correctAnswer: 1, explanation: 'Effective coaching involves far more listening than speaking.' },
    { type: 'multiple_choice', question: 'What is a "powerful question"?', options: ['A yes/no question', 'A trick question', 'An open-ended, non-judgemental question that promotes self-discovery', 'A demanding question'], correctAnswer: 2, explanation: 'Powerful questions help others find their own answers, which are more impactful than advice.' },
    { type: 'multiple_choice', question: 'When must you refer to professional help?', options: ['Only if they request it', 'Only in emergencies', 'Never', 'When someone describes persistent low mood, self-harm, panic attacks, or trauma responses'], correctAnswer: 3, explanation: 'Clinical symptoms exceed peer coaching scope and require trained professional intervention.' },
      { type: 'multiple_choice', question: "Why is resisting the urge to give advice important in coaching?", options: ['Option A', 'Option B', 'Option C', 'Option D'], correctAnswer: 0, explanation: "Self-discovered insights create stronger commitment and lasting change than externally given advice." },
    { type: 'multiple_choice', question: 'Why does teaching resilience deepen your own practice?', options: ['It does not', 'Teaching forces you to articulate, organise, and truly understand concepts — filling gaps you did not know existed', 'Only if you are certified', 'Teaching weakens your own practice'], correctAnswer: 1, explanation: 'The "protégé effect" — teaching forces deeper processing, reveals gaps in understanding, and reinforces your own practice through articulation.' },
    { type: 'multiple_choice', question: 'What is the most important quality in coaching someone through adversity?', options: ['Having all the answers', 'Holding space — being present without fixing, judging, or rushing to solutions', 'Being tough', 'Giving lots of advice'], correctAnswer: 1, explanation: 'The most powerful coaching skill is holding space — being genuinely present, listening without judgement, and trusting the person to find their own path with support.' },
    { type: 'multiple_choice', question: 'What is the coaching principle of "ask, don\'t tell"?', options: ['Never give information', 'Asking powerful questions helps people discover their own answers — which creates deeper learning than being told', 'Always ask for permission', 'It is outdated'], correctAnswer: 1, explanation: 'Self-discovered answers create stronger neural pathways and greater ownership than advice — powerful questions guide without dictating.' },
    { type: 'multiple_choice', question: 'Why is modelling more powerful than instructing?', options: ['It is not', 'People learn more from watching you live your values than from hearing you talk about them', 'Instructing is always better', 'Modelling only works for children'], correctAnswer: 1, explanation: 'Behaviour modelling — actually living what you teach — is the most powerful form of influence. Inconsistency between words and actions destroys credibility.' },
    { type: 'multiple_choice', question: 'What is the coaching competency of "unconditional positive regard"?', options: ['Praising everything', 'Accepting the person fully while still challenging their behaviours — separating person from performance', 'Ignoring problems', 'Never giving negative feedback'], correctAnswer: 1, explanation: 'Carl Rogers\' concept: accepting the whole person (unconditional positive regard) while honestly addressing behaviours — the person is always valued even when challenged.' },
  
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'What does "unbreakable" mean in the course philosophy?', options: ['Never feeling pain', 'Being physically invincible', 'Never failing', 'Having the tools and self-awareness to recover from anything and grow stronger'], correctAnswer: 3, explanation: 'Unbreakable means having resilience systems that enable recovery and growth, not invulnerability.' },
    { type: 'multiple_choice', question: 'What is the ultimate performance metric according to the course?', options: ['Speed of progress', 'Maximum intensity', 'Sustainability — consistency over years', 'Perfect technique'], correctAnswer: 2, explanation: '3x/week for 10 years beats 7x/week for 3 months. Sustainability is the ultimate metric.' },
    { type: 'multiple_choice', question: 'What should a lifelong maintenance plan include?', options: ['Whatever you feel like each day', 'Only training', 'Daily non-negotiables, weekly practices, and periodic reviews', 'Only cold exposure'], correctAnswer: 2, explanation: 'A structured plan with daily, weekly, and periodic elements maintains resilience long-term.' },
    { type: 'multiple_choice', question: 'What is the purpose of deload weeks in mental training?', options: ['To prevent psychological burnout and maintain long-term sustainability', 'They are unnecessary', 'To test maximum capacity', 'To lose progress'], correctAnswer: 0, explanation: 'Deload weeks prevent burnout and allow recovery, ensuring practices remain sustainable.' },
    { type: 'multiple_choice', question: 'Where does resilience ultimately live?', options: ['In genetic potential', 'In supplements', 'In the accumulated evidence of who you choose to be, every single day', 'In textbooks'], correctAnswer: 2, explanation: 'Resilience is demonstrated through daily consistent action, not theoretical knowledge.' },
    { type: 'multiple_choice', question: 'What does "Living Without Limits" mean in practice?', options: ['Ignoring all boundaries', 'Continuously expanding your perceived limitations through deliberate practice and growth', 'Having no rules', 'Being reckless'], correctAnswer: 1, explanation: 'Living Without Limits means recognising that most limits are self-imposed beliefs — and systematically testing and expanding them through deliberate challenge.' },
    { type: 'multiple_choice', question: 'What is the Unbreakable philosophy?', options: ['Never breaking anything', 'Building such deep resilience that adversity becomes fuel for growth rather than a source of destruction', 'Being physically invincible', 'Avoiding all risk'], correctAnswer: 1, explanation: 'Unbreakable does not mean invulnerable — it means having the depth of practice, self-awareness, and recovery capacity to grow from anything life throws at you.' },
    { type: 'multiple_choice', question: 'Why is the concept of "antifragile" more powerful than "resilient"?', options: ['They are the same', 'Resilient bounces back to baseline; antifragile actually gets stronger from stress and adversity', 'Resilient is better', 'Antifragile is theoretical'], correctAnswer: 1, explanation: 'Nassim Taleb\'s antifragility goes beyond resilience — while resilience recovers, antifragility improves through disorder and challenge.' },
    { type: 'multiple_choice', question: 'What distinguishes someone who is mentally "unbreakable"?', options: ['They never feel pain', 'They have consistent daily practices, strong self-awareness, support systems, and the ability to find meaning in adversity', 'They suppress all emotions', 'They avoid all challenges'], correctAnswer: 1, explanation: 'Being unbreakable is not about being tough — it is about having deep foundations: consistent practice, self-awareness, genuine connections, and meaning-making ability.' },
    { type: 'multiple_choice', question: 'How does the Unbreakable approach view failure?', options: ['Failure should be avoided at all costs', 'Failure is essential data — each failure reveals limits to be expanded and lessons to be integrated', 'Failure means you are not resilient', 'Failure is always bad'], correctAnswer: 1, explanation: 'In the Unbreakable philosophy, failure is not the opposite of success — it is information that guides growth and reveals where your next development lies.' },
  
  ]),
  cq(4, 7, [
    { type: 'multiple_choice', question: 'Why does resilience capacity fluctuate?', options: ['It is fixed at birth', 'It is influenced by daylight, workload, life events, hormonal cycles, and cumulative stress', 'It only changes with age', 'It only decreases over time'], correctAnswer: 1, explanation: 'Resilience fluctuates naturally across days, weeks, seasons, and life phases due to multiple biological and environmental factors.' },
    { type: 'multiple_choice', question: 'What is the best approach during winter for resilience training?', options: ['Push harder to compensate for low energy', 'Consolidation: maintain baselines, prioritise sleep and connection, reduce intensity', 'Stop all training', 'Double your exposure protocols'], correctAnswer: 1, explanation: 'Winter is a natural consolidation phase — maintain baseline practices while reducing intensity and prioritising sleep and connection.' },
    { type: 'multiple_choice', question: 'What should the goal shift to during high-stress life phases?', options: ['Maximum progression', 'Adding new challenges', 'Maintenance — protecting baseline practices', 'Complete rest with no practices'], correctAnswer: 2, explanation: 'During high-stress periods, the goal shifts from progression to maintenance — protecting your non-negotiable baseline practices.' },
    { type: 'multiple_choice', question: 'What is the recommended annual review approach?', options: ['No review needed', 'A comprehensive yearly review of resilience development: what improved, regressed, and needs attention', 'Only review if something went wrong', 'Daily detailed reviews'], correctAnswer: 1, explanation: 'An annual comprehensive review assesses what improved, what regressed, and what needs attention in the next cycle.' },
    { type: 'multiple_choice', question: 'Who outperforms in the long run?', options: ['The person who gives 100% for three months then quits', 'The person who maintains 70% consistency for a decade', 'The person who only trains when motivated', 'The person with the most intense single session'], correctAnswer: 1, explanation: 'Sustained moderate consistency (70% for a decade) outperforms short bursts of extreme effort (100% for three months).' },
    { type: 'multiple_choice', question: 'What is resilience periodisation?', options: ['Only training in certain seasons', 'Structuring resilience practices in phases — building, maintaining, and recovering — across the year', 'Periodically being resilient', 'A type of physical training'], correctAnswer: 1, explanation: 'Resilience periodisation applies training science principles — organising practices into build phases (higher challenge), maintenance, and recovery across the year.' },
    { type: 'multiple_choice', question: 'Why do seasonal changes affect mental resilience?', options: ['They do not', 'Light exposure, temperature, and social patterns shift with seasons — affecting hormones, mood, and energy', 'Only in extreme climates', 'It is psychological only'], correctAnswer: 1, explanation: 'Seasonal shifts in daylight, temperature, and social activity patterns measurably affect cortisol, melatonin, serotonin, and vitamin D — all influencing resilience.' },
    { type: 'multiple_choice', question: 'How should resilience practices adapt in winter?', options: ['No changes needed', 'Increase light exposure, prioritise sleep, maintain social connection, and adjust expectations for energy levels', 'Only train indoors', 'Stop all cold exposure'], correctAnswer: 1, explanation: 'Winter requires proactive light exposure (morning light), extra sleep attention, deliberate social engagement, and realistic energy expectations.' },
    { type: 'multiple_choice', question: 'What is a deload week in resilience training?', options: ['A week off everything', 'A planned reduction in challenge intensity to allow nervous system recovery and prevent burnout', 'Doing extra work', 'A sign of weakness'], correctAnswer: 1, explanation: 'Like physical training deloads, a resilience deload reduces the intensity of challenges while maintaining daily practices — preventing cumulative nervous system fatigue.' },
    { type: 'multiple_choice', question: 'Why is long-term periodisation important for sustained resilience?', options: ['It is unnecessary', 'Without planned variation, practices become stale and the nervous system stops adapting', 'Short-term is all that matters', 'Only athletes need periodisation'], correctAnswer: 1, explanation: 'Without variation, practices become routine and stop challenging the nervous system — periodisation ensures continued growth and prevents stagnation.' },
  
  ]),
  cq(4, 8, [
    { type: 'multiple_choice', question: 'What is the reflective practice cycle?', options: ['Read, memorise, forget, repeat', 'Experience, reflection, learning, application, repeat', 'Plan, execute, ignore, restart', 'Study, test, pass, move on'], correctAnswer: 1, explanation: 'The reflective practice cycle turns experience into learning and learning into improved practice through continuous iteration.' },
    { type: 'multiple_choice', question: 'What is the purpose of a personal development portfolio?', options: ['To impress others', 'To provide a concrete record of progress and deepen understanding through articulation', 'It is not useful', 'Only for professional qualifications'], correctAnswer: 1, explanation: 'A portfolio provides tangible progress evidence (sustaining motivation) and forces articulation of learnings (deepening understanding).' },
    { type: 'multiple_choice', question: 'What does "teaching summary" mean in portfolio development?', options: ['Writing a formal academic paper', 'Explaining each core concept as if teaching a friend — if you cannot explain it simply, you do not fully understand it', 'Creating a PowerPoint presentation', 'Recording a YouTube video'], correctAnswer: 1, explanation: 'If you cannot explain a concept simply, you do not fully understand it. Teaching summaries reveal knowledge gaps.' },
    { type: 'multiple_choice', question: 'How often should quarterly reviews be conducted?', options: ['Only when something goes wrong', 'Every three months to revisit the portfolio and adjust the plan', 'Once per year', 'Daily'], correctAnswer: 1, explanation: 'Quarterly reviews (every three months) provide regular checkpoints to update self-assessment and adjust development plans.' },
    { type: 'multiple_choice', question: 'What is this chapter ultimately about?', options: ['Finishing the course', 'Transitioning from guided learning to autonomous, lifelong development', 'Getting a certificate', 'Memorising all previous content'], correctAnswer: 1, explanation: 'This chapter marks the transition from structured course learning to self-directed, autonomous development that continues indefinitely.' },
    { type: 'multiple_choice', question: 'What is reflective practice?', options: ['Looking in a mirror', 'Systematically reviewing experiences to extract learning, adjust approaches, and deepen self-awareness', 'Thinking about the past only', 'Meditation'], correctAnswer: 1, explanation: 'Reflective practice is a structured process of reviewing what happened, what you learned, and what you will do differently — turning experience into expertise.' },
    { type: 'multiple_choice', question: 'What is a personal development portfolio?', options: ['A financial investment portfolio', 'A documented collection of your growth journey — practices, achievements, reflections, and development plans', 'A CV', 'A social media profile'], correctAnswer: 1, explanation: 'A development portfolio records your journey: what you practise, what you have achieved, key reflections, and where you are heading — providing evidence of growth.' },
    { type: 'multiple_choice', question: 'What is Kolb\'s reflective cycle?', options: ['A type of exercise', 'Experience → Reflection → Conceptualisation → Experimentation — a continuous learning loop', 'A breathing pattern', 'A sleep cycle'], correctAnswer: 1, explanation: 'Kolb\'s cycle: have an experience, reflect on it, draw conclusions (conceptualise), then test those conclusions in new situations — continuous improvement through structured reflection.' },
    { type: 'multiple_choice', question: 'Why is documenting your resilience journey valuable?', options: ['It is not valuable', 'Written records provide evidence of growth during setbacks when it feels like you have made no progress', 'Only to show others', 'It is a waste of time'], correctAnswer: 1, explanation: 'During difficult periods, documented evidence of past growth provides perspective and motivation — you can see how far you have come even when it does not feel like it.' },
    { type: 'multiple_choice', question: 'What should a 12-month development plan include?', options: ['Vague aspirations', 'Quarterly focus areas, specific practices, measurable targets, and scheduled review points', 'Only final outcomes', 'Daily schedules for the entire year'], correctAnswer: 1, explanation: 'An effective 12-month plan sets quarterly themes with specific practices, measurable targets, and regular review points — providing structure while allowing adaptation.' },
  
  ]),
];
