import type { UnitAssessment } from '../types';

export const mindsetL3Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Advanced Breathing & Exposure Science',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What happens to blood CO2 during cyclic hyperventilation?', options: ['It increases', 'It fluctuates randomly', 'It decreases (respiratory alkalosis)', 'It stays the same'], correctAnswer: 2, explanation: 'Rapid breathing blows off CO2, lowering blood CO2 and raising pH.' },
    { type: 'multiple_choice', question: 'What is resonance frequency breathing?', options: ['Breathing only through the mouth', 'Breathing at the rate that maximises heart rate variability', 'Holding your breath for maximum time', 'Breathing as fast as possible'], correctAnswer: 1, explanation: 'Resonance frequency breathing (typically 4.5–7 breaths/min) maximises HRV.' },
    { type: 'multiple_choice', question: 'By how much does cold exposure increase dopamine levels?', options: ['250%', '50%', '10%', '1000%'], correctAnswer: 0, explanation: 'Cold exposure can increase dopamine by approximately 250%, lasting 2–3 hours.' },
    { type: 'multiple_choice', question: 'What is the cold shock response?', options: ['Involuntary gasp, rapid breathing, and increased heart rate on cold contact', 'Feeling cold', 'Numbness in extremities', 'Shivering'], correctAnswer: 0, explanation: 'The cold shock response is a sympathetic nervous system reaction to sudden cold exposure.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Hormones released during fever', 'Proteins that cause heat stroke', 'Molecular chaperones that repair damaged proteins and protect cells', 'Muscle-building proteins'], correctAnswer: 2, explanation: 'HSPs repair damaged proteins and increase cellular stress resistance.' },
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['The relationship between sleep and performance', 'The inverted-U relationship between arousal and performance', 'The effect of nutrition on cognition', 'The stages of learning'], correctAnswer: 1, explanation: 'The Yerkes-Dodson Law shows performance peaks at moderate arousal and declines at extremes.' },
    { type: 'multiple_choice', question: 'What is the Valsalva manoeuvre used for in training?', options: ['Maximising intra-abdominal pressure for heavy lifts', 'Improving flexibility', 'Reducing heart rate', 'Improving endurance'], correctAnswer: 0, explanation: 'The Valsalva manoeuvre creates core stability through held breath and bracing during heavy lifts.' },
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['Chronic stress damage', 'A type of breathing technique', 'Beneficial adaptation from low-to-moderate stress doses', 'A disease caused by hormones'], correctAnswer: 2, explanation: 'Hormesis describes how moderate stressors trigger beneficial adaptive responses.' },
    { type: 'multiple_choice', question: 'Finnish sauna studies found frequent sauna use reduced all-cause mortality by approximately how much?', options: ['40%', '10%', '80%', '20%'], correctAnswer: 0, explanation: 'Frequent sauna use (4–7x/week) was associated with approximately 40% reduction in all-cause mortality.' },
    { type: 'scenario', scenario: 'Someone wants to start cold exposure but has never tried it before.', question: 'What is the safest starting protocol?', options: ['Hold ice on your skin for 10 minutes', 'Jump into an ice bath for 5 minutes', '30 seconds of cold water at the end of a normal shower', 'Swim in a cold lake'], correctAnswer: 2, explanation: 'Starting with brief cold at the end of a warm shower allows safe habituation before progression.' },
    { type: 'multiple_choice', question: 'What BOLT score should you achieve before progressing to intense cyclic hyperventilation?', options: ['60 seconds', '15 seconds', '10 seconds', '25 seconds'], correctAnswer: 3, explanation: 'A BOLT score above 25 indicates sufficient CO2 tolerance for advanced protocols.' },
    { type: 'multiple_choice', question: 'How does contrast therapy reduce DOMS?', options: ['By numbing the muscles', 'Through vascular pumping — alternating vasodilation and vasoconstriction', 'It does not reduce DOMS', 'By eliminating lactic acid'], correctAnswer: 1, explanation: 'Temperature oscillation creates a vascular pump effect that enhances circulation and reduces inflammation.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "The Wim Hof breathing method primarily involves:", options: ['Slow nasal breathing for 30 minutes', 'Holding the breath for as long as possible', 'Cycles of hyperventilation followed by breath retention', 'Breathing through the mouth only during exercise'], correctAnswer: 2, explanation: 'The Wim Hof method uses repeated cycles of controlled hyperventilation (30 deep breaths) followed by breath retention, inducing temporary alkalosis and sympathetic activation.' },
    { type: 'multiple_choice', question: "Regular sauna use has been associated with:", options: ["Muscle hypertrophy", "Increased bone density", "Reduced cardiovascular mortality and improved heat shock protein production", "Weight loss through fat burning only"], correctAnswer: 2, explanation: "Research (including the Kuopio Ischemic Heart Disease study) shows regular sauna use is associated with reduced cardiovascular events, improved vasodilation, and heat shock protein activation." },
    { type: 'multiple_choice', question: "Hormesis is the principle that:", options: ["All stress is harmful", "Low-dose stressors can trigger beneficial adaptive responses", "Recovery is unnecessary", "Only extreme stressors produce adaptation"], correctAnswer: 1, explanation: "Hormesis describes how mild, controlled stressors (cold, heat, fasting, exercise) trigger adaptive cellular responses that strengthen resilience \u2014 but only within an appropriate dose range." },
    { type: 'multiple_choice', question: "Contrast therapy (alternating hot and cold) benefits include:", options: ['Enhanced blood flow, reduced inflammation, and improved recovery', 'It only feels good but has no physiological benefit', 'It replaces the need for sleep', 'It should only be done by elite athletes'], correctAnswer: 0, explanation: 'Contrast therapy promotes vasodilation/vasoconstriction cycling, enhancing blood flow, lymphatic drainage, and recovery while reducing inflammation and muscle soreness.' },
    { type: 'multiple_choice', question: "Pre-competition breathing should generally:", options: ['Be fast and shallow to increase adrenaline', 'Always be the same regardless of sport', 'Match the demands \u2014 activating for explosive events, calming for precision events', 'Be held as long as possible before starting'], correctAnswer: 2, explanation: 'Breathing protocols should match demands: activating breathwork for explosive/power events, calming techniques for precision/focus events, and recovery breathing between efforts.' },
    { type: 'multiple_choice', question: "Cold water immersion below 10\u00b0C for extended periods risks:", options: ["Nothing \u2014 cold is always beneficial", "Hypothermia, cold shock response, and cardiac arrhythmia", "Only mild discomfort", "Enhanced immune function only"], correctAnswer: 1, explanation: "Extreme cold exposure carries real risks: cold shock (gasping reflex), hypothermia, and cardiac events. Safe practice requires gradual adaptation, supervision, and time limits." },
    { type: 'multiple_choice', question: "Breath-hold training improves:", options: ['Only lung capacity', 'Vo2 max directly', 'CO2 tolerance, mental composure under discomfort, and parasympathetic recovery', 'Strength and power'], correctAnswer: 2, explanation: 'Breath-hold training builds CO2 tolerance (reducing panic response), improves composure under physiological discomfort, and strengthens vagal tone for faster recovery.' },
    { type: 'multiple_choice', question: "The vagus nerve is stimulated by:", options: ["Fast, shallow breathing", "Extended exhalation, cold exposure to the face, and humming", "Intense exercise only", "High caffeine intake"], correctAnswer: 1, explanation: "The vagus nerve responds to extended exhalation (activating parasympathetic), cold stimulation of the face (dive reflex), humming/chanting, and gentle pressure on the carotid sinus." },

  ],
};
