import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the three attention networks?', options: ['Conscious, subconscious, unconscious', 'Visual, auditory, tactile', 'Short-term, long-term, working', 'Alerting, orienting, executive'], correctAnswer: 3, explanation: 'Alerting (readiness), orienting (directing focus), and executive (conflict resolution) networks.' },
    { type: 'multiple_choice', question: 'How long does attention residue affect focus after a phone check?', options: ['10–20 minutes', '1–2 minutes', '1 hour', 'No effect'], correctAnswer: 0, explanation: 'Part of attention remains on the previous task for 10–20 minutes after switching.' },
    { type: 'multiple_choice', question: 'What percentage of body energy does the brain consume?', options: ['5%', '10%', '40%', '20%'], correctAnswer: 3, explanation: 'The brain uses approximately 20% of total energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the recommended starting block for deep work training?', options: ['8-hour blocks', '5-minute blocks', '3-hour blocks', '25-minute Pomodoro blocks'], correctAnswer: 3, explanation: 'Start with 25-minute focused blocks and gradually extend as capacity develops.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for maintaining focus?', options: ['Caffeine', 'Environmental design — removing distractions', 'Positive thinking', 'Motivation'], correctAnswer: 1, explanation: 'Removing distractions beats trying to resist them — environment design trumps willpower.' },
    { type: 'multiple_choice', question: 'What is deep work according to Cal Newport?', options: ['Working long hours', 'Focused, undistracted cognitive work that pushes your abilities and creates real value', 'Multitasking efficiently', 'Any work done at a desk'], correctAnswer: 1, explanation: 'Deep work is professional activity performed in a state of distraction-free concentration that pushes cognitive abilities to their limit.' },
    { type: 'multiple_choice', question: 'What is the maximum duration most people can sustain deep work?', options: ['About 4 hours per day in 90-minute blocks', '30 minutes total', '12 hours', '8 hours continuously'], correctAnswer: 0, explanation: 'Most people can sustain approximately 4 hours of true deep work per day — typically in 60–90 minute blocks with breaks.' },
    { type: 'multiple_choice', question: 'What is attention residue?', options: ['A sleep disorder', 'The cognitive cost of switching tasks — part of your attention remains stuck on the previous task', 'Physical fatigue', 'A supplement'], correctAnswer: 1, explanation: 'When you switch tasks, part of your attention remains "stuck" on the previous task — this residue reduces performance on the new task.' },
    { type: 'multiple_choice', question: 'What is the most effective way to protect deep work time?', options: ['Willpower alone', 'Multitasking faster', 'Time-blocking — scheduling specific blocks for deep work and defending them like appointments', 'Working late at night'], correctAnswer: 2, explanation: 'Time-blocking creates structural protection for deep work — scheduling it and defending those blocks from interruption.' },
    { type: 'multiple_choice', question: 'What is the relationship between shallow work and deep work?', options: ['Deep work is shallow work done faster', 'Shallow work (emails, admin) is necessary but crowds out deep work if not deliberately managed', 'Shallow work is more valuable', 'They are the same'], correctAnswer: 1, explanation: 'Shallow work is not valueless but expands to fill available time — without deliberate boundaries, it eliminates deep work entirely.' },
  
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: "What did Baumeister\'s ego depletion theory propose?", options: ['Willpower only applies to diet', 'Willpower grows with use', 'Willpower is unlimited', 'Willpower is a finite resource that gets depleted through decisions'], correctAnswer: 3, explanation: 'The theory proposed willpower is finite and gets used up, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is decision fatigue?', options: ['A medical condition', 'Fatigue from too much sleep', 'Declining decision quality as the number of decisions increases', 'Tiredness from exercise'], correctAnswer: 2, explanation: 'More decisions = worse later decisions, which is well-documented even if the mechanism is debated.' },
    { type: 'multiple_choice', question: 'What did James Clear call "making the right thing the default"?', options: ['Motivation technique', 'Goal setting', 'System design that removes the need for willpower', 'Positive affirmation'], correctAnswer: 2, explanation: 'Designing environments where desired behaviour requires less effort than undesired alternatives.' },
    { type: 'multiple_choice', question: 'Which type of decision is easiest to make?', options: ['Multi-option decisions', 'Open-ended choices', 'Emotional decisions', 'Binary decisions (yes/no)'], correctAnswer: 3, explanation: 'Binary decisions are simpler and consume less cognitive resources than open-ended choices.' },
    { type: 'multiple_choice', question: 'How does meal prep reduce decision fatigue?', options: ['It only helps with cooking time', 'It does not', 'It eliminates the daily "what should I eat?" decision entirely', 'It saves money only'], correctAnswer: 2, explanation: 'Pre-committing food choices eliminates daily nutrition decisions when willpower may be depleted.' },
    { type: 'multiple_choice', question: 'What is decision fatigue?', options: ['The progressive deterioration of decision quality after making many decisions', 'A medical condition', 'Being tired of making decisions', 'Inability to make any decisions'], correctAnswer: 0, explanation: 'Decision fatigue means each decision depletes a finite resource — later decisions are increasingly impulsive, avoidant, or poor quality.' },
    { type: 'multiple_choice', question: 'Why do successful leaders often wear the same clothes daily?', options: ['They cannot afford variety', 'It eliminates trivial decisions, preserving decision-making energy for important choices', 'They are eccentric', 'Fashion is irrelevant to them'], correctAnswer: 1, explanation: 'Eliminating trivial decisions (what to wear, what to eat for breakfast) preserves cognitive resources for the decisions that actually matter.' },
    { type: 'multiple_choice', question: 'What is ego depletion?', options: ['Excessive confidence', 'A personality disorder', 'The theory that self-control draws from a limited pool that depletes with use', 'Losing self-esteem'], correctAnswer: 2, explanation: 'Ego depletion suggests willpower is like a battery that drains with use — which is why system design matters more than relying on willpower.' },
    { type: 'multiple_choice', question: 'How can you combat decision fatigue?', options: ['Avoid all decisions', 'Delegate every decision', 'Automate routine decisions, batch similar decisions, and make important decisions early in the day', 'Make more decisions to build tolerance'], correctAnswer: 2, explanation: 'Reduce total decisions (automate routines), batch similar decisions together, and schedule important decisions for peak cognitive periods.' },
    { type: 'multiple_choice', question: 'What is a decision matrix?', options: ['A movie reference', 'Random decision-making', 'A structured framework for evaluating options against weighted criteria to reduce cognitive load', 'A type of spreadsheet'], correctAnswer: 2, explanation: 'A decision matrix replaces intuition with structure — listing options against weighted criteria produces better decisions with less cognitive effort.' },
  
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What does BDNF do in the brain?', options: ['Damages neurons', 'Supports growth, survival, and plasticity of neurons', 'Produces cortisol', 'Clears waste'], correctAnswer: 1, explanation: 'BDNF is essential for neuronal growth, survival, and synaptic plasticity.' },
    { type: 'multiple_choice', question: 'What system clears brain waste during sleep?', options: ['Respiratory system', 'Digestive system', 'Lymphatic system', 'Glymphatic system'], correctAnswer: 3, explanation: 'The glymphatic system is 10x more active during sleep, clearing proteins linked to neurodegeneration.' },
    { type: 'multiple_choice', question: 'What cognitive effect does even 2% dehydration have?', options: ['Better memory', 'Improved focus', 'None', 'Impaired cognitive performance'], correctAnswer: 3, explanation: 'Even mild dehydration measurably impairs cognitive performance and mood.' },
    { type: 'multiple_choice', question: 'What supplement has evidence for cognitive benefits under stress?', options: ['Creatine (3–5g daily)', 'Vitamin C', 'Calcium', 'Iron'], correctAnswer: 0, explanation: 'Creatine improves short-term memory and reasoning, especially under stress or sleep deprivation.' },
    { type: 'multiple_choice', question: 'How does exercise affect the hippocampus?', options: ['Physically grows it through increased BDNF and neurogenesis', 'Damages it', 'Shrinks it', 'No effect'], correctAnswer: 0, explanation: 'Regular exercise increases hippocampal volume through BDNF-driven neurogenesis.' },
    { type: 'multiple_choice', question: 'What is neurogenesis?', options: ['Brain death', 'A disease', 'Only happens in children', 'The growth of new brain cells, which occurs primarily in the hippocampus throughout life'], correctAnswer: 3, explanation: 'Neurogenesis — new brain cell growth — continues throughout life, primarily in the hippocampus (memory), and is enhanced by exercise, sleep, and learning.' },
    { type: 'multiple_choice', question: 'What type of exercise most effectively promotes brain health?', options: ['No exercise affects the brain', 'Stretching only', 'Aerobic exercise — it increases BDNF (brain-derived neurotrophic factor) which supports neuroplasticity', 'Only resistance training'], correctAnswer: 2, explanation: 'Aerobic exercise increases BDNF — often called "fertiliser for the brain" — promoting neurogenesis, synaptic plasticity, and cognitive function.' },
    { type: 'multiple_choice', question: 'What is BDNF?', options: ['Brain-Derived Neurotrophic Factor — a protein that supports the growth and maintenance of brain cells', 'A type of exercise', 'A brain disease', 'A vitamin'], correctAnswer: 0, explanation: 'BDNF is a protein that promotes neuronal survival, growth, and connectivity — it is increased by exercise, sleep, and reduced by chronic stress and poor diet.' },
    { type: 'multiple_choice', question: 'How does chronic sleep deprivation affect the brain?', options: ['Only affects mood', 'No long-term effects', 'It makes you smarter', 'It impairs memory consolidation, reduces BDNF, increases neuroinflammation, and accelerates cognitive decline'], correctAnswer: 3, explanation: 'Chronic sleep deprivation causes cumulative brain damage — impairing memory, reducing neuroplasticity, increasing inflammation, and accelerating age-related decline.' },
    { type: 'multiple_choice', question: 'What lifestyle factors most protect long-term cognitive function?', options: ['Crossword puzzles only', 'Supplements alone', 'Regular exercise, quality sleep, social connection, continuous learning, and stress management', 'Genetics alone determine cognitive decline'], correctAnswer: 2, explanation: 'The "big five" for brain health: regular aerobic exercise, quality sleep, meaningful social connection, continuous learning, and effective stress management.' },
  
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What are the three needs in Self-Determination Theory?', options: ['Autonomy, competence, relatedness', 'Safety, belonging, esteem', 'Food, water, shelter', 'Power, achievement, affiliation'], correctAnswer: 0, explanation: 'SDT identifies autonomy (control), competence (capability), and relatedness (connection) as essential.' },
    { type: 'multiple_choice', question: 'What type of motivation is "I train because it is who I am"?', options: ['Amotivation', 'Integrated regulation', 'Introjected regulation', 'External regulation'], correctAnswer: 1, explanation: 'Integrated regulation means the behaviour is fully aligned with your sense of identity.' },
    { type: 'multiple_choice', question: 'Why do rigid externally imposed programmes often fail?', options: ['They are too easy', 'The exercises are wrong', 'They undermine autonomy', 'They are too short'], correctAnswer: 2, explanation: 'Removing choice undermines the autonomy need, which is essential for sustained intrinsic motivation.' },
    { type: 'multiple_choice', question: 'What is the relationship between action and motivation?', options: ['Motivation always comes first', 'Action generates motivation — not the other way around', 'Motivation is purely genetic', 'They are unrelated'], correctAnswer: 1, explanation: 'Starting the action creates the motivation to continue — waiting for motivation leads to inaction.' },
    { type: 'multiple_choice', question: 'How can you support competence in training?', options: ['Never change the programme', 'Make the programme too easy', 'Avoid challenging exercises', 'Track progressive overload and celebrate small wins'], correctAnswer: 3, explanation: 'Visible progress and acknowledged achievements satisfy the competence need.' },
    { type: 'multiple_choice', question: 'What are the three basic psychological needs according to Self-Determination Theory?', options: ['Money, status, power', 'Food, shelter, safety', 'Achievement, recognition, reward', 'Autonomy, competence, and relatedness'], correctAnswer: 3, explanation: 'SDT identifies autonomy (choice), competence (mastery), and relatedness (connection) as the three innate needs driving intrinsic motivation.' },
    { type: 'multiple_choice', question: 'What is the difference between intrinsic and extrinsic motivation?', options: ['Intrinsic is unreliable', 'They are the same', 'Intrinsic comes from internal interest and satisfaction; extrinsic comes from external rewards and punishments', 'Extrinsic is always better'], correctAnswer: 2, explanation: 'Intrinsic motivation (doing something because it is inherently interesting) is more sustainable than extrinsic (doing it for reward/to avoid punishment).' },
    { type: 'multiple_choice', question: 'What is the overjustification effect?', options: ['External rewards can undermine intrinsic motivation — people stop doing things "for fun" when paid to do them', 'A positive effect of rewards', 'Being too motivated', 'Having too many reasons'], correctAnswer: 0, explanation: 'Adding external rewards to intrinsically enjoyable activities can reduce intrinsic motivation — the external reward "overjustifies" the behaviour.' },
    { type: 'multiple_choice', question: 'How does autonomy affect motivation?', options: ['Having choice and control over your actions significantly increases motivation and engagement', 'Only leaders need autonomy', 'It has no effect', 'Autonomy reduces motivation'], correctAnswer: 0, explanation: 'Autonomy — feeling you have genuine choice in what, when, and how you do things — is one of the strongest predictors of sustained motivation.' },
    { type: 'multiple_choice', question: 'What happens to motivation when people feel incompetent?', options: ['It stays the same', 'It decreases rapidly — people disengage from activities where they feel unable to succeed', 'Incompetence is motivating', 'It increases as a challenge'], correctAnswer: 1, explanation: 'Competence need: if challenges consistently exceed ability with no progress, motivation collapses — the task must be within the growth zone, not the panic zone.' },
  
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'According to James Clear, what are the three layers of behaviour change?', options: ['Identity, process, outcome', 'Thought, feeling, behaviour', 'Input, process, output', 'Goal, plan, action'], correctAnswer: 0, explanation: 'Clear describes behaviour change as three concentric layers: identity (core), process, and outcome.' },
    { type: 'multiple_choice', question: 'How is identity actually changed?', options: ['Through declarations and affirmations', 'Through accumulated evidence — consistent actions that "vote" for the new identity', 'It cannot be changed', 'Through a single dramatic event'], correctAnswer: 1, explanation: 'Identity shifts through accumulated votes — small consistent actions that provide evidence.' },
    { type: 'multiple_choice', question: 'What is more powerful: "I should train today" or "I don\'t skip training"?', options: ['They are equally effective', '"I don\'t skip training" — because it is identity-based', 'Neither is effective', '"I should train today"'], correctAnswer: 1, explanation: 'Identity-based framing is more powerful because it connects the action to who you are, not just what you should do.' },
    { type: 'multiple_choice', question: 'What are identity conflicts during personal change?', options: ['Arguments with friends', 'Resistance from others and feelings of impostor syndrome as you adopt new behaviours', 'Physical pain', 'Financial difficulties'], correctAnswer: 1, explanation: 'Others may resist your changes, and you may feel like an imposter in your new identity — both are normal.' },
    { type: 'multiple_choice', question: 'What is the best response to identity conflicts?', options: ['Continue voting for the new identity while accepting discomfort is temporary', 'Avoid everyone who knew the old you', 'Pretend nothing has changed', 'Return to old behaviours'], correctAnswer: 0, explanation: 'Continue consistent action toward the new identity — the transition discomfort is temporary.' },
    { type: 'multiple_choice', question: 'What is identity-based change?', options: ['Changing who you believe you are, so that behaviours naturally follow from your self-concept', 'Changing your appearance', 'Pretending to be someone else', 'Changing your name'], correctAnswer: 0, explanation: 'Identity-based change focuses on "who do I want to become?" rather than "what do I want to achieve?" — behaviour flows naturally from identity.' },
    { type: 'multiple_choice', question: 'What is the difference between outcome-based and identity-based goals?', options: ['Outcome-based: "I want to lose weight"; Identity-based: "I am someone who eats well and moves daily"', 'They are the same', 'Outcome-based is always better', 'Identity-based goals are vague'], correctAnswer: 0, explanation: 'Identity-based goals create lasting change because they change the lens through which you evaluate every decision — "would a healthy person do this?"' },
    { type: 'multiple_choice', question: 'How are identity beliefs formed?', options: ['Through positive thinking alone', 'Only through major life events', 'Through repeated evidence — every action is a vote for the type of person you want to become', 'They are fixed at birth'], correctAnswer: 2, explanation: 'Identity is built through repeated action — every time you train, you cast a vote for "I am someone who trains." Enough votes build conviction.' },
    { type: 'multiple_choice', question: 'What is a self-concept?', options: ['What others think of you', 'Your job title', 'The collection of beliefs you hold about who you are and what you are capable of', 'Your social media profile'], correctAnswer: 2, explanation: 'Self-concept is your internal model of who you are — it filters opportunities, shapes decisions, and determines what you believe is possible for you.' },
    { type: 'multiple_choice', question: 'Can identity change be negative?', options: ['No — all identity change is positive', 'Only positive identity changes stick', 'Identity cannot change', 'Yes — identifying as "broken" or "a victim" can limit growth and become self-fulfilling'], correctAnswer: 3, explanation: 'Negative identity labels ("I am broken", "I am not a morning person") can become self-fulfilling prophecies that limit growth and reinforce unhelpful patterns.' },
  
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Why does mental rehearsal improve physical performance?', options: ['It replaces the need for training', 'It is a placebo effect', 'It activates similar motor cortex regions as physical practice, strengthening neural pathways', 'It only works for elite athletes'], correctAnswer: 2, explanation: 'Mental imagery activates motor cortex regions, strengthening the neural pathways used in actual performance.' },
    { type: 'multiple_choice', question: 'Why can outcome visualisation alone reduce effort?', options: ['Outcome visualisation is always harmful', 'It cannot', 'The brain partially "experiences" the reward, reducing motivation to earn it', 'It only affects beginners'], correctAnswer: 2, explanation: 'Premature reward experience from outcome visualisation can reduce the drive to actually achieve it.' },
    { type: 'multiple_choice', question: 'What makes visualisation more effective?', options: ['Multi-sensory detail — sight, sound, feel, even smell', 'Doing it once', 'Keeping it vague', 'Only visualising success'], correctAnswer: 0, explanation: 'Richer, more detailed imagery creates a stronger neural effect.' },
    { type: 'multiple_choice', question: 'Should you include adversity in your visualisation?', options: ['Yes — visualising overcoming obstacles improves real-world resilience', 'No — only visualise perfect execution', 'Only negative scenarios', 'Adversity visualisation is harmful'], correctAnswer: 0, explanation: 'Including challenges and your response to them prepares you for real-world imperfection.' },
    { type: 'multiple_choice', question: 'How long should daily mental rehearsal practice be?', options: ['60 minutes', '5–10 minutes', '1 minute', '2 hours'], correctAnswer: 1, explanation: '5–10 minutes daily is sufficient for measurable performance benefits from mental rehearsal.' },
    { type: 'multiple_choice', question: 'What is mental rehearsal?', options: ['Memorising facts', 'Thinking about training', 'Systematically imagining performing a skill or scenario in vivid sensory detail to improve actual performance', 'Watching training videos'], correctAnswer: 2, explanation: 'Mental rehearsal uses vivid, multi-sensory imagination to activate many of the same neural pathways as physical performance — improving motor skills and confidence.' },
    { type: 'multiple_choice', question: 'Why does visualisation work neurologically?', options: ['It relaxes the muscles', 'It does not work', 'It is just placebo', 'The brain activates similar neural pathways during vivid imagination as during actual performance'], correctAnswer: 3, explanation: 'Neuroimaging shows that vivid mental rehearsal activates the motor cortex, premotor areas, and cerebellum — many of the same regions used during physical execution.' },
    { type: 'multiple_choice', question: 'What makes visualisation most effective?', options: ['Visualising for 2+ hours', 'Doing it once before a big event', 'Multi-sensory detail (see, hear, feel), first-person perspective, and including both process and outcome', 'Only visualising success'], correctAnswer: 2, explanation: 'Effective visualisation engages all senses, uses first-person perspective, and includes the process (how you will perform) not just the outcome (winning).' },
    { type: 'multiple_choice', question: 'Should you visualise overcoming obstacles or only success?', options: ['Only success — negative thoughts are harmful', 'Neither — just show up', 'Both — mental contrasting (imagining success AND the obstacles) is more effective than positive fantasy alone', 'Only obstacles'], correctAnswer: 2, explanation: 'Mental contrasting — imagining the desired outcome AND the obstacles you might face — is more effective than pure positive visualisation at driving behaviour change.' },
    { type: 'multiple_choice', question: 'How often should you practise mental rehearsal for best results?', options: ['Daily — 5–10 minutes of consistent practice builds stronger neural pathways than occasional long sessions', 'Monthly', 'Once before competition only', 'Only when anxious'], correctAnswer: 0, explanation: 'Like physical skills, mental rehearsal benefits from daily consistency — short regular sessions build stronger neural pathways than infrequent long ones.' },
  ]),
  cq(3, 7, [
    { type: 'multiple_choice', question: 'What two brain networks interact to produce creative insight?', options: ['Visual and auditory networks', 'Task-positive network (focused attention) and default mode network (mind-wandering)', 'Motor and sensory networks', 'Left and right hemispheres'], correctAnswer: 1, explanation: 'Creativity emerges from the interplay between focused attention and mind-wandering — both are essential.' },
    { type: 'multiple_choice', question: 'What is divergent thinking?', options: ['Thinking about divergent topics', 'Narrowing options to find the single best answer', 'Expanding options to generate multiple possible answers', 'A form of negative thinking'], correctAnswer: 2, explanation: 'Divergent thinking expands possibilities — it is associative, playful, and non-linear, essential for innovation.' },
    { type: 'multiple_choice', question: 'Why does judging ideas while generating them kill creativity?', options: ['It only affects artists', 'It does not — always evaluate immediately', 'The evaluation mindset shuts down the generative process', 'Judgement improves idea quality'], correctAnswer: 2, explanation: 'Mixing convergent evaluation with divergent generation suppresses the creative process. Diverge first, then converge.' },
    { type: 'multiple_choice', question: 'By how much does walking increase creative output according to Stanford research?', options: ['60%', '100%', '30%', '10%'], correctAnswer: 0, explanation: 'Stanford research found walking increases creative output by an average of 60% — movement stimulates divergent thinking networks.' },
    { type: 'multiple_choice', question: 'What is a pre-mortem analysis?', options: ['Imagining a project has already failed and asking what went wrong — before starting', 'Analysing a project after it fails', 'Reviewing competitors', 'A medical procedure'], correctAnswer: 0, explanation: 'A pre-mortem imagines future failure before starting, generating creative risk identification that forward-looking analysis often misses.' },
    { type: 'multiple_choice', question: 'What is constraint reframing?', options: ['Removing all obstacles', 'Asking how an obstacle could become an advantage', 'Adding more constraints', 'Ignoring constraints entirely'], correctAnswer: 1, explanation: 'Instead of asking how to remove an obstacle, ask how it could become an advantage — constraints often drive the most creative solutions.' },
    { type: 'multiple_choice', question: 'What is lateral thinking?', options: ['Thinking while lying on your side', 'Approaching problems from unconventional angles rather than logical, sequential steps', 'A type of brainstorming', 'Thinking faster'], correctAnswer: 1, explanation: 'Lateral thinking (Edward de Bono) solves problems by approaching them indirectly — using creative, non-obvious perspectives rather than linear logic.' },
    { type: 'multiple_choice', question: 'What brain state is most associated with creative insight?', options: ['Gamma waves only', 'High-beta focused attention', 'Delta sleep waves', 'Alpha waves — relaxed, diffuse attention where the brain makes unexpected connections'], correctAnswer: 3, explanation: 'Creative insights often occur during alpha wave states — relaxed, unfocused attention (walking, showering) where the default mode network makes novel connections.' },
    { type: 'multiple_choice', question: 'What is the default mode network (DMN)?', options: ['The network you use when focused', 'Your wifi network', 'A computer term', 'The brain network active during mind-wandering, daydreaming, and self-reflection — crucial for creativity'], correctAnswer: 3, explanation: 'The DMN activates when the focused mind relaxes — it connects disparate ideas, enables creative insight, and supports self-reflection and future planning.' },
    { type: 'multiple_choice', question: 'Why is constraint often beneficial for creativity?', options: ['Constraints block creativity', 'Only artists benefit from constraints', 'Constraints force the brain to find novel solutions within boundaries rather than being paralysed by infinite options', 'It is not — freedom is always better'], correctAnswer: 2, explanation: 'Constraints paradoxically enhance creativity by eliminating the paralysis of infinite options and forcing the brain into novel territory.' },
  
  ]),
  cq(3, 8, [
    { type: 'multiple_choice', question: 'What brain maintenance process occurs during deep sleep?', options: ['Muscle growth', 'Memory deletion', 'The glymphatic system clears metabolic waste including beta-amyloid', 'Hormone depletion'], correctAnswer: 2, explanation: 'During deep sleep, the glymphatic system activates and clears metabolic waste — including beta-amyloid associated with neurodegeneration.' },
    { type: 'multiple_choice', question: 'What does going to bed late selectively reduce?', options: ['All stages equally', 'Light sleep', 'REM sleep', 'Deep sleep (which predominates in the first half of the night)'], correctAnswer: 3, explanation: 'Deep sleep predominates in the first half of the night — late bedtimes selectively cut into this critical stage.' },
    { type: 'multiple_choice', question: 'What is the dangerous aspect of accumulated sleep debt?', options: ['It is easily repaid', 'Subjective awareness of impairment plateaus while objective performance continues to decline', 'You always feel tired', 'It only affects athletes'], correctAnswer: 1, explanation: 'After a few days, you stop feeling tired — but your brain remains measurably compromised. You lose awareness of your own impairment.' },
    { type: 'multiple_choice', question: 'What is the single most important anchor for circadian rhythm?', options: ['Meal timing', 'Bedtime', 'Exercise time', 'Consistent wake time'], correctAnswer: 3, explanation: 'Wake time is the single most important circadian anchor — keep it consistent to within 30 minutes, even on weekends.' },
    { type: 'multiple_choice', question: 'Why does a hot bath before bed help sleep onset?', options: ['It increases melatonin directly', 'It paradoxically cools you by drawing blood to the surface, accelerating heat loss', 'The heat makes you tired', 'It has no effect on sleep'], correctAnswer: 1, explanation: 'A hot bath 60–90 minutes before bed draws blood to the surface, accelerating core temperature drop — the signal for sleep onset.' },
    { type: 'multiple_choice', question: 'What is the optimal nap duration to restore alertness without grogginess?', options: ['90 minutes', '20 minutes', '60 minutes', '5 minutes'], correctAnswer: 1, explanation: '20 minutes improves alertness without entering deep sleep, which would cause sleep inertia (grogginess) upon waking.' },
    { type: 'multiple_choice', question: 'What is the glymphatic system?', options: ['Part of the digestive system', 'The brain\'s waste clearance system, most active during deep sleep, which removes metabolic debris including beta-amyloid', 'A lymphatic disorder', 'A breathing technique'], correctAnswer: 1, explanation: 'The glymphatic system clears metabolic waste (including Alzheimer\'s-linked beta-amyloid) from the brain — it is 10× more active during deep sleep.' },
    { type: 'multiple_choice', question: 'What happens during each 90-minute sleep cycle?', options: ['Nothing changes', 'Only REM occurs', 'You progress through N1 (light) → N2 → N3 (deep) → REM, with proportions shifting across the night', 'Only deep sleep occurs'], correctAnswer: 2, explanation: 'Each 90-minute cycle includes all stages, but early cycles have more deep sleep (physical recovery) and later cycles have more REM (cognitive/emotional recovery).' },
    { type: 'multiple_choice', question: 'Why is the last sleep cycle of the night critical for emotional regulation?', options: ['The final 90-minute cycle is REM-dominant — processing emotions and consolidating emotional memories', 'It is mostly deep sleep', 'Only the first cycle matters', 'It is not critical'], correctAnswer: 0, explanation: 'Cutting sleep short (alarm clocks, early rising) disproportionately removes REM-rich final cycles — impairing emotional processing and increasing reactivity.' },
    { type: 'multiple_choice', question: 'What is sleep pressure (adenosine)?', options: ['A sleep disorder', 'The weight of your pillow', 'Blood pressure during sleep', 'Adenosine builds during wakefulness creating increasing sleep drive — caffeine blocks its receptors temporarily'], correctAnswer: 3, explanation: 'Adenosine accumulates during wakefulness, creating sleep pressure. Caffeine blocks adenosine receptors (masking tiredness) but does not reduce the actual adenosine — it crashes when caffeine wears off.' },
  
  ]),
];

// Unit 4 — Resilience Integration & Lifelong Practice
