import type { UnitAssessment } from '../types';

export const mindsetL3Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Resilience Integration & Lifelong Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Breathing, cold, heat, journaling, meditation', 'Strength, speed, endurance, flexibility, balance', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Eat, sleep, train, repeat, rest'], correctAnswer: 2, explanation: 'A complete system addresses physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'What is the AAAA Setback Protocol?', options: ['Assess, Accept, Adapt, Act', 'Avoid, Analyse, Attempt, Achieve', 'Assess, Avoid, Accept, Achieve', 'Acknowledge, Apologise, Adjust, Advance'], correctAnswer: 0, explanation: 'Assess the reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does rumination differ from reflection?', options: ['Reflection is unhealthy', 'Rumination is more productive', 'They are the same', 'Reflection produces action points; rumination is circular without resolution'], correctAnswer: 3, explanation: 'Reflection moves toward insight and action; rumination repeats without progress.' },
    { type: 'multiple_choice', question: 'How harmful is loneliness compared to other health risks?', options: ['Equivalent to mild dehydration', 'No measurable health effect', 'Equivalent to smoking 15 cigarettes per day', 'Minor effect'], correctAnswer: 2, explanation: 'Meta-analysis of 300,000+ participants found loneliness as harmful as smoking 15 cigarettes daily.' },
    { type: 'multiple_choice', question: 'What characterises an effective boundary?', options: ['Only set when convenient', 'Clear, consistent, compassionate, with known consequences', 'Vague and flexible', 'Aggressive and punishing'], correctAnswer: 1, explanation: 'Effective boundaries are specific, consistently enforced, compassionate, and have clear consequences.' },
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['Hedonic is pleasure-based; eudaimonic is meaning and purpose-based', 'They are identical', 'Eudaimonic is about physical health', 'Hedonic is long-lasting; eudaimonic is temporary'], correctAnswer: 0, explanation: 'Hedonic wellbeing seeks pleasure; eudaimonic wellbeing seeks meaning, purpose, and self-realisation.' },
    { type: 'multiple_choice', question: 'What is the difference between coaching and therapy?', options: ['Therapy is for weak people', 'Coaching is more effective', 'No difference', 'Coaching helps find answers through questions; therapy treats clinical conditions'], correctAnswer: 3, explanation: 'Coaching facilitates self-discovery; therapy provides clinical treatment for mental health conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Listen 80%, speak 20%', 'Practise 80 minutes daily', 'Agree 80% of the time', 'Speak 80%, listen 20%'], correctAnswer: 0, explanation: 'Effective coaching involves listening far more than speaking — approximately 80% listening.' },
    { type: 'scenario', scenario: 'Someone you are coaching describes persistent low mood for three weeks, loss of interest in activities, and difficulty getting out of bed.', question: 'What should you do?', options: ['Give them a harder training programme', 'Suggest cold exposure therapy', 'Encourage them to seek professional mental health support', 'Tell them to be more positive'], correctAnswer: 2, explanation: 'These symptoms suggest possible depression — this exceeds peer coaching scope and requires professional help.' },
    { type: 'multiple_choice', question: 'What does "periodising mental training" mean?', options: ['Only training mentally on weekdays', 'Alternating between higher stress phases and recovery phases in mental practices', 'Training the same way every day', 'Only practising when motivated'], correctAnswer: 1, explanation: 'Like physical training, mental training benefits from cycling intensity with adequate recovery periods.' },
    { type: 'multiple_choice', question: 'According to the course, what is the ultimate performance metric?', options: ['Perfect execution', 'Maximum intensity', 'Speed of progress', 'Sustainability'], correctAnswer: 3, explanation: 'Sustainability — consistency over years — beats short-term intensity every time.' },
    { type: 'multiple_choice', question: 'What is a values clarification exercise designed to reveal?', options: ['Your core values that should guide decision-making', 'Your personality type', 'Your career path', 'Your fitness level'], correctAnswer: 0, explanation: 'Values clarification identifies your deepest priorities to guide consistent, meaningful decision-making.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "A personal resilience system should be:", options: ['Identical for everyone', 'Rigid and never changing', 'Only focused on stress management', 'Personalised, adaptable, and covering physical, mental, and social domains'], correctAnswer: 3, explanation: 'Effective resilience systems are individualised, cover multiple domains (physical, mental, social, spiritual), and adapt as circumstances change.' },
    { type: 'multiple_choice', question: "Values differ from goals because:", options: ['Goals are permanent; values change daily', 'Values are less important than goals', 'Values are directions to move in; goals are specific destinations', 'There is no difference'], correctAnswer: 2, explanation: 'Values are ongoing directions (e.g., 'be healthy'), while goals are specific outcomes (e.g., 'lose 5kg by June'). Values guide action even after goals are achieved." },
    { type: 'multiple_choice', question: "Teaching a concept to someone else improves your own understanding because:", options: ['It only works for academic subjects', 'It doesn't \u2014 teaching doesn't help learning', 'It forces retrieval practice and exposes knowledge gaps', 'Teaching is purely an altruistic act'], correctAnswer: 2, explanation: 'The 'prot\u00e9g\u00e9 effect' shows that teaching forces active retrieval, reorganisation of knowledge, and identification of gaps \u2014 all of which deepen understanding." },
    { type: 'multiple_choice', question: "Social resilience refers to:", options: ['Training alone to avoid relying on others', 'Avoiding conflict at all costs', 'Only having a large social media following', 'The ability to maintain supportive relationships and set healthy boundaries'], correctAnswer: 3, explanation: 'Social resilience involves cultivating meaningful relationships, communicating effectively, setting healthy boundaries, and giving/receiving support through challenges.' },
    { type: 'multiple_choice', question: "Ikigai (a concept relevant to purpose and meaning) translates roughly as:", options: ['A reason for being \u2014 the intersection of what you love, what you're good at, what the world needs, and what you can be paid for', 'Extreme discipline', 'A Japanese martial art', 'A meditation technique'], correctAnswer: 0, explanation: 'Ikigai is a Japanese concept describing the intersection of passion, mission, vocation, and profession \u2014 providing a sense of purpose and direction in life.' },
    { type: 'multiple_choice', question: "When setbacks occur, the most resilient response is:", options: ['Acknowledge the setback, extract lessons, and recommit to action', 'Blame external factors entirely', 'Pretend it didn't happen', 'Immediately change all goals'], correctAnswer: 0, explanation: 'Resilient individuals acknowledge setbacks without denial, objectively analyse what happened, extract actionable lessons, and recommit to their path forward.' },
    { type: 'multiple_choice', question: "Healthy boundaries in relationships help resilience by:", options: ['Isolating yourself from others', 'Making you more popular', 'Preserving energy, reducing resentment, and clarifying expectations', 'Avoiding all emotional conversations'], correctAnswer: 2, explanation: 'Healthy boundaries protect mental and emotional energy, prevent resentment from overcommitment, and create clarity in relationships \u2014 all supporting long-term resilience.' },
    { type: 'multiple_choice', question: "The Unbreakable philosophy 'Live Without Limits' means:", options: ['There are no consequences to any action', 'Refusing to let self-imposed barriers define what you're capable of becoming', 'Ignoring physical limitations and safety', 'Training as hard as possible regardless of recovery'], correctAnswer: 1, explanation: 'Living without limits means challenging self-imposed beliefs about what you can achieve \u2014 not ignoring reality, but refusing to let fear, doubt, or comfort define your potential.' },

  ],
};

// ── Final Assessment ──
