import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Breathing, cold, heat, journaling, meditation', 'Strength, cardio, flexibility, diet, sleep', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Work, rest, play, eat, sleep'], correctAnswer: 2, explanation: 'The five pillars cover physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'How should you approach implementing the five pillars?', options: ['Only the pillars you enjoy', 'All five simultaneously from day one', 'One pillar per week, building gradually', 'Only during training days'], correctAnswer: 2, explanation: 'Gradual stacking prevents overwhelm and builds sustainable habits.' },
    { type: 'multiple_choice', question: 'What is mental training periodisation?', options: ['Alternating high-intensity and recovery phases, with deload weeks every 4–6 weeks', 'Only training mentally on weekdays', 'Always pushing to maximum', 'Only practising when stressed'], correctAnswer: 0, explanation: 'Like physical training, mental training needs intensity cycling with scheduled recovery.' },
    { type: 'multiple_choice', question: 'What should your protocol specify for difficult life periods?', options: ['Only exercise more', 'Minimum viable doses — even 5 minutes of breathing is better than nothing', 'Stop all practices', 'Double the intensity'], correctAnswer: 1, explanation: 'Minimum viable doses maintain the habit even when full practice is not possible.' },
    { type: 'multiple_choice', question: 'How often should you review your resilience system?', options: ['Only when something goes wrong', 'Never — set it and forget it', 'Annually', 'Weekly quick review, with monthly and quarterly deeper reviews'], correctAnswer: 3, explanation: 'Regular reviews at multiple intervals ensure the system stays relevant and effective.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What does the A-A-A-A setback protocol stand for?', options: ['Assess, Avoid, Accept, Achieve', 'Assess, Accept, Adapt, Act', 'Acknowledge, Adjust, Apply, Advance', 'Avoid, Analyse, Attempt, Achieve'], correctAnswer: 1, explanation: 'Assess reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does reflection differ from rumination?', options: ['They are the same process', 'Reflection is unhealthy', 'Rumination is more productive', 'Reflection produces action points; rumination is circular without resolution'], correctAnswer: 3, explanation: 'Reflection has direction and produces conclusions; rumination loops without progress.' },
    { type: 'multiple_choice', question: 'What should you do if you have been thinking about a setback for 20+ minutes without new insight?', options: ['Go to sleep', 'Keep thinking harder', 'Call a friend to discuss', 'Write down three controllable actions and do one immediately'], correctAnswer: 3, explanation: 'Breaking the rumination cycle requires shifting to concrete, controllable action.' },
    { type: 'multiple_choice', question: 'Is setback recovery a linear process?', options: ['Yes — it follows clear stages', 'It only occurs with therapy', 'It happens instantly', 'No — it oscillates between emotional states with gradually decreasing intensity'], correctAnswer: 3, explanation: 'Recovery is messy and non-linear — good days and bad days are normal throughout the process.' },
    { type: 'multiple_choice', question: 'What is the first practical step after a major setback?', options: ['Ignore it and carry on', 'Make a comprehensive recovery plan', 'Take the smallest meaningful action — one constructive thing today', 'Wait until you feel better'], correctAnswer: 2, explanation: 'The smallest step breaks paralysis and begins momentum — do not wait for a complete plan.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'How harmful is loneliness to health?', options: ['Mildly inconvenient', 'Only affects mental health', 'Has no measurable health impact', 'Equivalent to smoking 15 cigarettes per day'], correctAnswer: 3, explanation: 'Meta-analysis of 300,000+ people found loneliness as damaging as heavy smoking.' },
    { type: 'multiple_choice', question: 'What matters more — relationship quantity or quality?', options: ['Only professional relationships matter', 'Quality — one deeply supportive relationship outweighs a hundred superficial ones', 'Neither matters', 'Quantity — more connections is always better'], correctAnswer: 1, explanation: 'Relationship quality — trust, reciprocity, emotional safety — is more protective than quantity.' },
    { type: 'multiple_choice', question: 'What characterises assertive (not aggressive) communication?', options: ['Yelling your needs', 'Saying nothing to avoid conflict', 'Stating needs clearly without attacking the other person', 'Manipulating others to get what you want'], correctAnswer: 2, explanation: 'Assertive communication is clear and direct while respecting both parties.' },
    { type: 'multiple_choice', question: 'What makes boundaries effective?', options: ['Only setting them when angry', 'Being vague so others can interpret them', 'Being clear, consistent, compassionate, with known consequences', 'Changing them based on others'], correctAnswer: 2, explanation: "Effective boundaries are specific, consistently enforced, kind in delivery, and backed by consequences." },
    { type: 'multiple_choice', question: 'How should you approach curating your social environment?', options: ['Deliberately add growth-supportive connections while managing existing relationships with boundaries', 'Ruthlessly cut everyone who is not perfect', 'Isolate yourself for focus', 'Only socialise with successful people'], correctAnswer: 0, explanation: 'The approach is additive — bring in supportive people while setting appropriate boundaries with others.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['Eudaimonic is about physical health', 'No difference', 'Hedonic is better long-term', 'Hedonic = pleasure/comfort; Eudaimonic = meaning/purpose/potential'], correctAnswer: 3, explanation: 'Hedonic seeks pleasure; eudaimonic seeks meaning — research shows eudaimonic produces deeper, lasting satisfaction.' },
    { type: 'multiple_choice', question: 'How are values best identified?', options: ['By what you say matters', 'By personality tests', 'By what you consistently prioritise when things get difficult', 'By what others value'], correctAnswer: 2, explanation: 'True values are revealed by behaviour under pressure, not by stated preferences.' },
    { type: 'multiple_choice', question: 'What is values-based decision-making?', options: ['Always choosing the easiest option', 'Asking "which option aligns with my core values?" when facing decisions', 'Only making decisions when calm', 'Following rules set by others'], correctAnswer: 1, explanation: 'Using your identified core values as a decision framework cuts through analysis paralysis.' },
    { type: 'multiple_choice', question: 'Why does values-aligned living sustain motivation?', options: ['It requires no effort', 'It eliminates all difficulty', 'It does not', 'It creates a sense of coherence — you are acting in line with who you truly are'], correctAnswer: 3, explanation: 'When actions align with deepest values, intrinsic motivation sustains effort far longer than external rewards.' },
    { type: 'multiple_choice', question: 'What is the values clarification "end of life" exercise?', options: ['Planning your funeral', 'A medical assessment', 'A legal document', 'Imagining looking back at your life and asking what you want to have been true'], correctAnswer: 3, explanation: 'This reflection exercise reveals your deepest values by considering what would matter most in retrospect.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is the key difference between coaching and therapy?', options: ['Therapy is for everyone; coaching is for athletes only', 'Coaching helps find answers through questions; therapy treats clinical conditions', 'Coaching is superior', 'No difference'], correctAnswer: 1, explanation: 'Coaching facilitates self-discovery; therapy provides evidence-based treatment for clinical conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Talk 80%, listen 20%', 'Listen 80%, speak 20%', 'Agree with 80% of what is said', 'Use 80% of the session for exercises'], correctAnswer: 1, explanation: 'Effective coaching involves far more listening than speaking.' },
    { type: 'multiple_choice', question: 'What is a "powerful question"?', options: ['A yes/no question', 'A trick question', 'An open-ended, non-judgemental question that promotes self-discovery', 'A demanding question'], correctAnswer: 2, explanation: 'Powerful questions help others find their own answers, which are more impactful than advice.' },
    { type: 'multiple_choice', question: 'When must you refer to professional help?', options: ['Only if they request it', 'Only in emergencies', 'Never', 'When someone describes persistent low mood, self-harm, panic attacks, or trauma responses'], correctAnswer: 3, explanation: 'Clinical symptoms exceed peer coaching scope and require trained professional intervention.' },
      { type: 'multiple_choice', question: "Why is resisting the urge to give advice important in coaching?", options: ['Option A', 'Option B', 'Option C', 'Option D'], correctAnswer: 0, explanation: "Self-discovered insights create stronger commitment and lasting change than externally given advice." },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'What does "unbreakable" mean in the course philosophy?', options: ['Never feeling pain', 'Being physically invincible', 'Never failing', 'Having the tools and self-awareness to recover from anything and grow stronger'], correctAnswer: 3, explanation: 'Unbreakable means having resilience systems that enable recovery and growth, not invulnerability.' },
    { type: 'multiple_choice', question: 'What is the ultimate performance metric according to the course?', options: ['Speed of progress', 'Maximum intensity', 'Sustainability — consistency over years', 'Perfect technique'], correctAnswer: 2, explanation: '3x/week for 10 years beats 7x/week for 3 months. Sustainability is the ultimate metric.' },
    { type: 'multiple_choice', question: 'What should a lifelong maintenance plan include?', options: ['Whatever you feel like each day', 'Only training', 'Daily non-negotiables, weekly practices, and periodic reviews', 'Only cold exposure'], correctAnswer: 2, explanation: 'A structured plan with daily, weekly, and periodic elements maintains resilience long-term.' },
    { type: 'multiple_choice', question: 'What is the purpose of deload weeks in mental training?', options: ['To prevent psychological burnout and maintain long-term sustainability', 'They are unnecessary', 'To test maximum capacity', 'To lose progress'], correctAnswer: 0, explanation: 'Deload weeks prevent burnout and allow recovery, ensuring practices remain sustainable.' },
    { type: 'multiple_choice', question: 'Where does resilience ultimately live?', options: ['In genetic potential', 'In supplements', 'In the accumulated evidence of who you choose to be, every single day', 'In textbooks'], correctAnswer: 2, explanation: 'Resilience is demonstrated through daily consistent action, not theoretical knowledge.' },
  ]),
];
