import type { UnitAssessment } from '../types';

export const mindsetL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Advanced Focus, Discipline & Cognitive Performance',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is attention residue?', options: ['Leftover attention from sleep', 'Cognitive cost of task-switching — part of your focus remains on the previous task', 'Attention deficit disorder', 'A type of meditation'], correctAnswer: 1, explanation: 'Attention residue means part of your cognitive focus remains on the previous task after switching.' },
    { type: 'multiple_choice', question: 'How many hours of genuine deep work can most people sustain per day?', options: ['3–4 hours', '1–2 hours', '10+ hours', '6–8 hours'], correctAnswer: 0, explanation: 'Research suggests most people can sustain 3–4 hours of truly deep cognitive work daily.' },
    { type: 'multiple_choice', question: 'What does the ego depletion model propose?', options: ['Ego has no effect on decisions', 'Willpower is unlimited', 'The ego grows with use', 'Willpower is a finite resource that gets depleted'], correctAnswer: 3, explanation: "Baumeister\'s model proposed willpower is a depletable resource, though recent research questions the effect size." },
    { type: 'multiple_choice', question: 'What is the most effective solution to decision fatigue?', options: ['Making more decisions to build stamina', 'Designing systems that eliminate unnecessary decisions', 'Drinking coffee', 'Sleeping more'], correctAnswer: 1, explanation: 'Systems and pre-commitment remove the need for decisions, preserving cognitive resources.' },
    { type: 'multiple_choice', question: 'What does BDNF stand for and why is it important?', options: ['Basic Daily Nutritional Formula', 'Brain-Derived Neurotrophic Factor — supports neuron growth and plasticity', 'Body-Dependent Nutritional Factor', 'Brain-Disrupting Neural Function'], correctAnswer: 1, explanation: 'BDNF supports neuronal growth, survival, and synaptic plasticity — critical for learning and brain health.' },
    { type: 'multiple_choice', question: 'What clears metabolic waste from the brain during sleep?', options: ['Blood circulation', 'The glymphatic system', 'The lymphatic system', 'Cerebrospinal breathing'], correctAnswer: 1, explanation: 'The glymphatic system is 10x more active during sleep, clearing amyloid-beta and other waste.' },
    { type: 'multiple_choice', question: 'What are the three basic psychological needs in Self-Determination Theory?', options: ['Physical, emotional, spiritual', 'Autonomy, competence, relatedness', 'Power, achievement, affiliation', 'Food, shelter, safety'], correctAnswer: 1, explanation: 'Deci and Ryan identified autonomy, competence, and relatedness as essential for intrinsic motivation.' },
    { type: 'multiple_choice', question: 'According to James Clear, what is the most effective layer to start behaviour change?', options: ['Outcomes', 'Environment', 'Processes', 'Identity'], correctAnswer: 3, explanation: 'Starting with identity (\'I am someone who...") creates lasting change because behaviour follows belief.' },
    { type: 'multiple_choice', question: 'What type of visualisation is most effective for performance?', options: ['Not visualising at all', 'Outcome visualisation only', 'Process visualisation combined with brief outcome visualisation', 'Visualising relaxation'], correctAnswer: 2, explanation: 'Process visualisation primes neural pathways; brief outcome visualisation sets direction.' },
    { type: 'scenario', scenario: 'An athlete keeps saying "I just need to find my motivation" before training.', question: 'What does motivation science suggest?', options: ['Action precedes motivation — start training and motivation follows', 'They should wait until motivation arrives', 'They need a new programme', 'They should take a month off'], correctAnswer: 0, explanation: 'Motivation follows action, not the other way around. Starting creates the motivation to continue.' },
    { type: 'multiple_choice', question: 'What does creatine supplementation improve cognitively?', options: ['Nothing — it only affects muscles', 'Short-term memory and reasoning, especially under stress or sleep deprivation', 'Emotional regulation', 'Long-term memory only'], correctAnswer: 1, explanation: 'Creatine has cognitive benefits for short-term memory and reasoning, particularly when cognitively stressed.' },
    { type: 'multiple_choice', question: 'What is the motivation spectrum in SDT from least to most self-determined?', options: ['Passive → active', 'Amotivation → external → introjected → identified → integrated → intrinsic', 'Low energy → high energy', 'Intrinsic → extrinsic'], correctAnswer: 1, explanation: 'SDT describes a continuum from amotivation through external regulation to intrinsic motivation.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "'Deep work' (Cal Newport) is defined as:", options: ['Working many hours without breaks', 'Only working on creative tasks', 'Professional activity performed in distraction-free concentration that pushes cognitive capabilities', 'Working in silence'], correctAnswer: 2, explanation: "Deep work is focused, distraction-free cognitive effort that produces high-value output and develops skill \u2014 as opposed to 'shallow work' like email and admin." },
    { type: 'multiple_choice', question: "Decision fatigue leads to:", options: ['Poorer decisions and increased impulsivity as mental energy depletes', 'Better decisions later in the day', 'No measurable effect on performance', 'Improved creative thinking'], correctAnswer: 0, explanation: 'Decision fatigue occurs when the quality of decisions deteriorates after prolonged decision-making. It increases impulsivity, avoidance, and reliance on defaults.' },
    { type: 'multiple_choice', question: "Self-Determination Theory identifies three basic psychological needs:", options: ['Money, status, power', 'Sleep, food, water', 'Autonomy, competence, relatedness', 'Challenge, reward, recognition'], correctAnswer: 2, explanation: "Deci & Ryan's Self-Determination Theory identifies autonomy (control), competence (mastery), and relatedness (connection) as fundamental drivers of intrinsic motivation." },
    { type: 'multiple_choice', question: "Identity-based habit change means:", options: ["Imitating someone else's routine completely", 'Only focusing on outcomes and results', 'Changing habits by changing who you believe you are', 'Changing your legal name'], correctAnswer: 2, explanation: "James Clear argues the most powerful habit change comes from shifting identity: 'I am someone who exercises' rather than 'I want to lose weight' \u2014 behaviour follows identity." },
    { type: 'multiple_choice', question: "Brain-derived neurotrophic factor (BDNF) is:", options: ['A protein that supports neuron growth, learning, and memory \u2014 increased by exercise', 'A type of muscle fibre', 'A hormone that causes stress', "Only relevant to children's brain development"], correctAnswer: 0, explanation: 'BDNF is a key protein for neuroplasticity \u2014 supporting the growth and survival of neurons. Exercise, sleep, and learning all increase BDNF production.' },
    { type: 'multiple_choice', question: "The Pomodoro Technique involves:", options: ['Working for 4 hours straight', '25-minute focused work blocks followed by 5-minute breaks', 'Only working when motivated', 'Using timers to increase speed of work'], correctAnswer: 1, explanation: "The Pomodoro Technique uses 25-minute focused intervals ('pomodoros') with 5-minute breaks, leveraging time-boxing and urgency to sustain concentration." },
    { type: 'multiple_choice', question: "Ego depletion theory suggests:", options: ['The ego makes you stronger', 'Only physical tasks deplete willpower', 'Willpower is unlimited', 'Self-control draws on a limited resource that depletes with use'], correctAnswer: 3, explanation: "Baumeister's ego depletion model proposes that self-control uses a limited mental resource \u2014 acts of willpower in one area reduce availability for subsequent tasks." },
    { type: 'multiple_choice', question: "Visualisation is most effective when it includes:", options: ["Only seeing success in the mind's eye", "Both the process (steps to take) and the outcome (desired result)", "Imagining failure to motivate action", "Visual imagery without any physical practice"], correctAnswer: 1, explanation: "Research shows process visualisation (imagining the steps) combined with outcome visualisation (seeing the end result) is more effective than outcome imagery alone." },

  ],
};
