import type { UnitAssessment } from '../types';

export const nutritionL2Unit1Assessment: UnitAssessment = {
  unitNumber: 1,
  title: 'Unit 1 Assessment — Principles of Healthy Eating',
  passMarkPercent: 80,
  questions: [
    { type: 'multiple_choice', question: 'The Eatwell Guide recommends fruit and vegetables make up approximately what proportion of your diet?', options: ['Just over a third', 'Half', 'A quarter', 'Two-thirds'], correctAnswer: 0, explanation: 'Fruit and vegetables should make up just over a third of your daily food intake according to the Eatwell Guide.' },
    { type: 'multiple_choice', question: 'Which macronutrient provides 9 calories per gram?', options: ['Carbohydrate', 'Fat', 'Protein', 'Alcohol'], correctAnswer: 1, explanation: 'Fat provides 9 calories per gram — more than double the energy density of protein and carbohydrate (4 kcal/g each).' },
    { type: 'multiple_choice', question: 'Vitamin D is important for:', options: ['Red blood cell production', 'Bone health and calcium absorption', 'Protein synthesis', 'Blood clotting'], correctAnswer: 1, explanation: 'Vitamin D aids calcium absorption and is essential for bone health and immune function.' },
    { type: 'multiple_choice', question: 'The UK recommended daily fibre intake for adults is:', options: ['20 grams', '15 grams', '50 grams', '30 grams'], correctAnswer: 3, explanation: 'Adults in the UK are recommended to consume 30 grams of dietary fibre per day.' },
    { type: 'multiple_choice', question: 'Dehydration of 2% body weight during exercise can:', options: ['Have no effect', 'Only affect marathon runners', 'Improve performance', 'Reduce physical and cognitive performance'], correctAnswer: 3, explanation: 'Even mild dehydration impairs physical performance, cognitive function, and increases perceived exertion.' },
    { type: 'multiple_choice', question: 'Oily fish are important because they contain:', options: ['High levels of calcium', 'No fat', 'Vitamin B12 only', 'Omega-3 fatty acids'], correctAnswer: 3, explanation: 'Oily fish (salmon, mackerel, sardines) are rich sources of omega-3 fatty acids, supporting heart and brain health.' },
    { type: 'scenario', question: 'What advice would you give?', scenario: 'A person eats the same three meals every day and feels healthy but is concerned about nutrient gaps.', options: ['Suggest they take supplements instead', 'Recommend variety — eating a wider range of foods reduces the risk of micronutrient deficiencies', 'Tell them to eat more of the same foods', 'If they feel fine, there is no issue'], correctAnswer: 1, explanation: 'Dietary variety is essential for covering the full spectrum of vitamins, minerals, and phytonutrients. Repetitive diets increase deficiency risk.' },
    { type: 'multiple_choice', question: 'The hand method uses your fist to estimate a portion of:', options: ['Vegetables', 'Protein', 'Fat', 'Carbohydrate'], correctAnswer: 3, explanation: 'Your fist approximates a portion of carbohydrate (rice, pasta, potatoes). Your palm is used for protein, thumb for fat.' },
    { type: 'multiple_choice', question: 'A balanced meal should contain:', options: ['Protein and supplements', 'Carbohydrate only', 'Only protein and fat', 'Protein, carbohydrate, fat, and vegetables'], correctAnswer: 3, explanation: 'A balanced meal combines protein, carbohydrate, healthy fat, and vegetables to provide all macronutrients and micronutrients.' },
    { type: 'multiple_choice', question: 'Which vitamin is water-soluble and NOT stored in the body?', options: ['Vitamin C', 'Vitamin A', 'Vitamin D', 'Vitamin K'], correctAnswer: 0, explanation: 'Vitamin C is water-soluble and cannot be stored in the body, requiring regular dietary intake.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "Which macronutrient provides the most energy per gram?", options: ['Protein', 'Carbohydrate', 'Fibre', 'Fat'], correctAnswer: 3, explanation: 'Fat provides 9 kcal per gram, compared to 4 kcal/g for both protein and carbohydrate. Fibre provides approximately 2 kcal/g.' },
    { type: 'multiple_choice', question: "The Eatwell Guide recommends that the largest portion of your plate should be:", options: ['Protein', 'Starchy carbohydrates', 'Dairy', 'Fats and oils'], correctAnswer: 1, explanation: 'The Eatwell Guide recommends starchy carbohydrates (bread, rice, potatoes, pasta) make up about a third of your plate \u2014 the largest single category.' },
    { type: 'multiple_choice', question: "Which vitamin is primarily produced through sunlight exposure?", options: ['Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'], correctAnswer: 0, explanation: 'Vitamin D is synthesised in the skin when exposed to UVB sunlight. Deficiency is common in the UK, especially during winter months.' },
    { type: 'multiple_choice', question: "Dehydration of just 2% body weight can:", options: ['Impair physical performance, concentration, and mood', 'Improve concentration', 'Have no effect on performance', 'Only affect professional athletes'], correctAnswer: 0, explanation: 'Even mild dehydration (2% body weight loss) can impair cognitive function, physical performance, reaction time, and mood.' },
    { type: 'multiple_choice', question: "Complete proteins contain:", options: ["Only one essential amino acid", "All essential amino acids in sufficient quantities", "No amino acids", "Only non-essential amino acids"], correctAnswer: 1, explanation: "Complete proteins (found in meat, fish, eggs, dairy, soya, quinoa) contain all 9 essential amino acids the body cannot make itself." },
    { type: 'multiple_choice', question: "The recommended daily fibre intake for adults is approximately:", options: ['5g', '30g', '10g', '60g'], correctAnswer: 1, explanation: 'UK guidelines recommend approximately 30g of fibre per day for adults, though most people consume far less (average ~18g).' },
    { type: 'multiple_choice', question: "Which mineral is essential for oxygen transport in the blood?", options: ['Calcium', 'Iron', 'Zinc', 'Sodium'], correctAnswer: 1, explanation: "Iron is a key component of haemoglobin, the protein in red blood cells that carries oxygen from the lungs to the body's tissues." },
    { type: 'multiple_choice', question: "Building balanced meals should generally include:", options: ['As much protein as possible, nothing else', 'Only foods with low calories', 'A source of protein, carbohydrate, healthy fat, and vegetables', 'Whatever is cheapest'], correctAnswer: 2, explanation: 'Balanced meals combine protein (for satiety and repair), carbohydrate (for energy), healthy fat (for hormone function and absorption), and vegetables (for micronutrients and fibre).' },
    { type: 'multiple_choice', question: "What does 'portion control' primarily help with?", options: ["Making food taste better", "Managing energy intake without needing to count every calorie", "Eliminating food groups", "Increasing food waste"], correctAnswer: 1, explanation: "Portion control is a practical strategy to manage overall energy intake. Using hands, plates, or visual cues helps regulate serving sizes without obsessive calorie counting." },
    { type: 'multiple_choice', question: "Trans fats are particularly harmful because they:", options: ['Raise LDL cholesterol and lower HDL cholesterol, increasing cardiovascular risk', 'Are found in all natural foods', 'Contain too many calories', 'Are the same as saturated fats'], correctAnswer: 0, explanation: "Artificial trans fats (found in some processed foods) simultaneously raise 'bad' LDL cholesterol and lower 'good' HDL cholesterol \u2014 a uniquely harmful combination for heart health." },

  ],
};
