import type { ChapterQuiz } from '../types';

export const nutritionL2Unit1ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: The Eatwell Guide
  {
    unitNumber: 1, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'How many food groups does the UK Eatwell Guide contain?', options: ['Six', 'Four', 'Three', 'Five'], correctAnswer: 3, explanation: 'The Eatwell Guide divides food into five groups: fruit and vegetables, starchy carbohydrates, protein, dairy and alternatives, and oils and spreads.' },
      { type: 'multiple_choice', question: 'Which food group should make up the largest proportion of your plate according to the Eatwell Guide?', options: ['Protein foods', 'Oils and spreads', 'Fruit and vegetables', 'Dairy and alternatives'], correctAnswer: 2, explanation: 'Fruit and vegetables should make up just over a third of your daily food intake — the largest single group.' },
      { type: 'multiple_choice', question: 'Which of the following is NOT one of the five food groups in the Eatwell Guide?', options: ['Beans, pulses, fish, eggs, meat', 'Supplements and vitamins', 'Dairy and alternatives', 'Starchy carbohydrates'], correctAnswer: 1, explanation: 'Supplements are not a food group in the Eatwell Guide. The guide focuses on whole foods.' },
      { type: 'multiple_choice', question: 'The Eatwell Guide recommends choosing which type of starchy carbohydrates where possible?', options: ['Low-carb alternatives', 'Gluten-free only', 'White and refined', 'Wholegrain or higher-fibre'], correctAnswer: 3, explanation: 'Wholegrain and higher-fibre starchy carbohydrates provide more sustained energy and additional nutrients.' },
      { type: 'scenario', question: 'What is the most appropriate advice to give?', scenario: 'A friend asks you how much fruit and vegetables they should eat each day based on UK guidelines.', options: ['As much as possible with no target', 'At least five portions per day', 'Ten portions per day', 'Two portions per day'], correctAnswer: 1, explanation: 'UK guidelines recommend at least five portions of fruit and vegetables per day, with variety in colour and type.' },
      { type: 'multiple_choice', question: 'Which limitation of the Eatwell Guide is most relevant for regular gym users?', options: ['It excludes all processed foods', 'It was designed for children only', 'It does not include water', 'It does not account for increased protein or calorie needs'], correctAnswer: 3, explanation: 'The Eatwell Guide was designed for the general population and does not account for the increased protein and energy needs of active individuals.' },
      { type: 'multiple_choice', question: 'For whom was the Eatwell Guide primarily designed?', options: ['Elite athletes', 'Pregnant women exclusively', 'People with diabetes only', 'The general UK population aged 2 and above'], correctAnswer: 3, explanation: 'The Eatwell Guide is designed for the general population aged 2 and above as a framework for balanced eating.' },
    ],
  },
  // Chapter 2: Macronutrients Explained
  {
    unitNumber: 1, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which macronutrient provides the most calories per gram?', options: ['Fibre', 'Carbohydrate', 'Fat', 'Protein'], correctAnswer: 2, explanation: 'Fat provides 9 calories per gram, compared to 4 calories per gram for both protein and carbohydrate.' },
      { type: 'multiple_choice', question: 'What is the primary role of protein in the body?', options: ['Providing quick energy', 'Storing excess calories', 'Building and repairing tissues', 'Regulating body temperature'], correctAnswer: 2, explanation: 'Protein is essential for building and repairing body tissues including muscle, skin, hair, and enzymes.' },
      { type: 'multiple_choice', question: 'How many calories does one gram of carbohydrate provide?', options: ['4 calories', '2 calories', '9 calories', '7 calories'], correctAnswer: 0, explanation: 'Carbohydrates provide 4 calories per gram, the same as protein.' },
      { type: 'multiple_choice', question: 'Which of these is a source of complex carbohydrate?', options: ['Honey', 'Fruit juice', 'Table sugar', 'Brown rice'], correctAnswer: 3, explanation: 'Brown rice is a complex carbohydrate that provides sustained energy due to its longer chain structure and fibre content.' },
      { type: 'multiple_choice', question: 'Essential fatty acids must be obtained from the diet because:', options: ['They are only found in animal products', 'They taste better than other fats', 'They are too expensive to supplement', 'The body cannot produce them'], correctAnswer: 3, explanation: 'Essential fatty acids (omega-3 and omega-6) cannot be synthesised by the body and must come from dietary sources.' },
      { type: 'scenario', question: 'What is the best explanation?', scenario: 'Someone tells you they are cutting all fat from their diet to lose weight.', options: ['Fat is essential for hormone production, vitamin absorption, and cell function', 'Fat only matters for brain health', 'This is a good strategy for rapid weight loss', 'You should replace all fat with protein'], correctAnswer: 0, explanation: 'Dietary fat is essential for hormone production, absorption of fat-soluble vitamins (A, D, E, K), and maintaining cell membranes.' },
      { type: 'multiple_choice', question: 'Which macronutrient is the body\'s preferred source of energy during moderate to high intensity exercise?', options: ['Alcohol', 'Protein', 'Fat', 'Carbohydrate'], correctAnswer: 3, explanation: 'Carbohydrate (stored as glycogen) is the body\'s preferred fuel for moderate to high intensity activity.' },
    ],
  },
  // Chapter 3: Micronutrients & Vitamins
  {
    unitNumber: 1, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which vitamin is primarily obtained through sunlight exposure?', options: ['Vitamin C', 'Vitamin B12', 'Vitamin A', 'Vitamin D'], correctAnswer: 3, explanation: 'Vitamin D is synthesised in the skin when exposed to sunlight and is difficult to obtain in sufficient amounts from food alone.' },
      { type: 'multiple_choice', question: 'Iron deficiency is most likely to cause which condition?', options: ['Rickets', 'Anaemia', 'Night blindness', 'Scurvy'], correctAnswer: 1, explanation: 'Iron deficiency anaemia occurs when the body lacks sufficient iron to produce adequate haemoglobin for red blood cells.' },
      { type: 'multiple_choice', question: 'Which mineral is most important for bone health?', options: ['Calcium', 'Potassium', 'Sodium', 'Zinc'], correctAnswer: 0, explanation: 'Calcium is the primary mineral component of bones and teeth, essential for maintaining bone density and strength.' },
      { type: 'multiple_choice', question: 'Fat-soluble vitamins are stored in the body. Which group are they?', options: ['B vitamins and C', 'C, D, E, and iron', 'B1, B6, B12, and folate', 'A, D, E, and K'], correctAnswer: 3, explanation: 'Vitamins A, D, E, and K are fat-soluble, meaning they are stored in body fat and the liver.' },
      { type: 'multiple_choice', question: 'Which vitamin is essential for immune function and is found in citrus fruits?', options: ['Vitamin K', 'Vitamin A', 'Vitamin B12', 'Vitamin C'], correctAnswer: 3, explanation: 'Vitamin C supports immune function, collagen production, and iron absorption. Citrus fruits are a rich source.' },
      { type: 'scenario', question: 'Which micronutrient are they most likely lacking?', scenario: 'A person following a strict vegan diet reports feeling constantly tired and has been told their blood tests show low haemoglobin.', options: ['Vitamin D', 'Calcium', 'Vitamin B12 and/or iron', 'Vitamin C'], correctAnswer: 2, explanation: 'Vegans are at higher risk of B12 and iron deficiency. Both contribute to anaemia and fatigue.' },
      { type: 'multiple_choice', question: 'What is the difference between vitamins and minerals?', options: ['Minerals are only needed in large amounts', 'There is no difference', 'Vitamins come from animals, minerals from plants', 'Vitamins are organic compounds, minerals are inorganic'], correctAnswer: 3, explanation: 'Vitamins are organic compounds that can be broken down by heat or acid. Minerals are inorganic elements that maintain their chemical structure.' },
    ],
  },
  // Chapter 4: Dietary Fibre
  {
    unitNumber: 1, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the UK recommended daily intake of fibre for adults?', options: ['50 grams', '10 grams', '20 grams', '30 grams'], correctAnswer: 3, explanation: 'The UK government recommends 30 grams of fibre per day for adults, though most people consume far less.' },
      { type: 'multiple_choice', question: 'Which type of fibre dissolves in water and can help lower cholesterol?', options: ['Soluble fibre', 'Insoluble fibre', 'Cellulose', 'Resistant starch'], correctAnswer: 0, explanation: 'Soluble fibre dissolves in water to form a gel-like substance, which can help lower blood cholesterol and stabilise blood sugar.' },
      { type: 'multiple_choice', question: 'Which of these foods is the richest source of dietary fibre?', options: ['Chicken breast', 'Lentils', 'Cheddar cheese', 'White bread'], correctAnswer: 1, explanation: 'Lentils are an excellent source of dietary fibre, providing both soluble and insoluble fibre along with protein.' },
      { type: 'multiple_choice', question: 'What is the primary benefit of insoluble fibre?', options: ['Lowering cholesterol', 'Adding bulk to stools and promoting regular bowel movements', 'Increasing vitamin absorption', 'Providing energy'], correctAnswer: 1, explanation: 'Insoluble fibre adds bulk to stools and helps food pass through the digestive system more efficiently.' },
      { type: 'multiple_choice', question: 'Which statement about fibre is correct?', options: ['Fibre provides 9 calories per gram', 'The body fully digests all types of fibre', 'Fibre is only found in animal products', 'Fibre supports gut health and feeds beneficial bacteria'], correctAnswer: 3, explanation: 'Fibre supports gut health by feeding beneficial gut bacteria and promoting regular digestion. It is found exclusively in plant foods.' },
      { type: 'scenario', question: 'What is the most likely issue?', scenario: 'Someone has increased their fibre intake dramatically overnight and is experiencing bloating and discomfort.', options: ['They are eating too much protein', 'They increased fibre too quickly without adequate hydration', 'Fibre is harmful to digestion', 'They need to eliminate fibre entirely'], correctAnswer: 1, explanation: 'Increasing fibre too rapidly can cause bloating and discomfort. It should be increased gradually alongside adequate water intake.' },
    ],
  },
  // Chapter 5: Hydration
  {
    unitNumber: 1, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the general UK recommendation for daily fluid intake?', options: ['1 litre', '6–8 glasses (approximately 1.5–2 litres)', '3 litres minimum', '4 glasses'], correctAnswer: 1, explanation: 'The UK Eatwell Guide recommends 6–8 glasses of fluid per day, approximately 1.5–2 litres, though active individuals may need more.' },
      { type: 'multiple_choice', question: 'Which of these is an early sign of dehydration?', options: ['Improved concentration', 'Dark yellow urine', 'Lower heart rate', 'Increased appetite'], correctAnswer: 1, explanation: 'Dark yellow urine is one of the earliest and most practical indicators of dehydration.' },
      { type: 'multiple_choice', question: 'Water makes up approximately what percentage of the human body?', options: ['60%', '45%', '30%', '80%'], correctAnswer: 0, explanation: 'Water makes up approximately 60% of total body weight in adults, making hydration critical for all bodily functions.' },
      { type: 'multiple_choice', question: 'Which drink is NOT recommended as a primary hydration source?', options: ['Herbal tea', 'Milk', 'Energy drinks high in sugar and caffeine', 'Water'], correctAnswer: 2, explanation: 'Energy drinks high in sugar and caffeine are not ideal hydration sources and may have diuretic effects or cause energy crashes.' },
      { type: 'multiple_choice', question: 'During exercise, dehydration of just 2% body weight can:', options: ['Only affect endurance athletes', 'Have no noticeable effect', 'Reduce physical and cognitive performance', 'Improve performance'], correctAnswer: 2, explanation: 'Even mild dehydration of 2% body weight can impair physical performance, concentration, and increase perceived effort.' },
      { type: 'scenario', question: 'What is the best advice?', scenario: 'A gym member asks whether they should drink water only when they feel thirsty during training.', options: ['Yes, thirst is always a reliable indicator', 'Avoid water during training to prevent stomach cramps', 'No — drink regularly before, during, and after training as thirst often lags behind actual dehydration', 'Only drink after training is complete'], correctAnswer: 2, explanation: 'Thirst is a delayed indicator of dehydration. It is better to drink regularly throughout training rather than waiting until thirsty.' },
    ],
  },
  // Chapter 6: Understanding Food Groups
  {
    unitNumber: 1, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which food group provides the body with the most calcium?', options: ['Fruit and vegetables', 'Dairy and alternatives', 'Oils and spreads', 'Starchy carbohydrates'], correctAnswer: 1, explanation: 'Dairy and its alternatives (fortified plant milks, yoghurts) are the primary dietary source of calcium.' },
      { type: 'multiple_choice', question: 'Oily fish such as salmon and mackerel are important because they provide:', options: ['Calcium', 'Insoluble fibre', 'Omega-3 fatty acids', 'High levels of vitamin C'], correctAnswer: 2, explanation: 'Oily fish are one of the richest sources of omega-3 fatty acids, which support heart health, brain function, and reduce inflammation.' },
      { type: 'multiple_choice', question: 'How many portions of fruit and vegetables are recommended per day in the UK?', options: ['At least five', 'Three', 'Ten', 'Seven'], correctAnswer: 0, explanation: 'The UK recommends at least five portions of fruit and vegetables per day as part of a balanced diet.' },
      { type: 'multiple_choice', question: 'Which of these is a good plant-based protein source?', options: ['Olive oil', 'Butter', 'White rice', 'Chickpeas'], correctAnswer: 3, explanation: 'Chickpeas are an excellent plant-based protein source, also providing fibre, iron, and B vitamins.' },
      { type: 'multiple_choice', question: 'What does "eating the rainbow" refer to?', options: ['Following a specific diet plan', 'Only eating colourful sweets', 'Eating a variety of differently coloured fruits and vegetables', 'Eating one colour of food per day'], correctAnswer: 2, explanation: 'Eating the rainbow means consuming a variety of differently coloured fruits and vegetables to ensure a broad range of vitamins, minerals, and antioxidants.' },
      { type: 'scenario', question: 'What should you recommend?', scenario: 'A person tells you they only eat chicken and rice for every meal because it is "clean eating".', options: ['Remove the rice entirely', 'Add variety — different protein sources, vegetables, fruits, and whole grains for a wider nutrient profile', 'Just add a multivitamin', 'Continue as this is optimal'], correctAnswer: 1, explanation: 'A varied diet ensures a complete range of micronutrients. Relying on the same foods repeatedly increases the risk of nutritional deficiencies.' },
    ],
  },
  // Chapter 7: Portion Control
  {
    unitNumber: 1, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the difference between a "serving size" and a "portion"?', options: ['Serving sizes are only used in America', 'A portion is always smaller than a serving size', 'They are exactly the same thing', 'A serving size is a standardised recommendation; a portion is how much you actually eat'], correctAnswer: 3, explanation: 'A serving size is a standardised amount used on food labels. A portion is the amount you choose to eat, which may be more or less than the serving size.' },
      { type: 'multiple_choice', question: 'The "hand method" of portion estimation uses your palm to approximate:', options: ['Fat portions', 'Vegetable portions', 'Protein portions', 'Carbohydrate portions'], correctAnswer: 2, explanation: 'The hand method uses your palm as a rough guide for protein portions, your fist for carbohydrates, your thumb for fats, and two cupped hands for vegetables.' },
      { type: 'multiple_choice', question: 'Which factor most commonly leads to overeating?', options: ['Drinking water before meals', 'Distracted eating (screens, phones)', 'Using smaller plates', 'Eating too slowly'], correctAnswer: 1, explanation: 'Distracted eating reduces awareness of satiety signals, leading to overconsumption. Mindful eating helps regulate intake.' },
      { type: 'multiple_choice', question: 'What is calorie density?', options: ['The weight of food per calorie', 'The taste intensity of food', 'The number of calories in a given volume or weight of food', 'How quickly food is digested'], correctAnswer: 2, explanation: 'Calorie density refers to the number of calories per unit of weight or volume. Lower calorie-dense foods (fruits, vegetables) allow larger portions for fewer calories.' },
      { type: 'multiple_choice', question: 'Using a smaller plate can help with portion control because:', options: ['Smaller plates are cheaper', 'Food tastes different on smaller plates', 'It makes food cook faster', 'It creates a visual illusion of a fuller plate, promoting satisfaction with less food'], correctAnswer: 3, explanation: 'Research shows that using smaller plates creates a visual cue of a fuller plate, which can reduce overall intake without increasing hunger.' },
      { type: 'scenario', question: 'What is the best response?', scenario: 'Someone is struggling to lose weight despite "eating healthy foods". They do not track portions or calories.', options: ['They should skip meals to compensate', 'Healthy foods cannot cause weight gain', 'They should only eat salads', 'Even healthy foods contribute to weight gain if portions exceed energy needs'], correctAnswer: 3, explanation: 'Even nutrient-dense foods contribute to caloric surplus if consumed in excess. Portion awareness is key to managing energy balance.' },
    ],
  },
  // Chapter 8: Building Balanced Meals
  {
    unitNumber: 1, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'A balanced meal should ideally contain which three macronutrient components?', options: ['Fibre, vitamins, and minerals', 'Protein, carbohydrate, and fat', 'Water, protein, and carbohydrate only', 'Protein, fat, and sugar'], correctAnswer: 1, explanation: 'A balanced meal should contain protein, carbohydrate, and fat in appropriate proportions, along with vegetables for micronutrients and fibre.' },
      { type: 'multiple_choice', question: 'What proportion of your plate should typically be filled with vegetables?', options: ['The entire plate', 'A third', 'A quarter', 'Half'], correctAnswer: 3, explanation: 'Filling half your plate with vegetables ensures adequate micronutrient and fibre intake while keeping calorie density manageable.' },
      { type: 'multiple_choice', question: 'Which meal component is most commonly missing from quick convenience meals?', options: ['Fat', 'Salt', 'Carbohydrate', 'Vegetables and fibre'], correctAnswer: 3, explanation: 'Convenience meals tend to be high in refined carbohydrates and fat but low in vegetables, fibre, and micronutrients.' },
      { type: 'multiple_choice', question: 'Pre-planning meals for the week is known as:', options: ['Calorie counting', 'Intermittent fasting', 'Food cycling', 'Meal prepping'], correctAnswer: 3, explanation: 'Meal prepping involves planning and preparing meals in advance to ensure consistent, balanced nutrition throughout the week.' },
      { type: 'scenario', question: 'What adjustment would make this meal more balanced?', scenario: 'You are building a lunch plate with a large portion of pasta, garlic bread, and a glass of orange juice.', options: ['Add dessert for more variety', 'Add more bread for energy', 'Replace some pasta with vegetables, add a protein source, and choose water instead of juice', 'Remove the pasta entirely'], correctAnswer: 2, explanation: 'The meal is carbohydrate-heavy with no protein or vegetables. Adding a protein source, reducing pasta, and including vegetables would improve balance.' },
      { type: 'multiple_choice', question: 'What is the benefit of including protein at every main meal?', options: ['It prevents all diseases', 'Protein has no specific mealtime benefit', 'It is the only way to lose weight', 'It supports satiety, muscle maintenance, and steady blood sugar'], correctAnswer: 3, explanation: 'Including protein at each meal supports satiety (feeling full), muscle repair and maintenance, and helps stabilise blood sugar levels.' },
    ],
  },
];

// ═══ UNIT 2 CHAPTER QUIZZES — Nutritional Needs Across Life ═══
