import type { UnitAssessment } from '../types';

export const nutritionL2Unit4Assessment: UnitAssessment = {
  unitNumber: 4,
  title: 'Unit 4 Assessment — Planning Balanced Diets',
  passMarkPercent: 80,
  questions: [
    { type: 'multiple_choice', question: 'A SMART goal must be:', options: ['Short, Moderate, Active, Restricted, Tracked', 'Social, Mental, Academic, Reliable, Technical', 'Specific, Measurable, Achievable, Relevant, Time-bound', 'Simple, Meaningful, Attractive, Rapid, Tough'], correctAnswer: 2, explanation: 'SMART stands for Specific, Measurable, Achievable, Relevant, and Time-bound.' },
    { type: 'multiple_choice', question: 'BMR stands for:', options: ['Basal Metabolic Rate', 'Body Mass Ratio', 'Basic Meal Requirement', 'Best Macro Ratio'], correctAnswer: 0, explanation: 'Basal Metabolic Rate is the calories your body burns at complete rest for basic life functions.' },
    { type: 'multiple_choice', question: 'A sustainable rate of weight loss is:', options: ['As fast as possible', '0.5–1kg per week', '5kg per month minimum', '3kg per week'], correctAnswer: 1, explanation: 'A rate of 0.5–1kg per week is sustainable, preserving muscle mass and energy levels.' },
    { type: 'multiple_choice', question: 'Macro tracking monitors your daily intake of:', options: ['Calories only', 'Protein, carbohydrate, and fat', 'Water only', 'Vitamins and minerals'], correctAnswer: 1, explanation: 'Macro tracking focuses on the three macronutrients: protein, carbohydrate, and fat.' },
    { type: 'multiple_choice', question: 'The "80/20" approach means:', options: ['Eating 80% of your plate', '80% protein, 20% carbohydrate', '80 meals per week planned', 'Following your plan 80% of the time with 20% flexibility'], correctAnswer: 3, explanation: 'The 80/20 approach prioritises consistency most of the time while allowing real-life flexibility.' },
    { type: 'multiple_choice', question: '"Detox" diets and juice cleanses:', options: ['Should be done monthly', 'Are recommended by the NHS', 'Have no scientific basis — the liver and kidneys handle detoxification', 'Are scientifically proven to remove toxins'], correctAnswer: 2, explanation: 'There is no scientific evidence that commercial detox products improve natural detoxification, which the liver and kidneys perform continuously.' },
    { type: 'multiple_choice', question: 'Habit stacking is:', options: ['Doing 10 new habits simultaneously', 'Stacking meals together', 'Linking a new habit to an existing routine for consistency', 'A type of meal prep'], correctAnswer: 2, explanation: 'Habit stacking attaches a new behaviour to an established routine, increasing the likelihood of it becoming automatic.' },
    { type: 'scenario', question: 'What should you recommend?', scenario: 'A person has been dieting strictly for 12 weeks and feels exhausted, irritable, and their weight loss has stalled.', options: ['Give up entirely', 'Switch to a liquid diet', 'Consider a diet break or reverse to maintenance calories temporarily, then reassess', 'Diet harder'], correctAnswer: 2, explanation: 'Extended dieting can cause metabolic adaptation and psychological fatigue. A temporary return to maintenance calories allows recovery before resuming.' },
    { type: 'multiple_choice', question: 'Which factor is most important for long-term nutrition success?', options: ['Following a perfect diet', 'Consistency over perfection', 'Taking supplements', 'Eliminating all "bad" foods'], correctAnswer: 1, explanation: 'Consistency with a good-enough approach outperforms sporadic attempts at perfection every time.' },
    { type: 'multiple_choice', question: 'Environment design for nutrition means:', options: ['Only eating at home', 'Arranging your surroundings to make healthy choices easier', 'Painting your kitchen green', 'Buying a bigger kitchen'], correctAnswer: 1, explanation: 'Placing nutritious foods visibly, removing tempting ultra-processed items, and organising your kitchen supports better daily choices.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "A calorie deficit means:", options: ['Eating fewer calories than your body uses, leading to weight loss over time', 'Eating exactly the number of calories your body needs', 'Eating more calories than your body uses', 'Only counting calories from protein'], correctAnswer: 0, explanation: 'A calorie deficit occurs when energy intake is less than energy expenditure, causing the body to use stored energy (fat/glycogen), resulting in weight loss over time.' },
    { type: 'multiple_choice', question: "SMART nutrition goals differ from vague goals because they:", options: ['Are specific, measurable, achievable, relevant, and time-bound', 'Focus only on weight loss', 'Sound more impressive', 'Are set by a nutritionist, not by the individual'], correctAnswer: 0, explanation: "SMART goals provide structure: 'I will eat 3 portions of vegetables daily for the next 4 weeks' vs the vague 'I want to eat healthier'." },
    { type: 'multiple_choice', question: "Macro tracking involves:", options: ['Monitoring the intake of protein, carbohydrates, and fats', 'Weighing yourself daily', 'Tracking micronutrients only', 'Counting only calories'], correctAnswer: 0, explanation: "Macro tracking monitors the three macronutrients \u2014 protein, carbohydrate, and fat \u2014 to ensure they're consumed in proportions that support the individual's goals." },
    { type: 'multiple_choice', question: "The biggest myth about 'detox' diets is:", options: ["They are backed by strong scientific evidence", "The body already has organs (liver, kidneys) that handle detoxification \u2014 commercial detox products are unnecessary", "They only work for athletes", "Juice cleanses provide all necessary nutrients"], correctAnswer: 1, explanation: "The liver and kidneys already detoxify the body continuously. Commercial 'detox' diets have no scientific basis and can be nutritionally inadequate and expensive." },
    { type: 'multiple_choice', question: "Eating out healthily can be achieved by:", options: ["Never eating out", "Choosing grilled over fried, controlling portions, including vegetables, and checking menus in advance", "Only ordering salads", "Fasting before restaurant meals"], correctAnswer: 1, explanation: "Practical eating-out strategies: check menus beforehand, choose grilled/steamed options, include vegetables, control portions, limit liquid calories, and don't feel obligated to finish everything." },
    { type: 'multiple_choice', question: "Sustainable healthy eating is best achieved through:", options: ["Strict short-term dieting followed by returning to old habits", "Small, consistent changes built into daily routine over time", "Eliminating all treats permanently", "Following the most popular diet on social media"], correctAnswer: 1, explanation: "Long-term success comes from gradual habit change \u2014 small, consistent improvements that become automatic, not extreme short-term diets that aren't maintainable." },
    { type: 'multiple_choice', question: "Meal planning helps with nutrition goals because:", options: ['It requires expensive equipment', 'It ensures balanced meals are prepared in advance, reducing impulsive food choices', 'It removes all enjoyment from eating', 'It only works for people who like cooking'], correctAnswer: 1, explanation: 'Meal planning aligns food choices with nutritional goals before hunger or convenience drive decisions \u2014 reducing impulsive, less healthy choices.' },
    { type: 'multiple_choice', question: "Which of these is a common diet myth?", options: ['Drinking water supports hydration', 'You must eat exactly every 3 hours or your metabolism will slow down', 'Fibre helps digestive health', 'Eating more vegetables is generally beneficial'], correctAnswer: 1, explanation: "Meal timing is far less important than total daily intake. The '3-hour eating window' myth has been debunked \u2014 meal frequency should fit the individual's lifestyle and preferences." },
    { type: 'multiple_choice', question: "'Putting it all together' in nutrition planning means:", options: ["Following one strict rule", "Combining knowledge of macros, micros, meal prep, portions, and sustainable habits into a personalised approach", "Copying a celebrity's diet", "Only eating whole foods with zero processed food ever"], correctAnswer: 1, explanation: "Effective nutrition is the integration of multiple principles \u2014 energy balance, nutrient quality, meal planning, portion awareness, and sustainable habits \u2014 personalised to the individual." },
    { type: 'multiple_choice', question: "Why is tracking food intake temporarily useful?", options: ['It should be done forever', 'It replaces the need for exercise', 'It builds awareness of portion sizes, calorie content, and eating patterns', 'It guarantees weight loss'], correctAnswer: 2, explanation: 'Temporary food tracking builds awareness and education \u2014 most people underestimate intake by 30-50%. Once patterns are learned, intuitive eating often becomes more effective.' },

  ],
};
