import type { ChapterQuiz } from '../types';

export const nutritionL2Unit3ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: Food Hygiene Fundamentals
  {
    unitNumber: 3, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What are the "Four Cs" of food hygiene?', options: ['Cooking, Cooling, Cleaning, Covering', 'Cleaning, Cooking, Chilling, Cross-contamination prevention', 'Cleaning, Covering, Cooking, Consuming', 'Cutting, Cooking, Chilling, Checking'], correctAnswer: 1, explanation: 'The Four Cs are Cleaning, Cooking, Chilling, and Cross-contamination prevention — the foundation of food safety.' },
      { type: 'multiple_choice', question: 'At what temperature should a fridge be set to safely store food?', options: ['Below 15°C', 'Below 10°C', 'Below 5°C', 'Below 0°C'], correctAnswer: 2, explanation: 'Fridges should be set below 5°C to slow bacterial growth and keep perishable foods safe.' },
      { type: 'multiple_choice', question: 'How long should you wash your hands for when preparing food?', options: ['2 minutes', 'At least 20 seconds', '10 seconds', '5 seconds'], correctAnswer: 1, explanation: 'Hands should be washed with soap and warm water for at least 20 seconds to effectively remove bacteria.' },
      { type: 'multiple_choice', question: 'Which bacterium is commonly associated with undercooked poultry?', options: ['E. coli', 'Campylobacter', 'Clostridium', 'Listeria'], correctAnswer: 1, explanation: 'Campylobacter is the most common cause of food poisoning in the UK and is frequently found on raw and undercooked poultry.' },
      { type: 'multiple_choice', question: 'Food should be reheated to what core temperature?', options: ['60°C', '70°C or above', '50°C', '100°C'], correctAnswer: 1, explanation: 'Reheated food should reach a core temperature of at least 70°C for 2 minutes (75°C in Scotland) to kill harmful bacteria.' },
      { type: 'scenario', question: 'What is the food safety concern?', scenario: 'You see someone in a kitchen using the same chopping board for raw chicken and then immediately cutting salad vegetables without washing it.', options: ['The vegetables will cook the bacteria away', 'Only the knife needs washing', 'Cross-contamination — raw chicken bacteria can transfer to the ready-to-eat salad', 'No concern — the same board can be used'], correctAnswer: 2, explanation: 'This is a cross-contamination risk. Raw meat bacteria (like salmonella or campylobacter) can transfer to ready-to-eat foods. Separate boards should be used.' },
      { type: 'multiple_choice', question: 'What are the four Cs of food hygiene?', options: ['Calories, carbs, cholesterol, calcium', 'Cut, cook, cool, clean', 'Colour, consistency, cost, convenience', 'Cross-contamination, cleaning, chilling, and cooking'], correctAnswer: 3, explanation: 'The four Cs of food hygiene are: preventing cross-contamination, cleaning properly, chilling foods correctly, and cooking food to the right temperature.' },
      { type: 'multiple_choice', question: 'How long should you wash your hands for effective hygiene?', options: ['5 seconds', 'At least 20 seconds with soap and warm water', 'Hand washing is optional', '1 second under water'], correctAnswer: 1, explanation: '20 seconds of thorough handwashing with soap and warm water effectively removes the majority of harmful bacteria — the "Happy Birthday" song twice is a useful timer.' },
      { type: 'multiple_choice', question: 'When should you wash your hands during food preparation?', options: ['Before handling food, after touching raw meat, after using the toilet, after sneezing, and between tasks', 'Only at the start', 'Only after cooking', 'Hand washing is not necessary during cooking'], correctAnswer: 0, explanation: 'Hands should be washed frequently: before starting, between raw and cooked foods, after using the toilet, touching bins, sneezing, or handling pets.' },
      { type: 'multiple_choice', question: 'What temperature should hot food be served at to be safe?', options: ['Any temperature', 'Above 30°C', 'Room temperature is fine', 'Above 63°C — keeping food above the danger zone prevents bacterial growth'], correctAnswer: 3, explanation: 'Hot food should be held above 63°C — below this temperature, bacteria can multiply rapidly in the danger zone (5–63°C).' },
    
    ],
  },
  // Chapter 2: Food Storage & Temperatures
  {
    unitNumber: 3, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the "danger zone" temperature range for bacterial growth?', options: ['63–100°C', '100°C and above', '0–5°C', '5–63°C'], correctAnswer: 3, explanation: 'The danger zone is 5–63°C. Bacteria multiply most rapidly in this temperature range, so food should be kept below 5°C or above 63°C.' },
      { type: 'multiple_choice', question: 'How quickly should leftover cooked food be refrigerated?', options: ['Within 30 minutes', 'Within 4 hours', 'Within 1–2 hours', 'It does not matter'], correctAnswer: 2, explanation: 'Leftover food should be cooled and refrigerated within 1–2 hours of cooking to minimise time in the danger zone.' },
      { type: 'multiple_choice', question: 'Raw meat should be stored where in the fridge?', options: ['On the bottom shelf, covered', 'Outside the fridge', 'On the top shelf', 'Next to ready-to-eat foods'], correctAnswer: 0, explanation: 'Raw meat should be stored on the bottom shelf of the fridge, covered, to prevent drips contaminating other foods below.' },
      { type: 'multiple_choice', question: 'What is the difference between "use by" and "best before" dates?', options: ['"Best before" is more important for safety', '"Use by" relates to safety; "best before" relates to quality', 'They mean the same thing', '"Use by" only applies to frozen foods'], correctAnswer: 1, explanation: '"Use by" dates are about food safety — eating food after this date can be dangerous. "Best before" relates to quality — food may still be safe but less fresh.' },
      { type: 'multiple_choice', question: 'At what temperature should a freezer operate?', options: ['-18°C or below', '-10°C', '-5°C', '0°C'], correctAnswer: 0, explanation: 'Freezers should operate at -18°C or below to effectively halt bacterial growth and preserve food safely.' },
      { type: 'scenario', question: 'Is this safe?', scenario: 'You leave a cooked chicken curry on the kitchen worktop for 4 hours before putting it in the fridge.', options: ['No — it has been in the danger zone for too long and bacteria may have multiplied to unsafe levels', 'Yes, as long as it is covered', 'Yes, if reheated thoroughly later', 'Only unsafe if it smells bad'], correctAnswer: 0, explanation: 'Food left at room temperature for more than 2 hours is at risk of dangerous bacterial growth. It should have been refrigerated within 1–2 hours.' },
      { type: 'multiple_choice', question: 'What temperature should a fridge be set to?', options: ['10°C', '-18°C', 'Room temperature', '0–5°C'], correctAnswer: 3, explanation: 'Fridges should be set between 0–5°C to keep food below the danger zone and slow bacterial growth effectively.' },
      { type: 'multiple_choice', question: 'What temperature should a freezer be set to?', options: ['-5°C', '-1°C', '0°C', '-18°C or below'], correctAnswer: 3, explanation: 'Freezers should be at -18°C or below — this temperature stops bacterial growth completely (though it does not kill bacteria).' },
      { type: 'multiple_choice', question: 'How should raw meat be stored in the fridge?', options: ['On the top shelf', 'Anywhere is fine', 'On the bottom shelf in a sealed container to prevent juices dripping onto other foods', 'Next to ready-to-eat foods'], correctAnswer: 2, explanation: 'Raw meat goes on the bottom shelf in sealed containers — preventing raw juices from dripping onto ready-to-eat foods below and causing cross-contamination.' },
      { type: 'multiple_choice', question: 'What is the correct order for shelving food in a fridge?', options: ['It does not matter', 'Ready-to-eat foods on top shelves, raw meat on the bottom shelf — preventing cross-contamination from dripping', 'Random order', 'Raw meat on top'], correctAnswer: 1, explanation: 'Fridge order (top to bottom): ready-to-eat foods, dairy, cooked meats, then raw meat at the bottom — preventing cross-contamination from dripping juices.' },
    
    ],
  },
  // Chapter 3: Cross-Contamination
  {
    unitNumber: 3, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Cross-contamination is best defined as:', options: ['Eating food past its best before date', 'The transfer of harmful bacteria from one food or surface to another', 'Mixing different cuisines in one meal', 'Cooking food at the wrong temperature'], correctAnswer: 1, explanation: 'Cross-contamination is the transfer of bacteria or allergens from one food, surface, or piece of equipment to another.' },
      { type: 'multiple_choice', question: 'Which colour chopping board is typically used for raw meat in UK food safety systems?', options: ['Green', 'Blue', 'Red', 'White'], correctAnswer: 2, explanation: 'In the UK colour-coded system, red chopping boards are designated for raw meat to prevent cross-contamination.' },
      { type: 'multiple_choice', question: 'Which of these is an example of indirect cross-contamination?', options: ['Storing food in sealed containers', 'Cooking chicken until fully done', 'Raw chicken dripping onto salad in the fridge', 'Using a knife on raw meat then cutting bread without washing it'], correctAnswer: 3, explanation: 'Indirect cross-contamination occurs via equipment, utensils, or hands — using a contaminated knife without washing it transfers bacteria to other foods.' },
      { type: 'multiple_choice', question: 'How should you clean surfaces after handling raw meat?', options: ['Just blow on it', 'Wipe with a dry cloth', 'Clean with hot soapy water and disinfect', 'Rinse with cold water only'], correctAnswer: 2, explanation: 'Surfaces should be cleaned with hot soapy water and then disinfected to kill remaining bacteria after contact with raw meat.' },
      { type: 'multiple_choice', question: 'Why are allergens a cross-contamination concern?', options: ['Allergens are always visible', 'They only matter in restaurants', 'Even trace amounts transferred to another food can trigger a severe allergic reaction', 'They make food taste bad'], correctAnswer: 2, explanation: 'Even microscopic traces of an allergen transferred via equipment, surfaces, or hands can trigger severe allergic reactions in sensitive individuals.' },
      { type: 'scenario', question: 'What is the risk here?', scenario: 'In a busy kitchen, a chef uses the same tongs to handle raw burgers and then serve cooked ones.', options: ['Serious cross-contamination risk — raw meat bacteria are transferred to the cooked, ready-to-eat burgers', 'The heat from the cooked burgers will kill any bacteria', 'Only a risk if the burgers are undercooked', 'No risk — the burgers are the same food'], correctAnswer: 0, explanation: 'Using the same tongs for raw and cooked meat transfers bacteria from raw meat to the cooked product, creating a serious food safety hazard.' },
      { type: 'multiple_choice', question: 'What is the most common cause of cross-contamination in home kitchens?', options: ['Cooking temperature', 'Using the same chopping board for raw meat and ready-to-eat foods without washing between', 'Storing food incorrectly', 'Buying cheap food'], correctAnswer: 1, explanation: 'The most common cross-contamination route is shared surfaces — particularly chopping boards used for raw meat then salad/bread without thorough cleaning between.' },
      { type: 'multiple_choice', question: 'How can you prevent cross-contamination with chopping boards?', options: ['Only use plastic boards', 'Use separate colour-coded boards for raw meat, vegetables, and cooked foods', 'One board for everything', 'Wipe with a dry cloth between uses'], correctAnswer: 1, explanation: 'Colour-coded boards (red for raw meat, green for vegetables, etc.) eliminate the risk of cross-contamination between food types.' },
      { type: 'multiple_choice', question: 'Can bacteria be transferred from hands to food?', options: ['No — hands are clean', 'Only from raw meat', 'Only visibly dirty hands', 'Yes — hands are one of the main vectors for transferring bacteria between surfaces, foods, and people'], correctAnswer: 3, explanation: 'Hands are one of the primary vectors for bacterial transfer — even clean-looking hands carry bacteria that can contaminate food.' },
      { type: 'multiple_choice', question: 'What should you do with kitchen cloths and sponges to prevent bacterial spread?', options: ['Replace or disinfect regularly — damp cloths and sponges are ideal breeding grounds for bacteria', 'Reuse indefinitely', 'Only wash weekly', 'Cloths cannot harbour bacteria'], correctAnswer: 0, explanation: 'Damp kitchen cloths and sponges are bacterial breeding grounds — replace frequently, use disposable cloths for raw meat areas, and wash reusable cloths at 60°C+.' },
    
    ],
  },
  // Chapter 4: Reading Food Labels
  {
    unitNumber: 3, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'On UK food labels, ingredients are listed in order of:', options: ['Weight — highest to lowest', 'Nutritional importance', 'Alphabetical order', 'Calorie content'], correctAnswer: 0, explanation: 'Ingredients are listed by weight in descending order — the first ingredient is the most abundant by weight.' },
      { type: 'multiple_choice', question: 'The traffic light labelling system on UK food packaging uses which colours?', options: ['Blue, yellow, pink', 'Black, white, grey', 'Purple, orange, teal', 'Red, amber, green'], correctAnswer: 3, explanation: 'The UK traffic light system uses red (high), amber (medium), and green (low) to indicate levels of fat, saturated fat, sugar, and salt per portion.' },
      { type: 'multiple_choice', question: 'What does "per 100g" information on a food label allow you to do?', options: ['Know exactly how much to eat', 'Determine allergen content', 'Compare the nutritional content of different products fairly', 'Calculate cooking times'], correctAnswer: 2, explanation: 'Per 100g values allow fair comparison between products of different sizes and serving amounts.' },
      { type: 'multiple_choice', question: '"Low fat" on a UK food label means the product contains no more than:', options: ['1g fat per 100g', '5g fat per 100g', '10g fat per 100g', '3g fat per 100g'], correctAnswer: 3, explanation: 'Under UK/EU regulations, \'low fat" means the product contains no more than 3g of fat per 100g.' },
      { type: 'multiple_choice', question: 'Which of these is a hidden name for sugar on food labels?', options: ['Maltodextrin', 'Riboflavin', 'Sodium chloride', 'Calcium carbonate'], correctAnswer: 0, explanation: 'Maltodextrin is a form of sugar. Other hidden names include dextrose, fructose, glucose syrup, and high-fructose corn syrup.' },
      { type: 'scenario', question: 'Which product is lower in sugar per 100g?', scenario: 'You are comparing two yoghurts. Product A has 15g sugar per 150g serving. Product B has 8g sugar per 100g.', options: ['They are the same', 'Product A', 'Product B', 'Cannot be determined'], correctAnswer: 2, explanation: 'Product A has 10g sugar per 100g (15g ÷ 1.5), while Product B has 8g per 100g. Product B is lower in sugar per standardised amount.' },
      { type: 'multiple_choice', question: 'What does the traffic light label system show?', options: ['Whether food is organic', 'Allergen information only', 'Cooking instructions', 'Red, amber, and green colours indicating high, medium, and low levels of fat, saturated fat, sugar, and salt per serving'], correctAnswer: 3, explanation: 'Traffic light labels show at a glance whether fat, saturated fat, sugar, and salt are high (red), medium (amber), or low (green) — helping quick, informed choices.' },
      { type: 'multiple_choice', question: 'What does "per 100g" mean on a food label?', options: ['The daily recommended amount', 'The nutritional values for every 100 grams of the product — allowing fair comparison between different products', 'The weight of the package', 'The serving size'], correctAnswer: 1, explanation: 'Per 100g values allow fair comparison between products regardless of package size — it standardises the nutritional information.' },
      { type: 'multiple_choice', question: 'What does the ingredients list on a food label tell you?', options: ['All ingredients listed in descending order by weight — the first ingredient is the most abundant', 'Nothing useful', 'Ingredients in alphabetical order', 'Only allergens'], correctAnswer: 0, explanation: 'Ingredients are listed by weight (highest first) — if sugar appears first or second, the product is predominantly sugar.' },
      { type: 'multiple_choice', question: 'What is the Reference Intake (RI) on food labels?', options: ['A legal requirement for supplements only', 'The minimum you should eat', 'A guideline for the maximum daily amount of calories and nutrients for an average adult', 'Your personal daily needs'], correctAnswer: 2, explanation: 'Reference Intake (RI) shows what percentage of a typical adult\'s daily maximum the product provides — based on an average 2000 kcal diet.' },
    
    ],
  },
  // Chapter 5: Shopping on a Budget
  {
    unitNumber: 3, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which strategy is most effective for reducing food shopping costs?', options: ['Buying only ready meals', 'Planning meals for the week and creating a shopping list', 'Only buying branded products', 'Shopping without a list to find deals'], correctAnswer: 1, explanation: 'Meal planning and shopping with a list reduces impulse purchases and food waste, the two biggest drivers of overspending on food.' },
      { type: 'multiple_choice', question: 'Frozen vegetables are:', options: ['Less nutritious than fresh', 'Only suitable for emergencies', 'Often equally or more nutritious than fresh and more cost-effective', 'Always processed with additives'], correctAnswer: 2, explanation: 'Frozen vegetables are typically frozen at peak freshness, preserving their nutritional content. They are often cheaper and reduce waste.' },
      { type: 'multiple_choice', question: 'Which protein source is typically the most affordable per gram of protein?', options: ['Salmon fillets', 'Steak', 'Protein powder', 'Eggs or tinned beans'], correctAnswer: 3, explanation: 'Eggs, tinned beans, and lentils are among the most affordable protein sources per gram, making them excellent budget-friendly options.' },
      { type: 'multiple_choice', question: 'Buying in bulk is most beneficial when:', options: ['You buy everything in bulk regardless', 'You buy fresh produce in large quantities', 'You buy items you have never tried before', 'You buy non-perishable staples you use regularly'], correctAnswer: 3, explanation: 'Buying non-perishable staples (rice, oats, tinned goods) in bulk saves money over time. Perishable items in bulk can lead to waste.' },
      { type: 'multiple_choice', question: 'What is the most common cause of food waste in UK households?', options: ['Cooking too much and not storing leftovers properly', 'Buying only organic food', 'Buying too little food', 'Eating out too often'], correctAnswer: 0, explanation: 'Over-purchasing and not using leftovers are the biggest contributors to household food waste in the UK.' },
      { type: 'scenario', question: 'What is the most practical advice?', scenario: 'A student tells you they cannot afford to eat healthily and rely on takeaway meals.', options: ['Recommend expensive meal delivery services', 'Suggest they eat less', 'Show them how batch cooking staples like rice, beans, and frozen vegetables can be cheaper than takeaways', 'Agree that healthy eating is expensive'], correctAnswer: 2, explanation: 'Batch cooking with affordable staples is significantly cheaper than takeaways and can be equally convenient with basic planning.' },
      { type: 'multiple_choice', question: 'What is the most effective strategy for shopping on a budget?', options: ['Only shopping at discount stores', 'Buying in bulk always', 'Buying the cheapest items always', 'Planning meals in advance and writing a shopping list to avoid impulse purchases and reduce waste'], correctAnswer: 3, explanation: 'Meal planning + shopping lists reduce impulse buying (up to 30% of supermarket purchases are unplanned) and food waste — the two biggest budget drains.' },
      { type: 'multiple_choice', question: 'Are frozen vegetables as nutritious as fresh?', options: ['No — always inferior', 'Only canned is as good', 'Frozen vegetables have no nutrients', 'Yes — frozen vegetables are often more nutritious than "fresh" because they are frozen at peak ripeness, preserving nutrients'], correctAnswer: 3, explanation: 'Frozen vegetables are picked and frozen at peak ripeness, locking in nutrients — "fresh" supermarket vegetables may have been in transit for days, losing nutrients.' },
      { type: 'multiple_choice', question: 'What is the difference between "use by" and "best before" dates?', options: ['"Best before" is more important', '"Use by" is a safety date (do not eat after); "best before" is a quality date (safe but quality may decrease)', 'Neither matters', 'They mean the same'], correctAnswer: 1, explanation: '"Use by" dates are about safety — eating after risks food poisoning. "Best before" dates are about quality — the food is still safe but may not be at its best.' },
      { type: 'multiple_choice', question: 'How can buying seasonal produce save money?', options: ['In-season produce is more abundant, requires less transportation, and is therefore cheaper and often tastier', 'Season does not affect price', 'Seasonal produce is always expensive', 'Only organic is seasonal'], correctAnswer: 0, explanation: 'Seasonal produce is locally abundant and has lower transportation costs — it is typically cheaper, fresher, and more nutritious than out-of-season alternatives.' },
    
    ],
  },
  // Chapter 6: Batch Cooking & Meal Prep
  {
    unitNumber: 3, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the primary benefit of batch cooking?', options: ['It saves time, money, and ensures consistent nutrition throughout the week', 'It makes food taste better', 'It only works for athletes', 'It eliminates the need for a fridge'], correctAnswer: 0, explanation: 'Batch cooking saves time by preparing multiple meals at once, reduces costs through bulk purchasing, and ensures consistent balanced nutrition.' },
      { type: 'multiple_choice', question: 'How long can most batch-cooked meals be safely stored in the fridge?', options: ['Up to 3–4 days', 'Up to 1 day', 'Indefinitely', 'Up to 2 weeks'], correctAnswer: 0, explanation: 'Most cooked meals can be safely stored in the fridge for 3–4 days when properly cooled and stored in sealed containers.' },
      { type: 'multiple_choice', question: 'When freezing batch-cooked meals, what is important to do?', options: ['Stack them without containers', 'Cool them completely first, then freeze in labelled, portioned containers', 'Freeze them while still hot', 'Only freeze carbohydrate-based meals'], correctAnswer: 1, explanation: 'Food should be cooled completely before freezing, portioned into labelled containers with dates for safe, organised storage.' },
      { type: 'multiple_choice', question: 'Which of these foods freezes well for meal prep?', options: ['Hard-boiled eggs', 'Chilli con carne', 'Salad leaves', 'Cucumber'], correctAnswer: 1, explanation: 'Stews, curries, and chilli freeze excellently. High-water-content foods like salad and cucumber become mushy when defrosted.' },
      { type: 'multiple_choice', question: 'What is the safest way to defrost frozen food?', options: ['Put it directly in a hot oven from frozen', 'Run it under hot water', 'Defrost in the fridge overnight', 'Leave it on the kitchen counter overnight'], correctAnswer: 2, explanation: 'Defrosting in the fridge overnight is the safest method, keeping food below 5°C and out of the danger zone throughout the process.' },
      { type: 'multiple_choice', question: "What adjustment would you suggest?", options: ['Option B', 'Option C', 'Option A', 'Option D'], correctAnswer: 2, explanation: "Freezing portions for later in the week ensures freshness and safety. Only refrigerate what you will eat within 3–4 days." },
      { type: 'multiple_choice', question: 'What is the main advantage of batch cooking?', options: ['Food tastes better in batches', 'It is only for large families', 'Batch cooking is unhealthy', 'It saves time, money, and energy by cooking multiple portions at once — reducing daily cooking decisions'], correctAnswer: 3, explanation: 'Batch cooking saves time (cook once, eat multiple times), money (bulk ingredients cost less), and removes daily cooking decisions that can lead to unhealthy choices.' },
      { type: 'multiple_choice', question: 'How long can batch-cooked meals safely be stored in the fridge?', options: ['24 hours only', '1 week', 'Indefinitely', '3–4 days maximum'], correctAnswer: 3, explanation: 'Most batch-cooked meals are safe in the fridge for 3–4 days — anything planned beyond that should be frozen promptly.' },
      { type: 'multiple_choice', question: 'What foods batch cook well?', options: ['Only soups', 'Only salads', 'No foods batch cook well', 'Stews, curries, chilli, bolognese, rice, roasted vegetables, and grains — foods that reheat well and store safely'], correctAnswer: 3, explanation: 'Best batch-cooking foods are those that reheat well: stews, curries, chilli, grains, roasted vegetables, and sauces. Salads and fried foods do not batch cook as well.' },
      { type: 'multiple_choice', question: 'What is the safest way to cool hot food before refrigerating?', options: ['Cool to room temperature within 2 hours, then refrigerate — divide large portions into smaller containers for faster cooling', 'Cooling is not necessary', 'Leave out overnight to cool', 'Put hot food directly in the fridge'], correctAnswer: 0, explanation: 'Cool food within 2 hours (divide into smaller portions for faster cooling) then refrigerate — putting very hot food in the fridge raises the overall temperature.' },
    
    ],
  },
  // Chapter 7: Meal Prep Fundamentals
  {
    unitNumber: 3, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the first step of effective meal preparation?', options: ['Start cooking immediately', 'Plan your meals and create a shopping list', 'Buy the most expensive ingredients', 'Buy as much food as possible'], correctAnswer: 1, explanation: 'Planning meals and creating a shopping list is the essential first step, ensuring you buy only what you need and maintain nutritional balance.' },
      { type: 'multiple_choice', question: 'Which containers are most suitable for meal prep storage?', options: ['BPA-free, airtight containers with lids', 'Open bowls covered with cling film', 'Any container regardless of seal', 'Plastic bags only'], correctAnswer: 0, explanation: 'BPA-free, airtight containers with secure lids maintain food freshness, prevent contamination, and are safe for reheating.' },
      { type: 'multiple_choice', question: 'How should you organise meals for the week?', options: ['Only prep breakfasts', 'Prepare protein, carbohydrate, and vegetable components separately for flexible combinations', 'Cook everything as one dish', 'Rely on willpower to make good choices daily'], correctAnswer: 1, explanation: 'Preparing components separately allows flexible meal assembly throughout the week and prevents boredom with repetitive meals.' },
      { type: 'multiple_choice', question: 'Which of these is a time-saving meal prep technique?', options: ['Ordering takeaway instead', 'Only eating raw foods', 'Cooking each meal individually from scratch', 'Using a slow cooker or batch roasting multiple trays simultaneously'], correctAnswer: 3, explanation: 'Slow cookers and batch roasting multiple trays at once are efficient techniques that maximise output with minimal active cooking time.' },
      { type: 'scenario', question: 'What is the best approach?', scenario: 'A busy parent says they have no time to meal prep and relies on convenience foods.', options: ['Accept that they cannot eat well', 'Tell them to hire a chef', 'Recommend they skip meals to save time', 'Suggest starting with just 2–3 simple meals prepped on one day, using quick methods like one-pot cooking'], correctAnswer: 3, explanation: 'Starting small with 2–3 simple meals on one day makes meal prep manageable. One-pot cooking minimises preparation and washing up.' },
      { type: 'multiple_choice', question: 'What role does seasoning play in successful meal prep?', options: ['Only salt should be used', 'It is unnecessary', 'Seasoning reduces nutritional value', 'Varied seasoning keeps meals enjoyable and prevents meal prep fatigue'], correctAnswer: 3, explanation: 'Using varied herbs, spices, and seasonings keeps prepped meals enjoyable, reducing the temptation to abandon meal prep due to boredom.' },
      { type: 'multiple_choice', question: 'What containers are best for meal prep?', options: ['Plastic bags only', 'Only cling film', 'Any container', 'BPA-free, microwave-safe, airtight containers with lids — glass containers are ideal for reheating'], correctAnswer: 3, explanation: 'BPA-free, microwave-safe containers with secure lids are ideal — glass containers are preferred for reheating as they do not leach chemicals when heated.' },
      { type: 'multiple_choice', question: 'How can you keep meal prep interesting?', options: ['Change everything every day', 'Only cook your favourite meal', 'Prepare versatile base ingredients that can be combined differently throughout the week', 'Eat the same meals forever'], correctAnswer: 2, explanation: 'Flexible meal prep: cook base ingredients (proteins, grains, roasted veg) that can be recombined with different sauces, spices, and additions for variety without extra effort.' },
      { type: 'multiple_choice', question: 'When is the best time to do weekly meal prep?', options: ['It does not matter', 'Only weekday mornings', 'Every morning', 'A consistent time that works for your schedule — most people choose Sunday afternoon or evening'], correctAnswer: 3, explanation: 'Consistency matters more than the specific day — most people prefer Sunday to prepare for the working week, but any consistent time works.' },
      { type: 'multiple_choice', question: 'What should a beginner focus on when starting meal prep?', options: ['Buy every container available', 'Start small — prep just one or two meals to build the habit before scaling up', 'Follow complex recipes from day one', 'Preparing every meal for the week immediately'], correctAnswer: 1, explanation: 'Start with one or two meals (e.g., lunches only) to build the habit without overwhelm — scale up gradually as the routine becomes established.' },
    
    ],
  },
  // Chapter 8: Kitchen Safety
  {
    unitNumber: 3, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What should you do if a pan of oil catches fire?', options: ['Move it outside quickly', 'Pour water on it', 'Turn off the heat and cover with a damp cloth or fire blanket', 'Blow on it'], correctAnswer: 2, explanation: 'Never put water on an oil fire — it will cause a dangerous flare-up. Turn off the heat and smother with a damp cloth or fire blanket.' },
      { type: 'multiple_choice', question: 'Sharp knives are safer than blunt knives because:', options: ['They look more professional', 'They require less force, giving you more control and reducing the risk of slipping', 'They are more expensive', 'Blunt knives cannot cut food'], correctAnswer: 1, explanation: 'Sharp knives require less pressure, meaning you have greater control and are less likely to slip and cut yourself.' },
      { type: 'multiple_choice', question: 'Which of these is a common kitchen hazard?', options: ['Having good lighting', 'Keeping knives in a block', 'Using oven gloves', 'Wet floors near cooking areas'], correctAnswer: 3, explanation: 'Wet or greasy floors near cooking areas create slip hazards. Spills should be cleaned up immediately.' },
      { type: 'multiple_choice', question: 'When using a microwave, why should you stir food and let it stand?', options: ['Only to improve flavour', 'Microwaves always cook evenly', 'Because microwaves heat unevenly — stirring and standing ensures even temperature distribution', 'To cool it down faster'], correctAnswer: 2, explanation: 'Microwaves can heat food unevenly, creating hot spots. Stirring and standing time allows heat to distribute evenly, ensuring safe temperatures throughout.' },
      { type: 'multiple_choice', question: 'What is the correct way to handle hot pans?', options: ['Use dry, heat-resistant oven gloves or mitts', 'Wait until they cool on the hob', 'Use a tea towel', 'Grab the handle quickly'], correctAnswer: 0, explanation: 'Dry, heat-resistant oven gloves or mitts provide proper protection. Damp cloths can conduct heat and cause burns.' },
      { type: 'scenario', question: 'What should you do?', scenario: 'You notice a frayed electrical cord on a kitchen appliance.', options: ['Only use it for quick tasks', 'Stop using it immediately, unplug it, and have it repaired or replaced', 'Wrap it in tape and carry on', 'Continue using it carefully'], correctAnswer: 1, explanation: 'Frayed electrical cords are a fire and electrocution hazard. The appliance should be unplugged immediately and not used until repaired or replaced.' },
      { type: 'multiple_choice', question: 'What should you do if a grease fire starts in a pan?', options: ['Pour water on it', 'Leave it to burn out', 'Fan it with a towel', 'Turn off the heat and cover with a lid or damp cloth — never use water on a grease fire'], correctAnswer: 3, explanation: 'Water on a grease fire causes a dangerous explosion — turn off the heat and smother with a lid, damp cloth, or fire blanket. Never use water.' },
      { type: 'multiple_choice', question: 'Why should knife handles be kept dry?', options: ['It does not matter', 'Wet handles are slippery and increase the risk of the knife slipping during cutting — causing injury', 'Dry handles last longer', 'To look clean'], correctAnswer: 1, explanation: 'Wet or greasy handles dramatically increase the risk of knives slipping during use — always dry handles before cutting and use a stable cutting surface.' },
      { type: 'multiple_choice', question: 'What is the correct way to carry a knife in the kitchen?', options: ['Blade pointing forward', 'Blade pointing down at your side with the blade facing behind you', 'Blade pointing up', 'Throw it to the counter'], correctAnswer: 1, explanation: 'Carry knives blade-down at your side, blade facing behind you — and announce "behind" when passing other people in the kitchen.' },
      { type: 'multiple_choice', question: 'How can you prevent scalding injuries in the kitchen?', options: ['Use oven gloves, turn pan handles inward, open lids away from you, and be careful with steam', 'There is no prevention', 'Avoid cooking with liquids', 'Only use cold water'], correctAnswer: 0, explanation: 'Prevent scalds by: using oven gloves, turning pan handles to the side (not over the edge or other burners), opening lids away from you, and respecting steam from kettles and pans.' },
    
    ],
  },
];

// ═══ UNIT 4 CHAPTER QUIZZES — Planning Balanced Diets ═══
