import type { ChapterQuiz } from '../types';

export const nutritionL2Unit1ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: The Eatwell Guide
  {
    unitNumber: 1, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'How many food groups does the UK Eatwell Guide contain?', options: ['Six', 'Four', 'Three', 'Five'], correctAnswer: 3, explanation: 'The Eatwell Guide divides food into five groups: fruit and vegetables, starchy carbohydrates, protein, dairy and alternatives, and oils and spreads.' },
      { type: 'multiple_choice', question: 'Which food group should make up the largest proportion of your plate according to the Eatwell Guide?', options: ['Protein foods', 'Oils and spreads', 'Fruit and vegetables', 'Dairy and alternatives'], correctAnswer: 2, explanation: 'Fruit and vegetables should make up just over a third of your daily food intake — the largest single group.' },
      { type: 'multiple_choice', question: 'Which of the following is NOT one of the five food groups in the Eatwell Guide?', options: ['Beans, pulses, fish, eggs, meat', 'Supplements and vitamins', 'Dairy and alternatives', 'Starchy carbohydrates'], correctAnswer: 1, explanation: 'Supplements are not a food group in the Eatwell Guide. The guide focuses on whole foods.' },
      { type: 'multiple_choice', question: 'The Eatwell Guide recommends choosing which type of starchy carbohydrates where possible?', options: ['Low-carb alternatives', 'Gluten-free only', 'White and refined', 'Wholegrain or higher-fibre'], correctAnswer: 3, explanation: 'Wholegrain and higher-fibre starchy carbohydrates provide more sustained energy and additional nutrients.' },
      { type: 'scenario', question: 'What is the most appropriate advice to give?', scenario: 'A friend asks you how much fruit and vegetables they should eat each day based on UK guidelines.', options: ['As much as possible with no target', 'At least five portions per day', 'Ten portions per day', 'Two portions per day'], correctAnswer: 1, explanation: 'UK guidelines recommend at least five portions of fruit and vegetables per day, with variety in colour and type.' },
      { type: 'multiple_choice', question: 'Which limitation of the Eatwell Guide is most relevant for regular gym users?', options: ['It excludes all processed foods', 'It was designed for children only', 'It does not include water', 'It does not account for increased protein or calorie needs'], correctAnswer: 3, explanation: 'The Eatwell Guide was designed for the general population and does not account for the increased protein and energy needs of active individuals.' },
      { type: 'multiple_choice', question: 'For whom was the Eatwell Guide primarily designed?', options: ['Elite athletes', 'Pregnant women exclusively', 'People with diabetes only', 'The general UK population aged 2 and above'], correctAnswer: 3, explanation: 'The Eatwell Guide is designed for the general population aged 2 and above as a framework for balanced eating.' },
      { type: 'multiple_choice', question: 'What percentage of your plate should be fruit and vegetables according to the Eatwell Guide?', options: ['10%', 'Just over a third', 'Half', 'A quarter'], correctAnswer: 1, explanation: 'Fruit and vegetables should make up just over a third of everything you eat — the largest single food group on the plate.' },
      { type: 'multiple_choice', question: 'Which drinks does the Eatwell Guide recommend?', options: ['Sugary drinks and fruit juice', '6–8 glasses of fluid per day, with water, lower-fat milk, and sugar-free drinks as best options', 'Only water', 'Energy drinks'], correctAnswer: 1, explanation: 'The guide recommends 6–8 glasses of fluid daily — water, lower-fat milk, and sugar-free drinks are the healthiest choices.' },
      { type: 'multiple_choice', question: 'Why does the Eatwell Guide place oils and spreads in a small section?', options: ['They are not needed', 'They are high in energy — needed in small amounts for essential fatty acids and fat-soluble vitamin absorption', 'They are unhealthy', 'They should be avoided completely'], correctAnswer: 1, explanation: 'Oils and spreads provide essential fatty acids and help absorb fat-soluble vitamins, but they are energy-dense so only small amounts are needed.' },
    
    ],
  },
  // Chapter 2: Macronutrients Explained
  {
    unitNumber: 1, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which macronutrient provides the most calories per gram?', options: ['Fibre', 'Carbohydrate', 'Fat', 'Protein'], correctAnswer: 2, explanation: 'Fat provides 9 calories per gram, compared to 4 calories per gram for both protein and carbohydrate.' },
      { type: 'multiple_choice', question: 'What is the primary role of protein in the body?', options: ['Providing quick energy', 'Storing excess calories', 'Building and repairing tissues', 'Regulating body temperature'], correctAnswer: 2, explanation: 'Protein is essential for building and repairing body tissues including muscle, skin, hair, and enzymes.' },
      { type: 'multiple_choice', question: 'How many calories does one gram of carbohydrate provide?', options: ['4 calories', '2 calories', '9 calories', '7 calories'], correctAnswer: 0, explanation: 'Carbohydrates provide 4 calories per gram, the same as protein.' },
      { type: 'multiple_choice', question: 'Which of these is a source of complex carbohydrate?', options: ['Honey', 'Fruit juice', 'Table sugar', 'Brown rice'], correctAnswer: 3, explanation: 'Brown rice is a complex carbohydrate that provides sustained energy due to its longer chain structure and fibre content.' },
      { type: 'multiple_choice', question: 'Essential fatty acids must be obtained from the diet because:', options: ['They are only found in animal products', 'They taste better than other fats', 'They are too expensive to supplement', 'The body cannot produce them'], correctAnswer: 3, explanation: 'Essential fatty acids (omega-3 and omega-6) cannot be synthesised by the body and must come from dietary sources.' },
      { type: 'scenario', question: 'What is the best explanation?', scenario: 'Someone tells you they are cutting all fat from their diet to lose weight.', options: ['Fat is essential for hormone production, vitamin absorption, and cell function', 'Fat only matters for brain health', 'This is a good strategy for rapid weight loss', 'You should replace all fat with protein'], correctAnswer: 0, explanation: 'Dietary fat is essential for hormone production, absorption of fat-soluble vitamins (A, D, E, K), and maintaining cell membranes.' },
      { type: 'multiple_choice', question: "Which macronutrient is the body\'s preferred source of energy during moderate to high intensity exercise?", options: ['Alcohol', 'Protein', 'Fat', 'Carbohydrate'], correctAnswer: 3, explanation: "Carbohydrate (stored as glycogen) is the body\'s preferred fuel for moderate to high intensity activity." },
      { type: 'multiple_choice', question: 'How many calories per gram does protein provide?', options: ['9 kcal', '7 kcal', '4 kcal', '2 kcal'], correctAnswer: 2, explanation: 'Protein provides 4 kcal per gram — the same as carbohydrates, but with a higher thermic effect of food.' },
      { type: 'multiple_choice', question: 'What are the three macronutrients?', options: ['Vitamins, minerals, water', 'Carbohydrates, proteins, and fats', 'Fibre, water, electrolytes', 'Iron, calcium, zinc'], correctAnswer: 1, explanation: 'The three macronutrients are carbohydrates, proteins, and fats — they provide energy and are needed in large amounts for body function.' },
      { type: 'multiple_choice', question: 'What is the primary function of carbohydrates in the body?', options: ['Building muscle', 'Providing the body\'s preferred and most efficient source of energy', 'Storing vitamins', 'Regulating temperature'], correctAnswer: 1, explanation: 'Carbohydrates are the body\'s preferred energy source — broken down into glucose to fuel muscles, brain, and organs.' },
    
    ],
  },
  // Chapter 3: Micronutrients & Vitamins
  {
    unitNumber: 1, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which vitamin is primarily obtained through sunlight exposure?', options: ['Vitamin C', 'Vitamin B12', 'Vitamin A', 'Vitamin D'], correctAnswer: 3, explanation: 'Vitamin D is synthesised in the skin when exposed to sunlight and is difficult to obtain in sufficient amounts from food alone.' },
      { type: 'multiple_choice', question: 'Iron deficiency is most likely to cause which condition?', options: ['Rickets', 'Anaemia', 'Night blindness', 'Scurvy'], correctAnswer: 1, explanation: 'Iron deficiency anaemia occurs when the body lacks sufficient iron to produce adequate haemoglobin for red blood cells.' },
      { type: 'multiple_choice', question: 'Which mineral is most important for bone health?', options: ['Calcium', 'Potassium', 'Sodium', 'Zinc'], correctAnswer: 0, explanation: 'Calcium is the primary mineral component of bones and teeth, essential for maintaining bone density and strength.' },
      { type: 'multiple_choice', question: 'Fat-soluble vitamins are stored in the body. Which group are they?', options: ['B vitamins and C', 'C, D, E, and iron', 'B1, B6, B12, and folate', 'A, D, E, and K'], correctAnswer: 3, explanation: 'Vitamins A, D, E, and K are fat-soluble, meaning they are stored in body fat and the liver.' },
      { type: 'multiple_choice', question: 'Which vitamin is essential for immune function and is found in citrus fruits?', options: ['Vitamin K', 'Vitamin A', 'Vitamin B12', 'Vitamin C'], correctAnswer: 3, explanation: 'Vitamin C supports immune function, collagen production, and iron absorption. Citrus fruits are a rich source.' },
      { type: 'scenario', question: 'Which micronutrient are they most likely lacking?', scenario: 'A person following a strict vegan diet reports feeling constantly tired and has been told their blood tests show low haemoglobin.', options: ['Vitamin D', 'Calcium', 'Vitamin B12 and/or iron', 'Vitamin C'], correctAnswer: 2, explanation: 'Vegans are at higher risk of B12 and iron deficiency. Both contribute to anaemia and fatigue.' },
      { type: 'multiple_choice', question: 'What is the difference between vitamins and minerals?', options: ['Minerals are only needed in large amounts', 'There is no difference', 'Vitamins come from animals, minerals from plants', 'Vitamins are organic compounds, minerals are inorganic'], correctAnswer: 3, explanation: 'Vitamins are organic compounds that can be broken down by heat or acid. Minerals are inorganic elements that maintain their chemical structure.' },
      { type: 'multiple_choice', question: 'What is the difference between vitamins and minerals?', options: ['They are the same', 'Vitamins are organic compounds; minerals are inorganic — both are needed in small amounts for vital body functions', 'Minerals provide energy', 'Vitamins are only in supplements'], correctAnswer: 1, explanation: 'Vitamins are organic (can be broken down by heat, acid, or air); minerals are inorganic elements that maintain their chemical structure.' },
      { type: 'multiple_choice', question: 'Which vitamin is important for bone health alongside calcium?', options: ['Vitamin C', 'Vitamin D — it helps the body absorb calcium from food', 'Vitamin B12', 'Vitamin E'], correctAnswer: 1, explanation: 'Vitamin D is essential for calcium absorption — without adequate vitamin D, even high calcium intake cannot maintain bone density.' },
      { type: 'multiple_choice', question: 'Why should you eat a variety of coloured fruits and vegetables?', options: ['For visual appeal only', 'Different colours indicate different micronutrients and antioxidants — variety ensures a broad nutrient profile', 'Colour does not matter', 'Only green vegetables have nutrients'], correctAnswer: 1, explanation: 'Different colours reflect different phytonutrients: red (lycopene), orange (beta-carotene), green (folate), purple (anthocyanins) — variety maximises nutrient intake.' },
    
    ],
  },
  // Chapter 4: Dietary Fibre
  {
    unitNumber: 1, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the UK recommended daily intake of fibre for adults?', options: ['50 grams', '10 grams', '20 grams', '30 grams'], correctAnswer: 3, explanation: 'The UK government recommends 30 grams of fibre per day for adults, though most people consume far less.' },
      { type: 'multiple_choice', question: 'Which type of fibre dissolves in water and can help lower cholesterol?', options: ['Soluble fibre', 'Insoluble fibre', 'Cellulose', 'Resistant starch'], correctAnswer: 0, explanation: 'Soluble fibre dissolves in water to form a gel-like substance, which can help lower blood cholesterol and stabilise blood sugar.' },
      { type: 'multiple_choice', question: 'Which of these foods is the richest source of dietary fibre?', options: ['Chicken breast', 'Lentils', 'Cheddar cheese', 'White bread'], correctAnswer: 1, explanation: 'Lentils are an excellent source of dietary fibre, providing both soluble and insoluble fibre along with protein.' },
      { type: 'multiple_choice', question: 'What is the primary benefit of insoluble fibre?', options: ['Lowering cholesterol', 'Adding bulk to stools and promoting regular bowel movements', 'Increasing vitamin absorption', 'Providing energy'], correctAnswer: 1, explanation: 'Insoluble fibre adds bulk to stools and helps food pass through the digestive system more efficiently.' },
      { type: 'multiple_choice', question: 'Which statement about fibre is correct?', options: ['Fibre provides 9 calories per gram', 'The body fully digests all types of fibre', 'Fibre is only found in animal products', 'Fibre supports gut health and feeds beneficial bacteria'], correctAnswer: 3, explanation: 'Fibre supports gut health by feeding beneficial gut bacteria and promoting regular digestion. It is found exclusively in plant foods.' },
      { type: 'scenario', question: 'What is the most likely issue?', scenario: 'Someone has increased their fibre intake dramatically overnight and is experiencing bloating and discomfort.', options: ['They are eating too much protein', 'They increased fibre too quickly without adequate hydration', 'Fibre is harmful to digestion', 'They need to eliminate fibre entirely'], correctAnswer: 1, explanation: 'Increasing fibre too rapidly can cause bloating and discomfort. It should be increased gradually alongside adequate water intake.' },
      { type: 'multiple_choice', question: 'What are the two main types of dietary fibre?', options: ['Good and bad fibre', 'Soluble fibre (dissolves in water) and insoluble fibre (does not dissolve)', 'Animal and plant fibre', 'Natural and artificial fibre'], correctAnswer: 1, explanation: 'Soluble fibre dissolves in water forming a gel (helps lower cholesterol); insoluble fibre adds bulk to stool (helps prevent constipation).' },
      { type: 'multiple_choice', question: 'What is the UK recommended daily intake of fibre for adults?', options: ['10g', '30g per day', '50g', '5g'], correctAnswer: 1, explanation: 'UK guidelines recommend 30g of fibre per day — most adults only consume about 18g, missing significant health benefits.' },
      { type: 'multiple_choice', question: 'Name three good sources of dietary fibre.', options: ['Chicken, fish, eggs', 'Wholegrain bread, oats, and vegetables', 'Butter, cheese, cream', 'Sugar, honey, syrup'], correctAnswer: 1, explanation: 'Good fibre sources include wholegrains (bread, oats, brown rice), vegetables, fruits, beans, lentils, nuts, and seeds.' },
      { type: 'multiple_choice', question: 'What health benefits does adequate fibre intake provide?', options: ['Only digestive benefits', 'Reduced risk of heart disease, type 2 diabetes, bowel cancer, and improved digestive health', 'It only prevents constipation', 'No proven health benefits'], correctAnswer: 1, explanation: 'Adequate fibre intake reduces risk of cardiovascular disease, type 2 diabetes, and colorectal cancer while supporting healthy digestion and blood sugar control.' },
    
    ],
  },
  // Chapter 5: Hydration
  {
    unitNumber: 1, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the general UK recommendation for daily fluid intake?', options: ['1 litre', '6–8 glasses (approximately 1.5–2 litres)', '3 litres minimum', '4 glasses'], correctAnswer: 1, explanation: 'The UK Eatwell Guide recommends 6–8 glasses of fluid per day, approximately 1.5–2 litres, though active individuals may need more.' },
      { type: 'multiple_choice', question: 'Which of these is an early sign of dehydration?', options: ['Improved concentration', 'Dark yellow urine', 'Lower heart rate', 'Increased appetite'], correctAnswer: 1, explanation: 'Dark yellow urine is one of the earliest and most practical indicators of dehydration.' },
      { type: 'multiple_choice', question: 'Water makes up approximately what percentage of the human body?', options: ['60%', '45%', '30%', '80%'], correctAnswer: 0, explanation: 'Water makes up approximately 60% of total body weight in adults, making hydration critical for all bodily functions.' },
      { type: 'multiple_choice', question: 'Which drink is NOT recommended as a primary hydration source?', options: ['Herbal tea', 'Milk', 'Energy drinks high in sugar and caffeine', 'Water'], correctAnswer: 2, explanation: 'Energy drinks high in sugar and caffeine are not ideal hydration sources and may have diuretic effects or cause energy crashes.' },
      { type: 'multiple_choice', question: 'During exercise, dehydration of just 2% body weight can:', options: ['Only affect endurance athletes', 'Have no noticeable effect', 'Reduce physical and cognitive performance', 'Improve performance'], correctAnswer: 2, explanation: 'Even mild dehydration of 2% body weight can impair physical performance, concentration, and increase perceived effort.' },
      { type: 'scenario', question: 'What is the best advice?', scenario: 'A gym member asks whether they should drink water only when they feel thirsty during training.', options: ['Yes, thirst is always a reliable indicator', 'Avoid water during training to prevent stomach cramps', 'No — drink regularly before, during, and after training as thirst often lags behind actual dehydration', 'Only drink after training is complete'], correctAnswer: 2, explanation: 'Thirst is a delayed indicator of dehydration. It is better to drink regularly throughout training rather than waiting until thirsty.' },
      { type: 'multiple_choice', question: 'How much fluid per day does the UK recommend for adults?', options: ['2 glasses', '6–8 glasses (approximately 1.5–2 litres)', '10 litres', '1 glass'], correctAnswer: 1, explanation: 'The UK recommends 6–8 glasses (approximately 1.5–2 litres) of fluid per day — more in hot weather or during exercise.' },
      { type: 'multiple_choice', question: 'What are the signs of mild dehydration?', options: ['No symptoms', 'Dark urine, headache, fatigue, reduced concentration, and dry mouth', 'Only thirst', 'Dehydration is always obvious'], correctAnswer: 1, explanation: 'Mild dehydration symptoms include darker urine, headache, tiredness, difficulty concentrating, and dry mouth — thirst alone is a late indicator.' },
      { type: 'multiple_choice', question: 'Does tea and coffee count towards daily fluid intake?', options: ['No — caffeine dehydrates you completely', 'Yes — the fluid content outweighs the mild diuretic effect of caffeine', 'Only herbal tea counts', 'Coffee dehydrates more than it hydrates'], correctAnswer: 1, explanation: 'Tea and coffee do count towards fluid intake — while caffeine has a mild diuretic effect, the net fluid contribution is still positive.' },
      { type: 'multiple_choice', question: 'Why is hydration important during exercise?', options: ['Only for long exercise', 'Fluid loss through sweat impairs temperature regulation, cardiovascular function, and performance', 'Water provides energy', 'It is not important for short exercise'], correctAnswer: 1, explanation: 'Even small fluid losses (1–2% body weight) impair thermoregulation and performance — staying hydrated maintains blood volume and cooling capacity.' },
    
    ],
  },
  // Chapter 6: Understanding Food Groups
  {
    unitNumber: 1, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which food group provides the body with the most calcium?', options: ['Fruit and vegetables', 'Dairy and alternatives', 'Oils and spreads', 'Starchy carbohydrates'], correctAnswer: 1, explanation: 'Dairy and its alternatives (fortified plant milks, yoghurts) are the primary dietary source of calcium.' },
      { type: 'multiple_choice', question: 'Oily fish such as salmon and mackerel are important because they provide:', options: ['Calcium', 'Insoluble fibre', 'Omega-3 fatty acids', 'High levels of vitamin C'], correctAnswer: 2, explanation: 'Oily fish are one of the richest sources of omega-3 fatty acids, which support heart health, brain function, and reduce inflammation.' },
      { type: 'multiple_choice', question: 'How many portions of fruit and vegetables are recommended per day in the UK?', options: ['At least five', 'Three', 'Ten', 'Seven'], correctAnswer: 0, explanation: 'The UK recommends at least five portions of fruit and vegetables per day as part of a balanced diet.' },
      { type: 'multiple_choice', question: 'Which of these is a good plant-based protein source?', options: ['Olive oil', 'Butter', 'White rice', 'Chickpeas'], correctAnswer: 3, explanation: 'Chickpeas are an excellent plant-based protein source, also providing fibre, iron, and B vitamins.' },
      { type: 'multiple_choice', question: 'What does "eating the rainbow" refer to?', options: ['Following a specific diet plan', 'Only eating colourful sweets', 'Eating a variety of differently coloured fruits and vegetables', 'Eating one colour of food per day'], correctAnswer: 2, explanation: 'Eating the rainbow means consuming a variety of differently coloured fruits and vegetables to ensure a broad range of vitamins, minerals, and antioxidants.' },
      { type: 'scenario', question: 'What should you recommend?', scenario: 'A person tells you they only eat chicken and rice for every meal because it is "clean eating".', options: ['Remove the rice entirely', 'Add variety — different protein sources, vegetables, fruits, and whole grains for a wider nutrient profile', 'Just add a multivitamin', 'Continue as this is optimal'], correctAnswer: 1, explanation: 'A varied diet ensures a complete range of micronutrients. Relying on the same foods repeatedly increases the risk of nutritional deficiencies.' },
      { type: 'multiple_choice', question: 'What counts as one portion of fruit or vegetables?', options: ['Any amount', '80g of fresh, frozen, or canned, or 30g of dried fruit', 'One whole fruit only', '200g minimum'], correctAnswer: 1, explanation: 'One portion is approximately 80g of fresh, frozen, or canned fruit/vegetables, or 30g of dried fruit. A glass of juice counts as maximum one portion.' },
      { type: 'multiple_choice', question: 'Why should you choose lean sources of protein?', options: ['Lean protein tastes better', 'Lean sources provide protein with less saturated fat — reducing cardiovascular risk', 'All protein is the same', 'Fatty protein is always healthier'], correctAnswer: 1, explanation: 'Lean protein sources (chicken breast, fish, beans, lentils) provide the protein you need with less saturated fat, supporting heart health.' },
      { type: 'multiple_choice', question: 'What are dairy alternatives and who might use them?', options: ['Only for vegans', 'Fortified plant-based milks (soya, oat, almond) used by those with dairy allergies, intolerances, or dietary preferences', 'They are not nutritious', 'Only soya milk exists'], correctAnswer: 1, explanation: 'Dairy alternatives include fortified soya, oat, and almond milks — used by those with lactose intolerance, dairy allergies, or vegan diets. Choose fortified versions for calcium.' },
      { type: 'multiple_choice', question: 'How many portions of oily fish per week are recommended?', options: ['None', 'At least two portions per week, including one of oily fish (salmon, mackerel, sardines)', 'Seven portions daily', 'Only one per month'], correctAnswer: 1, explanation: 'At least two portions of fish per week (one oily) provides omega-3 fatty acids that support heart and brain health.' },
    
    ],
  },
  // Chapter 7: Portion Control
  {
    unitNumber: 1, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the difference between a "serving size" and a "portion"?', options: ['Serving sizes are only used in America', 'A portion is always smaller than a serving size', 'They are exactly the same thing', 'A serving size is a standardised recommendation; a portion is how much you actually eat'], correctAnswer: 3, explanation: 'A serving size is a standardised amount used on food labels. A portion is the amount you choose to eat, which may be more or less than the serving size.' },
      { type: 'multiple_choice', question: 'The "hand method" of portion estimation uses your palm to approximate:', options: ['Fat portions', 'Vegetable portions', 'Protein portions', 'Carbohydrate portions'], correctAnswer: 2, explanation: 'The hand method uses your palm as a rough guide for protein portions, your fist for carbohydrates, your thumb for fats, and two cupped hands for vegetables.' },
      { type: 'multiple_choice', question: 'Which factor most commonly leads to overeating?', options: ['Drinking water before meals', 'Distracted eating (screens, phones)', 'Using smaller plates', 'Eating too slowly'], correctAnswer: 1, explanation: 'Distracted eating reduces awareness of satiety signals, leading to overconsumption. Mindful eating helps regulate intake.' },
      { type: 'multiple_choice', question: 'What is calorie density?', options: ['The weight of food per calorie', 'The taste intensity of food', 'The number of calories in a given volume or weight of food', 'How quickly food is digested'], correctAnswer: 2, explanation: 'Calorie density refers to the number of calories per unit of weight or volume. Lower calorie-dense foods (fruits, vegetables) allow larger portions for fewer calories.' },
      { type: 'multiple_choice', question: 'Using a smaller plate can help with portion control because:', options: ['Smaller plates are cheaper', 'Food tastes different on smaller plates', 'It makes food cook faster', 'It creates a visual illusion of a fuller plate, promoting satisfaction with less food'], correctAnswer: 3, explanation: 'Research shows that using smaller plates creates a visual cue of a fuller plate, which can reduce overall intake without increasing hunger.' },
      { type: 'scenario', question: 'What is the best response?', scenario: 'Someone is struggling to lose weight despite "eating healthy foods". They do not track portions or calories.', options: ['They should skip meals to compensate', 'Healthy foods cannot cause weight gain', 'They should only eat salads', 'Even healthy foods contribute to weight gain if portions exceed energy needs'], correctAnswer: 3, explanation: 'Even nutrient-dense foods contribute to caloric surplus if consumed in excess. Portion awareness is key to managing energy balance.' },
      { type: 'multiple_choice', question: 'What is the difference between a portion and a serving?', options: ['They are always the same', 'A portion is how much you choose to eat; a serving is a standardised recommended amount', 'A serving is always larger', 'There is no difference'], correctAnswer: 1, explanation: 'A serving is a standardised amount (e.g., on a label); a portion is how much you actually eat — portions have grown significantly over time.' },
      { type: 'multiple_choice', question: 'How has portion size changed over the past 20 years?', options: ['Portions have shrunk', 'Portions have significantly increased — plates, drinks, and packaged foods are all larger than 20 years ago', 'No change', 'Only restaurant portions have changed'], correctAnswer: 1, explanation: 'Portion distortion: plate sizes, fast food servings, and packaged foods have all grown significantly — normalising larger portions and increasing calorie intake.' },
      { type: 'multiple_choice', question: 'What is a simple hand-based guide for portion sizes?', options: ['No hand guides exist', 'Palm = protein, fist = carbs, cupped hand = vegetables, thumb = fats', 'Hand size does not relate to portions', 'Only for children'], correctAnswer: 1, explanation: 'Hand-based portions are practical: palm-sized protein, fist-sized carbohydrates, cupped hand of vegetables, and thumb-sized fat portions — scaled to individual body size.' },
      { type: 'multiple_choice', question: 'How does plate size affect how much we eat?', options: ['It has no effect', 'Larger plates make portions look smaller, leading to serving and eating more food', 'Smaller plates increase eating', 'Only colour matters'], correctAnswer: 1, explanation: 'The Delboeuf illusion: food looks smaller on a large plate, leading to larger servings. Using smaller plates is a simple strategy to reduce portion sizes.' },
    
    ],
  },
  // Chapter 8: Building Balanced Meals
  {
    unitNumber: 1, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'A balanced meal should ideally contain which three macronutrient components?', options: ['Fibre, vitamins, and minerals', 'Protein, carbohydrate, and fat', 'Water, protein, and carbohydrate only', 'Protein, fat, and sugar'], correctAnswer: 1, explanation: 'A balanced meal should contain protein, carbohydrate, and fat in appropriate proportions, along with vegetables for micronutrients and fibre.' },
      { type: 'multiple_choice', question: 'What proportion of your plate should typically be filled with vegetables?', options: ['The entire plate', 'A third', 'A quarter', 'Half'], correctAnswer: 3, explanation: 'Filling half your plate with vegetables ensures adequate micronutrient and fibre intake while keeping calorie density manageable.' },
      { type: 'multiple_choice', question: 'Which meal component is most commonly missing from quick convenience meals?', options: ['Fat', 'Salt', 'Carbohydrate', 'Vegetables and fibre'], correctAnswer: 3, explanation: 'Convenience meals tend to be high in refined carbohydrates and fat but low in vegetables, fibre, and micronutrients.' },
      { type: 'multiple_choice', question: 'Pre-planning meals for the week is known as:', options: ['Calorie counting', 'Intermittent fasting', 'Food cycling', 'Meal prepping'], correctAnswer: 3, explanation: 'Meal prepping involves planning and preparing meals in advance to ensure consistent, balanced nutrition throughout the week.' },
      { type: 'scenario', question: 'What adjustment would make this meal more balanced?', scenario: 'You are building a lunch plate with a large portion of pasta, garlic bread, and a glass of orange juice.', options: ['Add dessert for more variety', 'Add more bread for energy', 'Replace some pasta with vegetables, add a protein source, and choose water instead of juice', 'Remove the pasta entirely'], correctAnswer: 2, explanation: 'The meal is carbohydrate-heavy with no protein or vegetables. Adding a protein source, reducing pasta, and including vegetables would improve balance.' },
      { type: 'multiple_choice', question: 'What is the benefit of including protein at every main meal?', options: ['It prevents all diseases', 'Protein has no specific mealtime benefit', 'It is the only way to lose weight', 'It supports satiety, muscle maintenance, and steady blood sugar'], correctAnswer: 3, explanation: 'Including protein at each meal supports satiety (feeling full), muscle repair and maintenance, and helps stabilise blood sugar levels.' },
      { type: 'multiple_choice', question: 'What are the key components of a balanced meal?', options: ['Only protein', 'A source of protein, complex carbohydrates, healthy fats, and plenty of vegetables', 'Carbohydrates only', 'Whatever is available'], correctAnswer: 1, explanation: 'A balanced meal includes all macronutrients: protein (repair), complex carbs (energy), healthy fats (hormones/absorption), and vegetables (micronutrients/fibre).' },
      { type: 'multiple_choice', question: 'Why is meal planning helpful for healthy eating?', options: ['It is not helpful', 'Planning reduces impulsive food choices, saves money, reduces waste, and ensures nutritional balance', 'Only for athletes', 'It is too time-consuming to be worthwhile'], correctAnswer: 1, explanation: 'Meal planning removes the decision point where unhealthy choices happen — it also reduces food waste, saves money, and ensures nutritional variety.' },
      { type: 'multiple_choice', question: 'What is the balanced plate model?', options: ['Eating from a plate', 'A visual guide: half the plate vegetables, quarter protein, quarter starchy carbohydrates', 'Equal portions of everything', 'Only protein matters'], correctAnswer: 1, explanation: 'The balanced plate model is a simple visual guide: fill half your plate with vegetables, a quarter with lean protein, and a quarter with starchy carbohydrates.' },
      { type: 'multiple_choice', question: 'How can you make a takeaway meal more balanced?', options: ['You cannot — all takeaways are unhealthy', 'Add a side of vegetables or salad, choose grilled over fried, and control portion sizes', 'Avoid all takeaways forever', 'Only order salad'], correctAnswer: 1, explanation: 'Takeaways can be balanced by adding vegetables, choosing grilled/steamed options, controlling portions, and not feeling guilty — balance is about overall patterns, not perfection.' },
    
    ],
  },
];

// ═══ UNIT 2 CHAPTER QUIZZES — Nutritional Needs Across Life ═══
