import type { UnitAssessment } from '../types';

export const nutritionL2Unit2Assessment: UnitAssessment = {
  unitNumber: 2,
  title: 'Unit 2 Assessment — Nutritional Needs Across Life',
  passMarkPercent: 80,
  questions: [
    { type: 'multiple_choice', question: 'Peak bone mass is primarily established during:', options: ['Old age', 'Middle age', 'Adolescence', 'Infancy'], correctAnswer: 2, explanation: 'Adolescence is the critical period for establishing peak bone mass, making calcium intake during this time essential.' },
    { type: 'multiple_choice', question: 'Sarcopenia refers to:', options: ['Age-related vision loss', 'Bone softening', 'A childhood disease', 'Age-related muscle mass loss'], correctAnswer: 3, explanation: 'Sarcopenia is the progressive loss of skeletal muscle mass and strength associated with ageing.' },
    { type: 'multiple_choice', question: 'Folic acid supplementation is recommended before and during early pregnancy to prevent:', options: ['Miscarriage', 'Gestational diabetes', 'Neural tube defects', 'Anaemia'], correctAnswer: 2, explanation: 'Folic acid significantly reduces the risk of neural tube defects such as spina bifida.' },
    { type: 'multiple_choice', question: 'Which nutrient must vegans supplement?', options: ['Vitamin B12', 'Vitamin C', 'Iron', 'Calcium'], correctAnswer: 0, explanation: 'Vitamin B12 is found almost exclusively in animal products and must be supplemented on a vegan diet.' },
    { type: 'multiple_choice', question: 'Halal dietary law prohibits:', options: ['All dairy', 'Pork and alcohol', 'Wheat and gluten', 'All meat'], correctAnswer: 1, explanation: 'Halal law prohibits pork, alcohol, and meat not slaughtered according to Islamic guidelines.' },
    { type: 'multiple_choice', question: 'How many major allergens must be declared on UK food labels?', options: ['10', '8', '20', '14'], correctAnswer: 3, explanation: 'UK food law requires 14 major allergens to be declared on food labels.' },
    { type: 'multiple_choice', question: 'Active individuals typically need more:', options: ['Fat and less carbohydrate', 'Calories, protein, and fluids', 'Supplements only', 'Sleep and less food'], correctAnswer: 1, explanation: 'Higher activity levels increase requirements for energy, protein, and hydration.' },
    { type: 'scenario', question: 'What should you do?', scenario: 'A client with newly diagnosed Type 1 diabetes asks you to create a meal plan for managing their blood sugar.', options: ['Tell them to avoid all sugar', 'Create a detailed diabetes meal plan', 'Research diabetes diets and try your best', 'Refer them to a registered dietitian who specialises in diabetes management'], correctAnswer: 3, explanation: 'Medical nutrition therapy for diabetes is outside the scope of a general nutrition adviser. Referral to a specialist is essential.' },
    { type: 'multiple_choice', question: 'Iron from plant sources is called:', options: ['Non-haem iron', 'Haem iron', 'Complete iron', 'Ferrous iron'], correctAnswer: 0, explanation: 'Plant-based iron is non-haem iron, which is less readily absorbed than haem iron from animal sources.' },
    { type: 'multiple_choice', question: 'Vitamin C enhances the absorption of:', options: ['Non-haem iron', 'Calcium', 'Vitamin D', 'Zinc'], correctAnswer: 0, explanation: 'Vitamin C significantly improves the absorption of non-haem iron from plant sources when consumed together.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "Children have higher energy needs per kilogram of body weight because:", options: ['They are less efficient at digestion', 'They eat more sugar', 'They exercise more than adults', 'They are still growing and developing'], correctAnswer: 3, explanation: 'Children need more energy relative to body size to support growth, brain development, and the higher metabolic demands of a developing body.' },
    { type: 'multiple_choice', question: "Older adults are particularly at risk of deficiency in:", options: ['Vitamin D, calcium, and protein', 'Vitamin A and zinc', 'Omega-3 fats only', 'Carbohydrates'], correctAnswer: 0, explanation: 'Older adults commonly face deficiencies in vitamin D (less sun exposure, reduced skin synthesis), calcium (bone health), and protein (sarcopenia prevention).' },
    { type: 'multiple_choice', question: "During pregnancy, which nutrient is critical for preventing neural tube defects?", options: ['Vitamin C', 'Folic acid (folate)', 'Iron', 'Calcium'], correctAnswer: 1, explanation: 'Folic acid (400mcg daily before conception and in early pregnancy) significantly reduces the risk of neural tube defects like spina bifida.' },
    { type: 'multiple_choice', question: "A vegan diet requires particular attention to:", options: ['Carbohydrate intake', 'Fibre intake', 'Protein only', 'Vitamin B12, iron, calcium, omega-3, and zinc'], correctAnswer: 3, explanation: 'Vegans must plan for nutrients primarily found in animal products: B12 (supplementation essential), iron (plant sources less bioavailable), calcium, omega-3 (ALA/EPA/DHA), and zinc.' },
    { type: 'multiple_choice', question: "Food allergies differ from food intolerances because allergies:", options: ["Are less serious", "Involve an immune system response that can be life-threatening", "Only cause digestive symptoms", "Are caused by eating too much of a food"], correctAnswer: 1, explanation: "Food allergies trigger an immune-mediated response (potentially anaphylaxis), while intolerances typically cause digestive discomfort without immune system involvement." },
    { type: 'multiple_choice', question: "The 14 major food allergens in UK law include:", options: ['Only peanuts and shellfish', 'Only gluten and nuts', 'Gluten, dairy, and sugar', 'Gluten, milk, eggs, nuts, peanuts, soya, fish, shellfish, celery, mustard, sesame, sulphites, lupin, molluscs'], correctAnswer: 3, explanation: 'UK food law (Natasha's Law) requires all 14 allergens to be clearly labelled: cereals containing gluten, crustaceans, eggs, fish, peanuts, soybeans, milk, nuts, celery, mustard, sesame, sulphites, lupin, and molluscs." },
    { type: 'multiple_choice', question: "Athletes need more protein than sedentary individuals primarily for:", options: ['Taste preferences', 'Improving sleep quality', 'Muscle repair, recovery, and adaptation to training', 'Reducing body temperature'], correctAnswer: 2, explanation: 'Athletes need 1.2\u20132.0g protein per kg body weight (vs ~0.8g for sedentary) to support muscle protein synthesis, repair exercise-induced damage, and support training adaptations.' },
    { type: 'multiple_choice', question: "Cultural and religious dietary practices should be:", options: ['Ignored in nutrition advice', 'Only considered for specific populations', 'Changed to match standard guidelines', 'Respected and accommodated while ensuring nutritional adequacy'], correctAnswer: 3, explanation: 'Effective nutrition advice respects cultural and religious dietary practices (halal, kosher, Hindu vegetarianism, Ramadan fasting) while ensuring nutritional needs are met.' },
    { type: 'multiple_choice', question: "Lactose intolerance is:", options: ['An inability to fully digest lactose due to insufficient lactase enzyme', 'An immune-mediated allergy to milk', 'Dangerous and life-threatening', 'Only found in children'], correctAnswer: 0, explanation: 'Lactose intolerance results from insufficient lactase enzyme, causing digestive symptoms (bloating, gas, diarrhoea) when consuming dairy \u2014 it's an intolerance, not an allergy." },
    { type: 'multiple_choice', question: "When advising a vegetarian athlete on protein, you should:", options: ['Tell them they can't get enough protein without meat', 'Only recommend dairy protein', 'Suggest they become vegan instead', 'Recommend combining varied plant protein sources and possibly supplementing B12'], correctAnswer: 3, explanation: 'Vegetarian athletes can meet protein needs through varied sources: eggs, dairy, legumes, tofu, tempeh, quinoa, and combining complementary plant proteins. B12 monitoring is important.' },

  ],
};
