import type { UnitAssessment } from '../types';

export const nutritionL2Unit3Assessment: UnitAssessment = {
  unitNumber: 3,
  title: 'Unit 3 Assessment — Food Safety & Practical Skills',
  passMarkPercent: 80,
  questions: [
    { type: 'multiple_choice', question: 'The danger zone for bacterial growth is:', options: ['63–100°C', '0–5°C', '5–63°C', 'Above 100°C'], correctAnswer: 2, explanation: 'Bacteria multiply most rapidly between 5°C and 63°C — the danger zone.' },
    { type: 'multiple_choice', question: 'Raw meat should be stored on which shelf of the fridge?', options: ['Any shelf', 'Top shelf', 'Bottom shelf', 'Middle shelf'], correctAnswer: 2, explanation: 'Raw meat should be stored on the bottom shelf to prevent drips contaminating other foods.' },
    { type: 'multiple_choice', question: 'Cross-contamination is:', options: ['Cooking food too long', 'Using too much seasoning', 'Eating expired food', 'Transfer of bacteria from one surface or food to another'], correctAnswer: 3, explanation: 'Cross-contamination is the transfer of harmful bacteria between foods, surfaces, or equipment.' },
    { type: 'multiple_choice', question: 'On UK food labels, ingredients are listed by:', options: ['Nutritional value', 'Calorie content', 'Alphabetical order', 'Weight — highest to lowest'], correctAnswer: 3, explanation: 'Ingredients are listed in descending order of weight, so the first ingredient is the most abundant.' },
    { type: 'multiple_choice', question: 'Frozen vegetables compared to fresh are:', options: ['Only suitable for cooking, not eating', 'Always less nutritious', 'Unsafe to eat', 'Often equally nutritious and more cost-effective'], correctAnswer: 3, explanation: 'Frozen vegetables are typically frozen at peak freshness and retain comparable nutritional content to fresh.' },
    { type: 'multiple_choice', question: 'Batch-cooked meals can be safely stored in the fridge for:', options: ['Indefinitely', '2 weeks', '3–4 days', '1 day'], correctAnswer: 2, explanation: 'Most cooked meals are safe in the fridge for 3–4 days when properly cooled and stored.' },
    { type: 'multiple_choice', question: 'The safest way to defrost food is:', options: ['On the kitchen counter', 'In the fridge overnight', 'In direct sunlight', 'Under hot water'], correctAnswer: 1, explanation: 'Defrosting in the fridge maintains safe temperatures throughout the process.' },
    { type: 'scenario', question: 'What is the safety concern?', scenario: 'A sharp knife is left in a sink full of soapy water.', options: ['No concern', 'It will rust', 'Soapy water cleans it better', 'It is a cut hazard — knives should be washed separately and stored safely'], correctAnswer: 3, explanation: 'Submerged knives in soapy water are invisible and pose a serious cut risk. They should be washed separately and stored safely.' },
    { type: 'multiple_choice', question: 'What should you do if a pan of oil catches fire?', options: ['Blow on it', 'Turn off the heat and smother with a fire blanket', 'Move it to the sink', 'Pour water on it'], correctAnswer: 1, explanation: 'Water on an oil fire causes a dangerous flare-up. Turn off the heat and smother with a fire blanket or damp cloth.' },
    { type: 'multiple_choice', question: '"Use by" dates relate to:', options: ['Food safety — eating after this date is potentially dangerous', 'Food quality only', 'Packaging appearance', 'Selling regulations only'], correctAnswer: 0, explanation: '"Use by" dates are about food safety. Consuming food after this date risks foodborne illness.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "The temperature danger zone for bacterial growth in food is:", options: ['-18\u00b0C to 0\u00b0C', '0\u00b0C to 5\u00b0C', '63\u00b0C to 100\u00b0C', '5\u00b0C to 63\u00b0C'], correctAnswer: 3, explanation: "Bacteria multiply most rapidly between 5\u00b0C and 63\u00b0C \u2014 the 'danger zone'. Food should be kept below 5\u00b0C (fridge) or above 63\u00b0C (hot holding) to minimise risk." },
    { type: 'multiple_choice', question: "Cross-contamination is best prevented by:", options: ['Using the same chopping board for everything', 'Cooking everything at the same temperature', 'Washing hands thoroughly and using separate boards for raw meat and ready-to-eat foods', 'Storing raw meat above cooked food in the fridge'], correctAnswer: 2, explanation: 'Cross-contamination prevention: separate chopping boards (colour-coded), wash hands between handling raw and cooked food, store raw meat below ready-to-eat foods.' },
    { type: 'multiple_choice', question: "When reading food labels, ingredients are listed:", options: ['In alphabetical order', 'By nutritional value', 'Randomly', 'By weight, from highest to lowest'], correctAnswer: 3, explanation: 'UK food labelling law requires ingredients to be listed in descending order of weight \u2014 the first ingredient makes up the largest proportion of the product.' },
    { type: 'multiple_choice', question: "'Use by' dates indicate:", options: ["When food tastes best", "The last date food is safe to eat \u2014 after this it may be unsafe", "A suggestion that can be ignored", "When food should be frozen"], correctAnswer: 1, explanation: "'Use by' dates are safety dates \u2014 food should not be eaten after this date as it may pose a health risk. 'Best before' dates relate to quality, not safety." },
    { type: 'multiple_choice', question: "Batch cooking helps with healthy eating by:", options: ['Preparing multiple portions in advance, saving time and reducing reliance on convenience food', 'Making food taste worse', 'Using more energy than cooking each meal separately', 'Only working for vegetarian meals'], correctAnswer: 0, explanation: 'Batch cooking prepares multiple portions at once, ensuring healthy meals are readily available \u2014 reducing the temptation for convenience food when time or energy is low.' },
    { type: 'multiple_choice', question: "Which cleaning step kills most food-borne bacteria?", options: ['Rinsing with cold water', 'Wiping with a dry cloth', 'Blowing on the surface', 'Using hot soapy water or food-safe sanitiser'], correctAnswer: 3, explanation: 'Hot soapy water or food-safe sanitiser kills most bacteria on surfaces and equipment. Cold water rinsing alone does not effectively remove or kill bacteria.' },
    { type: 'multiple_choice', question: "Food should be reheated to a core temperature of at least:", options: ['50\u00b0C', '60\u00b0C', '100\u00b0C', '70\u00b0C'], correctAnswer: 3, explanation: 'Reheated food must reach a core temperature of at least 70\u00b0C for 2 minutes (75\u00b0C in Scotland) to kill harmful bacteria. Food should only be reheated once.' },
    { type: 'multiple_choice', question: "Meal prep fundamentals include:", options: ['Planning meals, shopping with a list, batch cooking, and proper storage', 'Cooking only one food and eating it all week', 'Buying pre-made meals only', 'Spending the entire weekend cooking'], correctAnswer: 0, explanation: 'Effective meal prep involves: planning meals for the week, shopping with a list to reduce waste, batch cooking proteins and staples, and using proper storage containers.' },
    { type: 'multiple_choice', question: "Shopping on a budget for healthy eating involves:", options: ['Only buying the cheapest processed food', 'Skipping fresh food entirely', 'Buying seasonal produce, frozen vegetables, store-brand staples, and reducing food waste', 'Only shopping at expensive health food stores'], correctAnswer: 2, explanation: 'Budget-friendly healthy eating: buy seasonal produce, use frozen vegetables (nutritionally equivalent to fresh), choose store-brand staples, plan meals to reduce waste, and buy in bulk.' },
    { type: 'multiple_choice', question: "Kitchen safety includes:", options: ['Keeping knives sharp (not blunt), wiping spills immediately, and knowing fire safety procedures', 'Only wearing shoes in the kitchen', 'Using the microwave for everything', 'Avoiding the kitchen as much as possible'], correctAnswer: 0, explanation: 'Kitchen safety essentials: sharp knives (blunt ones slip), immediate spill cleanup, correct fire procedures (never water on oil fires), proper equipment handling, and first aid knowledge.' },

  ],
};
