import type { ChapterQuiz } from '../types';

export const nutritionL2Unit3ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: Food Hygiene Fundamentals
  {
    unitNumber: 3, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What are the "Four Cs" of food hygiene?', options: ['Cleaning, Covering, Cooking, Consuming', 'Cleaning, Cooking, Chilling, Cross-contamination prevention', 'Cutting, Cooking, Chilling, Checking', 'Cooking, Cooling, Cleaning, Covering'], correctAnswer: 1, explanation: 'The Four Cs are Cleaning, Cooking, Chilling, and Cross-contamination prevention — the foundation of food safety.' },
      { type: 'multiple_choice', question: 'At what temperature should a fridge be set to safely store food?', options: ['Below 10°C', 'Below 0°C', 'Below 5°C', 'Below 15°C'], correctAnswer: 2, explanation: 'Fridges should be set below 5°C to slow bacterial growth and keep perishable foods safe.' },
      { type: 'multiple_choice', question: 'How long should you wash your hands for when preparing food?', options: ['5 seconds', '10 seconds', 'At least 20 seconds', '2 minutes'], correctAnswer: 2, explanation: 'Hands should be washed with soap and warm water for at least 20 seconds to effectively remove bacteria.' },
      { type: 'multiple_choice', question: 'Which bacterium is commonly associated with undercooked poultry?', options: ['Listeria', 'E. coli', 'Campylobacter', 'Clostridium'], correctAnswer: 2, explanation: 'Campylobacter is the most common cause of food poisoning in the UK and is frequently found on raw and undercooked poultry.' },
      { type: 'multiple_choice', question: 'Food should be reheated to what core temperature?', options: ['100°C', '60°C', '50°C', '70°C or above'], correctAnswer: 3, explanation: 'Reheated food should reach a core temperature of at least 70°C for 2 minutes (75°C in Scotland) to kill harmful bacteria.' },
      { type: 'scenario', question: 'What is the food safety concern?', scenario: 'You see someone in a kitchen using the same chopping board for raw chicken and then immediately cutting salad vegetables without washing it.', options: ['Only the knife needs washing', 'No concern — the same board can be used', 'Cross-contamination — raw chicken bacteria can transfer to the ready-to-eat salad', 'The vegetables will cook the bacteria away'], correctAnswer: 2, explanation: 'This is a cross-contamination risk. Raw meat bacteria (like salmonella or campylobacter) can transfer to ready-to-eat foods. Separate boards should be used.' },
    ],
  },
  // Chapter 2: Food Storage & Temperatures
  {
    unitNumber: 3, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the "danger zone" temperature range for bacterial growth?', options: ['0–5°C', '63–100°C', '5–63°C', '100°C and above'], correctAnswer: 2, explanation: 'The danger zone is 5–63°C. Bacteria multiply most rapidly in this temperature range, so food should be kept below 5°C or above 63°C.' },
      { type: 'multiple_choice', question: 'How quickly should leftover cooked food be refrigerated?', options: ['Within 30 minutes', 'It does not matter', 'Within 4 hours', 'Within 1–2 hours'], correctAnswer: 3, explanation: 'Leftover food should be cooled and refrigerated within 1–2 hours of cooking to minimise time in the danger zone.' },
      { type: 'multiple_choice', question: 'Raw meat should be stored where in the fridge?', options: ['Next to ready-to-eat foods', 'Outside the fridge', 'On the bottom shelf, covered', 'On the top shelf'], correctAnswer: 2, explanation: 'Raw meat should be stored on the bottom shelf of the fridge, covered, to prevent drips contaminating other foods below.' },
      { type: 'multiple_choice', question: 'What is the difference between "use by" and "best before" dates?', options: ['"Use by" relates to safety; "best before" relates to quality', 'They mean the same thing', '"Use by" only applies to frozen foods', '"Best before" is more important for safety'], correctAnswer: 0, explanation: '"Use by" dates are about food safety — eating food after this date can be dangerous. "Best before" relates to quality — food may still be safe but less fresh.' },
      { type: 'multiple_choice', question: 'At what temperature should a freezer operate?', options: ['0°C', '-5°C', '-10°C', '-18°C or below'], correctAnswer: 3, explanation: 'Freezers should operate at -18°C or below to effectively halt bacterial growth and preserve food safely.' },
      { type: 'scenario', question: 'Is this safe?', scenario: 'You leave a cooked chicken curry on the kitchen worktop for 4 hours before putting it in the fridge.', options: ['Yes, as long as it is covered', 'Yes, if reheated thoroughly later', 'No — it has been in the danger zone for too long and bacteria may have multiplied to unsafe levels', 'Only unsafe if it smells bad'], correctAnswer: 2, explanation: 'Food left at room temperature for more than 2 hours is at risk of dangerous bacterial growth. It should have been refrigerated within 1–2 hours.' },
    ],
  },
  // Chapter 3: Cross-Contamination
  {
    unitNumber: 3, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Cross-contamination is best defined as:', options: ['Mixing different cuisines in one meal', 'Cooking food at the wrong temperature', 'The transfer of harmful bacteria from one food or surface to another', 'Eating food past its best before date'], correctAnswer: 2, explanation: 'Cross-contamination is the transfer of bacteria or allergens from one food, surface, or piece of equipment to another.' },
      { type: 'multiple_choice', question: 'Which colour chopping board is typically used for raw meat in UK food safety systems?', options: ['White', 'Red', 'Blue', 'Green'], correctAnswer: 1, explanation: 'In the UK colour-coded system, red chopping boards are designated for raw meat to prevent cross-contamination.' },
      { type: 'multiple_choice', question: 'Which of these is an example of indirect cross-contamination?', options: ['Raw chicken dripping onto salad in the fridge', 'Cooking chicken until fully done', 'Storing food in sealed containers', 'Using a knife on raw meat then cutting bread without washing it'], correctAnswer: 3, explanation: 'Indirect cross-contamination occurs via equipment, utensils, or hands — using a contaminated knife without washing it transfers bacteria to other foods.' },
      { type: 'multiple_choice', question: 'How should you clean surfaces after handling raw meat?', options: ['Rinse with cold water only', 'Clean with hot soapy water and disinfect', 'Just blow on it', 'Wipe with a dry cloth'], correctAnswer: 1, explanation: 'Surfaces should be cleaned with hot soapy water and then disinfected to kill remaining bacteria after contact with raw meat.' },
      { type: 'multiple_choice', question: 'Why are allergens a cross-contamination concern?', options: ['They only matter in restaurants', 'They make food taste bad', 'Even trace amounts transferred to another food can trigger a severe allergic reaction', 'Allergens are always visible'], correctAnswer: 2, explanation: 'Even microscopic traces of an allergen transferred via equipment, surfaces, or hands can trigger severe allergic reactions in sensitive individuals.' },
      { type: 'scenario', question: 'What is the risk here?', scenario: 'In a busy kitchen, a chef uses the same tongs to handle raw burgers and then serve cooked ones.', options: ['Serious cross-contamination risk — raw meat bacteria are transferred to the cooked, ready-to-eat burgers', 'Only a risk if the burgers are undercooked', 'No risk — the burgers are the same food', 'The heat from the cooked burgers will kill any bacteria'], correctAnswer: 0, explanation: 'Using the same tongs for raw and cooked meat transfers bacteria from raw meat to the cooked product, creating a serious food safety hazard.' },
    ],
  },
  // Chapter 4: Reading Food Labels
  {
    unitNumber: 3, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'On UK food labels, ingredients are listed in order of:', options: ['Weight — highest to lowest', 'Nutritional importance', 'Alphabetical order', 'Calorie content'], correctAnswer: 0, explanation: 'Ingredients are listed by weight in descending order — the first ingredient is the most abundant by weight.' },
      { type: 'multiple_choice', question: 'The traffic light labelling system on UK food packaging uses which colours?', options: ['Purple, orange, teal', 'Black, white, grey', 'Blue, yellow, pink', 'Red, amber, green'], correctAnswer: 3, explanation: 'The UK traffic light system uses red (high), amber (medium), and green (low) to indicate levels of fat, saturated fat, sugar, and salt per portion.' },
      { type: 'multiple_choice', question: 'What does "per 100g" information on a food label allow you to do?', options: ['Calculate cooking times', 'Determine allergen content', 'Know exactly how much to eat', 'Compare the nutritional content of different products fairly'], correctAnswer: 3, explanation: 'Per 100g values allow fair comparison between products of different sizes and serving amounts.' },
      { type: 'multiple_choice', question: '"Low fat" on a UK food label means the product contains no more than:', options: ['5g fat per 100g', '1g fat per 100g', '10g fat per 100g', '3g fat per 100g'], correctAnswer: 3, explanation: 'Under UK/EU regulations, \'low fat" means the product contains no more than 3g of fat per 100g.' },
      { type: 'multiple_choice', question: 'Which of these is a hidden name for sugar on food labels?', options: ['Sodium chloride', 'Maltodextrin', 'Calcium carbonate', 'Riboflavin'], correctAnswer: 1, explanation: 'Maltodextrin is a form of sugar. Other hidden names include dextrose, fructose, glucose syrup, and high-fructose corn syrup.' },
      { type: 'scenario', question: 'Which product is lower in sugar per 100g?', scenario: 'You are comparing two yoghurts. Product A has 15g sugar per 150g serving. Product B has 8g sugar per 100g.', options: ['They are the same', 'Product A', 'Cannot be determined', 'Product B'], correctAnswer: 3, explanation: 'Product A has 10g sugar per 100g (15g ÷ 1.5), while Product B has 8g per 100g. Product B is lower in sugar per standardised amount.' },
    ],
  },
  // Chapter 5: Shopping on a Budget
  {
    unitNumber: 3, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which strategy is most effective for reducing food shopping costs?', options: ['Only buying branded products', 'Buying only ready meals', 'Shopping without a list to find deals', 'Planning meals for the week and creating a shopping list'], correctAnswer: 3, explanation: 'Meal planning and shopping with a list reduces impulse purchases and food waste, the two biggest drivers of overspending on food.' },
      { type: 'multiple_choice', question: 'Frozen vegetables are:', options: ['Always processed with additives', 'Often equally or more nutritious than fresh and more cost-effective', 'Only suitable for emergencies', 'Less nutritious than fresh'], correctAnswer: 1, explanation: 'Frozen vegetables are typically frozen at peak freshness, preserving their nutritional content. They are often cheaper and reduce waste.' },
      { type: 'multiple_choice', question: 'Which protein source is typically the most affordable per gram of protein?', options: ['Eggs or tinned beans', 'Protein powder', 'Steak', 'Salmon fillets'], correctAnswer: 0, explanation: 'Eggs, tinned beans, and lentils are among the most affordable protein sources per gram, making them excellent budget-friendly options.' },
      { type: 'multiple_choice', question: 'Buying in bulk is most beneficial when:', options: ['You buy fresh produce in large quantities', 'You buy non-perishable staples you use regularly', 'You buy items you have never tried before', 'You buy everything in bulk regardless'], correctAnswer: 1, explanation: 'Buying non-perishable staples (rice, oats, tinned goods) in bulk saves money over time. Perishable items in bulk can lead to waste.' },
      { type: 'multiple_choice', question: 'What is the most common cause of food waste in UK households?', options: ['Cooking too much and not storing leftovers properly', 'Buying too little food', 'Eating out too often', 'Buying only organic food'], correctAnswer: 0, explanation: 'Over-purchasing and not using leftovers are the biggest contributors to household food waste in the UK.' },
      { type: 'scenario', question: 'What is the most practical advice?', scenario: 'A student tells you they cannot afford to eat healthily and rely on takeaway meals.', options: ['Recommend expensive meal delivery services', 'Agree that healthy eating is expensive', 'Show them how batch cooking staples like rice, beans, and frozen vegetables can be cheaper than takeaways', 'Suggest they eat less'], correctAnswer: 2, explanation: 'Batch cooking with affordable staples is significantly cheaper than takeaways and can be equally convenient with basic planning.' },
    ],
  },
  // Chapter 6: Batch Cooking & Meal Prep
  {
    unitNumber: 3, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the primary benefit of batch cooking?', options: ['It eliminates the need for a fridge', 'It only works for athletes', 'It saves time, money, and ensures consistent nutrition throughout the week', 'It makes food taste better'], correctAnswer: 2, explanation: 'Batch cooking saves time by preparing multiple meals at once, reduces costs through bulk purchasing, and ensures consistent balanced nutrition.' },
      { type: 'multiple_choice', question: 'How long can most batch-cooked meals be safely stored in the fridge?', options: ['Indefinitely', 'Up to 1 day', 'Up to 3–4 days', 'Up to 2 weeks'], correctAnswer: 2, explanation: 'Most cooked meals can be safely stored in the fridge for 3–4 days when properly cooled and stored in sealed containers.' },
      { type: 'multiple_choice', question: 'When freezing batch-cooked meals, what is important to do?', options: ['Only freeze carbohydrate-based meals', 'Freeze them while still hot', 'Cool them completely first, then freeze in labelled, portioned containers', 'Stack them without containers'], correctAnswer: 2, explanation: 'Food should be cooled completely before freezing, portioned into labelled containers with dates for safe, organised storage.' },
      { type: 'multiple_choice', question: 'Which of these foods freezes well for meal prep?', options: ['Hard-boiled eggs', 'Salad leaves', 'Chilli con carne', 'Cucumber'], correctAnswer: 2, explanation: 'Stews, curries, and chilli freeze excellently. High-water-content foods like salad and cucumber become mushy when defrosted.' },
      { type: 'multiple_choice', question: 'What is the safest way to defrost frozen food?', options: ['Put it directly in a hot oven from frozen', 'Defrost in the fridge overnight', 'Run it under hot water', 'Leave it on the kitchen counter overnight'], correctAnswer: 1, explanation: 'Defrosting in the fridge overnight is the safest method, keeping food below 5°C and out of the danger zone throughout the process.' },
      { type: 'multiple_choice', question: "What adjustment would you suggest?", options: ['Option A', 'Option B', 'Option C', 'Option D'], correctAnswer: 0, explanation: "Freezing portions for later in the week ensures freshness and safety. Only refrigerate what you will eat within 3–4 days." },
    ],
  },
  // Chapter 7: Meal Prep Fundamentals
  {
    unitNumber: 3, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the first step of effective meal preparation?', options: ['Buy the most expensive ingredients', 'Plan your meals and create a shopping list', 'Buy as much food as possible', 'Start cooking immediately'], correctAnswer: 1, explanation: 'Planning meals and creating a shopping list is the essential first step, ensuring you buy only what you need and maintain nutritional balance.' },
      { type: 'multiple_choice', question: 'Which containers are most suitable for meal prep storage?', options: ['Plastic bags only', 'Open bowls covered with cling film', 'BPA-free, airtight containers with lids', 'Any container regardless of seal'], correctAnswer: 2, explanation: 'BPA-free, airtight containers with secure lids maintain food freshness, prevent contamination, and are safe for reheating.' },
      { type: 'multiple_choice', question: 'How should you organise meals for the week?', options: ['Cook everything as one dish', 'Only prep breakfasts', 'Rely on willpower to make good choices daily', 'Prepare protein, carbohydrate, and vegetable components separately for flexible combinations'], correctAnswer: 3, explanation: 'Preparing components separately allows flexible meal assembly throughout the week and prevents boredom with repetitive meals.' },
      { type: 'multiple_choice', question: 'Which of these is a time-saving meal prep technique?', options: ['Using a slow cooker or batch roasting multiple trays simultaneously', 'Cooking each meal individually from scratch', 'Only eating raw foods', 'Ordering takeaway instead'], correctAnswer: 0, explanation: 'Slow cookers and batch roasting multiple trays at once are efficient techniques that maximise output with minimal active cooking time.' },
      { type: 'scenario', question: 'What is the best approach?', scenario: 'A busy parent says they have no time to meal prep and relies on convenience foods.', options: ['Accept that they cannot eat well', 'Recommend they skip meals to save time', 'Suggest starting with just 2–3 simple meals prepped on one day, using quick methods like one-pot cooking', 'Tell them to hire a chef'], correctAnswer: 2, explanation: 'Starting small with 2–3 simple meals on one day makes meal prep manageable. One-pot cooking minimises preparation and washing up.' },
      { type: 'multiple_choice', question: 'What role does seasoning play in successful meal prep?', options: ['Seasoning reduces nutritional value', 'Only salt should be used', 'It is unnecessary', 'Varied seasoning keeps meals enjoyable and prevents meal prep fatigue'], correctAnswer: 3, explanation: 'Using varied herbs, spices, and seasonings keeps prepped meals enjoyable, reducing the temptation to abandon meal prep due to boredom.' },
    ],
  },
  // Chapter 8: Kitchen Safety
  {
    unitNumber: 3, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What should you do if a pan of oil catches fire?', options: ['Blow on it', 'Pour water on it', 'Move it outside quickly', 'Turn off the heat and cover with a damp cloth or fire blanket'], correctAnswer: 3, explanation: 'Never put water on an oil fire — it will cause a dangerous flare-up. Turn off the heat and smother with a damp cloth or fire blanket.' },
      { type: 'multiple_choice', question: 'Sharp knives are safer than blunt knives because:', options: ['They look more professional', 'They require less force, giving you more control and reducing the risk of slipping', 'They are more expensive', 'Blunt knives cannot cut food'], correctAnswer: 1, explanation: 'Sharp knives require less pressure, meaning you have greater control and are less likely to slip and cut yourself.' },
      { type: 'multiple_choice', question: 'Which of these is a common kitchen hazard?', options: ['Having good lighting', 'Using oven gloves', 'Keeping knives in a block', 'Wet floors near cooking areas'], correctAnswer: 3, explanation: 'Wet or greasy floors near cooking areas create slip hazards. Spills should be cleaned up immediately.' },
      { type: 'multiple_choice', question: 'When using a microwave, why should you stir food and let it stand?', options: ['Microwaves always cook evenly', 'Only to improve flavour', 'Because microwaves heat unevenly — stirring and standing ensures even temperature distribution', 'To cool it down faster'], correctAnswer: 2, explanation: 'Microwaves can heat food unevenly, creating hot spots. Stirring and standing time allows heat to distribute evenly, ensuring safe temperatures throughout.' },
      { type: 'multiple_choice', question: 'What is the correct way to handle hot pans?', options: ['Use dry, heat-resistant oven gloves or mitts', 'Grab the handle quickly', 'Use a tea towel', 'Wait until they cool on the hob'], correctAnswer: 0, explanation: 'Dry, heat-resistant oven gloves or mitts provide proper protection. Damp cloths can conduct heat and cause burns.' },
      { type: 'scenario', question: 'What should you do?', scenario: 'You notice a frayed electrical cord on a kitchen appliance.', options: ['Only use it for quick tasks', 'Stop using it immediately, unplug it, and have it repaired or replaced', 'Wrap it in tape and carry on', 'Continue using it carefully'], correctAnswer: 1, explanation: 'Frayed electrical cords are a fire and electrocution hazard. The appliance should be unplugged immediately and not used until repaired or replaced.' },
    ],
  },
];

// ═══ UNIT 4 CHAPTER QUIZZES — Planning Balanced Diets ═══
