import type { ChapterQuiz } from '../types';

export const nutritionL2Unit4ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: SMART Nutrition Goals
  {
    unitNumber: 4, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What does the "M" in SMART goals stand for?', options: ['Measurable', 'Manageable', 'Meaningful', 'Motivational'], correctAnswer: 0, explanation: 'The M stands for Measurable — you should be able to objectively verify whether you have achieved your goal.' },
      { type: 'multiple_choice', question: 'Which of these is a SMART nutrition goal?', options: ['Try harder with food', 'Eat 30g of protein at breakfast every day for 4 weeks', 'Eat better', 'Be healthier'], correctAnswer: 1, explanation: 'This goal is Specific (30g protein at breakfast), Measurable, Achievable, Relevant, and Time-bound (4 weeks).' },
      { type: 'multiple_choice', question: 'What is the difference between an outcome goal and a process goal?', options: ['An outcome goal focuses on the end result; a process goal focuses on the actions needed to get there', 'Outcome goals are always better', 'Process goals are less important', 'They are the same'], correctAnswer: 0, explanation: 'Outcome goals define what you want to achieve (e.g., lose 5kg). Process goals define what you will do (e.g., eat vegetables at every meal).' },
      { type: 'multiple_choice', question: 'Why is the "Time-bound" element important in goal setting?', options: ['It creates unnecessary pressure', 'It provides a deadline for review and creates accountability', 'It only matters for athletes', 'Goals should be open-ended'], correctAnswer: 1, explanation: 'Time-bound goals create a review point, helping you assess progress and adjust your approach if needed.' },
      { type: 'scenario', question: 'How would you make this goal SMART?', scenario: 'A friend says: "I want to drink more water."', options: ['That goal is already SMART', '"Drink at least 2 litres of water every day for the next 2 weeks, tracked with a water bottle"', '"Drink loads of water"', '"Try to drink water sometimes"'], correctAnswer: 1, explanation: 'The improved version is Specific (2 litres), Measurable (tracked), Achievable, Relevant, and Time-bound (2 weeks).' },
      { type: 'multiple_choice', question: 'Which component of SMART ensures the goal is realistic?', options: ['Relevant', 'Achievable', 'Measurable', 'Specific'], correctAnswer: 1, explanation: 'Achievable ensures the goal is realistic given your current lifestyle, skills, and resources — preventing frustration and failure.' },
      { type: 'multiple_choice', question: 'What does SMART stand for in goal setting?', options: ['Simple, Massive, Aggressive, Rapid, Total', 'Specific, Measurable, Achievable, Relevant, Time-bound', 'Strong, Motivated, Active, Resilient, Tough', 'Small, Manageable, Appropriate, Reasonable, Trackable'], correctAnswer: 1, explanation: 'SMART goals are: Specific (clear), Measurable (trackable), Achievable (realistic), Relevant (meaningful to you), and Time-bound (with a deadline).' },
      { type: 'multiple_choice', question: 'Which is a SMART nutrition goal?', options: ['Eat healthier', 'Eat 5 portions of fruit and vegetables every day for the next 4 weeks', 'Lose weight soon', 'Stop eating junk food'], correctAnswer: 1, explanation: '"Eat 5 portions of fruit and vegetables every day for 4 weeks" is specific (5 portions), measurable (count daily), achievable, relevant, and time-bound (4 weeks).' },
      { type: 'multiple_choice', question: 'Why is the "achievable" part of SMART important?', options: ['It is not important', 'Unrealistic goals lead to failure and demotivation — achievable goals build confidence and momentum', 'Goals should always be extreme', 'Achievable means easy'], correctAnswer: 1, explanation: 'Goals beyond your current capacity lead to failure and learned helplessness — achievable goals create success experiences that build confidence for larger changes.' },
      { type: 'multiple_choice', question: 'How often should you review your SMART goals?', options: ['Never — set and forget', 'Regularly — weekly check-ins and formal reviews at the time-bound deadline to assess progress and adjust', 'Only when you fail', 'Once a year'], correctAnswer: 1, explanation: 'Regular review (weekly check-ins, formal deadline reviews) allows adjustment, maintains motivation, and ensures goals remain relevant and achievable.' },
    
    ],
  },
  // Chapter 2: Understanding Calories
  {
    unitNumber: 4, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is a calorie?', options: ['A unit of energy', 'A type of vitamin', 'A macronutrient', 'A measure of weight'], correctAnswer: 0, explanation: 'A calorie is a unit of energy. In nutrition, we use kilocalories (kcal) to measure the energy content of food.' },
      { type: 'multiple_choice', question: 'What is BMR?', options: ['Best Muscle Recovery', 'Body Mass Ratio', 'Basal Metabolic Rate — the calories your body burns at rest', 'Basic Meal Requirement'], correctAnswer: 2, explanation: 'BMR (Basal Metabolic Rate) is the number of calories your body needs at complete rest to maintain basic functions like breathing and circulation.' },
      { type: 'multiple_choice', question: 'To lose weight, you need to be in a:', options: ['Calorie equilibrium', 'Calorie deficit', 'Calorie surplus', 'Protein surplus'], correctAnswer: 1, explanation: 'Weight loss requires a calorie deficit — consuming fewer calories than your body expends over time.' },
      { type: 'multiple_choice', question: 'TDEE stands for:', options: ['Total Daily Eating Estimate', 'Total Daily Energy Expenditure', 'The Diet and Exercise Equation', 'Tracked Daily Energy Evaluation'], correctAnswer: 1, explanation: 'TDEE (Total Daily Energy Expenditure) is your total calorie burn per day, including BMR plus activity and exercise.' },
      { type: 'multiple_choice', question: 'A safe and sustainable rate of weight loss is generally considered to be:', options: ['0.5–1kg per week', 'As fast as possible', '3–5kg per week', '5kg per month minimum'], correctAnswer: 0, explanation: 'A sustainable rate of 0.5–1kg per week typically requires a deficit of 500–1000 calories per day, preserving muscle mass and energy levels.' },
      { type: 'scenario', question: 'Why might this be happening?', scenario: 'Someone is eating 1,200 calories per day but has stopped losing weight after 4 weeks.', options: ['Their metabolism may have adapted, or they may be underestimating intake — a moderate deficit with regular reviews is more sustainable', 'They should fast for a week', 'They need to eat even less', 'Calories do not matter for weight loss'], correctAnswer: 0, explanation: 'Very low calorie diets can cause metabolic adaptation. A moderate, sustainable deficit with regular reviews is more effective long-term.' },
      { type: 'multiple_choice', question: 'What is a calorie?', options: ['A type of nutrient', 'A unit of energy — specifically, the energy needed to raise 1 kilogram of water by 1 degree Celsius', 'A type of fat', 'A mineral'], correctAnswer: 1, explanation: 'A kilocalorie (kcal, commonly called a "calorie") is a unit of energy — food provides energy measured in calories to fuel body functions and activity.' },
      { type: 'multiple_choice', question: 'What is TDEE?', options: ['A type of exercise', 'Total Daily Energy Expenditure — the total number of calories you burn in a day including all activity', 'A diet plan', 'A supplement'], correctAnswer: 1, explanation: 'TDEE (Total Daily Energy Expenditure) is the total calories burned daily — including BMR (resting metabolism), activity, digestion, and exercise.' },
      { type: 'multiple_choice', question: 'What happens if you consistently eat more calories than you burn?', options: ['Nothing — excess is excreted', 'The excess energy is stored, primarily as body fat, leading to weight gain over time', 'You build muscle automatically', 'Your metabolism speeds up to match'], correctAnswer: 1, explanation: 'Energy balance: consistently consuming more calories than you expend results in the excess being stored as body fat — regardless of the food source.' },
      { type: 'multiple_choice', question: 'How many calories per gram do the three macronutrients provide?', options: ['All provide 4 kcal', 'Carbs: 4 kcal, Protein: 4 kcal, Fat: 9 kcal per gram', 'All provide 9 kcal', 'Carbs: 9, Protein: 4, Fat: 4'], correctAnswer: 1, explanation: 'Carbohydrates and protein each provide 4 kcal/g; fat provides 9 kcal/g — this is why fat-rich foods are more calorie-dense.' },
    
    ],
  },
  // Chapter 3: Introduction to Macro Tracking
  {
    unitNumber: 4, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Macro tracking involves monitoring your daily intake of:', options: ['Only protein', 'Only calories', 'Protein, carbohydrate, and fat', 'Vitamins and minerals'], correctAnswer: 2, explanation: 'Macro tracking involves monitoring your daily intake of the three macronutrients: protein, carbohydrate, and fat.' },
      { type: 'multiple_choice', question: 'Which tool is most commonly used for tracking food intake?', options: ['A stopwatch', 'A thermometer', 'A ruler', 'A food diary or tracking app (e.g., MyFitnessPal)'], correctAnswer: 3, explanation: 'Food diary apps and tracking apps like MyFitnessPal are the most common and convenient tools for logging food intake and macros.' },
      { type: 'multiple_choice', question: 'What is a potential downside of obsessive macro tracking?', options: ['There are no downsides', 'It makes you eat less', 'It can lead to an unhealthy relationship with food and disordered eating behaviours', 'It always improves health'], correctAnswer: 2, explanation: 'Obsessive tracking can cause anxiety around food, social isolation at mealtimes, and may contribute to disordered eating. Balance is important.' },
      { type: 'multiple_choice', question: 'For general health, which macronutrient should most people prioritise hitting consistently?', options: ['Fat', 'Carbohydrate', 'Alcohol', 'Protein'], correctAnswer: 3, explanation: 'Protein is typically the most important macronutrient to prioritise, as it supports muscle maintenance, satiety, and recovery.' },
      { type: 'multiple_choice', question: 'A food scale is useful for macro tracking because:', options: ['It replaces the need for cooking', 'It is required by law', 'It makes food taste better', 'It provides accurate portion measurements, improving tracking accuracy'], correctAnswer: 3, explanation: 'A food scale ensures accurate portion measurement, eliminating guesswork and improving the reliability of macro tracking.' },
      { type: 'scenario', question: 'What would you suggest?', scenario: 'A person new to tracking is spending 30 minutes per meal logging every ingredient and feeling overwhelmed.', options: ['Only track on weekdays', 'They should track more carefully', 'Give up tracking entirely', 'Start with tracking just one meal per day or just protein, and build the habit gradually'], correctAnswer: 3, explanation: 'Starting with one meal or one macronutrient makes the habit manageable. Complexity can be added gradually as confidence builds.' },
      { type: 'multiple_choice', question: 'What is macro tracking?', options: ['Counting steps', 'Recording the grams of protein, carbohydrates, and fat you eat to ensure you meet specific targets', 'Tracking micronutrients', 'Counting calories only'], correctAnswer: 1, explanation: 'Macro tracking goes beyond calorie counting — recording protein, carbohydrate, and fat intake ensures you meet targets for body composition and performance goals.' },
      { type: 'multiple_choice', question: 'What tools can help with macro tracking?', options: ['No tools exist', 'Food diary apps (MyFitnessPal, Cronometer), food scales, and measuring cups', 'Only pen and paper', 'Supplements'], correctAnswer: 1, explanation: 'Apps like MyFitnessPal and Cronometer make tracking practical — combined with food scales for accuracy and measuring cups for convenience.' },
      { type: 'multiple_choice', question: 'Is macro tracking necessary for everyone?', options: ['Yes — everyone must track', 'No — it is a useful learning tool but not necessary long-term; some people develop an intuitive understanding', 'Only athletes should track', 'Tracking causes eating disorders'], correctAnswer: 1, explanation: 'Tracking is an educational tool — it teaches portion awareness and macronutrient content. Some people benefit from ongoing tracking; others develop intuitive eating skills.' },
      { type: 'multiple_choice', question: 'What is a common mistake when starting macro tracking?', options: ['Being too accurate', 'Not weighing food and relying on estimates — which can be off by 30–50%', 'Tracking too carefully', 'Using an app'], correctAnswer: 1, explanation: 'Estimation errors are significant — people typically underestimate portions by 30–50%. Using food scales initially calibrates your eye for more accurate future estimation.' },
    
    ],
  },
  // Chapter 4: Meal Planning Principles
  {
    unitNumber: 4, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the primary purpose of meal planning?', options: ['To follow a celebrity diet', 'To ensure consistent, balanced nutrition while saving time and money', 'To eliminate all treats', 'To restrict food choices'], correctAnswer: 1, explanation: 'Meal planning ensures nutritional consistency, reduces food waste, saves time and money, and removes daily decision fatigue.' },
      { type: 'multiple_choice', question: 'A weekly meal plan should ideally include:', options: ['Only foods you already know', 'Maximum calorie restriction', 'The same meals every day for consistency', 'Variety across protein sources, vegetables, and cooking methods'], correctAnswer: 3, explanation: 'Variety ensures a broader range of nutrients and prevents boredom, which is a common reason people abandon meal plans.' },
      { type: 'multiple_choice', question: 'When is the best time to do your weekly food shop based on a meal plan?', options: ['Once per week after planning meals and creating a list', 'Twice per day', 'Only when the fridge is completely empty', 'Every day'], correctAnswer: 0, explanation: 'A single weekly shop based on a planned list is the most efficient approach, reducing impulse buys and multiple trips.' },
      { type: 'multiple_choice', question: 'What should you consider when planning meals for the week?', options: ['What is trending on social media', 'Nutritional balance, budget, time available for cooking, and shelf life of ingredients', 'Only taste preferences', 'Only calorie content'], correctAnswer: 1, explanation: 'Effective meal planning considers nutrition, budget, cooking time, ingredient shelf life, and personal preferences for sustainability.' },
      { type: 'scenario', question: 'What would make this plan more effective?', scenario: 'Someone plans 7 elaborate meals for the week but works 12-hour shifts on 3 of those days.', options: ['Plan simpler or pre-prepared meals for work days and more elaborate meals for days off', 'They should cook all 7 meals regardless', 'Only eat protein bars on work days', 'Skip meals on work days'], correctAnswer: 0, explanation: 'Aligning meal complexity with available time ensures the plan is realistic. Simple meals or pre-prepared food works best for busy days.' },
      { type: 'multiple_choice', question: 'Including a "flexible day" in your meal plan helps with:', options: ['Losing weight faster', 'Nothing — it is wasted time', 'Adherence — it allows for social meals, leftovers, or unexpected changes', 'Eliminating all treats'], correctAnswer: 2, explanation: 'A flexible day accounts for real life — social meals, leftovers, or changes in plans — preventing the all-or-nothing mentality that leads to plan abandonment.' },
      { type: 'multiple_choice', question: 'What are the benefits of meal planning?', options: ['No benefits', 'Better nutrition, less food waste, saved money, reduced stress, and fewer unhealthy impulse choices', 'Only saving time', 'Only for people who enjoy cooking'], correctAnswer: 1, explanation: 'Meal planning improves nutrition quality, reduces food waste (saving money), removes daily decision stress, and significantly reduces unhealthy impulse eating.' },
      { type: 'multiple_choice', question: 'What should a weekly meal plan include?', options: ['Only dinner plans', 'All meals and snacks, a corresponding shopping list, and consideration of schedule and budget', 'Only weekday meals', 'The same meal every day'], correctAnswer: 1, explanation: 'A complete meal plan covers all meals and snacks, accounts for your weekly schedule, includes a shopping list, and considers budget and time constraints.' },
      { type: 'multiple_choice', question: 'How can you build flexibility into a meal plan?', options: ['Rigid plans are always better', 'Include 1–2 flexible meals per week and plan meals that can swap days without waste', 'Plan every minute detail', 'Never plan — be spontaneous'], correctAnswer: 1, explanation: 'Built-in flexibility (swappable meals, a "wildcard" night) prevents the rigidity that causes people to abandon meal plans entirely.' },
      { type: 'multiple_choice', question: 'What is the "base ingredient" approach to meal planning?', options: ['Only eating basic foods', 'Preparing versatile base ingredients (chicken, rice, roasted veg) that can be used in multiple meals throughout the week', 'Using one ingredient per meal', 'A restaurant technique'], correctAnswer: 1, explanation: 'Cooking base ingredients in bulk (proteins, grains, roasted vegetables) then combining them differently throughout the week saves time while maintaining variety.' },
    
    ],
  },
  // Chapter 5: Eating Out Strategies
  {
    unitNumber: 4, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the best strategy for eating out while maintaining your nutrition goals?', options: ['Avoid eating out entirely', 'Review the menu in advance and choose options that align with your goals', 'Only order salad regardless of the restaurant', 'Fast before and after eating out'], correctAnswer: 1, explanation: 'Reviewing menus in advance allows informed choices without stress. Complete avoidance is unsustainable and unnecessary.' },
      { type: 'multiple_choice', question: 'Restaurant portions are typically:', options: ['Perfectly measured', 'Larger than home portions', 'Smaller than home portions', 'The same as home portions'], correctAnswer: 1, explanation: 'Restaurant portions are generally larger than recommended serving sizes, which means total calorie intake can be significantly higher than expected.' },
      { type: 'multiple_choice', question: 'Which cooking method at restaurants typically adds the most calories?', options: ['Deep-fried', 'Baked', 'Steamed', 'Grilled'], correctAnswer: 0, explanation: 'Deep-frying adds significant calories from oil absorption. Grilled, steamed, and baked options are generally lower in added fat.' },
      { type: 'multiple_choice', question: 'A practical tip for managing portions when eating out is:', options: ['Ask for a side of vegetables and leave food if you feel full', 'Eat as fast as possible', 'Always order a starter, main, and dessert', 'Never eat bread'], correctAnswer: 0, explanation: 'Ordering extra vegetables, eating mindfully, and listening to satiety cues helps manage intake without feeling restricted.' },
      { type: 'scenario', question: 'What is the best approach?', scenario: 'You are at a pizza restaurant with friends and feel pressure to abandon your nutrition plan.', options: ['Skip the meal entirely', 'Order nothing and watch everyone else eat', 'Eat an entire pizza because "the day is ruined"', 'Enjoy a reasonable portion — perhaps one or two slices with a side salad — and return to your plan at the next meal'], correctAnswer: 3, explanation: 'One meal does not define your overall nutrition. Enjoying a reasonable portion and returning to your plan is sustainable and socially healthy.' },
      { type: 'multiple_choice', question: 'The "80/20" approach to nutrition means:', options: ['Cooking at home 80 days per year', 'Eating 80% protein and 20% carbohydrate', 'Eating 80% of your meal and leaving 20%', 'Following your nutrition plan 80% of the time and allowing flexibility 20% of the time'], correctAnswer: 3, explanation: 'The 80/20 approach prioritises consistency most of the time while allowing flexibility, which supports long-term adherence and a healthy relationship with food.' },
      { type: 'multiple_choice', question: 'How can you make healthier choices when eating out?', options: ['Never eat out', 'Check the menu in advance, choose grilled over fried, ask for dressings on the side, and control portions', 'Only order salads', 'Eating out is always unhealthy'], correctAnswer: 1, explanation: 'Practical strategies: preview menus, choose cooking methods (grilled > fried), ask for sauces/dressings on the side, and do not feel pressured to finish oversized portions.' },
      { type: 'multiple_choice', question: 'What is the best approach to alcohol when eating out?', options: ['Always avoid alcohol', 'Be mindful of liquid calories — alternate alcoholic drinks with water and choose lower-calorie options', 'Alcohol has no calories', 'Only drink spirits'], correctAnswer: 1, explanation: 'Alcohol adds significant liquid calories (a pint of beer = ~200 kcal, a glass of wine = ~130 kcal) — alternating with water and choosing wisely helps manage intake.' },
      { type: 'multiple_choice', question: 'Should you skip meals before eating out to save calories?', options: ['Yes — always skip lunch before dinner out', 'No — skipping meals leads to arriving excessively hungry, which typically causes overeating and poor choices', 'Only skip breakfast', 'Fasting all day is best'], correctAnswer: 1, explanation: 'Arriving at a restaurant very hungry impairs decision-making and increases overeating — eating normally and making conscious choices at the restaurant is more effective.' },
      { type: 'multiple_choice', question: 'How should you view eating out in the context of overall nutrition?', options: ['One bad meal ruins everything', 'One meal does not define your nutrition — overall dietary patterns over weeks and months matter most', 'Eating out is always a failure', 'You must compensate with exercise'], correctAnswer: 1, explanation: 'Nutrition is about patterns, not single meals — enjoying a restaurant meal without guilt is part of a healthy relationship with food. Overall consistency matters most.' },
    
    ],
  },
  // Chapter 6: Common Diet Myths
  {
    unitNumber: 4, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Is the claim "carbohydrates make you fat" accurate?', options: ['No — excessive calories from any source cause weight gain; carbohydrates are an important energy source', 'Only refined carbohydrates cause weight gain', 'Carbohydrates should be eliminated entirely', 'Yes — all carbohydrates cause weight gain'], correctAnswer: 0, explanation: 'Weight gain is caused by a calorie surplus, not by any single macronutrient. Carbohydrates are an important energy source and should not be eliminated.' },
      { type: 'multiple_choice', question: 'Do "detox" diets or juice cleanses remove toxins from your body?', options: ['No — the liver and kidneys already perform detoxification; these diets have no scientific basis', 'Only certain branded detox products work', 'Yes — they are essential for health', 'Detox diets are recommended by the NHS'], correctAnswer: 0, explanation: 'The liver and kidneys continuously detoxify the body. Commercial \'detox" diets and juice cleanses have no scientific evidence supporting their claims.' },
      { type: 'multiple_choice', question: 'Eating late at night causes weight gain — is this true?', options: ['Only if you eat after 8pm', 'Yes — calories consumed at night are stored as fat', 'Only if you eat carbohydrates', 'No — total daily calorie intake matters more than when you eat'], correctAnswer: 3, explanation: 'Weight gain is determined by total calorie intake over time, not the time of day food is consumed. Meal timing has minimal impact on body composition.' },
      { type: 'multiple_choice', question: 'The claim that "you must eat six small meals a day to boost metabolism" is:', options: ['Only true for athletes', 'Recommended by all dietitians', 'A myth — meal frequency has minimal impact on metabolic rate', 'Scientifically proven'], correctAnswer: 2, explanation: 'Research shows that total calorie intake, not meal frequency, determines metabolic response. Some people prefer more meals, others fewer — both are valid.' },
      { type: 'multiple_choice', question: 'Are all processed foods unhealthy?', options: ['No — processing exists on a spectrum; many processed foods (tinned beans, frozen vegetables) are nutritious', 'Processed means artificial', 'Only organic processed foods are acceptable', 'Yes — all processed foods should be avoided'], correctAnswer: 0, explanation: 'Processing ranges from minimal (frozen vegetables, tinned beans) to ultra-processed (sugary cereals, ready meals). Not all processed foods are unhealthy.' },
      { type: 'scenario', question: 'How should you respond?', scenario: 'A friend says they are doing a "metabolism boosting" tea detox they saw on social media.', options: ['Suggest a different brand of detox tea', 'Explain that no tea can "boost metabolism" or "detox" the body — the liver and kidneys do this naturally', 'Encourage them to continue', 'Say nothing to avoid conflict'], correctAnswer: 1, explanation: "Politely explaining the science helps protect people from wasting money on ineffective products. The body\'s own organs handle detoxification." },
      { type: 'multiple_choice', question: 'Is it true that eating after 8pm causes weight gain?', options: ['Yes — always', 'No — total daily calorie intake matters, not the time you eat; late eating only matters if it leads to excess intake', 'Only carbohydrates after 8pm cause weight gain', 'You should never eat after 6pm'], correctAnswer: 1, explanation: 'The body does not store food differently based on time — weight gain comes from total calorie surplus. Late eating is only problematic if it adds excess calories to the day.' },
      { type: 'multiple_choice', question: 'Do detox diets and juice cleanses work?', options: ['Yes — they remove toxins', 'No — the liver and kidneys detox continuously; detox diets are unnecessary and often nutritionally inadequate', 'Only expensive ones work', 'They work short-term'], correctAnswer: 1, explanation: 'Your liver and kidneys detoxify constantly — "detox" diets have no scientific basis. Any weight lost is water and will return. They are often nutritionally deficient.' },
      { type: 'multiple_choice', question: 'Is fat in food always bad?', options: ['Yes — avoid all fat', 'No — dietary fat is essential for hormone production, brain function, and vitamin absorption; the type of fat matters', 'Only animal fat is bad', 'Fat-free is always healthier'], correctAnswer: 1, explanation: 'Dietary fat is essential — unsaturated fats (olive oil, nuts, avocado, oily fish) support health. The focus should be on reducing saturated and trans fats, not all fat.' },
      { type: 'multiple_choice', question: 'Does eating breakfast speed up your metabolism?', options: ['Yes — it "fires up" your metabolism', 'No — breakfast does not significantly affect metabolic rate; whether to eat breakfast depends on personal preference and hunger', 'Skipping breakfast is always bad', 'Only protein breakfasts boost metabolism'], correctAnswer: 1, explanation: 'There is no significant metabolic advantage to eating breakfast — it neither "fires up" nor "slows down" metabolism. The best breakfast strategy is one that supports your overall dietary pattern.' },
    
    ],
  },
  // Chapter 7: Building Sustainable Habits
  {
    unitNumber: 4, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is "habit stacking"?', options: ['Stacking food on your plate', 'Doing many habits at once', 'Attaching a new habit to an existing routine to increase consistency', 'Following multiple diet plans simultaneously'], correctAnswer: 2, explanation: 'Habit stacking links a new behaviour to an existing habit (e.g., \'After I make my morning coffee, I will prepare a balanced breakfast").' },
      { type: 'multiple_choice', question: 'Research suggests it takes approximately how long to form a new habit?', options: ['Exactly 30 days', '21 days', '7 days', '66 days on average, varying by complexity'], correctAnswer: 3, explanation: 'Research by Phillippa Lally at UCL found it takes an average of 66 days for a new behaviour to become automatic, though this varies by individual and complexity.' },
      { type: 'multiple_choice', question: 'Which approach is most effective for building lasting nutrition habits?', options: ["Copy someone else\'s diet exactly", 'Follow a strict elimination diet', 'Change everything at once for maximum impact', 'Make one small change at a time and build on each success'], correctAnswer: 3, explanation: 'Small, incremental changes are more sustainable than dramatic overhauls. Building on each success creates momentum and confidence.' },
      { type: 'multiple_choice', question: 'What is "decision fatigue" in the context of nutrition?', options: ['Deciding not to eat', 'Being tired from eating too much', 'A medical condition', 'Mental exhaustion from making too many food choices, leading to poor decisions'], correctAnswer: 3, explanation: 'Decision fatigue occurs when constant food choices deplete willpower, leading to impulsive or poor decisions — meal planning reduces this.' },
      { type: 'multiple_choice', question: 'Environment design for better nutrition means:', options: ['Buying more kitchen gadgets', 'Moving to a different country', 'Arranging your kitchen, fridge, and surroundings to make healthy choices easier and unhealthy choices harder', 'Eating outside more'], correctAnswer: 2, explanation: 'Placing nutritious foods at eye level, keeping fruit visible, and removing tempting ultra-processed foods from sight nudges better choices.' },
      { type: 'scenario', question: 'What is the best advice?', scenario: 'Someone has tried and failed multiple diets and says "I just have no willpower."', options: ['Explain that willpower is limited — sustainable change comes from environment design, small habits, and systems, not just motivation', 'Agree and suggest giving up', 'Suggest a willpower supplement', 'Recommend a stricter diet'], correctAnswer: 0, explanation: 'Willpower is a limited resource. Sustainable change relies on systems (meal prep, environment design, habit stacking) rather than motivation alone.' },
      { type: 'multiple_choice', question: 'What is the most effective way to build a new nutrition habit?', options: ['Willpower and motivation', 'Start with a small, specific change linked to an existing routine and track consistency', 'Change everything at once', 'Only think about it'], correctAnswer: 1, explanation: 'Small, specific habits attached to existing routines ("after breakfast, I will drink a glass of water") build neural pathways more effectively than relying on motivation.' },
      { type: 'multiple_choice', question: 'How long does it typically take to form a new habit?', options: ['21 days exactly', 'On average 66 days, but it varies from 18 to 254 days depending on the habit complexity', '1 week', '1 year'], correctAnswer: 1, explanation: 'The 21-day myth is inaccurate — research shows habit formation averages 66 days but varies widely. Consistency matters more than a specific number of days.' },
      { type: 'multiple_choice', question: 'What should you do when you break a healthy eating streak?', options: ['Give up — you have failed', 'Resume the habit at the next opportunity — one slip does not erase previous progress', 'Start from scratch', 'Punish yourself with extra exercise'], correctAnswer: 1, explanation: 'Missing once does not break a habit — research shows that occasional lapses have minimal impact on habit formation. The key is resuming, not perfection.' },
      { type: 'multiple_choice', question: 'Why does making unhealthy food less convenient work better than willpower?', options: ['Convenience does not matter', 'Environment design removes the need for willpower — if unhealthy food is not visible or accessible, you eat less of it automatically', 'Willpower is always stronger', 'Only works for children'], correctAnswer: 1, explanation: 'Environmental design is more reliable than willpower: moving unhealthy snacks out of sight, keeping fruit visible, and pre-preparing healthy options reduces reliance on self-control.' },
    
    ],
  },
  // Chapter 8: Putting It All Together
  {
    unitNumber: 4, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'A personal nutrition plan should be based on:', options: ['Your individual goals, lifestyle, preferences, and nutritional needs', 'The latest celebrity diet', 'The cheapest foods available', 'What works for your friend'], correctAnswer: 0, explanation: 'An effective nutrition plan is personalised to individual goals, lifestyle, preferences, budget, and specific nutritional requirements.' },
      { type: 'multiple_choice', question: 'How often should you review and adjust your nutrition plan?', options: ['Only when you gain weight', 'Never — stick to it forever', 'Every day', 'Every 2–4 weeks based on progress, energy levels, and adherence'], correctAnswer: 3, explanation: 'Regular reviews every 2–4 weeks allow you to assess what is working, adjust for changes, and maintain progress.' },
      { type: 'multiple_choice', question: 'Which factor is MOST important for long-term nutrition success?', options: ['Taking supplements', 'Consistency over perfection', 'Eating as little as possible', 'Following the perfect diet'], correctAnswer: 1, explanation: 'Consistency with a good-enough plan vastly outperforms sporadic attempts at a "perfect" diet. Sustainable habits beat short-term extremes.' },
      { type: 'multiple_choice', question: 'What should you do if you have a day of eating that does not match your plan?', options: ['Punish yourself with extra exercise', 'Fast the next day to compensate', 'Accept it, learn from it, and return to your plan at the next meal', 'Give up the entire plan'], correctAnswer: 2, explanation: 'One off-plan day does not erase weeks of good nutrition. The key is returning to your plan without guilt or compensatory behaviours.' },
      { type: 'scenario', question: 'What is your priority recommendation?', scenario: 'You are helping someone create their first nutrition plan. They want to lose weight, eat more vegetables, track their protein, and meal prep — all starting Monday.', options: ['Pick one or two priorities to start with (e.g., protein target and meal prep) and add the rest gradually', 'Start everything at once', 'Tell them to wait until they are more motivated', 'Suggest a meal replacement shake plan instead'], correctAnswer: 0, explanation: 'Starting with one or two changes prevents overwhelm and builds confidence. Additional habits can be layered in as the first ones become automatic.' },
      { type: 'multiple_choice', question: 'The concept of "progress, not perfection" means:', options: ['Small, consistent improvements over time are more valuable than striving for an impossible ideal', 'Perfection is easily achievable', 'It does not matter what you eat', 'You should never set high standards'], correctAnswer: 0, explanation: 'Progress over perfection acknowledges that consistent small improvements compound into significant long-term results, while perfectionism often leads to all-or-nothing behaviour.' },
      { type: 'multiple_choice', question: 'What is the 80/20 approach to nutrition?', options: ['80% dieting, 20% exercise', 'Eating nutritious whole foods 80% of the time and allowing flexibility for 20% — promoting sustainability without perfection', '80% protein, 20% carbs', 'Only eating 80% of your meal'], correctAnswer: 1, explanation: 'The 80/20 approach means focusing on whole, nutritious foods most of the time while allowing flexibility — preventing the all-or-nothing mentality that derails long-term consistency.' },
      { type: 'multiple_choice', question: 'What is the single most important factor for long-term nutrition success?', options: ['Following the perfect diet', 'Consistency — the best nutrition plan is one you can follow consistently over months and years', 'Supplements', 'Extreme restriction'], correctAnswer: 1, explanation: 'Consistency beats perfection — an "80% good" diet followed consistently for years produces far better results than a "perfect" diet abandoned after 3 weeks.' },
      { type: 'multiple_choice', question: 'How should you use everything you have learned in this course?', options: ['Follow every rule perfectly forever', 'Apply principles progressively — start with the changes that will make the biggest difference and build from there', 'Ignore it and eat intuitively', 'Only use it for yourself'], correctAnswer: 1, explanation: 'Progressive implementation: identify your biggest nutrition gaps, address them one at a time, build consistent habits, and continue learning and adjusting.' },
      { type: 'multiple_choice', question: 'Why is a flexible approach to nutrition more sustainable than rigid dieting?', options: ['Flexibility leads to poor nutrition', 'Rigid rules create psychological pressure, guilt, and binge-restrict cycles — flexibility allows life events without derailing progress', 'Rigid diets always work better', 'Flexibility means no plan'], correctAnswer: 1, explanation: 'Rigid dietary rules create psychological pressure that leads to guilt, stress, and eventual abandonment — a flexible approach accommodates real life while maintaining overall direction.' },
    
    ],
  },
];

// ═══ UNIT ASSESSMENTS ═══
