import type { ChapterQuiz } from '../types';

export const nutritionL2Unit2ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: Children & Adolescents
  {
    unitNumber: 2, chapterNumber: 1, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Why do children have proportionally higher energy needs than adults?', options: ['They are building new tissues as well as maintaining existing ones', 'Their metabolisms are slower', 'They eat less frequently', 'They exercise more'], correctAnswer: 0, explanation: 'Children are actively growing — building new bone, muscle, and neural tissue — which requires proportionally more energy relative to body weight.' },
      { type: 'multiple_choice', question: 'During which life stage is peak bone mass typically established?', options: ['Adolescence', 'Old age', 'Middle age', 'Early childhood'], correctAnswer: 0, explanation: 'Peak bone mass is largely established during adolescence, making calcium intake during this period particularly important.' },
      { type: 'multiple_choice', question: 'Which nutrient is particularly important for adolescent girls after menstruation begins?', options: ['Calcium', 'Iron', 'Zinc', 'Vitamin D'], correctAnswer: 1, explanation: 'Iron needs increase for adolescent girls after menstruation begins due to monthly blood loss.' },
      { type: 'multiple_choice', question: 'Why are restrictive diets inappropriate for growing children?', options: ['Restrictive diets are only harmful for adults', 'Children need less nutrition than adults', 'Children do not enjoy them', 'They can impair growth, development, and establish unhealthy relationships with food'], correctAnswer: 3, explanation: 'Restrictive diets during growth periods can lead to nutritional deficiencies, impaired development, and disordered eating patterns.' },
      { type: 'scenario', question: 'What is the most appropriate response?', scenario: 'A parent asks whether their 14-year-old should go on a low-carbohydrate diet to lose weight.', options: ['Yes, low-carb works for everyone', 'Yes, but only for two weeks', 'Only if supervised by a doctor', 'No — adolescents need adequate carbohydrates for energy, growth, and brain function; focus on balanced meals instead'], correctAnswer: 3, explanation: 'Adolescents need adequate carbohydrates for energy, brain development, and growth. Restrictive diets are not appropriate; balanced eating is the priority.' },
      { type: 'multiple_choice', question: 'Which of these is a key nutrient for cognitive development in young people?', options: ['Iron', 'Sodium', 'Caffeine', 'Saturated fat'], correctAnswer: 0, explanation: 'Iron supports cognitive development and oxygen transport to the brain. Deficiency can impair concentration and academic performance.' },
      { type: 'multiple_choice', question: 'Why do children have higher energy needs relative to their body size?', options: ['They do not', 'Only teenage boys need more energy', 'They waste more energy', 'They are growing rapidly and are typically more physically active than adults'], correctAnswer: 3, explanation: 'Children need more energy per kilogram of body weight than adults due to rapid growth, development, and typically higher levels of physical activity.' },
      { type: 'multiple_choice', question: 'Why is iron particularly important for teenage girls?', options: ['Iron needs decrease during puberty', 'It is not important for them', 'Only for boys', 'Menstruation increases iron losses, and inadequate intake leads to iron-deficiency anaemia affecting energy and concentration'], correctAnswer: 3, explanation: 'Teenage girls lose iron through menstruation while simultaneously growing — making them the highest-risk group for iron-deficiency anaemia in the UK.' },
      { type: 'multiple_choice', question: 'At what age should children transition to semi-skimmed milk?', options: ['From age 10', 'From birth', 'Never', 'From age 2 — younger children need the energy and fat-soluble vitamins in whole milk'], correctAnswer: 3, explanation: 'Children under 2 need whole milk for energy and fat-soluble vitamins. Semi-skimmed can be introduced from age 2 if the child is eating well and growing normally.' },
      { type: 'multiple_choice', question: 'Why should salt intake be limited in children?', options: ['It should not be limited', 'Children\'s kidneys are less developed — excess salt increases blood pressure risk and sets lifelong taste preferences', 'Salt is always fine for children', 'Only for children with kidney disease'], correctAnswer: 1, explanation: 'Children\'s kidneys cannot process excess salt efficiently — high salt intake in childhood raises blood pressure risk and establishes preferences for salty foods.' },
    
    ],
  },
  // Chapter 2: Older Adults
  {
    unitNumber: 2, chapterNumber: 2, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is sarcopenia?', options: ['A vitamin deficiency', 'Age-related muscle mass loss', 'Age-related bone loss', 'A type of arthritis'], correctAnswer: 1, explanation: 'Sarcopenia is the progressive loss of skeletal muscle mass and strength that occurs with ageing.' },
      { type: 'multiple_choice', question: 'Which nutrient becomes harder to absorb as people age?', options: ['Fat', 'Vitamin B12', 'Fibre', 'Vitamin C'], correctAnswer: 1, explanation: 'Vitamin B12 absorption decreases with age due to reduced stomach acid production, making supplementation or fortified foods important.' },
      { type: 'multiple_choice', question: 'Why is protein intake particularly important for older adults?', options: ['To gain weight', 'Protein is only important for young adults', 'Because they digest protein faster', 'To counteract sarcopenia and maintain muscle mass'], correctAnswer: 3, explanation: 'Adequate protein intake helps counteract sarcopenia and maintain functional strength and independence in older adults.' },
      { type: 'multiple_choice', question: 'UK guidelines recommend vitamin D supplementation for adults over 65 during which months?', options: ['No supplementation needed', 'Only summer months', 'Year-round (10 micrograms daily)', 'Only winter months'], correctAnswer: 2, explanation: 'Adults over 65 are advised to supplement with 10 micrograms of vitamin D year-round due to reduced skin synthesis and limited sun exposure.' },
      { type: 'multiple_choice', question: 'Which condition is caused by severe vitamin D and calcium deficiency in older adults?', options: ['Anaemia', 'Scurvy', 'Osteoporosis', 'Rickets'], correctAnswer: 2, explanation: 'Osteoporosis — reduced bone density and increased fracture risk — is strongly associated with long-term vitamin D and calcium deficiency.' },
      { type: 'scenario', question: 'What dietary change would you suggest first?', scenario: 'An 70-year-old reports poor appetite and is losing weight unintentionally.', options: ['Reduce meal frequency', 'Put them on a calorie-restricted diet', 'Increase fibre intake significantly', 'Offer smaller, more frequent nutrient-dense meals and snacks'], correctAnswer: 3, explanation: 'Smaller, more frequent nutrient-dense meals can help maintain adequate nutrition when appetite is reduced.' },
      { type: 'multiple_choice', question: 'Why does appetite often decrease in older adults?', options: ['Appetite stays the same throughout life', 'Only due to dental problems', 'Reduced sense of taste and smell, medications, reduced activity, and social isolation can all reduce appetite', 'They need less food'], correctAnswer: 2, explanation: 'Multiple factors reduce appetite in older adults: diminished taste/smell, medication side effects, reduced activity, social isolation, and depression.' },
      { type: 'multiple_choice', question: 'Why is vitamin D supplementation recommended for adults over 65?', options: ['Only if diagnosed with deficiency', 'It is not recommended', 'Reduced skin synthesis from sunlight, less time outdoors, and reduced kidney conversion make supplementation important', 'Older adults make more vitamin D'], correctAnswer: 2, explanation: 'Over 65s produce less vitamin D from sunlight, spend less time outdoors, and have reduced kidney conversion — 10μg daily supplementation is recommended year-round.' },
      { type: 'multiple_choice', question: 'What is the risk of dehydration in older adults?', options: ['They naturally drink enough', 'Only in hot weather', 'No increased risk', 'Higher risk due to reduced thirst sensation, kidney changes, and medication effects'], correctAnswer: 3, explanation: 'Older adults are at higher dehydration risk because the thirst mechanism weakens with age, kidneys become less efficient, and some medications increase fluid loss.' },
      { type: 'multiple_choice', question: 'Why are nutrient-dense foods particularly important for older adults?', options: ['Energy needs may decrease but nutrient needs remain the same or increase — every calorie needs to deliver maximum nutrition', 'Supplements replace the need for nutrient-dense food', 'They need fewer nutrients', 'Only protein matters'], correctAnswer: 0, explanation: 'Older adults often need fewer calories but the same or more nutrients — nutrient-dense foods (eggs, oily fish, vegetables, wholegrains) maximise nutrition per calorie.' },
    
    ],
  },
  // Chapter 3: Pregnancy & Postnatal
  {
    unitNumber: 2, chapterNumber: 3, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which nutrient is critical before and during early pregnancy to prevent neural tube defects?', options: ['Folic acid (folate)', 'Calcium', 'Vitamin B12', 'Vitamin C'], correctAnswer: 0, explanation: 'Folic acid is essential before conception and during the first 12 weeks of pregnancy to reduce the risk of neural tube defects such as spina bifida.' },
      { type: 'multiple_choice', question: 'The phrase "eating for two" during pregnancy is:', options: ['Only true in the first trimester', 'Completely accurate — double your calories', 'Misleading — only an extra 200 calories per day is needed in the third trimester', 'True for protein but not calories'], correctAnswer: 2, explanation: 'The "eating for two" myth is misleading. Only an additional 200 calories per day is recommended, and only during the third trimester.' },
      { type: 'multiple_choice', question: 'Which of these foods should be avoided during pregnancy?', options: ['Pasteurised milk', 'Cooked chicken', 'Raw shellfish', 'Steamed vegetables'], correctAnswer: 2, explanation: 'Raw shellfish carries a risk of harmful bacteria and should be avoided during pregnancy. All seafood should be thoroughly cooked.' },
      { type: 'multiple_choice', question: 'Iron needs during pregnancy increase primarily because:', options: ['Blood volume increases significantly to supply the placenta and baby', 'Iron is used to produce breast milk', 'Pregnant women lose iron through sweat', 'The baby needs iron for bone growth'], correctAnswer: 0, explanation: 'Blood volume increases by up to 50% during pregnancy, significantly increasing iron requirements to maintain haemoglobin levels.' },
      { type: 'multiple_choice', question: 'Which supplement is recommended for all pregnant women in the UK?', options: ['Vitamin C', 'Omega-3', 'Folic acid and vitamin D', 'Iron and zinc'], correctAnswer: 2, explanation: 'The NHS recommends folic acid (400mcg daily) from before conception until week 12, and vitamin D (10mcg daily) throughout pregnancy.' },
      { type: 'scenario', question: 'Is this advice correct?', scenario: 'A pregnant woman in her second trimester is told she needs to significantly increase her calorie intake immediately.', options: ['Yes, she should eat much more right away', 'She should reduce her intake to prevent excessive weight gain', 'She should only eat protein-rich foods', 'No — additional calories are only recommended in the third trimester, and only approximately 200 per day'], correctAnswer: 3, explanation: 'Additional calorie intake is only recommended during the third trimester (approximately 200 extra calories per day), not earlier.' },
      { type: 'multiple_choice', question: 'When should folic acid supplementation begin?', options: ['After conception', 'Before conception if possible and during the first 12 weeks of pregnancy', 'In the third trimester', 'Only if the doctor prescribes it'], correctAnswer: 1, explanation: 'Folic acid (400μg daily) should ideally start before conception and continue through the first 12 weeks — the neural tube forms very early in pregnancy.' },
      { type: 'multiple_choice', question: 'What foods should be avoided during pregnancy?', options: ['All fish', 'All dairy', 'No foods need to be avoided', 'Raw or undercooked eggs, unpasteurised cheese, raw shellfish, and liver (excess vitamin A)'], correctAnswer: 3, explanation: 'Pregnancy food risks include listeria (soft cheese, pâté), salmonella (undercooked eggs), toxoplasmosis (raw meat), and excess vitamin A (liver).' },
      { type: 'multiple_choice', question: 'Does a pregnant woman really need to eat for two?', options: ['No — only an extra 200 calories per day is needed in the third trimester, with no extra needed in the first two trimesters', 'Yes — double portions needed', 'Calorie needs do not change at all', 'Triple portions in the third trimester'], correctAnswer: 0, explanation: 'The "eating for two" myth is outdated — energy needs only increase by about 200 kcal/day in the third trimester. Nutrient quality matters more than quantity.' },
      { type: 'multiple_choice', question: 'What are the nutritional benefits of breastfeeding for the mother?', options: ['None for the mother', 'It only benefits the baby', 'It uses approximately 500 extra calories per day, may reduce risk of breast and ovarian cancer, and supports uterine recovery', 'It causes nutrient deficiency'], correctAnswer: 2, explanation: 'Breastfeeding uses ~500 kcal/day (supporting post-pregnancy weight loss), reduces breast and ovarian cancer risk, and promotes uterine contraction and recovery.' },
    
    ],
  },
  // Chapter 4: Vegetarian & Vegan Diets
  {
    unitNumber: 2, chapterNumber: 4, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Which nutrient is most commonly deficient in vegan diets?', options: ['Vitamin C', 'Vitamin E', 'Vitamin B12', 'Vitamin A'], correctAnswer: 2, explanation: 'Vitamin B12 is primarily found in animal products and must be supplemented or obtained from fortified foods on a vegan diet.' },
      { type: 'multiple_choice', question: 'What does "complementary proteins" mean?', options: ['Eating protein with every meal', 'Combining plant proteins that together provide all essential amino acids', 'Eating only complete proteins', 'Using protein supplements'], correctAnswer: 1, explanation: 'Complementary proteins involve combining different plant protein sources (e.g., rice and beans) to obtain all essential amino acids.' },
      { type: 'multiple_choice', question: 'Which plant-based food is considered a complete protein?', options: ['Rice', 'Soya (tofu, tempeh)', 'Potatoes', 'Bread'], correctAnswer: 1, explanation: 'Soya products contain all essential amino acids, making them one of the few complete plant-based protein sources.' },
      { type: 'multiple_choice', question: 'Iron from plant sources (non-haem iron) is absorbed less efficiently. What can improve its absorption?', options: ['Cooking with aluminium pans', 'Taking calcium supplements at the same time', 'Consuming vitamin C alongside iron-rich foods', 'Drinking tea with meals'], correctAnswer: 2, explanation: 'Vitamin C significantly enhances the absorption of non-haem iron from plant sources. Consuming citrus fruit or peppers alongside iron-rich meals helps.' },
      { type: 'multiple_choice', question: 'Which of these is NOT a reliable source of omega-3 for vegans?', options: ['Coconut oil', 'Walnuts', 'Chia seeds', 'Flaxseeds'], correctAnswer: 0, explanation: 'Coconut oil does not contain significant omega-3 fatty acids. Flaxseeds, chia seeds, and walnuts provide plant-based ALA omega-3.' },
      { type: 'scenario', question: 'What nutrients should they pay particular attention to?', scenario: 'A new vegan asks you what supplements they should consider.', options: ['Only protein powder', 'Vitamin B12, vitamin D, omega-3, and possibly iodine and iron', 'None — a vegan diet is always complete', 'Just a multivitamin is sufficient'], correctAnswer: 1, explanation: 'Vegans should pay attention to B12 (supplement essential), vitamin D, omega-3 (algae-based), iodine, iron, and calcium from fortified sources.' },
      { type: 'multiple_choice', question: 'What is the main nutritional concern with a vegan diet?', options: ['Too much protein', 'No nutritional concerns', 'Risk of deficiency in vitamin B12, iron, calcium, omega-3, zinc, and iodine without careful planning', 'Too many carbohydrates'], correctAnswer: 2, explanation: 'Vegan diets can be nutritionally complete but require planning for B12 (must supplement), iron, calcium, omega-3 (algae-based), zinc, and iodine.' },
      { type: 'multiple_choice', question: 'What is a complete protein?', options: ['Protein with added vitamins', 'Only animal protein', 'A protein source containing all nine essential amino acids in adequate amounts', 'Any protein food'], correctAnswer: 2, explanation: 'Complete proteins contain all 9 essential amino acids — most animal proteins are complete; plant proteins often lack one or more and benefit from combining sources.' },
      { type: 'multiple_choice', question: 'How can vegetarians ensure adequate iron intake?', options: ['Only through supplements', 'Iron is only in meat', 'They cannot get enough iron', 'Eating iron-rich plant foods (lentils, beans, spinach) with vitamin C to enhance absorption'], correctAnswer: 3, explanation: 'Plant-based iron (non-haem) is less easily absorbed, but pairing with vitamin C-rich foods (citrus, peppers) significantly improves absorption.' },
      { type: 'multiple_choice', question: 'Why might a vegetarian need to eat more protein than a meat eater?', options: ['They do not', 'Only vegans need more', 'Vegetarians need less protein', 'Plant proteins are generally less digestible and have lower biological value — slightly more total protein compensates'], correctAnswer: 3, explanation: 'Plant protein digestibility is typically lower (70–90%) compared to animal protein (>95%) — eating slightly more total protein and combining sources compensates.' },
    
    ],
  },
  // Chapter 5: Cultural & Religious Diets
  {
    unitNumber: 2, chapterNumber: 5, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What does "halal" mean in the context of food?', options: ['Food without allergens', 'Vegetarian food', 'Food that is permissible under Islamic dietary law', 'Organic food only'], correctAnswer: 2, explanation: 'Halal refers to food that is permissible under Islamic law, including specific requirements for animal slaughter and prohibition of pork and alcohol.' },
      { type: 'multiple_choice', question: 'During Ramadan, Muslims fast from sunrise to sunset. Which nutritional concern is most relevant?', options: ['Dehydration and inadequate energy intake', 'Protein deficiency', 'Excessive vitamin intake', 'Too much fibre'], correctAnswer: 0, explanation: 'Extended fasting during daylight hours increases the risk of dehydration and inadequate total energy intake, particularly in summer months.' },
      { type: 'multiple_choice', question: 'Kosher dietary laws prohibit:', options: ['All forms of bread', 'Eating vegetables on Saturdays', 'Mixing meat and dairy products', 'All seafood'], correctAnswer: 2, explanation: 'Kosher laws prohibit the mixing of meat and dairy products in the same meal, along with specific requirements for animal slaughter.' },
      { type: 'multiple_choice', question: 'Why is it important to understand cultural dietary practices in a nutrition context?', options: ['To judge people for their food choices', 'To provide advice that is respectful and achievable within their food culture', 'To convince people to change their traditional diets', 'Cultural practices have no impact on nutrition'], correctAnswer: 1, explanation: "Understanding cultural practices allows nutrition professionals to provide advice that is respectful, practical, and achievable within the individual's food culture." },
      { type: 'multiple_choice', question: 'A lacto-vegetarian diet includes:', options: ['Eggs and dairy', 'Dairy but not eggs', 'Fish and dairy', 'Neither eggs nor dairy'], correctAnswer: 1, explanation: 'Lacto-vegetarian diets include dairy products but exclude eggs, meat, and fish.' },
      { type: 'scenario', question: 'What is the most respectful approach?', scenario: 'You are advising someone who follows a Hindu vegetarian diet and they ask about protein sources.', options: ['Tell them to eat meat for better health', 'Recommend plant-based proteins that align with their dietary practices: lentils, chickpeas, paneer, yoghurt', 'Ignore their cultural preferences', 'Suggest they change their religion'], correctAnswer: 1, explanation: "Providing culturally appropriate advice shows respect and ensures practical, achievable recommendations within the individual\'s belief system." },
      { type: 'multiple_choice', question: 'What is halal food?', options: ['Organic food', 'Food without additives', 'Vegetarian food', 'Food permitted under Islamic dietary laws — including specific animal slaughter requirements and prohibition of pork and alcohol'], correctAnswer: 3, explanation: 'Halal ("permissible") follows Islamic dietary law: specific slaughter methods, no pork or pork products, no alcohol, and specific food preparation requirements.' },
      { type: 'multiple_choice', question: 'What does kosher mean?', options: ['Vegetarian food', 'Food prepared according to Jewish dietary laws (kashrut) — including separation of meat and dairy, and specific animal requirements', 'Organic food', 'Healthy food'], correctAnswer: 1, explanation: 'Kosher follows Jewish dietary law: no pork or shellfish, meat and dairy are not mixed, specific slaughter requirements, and supervised preparation.' },
      { type: 'multiple_choice', question: 'Why is cultural sensitivity important when giving nutrition advice?', options: ['It is not important', 'Cultural foods are always unhealthy', 'Food is deeply connected to identity, tradition, and community — disrespecting food practices damages trust and adherence', 'Only science matters'], correctAnswer: 2, explanation: 'Food is central to cultural identity — nutrition advice that respects cultural practices is more likely to be followed and maintains the trust needed for an effective relationship.' },
      { type: 'multiple_choice', question: 'How should you approach nutrition advice for someone with dietary restrictions based on religion?', options: ['Ignore their restrictions', 'Learn about their dietary requirements, work within them, and never suggest they change their religious practices', 'Tell them their diet is wrong', 'Only give general advice'], correctAnswer: 1, explanation: 'Work within religious dietary frameworks — learn the requirements, find creative solutions within those boundaries, and never suggest compromising religious beliefs for nutrition.' },
    
    ],
  },
  // Chapter 6: Food Allergies & Intolerances
  {
    unitNumber: 2, chapterNumber: 6, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What is the key difference between a food allergy and a food intolerance?', options: ['An allergy involves the immune system; an intolerance does not', 'There is no difference', 'Allergies only affect children', 'An intolerance is more dangerous'], correctAnswer: 0, explanation: 'A food allergy triggers an immune system response that can be life-threatening. An intolerance causes digestive discomfort but does not involve the immune system.' },
      { type: 'multiple_choice', question: 'How many major food allergens must be declared on UK food labels?', options: ['20', '8', '14', '10'], correctAnswer: 2, explanation: 'UK food law requires 14 major allergens to be clearly declared on food labels and in catering establishments.' },
      { type: 'multiple_choice', question: 'Coeliac disease is an autoimmune condition triggered by:', options: ['Peanuts', 'Lactose', 'Eggs', 'Gluten'], correctAnswer: 3, explanation: 'Coeliac disease is triggered by gluten (found in wheat, barley, and rye), causing damage to the lining of the small intestine.' },
      { type: 'multiple_choice', question: 'Anaphylaxis is:', options: ['A type of food intolerance', 'Only caused by shellfish', 'A mild digestive reaction', 'A severe, potentially life-threatening allergic reaction'], correctAnswer: 3, explanation: 'Anaphylaxis is a severe allergic reaction that can cause breathing difficulties, swelling, and circulatory collapse. It requires immediate medical attention.' },
      { type: 'multiple_choice', question: 'Which of these is NOT one of the 14 major UK allergens?', options: ['Mustard', 'Tomatoes', 'Tree nuts', 'Soya'], correctAnswer: 1, explanation: 'Tomatoes are not on the list of 14 major UK allergens. The 14 include cereals containing gluten, crustaceans, eggs, fish, peanuts, soya, milk, tree nuts, celery, mustard, sesame, sulphur dioxide, lupin, and molluscs.' },
      { type: 'scenario', question: 'What is the correct course of action?', scenario: 'A customer in a café tells you they have a severe nut allergy and asks if a cake contains nuts.', options: ['Suggest they just try a small piece first', 'Guess and say no', 'Check the ingredient list and allergen information thoroughly before confirming', 'Tell them it probably does not'], correctAnswer: 2, explanation: 'You must always check allergen information thoroughly. Guessing or assuming can be life-threatening for someone with a severe allergy.' },
      { type: 'multiple_choice', question: 'What is the difference between a food allergy and a food intolerance?', options: ['They are the same', 'Intolerances are more dangerous', 'An allergy involves the immune system and can be life-threatening; an intolerance causes discomfort but is not immune-mediated', 'Allergies are not serious'], correctAnswer: 2, explanation: 'Food allergies trigger immune responses (potentially fatal anaphylaxis); intolerances cause digestive discomfort but do not involve the immune system.' },
      { type: 'multiple_choice', question: 'What are the 14 major food allergens that must be declared in the UK?', options: ['Only 5 allergens exist', 'Only nuts and dairy', 'Celery, cereals with gluten, crustaceans, eggs, fish, lupin, milk, molluscs, mustard, nuts, peanuts, sesame, soya, sulphur dioxide', 'Allergens do not need declaring'], correctAnswer: 2, explanation: 'UK law requires 14 allergens to be declared on food labels and menus — these cause the majority of allergic reactions.' },
      { type: 'multiple_choice', question: 'What is anaphylaxis?', options: ['A food intolerance', 'A stomach upset', 'A mild reaction', 'A severe, potentially life-threatening allergic reaction requiring immediate adrenaline (EpiPen) and emergency services'], correctAnswer: 3, explanation: 'Anaphylaxis is a severe allergic reaction causing airway swelling, blood pressure drop, and potentially death — requires immediate adrenaline injection and 999 call.' },
      { type: 'multiple_choice', question: 'What is lactose intolerance?', options: ['A psychological condition', 'An immune reaction to dairy', 'An allergy to milk', 'The inability to digest lactose (milk sugar) due to insufficient lactase enzyme — causing bloating, gas, and diarrhoea'], correctAnswer: 3, explanation: 'Lactose intolerance is enzyme deficiency (not allergy) — undigested lactose is fermented by gut bacteria causing bloating, gas, and diarrhoea. Lactose-free products are tolerated.' },
    
    ],
  },
  // Chapter 7: Athletes vs Sedentary Individuals
  {
    unitNumber: 2, chapterNumber: 7, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'Compared to sedentary individuals, active people typically need:', options: ['The same nutrition regardless of activity', 'Fewer calories and less protein', 'More calories, more protein, and greater attention to hydration', 'Only more carbohydrates'], correctAnswer: 2, explanation: 'Active individuals have higher energy, protein, and fluid requirements to support training, recovery, and performance.' },
      { type: 'multiple_choice', question: 'What is TDEE?', options: ['A type of meal plan', 'Total Daily Energy Expenditure — the total calories burned in a day', 'Total Diet and Exercise Evaluation', 'The Daily Exercise Estimate'], correctAnswer: 1, explanation: 'TDEE (Total Daily Energy Expenditure) is the total number of calories your body burns in a day, including BMR and activity.' },
      { type: 'multiple_choice', question: 'A general protein recommendation for active individuals is approximately:', options: ['0.5g per kg body weight', '0.8g per kg body weight', '1.4–2.0g per kg body weight', '5g per kg body weight'], correctAnswer: 2, explanation: 'Research suggests active individuals benefit from 1.4–2.0g of protein per kg body weight per day, depending on training type and intensity.' },
      { type: 'multiple_choice', question: 'Why is carbohydrate intake particularly important for endurance athletes?', options: ['Carbohydrate prevents all injuries', 'It is the cheapest macronutrient', 'Endurance athletes do not need protein', 'Carbohydrate (glycogen) is the primary fuel for sustained moderate-to-high intensity exercise'], correctAnswer: 3, explanation: 'Glycogen (stored carbohydrate) is the primary fuel source for sustained exercise. Depleted glycogen leads to fatigue and reduced performance.' },
      { type: 'multiple_choice', question: 'Which statement about sedentary individuals is correct?', options: ['They should eliminate carbohydrates', 'They have lower energy requirements but still need all essential nutrients', 'They need zero protein', 'They do not need hydration'], correctAnswer: 1, explanation: 'Sedentary individuals have lower calorie needs but still require adequate protein, vitamins, minerals, and hydration for health.' },
      { type: 'scenario', question: 'What is the most relevant nutritional adjustment?', scenario: 'A person who was previously sedentary has started training five days per week and is feeling constantly tired.', options: ['Only eat before training', 'Reduce food intake', 'Increase total calorie and protein intake to match new activity levels', 'Eliminate all fat'], correctAnswer: 2, explanation: 'Increasing activity without adjusting nutrition creates an energy deficit, leading to fatigue. Calorie and protein intake should increase to match demand.' },
      { type: 'multiple_choice', question: 'How do the nutritional needs of an athlete differ from a sedentary person?', options: ['No difference', 'Only protein differs', 'Sedentary people need more food', 'Athletes need more energy, more protein for repair, more carbohydrates for fuel, and more fluids for hydration'], correctAnswer: 3, explanation: 'Athletes have significantly higher needs across all macronutrients: more energy (fuel), more protein (repair), more carbohydrates (glycogen), and more fluids (sweat replacement).' },
      { type: 'multiple_choice', question: 'Why is protein timing more important for athletes than sedentary individuals?', options: ['Sedentary people benefit more from timing', 'It is not more important', 'Athletes have elevated MPS post-training — consuming protein within a few hours of exercise optimises the recovery response', 'Timing never matters'], correctAnswer: 2, explanation: 'Exercise elevates muscle protein synthesis for 24–48 hours — providing protein during this window (especially within a few hours) maximises the adaptive response.' },
      { type: 'multiple_choice', question: 'What additional nutrient considerations do endurance athletes have?', options: ['Higher carbohydrate needs (5–10g/kg), increased electrolyte replacement, and greater fluid intake', 'None beyond normal', 'Less food than normal', 'Only protein supplementation'], correctAnswer: 0, explanation: 'Endurance athletes require high carbohydrate intake (5–10g/kg) for glycogen, electrolyte replacement for sweat losses, and systematic hydration strategies.' },
      { type: 'multiple_choice', question: 'Should sedentary individuals follow the same diet as athletes?', options: ['Yes — the same diet works for everyone', 'Sedentary people do not need to think about nutrition', 'Athletes and sedentary people have identical needs', 'No — sedentary individuals need fewer calories and less carbohydrate, though protein and micronutrient needs remain important'], correctAnswer: 3, explanation: 'Sedentary individuals need fewer total calories and carbohydrates but still benefit from adequate protein, fibre, and micronutrients for health and body composition.' },
    
    ],
  },
  // Chapter 8: Special Medical Considerations
  {
    unitNumber: 2, chapterNumber: 8, pickCount: 5, passMarkPercent: 80,
    questionBank: [
      { type: 'multiple_choice', question: 'What does "scope of practice" mean in nutrition?', options: ['The boundaries of what you are qualified to advise on', 'How much you can charge for services', 'The number of clients you can work with', 'The range of exercises you can prescribe'], correctAnswer: 0, explanation: 'Scope of practice defines the limits of what a professional is qualified and legally permitted to advise on. Medical nutrition therapy is outside the scope for non-registered practitioners.' },
      { type: 'multiple_choice', question: 'Type 2 diabetes is primarily characterised by:', options: ['The body becoming resistant to insulin, leading to elevated blood sugar', 'The pancreas producing no insulin', 'Excessive protein consumption', 'An allergy to sugar'], correctAnswer: 0, explanation: "Type 2 diabetes involves insulin resistance — the body\'s cells respond poorly to insulin, resulting in elevated blood glucose levels." },
      { type: 'multiple_choice', question: 'If a client discloses a medical condition, what should a nutrition adviser do?', options: ['Provide detailed medical nutrition advice', 'Refer them to a registered dietitian or their GP', 'Research the condition on the internet and advise accordingly', 'Ignore the condition and continue'], correctAnswer: 1, explanation: 'Medical conditions require specialist assessment. A nutrition adviser should refer to a registered dietitian or GP rather than providing medical advice.' },
      { type: 'multiple_choice', question: 'Which condition requires careful management of sodium intake?', options: ['Lactose intolerance', 'Hypertension (high blood pressure)', 'Coeliac disease', 'Iron-deficiency anaemia'], correctAnswer: 1, explanation: 'Hypertension is strongly linked to excessive sodium intake. Reducing salt is a key dietary strategy for managing blood pressure.' },
      { type: 'multiple_choice', question: 'An eating disorder is:', options: ['Not relevant to nutrition professionals', 'Only about food restriction', 'Simply a lifestyle choice', 'A serious mental health condition requiring professional treatment'], correctAnswer: 3, explanation: 'Eating disorders are serious mental health conditions with physical consequences. They require professional treatment from qualified specialists.' },
      { type: 'scenario', question: 'What is the correct response?', scenario: 'A client asks you to design a specific diet plan for their recently diagnosed kidney disease.', options: ['Create a kidney-friendly meal plan', 'Tell them to eat less protein and hope for the best', 'Research kidney diets online and advise', 'Explain that this is outside your scope of practice and refer them to a registered dietitian with renal expertise'], correctAnswer: 3, explanation: 'Kidney disease requires specialist medical nutrition therapy. This is outside the scope of a general nutrition adviser and must be referred to a renal dietitian.' },
      { type: 'multiple_choice', question: 'What is coeliac disease?', options: ['A temporary condition', 'A mild intolerance', 'An autoimmune condition where gluten triggers damage to the small intestine lining, requiring lifelong gluten avoidance', 'A food preference'], correctAnswer: 2, explanation: 'Coeliac disease is autoimmune — gluten causes the immune system to attack the small intestine, damaging villi and impairing nutrient absorption. It requires lifelong strict gluten avoidance.' },
      { type: 'multiple_choice', question: 'When should a fitness professional refer a client to a medical professional?', options: ['When the client asks', 'Only in emergencies', 'When a client presents with a diagnosed medical condition, suspected clinical issue, or symptoms beyond your scope', 'Never — you can handle everything'], correctAnswer: 2, explanation: 'Refer whenever a client has or may have a medical condition affecting nutrition — diabetes, eating disorders, kidney disease, and clinical symptoms all require qualified clinical support.' },
      { type: 'multiple_choice', question: 'Why is scope of practice important in nutrition?', options: ['It is not important', 'Working within your qualification level protects clients from harm and protects you from legal liability', 'It limits what you can charge', 'Only doctors have scope of practice'], correctAnswer: 1, explanation: 'Scope of practice protects everyone — clients receive appropriate care, you avoid giving dangerous advice beyond your competence, and you are protected from legal issues.' },
      { type: 'multiple_choice', question: 'What nutritional considerations exist for someone with type 2 diabetes?', options: ['Only avoid sugar', 'Only protein matters', 'Blood glucose management through consistent carbohydrate control, fibre intake, and regular meals — but specific advice requires a dietitian', 'No dietary changes needed'], correctAnswer: 2, explanation: 'Type 2 diabetes requires careful carbohydrate management, adequate fibre, and regular eating patterns — but specific dietary management is within a registered dietitian\'s scope, not a fitness professional\'s.' },
    
    ],
  },
];

// ═══ UNIT 3 CHAPTER QUIZZES — Food Safety & Practical Skills ═══
