import type { UnitAssessment } from '../types';

export const nutritionL2Unit4Assessment: UnitAssessment = {
  unitNumber: 4,
  title: 'Unit 4 Assessment — Planning Balanced Diets',
  passMarkPercent: 80,
  questions: [
    { type: 'multiple_choice', question: 'A SMART goal must be:', options: ['Short, Moderate, Active, Restricted, Tracked', 'Social, Mental, Academic, Reliable, Technical', 'Simple, Meaningful, Attractive, Rapid, Tough', 'Specific, Measurable, Achievable, Relevant, Time-bound'], correctAnswer: 3, explanation: 'SMART stands for Specific, Measurable, Achievable, Relevant, and Time-bound.' },
    { type: 'multiple_choice', question: 'BMR stands for:', options: ['Best Macro Ratio', 'Body Mass Ratio', 'Basal Metabolic Rate', 'Basic Meal Requirement'], correctAnswer: 2, explanation: 'Basal Metabolic Rate is the calories your body burns at complete rest for basic life functions.' },
    { type: 'multiple_choice', question: 'A sustainable rate of weight loss is:', options: ['As fast as possible', '0.5–1kg per week', '3kg per week', '5kg per month minimum'], correctAnswer: 1, explanation: 'A rate of 0.5–1kg per week is sustainable, preserving muscle mass and energy levels.' },
    { type: 'multiple_choice', question: 'Macro tracking monitors your daily intake of:', options: ['Protein, carbohydrate, and fat', 'Calories only', 'Vitamins and minerals', 'Water only'], correctAnswer: 0, explanation: 'Macro tracking focuses on the three macronutrients: protein, carbohydrate, and fat.' },
    { type: 'multiple_choice', question: 'The "80/20" approach means:', options: ['80% protein, 20% carbohydrate', '80 meals per week planned', 'Eating 80% of your plate', 'Following your plan 80% of the time with 20% flexibility'], correctAnswer: 3, explanation: 'The 80/20 approach prioritises consistency most of the time while allowing real-life flexibility.' },
    { type: 'multiple_choice', question: '"Detox" diets and juice cleanses:', options: ['Are scientifically proven to remove toxins', 'Should be done monthly', 'Have no scientific basis — the liver and kidneys handle detoxification', 'Are recommended by the NHS'], correctAnswer: 2, explanation: 'There is no scientific evidence that commercial detox products improve natural detoxification, which the liver and kidneys perform continuously.' },
    { type: 'multiple_choice', question: 'Habit stacking is:', options: ['A type of meal prep', 'Linking a new habit to an existing routine for consistency', 'Doing 10 new habits simultaneously', 'Stacking meals together'], correctAnswer: 1, explanation: 'Habit stacking attaches a new behaviour to an established routine, increasing the likelihood of it becoming automatic.' },
    { type: 'scenario', question: 'What should you recommend?', scenario: 'A person has been dieting strictly for 12 weeks and feels exhausted, irritable, and their weight loss has stalled.', options: ['Consider a diet break or reverse to maintenance calories temporarily, then reassess', 'Diet harder', 'Give up entirely', 'Switch to a liquid diet'], correctAnswer: 0, explanation: 'Extended dieting can cause metabolic adaptation and psychological fatigue. A temporary return to maintenance calories allows recovery before resuming.' },
    { type: 'multiple_choice', question: 'Which factor is most important for long-term nutrition success?', options: ['Eliminating all "bad" foods', 'Following a perfect diet', 'Taking supplements', 'Consistency over perfection'], correctAnswer: 3, explanation: 'Consistency with a good-enough approach outperforms sporadic attempts at perfection every time.' },
    { type: 'multiple_choice', question: 'Environment design for nutrition means:', options: ['Painting your kitchen green', 'Only eating at home', 'Arranging your surroundings to make healthy choices easier', 'Buying a bigger kitchen'], correctAnswer: 2, explanation: 'Placing nutritious foods visibly, removing tempting ultra-processed items, and organising your kitchen supports better daily choices.' },
  ],
};
