import type { UnitAssessment } from '../types';
import { nutritionL3Unit1Assessment } from './assessments';
import { nutritionL3Unit2Assessment } from './unit2-assessments';
import { nutritionL3Unit3Assessment } from './unit3-assessments';
import { nutritionL3Unit4Assessment } from './unit4-assessments';

export const nutritionL3FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 3 Nutrition Final Assessment',
  passMarkPercent: 80, pickCount: 40,
  questions: [
    ...nutritionL3Unit1Assessment.questions,
    ...nutritionL3Unit2Assessment.questions,
    ...nutritionL3Unit3Assessment.questions,
    ...nutritionL3Unit4Assessment.questions,
    // ── Cross-unit final questions ──
    { type: 'scenario', question: 'What is the most important nutritional priority?', scenario: 'An intermediate lifter training 4 times per week wants to build muscle. They currently eat irregularly — some days very little, some days excessively.', options: ['Put them on a strict keto diet immediately', 'Establish consistent daily energy intake with a moderate surplus and adequate protein first', 'Tell them to eat as much as possible', 'Focus only on supplementation'], correctAnswer: 1, explanation: 'Consistency in energy and protein intake is the foundation. Before fine-tuning nutrient timing or supplementation, establish regular meals with adequate total calories and 1.6-2.2g/kg protein.' },
    { type: 'multiple_choice', question: 'The hierarchy of nutritional importance for body composition is:', options: ['Supplements > meal timing > calories', 'Calories > macronutrients > micronutrients > meal timing > supplements', 'Meal timing > macronutrients > calories', 'Food quality is the only factor that matters'], correctAnswer: 1, explanation: "Eric Helms\' nutrition pyramid: total calories matter most, then macronutrient ratios, then micronutrients/fibre/water, then meal timing, and finally supplements — in that order." },
    { type: 'multiple_choice', question: "Leucine\'s role in muscle protein synthesis involves:", options: ['Providing energy for training', 'Directly activating the mTOR signalling pathway', 'Reducing cortisol levels', 'Increasing fat oxidation'], correctAnswer: 1, explanation: 'Leucine is a key amino acid that directly activates the mTOR pathway — the molecular switch for muscle protein synthesis. Aim for 2-3g leucine per meal for maximal MPS stimulation.' },
    { type: 'scenario', question: 'What is the most evidence-based approach?', scenario: 'A recreational runner wants to lose body fat while maintaining performance. They are considering eliminating all carbohydrates.', options: ['Support the zero-carb approach for maximum fat loss', 'Advise a moderate calorie deficit while maintaining sufficient carbohydrate to fuel training', 'Recommend eating only protein and fat', 'Suggest they stop running until they reach their target weight'], correctAnswer: 1, explanation: 'Carbohydrate fuels endurance performance. A moderate deficit (300-500 kcal) while maintaining adequate carbohydrate preserves training quality and performance while enabling fat loss.' },
    { type: 'multiple_choice', question: 'Metabolic adaptation during prolonged dieting includes:', options: ['Increased resting metabolic rate', 'No physiological changes', 'Decreased RMR, increased hunger hormones, and reduced NEAT', 'Only changes in muscle mass'], correctAnswer: 2, explanation: 'Prolonged dieting triggers adaptive thermogenesis: RMR decreases beyond what weight loss alone would predict, ghrelin increases (hunger), leptin decreases (satiety), and NEAT drops significantly.' },
    { type: 'multiple_choice', question: 'Creatine monohydrate supplementation is supported by evidence for:', options: ['Endurance performance only', 'Increased strength, power output, and lean body mass', 'Weight loss', 'Improved sleep quality'], correctAnswer: 1, explanation: 'Creatine monohydrate is one of the most extensively researched supplements — consistently shown to increase strength, power, lean mass, and high-intensity exercise capacity.' },
    { type: 'multiple_choice', question: 'Alcohol impairs fitness goals primarily by:', options: ['Adding zero calories', 'Providing 7 kcal/g with no nutritional benefit while impairing protein synthesis, sleep, and recovery', 'Only causing dehydration', 'Improving testosterone levels'], correctAnswer: 1, explanation: 'Alcohol provides 7 kcal/g (empty calories), suppresses muscle protein synthesis by up to 37%, disrupts sleep architecture, impairs recovery, and reduces testosterone.' },
    { type: 'scenario', question: 'What is the best approach?', scenario: 'A client has been tracking macros meticulously for 6 months and has developed anxiety around eating any untracked meals. They refuse to eat at restaurants.', options: ['Praise their dedication and encourage even stricter tracking', 'Recognise this as potentially disordered behaviour and transition towards more flexible approaches while monitoring', 'Tell them to stop tracking immediately', 'Suggest they only eat at home forever'], correctAnswer: 1, explanation: 'Rigid dietary tracking that causes anxiety and social avoidance can indicate disordered eating patterns. Transitioning to flexible approaches while monitoring wellbeing is appropriate — refer if concerning.' },
    { type: 'multiple_choice', question: 'Post-exercise glycogen replenishment is most important for:', options: ['Everyone after every workout equally', 'Athletes training again within 8 hours who need rapid recovery', 'Only marathon runners', 'People trying to lose weight'], correctAnswer: 1, explanation: 'Rapid glycogen replenishment (high-GI carbohydrate within 30-60 minutes post-exercise) is most critical when training again within 8 hours. For single daily sessions, total daily intake matters more.' },
    { type: 'multiple_choice', question: 'The scope of practice for a Level 3 nutrition adviser includes:', options: ['Diagnosing eating disorders and prescribing therapeutic diets', 'Providing general healthy eating advice, supporting behaviour change, and referring when appropriate', 'Prescribing supplements for medical conditions', 'Overriding GP dietary advice'], correctAnswer: 1, explanation: 'Level 3 nutrition advisers provide evidence-based general guidance, support behaviour change, and recognise when to refer to dietitians, GPs, or mental health professionals for clinical needs.' },
    { type: 'multiple_choice', question: 'Iron from plant sources (non-haem) is best absorbed when:', options: ['Consumed with tea or coffee', 'Paired with vitamin C-rich foods', 'Taken with calcium supplements', 'Eaten on an empty stomach with water only'], correctAnswer: 1, explanation: 'Vitamin C significantly enhances non-haem iron absorption by reducing ferric iron to the more absorbable ferrous form. Tannins (tea/coffee) and calcium inhibit absorption.' },
    { type: 'multiple_choice', question: 'NEAT (Non-Exercise Activity Thermogenesis) is significant because:', options: ['It contributes nothing to daily energy expenditure', 'It can account for 15-30% of total energy expenditure and drops significantly during dieting', 'It only includes formal exercise', 'It cannot be influenced by behaviour'], correctAnswer: 1, explanation: 'NEAT — all daily movement outside formal exercise — can vary by 2,000+ kcal/day between individuals. It decreases substantially during calorie restriction, partly explaining weight loss plateaus.' },
    { type: 'scenario', question: 'What is the best first step?', scenario: 'A client following a vegan diet for ethical reasons reports fatigue, frequent illness, and poor concentration. They eat mainly rice, pasta, and bread.', options: ['Tell them to stop being vegan', 'Assess their diet for common vegan deficiencies (B12, iron, protein, omega-3, zinc) and suggest appropriate foods and supplements', 'Recommend a protein powder only', 'Refer them to a GP immediately without any dietary assessment'], correctAnswer: 1, explanation: 'The symptoms suggest potential nutrient deficiencies common in poorly planned vegan diets. Assess intake, identify gaps (B12 is almost certainly needed), suggest diverse plant foods, and refer to GP if symptoms persist.' },
    { type: 'multiple_choice', question: 'The Transtheoretical Model is useful in nutrition coaching because:', options: ['It provides a meal plan for each stage', "It matches intervention strategies to the client\'s readiness for change", 'It eliminates the need for personalisation', 'It only applies to people with eating disorders'], correctAnswer: 1, explanation: "Matching strategies to stages (e.g., education for pre-contemplators, action plans for those in preparation) increases effectiveness. Pushing someone to act before they\'re ready often backfires." },
    { type: 'multiple_choice', question: 'For endurance events lasting over 90 minutes, carbohydrate intake should be:', options: ['Zero — fat adaptation is sufficient', '30-60g per hour from easily digestible sources', 'As much as possible', 'Only consumed after the event'], correctAnswer: 1, explanation: 'During prolonged endurance exercise (>90 min), consuming 30-60g/hour of carbohydrate from gels, drinks, or easily digested food maintains blood glucose and delays fatigue.' },
    { type: 'multiple_choice', question: 'Omega-3 fatty acids (EPA/DHA) are important for athletes because:', options: ['They directly build muscle', 'They reduce inflammation, support recovery, and aid cardiovascular and brain health', 'They replace the need for carbohydrate', 'They are only found in supplements'], correctAnswer: 1, explanation: 'EPA and DHA have anti-inflammatory properties that support recovery from training, along with cardiovascular benefits, brain health, and potential improvements in mood and cognition.' },
    { type: 'multiple_choice', question: 'The best dietary approach for long-term fat loss is:', options: ['The most restrictive diet available', 'Whichever creates a sustainable calorie deficit the individual can adhere to', 'A specific named diet (keto, paleo, etc.) regardless of preference', 'Eliminating carbohydrates permanently'], correctAnswer: 1, explanation: "Meta-analyses consistently show adherence is the strongest predictor of diet success. The best diet is one that creates a sustainable deficit while fitting the person\'s lifestyle, preferences, and health needs." },
    { type: 'scenario', question: 'What is the most appropriate response?', scenario: 'A client asks you to create a specific diet plan for their Type 2 diabetes management.', options: ['Create a detailed therapeutic diet plan', 'Explain that diabetes management is beyond your scope of practice and refer them to a registered dietitian or their GP', 'Tell them to eliminate all sugar', 'Prescribe metformin with their meals'], correctAnswer: 1, explanation: 'Therapeutic diet planning for medical conditions is the scope of registered dietitians and medical professionals. A Level 3 nutrition adviser should refer appropriately while supporting general healthy eating.' },
    { type: 'multiple_choice', question: 'Motivational Interviewing differs from traditional advice-giving because:', options: ['It tells clients exactly what to do', "It explores the client\'s own motivations for change through open questions, reflections, and affirmations", 'It is more aggressive and confrontational', 'It avoids discussing behaviour change entirely'], correctAnswer: 1, explanation: "MI is a client-centred approach that draws out the person\'s own reasons for change rather than imposing external advice — resulting in greater autonomy, motivation, and sustained behaviour change." },
    { type: 'multiple_choice', question: 'Fat-soluble vitamins (A, D, E, K) differ from water-soluble vitamins because:', options: ['They are less important for health', 'They can accumulate in body tissues, creating risk of toxicity at excessive doses', 'They need to be taken every hour', 'They are only available through supplements'], correctAnswer: 1, explanation: 'Fat-soluble vitamins are stored in body fat and the liver. Unlike water-soluble vitamins (which are largely excreted), excess fat-soluble vitamins can build up to toxic levels.' },
  ],
};
