import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const nutritionL3Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What protein range is recommended for resistance-trained individuals?', options: ['1.6–2.2g/kg', '3–4g/kg', '5g/kg', '0.5–0.8g/kg'], correctAnswer: 0, explanation: '1.6–2.2g protein per kilogram body weight is the evidence-based range.' },
    { type: 'multiple_choice', question: 'How much muscle glycogen does a high-volume session typically deplete?', options: ['25–40%', '100%', '75%', '5%'], correctAnswer: 0, explanation: 'A typical 20–25 working set session depletes approximately 25–40% of muscle glycogen.' },
    { type: 'multiple_choice', question: 'What should a pre-training meal ideally contain?', options: ['Alcohol and protein', 'Only water', 'Only fats', '25–40g protein and 40–80g carbohydrates'], correctAnswer: 3, explanation: 'A balanced pre-training meal with protein and carbohydrates 2–3 hours before provides optimal fuel.' },
    { type: 'multiple_choice', question: 'Why do very low-carb diets reduce training performance?', options: ['Suboptimal glycogen stores limit high-intensity work', 'They cause dehydration', 'They contain too much fibre', 'They increase fat burning too much'], correctAnswer: 0, explanation: 'Low carb intake means starting sessions with less glycogen, impairing performance especially later in the session.' },
    { type: 'multiple_choice', question: 'What minimum fat intake per kg body weight is recommended?', options: ['5g/kg', '0.7g/kg', '0.1g/kg', '2g/kg'], correctAnswer: 1, explanation: 'At least 0.7g fat per kilogram protects hormonal function.' },
    { type: 'multiple_choice', question: 'How does glycogen bind water?', options: ['1g water per 1g glycogen', '10g water per 1g glycogen', '3g water per 1g glycogen', 'It does not bind water'], correctAnswer: 2, explanation: 'Glycogen binds water at approximately 3g water per 1g glycogen, explaining weight changes with carb intake.' },
    { type: 'multiple_choice', question: 'What is the recommended carbohydrate intake for moderate resistance training?', options: ['0g — carbs are not needed', '3–5g per kg body weight per day', '10g per kg', 'Only protein matters'], correctAnswer: 1, explanation: 'Moderate resistance training requires 3–5g/kg/day of carbohydrates to maintain glycogen stores and support performance.' },
    { type: 'multiple_choice', question: 'What is the optimal pre-training meal timing?', options: ['Immediately before', '2–3 hours before training for a full meal, or a small snack 30–60 minutes before', 'Only after training', '6 hours before'], correctAnswer: 1, explanation: 'A full meal 2–3 hours before allows digestion; a lighter snack 30–60 minutes before provides readily available energy without GI discomfort.' },
    { type: 'multiple_choice', question: 'Why is post-training nutrition important for resistance training?', options: ['It is not important', 'It provides amino acids for MPS, carbohydrates for glycogen replenishment, and supports recovery', 'Only hydration matters', 'Only within 5 minutes'], correctAnswer: 1, explanation: 'Post-training nutrition supports the elevated MPS response and glycogen replenishment — ideally 20–40g protein + carbohydrates within a few hours.' },
    { type: 'multiple_choice', question: 'What is the role of caffeine as a pre-workout ergogenic aid?', options: ['It has no performance benefit', 'It reduces perceived exertion, increases alertness, and can improve strength and endurance performance', 'It only helps with endurance', 'It is banned in sport'], correctAnswer: 1, explanation: 'Caffeine (3–6mg/kg, 30–60 min pre-training) is one of the most effective legal ergogenic aids — reducing RPE and improving both strength and endurance performance.' },
  
  
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What carbohydrate intake is recommended for carb loading?', options: ['15–20g/kg', '8–12g/kg', '2–3g/kg', '5–6g/kg'], correctAnswer: 1, explanation: '8–12g/kg for 36–48 hours is the modern carbohydrate loading protocol.' },
    { type: 'multiple_choice', question: 'What ratio of glucose to fructose enables up to 90g/hour absorption?', options: ['2:1', '1:1', '10:1', '3:1'], correctAnswer: 0, explanation: 'A 2:1 glucose-to-fructose ratio utilises different absorption pathways for maximum uptake.' },
    { type: 'multiple_choice', question: 'What is hyponatraemia?', options: ['Dangerously low blood sodium', 'Dehydration', 'High blood sodium', 'Muscle cramping'], correctAnswer: 0, explanation: 'Hyponatraemia is dangerously low blood sodium, often from over-drinking plain water.' },
    { type: 'multiple_choice', question: 'For events under 60 minutes, what fuelling is recommended?', options: ['90g carbs per hour', 'Protein shake', '60g carbs per hour', 'Water only (possible carb mouth rinse)'], correctAnswer: 3, explanation: 'Events under 60 minutes need only water; carb mouth rinsing may provide a small benefit.' },
    { type: 'multiple_choice', question: 'Why should fuelling strategy be practised in training?', options: ['To impress your coach', 'It does not need practising', 'The gut can be trained to tolerate carbs; new strategies on race day risk GI distress', 'To save money'], correctAnswer: 2, explanation: 'The gut adapts to higher carb intake over time; trying new strategies on race day risks gastrointestinal problems.' },
    { type: 'multiple_choice', question: 'How much sodium can be lost per hour through sweat?', options: ['10–50mg', '5000mg', '0mg', '200–2000mg+'], correctAnswer: 3, explanation: 'Sodium losses vary widely from 200mg to over 2000mg per hour depending on individual factors.' },
    { type: 'multiple_choice', question: 'What is carbohydrate loading?', options: ['Eating pasta once', 'Systematically increasing carbohydrate intake in the 2–3 days before endurance events to maximise glycogen stores', 'Eliminating carbs before racing', 'Loading up immediately before a race'], correctAnswer: 1, explanation: 'Carb loading (8–12g/kg/day for 2–3 days pre-event) maximises muscle and liver glycogen, extending time to exhaustion in events over 90 minutes.' },
    { type: 'multiple_choice', question: 'During endurance exercise over 60 minutes, how many carbohydrates per hour are recommended?', options: ['0g — use fat only', '30–60g per hour from easily digested sources', '200g per hour', '5g total'], correctAnswer: 1, explanation: 'For exercise over 60 minutes, 30–60g carbs/hour from gels, drinks, or easily digested foods maintains blood glucose and delays fatigue.' },
    { type: 'multiple_choice', question: 'What is "train low, compete high" in endurance nutrition?', options: ['Training at altitude', 'Occasionally training with low carbohydrate availability to enhance fat oxidation, but competing with full glycogen stores', 'Always training with low carbs', 'A supplement strategy'], correctAnswer: 1, explanation: 'Train low, compete high: periodic low-carb training sessions enhance metabolic flexibility and fat oxidation, while competition uses full glycogen for performance.' },
    { type: 'multiple_choice', question: 'What is gut training for endurance nutrition?', options: ['A digestive disorder', 'Practising consuming carbohydrates during training to improve gut tolerance and absorption rates on race day', 'Eating before training', 'A supplement protocol'], correctAnswer: 1, explanation: 'Gut training — practising in-race nutrition during training sessions — improves gastric tolerance and carbohydrate absorption rates, reducing GI distress on race day.' },
  
  
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What caloric deficit is appropriate for most people during fat loss?', options: ['2000 calories', '100 calories', '300–500 calories', '1000+ calories'], correctAnswer: 2, explanation: 'A 300–500 calorie deficit produces sustainable fat loss of 0.25–0.5kg per week.' },
    { type: 'multiple_choice', question: 'Why should protein intake increase during a deficit?', options: ['To preserve muscle mass, increase satiety, and raise thermic effect', 'It is unnecessary', 'To gain more muscle', 'Protein has fewer calories'], correctAnswer: 0, explanation: 'Higher protein (2.0–2.4g/kg) during a deficit preserves muscle, increases fullness, and burns more calories through TEF.' },
    { type: 'multiple_choice', question: 'What is the best predictor of successful fat loss?', options: ['The specific diet chosen', 'Supplement use', 'Training intensity', 'Adherence — consistently maintaining the deficit'], correctAnswer: 3, explanation: 'Adherence consistently outperforms any specific diet methodology for long-term results.' },
    { type: 'multiple_choice', question: 'How long should fat loss phases typically last before a diet break?', options: ['Indefinitely', '2–3 weeks', '8–16 weeks', '6–12 months'], correctAnswer: 2, explanation: 'After 8–16 weeks, a planned transition to maintenance is important for hormonal and psychological recovery.' },
    { type: 'multiple_choice', question: 'Which sign suggests you should end a fat loss phase?', options: ['Occasional cravings', 'Slow weight loss', 'Loss of menstrual cycle (amenorrhoea)', 'Mild hunger before meals'], correctAnswer: 2, explanation: 'Loss of menstrual cycle is a serious sign of energy deficiency requiring immediate attention.' },
    { type: 'multiple_choice', question: 'What fibre intake supports satiety during fat loss?', options: ['100g daily', '5–10g daily', '50–75g daily', '25–35g daily'], correctAnswer: 3, explanation: 'Adequate fibre intake of 25–35g daily supports fullness and digestive health during a deficit.' },
    { type: 'multiple_choice', question: 'What is the maximum recommended rate of fat loss to preserve muscle?', options: ['5kg per week', '0.5–1% of body weight per week', '0.1kg per week', 'As fast as possible'], correctAnswer: 1, explanation: 'Losing 0.5–1% of body weight per week minimises muscle loss, hormonal disruption, and metabolic adaptation — faster loss increases muscle loss risk.' },
    { type: 'multiple_choice', question: 'Why should protein intake increase during a caloric deficit?', options: ['It should decrease', 'Higher protein preserves muscle mass, increases satiety, and has a higher thermic effect', 'Protein has no effect during dieting', 'Only carbs matter for fat loss'], correctAnswer: 1, explanation: 'During a deficit, protein should increase to 2.0–2.4g/kg to preserve muscle mass, maintain satiety, and benefit from protein\'s high thermic effect (~25%).' },
    { type: 'multiple_choice', question: 'What is a refeed day?', options: ['A cheat day', 'A planned day of increased calorie intake (primarily carbohydrates) to temporarily reverse metabolic adaptation', 'Eating as much as possible', 'A fasting day'], correctAnswer: 1, explanation: 'Refeeds are structured, planned increases in carbohydrate intake — restoring leptin, thyroid hormones, and glycogen without the psychological damage of "cheat days."' },
    { type: 'multiple_choice', question: 'What determines whether you lose fat or muscle during weight loss?', options: ['Calories alone', 'The combination of caloric deficit size, protein intake, resistance training, and rate of weight loss', 'Only exercise type', 'Genetics exclusively'], correctAnswer: 1, explanation: 'Fat vs muscle loss depends on multiple factors: moderate deficit + high protein + resistance training + slow rate of loss = maximal fat loss with muscle preservation.' },
  
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What caloric surplus is appropriate for a lean bulk?', options: ['200–400 calories', '1000 calories', '2000 calories', '0 calories'], correctAnswer: 0, explanation: 'A modest 200–400 calorie surplus optimises muscle growth while minimising fat gain.' },
    { type: 'multiple_choice', question: 'What rate of weight gain is appropriate for intermediate lifters?', options: ['1kg per week', '0.25–0.5% body weight per month', '2% body weight per week', '5kg per month'], correctAnswer: 1, explanation: 'Intermediate lifters should aim for approximately 0.25–0.5% body weight gain per month.' },
    { type: 'multiple_choice', question: 'Do larger surpluses proportionally increase muscle growth?', options: ['Only with steroids', 'Yes, more food equals more muscle', 'Only for beginners', 'No — beyond a moderate surplus, extra calories primarily increase fat'], correctAnswer: 3, explanation: 'Muscle growth rate is biologically limited; excess calories beyond a moderate surplus become fat.' },
    { type: 'multiple_choice', question: 'What should you monitor alongside body weight during a gaining phase?', options: ['Hair growth', 'Waist measurement', 'Blood pressure', 'Skin colour'], correctAnswer: 1, explanation: 'If waist increases significantly faster than weight, the surplus is likely too large.' },
    { type: 'multiple_choice', question: 'How fast can beginners gain muscle?', options: ['Approximately 0.5–1% body weight per month', 'They cannot gain muscle', '5kg per week', '10kg per month'], correctAnswer: 0, explanation: 'Beginners can gain approximately 0.5–1% body weight per month with a higher proportion as muscle.' },
    { type: 'multiple_choice', question: 'What is a "dirty bulk"?', options: ['Training without showering', 'Eating unclean food', 'Eating fast food only', 'Unrestricted eating with a very large surplus, leading to excessive fat gain'], correctAnswer: 3, explanation: 'A dirty bulk involves unrestricted eating, producing excessive fat gain that requires longer cutting phases.' },
    { type: 'multiple_choice', question: 'What is a caloric surplus?', options: ['Eating less than you burn', 'Consuming more calories than you expend — creating the energy surplus needed for muscle growth', 'Eating exactly maintenance calories', 'Fasting'], correctAnswer: 1, explanation: 'Building muscle optimally requires a small caloric surplus (200–500 kcal above maintenance) to provide energy for the anabolic processes of muscle growth.' },
    { type: 'multiple_choice', question: 'What is the optimal surplus for lean muscle gain?', options: ['1000+ kcal daily', '200–500 kcal above maintenance — enough to support growth while minimising fat gain', 'Exactly maintenance', '50 kcal above maintenance'], correctAnswer: 1, explanation: 'A moderate surplus (200–500 kcal) supports muscle growth while limiting unnecessary fat gain — larger surpluses increase fat gain without proportionally more muscle.' },
    { type: 'multiple_choice', question: 'What is body recomposition?', options: ['Losing weight', 'Simultaneously losing fat and gaining muscle — possible for beginners, those returning to training, and those with higher body fat', 'Only possible with drugs', 'Eating maintenance calories'], correctAnswer: 1, explanation: 'Body recomposition (losing fat while gaining muscle) is possible for beginners, detrained individuals, and those with higher body fat — it requires adequate protein and progressive resistance training.' },
    { type: 'multiple_choice', question: 'What is the role of sleep in muscle growth?', options: ['Sleep is not important for muscle', 'Growth hormone peaks during deep sleep and MPS is elevated overnight — sleep deprivation directly impairs muscle recovery', 'Only naps matter', 'Sleep only affects recovery not growth'], correctAnswer: 1, explanation: 'Deep sleep triggers peak growth hormone release and supports overnight MPS — chronic sleep deprivation reduces anabolic hormones and impairs muscle protein synthesis.' },
  
  
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'At what percentage of body weight dehydration does performance decline?', options: ['2%', '5%', '0.5%', '10%'], correctAnswer: 0, explanation: '2% dehydration consistently impairs both physical and cognitive performance.' },
    { type: 'multiple_choice', question: 'What urine colour indicates good hydration?', options: ['Dark yellow', 'Orange', 'Clear', 'Pale straw'], correctAnswer: 3, explanation: 'Pale straw colour indicates good hydration; very clear may indicate over-hydration.' },
    { type: 'multiple_choice', question: 'How much water should you drink 2–3 hours before training?', options: ['400–600ml', '50ml', '2 litres', '5 litres'], correctAnswer: 0, explanation: 'Pre-hydrating with 400–600ml in the 2–3 hours before exercise is recommended.' },
    { type: 'multiple_choice', question: 'Is drinking 8 glasses of water per day scientifically supported?', options: ['Only in summer', 'Only for athletes', 'No — fluid needs vary based on many factors', 'Yes, it is essential'], correctAnswer: 2, explanation: 'The 8-glasses rule has no robust scientific basis; needs vary by size, activity, climate, and diet.' },
    { type: 'multiple_choice', question: 'How much fluid should you drink to replace 1kg of weight lost during exercise?', options: ['500ml', '1.5 litres (150%)', '1 litre', '3 litres'], correctAnswer: 1, explanation: 'Replace approximately 150% of weight lost — 1.5 litres for every 1kg.' },
    { type: 'multiple_choice', question: 'What hormone controls kidney water retention?', options: ['Anti-diuretic hormone (ADH)', 'Insulin', 'Cortisol', 'Testosterone'], correctAnswer: 0, explanation: 'ADH controls how much water the kidneys retain to maintain fluid balance.' },
    { type: 'multiple_choice', question: 'What is hyponatraemia?', options: ['Dehydration', 'Dangerously low blood sodium caused by drinking too much water without electrolytes', 'High sodium levels', 'A supplement'], correctAnswer: 1, explanation: 'Hyponatraemia occurs when excessive water intake dilutes blood sodium — potentially fatal. It is prevented by including electrolytes during prolonged exercise.' },
    { type: 'multiple_choice', question: 'How can you assess hydration status?', options: ['Only through blood tests', 'Urine colour (pale yellow = hydrated), body weight changes, and thirst', 'You cannot assess it', 'Only during exercise'], correctAnswer: 1, explanation: 'Practical hydration markers: pale yellow urine (not clear), minimal body weight change pre/post training, and monitoring thirst throughout the day.' },
    { type: 'multiple_choice', question: 'What are electrolytes and why do they matter for performance?', options: ['They are not important', 'Minerals (sodium, potassium, magnesium) that conduct electrical impulses for muscle contraction and fluid balance', 'A type of drink brand', 'Only matter in extreme heat'], correctAnswer: 1, explanation: 'Electrolytes enable muscle contraction, nerve signalling, and fluid balance — losses through sweat must be replaced during prolonged or intense exercise.' },
    { type: 'multiple_choice', question: 'How much performance is lost with 2% dehydration?', options: ['None', 'Endurance performance can decrease by up to 10–20% and cognitive function is impaired', '1% loss', '50% performance loss'], correctAnswer: 1, explanation: 'Even 2% body mass loss from dehydration significantly impairs endurance performance (10–20% decrease), thermoregulation, and cognitive function.' },
  
  
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Daily weight can fluctuate by how much?', options: ['5–10kg', '0.1kg', '20kg', '1–3kg'], correctAnswer: 3, explanation: 'Daily fluctuations of 1–3kg are normal from water, glycogen, and gut contents.' },
    { type: 'multiple_choice', question: 'Which body composition method is considered the practical gold standard?', options: ['BMI', 'DEXA scan', 'BIA scales', 'Tape measure'], correctAnswer: 1, explanation: 'DEXA scans differentiate bone, lean mass, and fat mass with approximately 1–2% accuracy.' },
    { type: 'multiple_choice', question: 'At what waist circumference are men at increased metabolic health risk?', options: ['80cm', '110cm', '120cm', '94cm'], correctAnswer: 3, explanation: 'Men above 94cm waist circumference are at increased metabolic health risk.' },
    { type: 'multiple_choice', question: 'What is the most practical tool for tracking visual body composition changes?', options: ['Guessing', 'BMI calculator', 'Daily scale weight', 'Monthly progress photos under consistent conditions'], correctAnswer: 3, explanation: 'Monthly progress photos with consistent lighting, time, and clothing reveal changes numbers often miss.' },
    { type: 'multiple_choice', question: 'What does it mean if weight is stable but waist is decreasing?', options: ['You need to eat less', 'The tape measure is wrong', 'No progress is being made', 'You are likely recomposing — gaining muscle while losing fat'], correctAnswer: 3, explanation: 'Stable weight with decreasing waist indicates body recomposition — simultaneous muscle gain and fat loss.' },
    { type: 'multiple_choice', question: 'How often should progress photos be taken?', options: ['Yearly', 'Never', 'Monthly', 'Daily'], correctAnswer: 2, explanation: 'Monthly progress photos under consistent conditions provide the best visual tracking data.' },
    { type: 'multiple_choice', question: 'Why is body weight alone a poor measure of progress?', options: ['It is a perfect measure', 'Weight fluctuates with water, glycogen, food volume, and hormones — it does not distinguish fat from muscle', 'It is the only measure that matters', 'Weight never fluctuates'], correctAnswer: 1, explanation: 'Body weight can fluctuate 1–3kg daily from water, glycogen, food volume, and hormonal cycles — these mask actual fat/muscle changes.' },
    { type: 'multiple_choice', question: 'What combination of metrics gives the most accurate picture of body composition changes?', options: ['Weight only', 'Weight trends + measurements + photos + performance metrics — no single measure is sufficient', 'BMI only', 'Callipers only'], correctAnswer: 1, explanation: 'Multiple metrics combined (weekly weight trends, waist/hip measurements, progress photos, strength changes) provide a reliable picture that no single measure can.' },
    { type: 'multiple_choice', question: 'What is the limitation of BMI?', options: ['No limitations', 'It does not distinguish between fat and muscle mass — muscular individuals are classified as "overweight"', 'It is too accurate', 'It is only for children'], correctAnswer: 1, explanation: 'BMI (weight/height²) cannot distinguish body composition — a muscular athlete and an obese sedentary person may have the same BMI.' },
    { type: 'multiple_choice', question: 'Why are progress photos valuable alongside objective measurements?', options: ['They are not useful', 'Visual changes often precede scale changes — photos capture body composition shifts that weight and measurements can miss', 'Only for social media', 'They are unreliable'], correctAnswer: 1, explanation: 'Progress photos (consistent lighting, angles, timing) capture visual changes that often precede scale movement — particularly during body recomposition phases.' },
  
  
  ]),
  cq(3, 7, [
    { type: 'multiple_choice', question: 'What is the most important rule of competition nutrition?', options: ['Eat as much as possible', 'Try new supplements for an edge', 'Do not try anything new on competition day', 'Skip breakfast to stay light'], correctAnswer: 2, explanation: 'Every food, drink, supplement, and timing strategy should be tested multiple times in training before competition day.' },
    { type: 'multiple_choice', question: 'What should the pre-competition meal (3–4 hours before) consist of?', options: ['High fat, high fibre', '1–2g/kg carbohydrate, moderate protein, low fat, low fibre', 'Nothing — compete fasted', 'As much protein as possible'], correctAnswer: 1, explanation: 'A moderate meal of 1–2g/kg carbs, 0.3g/kg protein, low fat, and low fibre provides energy without GI distress.' },
    { type: 'multiple_choice', question: 'How much water should you aim to drink per hour of flight?', options: ['50ml', '100ml', '250ml', '1 litre'], correctAnswer: 2, explanation: 'Air travel is dehydrating — aim for 250ml of water per hour of flight to maintain hydration.' },
    { type: 'multiple_choice', question: 'What is the recommended caffeine dose for competition performance?', options: ['1mg/kg 2 hours before', '3–6mg/kg 30–60 minutes before (only if tested in training)', '10mg/kg on competition morning', 'As much as possible'], correctAnswer: 1, explanation: '3–6mg/kg body weight 30–60 minutes before competition — but only if previously tested and tolerated in training.' },
    { type: 'multiple_choice', question: 'What approach should travel nutrition take?', options: ['Perfect macro tracking at all times', 'Damage limitation — maintaining adequate protein, hydration, and energy covers 80%', 'Fasting during travel', 'Only eating at restaurants'], correctAnswer: 1, explanation: 'Travel nutrition is about damage limitation, not perfection — adequate protein, hydration, and total energy cover 80% of the equation.' },
    { type: 'multiple_choice', question: 'What is the number one rule of competition nutrition?', options: ['Try new foods', 'Never try anything new on competition day — practise your nutrition strategy in training', 'Eat as much as possible', 'Fast before competing'], correctAnswer: 1, explanation: 'The golden rule: nothing new on race/competition day. Every food, drink, and supplement should be tested in training to avoid GI issues or unexpected reactions.' },
    { type: 'multiple_choice', question: 'How should you manage nutrition when travelling across time zones?', options: ['Eat whatever is available', 'Gradually shift meal times toward the destination time zone, stay hydrated, and bring familiar snacks', 'Fast during travel', 'Only eat local food immediately'], correctAnswer: 1, explanation: 'Shift meal times gradually, prioritise hydration (dehydration worsens jet lag), and bring familiar snacks to maintain routine and avoid GI disruption.' },
    { type: 'multiple_choice', question: 'What is the primary nutritional concern during travel?', options: ['Protein intake', 'Dehydration — air travel, unfamiliar environments, and disrupted routines all increase dehydration risk', 'Calorie surplus', 'Vitamin deficiency'], correctAnswer: 1, explanation: 'Pressurised aircraft cabins, disrupted routines, and unfamiliar climates all increase dehydration risk — proactive hydration is the primary travel nutrition priority.' },
    { type: 'multiple_choice', question: 'What should a pre-competition meal look like?', options: ['A huge feast', 'Familiar, easily digested foods — high carbohydrate, moderate protein, low fat and fibre, eaten 3–4 hours before', 'High fat for energy', 'Nothing — compete fasted'], correctAnswer: 1, explanation: 'Pre-competition meals should be familiar, carb-dominant, moderate protein, low in fat and fibre (to reduce GI risk), eaten 3–4 hours before for full digestion.' },
    { type: 'multiple_choice', question: 'What is the role of post-competition nutrition?', options: ['Not important', 'Rapid glycogen replenishment, protein for repair, rehydration, and supporting immune function during the open window', 'Only celebrate with food', 'Wait until the next day'], correctAnswer: 1, explanation: 'Post-competition: rapid carbs for glycogen (1–1.2g/kg/hr for 4 hours), 20–40g protein for repair, fluid with electrolytes, and immune-supporting nutrients.' },
  
  
  ]),
  cq(3, 8, [
    { type: 'multiple_choice', question: 'Why do static nutrition plans fail?', options: ['They are too complicated', 'They do not account for changing training demands across phases', 'They include too much variety', 'Static plans always work'], correctAnswer: 1, explanation: 'Training is periodised with changing demands — nutrition should follow the same logic rather than staying the same regardless of phase.' },
    { type: 'multiple_choice', question: 'What is the recommended energy surplus during a hypertrophy phase?', options: ['No surplus needed', '200–300 kcal above TDEE', '1000 kcal above TDEE', '500 kcal deficit'], correctAnswer: 1, explanation: 'A slight surplus with protein at 1.8–2.2g/kg and adequate carbohydrate supports muscle growth without excessive fat gain.' },
    { type: 'multiple_choice', question: 'During a fat loss phase, what should protein intake be?', options: ['Reduced to save calories', 'Increased to 2.0–2.4g/kg to preserve lean mass', 'Kept the same as maintenance', 'Replaced with supplements'], correctAnswer: 1, explanation: 'During energy deficits, protein should increase to 2.0–2.4g/kg to protect lean mass against catabolism.' },
    { type: 'multiple_choice', question: 'Which macronutrient should be allocated first in any phase?', options: ['Fat', 'Carbohydrate', 'Protein — always adequate', 'Alcohol'], correctAnswer: 2, explanation: 'Protein is allocated first (always adequate), then carbohydrate (matched to training demand), then fat (fills remaining above minimum).' },
    { type: 'multiple_choice', question: 'How should you transition between nutrition phases?', options: ['Jump abruptly to new targets', 'Transition by 200–300 kcal per week to allow metabolic adjustment', 'Fast for a week between phases', 'No transition needed'], correctAnswer: 1, explanation: 'Gradual transitions of 200–300 kcal per week allow metabolic adjustment and prevent the negative effects of abrupt changes.' },
    { type: 'multiple_choice', question: 'How often should a periodised nutrition plan be reassessed?', options: ['Never', 'Every 2–4 weeks using body composition, performance, and adherence data', 'Only at the end of the programme', 'Daily'], correctAnswer: 1, explanation: 'Reassess every 2–4 weeks using body composition data, training performance, energy levels, and adherence to make informed adjustments.' },
    { type: 'multiple_choice', question: 'What are the main phases of nutrition periodisation?', options: ['Only bulking and cutting', 'Building/surplus, maintenance, fat loss/deficit, and recovery/deload — aligned with training phases', 'No phases needed', 'Only competition nutrition'], correctAnswer: 1, explanation: 'Nutrition periodisation aligns intake with training: surplus phases for building, maintenance for consolidation, deficit phases for leaning, and recovery periods.' },
    { type: 'multiple_choice', question: 'Why should fat loss phases have a defined end point?', options: ['They should not — diet forever', 'Indefinite dieting causes metabolic adaptation, hormonal disruption, and psychological fatigue', 'End points reduce motivation', 'Only for competitors'], correctAnswer: 1, explanation: 'Open-ended dieting drives progressive metabolic adaptation and psychological fatigue — defined phases (8–16 weeks) with maintenance periods produce better long-term results.' },
    { type: 'multiple_choice', question: 'What is reverse dieting?', options: ['Eating backwards', 'Gradually increasing calories after a fat loss phase to restore metabolic rate while minimising fat regain', 'Fasting after eating', 'Eating in reverse meal order'], correctAnswer: 1, explanation: 'Reverse dieting (increasing calories by 50–100 kcal/week) gradually restores metabolic rate, hormone levels, and energy while minimising the fat regain of sudden increases.' },
    { type: 'multiple_choice', question: 'What is a maintenance phase and why is it important?', options: ['Eating the same forever', 'A period at estimated maintenance calories between deficit/surplus phases to restore metabolic and hormonal function', 'A phase of no training', 'Only for advanced athletes'], correctAnswer: 1, explanation: 'Maintenance phases (4–12 weeks) between deficit or surplus phases allow hormonal recovery, metabolic restoration, and psychological reset — improving long-term outcomes.' },
  
  
  ]),
];

// Unit 4 chapter quizzes
