import type { UnitAssessment } from '../types';

export const nutritionL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Sports Nutrition & Performance Fuelling',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What protein intake is recommended during a fat loss phase?', options: ['2.0–2.4g per kg', '0.8g per kg', '4g per kg', '1.2g per kg'], correctAnswer: 0, explanation: 'Higher protein (2.0–2.4g/kg) during a deficit preserves muscle mass and increases satiety.' },
    { type: 'multiple_choice', question: 'What carbohydrate loading protocol is currently recommended?', options: ['Normal eating with extra pasta the night before', 'Zero carbs for a week then unlimited carbs', 'Depletion for 3 days then loading for 3 days', '8–12g/kg carbohydrate for 36–48 hours with tapering training'], correctAnswer: 3, explanation: 'The modern simplified protocol of 8–12g/kg for 36–48 hours achieves comparable glycogen levels without depletion.' },
    { type: 'multiple_choice', question: 'For events over 2.5 hours, what is the recommended intra-event carbohydrate intake?', options: ['30g per hour', 'Up to 90g per hour using glucose-fructose combinations', '10g per hour', '150g per hour'], correctAnswer: 1, explanation: 'Up to 90g/hour using multiple transportable carbohydrates (2:1 glucose:fructose) for ultra-endurance events.' },
    { type: 'multiple_choice', question: 'What caloric surplus is appropriate for a lean bulk in trained individuals?', options: ['1000+ calories', '50–100 calories', 'No surplus needed', '200–400 calories'], correctAnswer: 3, explanation: 'A modest 200–400 calorie surplus provides sufficient energy for muscle growth with minimal fat gain.' },
    { type: 'multiple_choice', question: 'At what level of dehydration does measurable performance decline typically begin?', options: ['10% body weight', '2% body weight', '5% body weight', '0.5% body weight'], correctAnswer: 1, explanation: 'Dehydration of 2% or more of body weight consistently impairs both physical and cognitive performance.' },
    { type: 'scenario', scenario: 'An athlete has been dieting for 14 weeks. They report persistent fatigue, strength loss, poor sleep, and extreme hunger.', question: 'What is the most appropriate recommendation?', options: ['Add more cardio', 'Plan a 1–2 week diet break at maintenance calories', 'Reduce calories further', 'Switch to a keto diet'], correctAnswer: 1, explanation: 'After 14 weeks, these symptoms indicate metabolic adaptation. A diet break at maintenance is the appropriate response.' },
    { type: 'multiple_choice', question: 'Which body composition method is considered the practical gold standard?', options: ['Bioelectrical impedance (BIA) scales', 'BMI calculation', 'DEXA scan', 'Waist-to-hip ratio'], correctAnswer: 2, explanation: 'DEXA scans use low-dose X-rays to differentiate bone, lean mass, and fat mass with approximately 1–2% accuracy.' },
    { type: 'multiple_choice', question: 'What is the primary electrolyte of concern during prolonged endurance exercise?', options: ['Calcium', 'Potassium', 'Magnesium', 'Sodium'], correctAnswer: 3, explanation: 'Sodium is the primary electrolyte lost in sweat and its depletion can cause dangerous hyponatraemia.' },
    { type: 'multiple_choice', question: 'What is the recommended fat loss rate for non-obese individuals?', options: ['3kg per week', '0.05kg per week', '1–2kg per week', '0.25–0.5kg per week'], correctAnswer: 3, explanation: 'A rate of 0.25–0.5kg per week minimises muscle loss and is sustainable.' },
    { type: 'multiple_choice', question: 'Why is body weight alone an unreliable measure of progress?', options: ['Scales are inaccurate', 'Weight never changes', 'Daily fluctuations of 1–3kg from water, glycogen, and gut contents mask true changes', 'Muscle weighs more than fat'], correctAnswer: 2, explanation: 'Daily weight fluctuations from non-fat factors obscure the actual trend in body composition.' },
    { type: 'multiple_choice', question: 'What is hyponatraemia?', options: ['High blood sugar', 'High blood sodium', 'Dangerously low blood sodium from over-drinking plain water', 'Dehydration'], correctAnswer: 2, explanation: 'Hyponatraemia is dangerously low blood sodium, usually caused by over-drinking water without sodium replacement.' },
    { type: 'multiple_choice', question: 'How much glycogen does a high-volume training session typically deplete?', options: ['80–100%', '0%', '5–10%', '25–40%'], correctAnswer: 3, explanation: 'A typical high-volume session (20–25 working sets) depletes approximately 25–40% of muscle glycogen.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "Pre-workout nutrition for resistance training should ideally include:", options: ['Nothing \u2014 train fasted for best results', 'A high-fat meal immediately before training', 'Only water', 'A combination of protein and carbohydrate 1-3 hours before training'], correctAnswer: 3, explanation: 'Pre-workout nutrition combining protein and carbohydrate (1-3 hours before) provides amino acids for muscle protection and glycogen for energy \u2014 optimising training performance.' },
    { type: 'multiple_choice', question: "For fat loss, the most important factor is:", options: ['The specific diet type (keto, paleo, etc.)', 'A sustained calorie deficit through any dietary approach the person can maintain', 'Eliminating carbohydrates completely', 'Eating only between 12pm and 8pm'], correctAnswer: 1, explanation: 'Meta-analyses consistently show that total calorie deficit \u2014 not specific diet type \u2014 determines fat loss. The best diet is one the individual can sustain long-term.' },
    { type: 'multiple_choice', question: "During endurance events lasting over 90 minutes, athletes should:", options: ['Avoid all food and drink', 'Eat a large meal at the halfway point', 'Only drink water', 'Consume 30-60g carbohydrate per hour alongside fluids'], correctAnswer: 3, explanation: 'For endurance events >90 minutes, consuming 30-60g/hour of carbohydrate (gels, drinks, real food) maintains blood glucose, delays fatigue, and improves performance.' },
    { type: 'multiple_choice', question: "Hyponatremia during endurance events is caused by:", options: ["Not drinking enough water", "Consuming too much salt", "Drinking excessive water without electrolyte replacement, diluting blood sodium", "Eating too much during the race"], correctAnswer: 2, explanation: "Hyponatremia occurs when excessive fluid intake dilutes blood sodium levels. It's a serious condition \u2014 adding electrolytes to fluid and not over-drinking are preventive measures." },
    { type: 'multiple_choice', question: "For muscle gain, a caloric surplus of approximately how much above maintenance is recommended?", options: ['No surplus is needed', '1,000-2,000 kcal per day', '100-300 kcal per day', '500 kcal per day from fat only'], correctAnswer: 2, explanation: 'A moderate surplus of 200-500 kcal/day (sometimes cited as 100-300 for minimal fat gain) supports muscle growth without excessive fat accumulation. Larger surpluses increase fat gain disproportionately.' },
    { type: 'multiple_choice', question: "Body composition can be assessed using:", options: ['Methods like skinfold calipers, bioelectrical impedance, DEXA scans, and circumference measurements', 'Only BMI', 'The bathroom scale alone', 'Only visual assessment'], correctAnswer: 0, explanation: 'Multiple methods exist: skinfold calipers (practical), BIA (convenient), DEXA (gold standard), waist circumference, and photos. Each has pros/cons \u2014 using multiple gives the best picture.' },
    { type: 'multiple_choice', question: "Hydration during exercise should be guided by:", options: ['Drinking as much as possible', 'Fixed amounts regardless of conditions', 'Thirst, body weight changes, and urine colour \u2014 aiming to replace 80% of sweat losses', 'Only post-exercise rehydration'], correctAnswer: 2, explanation: 'Hydration should be individualised: drink to thirst, monitor body weight changes (>2% loss = underhydrating), and check urine colour. Aim to replace ~80% of sweat losses.' },
    { type: 'multiple_choice', question: "Post-exercise nutrition for recovery should ideally include:", options: ['Nothing for at least 4 hours', 'Only protein, no carbohydrate', 'Protein (20-40g) and carbohydrate within 1-2 hours of training', 'A high-fat meal to restore energy'], correctAnswer: 2, explanation: 'Post-exercise recovery is optimised by combining protein (for muscle repair, 20-40g) with carbohydrate (for glycogen replenishment) within the first 1-2 hours after training.' },

  ],
};
