import type { UnitAssessment } from '../types';

export const nutritionL3Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Micronutrients, Supplementation & Special Populations',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'Why do fat-soluble vitamins carry a risk of toxicity?', options: ['They interact with medications', 'They require large doses to be effective', 'They are absorbed quickly', 'They are stored in the body and can accumulate'], correctAnswer: 3, explanation: 'Fat-soluble vitamins are stored in liver and adipose tissue, so excess accumulates rather than being excreted.' },
    { type: 'multiple_choice', question: 'What daily vitamin D supplementation does Public Health England recommend for UK adults in autumn and winter?', options: ['5 micrograms', '100 micrograms', '10 micrograms (400 IU)', '50 micrograms'], correctAnswer: 2, explanation: 'PHE recommends 10 micrograms (400 IU) daily during autumn and winter.' },
    { type: 'multiple_choice', question: 'Which supplement has the strongest evidence base for improving strength and power?', options: ['Testosterone boosters', 'Creatine monohydrate', 'Glutamine', 'BCAAs'], correctAnswer: 1, explanation: 'Creatine monohydrate is the most researched and consistently supported sports supplement.' },
    { type: 'multiple_choice', question: 'What is the effective caffeine dose for performance enhancement?', options: ['3–6mg per kg body weight', '20mg per kg body weight', '1mg per kg body weight', '10–15mg per kg body weight'], correctAnswer: 0, explanation: '3–6mg/kg consumed 30–60 minutes before training is the evidence-based dose.' },
    { type: 'multiple_choice', question: 'Which nutrient must all vegans supplement without exception?', options: ['Iron', 'Vitamin C', 'Calcium', 'Vitamin B12'], correctAnswer: 3, explanation: 'No reliable plant source of B12 exists. Deficiency causes irreversible nerve damage.' },
    { type: 'multiple_choice', question: 'How much additional energy per day is recommended during the third trimester of pregnancy?', options: ['Approximately 500 calories', '0 extra calories', 'Double normal intake', 'Approximately 200 calories'], correctAnswer: 3, explanation: 'Only approximately 200 additional calories per day are recommended, and only in the third trimester.' },
    { type: 'multiple_choice', question: 'What daily protein intake may older adults need to combat sarcopenia?', options: ['1.2–1.6g per kg', '0.5g per kg', '0.8g per kg', '3g per kg'], correctAnswer: 0, explanation: 'Older adults may need 1.2–1.6g/kg to overcome anabolic resistance and maintain muscle mass.' },
    { type: 'scenario', scenario: 'A vegan client reports fatigue, tingling in their hands, and difficulty concentrating. They do not take any supplements.', question: 'Which deficiency is most likely?', options: ['Zinc', 'Iron', 'Vitamin D', 'Vitamin B12'], correctAnswer: 3, explanation: 'Neurological symptoms (tingling, concentration issues) combined with fatigue in a non-supplementing vegan strongly suggest B12 deficiency.' },
    { type: 'multiple_choice', question: 'In the UK, who is legally qualified to provide medical nutrition therapy?', options: ['Registered Dietitians (HCPC regulated)', 'Nutritional therapists', 'Personal trainers with a nutrition certificate', 'Anyone with a food hygiene certificate'], correctAnswer: 0, explanation: 'Only Registered Dietitians regulated by the HCPC are qualified for medical nutrition therapy in the UK.' },
    { type: 'multiple_choice', question: 'Which form of iron is more bioavailable?', options: ['Supplemental iron oxide', 'Non-haem iron from plants', 'Haem iron from animal sources', 'Iron from fortified cereals'], correctAnswer: 2, explanation: 'Haem iron from animal sources is absorbed approximately 2–3 times more efficiently than non-haem iron.' },
    { type: 'multiple_choice', question: 'What is the recommended folic acid supplementation during early pregnancy?', options: ['100 micrograms', '5000 micrograms', '400 micrograms daily', '1000 micrograms'], correctAnswer: 2, explanation: '400 micrograms daily from trying to conceive until 12 weeks of pregnancy.' },
    { type: 'multiple_choice', question: 'Plant-based ALA converts to EPA/DHA at approximately what rate?', options: ['0%', '25–30%', '5–10%', '50–60%'], correctAnswer: 2, explanation: 'ALA conversion to EPA/DHA is very poor — approximately 5–10% — which is why algae-based supplements are recommended for vegans.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "Fat-soluble vitamins (A, D, E, K) differ from water-soluble vitamins because:", options: ['They can be stored in body fat and the liver, creating risk of toxicity at high doses', 'They are less important', 'They need to be consumed every hour', 'They are only found in supplements'], correctAnswer: 0, explanation: 'Fat-soluble vitamins accumulate in body fat and liver \u2014 excess intake (especially A and D) can reach toxic levels, unlike water-soluble vitamins which are mostly excreted.' },
    { type: 'multiple_choice', question: "Creatine monohydrate is considered:", options: ['Dangerous and should be avoided', 'A banned substance in sport', 'Only useful for endurance athletes', 'One of the most well-researched and effective supplements for strength and power'], correctAnswer: 3, explanation: 'Creatine monohydrate has decades of research supporting its safety and effectiveness for increasing strength, power output, and lean mass. It is not banned in any sport.' },
    { type: 'multiple_choice', question: "Vitamin B12 is critical because deficiency can cause:", options: ['Megaloblastic anaemia, neurological damage, and fatigue', 'Stronger bones', 'Weight gain', 'Improved athletic performance'], correctAnswer: 0, explanation: 'B12 deficiency causes megaloblastic anaemia (enlarged red blood cells), neurological symptoms (numbness, cognitive issues), and fatigue. Vegans are at particular risk.' },
    { type: 'multiple_choice', question: "Evidence-based supplementation means:", options: ['Taking every supplement available', 'Replacing food with supplements', 'Following influencer recommendations', 'Using supplements supported by robust scientific research for specific, identified needs'], correctAnswer: 3, explanation: 'Evidence-based supplementation involves identifying specific needs (through diet analysis or blood tests) and using supplements with strong research backing \u2014 not blanket supplementation.' },
    { type: 'multiple_choice', question: "Clinical nutrition awareness for fitness professionals means:", options: ['Diagnosing and treating eating disorders', 'Prescribing therapeutic diets', 'Recognising signs that require referral to qualified healthcare professionals', 'Replacing medical nutrition therapy'], correctAnswer: 2, explanation: 'Fitness professionals must recognise red flags (disordered eating, suspected deficiencies, medical conditions) and refer to appropriate healthcare professionals \u2014 not diagnose or treat.' },
    { type: 'multiple_choice', question: "Iron absorption from plant sources is enhanced by:", options: ['Consuming tea or coffee with meals', 'Cooking in aluminium pans', 'Taking calcium supplements at the same time', 'Combining plant iron sources with vitamin C'], correctAnswer: 3, explanation: 'Non-haem iron (plant sources) is less bioavailable than haem iron (animal sources). Vitamin C significantly enhances non-haem iron absorption when consumed together.' },
    { type: 'multiple_choice', question: "Omega-3 fatty acids EPA and DHA are important for:", options: ['Increasing fat storage', 'Replacing protein in the diet', 'Only fish flavour', 'Reducing inflammation, supporting brain health, and cardiovascular function'], correctAnswer: 3, explanation: 'EPA and DHA (found in oily fish, algae supplements) have anti-inflammatory properties and support cardiovascular health, brain function, and mood regulation.' },
    { type: 'multiple_choice', question: "Nutrition for older adults should prioritise:", options: ['Calorie restriction to maintain low body weight', 'Eliminating all fat from the diet', 'Adequate protein (1.0-1.2g/kg), vitamin D, calcium, and B12', 'Only liquid nutrition'], correctAnswer: 2, explanation: 'Older adults need sufficient protein (to prevent sarcopenia), vitamin D (reduced synthesis), calcium (bone density), and B12 (reduced absorption) \u2014 not calorie restriction.' },

  ],
};
