import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const nutritionL3Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'Why can fat-soluble vitamins cause toxicity?', options: ['They are excreted quickly', 'They evaporate', 'They are water-based', 'They accumulate in the body'], correctAnswer: 3, explanation: 'Fat-soluble vitamins are stored in liver and adipose tissue, accumulating over time.' },
    { type: 'multiple_choice', question: 'Between which months is UVB insufficient for vitamin D production in the UK?', options: ['June to August', 'January to February', 'October to March', 'All year'], correctAnswer: 2, explanation: 'From October to March, the UK sun is too low for adequate UVB exposure.' },
    { type: 'multiple_choice', question: 'Why should pregnant women avoid liver?', options: ['Very high vitamin A (retinol) which can cause birth defects', 'It is too high in iron', 'It tastes bad', 'It contains bacteria'], correctAnswer: 0, explanation: 'Liver is very high in preformed retinol, which in excess can cause birth defects.' },
    { type: 'multiple_choice', question: 'What role does vitamin K play?', options: ['Fat storage', 'Blood clotting and bone metabolism', 'Energy production', 'Muscle growth'], correctAnswer: 1, explanation: 'Vitamin K is essential for blood clotting (K1) and bone metabolism (K2).' },
    { type: 'multiple_choice', question: 'Which groups are at higher risk of vitamin D deficiency?', options: ['People who spend a lot of time outdoors', 'People with darker skin, those who cover their skin, indoor workers, and older adults', 'Only children', 'Only athletes'], correctAnswer: 1, explanation: 'Darker skin, covered skin, limited outdoor time, and older age all increase risk.' },
    { type: 'multiple_choice', question: 'What does vitamin E primarily function as?', options: ['A coenzyme in glycolysis', 'A structural protein', 'A hormone', 'An antioxidant'], correctAnswer: 3, explanation: 'Vitamin E acts as an antioxidant, protecting cell membranes from oxidative damage.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What do B vitamins primarily support?', options: ['Blood clotting', 'Energy metabolism as coenzymes', 'Fat storage', 'Bone growth'], correctAnswer: 1, explanation: 'B vitamins act as coenzymes in pathways that convert macronutrients into ATP.' },
    { type: 'multiple_choice', question: 'Why is B12 a particular concern for vegans?', options: ['Plants contain too much B12', 'It is expensive', 'It causes weight gain', 'It is found almost exclusively in animal products'], correctAnswer: 3, explanation: 'B12 is found almost exclusively in animal products; all vegans must supplement.' },
    { type: 'multiple_choice', question: 'What improves non-haem iron absorption?', options: ['Phytates', 'Vitamin C', 'Calcium', 'Tea and coffee'], correctAnswer: 1, explanation: 'Vitamin C significantly improves absorption of non-haem iron from plant sources.' },
    { type: 'multiple_choice', question: 'Magnesium is involved in how many enzymatic reactions?', options: ['10', '50', 'Over 1000', 'Over 300'], correctAnswer: 3, explanation: 'Magnesium is involved in over 300 enzymatic reactions in the body.' },
    { type: 'multiple_choice', question: 'Which mineral supports testosterone production?', options: ['Calcium', 'Sodium', 'Iron', 'Zinc'], correctAnswer: 3, explanation: 'Zinc supports immune function, protein synthesis, and testosterone production.' },
    { type: 'multiple_choice', question: 'What is the most common nutritional deficiency worldwide?', options: ['Vitamin C', 'Vitamin D', 'Calcium', 'Iron'], correctAnswer: 3, explanation: 'Iron deficiency is the most common nutritional deficiency worldwide.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What is the recommended daily creatine dose?', options: ['50g', '20g', '3–5g', '0.5g'], correctAnswer: 2, explanation: 'The standard maintenance dose is 3–5g per day, every day.' },
    { type: 'multiple_choice', question: 'Which supplement tier do BCAAs fall into for people with adequate protein intake?', options: ['Not categorised', 'Tier 1 — Strong evidence', 'Tier 3 — Limited/no evidence', 'Tier 2 — Moderate evidence'], correctAnswer: 2, explanation: 'BCAAs are redundant if total protein intake is adequate — Tier 3.' },
    { type: 'multiple_choice', question: 'How does creatine improve performance?', options: ['By reducing appetite', 'By burning fat', 'By increasing testosterone', 'By increasing phosphocreatine stores for rapid ATP regeneration'], correctAnswer: 3, explanation: 'Creatine increases phosphocreatine stores, improving capacity for short, intense efforts.' },
    { type: 'multiple_choice', question: 'When should caffeine be consumed for performance benefits?', options: ['During training', '30–60 minutes before training', '3 hours after training', 'Before bed'], correctAnswer: 1, explanation: 'Caffeine is most effective when consumed 30–60 minutes before training.' },
    { type: 'multiple_choice', question: 'What is a red flag in supplement marketing?', options: ['Proprietary blends hiding individual ingredient doses', 'Third-party testing certification', 'Published peer-reviewed research', 'Transparent ingredient dosing'], correctAnswer: 0, explanation: 'Proprietary blends that hide doses are a warning sign of marketing-driven products.' },
    { type: 'multiple_choice', question: 'Does creatine cause kidney damage in healthy individuals?', options: ['Only in women', 'Only at high doses', 'Yes, always', 'No — extensively studied for 30+ years with no evidence of harm'], correctAnswer: 3, explanation: 'Decades of research show no kidney damage from creatine in healthy individuals.' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'How many extra calories per day are needed during the third trimester?', options: ['Approximately 200', '0', 'Approximately 500', '1000'], correctAnswer: 0, explanation: 'Only approximately 200 additional calories per day are recommended in the third trimester.' },
    { type: 'multiple_choice', question: 'When should folic acid supplementation begin?', options: ['Only in the third trimester', 'From trying to conceive until 12 weeks', 'At birth of the baby', 'After delivery'], correctAnswer: 1, explanation: '400 micrograms daily from the point of trying to conceive until 12 weeks of pregnancy.' },
    { type: 'multiple_choice', question: 'What protein intake may older adults need to combat sarcopenia?', options: ['1.2–1.6g/kg', '3g/kg', '0.8g/kg', '0.5g/kg'], correctAnswer: 0, explanation: 'Older adults may need 1.2–1.6g/kg daily to maintain muscle mass against anabolic resistance.' },
    { type: 'multiple_choice', question: 'What is sarcopenia?', options: ['Fat gain in older adults', 'Vitamin deficiency', 'Bone loss', 'Age-related loss of muscle mass and function'], correctAnswer: 3, explanation: 'Sarcopenia is the progressive loss of muscle mass and function associated with ageing.' },
    { type: 'multiple_choice', question: 'What is the UK advice on alcohol during pregnancy?', options: ['Complete abstinence', 'No more than 14 units', '1 glass of wine daily', 'Up to 2 units per week'], correctAnswer: 0, explanation: 'UK Chief Medical Officers advise complete abstinence as no safe level has been established.' },
    { type: 'multiple_choice', question: 'Why are older adults at higher risk of dehydration?', options: ['Higher activity levels', 'They drink too much tea', 'Reduced thirst sensation', 'They sweat more'], correctAnswer: 2, explanation: 'Ageing reduces thirst sensation, meaning older adults may not drink enough.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What must all vegans supplement?', options: ['Calcium', 'Vitamin B12', 'Vitamin C', 'Iron'], correctAnswer: 1, explanation: 'No reliable plant source of B12 exists — supplementation is non-negotiable for vegans.' },
    { type: 'multiple_choice', question: 'Do complementary plant proteins need to be eaten at the same meal?', options: ['Only post-training', 'No — the body pools amino acids over 24 hours', 'Only at breakfast', 'Yes, always'], correctAnswer: 1, explanation: 'Amino acids are pooled over the day; variety across meals is sufficient.' },
    { type: 'multiple_choice', question: 'How many major allergens must be declared under UK food law?', options: ['14', '20', '5', '8'], correctAnswer: 0, explanation: 'UK food law requires declaration of 14 major allergens.' },
    { type: 'multiple_choice', question: 'What improves plant-based zinc absorption?', options: ['Soaking, sprouting, and fermenting', 'Eating raw only', 'Taking calcium supplements', 'Consuming with tea'], correctAnswer: 0, explanation: 'Soaking, sprouting, and fermenting reduce phytates that inhibit zinc absorption.' },
    { type: 'multiple_choice', question: 'What is coeliac disease?', options: ['Lactose intolerance', 'A food preference', 'A type of food poisoning', 'An autoimmune condition triggered by gluten'], correctAnswer: 3, explanation: 'Coeliac disease is an autoimmune condition requiring lifelong strict gluten avoidance.' },
    { type: 'multiple_choice', question: 'Why are algae-based omega-3 supplements recommended for vegans?', options: ['They are cheaper', 'Fish oil causes allergies', 'Algae taste better', 'Plant ALA converts very poorly to EPA/DHA'], correctAnswer: 3, explanation: 'ALA from plants converts to EPA/DHA at only 5–10%, making algae-based supplements the reliable alternative.' },
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'Who can provide medical nutrition therapy in the UK?', options: ['Nutrition coaches', 'Any personal trainer', 'Registered Dietitians (HCPC)', 'Health food shop staff'], correctAnswer: 2, explanation: 'Only HCPC-regulated Registered Dietitians can provide medical nutrition therapy.' },
    { type: 'multiple_choice', question: 'What dietary pattern has the strongest evidence for cardiovascular health?', options: ['Carnivore diet', 'Mediterranean diet', 'Raw food diet', 'Juice cleanse'], correctAnswer: 1, explanation: 'Mediterranean and DASH dietary patterns have the strongest evidence for cardiovascular health.' },
    { type: 'multiple_choice', question: 'What percentage of body weight loss significantly reduces type 2 diabetes risk?', options: ['15%', '1%', '5–7%', '25%'], correctAnswer: 2, explanation: 'The UK Diabetes Prevention Programme shows 5–7% weight loss significantly reduces progression risk.' },
    { type: 'multiple_choice', question: 'What should you do if you suspect someone has an eating disorder?', options: ['Ignore it', 'Express concern and encourage them to speak with their GP', 'Put them on a meal plan', 'Diagnose them yourself'], correctAnswer: 1, explanation: 'Compassionate concern and referral to a GP is the appropriate response.' },
    { type: 'multiple_choice', question: 'What is the title of the UK eating disorder charity?', options: ['Beat', 'Samaritans', 'CALM', 'Mind'], correctAnswer: 0, explanation: "Beat (beateatingdisorders.org.uk) is the UK\'s leading eating disorder charity." },
    { type: 'multiple_choice', question: 'Is the title "nutritionist" legally protected in the UK?', options: ['Only for NHS staff', 'Only in Scotland', 'Yes, fully protected', 'No, not in the same way as "dietitian"'], correctAnswer: 3, explanation: 'Unlike \'dietitian," the title "nutritionist" is not legally protected in the UK.' },
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What is the temperature danger zone for bacterial growth?', options: ['0–5°C', '8–63°C', '70–100°C', '100°C+'], correctAnswer: 1, explanation: 'Bacteria multiply rapidly between 8°C and 63°C — minimise the time food spends in this range.' },
    { type: 'multiple_choice', question: 'What internal temperature should poultry be cooked to?', options: ['55°C', '63°C', '75°C', '90°C'], correctAnswer: 2, explanation: 'Poultry should reach 75°C internal temperature to ensure harmful bacteria are destroyed.' },
    { type: 'multiple_choice', question: 'How long can cooked meal-prepped food be safely stored in the refrigerator?', options: ['1 day', '3–4 days', '2 weeks', 'Indefinitely'], correctAnswer: 1, explanation: 'Cooked meal-prepped food should be consumed within 3–4 days when stored properly at or below 5°C, or frozen.' },
    { type: 'multiple_choice', question: 'What is cross-contamination?', options: ['Cooking food too long', 'Transfer of harmful bacteria from one food to another, often via shared surfaces or hands', 'Eating expired food', 'Using too much seasoning'], correctAnswer: 1, explanation: 'Cross-contamination occurs when bacteria transfer between foods via shared chopping boards, hands, or surfaces — especially from raw meat to ready-to-eat foods.' },
    { type: 'multiple_choice', question: 'Where should raw meat be stored in the refrigerator?', options: ['On the top shelf', 'On the lowest shelf to prevent dripping onto other foods', 'Next to ready-to-eat foods', 'Outside the refrigerator'], correctAnswer: 1, explanation: 'Raw meat should be stored on the lowest shelf to prevent juices dripping onto ready-to-eat foods below.' },
    { type: 'multiple_choice', question: 'How many major allergens must be considered when preparing food for others?', options: ['5', '8', '14', '20'], correctAnswer: 2, explanation: 'There are 14 major allergens (including gluten, dairy, nuts, soy, eggs) that must be considered in food preparation.' },
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'What determines how well nutrition works?', options: ['How expensive the food is', 'Your digestive system\'s ability to absorb and utilise nutrients', 'How much you eat', 'The brand of supplements you use'], correctAnswer: 1, explanation: 'You are not what you eat — you are what you absorb. Digestive function determines nutritional effectiveness.' },
    { type: 'multiple_choice', question: 'What is the most evidence-based dietary intervention for IBS?', options: ['High-fibre diet', 'Carnivore diet', 'Low-FODMAP diet under professional guidance', 'Juice cleanse'], correctAnswer: 2, explanation: 'A low-FODMAP diet under professional guidance is the most evidence-based dietary intervention for IBS.' },
    { type: 'multiple_choice', question: 'How quickly do gut cells (enterocytes) replace themselves?', options: ['Every month', 'Every year', 'Every 3–5 days', 'They never replace'], correctAnswer: 2, explanation: 'Gut cells have the fastest turnover rate in the body, replacing themselves every 3–5 days — requiring consistent amino acid supply.' },
    { type: 'multiple_choice', question: 'What is more important for gut health than probiotic supplements?', options: ['Expensive superfoods', 'Prebiotic foods that feed beneficial bacteria', 'Meal replacement shakes', 'Detox teas'], correctAnswer: 1, explanation: 'Prebiotic foods (garlic, onions, leeks, asparagus, bananas, oats) that feed beneficial bacteria are more important than probiotic supplements for most people.' },
    { type: 'multiple_choice', question: 'What is a common cause of exercise-related GI distress?', options: ['Drinking too much water', 'Reduced blood flow to the gut during exercise', 'Cold weather', 'Breathing through the mouth'], correctAnswer: 1, explanation: 'During exercise, blood is redirected to working muscles, reducing gut blood flow and potentially causing GI symptoms.' },
  ]),
];

// Unit 3 chapter quizzes
