import type { UnitAssessment } from '../types';

export const nutritionL3Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Nutrition Psychology, Behaviour Change & Professional Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the difference between hunger and appetite?', options: ['Hunger only occurs when fasting', 'Hunger is physiological; appetite can be triggered by environmental or emotional cues', 'Appetite is physiological; hunger is psychological', 'They are the same thing'], correctAnswer: 1, explanation: 'Hunger is a physiological need for energy; appetite is the desire to eat, influenced by many non-physiological factors.' },
    { type: 'multiple_choice', question: 'Using a smaller plate reduces intake by approximately how much?', options: ['5%', '50%', '10%', '20%'], correctAnswer: 3, explanation: 'Research shows using a 25cm plate instead of a 30cm plate reduces intake by approximately 20%.' },
    { type: 'multiple_choice', question: 'In the Transtheoretical Model, which stage involves actively changing behaviour?', options: ['Action', 'Contemplation', 'Preparation', 'Maintenance'], correctAnswer: 0, explanation: 'The Action stage is when the person is actively implementing new behaviours.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Tracking habits in a journal', 'Attaching a new behaviour to an existing established habit', 'Adding multiple habits at once', 'Replacing all bad habits simultaneously'], correctAnswer: 1, explanation: 'Habit stacking links a new desired behaviour to an existing automatic habit to reduce cognitive effort.' },
    { type: 'multiple_choice', question: 'Which of these is a warning sign of disordered eating?', options: ['Choosing to meal prep on Sundays', 'Intense guilt after eating and preoccupation with food that dominates daily thoughts', 'Enjoying a variety of foods', 'Occasional overeating at celebrations'], correctAnswer: 1, explanation: 'Intense guilt and food preoccupation that dominates daily life are key psychological warning signs.' },
    { type: 'scenario', scenario: 'A friend tells you they skip meals to compensate for "bad eating days" and exercise excessively after eating cake. They seem distressed about food.', question: 'What is the most appropriate response?', options: ['Give them a meal plan', 'Express concern without judgement and encourage them to speak with their GP', 'Ignore it — it is their choice', 'Tell them to stop worrying'], correctAnswer: 1, explanation: 'Compassionate concern and referral to appropriate professional support is the responsible response.' },
    { type: 'multiple_choice', question: 'Which principle of motivational interviewing involves avoiding arguments with resistant clients?', options: ['Support Self-Efficacy', 'Develop Discrepancy', 'Express Empathy', 'Roll with Resistance'], correctAnswer: 3, explanation: 'Rolling with Resistance means acknowledging the person\'s perspective rather than confronting it.' },
    { type: 'multiple_choice', question: 'In the UK, the title "dietitian" is protected by which body?', options: ['NHS', 'HCPC (Health and Care Professions Council)', 'British Nutrition Foundation', 'AfN (Association for Nutrition)'], correctAnswer: 1, explanation: 'The title 'dietitian" is legally protected by the HCPC in the UK.' },
    { type: 'multiple_choice', question: 'What is the most reliable predictor of sustained behaviour change?', options: ['Fear of consequences', 'Self-efficacy', 'Knowledge', 'Motivation'], correctAnswer: 1, explanation: 'Self-efficacy — belief in your ability to succeed — is one of the strongest predictors of sustained change.' },
    { type: 'multiple_choice', question: 'What is the cheapest approach to healthy eating?', options: ['Eating out at healthy restaurants', 'Buying pre-made meals', 'Ordering meal kit deliveries', 'Buying raw ingredients in bulk and cooking them yourself'], correctAnswer: 3, explanation: 'Buying and cooking raw ingredients is the most affordable approach by a significant margin.' },
    { type: 'multiple_choice', question: 'What does "change talk" refer to in motivational interviewing?', options: ['Talking about the weather to build rapport', 'Telling someone what they must change', 'Language that favours movement toward change', 'Discussing past failures'], correctAnswer: 2, explanation: 'Change talk is any language expressing desire, ability, reason, or need for change.' },
    { type: 'multiple_choice', question: 'Eating while distracted increases intake by approximately how much?', options: ['50%', '100%', '10–25%', '1–2%'], correctAnswer: 2, explanation: 'Research shows eating while distracted by TV or phones increases intake by 10–25%.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "Motivational Interviewing (MI) is:", options: ['Telling clients exactly what to do', 'Aggressive persuasion to change behaviour', 'A client-centred counselling approach that explores and resolves ambivalence about change', 'Only used in clinical psychology'], correctAnswer: 2, explanation: 'MI is a collaborative, non-judgemental approach where the practitioner helps the client explore their own reasons for change \u2014 more effective than directive advice-giving.' },
    { type: 'multiple_choice', question: "The Transtheoretical Model (stages of change) includes:", options: ['Pre-contemplation, contemplation, preparation, action, and maintenance', 'Only two stages: ready and not ready', 'Motivation, discipline, and achievement', 'Denial, anger, bargaining, and acceptance'], correctAnswer: 0, explanation: 'Prochaska & DiClemente's model identifies five stages: pre-contemplation (not considering change), contemplation (thinking about it), preparation (planning), action (doing it), and maintenance (sustaining it)." },
    { type: 'multiple_choice', question: "Disordered eating differs from an eating disorder because:", options: ['There is no difference', 'Disordered eating is more serious', 'Disordered eating exists on a spectrum and may not meet full clinical diagnostic criteria but still causes harm', 'Eating disorders are a choice'], correctAnswer: 2, explanation: 'Disordered eating encompasses a range of irregular eating behaviours (restriction, bingeing, excessive rules) that may not meet full diagnostic criteria for an eating disorder but can still significantly impair health.' },
    { type: 'multiple_choice', question: "A fitness professional's scope of practice in nutrition typically includes:", options: ['General healthy eating guidance and helping clients meet dietary guidelines', 'Diagnosing nutrient deficiencies', 'Prescribing supplements for medical conditions', 'Creating clinical diets for disease management'], correctAnswer: 0, explanation: 'Fitness professionals can provide general healthy eating guidance aligned with national guidelines, support behaviour change, and encourage balanced diets \u2014 but must refer for clinical/medical nutrition needs.' },
    { type: 'multiple_choice', question: "The psychology of eating is influenced by:", options: ['A complex interplay of hormones, emotions, habits, social context, stress, and environmental cues', 'Only hunger and satiety hormones', 'Willpower alone', 'Only food marketing'], correctAnswer: 0, explanation: 'Eating behaviour is influenced by biological signals (hunger/satiety hormones), psychological factors (emotions, stress, habits), social context, environmental cues, and cultural norms \u2014 not just willpower.' },
    { type: 'multiple_choice', question: "Effective nutrition communication involves:", options: ['Using technical jargon to appear knowledgeable', 'Telling clients they're doing everything wrong', 'Clear, simple language, active listening, empathy, and meeting the client where they are', 'Only providing written plans without discussion'], correctAnswer: 2, explanation: 'Effective communication uses plain language, listens actively, shows empathy, avoids judgment, and adapts to the client's level of understanding and readiness for change." },
    { type: 'multiple_choice', question: "Practical meal planning for clients should:", options: ["Be identical for everyone", "Be personalised, realistic, enjoyable, and consider budget, time, skills, and preferences", "Eliminate all treats and favourite foods", "Only include 'superfoods'"], correctAnswer: 1, explanation: "Effective meal plans are individualised \u2014 considering food preferences, budget, cooking skills, time available, cultural background, and existing habits. Rigid, generic plans rarely work." },
    { type: 'multiple_choice', question: "Which behaviour change technique is most effective long-term?", options: ['Punishment for non-compliance', 'Dramatic all-or-nothing changes', 'Relying entirely on external motivation from a coach', 'Self-monitoring combined with implementation intentions ('if-then' plans)'], correctAnswer: 3, explanation: 'Research shows self-monitoring (tracking intake/behaviour) combined with implementation intentions ('If I feel like snacking, then I'll have a piece of fruit') are among the most effective long-term techniques." },

  ],
};

// ── Final Assessment ──
