import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 }

export const nutritionL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What is the difference between hunger and appetite?', options: ['Hunger only happens when fasting', 'They are identical', 'Hunger is physiological; appetite is influenced by environment and emotion', 'Appetite is stronger than hunger'], correctAnswer: 2, explanation: 'Hunger is a physiological signal; appetite can be triggered by non-physiological cues.' },
    { type: 'multiple_choice', question: 'Using a smaller plate reduces intake by approximately how much?', options: ['50%', '75%', '5%', '20%'], correctAnswer: 3, explanation: 'A 25cm plate instead of 30cm reduces intake by approximately 20%.' },
    { type: 'multiple_choice', question: 'Eating while distracted increases intake by how much?', options: ['10–25%', '50%', '100%', '1–2%'], correctAnswer: 0, explanation: 'Distracted eating (TV, phone) increases intake by 10–25%.' },
    { type: 'multiple_choice', question: 'What is wrong with labelling foods as "good" or "bad"?', options: ['It creates guilt cycles and restriction-binge patterns', 'Nothing — it helps motivation', 'It makes food tastier', 'It simplifies nutrition'], correctAnswer: 0, explanation: 'Moral food labelling promotes guilt, shame, and restriction-overconsumption cycles.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for controlling food intake?', options: ['Stronger motivation', 'Skipping meals', 'Changing the food environment', 'Reading more nutrition books'], correctAnswer: 2, explanation: 'Environmental changes (food visibility, plate size, accessibility) produce larger effects than willpower alone.' },
    { type: 'multiple_choice', question: 'What category should foods be assessed by instead of "good" or "bad"?', options: ['Brand name', 'Price', 'Taste rating', 'Nutrient density'], correctAnswer: 3, explanation: 'Nutrient density — nutritional value per calorie — is a more constructive framework.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What are the five stages in the Transtheoretical Model?', options: ['Precontemplation, Contemplation, Preparation, Action, Maintenance', 'Denial, Anger, Bargaining, Depression, Acceptance', 'Plan, Do, Check, Act, Review', 'Start, Struggle, Fail, Restart, Succeed'], correctAnswer: 0, explanation: 'The five stages are Precontemplation, Contemplation, Preparation, Action, and Maintenance.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Making a to-do list', 'Replacing all habits simultaneously', 'Linking a new habit to an existing automatic habit', 'Doing everything at once'], correctAnswer: 2, explanation: 'Habit stacking attaches a new behaviour to an existing established habit as the cue.' },
    { type: 'multiple_choice', question: 'What is an implementation intention?', options: ['A New Year\'s resolution', 'A wish', 'A vague goal', 'A specific "if-then" plan for a behaviour'], correctAnswer: 3, explanation: 'Implementation intentions use "if-then" planning to specify when and how a behaviour will occur.' },
    { type: 'multiple_choice', question: 'What is self-efficacy?', options: ['Motivation', 'Intelligence', 'Belief in your ability to succeed at a specific task', 'Physical fitness'], correctAnswer: 2, explanation: 'Self-efficacy is your belief in your own ability to succeed — a strong predictor of sustained change.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['1–2 days', '1 year', '4–8 weeks', '6 months'], correctAnswer: 2, explanation: 'Most habits take approximately 4–8 weeks of consistent practice to become automatic.' },
    { type: 'multiple_choice', question: 'Which strategy best supports long-term behaviour change?', options: ['Relying on motivation', 'Changing everything at once', 'Setting extreme goals', 'Mastering one habit at a time before adding another'], correctAnswer: 3, explanation: 'Sequential habit building — mastering one before adding another — is more effective than simultaneous overhaul.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'Where on the spectrum does obsessive macro tracking sit?', options: ['Not on the spectrum', 'Potentially disordered eating', 'Clinical eating disorder', 'Healthy eating'], correctAnswer: 1, explanation: 'Obsessive tracking that causes anxiety or dominates daily life sits in the disordered eating range.' },
    { type: 'multiple_choice', question: 'What is the appropriate response if you suspect someone has an eating disorder?', options: ['Express concern without judgement and encourage them to see their GP', 'Diagnose them', 'Ignore it', 'Put them on a strict meal plan'], correctAnswer: 0, explanation: 'Compassionate concern and referral to a GP is the responsible response.' },
    { type: 'multiple_choice', question: 'What is Beat?', options: ['A music streaming service', ', ', ', ', 'The UK\'], correctAnswer: 3, explanation: 'Beat (beateatingdisorders.org.uk) provides helplines, support, and local services for eating disorders.' },
    { type: 'multiple_choice', question: 'Which is a behavioural warning sign of disordered eating?', options: ['Enjoying a variety of foods', 'Cooking for friends', 'Trying new restaurants', 'Avoiding social eating and excessive food rules'], correctAnswer: 3, explanation: 'Avoiding social eating and rigid food rules are behavioural indicators of disordered eating.' },
    { type: 'multiple_choice', question: 'Can fitness communities normalise disordered eating behaviours?', options: ['No, fitness is always healthy', 'Yes — extreme restriction and compensation are often normalised', 'Only online', 'Only in bodybuilding'], correctAnswer: 1, explanation: 'Fitness and bodybuilding communities have normalised many behaviours that sit on the disordered eating spectrum.' },
    { type: 'multiple_choice', question: 'What distinguishes a food allergy from an intolerance?', options: ['Intolerances are more dangerous', 'Allergies are less serious', 'Allergies involve an immune (IgE) response and can be life-threatening; intolerances do not', 'They are the same thing'], correctAnswer: 2, explanation: 'Food allergies involve an immune response and can cause anaphylaxis; intolerances are uncomfortable but not life-threatening.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is motivational interviewing?', options: ['Telling people what to do', 'A type of therapy for depression', 'A job interview technique', 'A counselling approach that helps people explore their own reasons for change'], correctAnswer: 3, explanation: 'MI guides people toward their own motivations for change rather than directing them.' },
    { type: 'multiple_choice', question: 'What does "rolling with resistance" mean?', options: [', ', ', ', 'Acknowledging the person\', ', '], correctAnswer: 2, explanation: 'Rolling with resistance means acknowledging rather than confronting opposition — resistance often decreases.' },
    { type: 'multiple_choice', question: 'What is "change talk"?', options: ['Talking about other people\'s changes', 'Complaining about current habits', 'Discussing the weather', 'Language that favours movement toward change'], correctAnswer: 3, explanation: 'Change talk includes statements of desire, ability, reason, or need for change.' },
    { type: 'multiple_choice', question: 'Which MI principle involves highlighting past successes?', options: ['Express Empathy', 'Develop Discrepancy', 'Support Self-Efficacy', 'Roll with Resistance'], correctAnswer: 2, explanation: 'Supporting Self-Efficacy includes reinforcing belief in ability through highlighting past successes.' },
    { type: 'multiple_choice', question: 'Why is asking questions more effective than giving advice?', options: ['Questions are easier', 'Advice is always wrong', 'People are more likely to commit to change they articulate themselves', 'It saves time'], correctAnswer: 2, explanation: 'Self-articulated motivations produce stronger commitment than externally imposed advice.' },
    { type: 'multiple_choice', question: 'Can MI principles be applied to your own internal dialogue?', options: ['Only with a therapist', 'Only in writing', 'No, only for professionals', 'Yes — noticing sustain talk and reframing toward change talk is effective'], correctAnswer: 3, explanation: 'MI principles work on your own internal dialogue — notice sustain talk and consciously reframe toward change talk.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is batch cooking?', options: ['Preparing large quantities of base ingredients to mix and match throughout the week', 'Cooking only at weekends', 'Ordering takeaway in bulk', 'Cooking one meal at a time'], correctAnswer: 0, explanation: 'Batch cooking prepares versatile base ingredients that are combined in different ways during the week.' },
    { type: 'multiple_choice', question: 'How much time does a typical batch cooking session take?', options: ['8 hours', '2–3 hours for 15–20 meals', '15 minutes', '30 minutes'], correctAnswer: 1, explanation: 'Approximately 2–3 hours on one day can produce components for 15–20 meals.' },
    { type: 'multiple_choice', question: 'Are frozen vegetables nutritionally inferior to fresh?', options: ['Only if organic', 'Frozen is always better', 'No — they are nutritionally equivalent, often frozen at peak ripeness', 'Yes, always'], correctAnswer: 2, explanation: 'Frozen vegetables are picked and frozen at peak ripeness, making them nutritionally equivalent to fresh.' },
    { type: 'multiple_choice', question: 'What is the cheapest protein source from this list?', options: ['Organic chicken breast', 'Wagyu steak', 'Fresh salmon', 'Eggs'], correctAnswer: 3, explanation: 'Eggs are consistently one of the cheapest high-quality protein sources available.' },
    { type: 'multiple_choice', question: 'What is a key benefit of meal planning for food waste?', options: ['It reduces waste by ensuring you buy only what you need', 'It increases waste', 'It only works for large families', 'It has no effect'], correctAnswer: 0, explanation: 'Planning purchases around actual needs significantly reduces food waste — a major hidden cost.' },
    { type: 'multiple_choice', question: 'What is the most expensive approach to eating?', options: ['Shopping at markets', 'Buying raw ingredients in bulk', 'Buying individual meals, takeaways, and prepared foods', 'Growing your own vegetables'], correctAnswer: 2, explanation: 'Convenience foods, takeaways, and prepared meals are significantly more expensive per serving.' },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Is the title "nutritionist" legally protected in the UK?', options: ['Only after 2020', 'Only in Wales', 'Yes', 'No'], correctAnswer: 3, explanation: 'Unlike 'dietitian," the title "nutritionist" is not legally protected in the UK.' },
    { type: 'multiple_choice', question: 'When should you refer someone to a registered dietitian?', options: ['When they ask about vegetables', 'Never', 'When they have a diagnosed medical condition affecting nutrition', 'Only if they ask'], correctAnswer: 2, explanation: 'Medical conditions like diabetes, kidney disease, or eating disorders require specialist referral.' },
    { type: 'multiple_choice', question: 'What regulates Registered Dietitians in the UK?', options: ['BMA', 'GMC', 'NHS', 'HCPC'], correctAnswer: 3, explanation: 'The Health and Care Professions Council (HCPC) regulates the title "dietitian" in the UK.' },
    { type: 'multiple_choice', question: 'What is the most responsible action when you do not know the answer to a nutrition question?', options: ['Make up an answer', 'Say "I do not know" and suggest appropriate resources', 'Avoid the person', 'Google it quickly and pretend you knew'], correctAnswer: 1, explanation: 'Honest acknowledgement of limitations and appropriate referral is the responsible approach.' },
    { type: 'multiple_choice', question: 'What is a key principle of responsible nutrition communication?', options: ['Using absolute statements like "never eat X"', 'Distinguishing between evidence-based guidelines and personal opinion', 'Sharing dramatic transformation photos', 'Promoting supplements for commission'], correctAnswer: 1, explanation: 'Responsible communication distinguishes evidence from opinion and acknowledges uncertainty.' },
    { type: 'multiple_choice', question: 'Why should you maintain a referral network?', options: ['For marketing purposes', 'It is a legal requirement', 'To avoid doing any work', 'To quickly direct people to appropriate help when situations exceed your scope'], correctAnswer: 3, explanation: 'Having referral contacts ready means you can act quickly when someone needs specialist support.' },
  ]),
];
