import type { UnitAssessment } from '../types';

export const nutritionL3Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Micronutrients, Supplementation & Special Populations',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'Why do fat-soluble vitamins carry a risk of toxicity?', options: ['They interact with medications', 'They require large doses to be effective', 'They are stored in the body and can accumulate', 'They are absorbed quickly'], correctAnswer: 2, explanation: 'Fat-soluble vitamins are stored in liver and adipose tissue, so excess accumulates rather than being excreted.' },
    { type: 'multiple_choice', question: 'What daily vitamin D supplementation does Public Health England recommend for UK adults in autumn and winter?', options: ['5 micrograms', '10 micrograms (400 IU)', '100 micrograms', '50 micrograms'], correctAnswer: 1, explanation: 'PHE recommends 10 micrograms (400 IU) daily during autumn and winter.' },
    { type: 'multiple_choice', question: 'Which supplement has the strongest evidence base for improving strength and power?', options: ['Creatine monohydrate', 'Testosterone boosters', 'Glutamine', 'BCAAs'], correctAnswer: 0, explanation: 'Creatine monohydrate is the most researched and consistently supported sports supplement.' },
    { type: 'multiple_choice', question: 'What is the effective caffeine dose for performance enhancement?', options: ['10–15mg per kg body weight', '20mg per kg body weight', '1mg per kg body weight', '3–6mg per kg body weight'], correctAnswer: 3, explanation: '3–6mg/kg consumed 30–60 minutes before training is the evidence-based dose.' },
    { type: 'multiple_choice', question: 'Which nutrient must all vegans supplement without exception?', options: ['Iron', 'Vitamin C', 'Vitamin B12', 'Calcium'], correctAnswer: 2, explanation: 'No reliable plant source of B12 exists. Deficiency causes irreversible nerve damage.' },
    { type: 'multiple_choice', question: 'How much additional energy per day is recommended during the third trimester of pregnancy?', options: ['Approximately 500 calories', 'Approximately 200 calories', 'Double normal intake', '0 extra calories'], correctAnswer: 1, explanation: 'Only approximately 200 additional calories per day are recommended, and only in the third trimester.' },
    { type: 'multiple_choice', question: 'What daily protein intake may older adults need to combat sarcopenia?', options: ['1.2–1.6g per kg', '0.5g per kg', '0.8g per kg', '3g per kg'], correctAnswer: 0, explanation: 'Older adults may need 1.2–1.6g/kg to overcome anabolic resistance and maintain muscle mass.' },
    { type: 'scenario', scenario: 'A vegan client reports fatigue, tingling in their hands, and difficulty concentrating. They do not take any supplements.', question: 'Which deficiency is most likely?', options: ['Zinc', 'Iron', 'Vitamin D', 'Vitamin B12'], correctAnswer: 3, explanation: 'Neurological symptoms (tingling, concentration issues) combined with fatigue in a non-supplementing vegan strongly suggest B12 deficiency.' },
    { type: 'multiple_choice', question: 'In the UK, who is legally qualified to provide medical nutrition therapy?', options: ['Personal trainers with a nutrition certificate', 'Nutritional therapists', 'Registered Dietitians (HCPC regulated)', 'Anyone with a food hygiene certificate'], correctAnswer: 2, explanation: 'Only Registered Dietitians regulated by the HCPC are qualified for medical nutrition therapy in the UK.' },
    { type: 'multiple_choice', question: 'Which form of iron is more bioavailable?', options: ['Supplemental iron oxide', 'Haem iron from animal sources', 'Non-haem iron from plants', 'Iron from fortified cereals'], correctAnswer: 1, explanation: 'Haem iron from animal sources is absorbed approximately 2–3 times more efficiently than non-haem iron.' },
    { type: 'multiple_choice', question: 'What is the recommended folic acid supplementation during early pregnancy?', options: ['400 micrograms daily', '5000 micrograms', '100 micrograms', '1000 micrograms'], correctAnswer: 0, explanation: '400 micrograms daily from trying to conceive until 12 weeks of pregnancy.' },
    { type: 'multiple_choice', question: 'Plant-based ALA converts to EPA/DHA at approximately what rate?', options: ['0%', '25–30%', '50–60%', '5–10%'], correctAnswer: 3, explanation: 'ALA conversion to EPA/DHA is very poor — approximately 5–10% — which is why algae-based supplements are recommended for vegans.' },
  ],
};
