import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const nutritionL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What is the difference between hunger and appetite?', options: ['They are identical', 'Hunger only happens when fasting', 'Appetite is stronger than hunger', 'Hunger is physiological; appetite is influenced by environment and emotion'], correctAnswer: 3, explanation: 'Hunger is a physiological signal; appetite can be triggered by non-physiological cues.' },
    { type: 'multiple_choice', question: 'Using a smaller plate reduces intake by approximately how much?', options: ['75%', '5%', '50%', '20%'], correctAnswer: 3, explanation: 'A 25cm plate instead of 30cm reduces intake by approximately 20%.' },
    { type: 'multiple_choice', question: 'Eating while distracted increases intake by how much?', options: ['50%', '10–25%', '1–2%', '100%'], correctAnswer: 1, explanation: 'Distracted eating (TV, phone) increases intake by 10–25%.' },
    { type: 'multiple_choice', question: 'What is wrong with labelling foods as "good" or "bad"?', options: ['It simplifies nutrition', 'It creates guilt cycles and restriction-binge patterns', 'Nothing — it helps motivation', 'It makes food tastier'], correctAnswer: 1, explanation: 'Moral food labelling promotes guilt, shame, and restriction-overconsumption cycles.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for controlling food intake?', options: ['Stronger motivation', 'Changing the food environment', 'Reading more nutrition books', 'Skipping meals'], correctAnswer: 1, explanation: 'Environmental changes (food visibility, plate size, accessibility) produce larger effects than willpower alone.' },
    { type: 'multiple_choice', question: 'What category should foods be assessed by instead of "good" or "bad"?', options: ['Price', 'Nutrient density', 'Brand name', 'Taste rating'], correctAnswer: 1, explanation: 'Nutrient density — nutritional value per calorie — is a more constructive framework.' },
    { type: 'multiple_choice', question: 'What is emotional eating?', options: ['Eating slowly', 'Eating when happy', 'Eating with friends', 'Using food to manage emotions rather than to satisfy physical hunger'], correctAnswer: 3, explanation: 'Emotional eating is using food to cope with emotions (stress, boredom, sadness) rather than responding to genuine physiological hunger signals.' },
    { type: 'multiple_choice', question: 'What is the difference between physical hunger and emotional hunger?', options: ['Emotional hunger is healthier', 'Physical hunger is always stronger', 'Physical hunger builds gradually and any food satisfies; emotional hunger is sudden, specific, and eating does not resolve the underlying emotion', 'No difference'], correctAnswer: 2, explanation: 'Physical hunger builds gradually, responds to any food, and stops when full. Emotional hunger is sudden, craves specific foods, and eating does not resolve the trigger.' },
    { type: 'multiple_choice', question: 'How does food environment influence eating behaviour?', options: ['No influence', 'Only taste matters', 'Environment only affects children', 'Plate size, food visibility, proximity, and portion size unconsciously influence how much we eat'], correctAnswer: 3, explanation: 'Research shows food environment (larger plates = more food, visible snacks = more snacking, proximity = more eating) powerfully shapes intake without conscious awareness.' },
    { type: 'multiple_choice', question: 'What is mindful eating?', options: ['Counting every calorie', 'Eating healthy food only', 'Eating while meditating', 'Paying deliberate attention to the experience of eating — taste, texture, hunger, and satiety cues — without distraction'], correctAnswer: 3, explanation: 'Mindful eating involves full attention to the eating experience — recognising hunger/satiety cues, savouring food, and eating without screens — improving portion control and satisfaction.' },
  
  
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What are the five stages in the Transtheoretical Model?', options: ['Start, Struggle, Fail, Restart, Succeed', 'Precontemplation, Contemplation, Preparation, Action, Maintenance', 'Denial, Anger, Bargaining, Depression, Acceptance', 'Plan, Do, Check, Act, Review'], correctAnswer: 1, explanation: 'The five stages are Precontemplation, Contemplation, Preparation, Action, and Maintenance.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Linking a new habit to an existing automatic habit', 'Replacing all habits simultaneously', 'Doing everything at once', 'Making a to-do list'], correctAnswer: 0, explanation: 'Habit stacking attaches a new behaviour to an existing established habit as the cue.' },
    { type: 'multiple_choice', question: 'What is an implementation intention?', options: ["A New Year\'s resolution", 'A wish', 'A vague goal', 'A specific "if-then" plan for a behaviour'], correctAnswer: 3, explanation: 'Implementation intentions use "if-then" planning to specify when and how a behaviour will occur.' },
    { type: 'multiple_choice', question: 'What is self-efficacy?', options: ['Belief in your ability to succeed at a specific task', 'Intelligence', 'Motivation', 'Physical fitness'], correctAnswer: 0, explanation: 'Self-efficacy is your belief in your own ability to succeed — a strong predictor of sustained change.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['6 months', '4–8 weeks', '1–2 days', '1 year'], correctAnswer: 1, explanation: 'Most habits take approximately 4–8 weeks of consistent practice to become automatic.' },
    { type: 'multiple_choice', question: 'Which strategy best supports long-term behaviour change?', options: ['Relying on motivation', 'Setting extreme goals', 'Mastering one habit at a time before adding another', 'Changing everything at once'], correctAnswer: 2, explanation: 'Sequential habit building — mastering one before adding another — is more effective than simultaneous overhaul.' },
    { type: 'multiple_choice', question: 'What are the stages of the transtheoretical model of change?', options: ['Precontemplation, contemplation, preparation, action, maintenance', 'Start, middle, end', 'Plan, do, check, act', 'Awareness, action, achievement'], correctAnswer: 0, explanation: 'The transtheoretical model identifies five stages: precontemplation (not considering change), contemplation (thinking about it), preparation (planning), action (doing), and maintenance (sustaining).' },
    { type: 'multiple_choice', question: 'Why do most diets fail long-term?', options: ['They focus on restriction rather than sustainable behaviour change — creating a psychological backlash', 'People lack willpower', 'The diets are wrong', 'People do not want to change'], correctAnswer: 0, explanation: 'Restrictive diets create psychological deprivation that leads to binge-restrict cycles — sustainable change requires positive habit building, not elimination.' },
    { type: 'multiple_choice', question: 'What is the most effective approach to nutrition behaviour change?', options: ['Strict meal plans', 'Small, specific habit changes implemented one at a time with accountability and self-monitoring', 'Complete diet overhaul', 'Supplements'], correctAnswer: 1, explanation: 'Research consistently shows that small, specific changes (one at a time, monitored, with support) produce better long-term outcomes than dramatic overhauls.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Adding multiple new habits at once', 'Linking a new habit to an existing one: "After I [current habit], I will [new habit]"', 'A supplement routine', 'Breaking all old habits'], correctAnswer: 1, explanation: 'Habit stacking leverages existing neural pathways — attaching a new behaviour to an established routine makes it more likely to stick.' },
  
  
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'Where on the spectrum does obsessive macro tracking sit?', options: ['Potentially disordered eating', 'Healthy eating', 'Not on the spectrum', 'Clinical eating disorder'], correctAnswer: 0, explanation: 'Obsessive tracking that causes anxiety or dominates daily life sits in the disordered eating range.' },
    { type: 'multiple_choice', question: 'What is the appropriate response if you suspect someone has an eating disorder?', options: ['Diagnose them', 'Ignore it', 'Put them on a strict meal plan', 'Express concern without judgement and encourage them to see their GP'], correctAnswer: 3, explanation: 'Compassionate concern and referral to a GP is the responsible response.' },
    { type: 'multiple_choice', question: 'What is Beat?', options: ['A music streaming service', 'A government food safety agency', 'A fitness tracking app', "The UK's leading eating disorder charity"], correctAnswer: 3, explanation: 'Beat (beateatingdisorders.org.uk) provides helplines, support, and local services for eating disorders.' },
    { type: 'multiple_choice', question: 'Which is a behavioural warning sign of disordered eating?', options: ['Cooking for friends', 'Enjoying a variety of foods', 'Trying new restaurants', 'Avoiding social eating and excessive food rules'], correctAnswer: 3, explanation: 'Avoiding social eating and rigid food rules are behavioural indicators of disordered eating.' },
    { type: 'multiple_choice', question: 'Can fitness communities normalise disordered eating behaviours?', options: ['Only in bodybuilding', 'Yes — extreme restriction and compensation are often normalised', 'Only online', 'No, fitness is always healthy'], correctAnswer: 1, explanation: 'Fitness and bodybuilding communities have normalised many behaviours that sit on the disordered eating spectrum.' },
    { type: 'multiple_choice', question: 'What distinguishes a food allergy from an intolerance?', options: ['Allergies are less serious', 'Intolerances are more dangerous', 'They are the same thing', 'Allergies involve an immune (IgE) response and can be life-threatening; intolerances do not'], correctAnswer: 3, explanation: 'Food allergies involve an immune response and can cause anaphylaxis; intolerances are uncomfortable but not life-threatening.' },
    { type: 'multiple_choice', question: 'What is the difference between disordered eating and an eating disorder?', options: ['They are the same', 'Eating disorders are less serious', 'Only women experience either', 'Disordered eating is unhealthy patterns; eating disorders are clinical conditions — but disordered eating can progress to an eating disorder'], correctAnswer: 3, explanation: 'Disordered eating exists on a spectrum — unhealthy patterns may not meet clinical criteria but can progress to diagnosable eating disorders if unaddressed.' },
    { type: 'multiple_choice', question: 'What are red flags that suggest a client may need referral for disordered eating?', options: ['Tracking macros', 'Wanting to lose weight', 'Extreme restriction, excessive exercise, rigid food rules, body image distortion, or compensatory behaviours', 'Skipping one meal'], correctAnswer: 2, explanation: 'Red flags include extreme restriction, compulsive exercise, purging, rigid rules around food, significant body image distortion, and distress around eating — these require referral.' },
    { type: 'multiple_choice', question: 'What is Relative Energy Deficiency in Sport (RED-S)?', options: ['A supplement', 'A training method', 'A syndrome caused by insufficient energy availability that impairs physiological function across multiple body systems', 'Not eating enough protein'], correctAnswer: 2, explanation: 'RED-S occurs when energy intake is chronically insufficient for health and activity — affecting hormones, bone health, immunity, cardiovascular function, and mental health.' },
    { type: 'multiple_choice', question: 'What is orthorexia?', options: ['A healthy eating pattern', 'Undereating', 'Overeating', 'An unhealthy obsession with eating only "clean" or "pure" foods — causing anxiety, social isolation, and nutritional deficiency'], correctAnswer: 3, explanation: 'Orthorexia is an obsessive focus on "clean" eating that paradoxically impairs health — causing anxiety around food, social isolation, and often nutritional deficiency.' },
  
  
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is motivational interviewing?', options: ['Telling people what to do', 'A type of therapy for depression', 'A job interview technique', 'A counselling approach that helps people explore their own reasons for change'], correctAnswer: 3, explanation: 'MI guides people toward their own motivations for change rather than directing them.' },
      { type: 'multiple_choice', question: 'What does "rolling with resistance" mean?', options: ['Acknowledging rather than confronting opposition to reduce resistance', 'Pushing harder against objections', 'Ignoring all feedback from clients', 'Physically rolling on a foam roller'], correctAnswer: 0, explanation: 'Rolling with resistance means acknowledging rather than confronting opposition — resistance often decreases when people feel heard.' },
    { type: 'multiple_choice', question: 'What is "change talk"?', options: ["Talking about other people\'s changes", 'Complaining about current habits', 'Discussing the weather', 'Language that favours movement toward change'], correctAnswer: 3, explanation: 'Change talk includes statements of desire, ability, reason, or need for change.' },
    { type: 'multiple_choice', question: 'Which MI principle involves highlighting past successes?', options: ['Roll with Resistance', 'Express Empathy', 'Support Self-Efficacy', 'Develop Discrepancy'], correctAnswer: 2, explanation: 'Supporting Self-Efficacy includes reinforcing belief in ability through highlighting past successes.' },
    { type: 'multiple_choice', question: 'Why is asking questions more effective than giving advice?', options: ['It saves time', 'Questions are easier', 'People are more likely to commit to change they articulate themselves', 'Advice is always wrong'], correctAnswer: 2, explanation: 'Self-articulated motivations produce stronger commitment than externally imposed advice.' },
    { type: 'multiple_choice', question: 'Can MI principles be applied to your own internal dialogue?', options: ['Yes — noticing sustain talk and reframing toward change talk is effective', 'Only in writing', 'No, only for professionals', 'Only with a therapist'], correctAnswer: 0, explanation: 'MI principles work on your own internal dialogue — notice sustain talk and consciously reframe toward change talk.' },
    { type: 'multiple_choice', question: 'What is motivational interviewing?', options: ['Telling clients what to do', 'A collaborative conversation style that strengthens a person\'s own motivation for change', 'A job interview technique', 'Motivational speaking'], correctAnswer: 1, explanation: 'Motivational interviewing is a client-centred approach that elicits the person\'s own reasons for change — more effective than prescriptive advice-giving.' },
    { type: 'multiple_choice', question: 'What is the "righting reflex" in coaching?', options: ['Correct posture', 'The urge to fix clients\' problems by telling them what to do — which often creates resistance', 'A balance exercise', 'Correcting technique'], correctAnswer: 1, explanation: 'The righting reflex is the coach\'s natural urge to fix problems — but unsolicited advice often creates resistance. MI elicits the client\'s own solutions.' },
    { type: 'multiple_choice', question: 'What are OARS in motivational interviewing?', options: ['Open questions, Affirmations, Reflective listening, and Summarising — the four core MI skills', 'Training exercises', 'Rowing equipment', 'A scoring system'], correctAnswer: 0, explanation: 'OARS: Open questions (explore), Affirmations (acknowledge strengths), Reflective listening (demonstrate understanding), Summarising (consolidate) — the foundation of MI.' },
    { type: 'multiple_choice', question: 'What is change talk and why is it important?', options: ['A type of therapy', 'Talking about changing careers', 'Telling clients to change', 'Statements from the client expressing desire, ability, reason, or need for change — the strongest predictor of actual behaviour change'], correctAnswer: 3, explanation: 'Change talk ("I want to...", "I could...", "I need to...") is language from the client expressing their own motivation — eliciting this is the primary goal of MI.' },
  
  
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is batch cooking?', options: ['Ordering takeaway in bulk', 'Cooking one meal at a time', 'Preparing large quantities of base ingredients to mix and match throughout the week', 'Cooking only at weekends'], correctAnswer: 2, explanation: 'Batch cooking prepares versatile base ingredients that are combined in different ways during the week.' },
    { type: 'multiple_choice', question: 'How much time does a typical batch cooking session take?', options: ['2–3 hours for 15–20 meals', '15 minutes', '30 minutes', '8 hours'], correctAnswer: 0, explanation: 'Approximately 2–3 hours on one day can produce components for 15–20 meals.' },
    { type: 'multiple_choice', question: 'Are frozen vegetables nutritionally inferior to fresh?', options: ['Yes, always', 'Only if organic', 'Frozen is always better', 'No — they are nutritionally equivalent, often frozen at peak ripeness'], correctAnswer: 3, explanation: 'Frozen vegetables are picked and frozen at peak ripeness, making them nutritionally equivalent to fresh.' },
    { type: 'multiple_choice', question: 'What is the cheapest protein source from this list?', options: ['Wagyu steak', 'Organic chicken breast', 'Fresh salmon', 'Eggs'], correctAnswer: 3, explanation: 'Eggs are consistently one of the cheapest high-quality protein sources available.' },
    { type: 'multiple_choice', question: 'What is a key benefit of meal planning for food waste?', options: ['It only works for large families', 'It reduces waste by ensuring you buy only what you need', 'It has no effect', 'It increases waste'], correctAnswer: 1, explanation: 'Planning purchases around actual needs significantly reduces food waste — a major hidden cost.' },
    { type: 'multiple_choice', question: 'What is the most expensive approach to eating?', options: ['Shopping at markets', 'Buying raw ingredients in bulk', 'Growing your own vegetables', 'Buying individual meals, takeaways, and prepared foods'], correctAnswer: 3, explanation: 'Convenience foods, takeaways, and prepared meals are significantly more expensive per serving.' },
    { type: 'multiple_choice', question: 'What is the primary benefit of meal prep?', options: ['Saving money only', 'Impressing others', 'Making food taste better', 'Reducing daily decision fatigue by having healthy options pre-prepared and readily available'], correctAnswer: 3, explanation: 'Meal prep removes the decision point where unhealthy choices happen — when tired, hungry, and faced with what to cook, pre-prepared healthy food wins.' },
    { type: 'multiple_choice', question: 'What is batch cooking?', options: ['Cooking one meal at a time', 'Preparing larger quantities of base ingredients or meals at once for use across multiple days', 'A professional kitchen technique', 'Cooking in small batches'], correctAnswer: 1, explanation: 'Batch cooking (cooking proteins, grains, and vegetables in bulk) creates flexible meal components that can be combined differently across the week.' },
    { type: 'multiple_choice', question: 'How long can most meal-prepped foods be safely stored in the fridge?', options: ['Indefinitely', '1 day', '2 weeks', '3–4 days for most cooked foods, or freeze for longer storage'], correctAnswer: 3, explanation: 'Most cooked meal-prep items are safe for 3–4 days refrigerated. Beyond that, freeze portions to maintain safety and quality.' },
    { type: 'multiple_choice', question: 'What is the "cook once, eat twice" principle?', options: ['Deliberately cooking double portions so a second meal requires minimal effort', 'Cooking two different meals', 'Eating the same meal forever', 'Eating leftovers only'], correctAnswer: 0, explanation: 'Cook once, eat twice maximises efficiency — double portions provide a ready-made next meal with zero additional cooking time.' },
  
  
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Is the title "nutritionist" legally protected in the UK?', options: ['Yes', 'No', 'Only after 2020', 'Only in Wales'], correctAnswer: 1, explanation: 'Unlike \'dietitian," the title "nutritionist" is not legally protected in the UK.' },
    { type: 'multiple_choice', question: 'When should you refer someone to a registered dietitian?', options: ['Only if they ask', 'When they have a diagnosed medical condition affecting nutrition', 'When they ask about vegetables', 'Never'], correctAnswer: 1, explanation: 'Medical conditions like diabetes, kidney disease, or eating disorders require specialist referral.' },
    { type: 'multiple_choice', question: 'What regulates Registered Dietitians in the UK?', options: ['HCPC', 'BMA', 'GMC', 'NHS'], correctAnswer: 0, explanation: 'The Health and Care Professions Council (HCPC) regulates the title "dietitian" in the UK.' },
    { type: 'multiple_choice', question: 'What is the most responsible action when you do not know the answer to a nutrition question?', options: ['Avoid the person', 'Say "I do not know" and suggest appropriate resources', 'Make up an answer', 'Google it quickly and pretend you knew'], correctAnswer: 1, explanation: 'Honest acknowledgement of limitations and appropriate referral is the responsible approach.' },
    { type: 'multiple_choice', question: 'What is a key principle of responsible nutrition communication?', options: ['Promoting supplements for commission', 'Using absolute statements like "never eat X"', 'Distinguishing between evidence-based guidelines and personal opinion', 'Sharing dramatic transformation photos'], correctAnswer: 2, explanation: 'Responsible communication distinguishes evidence from opinion and acknowledges uncertainty.' },
    { type: 'multiple_choice', question: 'Why should you maintain a referral network?', options: ['To avoid doing any work', 'For marketing purposes', 'It is a legal requirement', 'To quickly direct people to appropriate help when situations exceed your scope'], correctAnswer: 3, explanation: 'Having referral contacts ready means you can act quickly when someone needs specialist support.' },
    { type: 'multiple_choice', question: 'What should you do if a client asks about managing their diabetes with diet?', options: ['Create a diabetes meal plan', 'Refer them to a registered dietitian — diabetes management is outside L3 scope of practice', 'Give general healthy eating advice only', 'Ignore the request'], correctAnswer: 1, explanation: 'Managing diagnosed medical conditions like diabetes requires clinical expertise — refer to a registered dietitian while supporting general healthy eating within your scope.' },
    { type: 'multiple_choice', question: 'How should you communicate nutrition information to avoid misinformation?', options: ['Use complex scientific language', 'Use evidence-based information, cite sources when challenged, and say "I don\'t know" when uncertain', 'Share trending diet advice', 'Only use social media sources'], correctAnswer: 1, explanation: 'Professional nutrition communication uses evidence-based information, acknowledges uncertainty, and refers beyond scope — credibility comes from honesty, not appearing to know everything.' },
    { type: 'multiple_choice', question: 'What is the difference between general nutrition advice and medical nutrition therapy?', options: ['Anyone can provide both', 'No difference', 'Medical nutrition therapy is simpler', 'General advice covers healthy eating for the general population; medical nutrition therapy treats specific conditions and requires clinical qualification'], correctAnswer: 3, explanation: 'General nutrition advice (healthy eating, macros, meal planning) is within L3 scope; medical nutrition therapy (treating disease with diet) requires registered dietitian qualification.' },
    { type: 'multiple_choice', question: 'Why is it important to use simple language when communicating nutrition information?', options: ['Only use technical terms', 'Clear, jargon-free communication ensures understanding and empowers clients to make informed choices', 'Simplicity dumbs it down', 'Scientific language impresses clients'], correctAnswer: 1, explanation: 'Effective communication prioritises understanding over impression — clients who understand the "why" behind recommendations are more likely to follow through.' },
  
  
  ]),
  cq(4, 7, [
    { type: 'multiple_choice', question: 'What is the ideal listening-to-talking ratio in an initial nutrition consultation?', options: ['50:50', '100% practitioner talking', '80:20 (practitioner:client)', '30:70 (practitioner:client)'], correctAnswer: 3, explanation: 'The ideal ratio is approximately 70% client, 30% practitioner — your job is to understand their world before advising.' },
    { type: 'multiple_choice', question: 'What is the biggest consultation mistake?', options: ['Being too friendly', 'Asking too many questions', 'Using handouts', 'Talking more than listening and overloading with science'], correctAnswer: 3, explanation: 'Talking more than listening and overloading clients with scientific detail prevents them from feeling heard and reduces adherence.' },
    { type: 'multiple_choice', question: 'How should action plans from a consultation be evaluated?', options: ['The "would you bet £50 you will do this?" test', 'Whether they match a textbook plan', 'Whether they are scientifically perfect', 'How many actions there are'], correctAnswer: 0, explanation: 'Actions should pass a realistic commitment test — fewer realistic actions beat ambitious wishlists.' },
    { type: 'multiple_choice', question: 'What should you ask about a client\'s eating patterns?', options: ['A typical day of eating — not an ideal day', 'Their favourite restaurant', 'Only their supplement routine', 'What their ideal diet would look like'], correctAnswer: 0, explanation: 'Ask about a typical day of eating (reality), not an ideal day (aspiration) — you need to understand their actual starting point.' },
    { type: 'multiple_choice', question: 'What makes the real difference in behaviour change after a consultation?', options: ['The number of handouts given', 'How many tests were ordered', 'The follow-up — checking in, adjusting, and celebrating progress', 'The initial plan'], correctAnswer: 2, explanation: 'The consultation is not the intervention — the follow-up process is where behaviour change actually happens.' },
    { type: 'multiple_choice', question: 'What should a nutrition consultation begin with?', options: ['Giving a meal plan immediately', 'Listening to the client\'s story, understanding their goals, current habits, and lifestyle context', 'Measuring body fat', 'Discussing supplements'], correctAnswer: 1, explanation: 'Effective consultations start with listening — understanding the client\'s goals, current eating patterns, lifestyle constraints, and readiness for change before making recommendations.' },
    { type: 'multiple_choice', question: 'Why is rapport building important in nutrition consultations?', options: ['It wastes time', 'Trust and connection determine whether clients follow through — people implement advice from people they trust', 'Only for the first session', 'It is not important'], correctAnswer: 1, explanation: 'Research shows adherence correlates more strongly with the quality of the coaching relationship than the quality of the nutrition plan — rapport enables compliance.' },
    { type: 'multiple_choice', question: 'What is the best way to set nutrition goals with a client?', options: ['Set the most ambitious goals possible', 'Let them set goals alone', 'Collaboratively set SMART goals that align with their values, lifestyle, and readiness for change', 'Tell them what to do'], correctAnswer: 2, explanation: 'Collaborative goal-setting increases ownership and adherence — goals should be specific, measurable, achievable, relevant, and time-bound, aligned with the client\'s life.' },
    { type: 'multiple_choice', question: 'What information should a nutrition consultation intake form capture?', options: ['Only weight and height', 'Exercise history only', 'Medical history, current eating patterns, lifestyle, goals, allergies, medications, and readiness for change', 'Food preferences only'], correctAnswer: 2, explanation: 'A comprehensive intake captures the full picture: health history, medications, eating patterns, lifestyle constraints, goals, allergies, and psychological readiness.' },
    { type: 'multiple_choice', question: 'How should you handle a client who is resistant to change?', options: ['Give up on them', 'Tell them they are wrong', 'Push harder with facts', 'Explore their ambivalence with open questions, acknowledge their perspective, and avoid arguing'], correctAnswer: 3, explanation: 'Resistance signals ambivalence, not refusal — exploring concerns with genuine curiosity, acknowledging their perspective, and avoiding arguments builds trust and readiness.' },
  
  
  ]),
  cq(4, 8, [
    { type: 'multiple_choice', question: 'Why is continuing professional development (CPD) essential?', options: ['Only for career advancement', 'Nutrition science evolves rapidly and outdated advice can cause harm', 'To charge higher prices', 'It is not essential'], correctAnswer: 1, explanation: 'Nutrition science evolves rapidly — a practitioner who stops learning after qualification quickly becomes outdated, and outdated advice can cause real harm.' },
    { type: 'multiple_choice', question: 'What sits at the top of the evidence hierarchy?', options: ['Systematic reviews and meta-analyses', 'Expert opinion', 'Social media testimonials', 'Single case studies'], correctAnswer: 0, explanation: 'Systematic reviews and meta-analyses carry the most weight, followed by RCTs, observational studies, and finally expert opinion.' },
    { type: 'multiple_choice', question: 'What should you always check before forming opinions from a nutrition headline?', options: ['The journalist\'s credentials', 'The abstract of the actual study', 'How many likes the article got', 'Whether celebrities shared it'], correctAnswer: 1, explanation: 'Headlines distort research — always read the actual study abstract before forming an opinion based on media coverage.' },
    { type: 'multiple_choice', question: 'What is the difference between statistical significance and practical significance?', options: ['Practical significance is less important', 'A statistically significant finding can be practically meaningless if the effect size is tiny', 'Statistical significance always means large effects', 'They are the same thing'], correctAnswer: 1, explanation: 'A finding can be statistically significant but have such a tiny effect size that it makes no practical difference.' },
    { type: 'multiple_choice', question: 'What is the most effective CPD habit?', options: ['Only attending conferences', 'A weekly 30-minute learning block — consistency beats intensity', 'Reading for 8 hours once per year', 'Following social media influencers'], correctAnswer: 1, explanation: 'A consistent weekly 30-minute learning block compounds rapidly — consistency beats intensity in CPD, just as in training.' },
    { type: 'multiple_choice', question: 'Why is teaching a concept to others valuable for CPD?', options: ['It earns money', 'It is not valuable', 'It only benefits the student', 'Explaining concepts deepens your own understanding more than passive study'], correctAnswer: 3, explanation: 'Teaching forces articulation and reveals knowledge gaps — it deepens understanding more effectively than passive reading.' },
    { type: 'multiple_choice', question: 'What is CPD in the context of nutrition?', options: ['Continuing Professional Development — ongoing learning to maintain and improve knowledge and skills', 'A certification', 'A supplement brand', 'A type of diet'], correctAnswer: 0, explanation: 'CPD is the ongoing process of learning, reflecting, and developing professionally — nutrition science evolves rapidly, making continuous learning essential.' },
    { type: 'multiple_choice', question: 'Why is critical evaluation of nutrition research important?', options: ['Research is irrelevant to practice', 'All research is equally valid', 'Study quality varies enormously — understanding methodology helps distinguish reliable evidence from noise', 'Only scientists need this skill'], correctAnswer: 2, explanation: 'Nutrition research quality varies widely — understanding sample sizes, study design, conflicts of interest, and statistical significance helps filter reliable evidence from hype.' },
    { type: 'multiple_choice', question: 'What is the hierarchy of evidence in nutrition science?', options: ['All evidence is equal', 'Systematic reviews/meta-analyses > RCTs > cohort studies > case studies > expert opinion', 'Social media is most reliable', 'Expert opinion is strongest'], correctAnswer: 1, explanation: 'Evidence quality follows a hierarchy: systematic reviews and meta-analyses provide the strongest evidence, while expert opinion and anecdotes are the weakest.' },
    { type: 'multiple_choice', question: 'What is reflective practice in nutrition?', options: ['Systematically reviewing client interactions and outcomes to identify what worked, what did not, and what to improve', 'Looking in a mirror', 'Reading textbooks only', 'Attending courses'], correctAnswer: 0, explanation: 'Reflective practice — regularly reviewing your client interactions, decisions, and outcomes — is the most powerful form of professional development.' },
  
  
  ]),
];
