import type { UnitAssessment } from '../types';

export const nutritionL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Sports Nutrition & Performance Fuelling',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What protein intake is recommended during a fat loss phase?', options: ['4g per kg', '0.8g per kg', '2.0–2.4g per kg', '1.2g per kg'], correctAnswer: 2, explanation: 'Higher protein (2.0–2.4g/kg) during a deficit preserves muscle mass and increases satiety.' },
    { type: 'multiple_choice', question: 'What carbohydrate loading protocol is currently recommended?', options: ['Normal eating with extra pasta the night before', '8–12g/kg carbohydrate for 36–48 hours with tapering training', 'Depletion for 3 days then loading for 3 days', 'Zero carbs for a week then unlimited carbs'], correctAnswer: 1, explanation: 'The modern simplified protocol of 8–12g/kg for 36–48 hours achieves comparable glycogen levels without depletion.' },
    { type: 'multiple_choice', question: 'For events over 2.5 hours, what is the recommended intra-event carbohydrate intake?', options: ['Up to 90g per hour using glucose-fructose combinations', '30g per hour', '10g per hour', '150g per hour'], correctAnswer: 0, explanation: 'Up to 90g/hour using multiple transportable carbohydrates (2:1 glucose:fructose) for ultra-endurance events.' },
    { type: 'multiple_choice', question: 'What caloric surplus is appropriate for a lean bulk in trained individuals?', options: ['1000+ calories', '50–100 calories', 'No surplus needed', '200–400 calories'], correctAnswer: 3, explanation: 'A modest 200–400 calorie surplus provides sufficient energy for muscle growth with minimal fat gain.' },
    { type: 'multiple_choice', question: 'At what level of dehydration does measurable performance decline typically begin?', options: ['10% body weight', '5% body weight', '2% body weight', '0.5% body weight'], correctAnswer: 2, explanation: 'Dehydration of 2% or more of body weight consistently impairs both physical and cognitive performance.' },
    { type: 'scenario', scenario: 'An athlete has been dieting for 14 weeks. They report persistent fatigue, strength loss, poor sleep, and extreme hunger.', question: 'What is the most appropriate recommendation?', options: ['Add more cardio', 'Plan a 1–2 week diet break at maintenance calories', 'Reduce calories further', 'Switch to a keto diet'], correctAnswer: 1, explanation: 'After 14 weeks, these symptoms indicate metabolic adaptation. A diet break at maintenance is the appropriate response.' },
    { type: 'multiple_choice', question: 'Which body composition method is considered the practical gold standard?', options: ['DEXA scan', 'BMI calculation', 'Bioelectrical impedance (BIA) scales', 'Waist-to-hip ratio'], correctAnswer: 0, explanation: 'DEXA scans use low-dose X-rays to differentiate bone, lean mass, and fat mass with approximately 1–2% accuracy.' },
    { type: 'multiple_choice', question: 'What is the primary electrolyte of concern during prolonged endurance exercise?', options: ['Calcium', 'Potassium', 'Magnesium', 'Sodium'], correctAnswer: 3, explanation: 'Sodium is the primary electrolyte lost in sweat and its depletion can cause dangerous hyponatraemia.' },
    { type: 'multiple_choice', question: 'What is the recommended fat loss rate for non-obese individuals?', options: ['3kg per week', '0.05kg per week', '0.25–0.5kg per week', '1–2kg per week'], correctAnswer: 2, explanation: 'A rate of 0.25–0.5kg per week minimises muscle loss and is sustainable.' },
    { type: 'multiple_choice', question: 'Why is body weight alone an unreliable measure of progress?', options: ['Scales are inaccurate', 'Daily fluctuations of 1–3kg from water, glycogen, and gut contents mask true changes', 'Weight never changes', 'Muscle weighs more than fat'], correctAnswer: 1, explanation: 'Daily weight fluctuations from non-fat factors obscure the actual trend in body composition.' },
    { type: 'multiple_choice', question: 'What is hyponatraemia?', options: ['Dangerously low blood sodium from over-drinking plain water', 'High blood sodium', 'High blood sugar', 'Dehydration'], correctAnswer: 0, explanation: 'Hyponatraemia is dangerously low blood sodium, usually caused by over-drinking water without sodium replacement.' },
    { type: 'multiple_choice', question: 'How much glycogen does a high-volume training session typically deplete?', options: ['80–100%', '0%', '5–10%', '25–40%'], correctAnswer: 3, explanation: 'A typical high-volume session (20–25 working sets) depletes approximately 25–40% of muscle glycogen.' },
  ],
};
