import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const nutritionL3Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'Where does glycolysis occur?', options: ['Endoplasmic reticulum', 'Mitochondria', 'Cytoplasm', 'Cell nucleus'], correctAnswer: 2, explanation: 'Glycolysis occurs in the cytoplasm of cells.' },
    { type: 'multiple_choice', question: 'How many ATP molecules does glycolysis alone produce per glucose molecule?', options: ['36', '2', '12', '38'], correctAnswer: 1, explanation: 'Glycolysis yields 2 ATP per glucose molecule.' },
    { type: 'multiple_choice', question: 'What happens to pyruvate when oxygen is insufficient?', options: ['It is converted to lactate', 'It is excreted', 'It is stored as glycogen', 'It enters the Krebs cycle'], correctAnswer: 0, explanation: 'Without oxygen, pyruvate is converted to lactate via anaerobic metabolism.' },
    { type: 'multiple_choice', question: 'How much glycogen can muscles typically store?', options: ['1000–1500g', '50–100g', '2000g', '300–500g'], correctAnswer: 3, explanation: 'Muscles store approximately 300–500g of glycogen.' },
    { type: 'multiple_choice', question: 'What sensation is associated with glycogen depletion during exercise?', options: ['Dizziness', 'Cramping', '"Hitting the wall"', 'Nausea'], correctAnswer: 2, explanation: 'Glycogen depletion leads to the fatigue sensation athletes describe as "hitting the wall."' },
    { type: 'multiple_choice', question: 'Which energy system dominates during a heavy set of squats?', options: ['Ketone metabolism', 'Anaerobic glycolysis', 'Fat oxidation', 'Aerobic'], correctAnswer: 1, explanation: 'High-intensity, short-duration efforts rely primarily on anaerobic glycolysis.' },
    { type: 'multiple_choice', question: 'Liver glycogen primarily maintains what?', options: ['Blood glucose levels', 'Protein synthesis', 'Muscle contraction', 'Fat storage'], correctAnswer: 0, explanation: 'Liver glycogen maintains blood glucose, critical for brain function.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What does MPS stand for?', options: ['Metabolic Protein Storage', 'Minimal Protein Supply', 'Maximum Protein Serving', 'Muscle Protein Synthesis'], correctAnswer: 3, explanation: 'MPS stands for Muscle Protein Synthesis.' },
    { type: 'multiple_choice', question: 'How long does resistance training elevate MPS?', options: ['2–4 hours', '7 days', '24–72 hours', '30 minutes'], correctAnswer: 2, explanation: 'Resistance training stimulates MPS for 24–72 hours after a session.' },
    { type: 'multiple_choice', question: 'What amino acid is most important for triggering MPS?', options: ['Tryptophan', 'Leucine', 'Glycine', 'Glutamine'], correctAnswer: 1, explanation: 'Leucine is the key amino acid trigger for MPS.' },
    { type: 'multiple_choice', question: 'How much protein per meal is generally needed to reach the leucine threshold?', options: ['25–40g', '5–10g', '60–80g', '15–20g'], correctAnswer: 0, explanation: 'Approximately 25–40g of high-quality protein per meal reaches the leucine threshold.' },
    { type: 'multiple_choice', question: 'Is the 30-minute "anabolic window" after training critical?', options: ['Only for cardio', 'Yes, you must eat within 30 minutes', 'Only for beginners', 'No, the window is measured in hours not minutes'], correctAnswer: 3, explanation: 'The anabolic window is measured in hours. Daily total and distribution matter more than exact post-workout timing.' },
    { type: 'multiple_choice', question: 'How many protein-rich meals per day is recommended for optimal MPS?', options: ['6–8', '1–2', '3–5', '10+'], correctAnswer: 2, explanation: '3–5 meals each hitting the leucine threshold maximises 24-hour MPS.' },
    { type: 'multiple_choice', question: 'Why might vegans need larger protein servings per meal?', options: ['Plant protein tastes worse', 'Plant proteins contain less leucine per gram', 'Plant protein is not real protein', 'Vegans need less protein overall'], correctAnswer: 1, explanation: 'Plant proteins typically contain less leucine per gram, requiring larger servings to reach the threshold.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Cholesterol is the precursor to which type of hormones?', options: ['Steroid hormones', 'Thyroid hormones', 'Peptide hormones', 'Growth hormones'], correctAnswer: 0, explanation: 'Cholesterol is the precursor to steroid hormones including testosterone and oestrogen.' },
    { type: 'multiple_choice', question: 'What is the ideal omega-6 to omega-3 ratio?', options: ['15:1', '1:1', '20:1', '2:1 to 4:1'], correctAnswer: 3, explanation: 'The ideal ratio is 2:1 to 4:1, though the modern Western diet typically exceeds 15:1.' },
    { type: 'multiple_choice', question: 'What are industrial trans fats?', options: ['Natural fats found in dairy', 'Essential fatty acids', 'Unsaturated fats altered by partial hydrogenation', 'A type of omega-3'], correctAnswer: 2, explanation: 'Industrial trans fats are created through partial hydrogenation and increase cardiovascular risk.' },
    { type: 'multiple_choice', question: 'What percentage of daily calories should fat comprise for active individuals?', options: ['50–60%', '20–35%', '70–80%', '5–10%'], correctAnswer: 1, explanation: 'Fat should comprise 20–35% of total daily calories for most active individuals.' },
    { type: 'multiple_choice', question: 'Which omega-3 forms are most bioactive?', options: ['EPA and DHA', 'CLA', 'ALA', 'GLA'], correctAnswer: 0, explanation: 'EPA and DHA from oily fish are the most bioactive forms; plant ALA converts poorly.' },
    { type: 'multiple_choice', question: 'Going below what fat intake risks hormonal disruption?', options: ['5% of calories', '35% of calories', '50% of calories', '20% of calories'], correctAnswer: 3, explanation: 'Going below 20% of calories from fat risks hormonal disruption and poor vitamin absorption.' },
    { type: 'multiple_choice', question: 'What minimum fat intake per kg body weight is recommended?', options: ['2.0g/kg', '0.3g/kg', '0.7g/kg', '1.5g/kg'], correctAnswer: 2, explanation: 'At least 0.7g fat per kilogram body weight protects hormonal function.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'Which TDEE component accounts for 60–70% of daily expenditure?', options: ['TEF', 'BMR', 'EAT', 'NEAT'], correctAnswer: 1, explanation: 'BMR accounts for approximately 60–70% of total daily energy expenditure.' },
    { type: 'multiple_choice', question: 'Which macronutrient has the highest thermic effect?', options: ['Protein', 'Carbohydrate', 'Alcohol', 'Fat'], correctAnswer: 0, explanation: 'Protein has the highest TEF at 20–30%, meaning more calories are burned digesting it.' },
    { type: 'multiple_choice', question: 'What is a diet break?', options: ['Stopping your diet permanently', 'Skipping meals for a day', 'Fasting for 48 hours', 'A planned 1–2 week period eating at maintenance calories'], correctAnswer: 3, explanation: 'Diet breaks are planned periods at maintenance to partially restore hormonal balance.' },
    { type: 'multiple_choice', question: 'NEAT can decrease by how many calories during a deficit?', options: ['10–20', '50–100', '200–400', '1000+'], correctAnswer: 2, explanation: 'NEAT can unconsciously decrease by 200–400 calories during caloric restriction.' },
    { type: 'multiple_choice', question: 'Is "metabolic damage" a scientifically supported concept?', options: ['No, metabolism never changes', 'No, adaptive thermogenesis is real but partially reverses when calories are restored', 'Yes, but only from keto diets', 'Yes, diets permanently break your metabolism'], correctAnswer: 1, explanation: '"Metabolic damage" has no scientific basis. Adaptive thermogenesis is real but partially reversible.' },
    { type: 'multiple_choice', question: 'Exercise activity thermogenesis (EAT) typically accounts for what percentage of TDEE?', options: ['5–10%', '70–80%', '50–60%', '30–40%'], correctAnswer: 0, explanation: 'Despite feeling important, EAT typically accounts for only 5–10% of total expenditure.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'When should a pre-training meal ideally be consumed?', options: ['The night before', 'Immediately before', '6 hours before', '2–3 hours before'], correctAnswer: 3, explanation: 'A balanced pre-training meal 2–3 hours before provides adequate fuel and digestion time.' },
    { type: 'multiple_choice', question: 'For sessions under 60 minutes, what intra-training nutrition is needed?', options: ['60g carbs per hour', '90g carbs per hour', 'Water only', '30g carbs per hour'], correctAnswer: 2, explanation: 'For moderate-intensity sessions under 60 minutes, water alone is sufficient.' },
    { type: 'multiple_choice', question: 'What does carbohydrate periodisation mean?', options: ['Never eating carbs', 'Matching carb intake to training demands day-by-day', 'Eliminating carbs for a week then loading', 'Eating carbs only at night'], correctAnswer: 1, explanation: 'Carbohydrate periodisation means eating more carbs on heavy training days and fewer on rest days.' },
    { type: 'multiple_choice', question: 'How much carbohydrate per kg is recommended on a heavy training day?', options: ['4–7g/kg', '0–1g/kg', '10–15g/kg', '2–3g/kg'], correctAnswer: 0, explanation: '4–7g carbohydrate per kilogram body weight on heavy training days.' },
    { type: 'multiple_choice', question: 'How urgently do you need to eat protein after training?', options: ['Within 5 minutes or gains are lost', 'It does not matter at all', 'Within 30 seconds', 'Within 1–2 hours is ideal but not urgent if you ate before training'], correctAnswer: 3, explanation: 'Within 1–2 hours is ideal, but urgency depends on pre-training nutrition and next session timing.' },
    { type: 'multiple_choice', question: 'During carbohydrate periodisation, which macronutrient stays constant?', options: ['Carbohydrate', 'All macros change equally', 'Protein', 'Fat only'], correctAnswer: 2, explanation: 'Protein and fat remain relatively constant; carbohydrate varies based on training demand.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'How many calories per gram does alcohol provide?', options: ['4', '7', '0', '9'], correctAnswer: 1, explanation: 'Alcohol provides 7 calories per gram.' },
    { type: 'multiple_choice', question: 'What happens to fat oxidation when you consume alcohol?', options: ['It is suppressed until alcohol is processed', 'It is unaffected', 'It doubles', 'It increases'], correctAnswer: 0, explanation: 'The body prioritises alcohol metabolism, suppressing fat oxidation until processing is complete.' },
    { type: 'multiple_choice', question: 'How does alcohol affect sleep?', options: ['Only affects sleep if consumed after midnight', 'Has no effect on sleep', 'Improves all sleep phases', 'Reduces REM and deep sleep phases'], correctAnswer: 3, explanation: 'Alcohol disrupts sleep architecture, particularly reducing REM and deep sleep.' },
    { type: 'multiple_choice', question: 'When is the best time to consume alcohol if you choose to drink?', options: ['Immediately after training', 'Before training for confidence', 'On rest days, separated from training by 4–6 hours', 'During training'], correctAnswer: 2, explanation: 'Rest days with at least 4–6 hours separation from any training window minimises impact.' },
    { type: 'multiple_choice', question: 'How many calories do four pints of lager approximately add?', options: ['400', '800', '1500', '200'], correctAnswer: 1, explanation: 'Four pints of lager adds approximately 800 calories — equivalent to a full meal.' },
    { type: 'multiple_choice', question: 'Alcohol acts as what type of substance regarding fluid balance?', options: ['Diuretic', 'Hydrating agent', 'Electrolyte', 'Neutral'], correctAnswer: 0, explanation: 'Alcohol is a diuretic — it inhibits ADH, promoting fluid loss and potential dehydration.' },
  ]),
];

// Unit 2 chapter quizzes
