import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const sportCricketUnit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What forces does fast bowling generate through the lower limbs?', options: ['1-2x bodyweight', '3-4x bodyweight', '5-10x bodyweight', '20x bodyweight'], correctAnswer: 2, explanation: 'Fast bowling generates 5-10x bodyweight forces during delivery.' },
    { type: 'multiple_choice', question: 'How fast does a cricket ball travel from a fast bowler?', options: ['50-80 km/h', '90-120 km/h', '140+ km/h', '200+ km/h'], correctAnswer: 2, explanation: 'Fast bowling delivers at 140+ km/h.' },
    { type: 'multiple_choice', question: 'What has T20 cricket changed about physical demands?', options: ['Nothing', 'Increased demands for explosive athleticism, power hitting, and athletic fielding', 'Reduced physical demands', 'Only changed batting'], correctAnswer: 1, explanation: 'T20 has moved cricket toward higher-intensity athletic demands.' },
    { type: 'multiple_choice', question: 'How many balls might a fast bowler deliver in a Test match day?', options: ['10-20', '50-80', '120-150', '300+'], correctAnswer: 2, explanation: '120-150 deliveries across 20-30 overs.' },
    { type: 'multiple_choice', question: 'What is the most underrated batting demand?', options: ['Power', 'Speed', 'Mental concentration across an innings', 'Flexibility'], correctAnswer: 2, explanation: 'Sustained concentration over hours is the most overlooked demand.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is the primary strength quality for batters?', options: ['Arm strength', 'Rotational power through the kinetic chain', 'Grip strength alone', 'Calf strength'], correctAnswer: 1, explanation: 'Rotational power drives all cricket shots.' },
    { type: 'multiple_choice', question: 'What correlates with bowling speed?', options: ['Height alone', 'Single-leg strength, trunk rotation power, and upper-body strength', 'Arm length', 'Run-up distance'], correctAnswer: 1, explanation: 'Multiple strength qualities contribute to bowling velocity.' },
    { type: 'multiple_choice', question: 'Why should fast bowlers have balanced bilateral leg strength?', options: ['Appearance', 'Asymmetries between landing and drive legs increase injury risk', 'Rules require it', 'It does not matter'], correctAnswer: 1, explanation: 'Leg strength imbalances increase bowling-related injury risk.' },
    { type: 'multiple_choice', question: 'What exercises develop cricket-specific hitting power?', options: ['Bicep curls', 'Medicine ball rotational throws, cable woodchops, and landmine rotations', 'Leg extensions', 'Sit-ups'], correctAnswer: 1, explanation: 'Rotational exercises mirror the kinetic chain of cricket shots.' },
    { type: 'multiple_choice', question: 'How many gym sessions per week in-season?', options: ['None', '1-2 maintenance sessions', '5 sessions', 'Daily'], correctAnswer: 1, explanation: '1-2 sessions maintain strength without compromising cricket training.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What does bowler run-up speed correlate with?', options: ['Accuracy', 'Bowling velocity — faster run-up equals more kinetic energy', 'Economy rate', 'Fielding ability'], correctAnswer: 1, explanation: 'Run-up speed directly contributes to ball velocity.' },
    { type: 'multiple_choice', question: 'How much time can efficient turning save per run?', options: ['No time saved', '0.3-0.5 seconds', '2-3 seconds', '5+ seconds'], correctAnswer: 1, explanation: 'Efficient turning technique saves 0.3-0.5 seconds per run.' },
    { type: 'multiple_choice', question: 'What type of agility is most important for fielding?', options: ['Pre-planned agility', 'Reactive agility — responding to unpredictable ball off the bat', 'Flexibility', 'Balance only'], correctAnswer: 1, explanation: 'Fielders must react to the shot, not follow pre-planned patterns.' },
    { type: 'multiple_choice', question: 'Why is speed endurance important in long-format cricket?', options: ['It is not needed', 'Fielders must maintain sprint quality across 6+ hours of play', 'Only bowlers need it', 'Tests do not require sprinting'], correctAnswer: 1, explanation: 'Long-format cricket demands maintained intensity across a full day.' },
    { type: 'multiple_choice', question: 'What is the length of the cricket pitch?', options: ['10m', '17.68 metres', '22m', '30m'], correctAnswer: 1, explanation: 'The cricket pitch is 17.68 metres (1 chain / 22 yards).' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What VO2max should cricketers target?', options: ['30-35 mL/kg/min', '45-55 mL/kg/min', '70+ mL/kg/min', '80+ mL/kg/min'], correctAnswer: 1, explanation: '45-55 mL/kg/min supports all formats.' },
    { type: 'multiple_choice', question: 'How should fast bowler conditioning be structured?', options: ['Long-distance running', 'Repeat sprints mimicking over patterns — 6x 25-30m with 30s rest, multiple sets', 'Only bowling in nets', 'Cycling'], correctAnswer: 1, explanation: 'Sprint patterns mimic the run-up and recovery cycle of bowling overs.' },
    { type: 'multiple_choice', question: 'Why is fielding fitness described as military-style readiness?', options: ['Military training is used', 'Fielders must go from rest to maximum effort instantly, repeatedly, across hours', 'It sounds tough', 'No connection'], correctAnswer: 1, explanation: 'Explosive readiness after prolonged inactivity mirrors military demands.' },
    { type: 'multiple_choice', question: 'How long does heat acclimation take?', options: ['1 day', '3-5 days', '10-14 days', '1 month'], correctAnswer: 2, explanation: '10-14 days of exercise in hot conditions.' },
    { type: 'multiple_choice', question: 'What serves dual purpose as batting conditioning?', options: ['Gym work', 'Extended batting practice at match intensity (60-90min nets)', 'Swimming', 'Cycling'], correctAnswer: 1, explanation: 'Long net sessions develop both skill and endurance simultaneously.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What percentage of young fast bowlers suffer lumbar stress fractures?', options: ['1-5%', '5-10%', '15-25%', '50%+'], correctAnswer: 2, explanation: '15-25% of young fast bowlers are affected.' },
    { type: 'multiple_choice', question: 'What is the maximum weekly bowling workload increase?', options: ['50%', 'No more than 20%', '100%', 'No limit'], correctAnswer: 1, explanation: 'Never increase weekly balls by more than 20%.' },
    { type: 'multiple_choice', question: 'How do Nordic curls benefit cricketers?', options: ['They improve bowling speed', 'They reduce hamstring injury rates by up to 50%', 'They only help fielders', 'No benefit'], correctAnswer: 1, explanation: 'Nordic curls are the most effective hamstring injury prevention tool.' },
    { type: 'multiple_choice', question: 'What minimum rest is needed between full bowling sessions?', options: ['12 hours', '24 hours', '48 hours minimum', '1 week'], correctAnswer: 2, explanation: '48 hours allows recovery from bowling forces.' },
    { type: 'multiple_choice', question: 'Why do hamstring injuries occur in matches but not training?', options: ['Bad luck', 'Players sprint infrequently in training but are required to sprint maximally in matches', 'Match balls are different', 'Pitch conditions'], correctAnswer: 1, explanation: 'Insufficient sprint exposure in training creates vulnerability in match situations.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What daily calorie expenditure do fast bowlers face during Test matches?', options: ['1,500-2,000', '2,500-3,000', '4,000-4,500+', '6,000+'], correctAnswer: 2, explanation: 'Fast bowlers can expend 4,500+ kcal during a Test match day.' },
    { type: 'multiple_choice', question: 'When should carbohydrate be consumed during long bowling spells?', options: ['Only at lunch', 'At the end of overs using gels, sports drinks, or bananas', 'Never during play', 'Only between innings'], correctAnswer: 1, explanation: 'Quick carb sources at over-ends maintain energy.' },
    { type: 'multiple_choice', question: 'What sweat rates are possible in hot cricket conditions?', options: ['Less than 500mL/hour', '1-3 litres per hour', '5+ litres per hour', 'Sweating does not occur'], correctAnswer: 1, explanation: '1-3L/hour in hot Australian, Indian, or Caribbean conditions.' },
    { type: 'multiple_choice', question: 'What protein intake should fast bowlers target?', options: ['0.8g/kg', '1.2g/kg', '1.4-2.0g/kg (higher end)', '4.0g/kg'], correctAnswer: 2, explanation: 'Higher protein supports recovery from bowling-related muscle damage.' },
    { type: 'multiple_choice', question: 'Why is caffeine particularly valuable in cricket?', options: ['It improves bowling speed', 'It helps maintain concentration during long batting innings and bowling spells', 'It reduces injury risk', 'It has no value in cricket'], correctAnswer: 1, explanation: 'Sustained concentration is a critical performance factor in cricket.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'What is the foundational mental skill in cricket?', options: ['Aggression', 'Concentration management — sustained selective attention with structured resets', 'Positive thinking only', 'Ignoring pressure'], correctAnswer: 1, explanation: 'Cricket demands sustained concentration with deliberate recovery between deliveries.' },
    { type: 'multiple_choice', question: 'How is pressure in cricket generated?', options: ['By the opposition', 'Self-generated through outcome thinking', 'By the crowd only', 'By the pitch conditions'], correctAnswer: 1, explanation: 'Pressure comes from focusing on outcomes rather than processes.' },
    { type: 'multiple_choice', question: 'What should post-dismissal analysis focus on?', options: ['Emotional venting', 'Technical observations — what went wrong mechanically, not emotionally', 'Blaming conditions', 'Nothing — forget it'], correctAnswer: 1, explanation: 'Technical analysis builds learning; emotional reactions build frustration.' },
    { type: 'multiple_choice', question: 'What makes great cricket captains?', options: ['Just being the best player', 'Thinking 2-3 overs ahead while managing the present moment', 'Bowling the most overs', 'Being the most aggressive'], correctAnswer: 1, explanation: 'Proactive tactical thinking combined with present-moment management.' },
    { type: 'multiple_choice', question: 'How specific should cricket visualization be?', options: ['Very general and vague', 'Highly specific — facing particular deliveries, executing specific skills', 'Only visualize success', 'Visualization does not work for cricket'], correctAnswer: 1, explanation: 'Specific visualization prepares neural pathways for specific execution.' },
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'Why must the off-season include a complete break from cricket?', options: ['It is not necessary', 'Body and mind need recovery from the cumulative demands of a season', 'Coaches require it', 'Players lose skills if they practice'], correctAnswer: 1, explanation: 'Complete recovery prevents accumulated physical and mental fatigue.' },
    { type: 'multiple_choice', question: 'What is the most critical workload management rule for fast bowlers?', options: ['Bowl as much as possible', 'Never jump from zero to full match bowling — progressive loading', 'Only bowl in matches', 'No restrictions needed'], correctAnswer: 1, explanation: 'Progressive loading prevents the injury spikes from sudden workload increases.' },
    { type: 'multiple_choice', question: 'What is the minimum rest between multi-day games for fast bowlers?', options: ['1 day', '2 days', '4 days minimum', '1 week'], correctAnswer: 2, explanation: '4 days allows recovery from the accumulated bowling forces.' },
    { type: 'multiple_choice', question: 'How should the season build toward a final or key series?', options: ['Maximum intensity throughout', 'Plan backward — reduce volume in preceding weeks to arrive fresh and sharp', 'Ignore the schedule', 'Rest completely for 2 weeks before'], correctAnswer: 1, explanation: 'Strategic planning ensures peak readiness for the most important matches.' },
    { type: 'multiple_choice', question: 'How many gym sessions per week during the cricket season?', options: ['None', '1-2 maintenance sessions', '5 sessions', 'Daily'], correctAnswer: 1, explanation: '1-2 sessions maintain physical qualities around the match schedule.' },
  ]),
];