import type { UnitAssessment } from '../types';

export const mindsetL4Unit4Assessment: UnitAssessment = {
  unitNumber: 4,
  title: 'Applied Psychology & Professional Practice — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'A client knows what to eat and wants to change, but works 12-hour shifts with no time to cook. Using COM-B, what is the primary barrier?', options: ['Capability', 'Motivation', 'Opportunity — their environment doesn\'t support the behaviour', 'All three equally'], correctAnswer: 2, explanation: 'They have knowledge (capability) and desire (motivation) but their environment prevents the behaviour. Address the opportunity barrier.' },
    { type: 'multiple_choice', question: 'What are the three basic psychological needs in Self-Determination Theory?', options: ['Safety, belonging, esteem', 'Autonomy, competence, relatedness', 'Power, achievement, affiliation', 'Knowledge, skill, motivation'], correctAnswer: 1, explanation: 'SDT: Autonomy (choice and self-direction), Competence (feeling effective), Relatedness (feeling connected). All three sustain intrinsic motivation.' },
    { type: 'multiple_choice', question: 'What is the single strongest predictor of resilient outcomes?', options: ['Financial security', 'Strong social support', 'Physical fitness', 'Intelligence'], correctAnswer: 1, explanation: 'Social support is consistently the most powerful predictor of resilience across all types of adversity. Invest in relationships before crises.' },
    { type: 'scenario', question: 'Which PERMA pillar needs attention?', scenario: 'A client exercises regularly, earns good money, and has hobbies they enjoy, but says life feels "pointless." They can\'t articulate why they feel empty.', options: ['Positive Emotions', 'Engagement', 'Meaning — they lack connection to something bigger than themselves', 'Accomplishment'], correctAnswer: 2, explanation: 'The "pointless" feeling despite success typically indicates a Meaning deficit — Accomplishment without Purpose. Connecting to a cause or values would help.' },
    { type: 'multiple_choice', question: 'What is the fastest evidence-based technique for acute stress reduction?', options: ['Deep thinking', 'The physiological sigh — two quick inhales through the nose, one long exhale through the mouth', 'Counting to 10', 'Cold water on the face'], correctAnswer: 1, explanation: 'The physiological sigh activates the parasympathetic nervous system within seconds — the fastest evidence-based technique for in-the-moment stress reduction.' },
    { type: 'multiple_choice', question: 'Why is identity-based change more durable than goal-based change?', options: ['It isn\'t', 'Goals have endpoints; identity is ongoing — "I am someone who trains" sustains behaviour indefinitely', 'Goals are always better', 'Identity change is too difficult'], correctAnswer: 1, explanation: '"Lose 10kg" ends when achieved. "I am someone who takes care of their body" never ends. Identity drives behaviour automatically.' },
    { type: 'multiple_choice', question: 'What are the four core ethical principles in helping professions?', options: ['Speed, quality, cost, value', 'Beneficence, non-maleficence, autonomy, justice', 'Honesty, loyalty, courage, integrity', 'Empathy, skill, knowledge, practice'], correctAnswer: 1, explanation: 'Do good (beneficence), do no harm (non-maleficence), respect choices (autonomy), treat fairly (justice). These resolve most ethical dilemmas.' },
    { type: 'multiple_choice', question: 'What does Locke and Latham\'s goal-setting research conclude?', options: ['Easy goals are best', 'Specific, difficult goals produce higher performance than vague or easy goals', 'Goals don\'t affect performance', 'Only outcome goals matter'], correctAnswer: 1, explanation: 'Across 1,000+ studies: specific, challenging goals consistently outperform "do your best" instructions. One of psychology\'s most replicated findings.' },
    { type: 'multiple_choice', question: 'What is the key message about integrating multiple psychological frameworks?', options: ['One framework is sufficient', 'Multiple frameworks provide more accurate assessment and more effective intervention than any single approach', 'Integration creates confusion', 'Only clinical frameworks matter'], correctAnswer: 1, explanation: 'A single framework misses what others would catch. Integration means seeing a client through multiple lenses for better diagnosis and intervention.' },
    { type: 'scenario', question: 'What is the most ethical response?', scenario: 'A client shares that they\'ve been skipping meals and exercising excessively. They dismiss your concern and say they\'re "just being disciplined."', options: ['Accept their explanation — they know their own body', 'Express genuine concern, note the specific behaviours you\'ve observed, and sensitively recommend they speak with their GP', 'Ignore it — it\'s not your role', 'Design a more structured meal plan'], correctAnswer: 1, explanation: 'Restrictive eating + excessive exercise are red flags for disordered eating. Express concern, note specific observations, and refer to a professional.' },
    { type: 'multiple_choice', question: 'What reframes "laziness" from a character flaw to a neurological state?', options: ['Nothing — laziness is always a choice', 'Low dopaminergic activity — a neurochemical state influenced by sleep, exercise, overstimulation, and environment', 'Genetic predetermination', 'Personality type'], correctAnswer: 1, explanation: 'Low motivation is a low-dopamine state that can be addressed through exercise, sleep, cold exposure, and reducing dopamine-depleting stimuli.' },
    { type: 'multiple_choice', question: 'What should a personal development plan include?', options: ['Only certifications to pursue', 'Areas to deepen, skills to practise, resources to use, and a timeline for review', 'Only books to read', 'Only professional goals'], correctAnswer: 1, explanation: 'A complete PDP: what to learn, how to practise it, what resources to use, and when to review. Specific, actionable, and regularly updated.' },
  ],
};
