import type { UnitAssessment } from '../types';

export const mindsetL4Unit1Assessment: UnitAssessment = {
  unitNumber: 1,
  title: 'Clinical Psychology & Evidence-Based Interventions — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'A client says "I can\'t go to the gym because everyone will judge me." Which CBT distortion is most present?', options: ['Emotional reasoning', 'All-or-nothing thinking', 'Catastrophising', 'Mind reading'], correctAnswer: 3, explanation: 'Mind reading: assuming you know what others think without evidence.' },
    { type: 'multiple_choice', question: 'How does ACT\'s approach to negative thoughts differ from CBT\'s?', options: ['ACT changes the relationship with thoughts; CBT evaluates their accuracy', 'ACT suppresses them; CBT accepts them', 'They are identical', 'ACT ignores thoughts entirely'], correctAnswer: 0, explanation: 'CBT asks "Is this thought accurate?" ACT asks "Does engaging with this thought help me act on my values?"' },
    { type: 'multiple_choice', question: 'What is the key mechanism that maintains anxiety disorders?', options: ['Genetic predisposition', 'Avoidance — which prevents new learning and reinforces the threat perception', 'Chemical imbalance', 'Personality weakness'], correctAnswer: 1, explanation: 'Avoidance provides short-term relief but prevents the brain from learning that feared outcomes are unlikely or manageable.' },
    { type: 'multiple_choice', question: 'Why is Behavioural Activation effective for depression?', options: ['It only treats mild cases', 'Action precedes motivation — engagement in valued activities breaks the withdrawal cycle without requiring mood change first', 'It replaces medication', 'It forces people to be happy'], correctAnswer: 1, explanation: 'BA works outside-in: you don\'t need to feel motivated to benefit. Activity comes first; improved mood follows.' },
    { type: 'scenario', question: 'Using MI principles, what is the best response?', scenario: 'A client says: "I know I should eat better, but I just love takeaways. I can\'t give them up."', options: ['"You need to stop eating takeaways immediately"', '"It sounds like good food is important to you, and you also care about your health. What would a small step look like?"', '"That\'s why you\'re not getting results"', '"Just have willpower"'], correctAnswer: 1, explanation: 'This reflects both the sustain talk (loves takeaways) and change talk (should eat better), then evokes the client\'s own solution with an open question.' },
    { type: 'multiple_choice', question: 'What characterises post-traumatic growth?', options: ['Complete recovery', 'Positive psychological change that coexists with — not replaces — the pain of trauma', 'Forgetting the trauma', 'Denial of the experience'], correctAnswer: 1, explanation: 'PTG involves genuine positive change (stronger relationships, new possibilities) that coexists with ongoing pain — not toxic positivity.' },
    { type: 'multiple_choice', question: 'Which sleep intervention directly addresses the conditioned association between the bed and wakefulness?', options: ['White noise machines', 'Stimulus control — using the bed only for sleep', 'Melatonin supplements', 'Sleep restriction'], correctAnswer: 1, explanation: 'Stimulus control re-associates the bed with sleep by removing all waking activities from the bed environment.' },
    { type: 'multiple_choice', question: 'What does dopamine hijacking in addiction mean for treatment?', options: ['Addiction is incurable', 'The brain\'s reward system has been reorganised — recovery requires rewiring through new behaviours, not just willpower', 'Only medication works', 'Willpower is sufficient'], correctAnswer: 1, explanation: 'Addiction is a learned neural pattern. Recovery involves building new patterns through environmental change, new habits, and often professional support.' },
    { type: 'scenario', question: 'What is the most appropriate action?', scenario: 'During a coaching session, a client mentions they\'ve been having thoughts of self-harm. They say it casually.', options: ['Move on — they said it casually so it\'s probably not serious', 'Take it seriously: express concern, ask directly about their safety, and facilitate professional referral', 'Ignore it — it\'s outside your scope', 'Try to counsel them about it'], correctAnswer: 1, explanation: 'Suicidal ideation or self-harm should always be taken seriously regardless of delivery. Express concern, assess immediate risk, and refer appropriately.' },
    { type: 'multiple_choice', question: 'What connects CBT, ACT, MI, and BA as therapeutic approaches?', options: ['They all require medication', 'They are all the same approach', 'They all focus on the past', 'They are all evidence-based, targeting different aspects of psychological change: thoughts, flexibility, motivation, and behaviour'], correctAnswer: 3, explanation: 'Each addresses a different lever of change: CBT (thoughts), ACT (relationship with thoughts), MI (motivation), BA (behaviour). Together they cover the full spectrum.' },
    { type: 'multiple_choice', question: 'What is the non-clinician\'s role when encountering mental health issues?', options: ['Diagnose and treat', 'Recognise signs, create safety, provide support, and facilitate referral to qualified professionals', 'Ignore — it\'s not their responsibility', 'Only discuss physical health'], correctAnswer: 1, explanation: 'Recognise, support, refer — this is the appropriate scope. It\'s powerful and important without requiring clinical training.' },
    { type: 'multiple_choice', question: 'Why is circadian rhythm alignment important for mental health?', options: ['It isn\'t', 'Disrupted circadian rhythms are linked to depression, anxiety, and cognitive decline — alignment supports all neurochemical systems', 'Only physical health is affected', 'It only matters for shift workers'], correctAnswer: 1, explanation: 'Circadian disruption affects serotonin, dopamine, cortisol, and melatonin — all critical for mental health. Morning light and consistent wake times are protective.' },
  ],
};
