import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL4Unit2ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: Neuroplasticity
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What is neuroplasticity?', options: ['The brain\'s fixed structure', 'The brain\'s ability to reorganise itself based on experience', 'A type of brain injury', 'Genetic brain development'], correctAnswer: 1, explanation: 'Neuroplasticity is the brain\'s capacity to form new neural connections and reorganise existing ones in response to experience.' },
    { type: 'multiple_choice', question: 'What does Hebb\'s Law state?', options: ['Neurons compete for resources', 'Neurons that fire together wire together', 'The brain cannot change after age 25', 'Neural connections are fixed at birth'], correctAnswer: 1, explanation: 'Hebb\'s Law: repeated co-activation of neurons strengthens their connection — the foundation of learning and skill development.' },
    { type: 'multiple_choice', question: 'What is the role of myelin in skill development?', options: ['It provides energy to neurons', 'It insulates nerve fibres, increasing signal speed up to 100x', 'It destroys unused connections', 'It stores memories'], correctAnswer: 1, explanation: 'Myelin wraps around frequently used nerve fibres, dramatically increasing signal speed and efficiency — the biological basis of skill.' },
    { type: 'multiple_choice', question: 'Which type of practice triggers the most neuroplastic change?', options: ['Mindless repetition', 'Focused, attentive practice at the edge of ability', 'Easy, comfortable practice', 'Infrequent high-intensity sessions'], correctAnswer: 1, explanation: 'Neuroplasticity requires focused attention and appropriate challenge — distracted or too-easy practice doesn\'t trigger the same neural changes.' },
    { type: 'multiple_choice', question: 'Why is sleep critical for learning?', options: ['It isn\'t — learning happens during practice only', 'Memory consolidation occurs during deep sleep and REM sleep', 'Sleep only helps physical recovery', 'Sleep erases unused memories'], correctAnswer: 1, explanation: 'During sleep, the brain consolidates new learning — transferring it from short-term to long-term storage and strengthening neural pathways.' },
    { type: 'multiple_choice', question: 'What is BDNF and why does it matter?', options: ['A supplement brand', 'Brain-Derived Neurotrophic Factor — a protein that promotes neuronal growth, released during exercise', 'A brain scanning technique', 'A type of neurotransmitter'], correctAnswer: 1, explanation: 'BDNF is released during exercise and promotes neuronal growth and survival — exercise literally fertilises the brain for learning.' },
    { type: 'multiple_choice', question: 'How long should focused practice blocks typically last?', options: ['15 minutes', '60-90 minutes with breaks between blocks', '4+ hours continuously', 'It doesn\'t matter'], correctAnswer: 1, explanation: 'The brain sustains focused attention optimally in 60-90 minute blocks (ultradian rhythm) — breaks between blocks are essential for consolidation.' },
    { type: 'multiple_choice', question: 'Why does novelty enhance neuroplastic change?', options: ['It doesn\'t', 'New challenges activate more widespread neural circuits and trigger greater adaptive responses than familiar tasks', 'Novelty is only entertaining', 'The brain prefers routine'], correctAnswer: 1, explanation: 'Novel stimuli demand new neural solutions, driving more plastic change than repeating familiar patterns.' },
    { type: 'scenario', question: 'What is the neuroplasticity-based explanation?', scenario: 'A guitar player practises the same song for 3 hours straight with the TV on in the background. Despite the long practice time, they don\'t improve much.', options: ['They need a better guitar', 'Distracted, extended practice doesn\'t trigger the focused attention needed for myelination and neuroplastic change', 'They lack talent', 'Three hours isn\'t enough'], correctAnswer: 1, explanation: 'Neuroplasticity requires focused attention. Distracted practice and sessions longer than 90 minutes without breaks produce diminishing neural returns.' },
    { type: 'multiple_choice', question: 'What is the "first 20 hours" principle?', options: ['You need 20 hours of sleep to learn', 'The first 20 hours of focused, deliberate practice produce disproportionate improvement in any skill', 'Learning takes exactly 20 hours', '20 hours is the minimum for any skill'], correctAnswer: 1, explanation: 'The initial 20 hours of deliberate practice show the steepest learning curve — the brain makes its biggest structural changes early in skill acquisition.' },
  ]),

  // Chapter 2: Neurotransmitters
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What does dopamine primarily signal?', options: ['Pleasure and happiness', 'Motivation, reward anticipation, and willingness to exert effort', 'Relaxation and calm', 'Sleep readiness'], correctAnswer: 1, explanation: 'Dopamine drives motivation and the prediction of reward — it\'s about pursuit, not pleasure itself.' },
    { type: 'multiple_choice', question: 'Where is 95% of serotonin produced?', options: ['The brain', 'The gut', 'The heart', 'The muscles'], correctAnswer: 1, explanation: '95% of serotonin is synthesised in the gut, highlighting the gut-brain connection in mood regulation.' },
    { type: 'multiple_choice', question: 'Which neurotransmitter is the brain\'s primary inhibitory messenger?', options: ['Dopamine', 'Norepinephrine', 'GABA', 'Acetylcholine'], correctAnswer: 2, explanation: 'GABA is the brain\'s main inhibitory neurotransmitter — the "brakes" that promote calm, reduce anxiety, and enable sleep.' },
    { type: 'multiple_choice', question: 'How does cold exposure affect dopamine?', options: ['It has no effect', 'It increases dopamine by 250-300% for several hours', 'It depletes dopamine', 'It only affects serotonin'], correctAnswer: 1, explanation: 'Cold exposure (e.g., 1-3 minute cold shower) produces a significant, sustained dopamine increase — one of the most reliable natural dopamine boosters.' },
    { type: 'multiple_choice', question: 'What does norepinephrine (noradrenaline) drive?', options: ['Sleep and relaxation', 'Alertness, focus, and the "pay attention" signal', 'Digestion', 'Muscle contraction'], correctAnswer: 1, explanation: 'Norepinephrine drives alertness and focused attention. Moderate levels sharpen performance; excessive levels create anxiety.' },
    { type: 'multiple_choice', question: 'What happens when dopamine is chronically elevated by excessive stimulation?', options: ['Permanent happiness', 'Tolerance develops — the baseline drops, making normal pleasures feel flat', 'No effect', 'Better performance'], correctAnswer: 1, explanation: 'Chronic dopamine elevation (social media, constant novelty) creates tolerance — the reward threshold rises and natural rewards feel insufficient.' },
    { type: 'multiple_choice', question: 'Which neurotransmitter is most associated with focused attention and learning?', options: ['Serotonin', 'GABA', 'Acetylcholine', 'Dopamine'], correctAnswer: 2, explanation: 'Acetylcholine is released when you deliberately focus on something novel or challenging — it drives the attention required for learning.' },
    { type: 'multiple_choice', question: 'What are the four pillars of neurotransmitter health?', options: ['Supplements, sleep, therapy, meditation', 'Regular exercise, adequate sleep, morning sunlight, and social connection', 'Diet, hydration, stretching, rest', 'Coffee, protein, creatine, multivitamins'], correctAnswer: 1, explanation: 'The four foundational behaviours for healthy neurochemistry are exercise, sleep, morning light, and social connection — get these right before anything else.' },
    { type: 'scenario', question: 'What neurotransmitter system is most likely depleted?', scenario: 'A person feels constantly unmotivated, can\'t start tasks, and finds no excitement in activities they used to enjoy. They spend hours scrolling social media and snacking.', options: ['Serotonin', 'GABA', 'Dopamine — chronic overstimulation has created tolerance and baseline depletion', 'Acetylcholine'], correctAnswer: 2, explanation: 'The pattern suggests dopamine depletion from chronic overstimulation — excessive easy rewards (scrolling, snacking) have raised the reward threshold.' },
    { type: 'multiple_choice', question: 'How does exercise affect neurotransmitter systems?', options: ['It only affects endorphins', 'It increases dopamine, serotonin, norepinephrine, and BDNF simultaneously', 'It depletes all neurotransmitters', 'It only works for athletes'], correctAnswer: 1, explanation: 'Exercise is the broadest-spectrum neurotransmitter intervention available — it positively affects dopamine, serotonin, norepinephrine, endorphins, and BDNF.' },
  ]),

  // Chapter 3: Chronobiology
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What is the strongest correlate of physical performance across the day?', options: ['Motivation level', 'Core body temperature', 'Caffeine intake', 'Sleep quality'], correctAnswer: 1, explanation: 'Strength, power, flexibility, and reaction time all correlate closely with core body temperature, which peaks in the late afternoon.' },
    { type: 'multiple_choice', question: 'What is chronotype?', options: ['How long you sleep', 'Your natural preference for morning or evening activity, largely determined by genetics', 'How fast you recover from jet lag', 'Your favourite time to eat'], correctAnswer: 1, explanation: 'Chronotype is approximately 50% genetic — morning larks and night owls have genuinely different circadian biology.' },
    { type: 'multiple_choice', question: 'When do most people experience peak cognitive performance?', options: ['Immediately after waking', 'Late morning to early afternoon (varies by chronotype)', 'Late evening', 'It doesn\'t vary across the day'], correctAnswer: 1, explanation: 'Cognitive performance typically peaks in the late morning for morning types and shifts later for evening types, roughly 2-4 hours after waking.' },
    { type: 'multiple_choice', question: 'What is the cortisol awakening response?', options: ['Feeling stressed when waking', 'A natural cortisol peak 30-45 minutes after waking that promotes alertness', 'A sign of chronic stress', 'An abnormal hormonal pattern'], correctAnswer: 1, explanation: 'The cortisol awakening response is normal and healthy — it peaks alertness shortly after waking to prepare you for the day.' },
    { type: 'multiple_choice', question: 'Why might the afternoon be good for creative work?', options: ['You\'re more alert then', 'Reduced inhibition during the slight afternoon dip can boost creative thinking', 'There are fewer distractions', 'It isn\'t — only morning works'], correctAnswer: 1, explanation: 'The mild afternoon arousal dip reduces analytical control, which can actually enhance creative and divergent thinking.' },
    { type: 'multiple_choice', question: 'When are most athletic world records set?', options: ['Morning', 'Late afternoon / early evening (when core temperature peaks)', 'Night', 'Time doesn\'t matter'], correctAnswer: 1, explanation: 'Most world records are set in the late afternoon/early evening — when core temperature, strength, power, and reaction time peak.' },
    { type: 'multiple_choice', question: 'What is the best way to adapt to training at a non-optimal time?', options: ['Just push through', 'Consistently train at that time, use pre-training light/caffeine, and do a thorough warm-up', 'It\'s impossible to adapt', 'Take performance-enhancing supplements'], correctAnswer: 1, explanation: 'The body partially adapts to regular training times. Pre-training light exposure, caffeine, and warm-ups can compensate for circadian misalignment.' },
    { type: 'scenario', question: 'Based on chronobiology, what would you recommend?', scenario: 'A night owl is forcing themselves to train at 6am because they believe morning workouts are "more disciplined." They feel sluggish, perform poorly, and dread every session.', options: ['Keep going — discipline matters more than biology', 'Train at a time that aligns with their chronotype — late afternoon/evening — where they\'ll perform better and enjoy it more', 'Train at midnight', 'Stop training until they become a morning person'], correctAnswer: 1, explanation: 'Chronotype is largely genetic. Training at 6am when your biology peaks at 6pm is fighting your hardware. Align training with your chronotype for better performance and adherence.' },
    { type: 'multiple_choice', question: 'What happens to the circadian clock without morning light anchoring?', options: ['It stays perfectly aligned', 'It drifts later each day because the natural clock runs slightly longer than 24 hours', 'It shifts earlier', 'Nothing changes'], correctAnswer: 1, explanation: 'Most people\'s internal clocks run slightly longer than 24 hours. Without morning light to reset, the clock drifts later — explaining why free-running schedules shift toward later bedtimes.' },
    { type: 'multiple_choice', question: 'What should you protect in the 90 minutes before sleep?', options: ['Your workout routine', 'Avoid intense activity and bright light — both signal wakefulness to the circadian system', 'Your screen time', 'Nothing — evening activities don\'t affect sleep'], correctAnswer: 1, explanation: 'The 90-minute pre-sleep window should be protected from bright light and intense activity — both suppress melatonin and signal alertness.' },
  ]),

  // Chapter 4: Decision-Making Under Pressure
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What is System 1 thinking?', options: ['Deliberate and analytical', 'Fast, automatic, and intuitive', 'Only used for complex problems', 'Slow and effortful'], correctAnswer: 1, explanation: 'System 1 is the brain\'s fast, automatic mode — it handles most daily decisions without conscious effort but is prone to cognitive biases.' },
    { type: 'multiple_choice', question: 'What happens to decision quality under high stress?', options: ['It improves because stress sharpens focus', 'It deteriorates — people default to familiar responses and struggle to consider alternatives', 'Stress has no effect on decisions', 'Only physical decisions are affected'], correctAnswer: 1, explanation: 'High stress impairs the prefrontal cortex, causing people to default to familiar (possibly inappropriate) responses and reducing ability to evaluate options.' },
    { type: 'multiple_choice', question: 'What does HALT stand for?', options: ['Help, Assess, Learn, Try', 'Hungry, Angry, Lonely, Tired', 'Hold, Adjust, Limit, Think', 'High, Alert, Logical, Tough'], correctAnswer: 1, explanation: 'HALT: Never make important decisions when Hungry, Angry, Lonely, or Tired — these states compromise prefrontal function.' },
    { type: 'multiple_choice', question: 'What is the inverted-U arousal model (Yerkes-Dodson)?', options: ['More arousal always improves performance', 'Moderate arousal optimises performance; too little or too much degrades it', 'Low arousal is always best', 'Arousal is irrelevant to performance'], correctAnswer: 1, explanation: 'The Yerkes-Dodson law: performance peaks at moderate arousal. Under-arousal produces boredom; over-arousal produces anxiety and errors.' },
    { type: 'multiple_choice', question: 'What is a "bright line" rule?', options: ['A rule about lighting', 'A clear, binary boundary that requires no deliberation — removing the decision from the moment', 'A flexible guideline', 'A competition standard'], correctAnswer: 1, explanation: 'Bright line rules are unambiguous: "I don\'t drink on weeknights" requires no decision. "I try to limit drinking" requires a decision every time.' },
    { type: 'multiple_choice', question: 'Which brain region is most impaired by stress hormones?', options: ['Amygdala', 'Cerebellum', 'Prefrontal cortex', 'Brain stem'], correctAnswer: 2, explanation: 'The prefrontal cortex — responsible for executive function, planning, and impulse control — is the first region impaired by cortisol.' },
    { type: 'multiple_choice', question: 'What is pre-commitment?', options: ['Making a promise you can\'t keep', 'Deciding in advance (when calm) to remove real-time decision-making from compromised states', 'Committing to a gym membership', 'Planning your day in the morning'], correctAnswer: 1, explanation: 'Pre-commitment locks in good decisions before you enter states where you might decide badly — meal prep, training schedules, financial rules.' },
    { type: 'multiple_choice', question: 'What is the 10-10-10 rule?', options: ['Train 10 minutes, 10 times, 10 days', 'How will I feel about this decision in 10 minutes, 10 months, and 10 years?', 'Do 10 of everything', 'Rate 10 options on a 10-point scale'], correctAnswer: 1, explanation: 'The 10-10-10 rule creates temporal distance — helping evaluate whether a decision serves long-term interests, not just immediate impulses.' },
    { type: 'scenario', question: 'What principle does this demonstrate?', scenario: 'An athlete who meal-preps every Sunday consistently eats well, while one who decides meal-by-meal based on how they feel tends to choose junk food.', options: ['The first athlete has more willpower', 'Pre-commitment (deciding when calm) beats mood-dependent decisions', 'The second athlete needs better nutrition education', 'Meal prep is inconvenient'], correctAnswer: 1, explanation: 'Meal-prepping is a pre-commitment strategy — the decision was made in a calm state, removing the need for real-time willpower when tired or hungry.' },
    { type: 'multiple_choice', question: 'What is stress inoculation?', options: ['Avoiding all stress', 'Deliberately practising under simulated pressure to build tolerance and competence', 'Taking supplements for stress', 'Stress vaccination'], correctAnswer: 1, explanation: 'Stress inoculation exposes you to controlled stress in practice, building the skills and tolerance needed for real high-pressure situations.' },
  ]),

  // Chapter 5: Attention & Deep Work
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What are the three attention networks?', options: ['Focus, memory, creativity', 'Alerting, orienting, and executive attention', 'Short, medium, long', 'Visual, auditory, kinaesthetic'], correctAnswer: 1, explanation: 'The three networks: Alerting (general readiness), Orienting (directing attention), and Executive (managing focus and conflict).' },
    { type: 'multiple_choice', question: 'Why is multitasking a myth for cognitive work?', options: ['Some people can multitask', 'The brain can only focus on one cognitive task at a time — "multitasking" is rapid task-switching with a 40% productivity cost', 'Multitasking is real and effective', 'It only affects beginners'], correctAnswer: 1, explanation: 'What feels like multitasking is rapid switching. Each switch incurs a cost — 40% reduced productivity and increased errors.' },
    { type: 'multiple_choice', question: 'How long does it take to recover focus after checking your phone?', options: ['A few seconds', '15-23 minutes', '1 minute', 'No recovery needed'], correctAnswer: 1, explanation: 'Research shows it takes 15-23 minutes to fully recover deep focus after a distraction like checking your phone.' },
    { type: 'multiple_choice', question: 'What is the optimal duration for a deep work block?', options: ['30 minutes', '90 minutes maximum — aligned with the ultradian rhythm', '4 hours', 'Until you feel tired'], correctAnswer: 1, explanation: 'The ultradian rhythm limits sustained focus to about 90 minutes. Genuine breaks between blocks maintain quality across the day.' },
    { type: 'multiple_choice', question: 'What should you define BEFORE starting a deep work block?', options: ['Your playlist', 'A clear objective — what will you have produced by the end?', 'How long you\'ll work', 'Who you\'ll call during breaks'], correctAnswer: 1, explanation: 'Starting with a clear output objective focuses the executive network and prevents the session from drifting into busy but unproductive work.' },
    { type: 'multiple_choice', question: 'Which network is the bottleneck for complex work?', options: ['Alerting network', 'Orienting network', 'Executive attention network', 'All equally'], correctAnswer: 2, explanation: 'The executive attention network is energy-expensive and limited — it\'s the bottleneck for complex, focused work.' },
    { type: 'multiple_choice', question: 'How many hours of deep work do most knowledge workers average per day?', options: ['6-8 hours', '4-5 hours', 'Less than 2 hours', 'More than 8 hours'], correctAnswer: 2, explanation: 'Most knowledge workers average less than 2 hours of genuine deep work per day — the rest is shallow work, meetings, and distractions.' },
    { type: 'multiple_choice', question: 'What is the most effective strategy for protecting focus?', options: ['Willpower to resist distractions', 'Environmental design — remove distractions before starting rather than resisting them', 'Working longer hours', 'Caffeine'], correctAnswer: 1, explanation: 'Removing distractions before starting (phone away, notifications off, one tab open) is more effective than trying to resist them with willpower.' },
    { type: 'scenario', question: 'What is the primary problem according to attention science?', scenario: 'A student studies for 3 hours with their phone on the desk, checking notifications every few minutes. They feel they\'ve worked hard but can\'t remember much of what they studied.', options: ['They need to study longer', 'Constant task-switching prevented sustained executive attention — each notification broke the focus cycle', 'The material was too hard', 'They need better study techniques'], correctAnswer: 1, explanation: 'Each phone check incurred a switching cost of 15-23 minutes recovery. Over 3 hours, genuine focus may have been less than 30 minutes.' },
    { type: 'multiple_choice', question: 'What type of activity is best during breaks between deep work blocks?', options: ['More work on a different project', 'Walking, nature, or rest with no screens — genuine neural recovery', 'Social media scrolling', 'Answering emails'], correctAnswer: 1, explanation: 'Genuine breaks (walking, nature, rest) allow the executive network to recover. Screens and other cognitive tasks continue to drain attention resources.' },
  ]),

  // Chapter 6: Emotional Intelligence
  cq(2, 6, [
    { type: 'multiple_choice', question: 'What are the four domains of emotional intelligence?', options: ['Happy, sad, angry, fearful', 'Self-awareness, self-management, social awareness, relationship management', 'Thinking, feeling, acting, relating', 'IQ, EQ, SQ, PQ'], correctAnswer: 1, explanation: 'Goleman\'s EI model: self-awareness (recognising emotions), self-management (regulating responses), social awareness (reading others), relationship management (influencing others).' },
    { type: 'multiple_choice', question: 'What is an "amygdala hijack"?', options: ['A brain surgery procedure', 'An emotional response disproportionate to the situation, triggered before rational evaluation can occur', 'A mindfulness technique', 'A type of cognitive bias'], correctAnswer: 1, explanation: 'The amygdala processes threats faster than the prefrontal cortex can evaluate — triggering fight/flight before rational assessment.' },
    { type: 'multiple_choice', question: 'How long is the minimum gap needed to interrupt an amygdala hijack?', options: ['1 second', '6 seconds', '30 seconds', '5 minutes'], correctAnswer: 1, explanation: 'Even 6 seconds is enough for the prefrontal cortex to engage and evaluate the situation more rationally.' },
    { type: 'multiple_choice', question: 'Which emotion regulation strategy is most effective long-term?', options: ['Suppression', 'Cognitive reappraisal — reinterpreting the meaning of the situation', 'Avoidance', 'Distraction'], correctAnswer: 1, explanation: 'Cognitive reappraisal (reframing) changes the emotional impact at its source. Suppression and avoidance don\'t address the underlying trigger.' },
    { type: 'multiple_choice', question: 'Is emotional intelligence a fixed personality trait?', options: ['Yes — you\'re born with it', 'No — it\'s a set of learnable skills that can be developed', 'Yes — it only changes with therapy', 'It depends on IQ'], correctAnswer: 1, explanation: 'EI is a skill set, not a trait. Each domain can be deliberately practised and improved through consistent effort.' },
    { type: 'multiple_choice', question: 'What does self-awareness in EI involve?', options: ['Knowing your IQ score', 'Recognising your own emotions as they occur and understanding their impact', 'Being self-conscious', 'Awareness of your physical appearance'], correctAnswer: 1, explanation: 'Self-awareness is the ability to recognise what you\'re feeling in real time and understand how it affects your thinking and behaviour.' },
    { type: 'multiple_choice', question: 'Why is EI a better predictor of life outcomes than IQ in most domains?', options: ['IQ is irrelevant', 'Most life situations require navigating emotions and relationships — skills EI addresses directly', 'EI is easier to measure', 'IQ doesn\'t exist'], correctAnswer: 1, explanation: 'Career success, relationships, health, and leadership all depend heavily on emotional and social skills — domains where EI is the primary predictor.' },
    { type: 'scenario', question: 'Which EI strategy would be most effective?', scenario: 'You receive critical feedback from a client and immediately feel defensive and angry. You want to fire back a reply.', options: ['Send the reply immediately while you\'re motivated', 'Pause (6-second rule), recognise the emotion, reappraise the feedback as useful data, then respond thoughtfully', 'Ignore the feedback entirely', 'Complain about the client to someone else'], correctAnswer: 1, explanation: 'The 6-second pause interrupts the hijack. Reappraisal (feedback = data, not attack) enables a constructive response rather than a reactive one.' },
    { type: 'multiple_choice', question: 'What is situation selection as a regulation strategy?', options: ['Choosing which situations to enter or avoid based on their likely emotional impact', 'Selecting the best workout', 'Choosing friends carefully', 'Always avoiding negative situations'], correctAnswer: 0, explanation: 'Situation selection is proactive: choosing to enter situations likely to produce helpful emotions and avoiding those likely to trigger unhelpful ones.' },
    { type: 'multiple_choice', question: 'What is the difference between EI and emotional suppression?', options: ['They\'re the same thing', 'EI uses emotions intelligently; suppression ignores or hides them — suppression actually increases emotional intensity', 'Suppression is more effective', 'EI eliminates emotions'], correctAnswer: 1, explanation: 'EI means using emotions as data and choosing responses. Suppression hides emotions, which paradoxically increases their physiological impact.' },
  ]),

  // Chapter 7: Memory & Learning
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What are the three stages of memory formation?', options: ['Input, processing, output', 'Encoding, consolidation, retrieval', 'Learning, storing, forgetting', 'Attention, practice, mastery'], correctAnswer: 1, explanation: 'Encoding (converting to neural form), consolidation (transferring to long-term storage during sleep), retrieval (accessing stored memories).' },
    { type: 'multiple_choice', question: 'Why is active recall superior to re-reading?', options: ['It isn\'t', 'Each retrieval attempt physically strengthens the memory pathway — re-reading doesn\'t activate retrieval', 'Re-reading is faster', 'Active recall is only for experts'], correctAnswer: 1, explanation: 'The testing effect: retrieving information from memory strengthens it more than re-exposing to it. Active recall literally builds stronger neural pathways.' },
    { type: 'multiple_choice', question: 'What is spaced repetition?', options: ['Repeating the same thing rapidly', 'Reviewing material at increasing intervals to exploit the spacing effect', 'Studying one topic exhaustively', 'Repeating affirmations'], correctAnswer: 1, explanation: 'Spaced repetition schedules reviews at expanding intervals (1 day, 3 days, 7 days, 21 days) — maximising retention with minimal total study time.' },
    { type: 'multiple_choice', question: 'What is interleaving?', options: ['Studying one topic until mastery before moving on', 'Mixing different topics or problem types in one study session', 'Alternating between studying and breaks', 'Studying with a partner'], correctAnswer: 1, explanation: 'Interleaving mixes topics within a session. It feels harder but produces significantly better long-term retention and transfer than blocked practice.' },
    { type: 'multiple_choice', question: 'What role does the hippocampus play in memory?', options: ['It stores all long-term memories', 'It acts as a temporary filing system, transferring new memories to long-term storage during sleep', 'It only processes emotional memories', 'It controls motor memory'], correctAnswer: 1, explanation: 'The hippocampus is the gateway — it temporarily holds new memories and transfers them to cortical long-term storage during sleep consolidation.' },
    { type: 'multiple_choice', question: 'What is the single most powerful cognitive enhancer available?', options: ['Caffeine', 'Exercise — it increases BDNF, promotes neurogenesis, and improves blood flow to the brain', 'Nootropic supplements', 'Brain training apps'], correctAnswer: 1, explanation: 'Exercise outperforms all supplements and brain training apps for cognitive enhancement — the evidence is robust and the effects are broad.' },
    { type: 'multiple_choice', question: 'What happens during sleep consolidation?', options: ['The brain rests completely', 'The brain replays and strengthens newly formed memories, transferring them to long-term storage', 'Memories are deleted', 'Only emotional processing occurs'], correctAnswer: 1, explanation: 'During sleep, the brain actively replays learning experiences, strengthening neural pathways and transferring information from hippocampus to cortex.' },
    { type: 'multiple_choice', question: 'What is the "generation effect"?', options: ['Learning from generation to generation', 'Producing an answer before seeing it (even a wrong guess) improves subsequent learning', 'Generating questions from text', 'Creating study materials'], correctAnswer: 1, explanation: 'The generation effect: attempting to produce an answer — even incorrectly — creates a "retrieval scaffold" that makes the correct answer more memorable.' },
    { type: 'scenario', question: 'What evidence-based change would improve her retention most?', scenario: 'A student reads her textbook chapters twice, highlights key points, and feels confident. But she fails the exam because she can\'t recall the information.', options: ['Read the chapters a third time', 'Replace re-reading with active recall — close the book and test herself on the content', 'Use more highlighter colours', 'Study for longer hours'], correctAnswer: 1, explanation: 'Re-reading creates familiarity (which feels like learning) but doesn\'t strengthen retrieval pathways. Active recall — testing herself — would build the neural paths needed for exam performance.' },
    { type: 'multiple_choice', question: 'What does the glymphatic system do during sleep?', options: ['Produces dreams', 'Clears metabolic waste products (including amyloid beta) from the brain', 'Consolidates motor memories', 'Produces neurotransmitters'], correctAnswer: 1, explanation: 'The glymphatic system activates during sleep to flush metabolic waste — including amyloid beta associated with Alzheimer\'s — from the brain.' },
  ]),

  // Chapter 8: Motivation & Willpower
  cq(2, 8, [
    { type: 'multiple_choice', question: 'What is the dopamine-effort connection?', options: ['Dopamine makes everything effortless', 'Higher dopamine activity in the nucleus accumbens and PFC increases willingness to exert effort for rewards', 'Effort depletes dopamine permanently', 'Dopamine has nothing to do with effort'], correctAnswer: 1, explanation: 'Dopamine directly controls effort allocation — people with higher dopamine in key brain regions choose harder tasks with larger rewards over easy tasks with small ones.' },
    { type: 'multiple_choice', question: 'What is the current scientific consensus on ego depletion?', options: ['Willpower is unlimited', 'Self-control does become harder with sustained use, but the effect is modulated by beliefs and motivation', 'Ego depletion doesn\'t exist at all', 'Willpower is entirely blood sugar dependent'], correctAnswer: 1, explanation: 'The original ego depletion model was overstated, but self-control does decline with sustained use — moderated by beliefs about willpower and task importance.' },
    { type: 'multiple_choice', question: 'Why is environmental design superior to willpower?', options: ['It isn\'t', 'Removing temptation requires zero ongoing willpower — the decision is made once', 'Environment doesn\'t affect behaviour', 'Willpower is always sufficient'], correctAnswer: 1, explanation: 'Designing your environment (removing junk food, placing gym clothes out) makes the right behaviour easier permanently — no willpower needed.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Doing multiple habits simultaneously', 'Linking a new habit to an existing one — "After I [current habit], I will [new habit]"', 'Stacking weights in a gym', 'Combining supplements'], correctAnswer: 1, explanation: 'Habit stacking uses an existing behaviour as a cue for a new one — leveraging the established neural pathway to trigger the desired behaviour.' },
    { type: 'multiple_choice', question: 'What is a commitment device?', options: ['A piece of gym equipment', 'An arrangement that makes it costly to deviate from your intention — paying in advance, telling someone, setting deadlines', 'A motivational poster', 'A training diary'], correctAnswer: 1, explanation: 'Commitment devices bind your future self to a decision: paying upfront, public declaration, or creating consequences for not following through.' },
    { type: 'multiple_choice', question: 'Why does motivation often fail as a strategy?', options: ['People are lazy', 'Motivation fluctuates with neurochemical state — it\'s unreliable as a daily driver of behaviour', 'Motivation always works', 'Only discipline matters'], correctAnswer: 1, explanation: 'Motivation is a neurochemical state that fluctuates. Systems, environment design, and habits produce consistent behaviour regardless of motivational state.' },
    { type: 'multiple_choice', question: 'What does "design defaults" mean in behavioural architecture?', options: ['Accept the default option', 'Arrange your environment so the behaviour that happens when you do nothing is the right one', 'Follow factory settings', 'Don\'t change anything'], correctAnswer: 1, explanation: 'Designing defaults means: if I do nothing special, the outcome should still be good. Example: healthy food at eye level, gym on the route home.' },
    { type: 'scenario', question: 'What principle explains this difference?', scenario: 'Person A: keeps chocolate in a visible bowl on the kitchen counter and eats it daily despite wanting to stop. Person B: keeps no chocolate at home and rarely eats it. Both report similar levels of self-control.', options: ['Person B has more willpower', 'Environmental design — Person B removed the cue, making the behaviour unlikely regardless of willpower', 'Person A is addicted to chocolate', 'They have different genetics'], correctAnswer: 1, explanation: 'Person B designed their environment to make the unwanted behaviour harder. Equal willpower, different environments, different outcomes.' },
    { type: 'multiple_choice', question: 'What reframes "laziness" as a biological state?', options: ['It\'s always a character flaw', 'Low dopaminergic activity — not a moral failing but a neurochemical state that can be influenced through behaviour', 'Laziness doesn\'t exist', 'It\'s always genetic'], correctAnswer: 1, explanation: 'Low motivation is a low-dopamine state — addressable through exercise, cold exposure, sleep, and reducing dopamine-depleting behaviours.' },
    { type: 'multiple_choice', question: 'What is the best combination for sustained behaviour change?', options: ['Pure willpower', 'Systems (environment design + habits) supported by moderate motivation', 'Motivation alone', 'Punishment for failure'], correctAnswer: 1, explanation: 'Systems do the heavy lifting (consistent regardless of state), supported by motivation as a booster — never relying on motivation as the sole driver.' },
  ]),

  // Chapter 9: Brain Health
  cq(2, 9, [
    { type: 'multiple_choice', question: 'What percentage of dementia cases may be preventable through lifestyle modification?', options: ['5%', '15%', 'Up to 40%', '80%'], correctAnswer: 2, explanation: 'The Lancet Commission identified that up to 40% of dementia cases are linked to modifiable risk factors.' },
    { type: 'multiple_choice', question: 'What is cognitive reserve?', options: ['Memory storage capacity', 'The brain\'s ability to withstand damage before showing cognitive decline, built through lifelong learning and health', 'IQ level', 'How many facts you know'], correctAnswer: 1, explanation: 'Cognitive reserve is the brain\'s resilience — built through education, physical fitness, social engagement, and continued learning.' },
    { type: 'multiple_choice', question: 'How much exercise is recommended for brain health?', options: ['30 minutes per week', '150+ minutes of moderate activity per week — reduces dementia risk by 30%', '10 minutes per day', 'Only vigorous exercise counts'], correctAnswer: 1, explanation: '150+ minutes of moderate physical activity per week is the evidence-based threshold for significant dementia risk reduction.' },
    { type: 'multiple_choice', question: 'How does chronic sleep deprivation affect brain health?', options: ['No long-term effect', 'It doubles Alzheimer\'s risk by impairing glymphatic waste clearance', 'It only affects mood', 'It improves brain efficiency'], correctAnswer: 1, explanation: 'Chronic sleep deprivation prevents the glymphatic system from clearing amyloid beta and other waste products, significantly increasing dementia risk.' },
    { type: 'multiple_choice', question: 'By how much does social isolation increase dementia risk?', options: ['5%', '10%', '25%', '40%'], correctAnswer: 3, explanation: 'Loneliness and social isolation increase dementia risk by approximately 40% — as powerful a risk factor as physical inactivity.' },
    { type: 'multiple_choice', question: 'What are the "Big Four" for brain health?', options: ['Supplements, brain training, crosswords, reading', 'Exercise, sleep, social connection, and continued learning', 'Meditation, yoga, journaling, therapy', 'Diet, water, sunshine, rest'], correctAnswer: 1, explanation: 'The four factors with the strongest evidence: regular exercise, quality sleep, meaningful social connection, and novel cognitive challenges.' },
    { type: 'multiple_choice', question: 'Is cognitive decline with age inevitable?', options: ['Yes — nothing can be done', 'Not at the rate most people experience it — lifestyle factors can maintain sharp function for decades longer', 'Yes — after age 50', 'Only genetics determine decline'], correctAnswer: 1, explanation: 'While some decline is normal, the rate and severity are heavily influenced by modifiable factors. Healthy lifestyles can maintain cognitive sharpness decades longer.' },
    { type: 'multiple_choice', question: 'What is the relationship between physical and brain health?', options: ['They are separate', 'They are inseparable — the same behaviours that protect your heart protect your brain', 'Only brain exercises matter for brain health', 'Physical health only affects the body'], correctAnswer: 1, explanation: 'Cardiovascular health, metabolic health, and brain health are deeply connected — exercise, sleep, and nutrition protect all three simultaneously.' },
    { type: 'scenario', question: 'Based on brain health research, what is the highest-priority change?', scenario: 'A 45-year-old does no regular exercise, sleeps 5 hours per night, works alone from home, and hasn\'t learned anything new in years. They want to protect their brain health.', options: ['Start a supplement regimen', 'Begin regular exercise — it\'s the single most impactful modifiable factor for brain health', 'Do crossword puzzles', 'Buy a brain training app'], correctAnswer: 1, explanation: 'Exercise addresses the broadest range of brain health factors: BDNF production, cardiovascular health, inflammation, sleep quality, and mood. Start there.' },
    { type: 'multiple_choice', question: 'Why should hearing loss be addressed for brain health?', options: ['It isn\'t related', 'Hearing loss is an identified modifiable risk factor for dementia — early intervention with hearing aids reduces risk', 'It only affects communication', 'Hearing loss can\'t be treated'], correctAnswer: 1, explanation: 'The Lancet Commission identified hearing loss as a significant modifiable risk factor for dementia — early intervention matters.' },
  ]),
];
