import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL4Unit4ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: Behaviour Change Science
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the five stages of the Transtheoretical Model?', options: ['Start, build, peak, maintain, finish', 'Assess, plan, do, check, improve', 'Precontemplation, contemplation, preparation, action, maintenance', 'Denial, anger, bargaining, depression, acceptance'], correctAnswer: 2, explanation: 'The Transtheoretical Model describes change as moving through: not considering change, considering it, preparing, acting, and maintaining.' },
    { type: 'multiple_choice', question: 'What are the three components of the COM-B model?', options: ['Cost, Outcome, Method', 'Commitment, Objectives, Measures', 'Compliance, Organisation, Monitoring', 'Capability, Opportunity, Motivation'], correctAnswer: 3, explanation: 'COM-B states behaviour requires Capability (can they?), Opportunity (is it possible?), and Motivation (do they want to?).' },
    { type: 'multiple_choice', question: 'Why does giving information often fail to change behaviour?', options: ['People don\'t read', 'Information addresses only psychological capability — the person may lack opportunity or motivation', 'Information is always ineffective', 'People don\'t care about health'], correctAnswer: 1, explanation: 'Information only addresses one COM-B component (psychological capability). If the barrier is opportunity or motivation, more information won\'t help.' },
    { type: 'multiple_choice', question: 'What is the most common mistake in behaviour change interventions?', options: ['Applying the right intervention at the wrong stage of change', 'Not trying hard enough', 'Being too supportive', 'Using too many strategies'], correctAnswer: 0, explanation: 'Giving a gym programme to someone in precontemplation is like giving directions to someone who hasn\'t decided to travel. Stage-matching is essential.' },
    { type: 'multiple_choice', question: 'What approach is most effective for someone in the contemplation stage?', options: ['Prescribe a detailed action plan', 'Explore their ambivalence — pros/cons of change — using MI techniques', 'Push them to start immediately', 'Wait until they\'re ready'], correctAnswer: 1, explanation: 'Contemplation = ambivalence. The right approach is exploring pros and cons, not prescribing action (too early) or ignoring them (too passive).' },
    { type: 'scenario', question: 'Using COM-B, what is the primary barrier?', scenario: 'A client knows exactly what to eat (has a meal plan, understands nutrition), but works 12-hour shifts and has no time to cook.', options: ['Capability — they don\'t know enough', 'Motivation — they don\'t want it enough', 'Opportunity — their environment and schedule prevent the behaviour', 'All three equally'], correctAnswer: 2, explanation: 'This is an Opportunity barrier (physical). They have knowledge (capability) and desire (motivation) but the environment doesn\'t support the behaviour.' },
    { type: 'multiple_choice', question: 'What does relapse indicate in the Transtheoretical Model?', options: ['The person lacks commitment', 'The intervention was wrong', 'A normal part of the change process — most people cycle through stages multiple times', 'Complete failure'], correctAnswer: 2, explanation: 'Relapse is expected, not exceptional. Most people cycle through stages 3-7 times before permanent change. Normalising this prevents shame-based dropout.' },
    { type: 'multiple_choice', question: 'What is the difference between reflective and automatic motivation in COM-B?', options: ['They are the same', 'Reflective is conscious (goals, values); automatic is unconscious (habits, emotions, impulses)', 'Reflective is better', 'Automatic doesn\'t exist'], correctAnswer: 1, explanation: 'Both matter: reflective motivation drives deliberate decisions; automatic motivation drives habitual behaviour. Lasting change requires both.' },
    { type: 'multiple_choice', question: 'How should you intervene when the capability component is the barrier?', options: ['Wait for readiness', 'Change the environment', 'Provide education, training, skill development, or simplify the behaviour', 'Increase motivation'], correctAnswer: 2, explanation: 'Capability barriers need capability solutions: teach the skill, provide information, demonstrate the behaviour, or simplify it.' },
    { type: 'multiple_choice', question: 'Why is diagnosis essential before intervention?', options: ['To appear professional', 'Different barriers require different interventions — without diagnosis, you may target the wrong component', 'It\'s a legal requirement', 'Diagnosis is unnecessary'], correctAnswer: 1, explanation: 'More information won\'t fix an opportunity problem. More motivation won\'t fix a capability problem. Diagnose first, then match the intervention.' },
  ]),

  // Chapter 2: Client Psychology & Adherence
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What are the three basic psychological needs in Self-Determination Theory?', options: ['Security, belonging, esteem', 'Autonomy, competence, relatedness', 'Power, achievement, affiliation', 'Food, shelter, safety'], correctAnswer: 1, explanation: 'SDT: Autonomy (choice), Competence (effectiveness), Relatedness (connection). All three must be met for intrinsic motivation to develop.' },
    { type: 'multiple_choice', question: 'What is the "80% rule" for programme adherence?', options: ['Follow the programme 80% perfectly', 'If a client can\'t follow the programme 80% of the time, the programme is wrong — not the client', 'Eat clean 80% of the time', 'Train at 80% intensity'], correctAnswer: 1, explanation: 'If someone can\'t follow your programme most of the time, you\'ve designed it for someone else\'s life. Adjust the programme to match the person.' },
    { type: 'multiple_choice', question: 'Which question best predicts adherence?', options: ['"How much weight do you want to lose?"', '"On a scale of 1-10, how confident are you that you can follow this programme?"', '"Do you want to get fit?"', '"How often do you currently exercise?"'], correctAnswer: 1, explanation: 'Self-efficacy (confidence in following the specific plan) predicts adherence better than desire, knowledge, or current behaviour.' },
    { type: 'multiple_choice', question: 'What happens when the autonomy need is thwarted?', options: ['People try harder', 'People feel controlled, resist, and eventually disengage', 'Nothing — autonomy isn\'t important', 'People become more compliant'], correctAnswer: 1, explanation: 'Thwarted autonomy produces reactance (resistance) or amotivation (giving up). People need to feel they have choice and self-direction.' },
    { type: 'multiple_choice', question: 'How does providing choice support adherence?', options: ['It doesn\'t', 'Choice within structure satisfies autonomy needs while maintaining programme quality', 'Unlimited choice is best', 'Choice reduces results'], correctAnswer: 1, explanation: 'Choice within structure: "Do you prefer morning or evening training?" preserves programme integrity while giving the client ownership.' },
    { type: 'scenario', question: 'Which SDT need is most likely unmet?', scenario: 'A client has a well-designed programme but trains alone, has no training partner, and feels disconnected from any fitness community. After 6 weeks they quit.', options: ['All three equally', 'Autonomy', 'Competence', 'Relatedness — they lacked social connection and belonging'], correctAnswer: 3, explanation: 'Relatedness (social connection) is the unmet need. Adding social elements — training partner, group sessions, community — would address the dropout cause.' },
    { type: 'multiple_choice', question: 'Why do early wins matter for adherence?', options: ['They don\'t', 'Early successes build competence beliefs (self-efficacy) that sustain behaviour through later difficulties', 'They only motivate beginners', 'They create false expectations'], correctAnswer: 1, explanation: 'Early wins are self-efficacy deposits. When difficulty comes later, the accumulated confidence from past success provides the psychological capital to persist.' },
    { type: 'multiple_choice', question: 'What is the difference between intrinsic and extrinsic motivation?', options: ['Extrinsic is more reliable', 'They are the same', 'Intrinsic comes from inherent satisfaction; extrinsic comes from external rewards/pressures', 'Intrinsic is stronger'], correctAnswer: 2, explanation: 'Intrinsic = doing it because it\'s satisfying. Extrinsic = doing it for rewards or to avoid punishment. Intrinsic is more durable but takes time to develop.' },
    { type: 'multiple_choice', question: 'What role does feedback frequency play in adherence?', options: ['Feedback is unnecessary', 'Only negative feedback helps', 'Less feedback is better', 'Regular, visible feedback maintains motivation by demonstrating progress that might otherwise go unnoticed'], correctAnswer: 3, explanation: 'Progress is often invisible without measurement. Regular feedback (performance tracking, check-ins, body composition) makes progress visible and sustains motivation.' },
    { type: 'multiple_choice', question: 'What undermines intrinsic motivation according to SDT?', options: ['Physical discomfort', 'High expectations', 'External control, pressure, and surveillance that thwart autonomy', 'Difficult challenges'], correctAnswer: 2, explanation: 'External control, surveillance, and pressure undermine autonomy — the foundation of intrinsic motivation. Support autonomy, and intrinsic motivation grows.' },
  ]),

  // Chapter 3: Resilience & Post-Adversity Growth
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is the single strongest predictor of resilient outcomes?', options: ['Strong social support', 'Intelligence', 'Financial security', 'Personality type'], correctAnswer: 0, explanation: 'Social support is consistently the strongest predictor of resilience across all types of adversity. Invest in relationships before you need them.' },
    { type: 'multiple_choice', question: 'What is "realistic optimism"?', options: ['Always expecting the worst', 'Blind positivity', 'Believing things can improve while honestly acknowledging current challenges', 'Optimism based on facts only'], correctAnswer: 2, explanation: 'Realistic optimism is neither naive positivity nor pessimism — it\'s the belief that improvement is possible combined with honest assessment of the current situation.' },
    { type: 'multiple_choice', question: 'What is stress inoculation?', options: ['Taking supplements for stress', 'Stress-free living', 'Avoiding all stress', 'Controlled exposure to manageable stress that builds tolerance and capacity for future challenges'], correctAnswer: 3, explanation: 'Like vaccination, stress inoculation uses controlled exposure to build the system\'s capacity. Cold exposure, hard training, and voluntary discomfort all count.' },
    { type: 'multiple_choice', question: 'Why is resilience described as a process rather than a trait?', options: ['It doesn\'t matter how it\'s described', 'Processes can be developed and improved; traits feel fixed and unchangeable', 'Traits are better descriptions', 'Resilience is actually a trait'], correctAnswer: 1, explanation: 'Describing resilience as a process empowers development: "I can build resilience through specific actions" vs. "I\'m just not a resilient person."' },
    { type: 'multiple_choice', question: 'Which practice directly supports both physical and psychological resilience?', options: ['Journaling only', 'Positive affirmations', 'Avoiding challenges', 'Regular physical exercise'], correctAnswer: 3, explanation: 'Exercise improves stress hormones, sleep, mood, confidence, and physical capacity — making it the single most powerful resilience-building behaviour.' },
    { type: 'multiple_choice', question: 'What is "sense of coherence" in resilience research?', options: ['Understanding why adversity happened, believing you can cope, and finding meaning in it', 'Being organised', 'Having a clear schedule', 'Logical thinking ability'], correctAnswer: 0, explanation: 'Antonovsky\'s sense of coherence: comprehensibility (I understand what happened), manageability (I can cope), meaningfulness (it has purpose). All three support resilience.' },
    { type: 'scenario', question: 'What resilience strategy would you prioritise?', scenario: 'Someone faces a major setback — job loss, relationship breakdown, health scare. They\'re tempted to isolate and deal with it alone.', options: ['Isolation is fine — they need space', 'Prioritise social connection — the strongest protective factor is reaching out to trusted people, not withdrawing', 'Focus only on solving the practical problem', 'Distract themselves with work'], correctAnswer: 1, explanation: 'The instinct to isolate during adversity is common but counterproductive. Social support is the #1 resilience factor — connecting with others should be the first response.' },
    { type: 'multiple_choice', question: 'What does "active coping" mean?', options: ['Staying busy to avoid thinking', 'Taking purposeful action on what you can control while accepting what you can\'t', 'Aggressively confronting every problem', 'Ignoring problems until they resolve'], correctAnswer: 1, explanation: 'Active coping = problem-focused action on controllable elements + acceptance of uncontrollable ones. It\'s the most effective coping strategy.' },
    { type: 'multiple_choice', question: 'What is the role of purpose in resilience?', options: ['Purpose is irrelevant to resilience', 'Clear values and meaningful goals provide direction and motivation during chaos — a reason to keep going', 'Purpose creates more stress', 'Purpose only matters after recovery'], correctAnswer: 1, explanation: 'Viktor Frankl observed that those who survived extreme adversity often had a clear sense of purpose. Purpose provides direction when everything else is uncertain.' },
    { type: 'multiple_choice', question: 'How does cognitive flexibility support resilience?', options: ['By avoiding thinking about problems', 'By enabling alternative perspectives — seeing opportunities in setbacks and adapting strategies when plans fail', 'It doesn\'t help', 'By staying rigidly focused on the plan'], correctAnswer: 1, explanation: 'Cognitive flexibility — the ability to reframe and adapt — prevents getting stuck in one perspective and enables creative problem-solving during adversity.' },
  ]),

  // Chapter 4: Positive Psychology & Flourishing
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What are the five pillars of Seligman\'s PERMA model?', options: ['Power, Endurance, Recovery, Mindset, Agility', 'Planning, Execution, Review, Motivation, Action', 'Positive Emotions, Engagement, Relationships, Meaning, Accomplishment', 'Persistence, Energy, Resilience, Mastery, Attitude'], correctAnswer: 2, explanation: 'PERMA: Positive Emotions, Engagement (flow), Relationships, Meaning (serving something bigger), and Accomplishment (mastery).' },
    { type: 'multiple_choice', question: 'What is the "Three Good Things" exercise?', options: ['Listing three life goals', 'Doing three good deeds daily', 'Each evening, writing three things that went well and why', 'Identifying three strengths'], correctAnswer: 2, explanation: 'Three Good Things: each evening, write three positive events and why they happened. Simple but proven to reduce depression and increase happiness for 6+ months.' },
    { type: 'multiple_choice', question: 'What is the single most powerful positive psychology intervention tested?', options: ['Positive affirmations', 'Meditation', 'Visualisation', 'The gratitude letter — writing and delivering a letter of thanks to someone who has made a difference in your life'], correctAnswer: 3, explanation: 'The gratitude visit — writing and personally delivering a letter of gratitude — produces the largest and most sustained boost in happiness of any tested intervention.' },
    { type: 'multiple_choice', question: 'What is "engagement" in the PERMA model?', options: ['Attending events', 'Social media engagement', 'Being fully absorbed in activities that challenge your skills — flow states', 'Being busy'], correctAnswer: 2, explanation: 'Engagement = flow: complete absorption in an activity where challenge matches skill. Time disappears, self-consciousness drops, and performance peaks.' },
    { type: 'multiple_choice', question: 'What does positive psychology say about negative emotions?', options: ['They should be eliminated', 'They serve important functions — positive psychology aims to expand positive experiences, not eliminate negative ones', 'They\'re always harmful', 'They indicate weakness'], correctAnswer: 1, explanation: 'Positive psychology doesn\'t suppress negative emotions. It recognises their function while deliberately building more positive experiences and meaning.' },
    { type: 'multiple_choice', question: 'What are character strengths in positive psychology?', options: ['Positive personality characteristics (like curiosity, fairness, or bravery) that feel natural and energising when used', 'Skills learned in training', 'Physical abilities', 'Competitive advantages'], correctAnswer: 0, explanation: 'VIA character strengths are core positive traits. Using your top strengths daily is linked to greater engagement, meaning, and life satisfaction.' },
    { type: 'scenario', question: 'Which PERMA pillar needs the most attention?', scenario: 'A successful professional has a high-paying job, exercises regularly, and has many acquaintances but feels something is missing. They describe their life as "fine but empty."', options: ['Accomplishment', 'Meaning — they lack a sense of purpose or contribution to something bigger than themselves', 'Engagement', 'Positive Emotions'], correctAnswer: 1, explanation: 'The "fine but empty" feeling typically indicates a Meaning deficit — accomplishment without purpose. Connecting work to values or service would address this.' },
    { type: 'multiple_choice', question: 'What is the broaden-and-build theory of positive emotions?', options: ['Positive emotions narrow focus', 'Only negative emotions drive growth', 'Positive emotions broaden awareness and build lasting resources — physical, intellectual, social, and psychological', 'Positive emotions are just feelings'], correctAnswer: 2, explanation: 'Fredrickson\'s theory: positive emotions expand thinking, build relationships, increase creativity, and accumulate resources. They\'re not just pleasant — they\'re productive.' },
    { type: 'multiple_choice', question: 'How often should positive psychology interventions be practised?', options: ['Once a month', 'Only during difficult times', 'Once is enough', 'Consistently — daily or weekly practice produces cumulative benefits that compound over time'], correctAnswer: 3, explanation: 'Like exercise, positive psychology interventions require consistent practice. "Three Good Things" works because it\'s done daily — not because it\'s done once.' },
    { type: 'multiple_choice', question: 'What is savouring?', options: ['Daydreaming', 'Eating slowly', 'Reminiscing about the past', 'Deliberately extending positive experiences by paying full, mindful attention to them'], correctAnswer: 3, explanation: 'Savouring is intentionally amplifying positive experiences — paying full attention, sharing them with others, or mentally replaying them later.' },
  ]),

  // Chapter 5: Stress Physiology & Management
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What does the HPA axis stand for?', options: ['Health-Psychology-Assessment', 'Hypothalamic-Pituitary-Adrenal axis', 'High-Performance-Adaptation', 'Heart-Pulse-Artery'], correctAnswer: 1, explanation: 'The HPA axis: Hypothalamus → Pituitary → Adrenal glands — the cascade that produces cortisol and adrenaline in response to perceived threat.' },
    { type: 'multiple_choice', question: 'What is the Yerkes-Dodson law?', options: ['Stress has no effect on performance', 'Performance follows an inverted-U curve: too little stress = boredom, optimal stress = peak performance, too much = anxiety', 'More stress always improves performance', 'High stress is always harmful'], correctAnswer: 1, explanation: 'The inverted-U relationship: moderate arousal/stress optimises performance. The goal isn\'t zero stress — it\'s the right amount.' },
    { type: 'multiple_choice', question: 'What is the difference between eustress and distress?', options: ['Eustress is physical; distress is mental', 'Eustress promotes growth and is manageable; distress overwhelms and degrades functioning', 'They are the same', 'Eustress isn\'t real'], correctAnswer: 1, explanation: 'Eustress (positive stress) feels challenging but manageable — it drives growth. Distress feels overwhelming and degrades performance and health.' },
    { type: 'multiple_choice', question: 'What is the fastest evidence-based technique for acute stress reduction?', options: ['Deep thinking', 'Counting to 10', 'The physiological sigh — two quick inhales through the nose followed by a long exhale through the mouth', 'Drinking water'], correctAnswer: 2, explanation: 'The physiological sigh activates the parasympathetic nervous system within seconds — it\'s the fastest evidence-based technique for real-time stress reduction.' },
    { type: 'multiple_choice', question: 'Why is chronic stress particularly damaging?', options: ['It isn\'t — the body adapts', 'The stress response evolved for acute threats; chronic activation damages cardiovascular, immune, and cognitive systems', 'It only affects mood', 'Chronic stress builds tolerance'], correctAnswer: 1, explanation: 'The stress response was designed for short bursts. Chronic activation causes sustained cortisol elevation, damaging the heart, immune system, and brain.' },
    { type: 'multiple_choice', question: 'What is the single best stress buffer?', options: ['Regular physical exercise', 'Meditation', 'Alcohol', 'Sleeping pills'], correctAnswer: 0, explanation: 'Exercise is the most effective stress buffer: it metabolises stress hormones, releases mood-boosting neurotransmitters, improves sleep, and builds physical resilience.' },
    { type: 'scenario', question: 'Which stress management level should be addressed first?', scenario: 'A client is overwhelmed at work, has high blood pressure, and can\'t sleep. They\'ve tried deep breathing but it doesn\'t seem enough.', options: ['Cognitive reframing only', 'Ignore it — stress is normal', 'Environmental level — reduce controllable stressors (set boundaries, delegate, remove unnecessary commitments) alongside physiological techniques', 'More breathing exercises'], correctAnswer: 2, explanation: 'When stress is overwhelming, physiological techniques alone aren\'t enough. Environmental changes (reducing the actual stressors) must accompany individual coping strategies.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['Training volume', 'A strength measurement', 'The cumulative wear and tear on the body from chronic stress exposure', 'A stress tolerance test'], correctAnswer: 2, explanation: 'Allostatic load is the total physiological cost of adapting to chronic stress — it accumulates and eventually causes health breakdown.' },
    { type: 'multiple_choice', question: 'What is "cognitive reappraisal" for stress?', options: ['Ignoring the stressor', 'Thinking positively about everything', 'Changing how you interpret the stressful situation — "This is a challenge, not a threat"', 'Analysing stress logically'], correctAnswer: 2, explanation: 'Reappraisal changes the meaning: "This presentation is terrifying" → "This is a chance to share what I know." Same event, different emotional response.' },
    { type: 'multiple_choice', question: 'Why is recovery as important as stress management?', options: ['It isn\'t', 'Without adequate recovery between stress exposures, allostatic load accumulates regardless of coping strategies', 'Recovery is only for athletes', 'Stress management eliminates the need for recovery'], correctAnswer: 1, explanation: 'Stress + recovery = growth. Stress without recovery = breakdown. Designing recovery into your schedule is non-negotiable for sustainable performance.' },
  ]),

  // Chapter 6: Psychology of Identity & Self-Concept
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Why is identity a more powerful predictor of behaviour than goals?', options: ['It isn\'t', 'Identity-driven behaviour is self-sustaining — "This is who I am" doesn\'t require motivation', 'Goals are always better', 'Identity doesn\'t affect behaviour'], correctAnswer: 1, explanation: 'Identity is autopilot: "I am a runner" produces consistent running without daily motivation decisions. "I want to run more" requires a decision each time.' },
    { type: 'multiple_choice', question: 'What is the "vote" metaphor for identity change?', options: ['Every action consistent with the target identity is a "vote" that gradually builds that identity', 'People should vote on their identity', 'Identity changes through single events', 'Voting in elections'], correctAnswer: 0, explanation: 'James Clear: each action is a vote. You don\'t need a majority — just enough consistent votes to form a new identity. One gym session = one vote for "I train."' },
    { type: 'multiple_choice', question: 'What are "possible selves"?', options: ['Mental representations of who you could become — both hoped-for and feared versions of your future self', 'Multiple personality disorder', 'Fictional characters', 'Past identities'], correctAnswer: 0, explanation: 'Possible selves (Markus & Nurius) include hoped-for selves (motivating) and feared selves (also motivating). Both drive behaviour when vivid and paired with strategy.' },
    { type: 'multiple_choice', question: 'What happens when the gap between current self and ideal self feels too large?', options: ['No effect', 'Greater motivation', 'Despair rather than motivation — the gap must feel bridgeable for it to drive action', 'Automatic improvement'], correctAnswer: 2, explanation: 'If the gap feels insurmountable, it produces helplessness. Effective coaching makes the ideal self vivid AND the path to it achievable — hope + plan.' },
    { type: 'multiple_choice', question: 'How does community reinforce identity?', options: ['It doesn\'t', 'Groups validate and model the target identity — "These are my people" confirms "This is who I am"', 'Community dilutes identity', 'Only individual work matters'], correctAnswer: 1, explanation: 'Identity is socially reinforced. Joining a running club confirms "I am a runner" far more powerfully than running alone.' },
    { type: 'scenario', question: 'What identity-based strategy would be most effective?', scenario: 'A client completes a 12-week programme successfully but reverts to old habits as soon as it ends. This has happened three times.', options: ['A longer programme', 'Address the identity: they complete programmes (achiever identity) but haven\'t adopted a permanent identity shift — "I am someone who lives this way"', 'More willpower training', 'A simpler programme'], correctAnswer: 1, explanation: 'Programmes end; identity doesn\'t. The client succeeds within structure but hasn\'t internalised the identity. The goal should be permanent identity shift, not programme completion.' },
    { type: 'multiple_choice', question: 'What is "identity pruning"?', options: ['Removing social media profiles', 'Releasing identities that conflict with who you want to become', 'Reducing group memberships', 'Simplifying your name'], correctAnswer: 1, explanation: 'You can\'t be "someone who prioritises health" while maintaining an identity as "the person who\'s always available for everyone." Conflicting identities must be pruned.' },
    { type: 'multiple_choice', question: 'Why is self-narration important for identity change?', options: ['It isn\'t', 'Telling yourself and others who you\'re becoming reinforces the new identity through language', 'It\'s just positive thinking', 'Only actions matter'], correctAnswer: 1, explanation: 'Language shapes identity. "I\'m trying to eat healthier" is different from "I don\'t eat junk food." The narrative reinforces the identity, which drives behaviour.' },
    { type: 'multiple_choice', question: 'What makes identity-based change more durable than goal-based change?', options: ['Goals are more durable', 'Goals have endpoints; identity is ongoing. Once the goal is achieved, motivation disappears — identity sustains behaviour indefinitely', 'There\'s no difference', 'Goal-based change is always better'], correctAnswer: 1, explanation: '"Lose 10kg" ends when achieved (and often behaviour reverts). "I am someone who takes care of their body" never ends — it\'s self-sustaining.' },
    { type: 'multiple_choice', question: 'What is the first step in deliberate identity change?', options: ['Change your wardrobe', 'Define the target identity clearly: "I am someone who..."', 'Tell everyone about your new identity', 'Join a new social group'], correctAnswer: 1, explanation: 'Start with clarity: "I am someone who trains consistently, eats to fuel performance, and prioritises recovery." Then align daily actions with this statement.' },
  ]),

  // Chapter 7: Ethics, Boundaries & Professional Standards
  cq(4, 7, [
    { type: 'multiple_choice', question: 'What are the four core ethical principles in helping professions?', options: ['Honesty, loyalty, courage, integrity', 'Speed, quality, cost, efficiency', 'Beneficence, non-maleficence, autonomy, justice', 'Listen, advise, support, review'], correctAnswer: 2, explanation: 'Beneficence (do good), non-maleficence (do no harm), autonomy (respect their choices), justice (treat fairly). These guide all ethical decision-making.' },
    { type: 'multiple_choice', question: 'What is "scope of practice"?', options: ['The number of clients you can manage', 'How far you can travel for clients', 'The boundaries of what you are qualified and competent to do professionally', 'The range of your gym equipment'], correctAnswer: 2, explanation: 'Scope of practice defines your professional limits. Operating outside it — e.g., attempting therapy without training — risks harm to the client.' },
    { type: 'multiple_choice', question: 'What is a dual relationship and why is it problematic?', options: ['Working two jobs', 'Having more than one type of relationship with a client (e.g., coach and friend) which can create conflicts of interest', 'Training two clients at once', 'Having two certifications'], correctAnswer: 1, explanation: 'Dual relationships blur boundaries: a coach who becomes a friend may struggle with objective feedback, and the client may feel unable to leave.' },
    { type: 'multiple_choice', question: 'When should confidentiality be broken?', options: ['Never — it\'s absolute', 'When there is a safeguarding concern — risk of harm to the client or others overrides confidentiality', 'Whenever the coach thinks it\'s appropriate', 'When it would make a good story'], correctAnswer: 1, explanation: 'Confidentiality is near-absolute but not absolute. Safeguarding concerns (risk of harm to self or others) are the justified exception.' },
    { type: 'multiple_choice', question: 'What does the principle of autonomy require?', options: ['Doing whatever the client wants', 'Respecting the client\'s right to make their own decisions, even ones you disagree with', 'Making decisions for the client', 'Only working with autonomous people'], correctAnswer: 1, explanation: 'Autonomy means respecting self-determination. You can share information and opinions, but the client\'s right to choose their own path must be respected.' },
    { type: 'scenario', question: 'What is the most ethical response?', scenario: 'A personal training client starts telling you about their childhood trauma during sessions. They say talking to you helps more than their therapist.', options: ['Continue — if they find it helpful, it\'s working', 'Acknowledge their trust, explain that this is beyond your scope, and encourage them to share this with their therapist', 'Stop training them immediately', 'Tell them to stop talking about personal things'], correctAnswer: 1, explanation: 'This is a scope-of-practice issue. Validate their trust, but redirect to the appropriate professional. Training sessions shouldn\'t become therapy sessions.' },
    { type: 'multiple_choice', question: 'What should a professional code of ethics include?', options: ['Only legal requirements', 'Clear principles guiding professional behaviour with practical examples of application', 'A list of things you won\'t do', 'Marketing guidelines'], correctAnswer: 1, explanation: 'A good code includes guiding principles (what you stand for) AND practical examples (how they apply in real situations). Review and update it regularly.' },
    { type: 'multiple_choice', question: 'Why is transparent pricing an ethical issue?', options: ['It isn\'t', 'Hidden costs, unclear contracts, and financial pressure exploit the trust inherent in the professional relationship', 'Only in high-end services', 'Pricing is purely a business decision'], correctAnswer: 1, explanation: 'Financial transparency is an ethical obligation. Hidden fees, high-pressure upselling, and unclear contracts exploit the trust clients place in professionals.' },
    { type: 'multiple_choice', question: 'What is the ethical response to transformation photo requests?', options: ['Always share — it\'s good marketing', 'Obtain genuine informed consent, ensure dignity, and never pressure — the client\'s wellbeing overrides marketing', 'Never use photos', 'Only use anonymous photos'], correctAnswer: 1, explanation: 'Transformation photos require genuine consent (not pressured), dignity protection, and should serve the client\'s interests — not just marketing needs.' },
    { type: 'multiple_choice', question: 'What is the best test for ethical decision-making?', options: ['"Will I get in trouble?"', '"Is this in my client\'s best interest?" and "Am I operating within my competence?"', '"What would my competitors do?"', '"Is it legal?"'], correctAnswer: 1, explanation: 'These two questions resolve most dilemmas: client\'s best interest (beneficence) and within competence (scope of practice). When in doubt, apply both.' },
  ]),

  // Chapter 8: Psychology of Goal-Setting & Achievement
  cq(4, 8, [
    { type: 'multiple_choice', question: 'What does Locke and Latham\'s research conclude about goal specificity?', options: ['Vague goals are fine', 'Specific, difficult goals produce higher performance than vague or easy goals', 'Easy goals are most effective', 'Goals don\'t affect performance'], correctAnswer: 1, explanation: 'Across 1,000+ studies: specific, challenging goals consistently outperform "do your best" or easy goals. This is one of the most replicated findings in psychology.' },
    { type: 'multiple_choice', question: 'What are implementation intentions?', options: ['General goals', 'Implementation plans', '"When [situation], I will [behaviour]" — pre-planned responses that approximately double follow-through', 'Thinking about your goals'], correctAnswer: 2, explanation: 'Gollwitzer\'s research: linking behaviour to a specific cue approximately doubles follow-through because it pre-loads the decision.' },
    { type: 'multiple_choice', question: 'What does WOOP stand for?', options: ['Wish, Outcome, Obstacle, Plan', 'Will, Optimism, Objectives, Progress', 'Wake, Observe, Organise, Perform', 'Work Out On Purpose'], correctAnswer: 0, explanation: 'Oettingen\'s WOOP: Wish (goal) → Outcome (benefit) → Obstacle (main barrier) → Plan (if-then strategy). More effective than positive visualisation alone.' },
    { type: 'multiple_choice', question: 'What is the relationship between outcome goals and process goals?', options: ['Only outcome goals matter', 'Process goals are distracting', 'They are the same', 'Outcome goals provide direction; process goals provide the daily system that makes outcomes inevitable'], correctAnswer: 3, explanation: 'Outcome goals = "what I want." Process goals = "what I do daily." Without process goals, outcome goals are just wishes.' },
    { type: 'multiple_choice', question: 'What is the dark side of goal-setting?', options: ['There isn\'t one', 'Overly narrow goals can cause anxiety, unethical behaviour, and neglect of non-goal areas', 'Goals always improve wellbeing', 'Dark sides only affect lazy people'], correctAnswer: 1, explanation: 'Goal fixation can lead to tunnel vision, unethical shortcuts, risk-taking, and neglect of wellbeing. Goals need guardrails and regular review.' },
    { type: 'scenario', question: 'What goal architecture element is missing?', scenario: 'A client says: "My goal is to lose 20kg." They have no gym schedule, no meal plan, and no specific daily actions planned.', options: ['More motivation', 'Process goals — they need specific daily actions (train 4x/week, eat X calories, prep meals Sunday) that make the outcome achievable', 'A larger outcome goal', 'Their goal is fine as stated'], correctAnswer: 1, explanation: 'An outcome goal without process goals is a wish. The client needs specific, daily, actionable process goals that systematically drive toward the outcome.' },
    { type: 'multiple_choice', question: 'How often should goals be reviewed?', options: ['Daily', 'Quarterly — goals should be reviewed, adjusted, and recommitted to based on current reality', 'Never — once set, commit', 'Only when failing'], correctAnswer: 1, explanation: 'Quarterly review prevents both blind persistence on outdated goals and premature abandonment. Adjust the approach, reaffirm or revise the direction.' },
    { type: 'multiple_choice', question: 'What is the optimal level of goal difficulty?', options: ['As easy as possible', 'Challenging enough to require genuine effort but achievable with commitment — around 70-80% confidence of success', 'As hard as possible', 'Difficulty doesn\'t matter'], correctAnswer: 1, explanation: 'The sweet spot: hard enough to be meaningful, achievable enough to maintain belief. If confidence of success is below 50%, the goal is likely too ambitious.' },
    { type: 'multiple_choice', question: 'What makes public commitment effective for goals?', options: ['Social media accountability', 'It creates social accountability and identity alignment — "I said I would, so I will" leverages consistency', 'It doesn\'t work', 'It only works for extroverts'], correctAnswer: 1, explanation: 'Public commitment leverages the consistency principle — once you\'ve publicly stated a goal, acting inconsistently with it creates psychological discomfort.' },
    { type: 'multiple_choice', question: 'What is the key message about goals vs systems?', options: ['Goals are all you need', 'Choose one or the other', 'Goals give direction; systems give results. Winners and losers have the same goals — the system makes the difference', 'Systems are unnecessary'], correctAnswer: 2, explanation: 'Every Olympic athlete has the goal to win gold. The system — daily training, nutrition, recovery, coaching — determines who actually gets there.' },
  ]),

  // Chapter 9: Integrating Psychology Into Practice
  cq(4, 9, [
    { type: 'multiple_choice', question: 'What is the primary benefit of integrating multiple psychological frameworks?', options: ['Sounding more knowledgeable', 'Multiple lenses provide more accurate diagnosis and more effective intervention than any single framework', 'It\'s required by law', 'It impresses clients'], correctAnswer: 1, explanation: 'A client who "lacks motivation" might have a COM-B barrier, an SDT need deficit, a stage-of-change mismatch, or a neurochemical issue. Multiple frameworks = better diagnosis.' },
    { type: 'multiple_choice', question: 'What should a personal practice framework include?', options: ['Assessment, relationship-building, intervention, maintenance support, and ethical boundaries', 'Only client management systems', 'Only intervention techniques', 'Just theory knowledge'], correctAnswer: 0, explanation: 'A complete framework covers: how you assess, how you build rapport, what tools you use, how you maintain change, and where your boundaries are.' },
    { type: 'multiple_choice', question: 'What is the danger of using only one psychological framework?', options: ['One framework is usually enough', 'Multiple frameworks create confusion', 'No danger', 'When your only tool is a hammer, everything looks like a nail — single frameworks miss the complexity of human behaviour'], correctAnswer: 3, explanation: 'Single-framework thinking leads to misdiagnosis: seeing every problem through the same lens misses factors that another framework would catch.' },
    { type: 'multiple_choice', question: 'Why does the course emphasise "you are your own first client"?', options: ['Self-improvement is selfish', 'You cannot credibly guide others through processes you haven\'t experienced yourself — personal practice builds authenticity', 'It\'s just a saying', 'Only professional training matters'], correctAnswer: 1, explanation: 'Credibility comes from practice. A coach who manages their own stress, builds their own habits, and applies psychology to themselves is authentic and effective.' },
    { type: 'multiple_choice', question: 'What distinguishes knowledge from competence?', options: ['They are the same', 'Knowledge is understanding theory; competence is the ability to apply it effectively in real situations', 'Knowledge is more important', 'Competence can\'t be measured'], correctAnswer: 1, explanation: 'Knowing the GROW model is knowledge. Using it effectively in a live coaching conversation is competence. Competence requires practice, not just study.' },
    { type: 'scenario', question: 'Using an integrated approach, what should you assess first?', scenario: 'A new client wants to "get fit" but has failed multiple times. They feel hopeless and say "nothing works for me."', options: ['Prescribe a programme immediately', 'Assess: stage of change (contemplation/preparation?), COM-B barriers (which component?), self-efficacy level, and SDT needs — then design based on the diagnosis', 'Tell them to try harder', 'Suggest they aren\'t ready'], correctAnswer: 1, explanation: 'An integrated assessment reveals: they\'re likely in contemplation with low self-efficacy. The intervention should match the diagnosis, not be a generic programme.' },
    { type: 'multiple_choice', question: 'What is reflective practice?', options: ['Systematically reviewing your own performance, learning from experience, and improving your approach', 'Reading about practice', 'Reflecting on your appearance', 'Thinking about exercise'], correctAnswer: 0, explanation: 'Reflective practice means regularly asking: what went well, what didn\'t, what would I do differently? It\'s how practitioners improve without formal training.' },
    { type: 'multiple_choice', question: 'What is the role of supervision or mentorship in professional development?', options: ['Only for beginners', 'An external perspective catches blind spots, challenges assumptions, and accelerates growth — valuable at all career stages', 'It\'s a sign of weakness', 'Only required by regulations'], correctAnswer: 1, explanation: 'Even experts benefit from external perspectives. Supervision provides accountability, fresh viewpoints, and catches the blind spots self-reflection misses.' },
    { type: 'multiple_choice', question: 'What is the final message of Mindset L4?', options: ['Theory matters more than practice', 'Psychology is a practice, not a destination — continue learning, applying, and refining your approach throughout your career', 'You now know everything', 'Certification is enough'], correctAnswer: 1, explanation: 'The course is a foundation. Ongoing learning, application, reflection, and refinement are what transform knowledge into expertise.' },
    { type: 'multiple_choice', question: 'What should your personal development plan include?', options: ['A list of certifications to get', 'Only professional goals', 'Only book recommendations', 'Areas to deepen, skills to practise, resources to engage with, and a timeline for review'], correctAnswer: 3, explanation: 'A development plan should be specific: what you\'ll learn, how you\'ll practise it, what resources you\'ll use, and when you\'ll review progress.' },
  ]),
];
