import type { UnitAssessment } from '../types';

export const mindsetL4Unit3Assessment: UnitAssessment = {
  unitNumber: 3,
  title: 'Leadership Psychology & Social Dynamics — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'Which forms of social power produce the most durable influence?', options: ['Coercive and reward', 'Expert and referent — people follow because they want to, not because they have to', 'Legitimate and coercive', 'All are equally durable'], correctAnswer: 1, explanation: 'Expert (competence) and referent (admiration) power produce lasting, willing compliance. Coercive power only works under surveillance.' },
    { type: 'multiple_choice', question: 'What is the key difference between transformational and transactional leadership?', options: ['Transactional is always worse', 'Transformational inspires intrinsic motivation through vision and values; transactional uses contingent rewards and correction', 'They are the same', 'Transformational only works in sports'], correctAnswer: 1, explanation: 'Transactional = exchange (do this, get that). Transformational = inspiration (here\'s why this matters). Both have their place; transformation produces deeper commitment.' },
    { type: 'scenario', question: 'Which principle of influence is primarily at work?', scenario: 'A personal trainer offers a free nutrition workshop. Attendees feel obligated to book a training session afterwards, even though there was no pressure to do so.', options: ['Social proof', 'Scarcity', 'Reciprocity — the free workshop triggered an obligation to reciprocate', 'Authority'], correctAnswer: 2, explanation: 'The free value triggered reciprocity — recipients feel they should give something back. Used ethically, this builds genuine client relationships.' },
    { type: 'multiple_choice', question: 'What did Google\'s Project Aristotle identify as the most important factor for team effectiveness?', options: ['Individual talent', 'Psychological safety', 'Clear goals', 'Strong leadership'], correctAnswer: 1, explanation: 'Psychological safety — the ability to take risks and be vulnerable without fear — mattered more than who was on the team.' },
    { type: 'multiple_choice', question: 'What is the most effective conflict resolution style when both parties have valid points and the relationship matters?', options: ['Competing', 'Avoiding', 'Collaborating — finding a solution that satisfies both parties\' interests', 'Compromising'], correctAnswer: 2, explanation: 'Collaborating takes longer but produces win-win outcomes. It\'s the best choice when both perspectives have merit and the relationship is important.' },
    { type: 'multiple_choice', question: 'How does social identity theory explain fitness community behaviour?', options: ['It doesn\'t apply', 'People who identify as "someone who trains" maintain behaviour through disruption because it\'s part of who they are, not just what they do', 'Only genetics matter', 'Social identity only affects teenagers'], correctAnswer: 1, explanation: 'Social identity transforms behaviour from a choice into a characteristic. "I am a CrossFitter" drives consistent behaviour that "I go to CrossFit" doesn\'t.' },
    { type: 'multiple_choice', question: 'What are Gottman\'s "Four Horsemen" that predict relationship breakdown?', options: ['Anger, sadness, fear, disgust', 'Criticism, contempt, defensiveness, stonewalling', 'Lying, cheating, neglect, abuse', 'Arguing, disagreeing, competing, avoiding'], correctAnswer: 1, explanation: 'The Four Horsemen: personal criticism (not complaint), contempt (superiority), defensiveness (counter-attacking), stonewalling (withdrawing). All predictive of failure.' },
    { type: 'multiple_choice', question: 'What is the GROW coaching model used for?', options: ['Physical training programming', 'Structuring coaching conversations to move from aspiration to committed action', 'Measuring growth', 'Botanical research'], correctAnswer: 1, explanation: 'GROW (Goal, Reality, Options, Will) structures conversations from desired outcome through current situation and options to concrete commitment.' },
    { type: 'multiple_choice', question: 'What is the "power paradox" described by Dacher Keltner?', options: ['Power is always positive', 'The social skills that help you gain power (empathy, fairness) are often eroded by having power', 'Power always corrupts', 'There is no paradox'], correctAnswer: 1, explanation: 'The paradox: you gain power through social intelligence, but power can undermine the empathy and social awareness that earned it.' },
    { type: 'multiple_choice', question: 'What is the primary reason people leave fitness communities?', options: ['Cost', 'Lack of social connection and belonging — they didn\'t feel part of something', 'Poor equipment', 'Inconvenient location'], correctAnswer: 1, explanation: 'Social factors outweigh practical ones in exercise dropout. People who feel they belong stay; those who don\'t, leave — regardless of facility quality.' },
    { type: 'scenario', question: 'What group dynamic phenomenon is occurring?', scenario: 'A team meeting where everyone agrees with the leader\'s proposal. Privately, several members have serious concerns but don\'t voice them because no one else has objected.', options: ['Good leadership', 'Groupthink — consensus-seeking has overridden critical thinking; members self-censor because silence appears to equal agreement', 'Efficient decision-making', 'Strong team cohesion'], correctAnswer: 1, explanation: 'Classic groupthink: the illusion of unanimity (silence = agreement), self-censorship, and the suppression of dissent in favour of group harmony.' },
    { type: 'multiple_choice', question: 'What is the most powerful source of self-efficacy according to Bandura?', options: ['Verbal encouragement', 'Mastery experiences — successfully completing progressively challenging tasks builds the strongest confidence', 'Watching others succeed', 'Managing anxiety'], correctAnswer: 1, explanation: 'Nothing builds self-efficacy like personal success. Design experiences where clients succeed at challenging-but-achievable tasks.' },
  ],
};
