import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL4Unit3ChapterQuizzes: ChapterQuiz[] = [
  // Chapter 1: Transformational Leadership
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the four components of transformational leadership?', options: ['Plan, Do, Check, Act', 'Idealised influence, inspirational motivation, intellectual stimulation, individualised consideration', 'Autocratic, democratic, laissez-faire, situational', 'Vision, strategy, execution, review'], correctAnswer: 1, explanation: 'Bass\'s four I\'s: the leader is a role model (idealised), articulates a compelling vision (inspirational), challenges followers to think (intellectual), and mentors individually (individualised).' },
    { type: 'multiple_choice', question: 'How does transformational leadership differ from transactional?', options: ['They are the same', 'Transformational inspires intrinsic motivation; transactional uses rewards and punishments', 'Transactional is always better', 'Transformational is weaker'], correctAnswer: 1, explanation: 'Transactional = "do this, get that." Transformational = "here\'s why this matters, and here\'s what we can become." Both have their place.' },
    { type: 'multiple_choice', question: 'Why is leading by example the most powerful form of influence?', options: ['Because people obey authority', 'Because people follow what you do, not what you say — credibility comes from behaviour', 'Because it requires no effort', 'Because verbal instructions are ineffective'], correctAnswer: 1, explanation: 'Behaviour is the most credible communication. A leader who says "work hard" but doesn\'t has zero influence. One who demonstrates it has maximum influence.' },
    { type: 'multiple_choice', question: 'What is the foundation on which all effective leadership rests?', options: ['Intelligence', 'Technical expertise', 'Trust', 'Authority'], correctAnswer: 2, explanation: 'Without trust, no leadership technique works. Trust is built through consistency between words and actions over time.' },
    { type: 'multiple_choice', question: 'What distinguishes good leaders from great leaders, according to research?', options: ['Technical expertise', 'Their emotional intelligence — how they inspire, connect with, and develop others', 'Physical presence', 'Academic qualifications'], correctAnswer: 1, explanation: 'Technical skills get you to leadership positions; emotional intelligence determines how effective you are in them.' },
    { type: 'multiple_choice', question: 'What does "individualised consideration" mean?', options: ['Treating everyone equally', 'Mentoring and developing each person according to their unique needs and goals', 'Considering your own needs first', 'Individual performance reviews'], correctAnswer: 1, explanation: 'Individualised consideration means recognising that each person needs different support — adapting your leadership to each individual.' },
    { type: 'multiple_choice', question: 'What makes a vision "compelling" in transformational leadership?', options: ['It must be written beautifully', 'It connects to people\'s values, is vivid enough to imagine, and shows how each person contributes', 'It must be original', 'It needs to come from the top'], correctAnswer: 1, explanation: 'A compelling vision connects to values, is vivid enough to visualise, and makes each person feel their contribution matters.' },
    { type: 'scenario', question: 'Which transformational component is most needed here?', scenario: 'A team is competent but bored. They follow instructions accurately but show no creativity or initiative.', options: ['Tighter management', 'Intellectual stimulation — challenging them to think differently, question assumptions, and solve problems creatively', 'More rewards', 'Stricter deadlines'], correctAnswer: 1, explanation: 'The team needs intellectual stimulation — the "I" that challenges followers to think beyond routine and find innovative approaches.' },
    { type: 'multiple_choice', question: 'What is the key risk of charismatic leadership without ethical grounding?', options: ['No risk', 'Charisma can inspire people toward harmful goals — ethics provide the moral compass that charisma alone cannot', 'Charismatic leaders are always ethical', 'Charisma is always positive'], correctAnswer: 1, explanation: 'Charisma is a tool — it can inspire great things or terrible ones. Without ethical grounding, charismatic leaders can be deeply destructive.' },
    { type: 'multiple_choice', question: 'What is the best way to develop as a transformational leader?', options: ['Read leadership books only', 'Practise the four I\'s daily, seek feedback, and model the behaviour you want to see', 'Attend a single leadership course', 'Wait for a leadership position'], correctAnswer: 1, explanation: 'Leadership is a practice, not a position. Develop it through daily application of the principles, honest feedback, and consistent self-improvement.' },
  ]),

  // Chapter 2: Influence & Persuasion
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What are Cialdini\'s six principles of influence?', options: ['Plan, do, check, act, review, improve', 'Reciprocity, commitment/consistency, social proof, authority, liking, scarcity', 'Logic, emotion, trust, urgency, clarity, simplicity', 'Power, money, status, fear, reward, habit'], correctAnswer: 1, explanation: 'Cialdini\'s research identified six universal principles that trigger automatic compliance responses across cultures.' },
    { type: 'multiple_choice', question: 'What is the reciprocity principle?', options: ['Demanding favours', 'People feel obligated to return what they receive — give first, receive later', 'Getting something for nothing', 'Only helping those who help you'], correctAnswer: 1, explanation: 'Reciprocity is deeply wired: giving value first (information, help, time) creates a felt obligation to reciprocate. Give genuinely, not manipulatively.' },
    { type: 'multiple_choice', question: 'How does the commitment/consistency principle work?', options: ['It makes people commit to too many things', 'Once people take a small step, they tend to act consistently with that initial commitment', 'It only works in writing', 'It only applies to large decisions'], correctAnswer: 1, explanation: 'The foot-in-the-door effect: a small initial "yes" (signing up, trying a session) makes a larger consistent "yes" much more likely.' },
    { type: 'multiple_choice', question: 'What makes social proof effective?', options: ['People copy whoever is loudest', 'People look to others similar to themselves when uncertain about what to do', 'Social proof only works online', 'It only affects weak-minded people'], correctAnswer: 1, explanation: 'Social proof is most powerful when people are uncertain AND the proof comes from people similar to them — "people like me do this."' },
    { type: 'multiple_choice', question: 'What is the scarcity principle?', options: ['Making things cheap', 'Things become more desirable when availability is limited or decreasing', 'Hiding products from customers', 'Creating artificial shortages'], correctAnswer: 1, explanation: 'Scarcity triggers urgency and increased perceived value. It\'s most powerful when something was recently available and is now diminishing.' },
    { type: 'multiple_choice', question: 'What is the ethical boundary of persuasion?', options: ['There are no boundaries', 'Influence is ethical when it serves the other person\'s genuine interest; manipulation serves only yours', 'Ethics don\'t apply to business', 'All persuasion is manipulation'], correctAnswer: 1, explanation: 'The line between influence and manipulation is intent: whose interest does the outcome serve? Ethical influence benefits the other person.' },
    { type: 'scenario', question: 'Which principle of influence is primarily at work?', scenario: 'A gym offers a free personal training session. After the session, the client feels obligated to buy a package even though they hadn\'t planned to.', options: ['Scarcity', 'Social proof', 'Reciprocity — the free session created a sense of obligation to give something back', 'Authority'], correctAnswer: 2, explanation: 'The free session triggered reciprocity — the client feels they received value and should reciprocate by purchasing.' },
    { type: 'multiple_choice', question: 'Which principle is most powerful in coaching contexts?', options: ['Scarcity', 'Authority — coaches have expertise that clients look to for guidance', 'Social proof', 'Reciprocity'], correctAnswer: 1, explanation: 'Authority (expertise credibility) is central to coaching — clients follow guidance from trusted experts. Build it through competence and integrity.' },
    { type: 'multiple_choice', question: 'What is the "liking" principle?', options: ['Making people like you by flattery', 'People are more influenced by those they like — built through genuine similarity, compliments, and familiarity', 'Being likeable is manipulative', 'It only works in sales'], correctAnswer: 1, explanation: 'Liking is built through genuine rapport — shared interests, authentic compliments, and repeated positive contact. It\'s not about being fake.' },
    { type: 'multiple_choice', question: 'Why should understanding influence principles be part of everyone\'s education?', options: ['To manipulate others more effectively', 'Understanding how influence works makes you both more persuasive AND more resistant to manipulation', 'It\'s only useful for salespeople', 'It\'s unnecessary'], correctAnswer: 1, explanation: 'Knowledge of influence principles serves dual purpose: apply them ethically to help others, and recognise when they\'re being used against your interests.' },
  ]),

  // Chapter 3: Group Dynamics
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What are Tuckman\'s five stages of group development?', options: ['Plan, Do, Check, Act, Review', 'Forming, Storming, Norming, Performing, Adjourning', 'Beginning, Middle, End, Reflection, Restart', 'Introduction, Conflict, Resolution, Execution, Closure'], correctAnswer: 1, explanation: 'Tuckman\'s model: groups inevitably move through politeness (Forming), conflict (Storming), consensus (Norming), productivity (Performing), and ending (Adjourning).' },
    { type: 'multiple_choice', question: 'Why is the "storming" phase actually essential?', options: ['It isn\'t — it should be avoided', 'Conflict surfaces differences that must be resolved for genuine trust and effective collaboration', 'It weeds out weak members', 'It only happens in dysfunctional teams'], correctAnswer: 1, explanation: 'Teams that skip or suppress storming never develop real trust. Managed conflict is necessary for genuine norm-setting and psychological safety.' },
    { type: 'multiple_choice', question: 'What is groupthink?', options: ['Effective team consensus', 'Consensus-seeking that overrides critical thinking — the group prioritises harmony over accuracy', 'Creative brainstorming', 'Democratic decision-making'], correctAnswer: 1, explanation: 'Groupthink occurs when the desire for group harmony suppresses dissent, critical evaluation, and individual thought — leading to poor decisions.' },
    { type: 'multiple_choice', question: 'What is social loafing?', options: ['Relaxing after a workout', 'Individuals exerting less effort in a group than they would alone, especially when contributions aren\'t identifiable', 'Taking breaks during group work', 'Socialising instead of working'], correctAnswer: 1, explanation: 'Social loafing increases when individual contributions are invisible. Making contributions identifiable and creating accountability prevents it.' },
    { type: 'multiple_choice', question: 'What prevents social loafing?', options: ['Bigger groups', 'Making individual contributions identifiable, meaningful, and valued', 'Removing accountability', 'Increasing group size'], correctAnswer: 1, explanation: 'When people know their specific contribution matters and is visible, social loafing diminishes significantly.' },
    { type: 'multiple_choice', question: 'What did Google\'s Project Aristotle find was the most important factor for team effectiveness?', options: ['Individual talent', 'Psychological safety — team members feeling safe to take risks and be vulnerable', 'Clear hierarchy', 'Working hours'], correctAnswer: 1, explanation: 'Psychological safety was the single strongest predictor — more important than who was on the team, it was how they treated each other.' },
    { type: 'scenario', question: 'Which stage of group development is this team in?', scenario: 'A newly formed project team is overly polite, avoids disagreement, and looks to the leader for all direction. No one wants to rock the boat.', options: ['Norming', 'Performing', 'Forming — the team is still in the polite, orientation stage', 'Adjourning'], correctAnswer: 2, explanation: 'This is classic Forming behaviour: politeness, dependence on the leader, avoiding conflict. The team hasn\'t yet entered Storming.' },
    { type: 'multiple_choice', question: 'What is the optimal size for decision-making groups?', options: ['2-3 people', '5-7 people', '10-12 people', '15+ people'], correctAnswer: 1, explanation: 'Research consistently finds 5-7 as optimal — large enough for diverse perspectives, small enough for genuine discussion and accountability.' },
    { type: 'multiple_choice', question: 'What is a sign of groupthink in action?', options: ['Healthy debate', 'Illusion of unanimity — silence is interpreted as agreement, and dissenters self-censor', 'Critical evaluation of ideas', 'Welcoming of outside opinions'], correctAnswer: 1, explanation: 'In groupthink, silence = agreement. Members self-censor doubts, creating the illusion that everyone agrees when they don\'t.' },
    { type: 'multiple_choice', question: 'How can a leader prevent groupthink?', options: ['Demand agreement', 'Assign a devil\'s advocate, encourage disagreement, withhold their own opinion initially, and seek outside perspectives', 'Make decisions alone', 'Only select people who agree with them'], correctAnswer: 1, explanation: 'Preventing groupthink requires actively encouraging dissent, delaying leader opinion, and structuring processes that surface disagreement.' },
  ]),

  // Chapter 4: Conflict Resolution
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What are the five conflict-handling styles (Thomas-Kilmann)?', options: ['Fight, flight, freeze, fawn, appease', 'Competing, collaborating, compromising, avoiding, accommodating', 'Aggressive, passive, assertive, manipulative, withdrawn', 'Direct, indirect, passive, active, balanced'], correctAnswer: 1, explanation: 'Thomas-Kilmann\'s model: Competing (high assertiveness), Collaborating (win-win), Compromising (middle ground), Avoiding (low on both), Accommodating (yielding).' },
    { type: 'multiple_choice', question: 'What does the collaborating style aim for?', options: ['One winner', 'A solution that fully satisfies both parties\' interests', 'Splitting the difference', 'Avoiding the conflict'], correctAnswer: 1, explanation: 'Collaborating seeks win-win — it takes longer but produces the most durable, satisfying outcomes when the relationship matters.' },
    { type: 'multiple_choice', question: 'Why are "I" statements more effective than "You" statements in conflict?', options: ['They sound nicer', '"I feel frustrated when..." describes your experience without triggering defensiveness. "You always..." triggers counter-attack.', 'They are not more effective', '"You" statements are more direct'], correctAnswer: 1, explanation: '"You always..." triggers defensive reactions. "I feel... when... because..." describes impact without blame, keeping the conversation productive.' },
    { type: 'multiple_choice', question: 'When is the "avoiding" style actually appropriate?', options: ['Never', 'When the issue is trivial, emotions are too high for productive conversation, or you need more information', 'Always — conflict should be avoided', 'Only in emergencies'], correctAnswer: 1, explanation: 'Avoiding is appropriate when the issue is minor, emotions need to cool, or you need more information. It becomes harmful when used habitually for important issues.' },
    { type: 'multiple_choice', question: 'What is the most common source of interpersonal conflict?', options: ['Personality differences', 'Unmet expectations — usually caused by assumptions rather than explicit communication', 'Money disagreements', 'Competition for resources'], correctAnswer: 1, explanation: 'Most conflicts stem from unspoken expectations. "I assumed you would..." is the foundation of most interpersonal friction.' },
    { type: 'multiple_choice', question: 'What does active listening demonstrate during conflict?', options: ['Agreement', 'That you value the other person\'s perspective, even if you disagree', 'Weakness', 'That you\'re waiting to speak'], correctAnswer: 1, explanation: 'Active listening in conflict signals respect. "I hear that you feel..." validates their experience without requiring you to agree with their conclusion.' },
    { type: 'scenario', question: 'What is the best conflict resolution approach?', scenario: 'Two team members disagree about a project approach. Both have valid points. The relationship between them matters for future collaboration.', options: ['Let the senior person decide', 'Use the collaborating style — explore both perspectives to find a solution that incorporates the best of each', 'Avoid the topic', 'Flip a coin'], correctAnswer: 1, explanation: 'When the relationship matters and both sides have merit, collaborating produces the best outcome — it takes longer but builds trust and leverages both perspectives.' },
    { type: 'multiple_choice', question: 'What is "positions vs interests" in negotiation?', options: ['Seating arrangements', 'Positions are what people say they want; interests are WHY they want it — resolving interests often reveals creative solutions', 'They are the same thing', 'Positions are always more important'], correctAnswer: 1, explanation: 'Two people arguing over one orange (position) may discover one needs the peel and one needs the juice (interests). Understanding interests unlocks solutions.' },
    { type: 'multiple_choice', question: 'What is the role of emotion in conflict?', options: ['Emotions should be suppressed', 'Emotions are data about what matters — acknowledge them, but don\'t let them drive behaviour', 'Emotions are irrelevant', 'The most emotional person wins'], correctAnswer: 1, explanation: 'Emotions signal what matters. Acknowledging them (yours and theirs) prevents escalation while using the information to understand the real issues.' },
    { type: 'multiple_choice', question: 'What is the first step in any conflict resolution process?', options: ['State your position firmly', 'Regulate your own emotional state — you can\'t resolve conflict effectively when emotionally hijacked', 'Identify the winner', 'Involve a mediator'], correctAnswer: 1, explanation: 'Self-regulation comes first. If you\'re emotionally hijacked, delay the conversation. You can\'t think clearly or listen effectively while triggered.' },
  ]),

  // Chapter 5: Social Identity Theory
  cq(3, 5, [
    { type: 'multiple_choice', question: 'What is social identity theory?', options: ['Your name and address', 'People derive part of their self-concept from their group memberships, which affects behaviour and perception', 'A theory about social media', 'How society assigns identities'], correctAnswer: 1, explanation: 'Tajfel\'s social identity theory: we define ourselves partly through group membership — and this affects how we see ourselves, in-group members, and out-group members.' },
    { type: 'multiple_choice', question: 'What is in-group bias?', options: ['Disliking your own group', 'The tendency to favour members of your own group over outsiders', 'Bias toward minority groups', 'Preferring to work alone'], correctAnswer: 1, explanation: 'In-group bias is automatic: we perceive in-group members more positively, trust them more, and treat them more favourably — even with minimal group criteria.' },
    { type: 'multiple_choice', question: 'What did the minimal group paradigm experiments demonstrate?', options: ['Groups need clear identities', 'Even arbitrary, meaningless group divisions create in-group favouritism', 'Group conflict requires real differences', 'People don\'t form groups easily'], correctAnswer: 1, explanation: 'Tajfel found that even randomly assigned groups (e.g., based on art preference) produced in-group favouritism. Group bias doesn\'t require real differences.' },
    { type: 'multiple_choice', question: 'How does social identity affect fitness behaviour?', options: ['It doesn\'t', 'People who identify as "someone who trains" maintain exercise through disruptions that stop "people trying to get fit"', 'Only genetics determine fitness behaviour', 'Social identity only affects teenagers'], correctAnswer: 1, explanation: 'Identity drives behaviour more than goals. "I am a runner" produces more consistent running than "I want to run more."' },
    { type: 'multiple_choice', question: 'How can coaches use social identity principles ethically?', options: ['Create us-vs-them mentality', 'Build inclusive community identity — "We are people who..." — that supports positive behaviour', 'Exclude out-group members', 'Ignore group dynamics'], correctAnswer: 1, explanation: 'Ethical use: create inclusive identity ("We are people who push each other and show up") that strengthens positive behaviour without excluding others.' },
    { type: 'multiple_choice', question: 'What is the "social cure" effect?', options: ['Social media therapy', 'Group membership actively protects against depression, anxiety, and cognitive decline — belonging heals', 'Curing social anxiety', 'A type of group therapy'], correctAnswer: 1, explanation: 'Research shows that strong group memberships independently reduce depression, anxiety, and even cognitive decline. Social belonging is genuinely health-protective.' },
    { type: 'scenario', question: 'What social identity principle is at work?', scenario: 'A new member joins a CrossFit gym and within weeks starts calling themselves a "CrossFitter," wakes up earlier to train, and changes their diet — despite having no interest in fitness before.', options: ['They found the right exercise', 'The gym community provided a new group identity that reshaped their behaviour to align with "who we are"', 'They were always motivated', 'Peer pressure forced compliance'], correctAnswer: 1, explanation: 'Adopting the group identity ("I am a CrossFitter") shifted behaviour to be consistent with the new social identity. The group changed who they see themselves as.' },
    { type: 'multiple_choice', question: 'What is the danger of strong in-group identity?', options: ['No danger exists', 'It can create out-group hostility, stereotyping, and prejudice', 'It only creates positive outcomes', 'It weakens individual identity'], correctAnswer: 1, explanation: 'Strong in-group identity has a shadow side: it can produce hostility toward out-groups, stereotyping, and prejudice — especially under threat.' },
    { type: 'multiple_choice', question: 'What is identity threat?', options: ['A direct physical threat', 'Feeling that a valued group identity is being questioned, devalued, or undermined', 'Losing your ID card', 'An identity crisis'], correctAnswer: 1, explanation: 'When a valued identity is threatened, people become defensive and may respond with increased in-group bias or aggression toward the perceived threat.' },
    { type: 'multiple_choice', question: 'How can multiple group identities protect wellbeing?', options: ['They can\'t — multiple identities cause confusion', 'Having several meaningful group identities provides a buffer — if one is threatened, others maintain self-worth', 'Only one identity should matter', 'Multiple identities dilute commitment'], correctAnswer: 1, explanation: 'Identity diversity is protective: someone who is a trainer, parent, musician, and community member has multiple sources of belonging and self-worth.' },
  ]),

  // Chapter 6: Communication Psychology
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Which non-verbal channel is most important for emotional communication?', options: ['Words used', 'Vocal tone and body language — which carry 70-93% of emotional meaning', 'Written text', 'Eye colour'], correctAnswer: 1, explanation: 'Mehrabian\'s research (often over-simplified) highlights that when words and tone conflict, people trust tone. Non-verbal cues dominate emotional interpretation.' },
    { type: 'multiple_choice', question: 'What is the most important communication skill?', options: ['Speaking clearly', 'Active listening — making the other person feel genuinely heard and understood', 'Using complex vocabulary', 'Being persuasive'], correctAnswer: 1, explanation: 'Active listening is the foundation of all effective communication. People can\'t hear your message until they feel heard themselves.' },
    { type: 'multiple_choice', question: 'What does the "illusion of transparency" mean?', options: ['People can see through lies', 'We overestimate how much others understand what we\'re thinking and feeling', 'Communication is always transparent', 'Non-verbal signals are always clear'], correctAnswer: 1, explanation: 'We assume our internal states are more visible to others than they are — leading to communication breakdowns when we think we\'ve been clear but haven\'t.' },
    { type: 'multiple_choice', question: 'What is mirroring in communication?', options: ['Copying someone exactly', 'Subtly matching body language, tone, and pace to build rapport unconsciously', 'Using a mirror during conversations', 'Reflecting questions back'], correctAnswer: 1, explanation: 'Mirroring is the natural, subtle matching of posture, tone, and pace that occurs between people in rapport — it can be used consciously to build connection.' },
    { type: 'multiple_choice', question: 'Why should feedback use the "situation-behaviour-impact" model?', options: ['It sounds more professional', 'It\'s specific and objective: "In [situation], when you [behaviour], the impact was [effect]" — removing personal judgement', 'It\'s faster than other methods', 'It only applies to managers'], correctAnswer: 1, explanation: 'SBI makes feedback specific, observable, and non-judgemental: what happened, what they did, and what effect it had. No character attacks, just data.' },
    { type: 'scenario', question: 'What communication principle is being violated here?', scenario: 'A coach texts a client: "Your form needs work." The client reads it as harsh criticism and considers quitting.', options: ['The client is oversensitive', 'Text lacks non-verbal context — the coach\'s neutral intent couldn\'t be conveyed without tone, expression, or follow-up', 'Nothing is wrong — the feedback is accurate', 'The coach should avoid all criticism'], correctAnswer: 1, explanation: 'Written communication strips away 70-93% of emotional meaning. Critical feedback needs face-to-face or video delivery where tone conveys intent.' },
    { type: 'multiple_choice', question: 'What is the purpose of paraphrasing in active listening?', options: ['To repeat what was said word-for-word', 'To confirm understanding by restating the essence in your own words — showing you processed the message', 'To buy time to think', 'To correct what was said'], correctAnswer: 1, explanation: 'Paraphrasing proves you listened and understood — "So what you\'re saying is..." — and gives the speaker a chance to clarify if needed.' },
    { type: 'multiple_choice', question: 'What is "psychological safety" in team communication?', options: ['Avoiding all conflict', 'The belief that you can speak up, disagree, or admit mistakes without punishment', 'Never giving negative feedback', 'Always being positive'], correctAnswer: 1, explanation: 'Psychological safety doesn\'t mean comfortable silence — it means the team can have difficult conversations, disagree, and be honest without fear.' },
    { type: 'multiple_choice', question: 'What communication pattern predicts relationship failure?', options: ['Disagreement', 'Gottman\'s "Four Horsemen": criticism, contempt, defensiveness, and stonewalling', 'Frequent conversation', 'Having different opinions'], correctAnswer: 1, explanation: 'Gottman\'s research identifies four patterns that predict relationship breakdown: personal criticism, contempt, defensiveness, and withdrawal from engagement.' },
    { type: 'multiple_choice', question: 'What is the "curse of knowledge" in communication?', options: ['Knowing too much is harmful', 'Once you know something, you struggle to remember what it\'s like not to know it — making explanation harder', 'Knowledge curses relationships', 'Experts always communicate poorly'], correctAnswer: 1, explanation: 'The curse of knowledge: experts forget what it\'s like to be a beginner, using jargon and skipping steps that seem obvious to them but aren\'t to the listener.' },
  ]),

  // Chapter 7: Coaching Psychology
  cq(3, 7, [
    { type: 'multiple_choice', question: 'What is the coach\'s primary role according to coaching psychology?', options: ['To give advice', 'To facilitate the client\'s own thinking, insight, and action', 'To diagnose problems', 'To prescribe solutions'], correctAnswer: 1, explanation: 'Coaching facilitates — it draws out the client\'s own solutions rather than imposing the coach\'s. "What do you think?" before "Here\'s what I think."' },
    { type: 'multiple_choice', question: 'What does the GROW model stand for?', options: ['Get Results Or Withdraw', 'Goal, Reality, Options, Will (or Way forward)', 'Growth, Resilience, Outcomes, Wellbeing', 'Gather, Reflect, Outline, Work'], correctAnswer: 1, explanation: 'GROW: establish the Goal, explore the current Reality, generate Options, determine the Will (commitment and action steps).' },
    { type: 'multiple_choice', question: 'Why are powerful questions central to coaching?', options: ['They demonstrate intelligence', 'They provoke new thinking — the question itself creates insight the client couldn\'t access alone', 'They test the client\'s knowledge', 'They save time'], correctAnswer: 1, explanation: 'Powerful questions open new neural pathways: "What would you do if you knew you couldn\'t fail?" generates thinking that "What are you going to do?" doesn\'t.' },
    { type: 'multiple_choice', question: 'What is self-efficacy and why is it central to coaching?', options: ['Self-confidence in general', 'Belief in your ability to succeed in a specific situation — the strongest predictor of performance and persistence', 'Self-esteem', 'Self-awareness'], correctAnswer: 1, explanation: 'Self-efficacy (Bandura) is task-specific confidence. It predicts whether someone will start, persist, and recover from setbacks better than almost any other variable.' },
    { type: 'multiple_choice', question: 'What are the four sources of self-efficacy?', options: ['Education, intelligence, talent, support', 'Mastery experiences, vicarious learning, verbal persuasion, physiological/emotional states', 'Genes, environment, luck, effort', 'Willpower, discipline, habit, routine'], correctAnswer: 1, explanation: 'Bandura identified four sources: doing it successfully (strongest), seeing similar others succeed, encouragement from credible sources, and managing physical/emotional state.' },
    { type: 'multiple_choice', question: 'What is the most powerful source of self-efficacy?', options: ['Verbal encouragement', 'Mastery experiences — successfully completing progressively challenging tasks', 'Watching others succeed', 'Feeling confident'], correctAnswer: 1, explanation: 'Nothing builds self-efficacy like success. Design experiences where the client succeeds at challenging-but-achievable tasks — then build from there.' },
    { type: 'scenario', question: 'What coaching approach would be most effective?', scenario: 'A client says they want to lose weight but hasn\'t started. They know what to do but can\'t seem to begin.', options: ['Give them a stricter diet plan', 'Use the GROW model: clarify their real Goal, explore the Reality of barriers, generate Options they choose, and secure their commitment (Will)', 'Tell them to try harder', 'Send them motivational quotes'], correctAnswer: 1, explanation: 'The GROW model structures the conversation to move from vague desire to specific committed action — led by the client\'s own choices.' },
    { type: 'multiple_choice', question: 'What is the scaling question technique?', options: ['Weighing yourself regularly', '"On a scale of 1-10, where are you now? What would move you one point higher?" — making progress tangible and actionable', 'Rating exercises by difficulty', 'Measuring body fat percentage'], correctAnswer: 1, explanation: 'Scaling questions make abstract states concrete and identify specific, achievable next steps — "What would move you from a 5 to a 6?"' },
    { type: 'multiple_choice', question: 'Why is it important for coaches to manage their own "fix-it" reflex?', options: ['Fixing isn\'t part of coaching', 'Jumping to solutions robs the client of the insight and ownership that comes from working it out themselves', 'Coaches should always fix problems', 'The reflex is always helpful'], correctAnswer: 1, explanation: 'When the coach solves the problem, the client learns dependency. When the client solves it (with the coach\'s facilitation), they build capability and confidence.' },
    { type: 'multiple_choice', question: 'What makes the coaching relationship effective?', options: ['The coach\'s knowledge alone', 'A genuine alliance built on trust, respect, and collaborative goal-setting — the relationship IS the intervention', 'Strict professionalism', 'Frequent meetings'], correctAnswer: 1, explanation: 'Research consistently shows the coaching relationship itself — trust, respect, collaboration — accounts for more of the outcome than any specific technique.' },
  ]),

  // Chapter 8: Power & Status Dynamics
  cq(3, 8, [
    { type: 'multiple_choice', question: 'What are French and Raven\'s five bases of social power?', options: ['Money, force, charm, knowledge, position', 'Legitimate, reward, coercive, expert, referent', 'Political, economic, social, cultural, personal', 'Formal, informal, direct, indirect, implied'], correctAnswer: 1, explanation: 'French & Raven: Legitimate (position), Reward (can give), Coercive (can punish), Expert (knowledge), Referent (admiration/identification).' },
    { type: 'multiple_choice', question: 'Which forms of power produce the most durable influence?', options: ['Coercive and reward', 'Expert and referent — people follow because they want to, not because they have to', 'Legitimate and coercive', 'All forms are equally durable'], correctAnswer: 1, explanation: 'Expert (they know their stuff) and referent (I want to be like them) power produce willing, lasting compliance. Coercive power only works with surveillance.' },
    { type: 'multiple_choice', question: 'What can power do to empathy, according to research?', options: ['Increase it', 'Reduce it — power decreases perspective-taking and increases self-focused behaviour', 'No effect', 'Eliminate it completely'], correctAnswer: 1, explanation: 'Research shows power literally reduces the brain\'s mirroring activity — powerful people become less able to see situations from others\' perspectives.' },
    { type: 'multiple_choice', question: 'What is status differentiated from power?', options: ['They are the same', 'Status is voluntarily given by the group based on contribution; power can be imposed', 'Status is always higher than power', 'Power is earned; status is assigned'], correctAnswer: 1, explanation: 'Status is earned respect granted by others; power is the ability to influence regardless of others\' approval. The most effective leaders have both.' },
    { type: 'multiple_choice', question: 'What is the "power paradox"?', options: ['Power makes you stronger', 'The qualities that help you gain power (empathy, social skill) are often eroded by having power', 'Power always corrupts', 'There is no paradox'], correctAnswer: 1, explanation: 'Dacher Keltner\'s research: you gain power through social intelligence, but power can erode the very social skills that earned it.' },
    { type: 'scenario', question: 'Which type of power does this coach have?', scenario: 'A coach has no formal authority over their clients, but clients follow their advice enthusiastically because they deeply respect the coach\'s knowledge and character.', options: ['Legitimate power', 'Coercive power', 'Expert and referent power — knowledge + admiration', 'Reward power'], correctAnswer: 2, explanation: 'This coach has expert power (respected knowledge) and referent power (admired character) — the most effective and durable combination.' },
    { type: 'multiple_choice', question: 'Why does coercive power fail long-term?', options: ['It\'s not strong enough', 'Compliance only lasts while surveillance continues — remove the threat and the behaviour stops', 'It always works', 'It\'s too expensive'], correctAnswer: 1, explanation: 'Coercive power produces compliance, not commitment. People follow the rules when watched and break them when unsupervised.' },
    { type: 'multiple_choice', question: 'How can leaders maintain empathy despite gaining power?', options: ['They can\'t', 'Deliberately practise perspective-taking, maintain accountability structures, seek honest feedback, and stay connected to front-line experience', 'Avoid leadership positions', 'Only lead small groups'], correctAnswer: 1, explanation: 'Maintaining empathy in power requires deliberate effort: seeking feedback, staying connected to others\' experiences, and having people who will tell you the truth.' },
    { type: 'multiple_choice', question: 'What is the most effective way to build expert power?', options: ['Claim expertise publicly', 'Demonstrate competence consistently through actions and results, not self-promotion', 'Get certifications', 'Tell people about your qualifications'], correctAnswer: 1, explanation: 'Expert power is demonstrated, not claimed. Consistently showing competence through results builds credibility that credentials alone cannot.' },
    { type: 'multiple_choice', question: 'What determines whether power corrupts or empowers?', options: ['The amount of power', 'The person\'s values and the accountability structures around them', 'Power always corrupts', 'Nothing can prevent corruption'], correctAnswer: 1, explanation: 'Power amplifies existing tendencies. Strong values + accountability = empowering leadership. Weak values + no accountability = corruption.' },
  ]),

  // Chapter 9: Building Communities
  cq(3, 9, [
    { type: 'multiple_choice', question: 'What is psychological sense of community?', options: ['Living near other people', 'The feeling that one matters to the group and that needs will be met through belonging', 'Having a large social media following', 'Being part of an organisation'], correctAnswer: 1, explanation: 'McMillan & Chavis: psychological community = membership (belonging), influence (mattering), integration (needs met), and shared emotional connection.' },
    { type: 'multiple_choice', question: 'What is the "mere belonging" effect?', options: ['Joining a group without contributing', 'Even minimal group membership improves motivation, persistence, and performance', 'Being a passive member', 'Attending without participating'], correctAnswer: 1, explanation: 'Research shows that even minimal social belonging — simply feeling part of a group — measurably increases motivation and persistence.' },
    { type: 'multiple_choice', question: 'What is the best predictor of whether someone will maintain a new behaviour?', options: ['Their willpower', 'Whether they have a community that supports and models that behaviour', 'Their knowledge', 'Their fitness level'], correctAnswer: 1, explanation: 'Community is the strongest predictor of long-term behaviour maintenance. People who exercise in communities maintain it far longer than solo exercisers.' },
    { type: 'multiple_choice', question: 'What is the "social cure" evidence?', options: ['Social media improves health', 'Meaningful group membership independently reduces depression, anxiety, and cognitive decline', 'Socialising cures all illness', 'Online communities are harmful'], correctAnswer: 1, explanation: 'The "social cure" research demonstrates that group membership is independently health-protective — as powerful as exercise or diet for some conditions.' },
    { type: 'multiple_choice', question: 'What makes a community ritual effective?', options: ['It must be religious', 'It creates shared experience — regular, repeated activities that mark belonging (e.g., Friday workout, group motto)', 'It must be complex', 'It only works for large groups'], correctAnswer: 1, explanation: 'Rituals build shared identity and emotional connection. They can be simple (a group check-in, a weekly challenge) but must be consistent.' },
    { type: 'multiple_choice', question: 'What is Dunbar\'s number and its relevance to community building?', options: ['The maximum group size is 10', 'Humans can maintain approximately 150 stable social relationships — communities above this size need sub-groups', 'There is no limit to social connections', 'The ideal group size is 50'], correctAnswer: 1, explanation: 'Dunbar\'s number (~150) reflects cognitive limits on social relationships. Larger communities need sub-groups (classes, teams, cohorts) to maintain genuine connection.' },
    { type: 'scenario', question: 'What community-building principle would help most?', scenario: 'A gym has 300 members but low retention. Members come in, train alone, and leave. There\'s no social interaction or sense of belonging.', options: ['Lower the price', 'Create structured social elements: group classes, member challenges, welcome rituals, and community events that build identity and belonging', 'Better equipment', 'Longer opening hours'], correctAnswer: 1, explanation: 'The gym is a facility, not a community. Building belonging (group elements, rituals, identity) would transform retention because people stay for people, not equipment.' },
    { type: 'multiple_choice', question: 'What is the role of shared identity in community?', options: ['It\'s nice but not necessary', 'Shared identity transforms "those people" into "my people" — driving loyalty, mutual support, and collective action', 'It only matters for sports teams', 'It creates exclusion'], correctAnswer: 1, explanation: 'Shared identity ("We are UNBREAKABLE") transforms individuals into a collective with mutual investment. Identity is the engine of community.' },
    { type: 'multiple_choice', question: 'What is the primary reason people leave fitness programmes?', options: ['Cost', 'Lack of social connection and belonging — they didn\'t feel part of something', 'Poor equipment', 'Inconvenient location'], correctAnswer: 1, explanation: 'Research consistently shows social factors outweigh practical ones in exercise dropout. People who feel they belong stay; those who don\'t, leave.' },
    { type: 'multiple_choice', question: 'How should a community handle new members?', options: ['Let them figure it out', 'Intentional onboarding: welcome personally, introduce to existing members, give a clear first step, and follow up within 48 hours', 'Give them a rulebook', 'Wait for them to introduce themselves'], correctAnswer: 1, explanation: 'The first 48 hours determine whether a new member feels they belong. Intentional onboarding — welcome, introduction, clear next step, follow-up — dramatically improves retention.' },
  ]),
];
