import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const sportBoxingUnit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What peak force can elite boxers generate in a single punch?', options: ['50kg', '100kg', 'Over 400kg', '1000kg'], correctAnswer: 2, explanation: 'Elite boxers can generate over 400kg of peak force in a single punch.' },
    { type: 'multiple_choice', question: 'What heart rate range is sustained during competitive boxing?', options: ['60-70% max', '70-80% max', '85-95% max', '100% constant'], correctAnswer: 2, explanation: 'Competitive boxing sustains heart rates of 85-95% of maximum.' },
    { type: 'multiple_choice', question: 'What blood lactate levels have been recorded in elite boxers?', options: ['2-4 mmol/L', '5-8 mmol/L', '10-14 mmol/L', '20+ mmol/L'], correctAnswer: 2, explanation: 'Boxing produces some of the highest lactate levels in sport at 10-14 mmol/L.' },
    { type: 'multiple_choice', question: 'Where does a punch begin in the kinetic chain?', options: ['The shoulder', 'The fist', 'The feet', 'The elbow'], correctAnswer: 2, explanation: 'A punch begins at the feet and travels through the hips, core, and shoulders.' },
    { type: 'multiple_choice', question: 'What type of sport is boxing classified as?', options: ['Pure endurance', 'Pure power', 'Intermittent high-intensity', 'Low-intensity steady state'], correctAnswer: 2, explanation: 'Boxing is a classic intermittent high-intensity sport.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What type of power is most important for punching?', options: ['Vertical power', 'Rotational power', 'Isometric strength', 'Grip strength'], correctAnswer: 1, explanation: 'Every punch is a rotation — rotational power is the foundation of punching.' },
    { type: 'multiple_choice', question: 'What should the priority be when training med ball rotational throws?', options: ['Maximum weight', 'Speed of rotation with moderate weight', 'Slow controlled movement', 'High volume'], correctAnswer: 1, explanation: 'Train rotational throws at maximum velocity with moderate weights.' },
    { type: 'multiple_choice', question: 'What minimum squat strength should a boxer target?', options: ['0.5x bodyweight', '1x bodyweight', '1.5x bodyweight', '3x bodyweight'], correctAnswer: 2, explanation: '1.5x bodyweight squat provides the leg drive platform for powerful punching.' },
    { type: 'multiple_choice', question: 'Why is upper-body pulling important for boxers?', options: ['It builds bigger arms', 'It protects shoulders and retracts the arm after each punch', 'It improves punching technique', 'It is not important'], correctAnswer: 1, explanation: 'Pulling strengthens the posterior shoulder and balances the heavy pressing demands of punching.' },
    { type: 'multiple_choice', question: 'What should happen if gym work impairs sparring quality?', options: ['Train harder in the gym', 'Reduce gym volume immediately', 'Add more cardio', 'Ignore it'], correctAnswer: 1, explanation: 'The ring always takes priority — gym work must support, not impair, boxing training.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What kills hand speed in boxing?', options: ['Light gloves', 'Relaxation', 'Muscular tension', 'Fatigue only'], correctAnswer: 2, explanation: 'Tension kills speed — the fastest punchers are relaxed until the moment of impact.' },
    { type: 'multiple_choice', question: 'What separates elite perceptual speed from average?', options: ['Faster physical reflexes', 'Pattern recognition from processing thousands of hours of combat', 'Better eyesight', 'Younger age'], correctAnswer: 1, explanation: 'Elite boxers recognise patterns earlier, not physically react faster.' },
    { type: 'multiple_choice', question: 'What is the best form of defence in boxing?', options: ['Blocking with gloves', 'Not being where the punch arrives', 'Always moving backwards', 'Covering up'], correctAnswer: 1, explanation: 'The best defence is positional — not being where the punch lands.' },
    { type: 'multiple_choice', question: 'What is the most effective footwork training for boxing?', options: ['Ladder drills only', 'Contextual practice in sparring situations', 'Running long distances', 'Static balance work'], correctAnswer: 1, explanation: 'Contextual footwork training with tactical purpose transfers best to the ring.' },
    { type: 'multiple_choice', question: 'What makes good footwork valuable in boxing?', options: ['It looks impressive', 'It creates angles, maintains distance, and positions you to attack while being hard to hit', 'It burns more calories', 'It is only for defensive fighters'], correctAnswer: 1, explanation: 'Footwork creates tactical advantages in both attack and defence.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What percentage of max heart rate should boxing interval work reach?', options: ['60-70%', '70-80%', '85-95%', '100% constant'], correctAnswer: 2, explanation: 'Work periods should reach 85-95% max HR with recovery to 65-75%.' },
    { type: 'multiple_choice', question: 'Why should sparring not be the primary conditioning method?', options: ['It is not intense enough', 'Going in under-conditioned creates bad defensive habits and injury risk', 'It does not raise heart rate', 'Coaches do not allow it'], correctAnswer: 1, explanation: 'Under-conditioned sparring leads to cutting corners defensively.' },
    { type: 'multiple_choice', question: 'What indicates improving boxing conditioning?', options: ['Faster punching speed', 'Faster recovery heart rate between rounds', 'Being able to run further', 'Sweating less'], correctAnswer: 1, explanation: 'Recovery heart rate speed indicates cardiovascular conditioning level.' },
    { type: 'multiple_choice', question: 'How often should anaerobic capacity training be performed?', options: ['Every day', '1-2 sessions per week', '3-4 sessions per week', 'Only during fight camp'], correctAnswer: 1, explanation: 'Anaerobic training is very demanding and should be limited to 1-2 sessions weekly.' },
    { type: 'multiple_choice', question: 'What is the role of roadwork in boxing conditioning?', options: ['It is outdated and unnecessary', 'It builds the aerobic base that fuels recovery between exchanges', 'It develops punching power', 'It only helps with weight cutting'], correctAnswer: 1, explanation: 'Roadwork builds the cardiovascular foundation for inter-round and inter-exchange recovery.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What percentage of boxing injuries involve the hands?', options: ['10-20%', '20-30%', '40-50%', '60-70%'], correctAnswer: 2, explanation: 'Hand injuries account for 40-50% of all boxing injuries.' },
    { type: 'multiple_choice', question: 'What is the primary cause of metacarpal fractures in boxing?', options: ['Punching too hard', 'Landing with incorrect fist alignment', 'Not wearing wraps', 'Heavy bag work'], correctAnswer: 1, explanation: 'Incorrect fist alignment at impact is the primary cause of hand fractures.' },
    { type: 'multiple_choice', question: 'How does neck strengthening reduce concussion risk?', options: ['It prevents punches from landing', 'It decelerates the head more effectively after impact, reducing rotational brain forces', 'It makes the skull stronger', 'It does not reduce risk'], correctAnswer: 1, explanation: 'A stronger neck slows head acceleration after impact.' },
    { type: 'multiple_choice', question: 'What pulling-to-pushing ratio protects boxer shoulders?', options: ['1:1', '1:2', '2:1 pulling to pushing', '3:1'], correctAnswer: 2, explanation: '2:1 pulling-to-pushing strengthens the posterior shoulder against repetitive punching demands.' },
    { type: 'multiple_choice', question: 'How should hard sparring frequency be managed?', options: ['Every training session', '1-2 sessions per week maximum', 'Only before fights', 'Hard sparring should be avoided entirely'], correctAnswer: 1, explanation: 'Limiting hard sparring to 1-2 weekly sessions manages cumulative brain impact.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What protein intake is recommended for boxers in training?', options: ['1.0-1.2g/kg', '1.4-1.6g/kg', '2.0-2.4g/kg', '3.0g/kg'], correctAnswer: 2, explanation: '2.0-2.4g/kg supports recovery from intense boxing training demands.' },
    { type: 'multiple_choice', question: 'What is the maximum safe water weight cut for boxing?', options: ['1-2%', '3-4%', '5-7%', '10-12%'], correctAnswer: 2, explanation: 'Never cut more than 5-7% bodyweight through water manipulation.' },
    { type: 'multiple_choice', question: 'What is water loading used for in weight cutting?', options: ['It increases body weight', 'It tricks the body into flushing excess water when intake is reduced', 'It improves hydration permanently', 'It has no effect'], correctAnswer: 1, explanation: 'Water loading upregulates excretion; when intake drops, the body continues flushing.' },
    { type: 'multiple_choice', question: 'What should be avoided in the post-weigh-in meal?', options: ['Carbohydrates', 'Protein', 'High-fat and high-fibre foods that slow gastric emptying', 'Water'], correctAnswer: 2, explanation: 'High-fat and high-fibre foods slow digestion when rapid refuelling is needed.' },
    { type: 'multiple_choice', question: 'Why is crash dieting dangerous for boxers?', options: ['It causes weight gain', 'It reduces power, impairs reaction time, and compromises immune function', 'It is too slow', 'It only affects mood'], correctAnswer: 1, explanation: 'Crash dieting destroys the physical qualities needed for boxing performance.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'How should pre-fight anxiety be reframed?', options: ['Suppress it completely', 'As excitement — the physical symptoms are identical', 'Ignore it entirely', 'Medicate it away'], correctAnswer: 1, explanation: 'Reframing anxiety as excitement improves performance — the physiology is the same.' },
    { type: 'multiple_choice', question: 'How is in-fight composure developed?', options: ['Through meditation only', 'Progressive exposure to increasing sparring intensity over time', 'Reading books about fighting', 'It cannot be trained'], correctAnswer: 1, explanation: 'Graduated exposure to contact builds comfort and rational decision-making under fire.' },
    { type: 'multiple_choice', question: 'What is the three-round reset?', options: ['Resting for three rounds', 'Assessing past rounds, identifying one adjustment, committing to the next three rounds', 'Winning three rounds in a row', 'A specific combination'], correctAnswer: 1, explanation: 'The reset prevents dwelling on lost rounds and enables tactical adjustment.' },
    { type: 'multiple_choice', question: 'What defines courage in boxing?', options: ['Never feeling fear', 'Action in the presence of fear', 'Physical toughness', 'Ignoring pain'], correctAnswer: 1, explanation: 'Courage is choosing to act despite fear, not the absence of fear.' },
    { type: 'multiple_choice', question: 'Why is boxing uniquely demanding mentally?', options: ['It requires mathematics', 'You must maintain composure and execute tactics while someone is physically trying to hurt you', 'It has long training sessions', 'The weight cutting is difficult'], correctAnswer: 1, explanation: 'Boxing demands rational performance under genuine physical threat.' },
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'What are the three phases of a fight camp?', options: ['Easy, medium, hard', 'Base Building, Intensification, Sharpening', 'Cardio, strength, sparring', 'Diet, training, recovery'], correctAnswer: 1, explanation: 'Fight camps progress through structured phases toward peaking on fight night.' },
    { type: 'multiple_choice', question: 'When should the last hard sparring session occur?', options: ['3 days before the fight', 'The day before', 'At least 7 days before fight night', 'The morning of the fight'], correctAnswer: 2, explanation: 'No hard sparring in the final 7 days protects the brain for competition.' },
    { type: 'multiple_choice', question: 'What sign indicates a successful taper?', options: ['Feeling exhausted', 'Feeling restless, eager, and slightly undertrained', 'Peak muscle soreness', 'Maximum weight loss'], correctAnswer: 1, explanation: 'Feeling slightly undertrained and restless indicates the taper has worked.' },
    { type: 'multiple_choice', question: 'How should gym training change across a fight camp?', options: ['Stay constant at 4x/week', 'Reduce from 3x/week to 1-2x/week as sparring increases', 'Increase throughout camp', 'Gym should be eliminated entirely'], correctAnswer: 1, explanation: 'Gym volume reduces progressively as sparring and tactical preparation increase.' },
    { type: 'multiple_choice', question: 'What is the most common fight camp mistake?', options: ['Not training enough', 'Starting too hard and burning out by week 6', 'Too much rest', 'Not enough sparring'], correctAnswer: 1, explanation: 'Starting at peak intensity leads to burnout before the fight arrives.' },
  ]),
];