import type { UnitAssessment } from '../types';

export const mindsetL2Unit1Assessment: UnitAssessment = {
  unitNumber: 1, title: 'Unit 1 Assessment — Foundations of Mental Resilience',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is mental resilience?', options: ['Never feeling stressed', 'Being physically strong', 'The ability to adapt to stress, recover from setbacks, and maintain progress', 'Ignoring your emotions'], correctAnswer: 2, explanation: 'Resilience is about adaptation and recovery, not suppression or invincibility.' },
    { type: 'multiple_choice', question: 'What triggers the fight-or-flight response?', options: ['Only physical danger', 'The sympathetic nervous system via the amygdala', 'Deep breathing', 'The parasympathetic nervous system'], correctAnswer: 1, explanation: 'The amygdala detects threats and activates the sympathetic nervous system.' },
    { type: 'multiple_choice', question: 'What is the primary hormone associated with chronic stress?', options: ['Cortisol', 'Testosterone', 'Dopamine', 'Serotonin'], correctAnswer: 0, explanation: 'Cortisol is the primary chronic stress hormone with wide-ranging negative effects when chronically elevated.' },
    { type: 'multiple_choice', question: 'Which nerve is the primary pathway of the parasympathetic nervous system?', options: ['Sciatic nerve', 'Ulnar nerve', 'Femoral nerve', 'Vagus nerve'], correctAnswer: 3, explanation: 'The vagus nerve connects to heart, lungs, and digestive system, driving rest-and-digest responses.' },
    { type: 'multiple_choice', question: 'How does an extended exhale affect the nervous system?', options: ['Increases cortisol', 'Has no effect', 'Activates sympathetic tone', 'Activates parasympathetic tone via vagal stimulation'], correctAnswer: 3, explanation: 'Extended exhales stimulate the vagus nerve and shift toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: "In Carol Dweck\'s theory, what characterises a growth mindset?", options: ['Believing abilities are developed through effort and learning', 'Believing abilities are fixed', 'Ignoring feedback', 'Avoiding challenges'], correctAnswer: 0, explanation: 'Growth mindset sees abilities as developable through effort, learning, and persistence.' },
    { type: 'multiple_choice', question: 'Which type of goal is entirely within your control?', options: ['Result goal', 'Outcome goal', 'Process goal', 'Performance goal'], correctAnswer: 2, explanation: 'Process goals (daily actions) are fully controllable, unlike outcomes which depend on external factors.' },
    { type: 'multiple_choice', question: 'Which sleep stage is critical for physical recovery and growth hormone release?', options: ['REM sleep', 'All stages equally', 'Deep sleep (N3)', 'Light sleep (N1)'], correctAnswer: 2, explanation: 'Deep sleep (N3) is when growth hormone is released and physical tissue repair occurs.' },
    { type: 'multiple_choice', question: 'How long is a complete sleep cycle?', options: ['60 minutes', '30 minutes', 'Approximately 90 minutes', '3 hours'], correctAnswer: 2, explanation: 'A complete cycle through all sleep stages takes approximately 90 minutes.' },
    { type: 'scenario', scenario: 'Someone says "I am just not a morning person" when discussing building a morning routine.', question: 'What type of mindset does this reflect?', options: ['Realistic assessment', 'Process-oriented thinking', 'Growth mindset', 'Fixed mindset'], correctAnswer: 3, explanation: 'Framing a changeable behaviour as a fixed trait (\'I am not...") reflects a fixed mindset.' },
    { type: 'multiple_choice', question: 'What should caffeine intake be limited to for good sleep?', options: ['No limit needed', 'After 8pm', 'After 2pm', 'After 6pm'], correctAnswer: 2, explanation: 'Caffeine has a half-life of 5–6 hours, so avoiding it after 2pm protects sleep quality.' },
    { type: 'multiple_choice', question: 'What bedroom temperature is optimal for sleep?', options: ['20–22°C', '16–18°C', '12–14°C', '24–26°C'], correctAnswer: 1, explanation: 'A cool bedroom (16–18°C) supports the core temperature drop needed for sleep onset.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "What is the 'fight or flight' response?", options: ["The body's stress response activating the sympathetic nervous system", 'A relaxation technique', 'A type of breathing exercise', 'A mindset training method'], correctAnswer: 0, explanation: "The fight or flight response is the body's automatic stress reaction, activating the sympathetic nervous system to prepare for perceived danger." },
    { type: 'multiple_choice', question: "Which branch of the autonomic nervous system promotes rest and recovery?", options: ['Sympathetic', 'Somatic', 'Central', 'Parasympathetic'], correctAnswer: 3, explanation: "The parasympathetic nervous system \u2014 often called 'rest and digest' \u2014 slows heart rate, lowers blood pressure, and promotes recovery." },
    { type: 'multiple_choice', question: "A growth mindset is characterised by:", options: ['Believing abilities can be developed through effort and learning', 'Focusing only on outcomes, not processes', 'Avoiding challenges to prevent failure', 'Believing talent is fixed and unchangeable'], correctAnswer: 0, explanation: "Carol Dweck's research shows that a growth mindset \u2014 believing abilities are developable \u2014 leads to greater resilience, effort, and achievement." },
    { type: 'multiple_choice', question: "What is the recommended amount of sleep for adult cognitive and physical recovery?", options: ["4\u20135 hours", "7\u20139 hours", "10\u201312 hours", "As little as possible"], correctAnswer: 1, explanation: "Most adults need 7\u20139 hours of quality sleep for optimal cognitive function, emotional regulation, hormonal balance, and physical recovery." },
    { type: 'multiple_choice', question: "Which hormone is most associated with chronic stress?", options: ["Testosterone", "Cortisol", "Insulin", "Melatonin"], correctAnswer: 1, explanation: "Cortisol is the primary stress hormone. While useful in acute situations, chronically elevated cortisol can impair immune function, sleep, and recovery." },
    { type: 'multiple_choice', question: "SMART goals must be:", options: ['Simple, Motivating, Abstract, Relaxed, Theoretical', 'Short, Mild, Acceptable, Random, Temporary', 'Specific, Measurable, Achievable, Relevant, Time-bound', 'Secret, Massive, Aggressive, Rigid, Timeless'], correctAnswer: 2, explanation: 'SMART goals provide structure and clarity: Specific, Measurable, Achievable, Relevant, and Time-bound.' },
    { type: 'multiple_choice', question: "Which sleep stage is most important for physical recovery?", options: ['Light sleep (Stage 1)', 'Falling asleep (hypnagogic)', 'REM sleep', 'Deep sleep (Stage 3\u20134)'], correctAnswer: 3, explanation: 'Deep sleep (slow-wave sleep) is when growth hormone is released, tissues repair, and the immune system strengthens \u2014 critical for physical recovery.' },
    { type: 'multiple_choice', question: "What does resilience mean in a mental performance context?", options: ['The ability to adapt and recover from adversity, stress, and setbacks', 'Never experiencing stress or difficulty', 'Avoiding all challenges', 'Being emotionally numb'], correctAnswer: 0, explanation: "Resilience is not the absence of difficulty \u2014 it's the capacity to bounce back, adapt, and grow through challenges." },

  ],
};
