import type { UnitAssessment } from '../types';
import { mindsetL2Unit1Assessment } from './assessments';
import { mindsetL2Unit2Assessment } from './unit2-assessments';
import { mindsetL2Unit3Assessment } from './unit3-assessments';
import { mindsetL2Unit4Assessment } from './unit4-assessments';

export const mindsetL2FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 2 Mindset Final Assessment',
  passMarkPercent: 80, pickCount: 40,
  questions: [
    ...mindsetL2Unit1Assessment.questions,
    ...mindsetL2Unit2Assessment.questions,
    ...mindsetL2Unit3Assessment.questions,
    ...mindsetL2Unit4Assessment.questions,
    // ── Cross-unit final questions ──
    { type: 'scenario', question: 'What is the most appropriate first step?', scenario: 'A client tells you they feel overwhelmed with work stress and have been sleeping poorly for weeks. They want to start a mental resilience programme.', options: ['Recommend medication', 'Address sleep hygiene first — recovery is the foundation for all mental performance', 'Tell them to just push through', 'Start with an intense breathwork session'], correctAnswer: 1, explanation: 'Sleep is foundational to mental resilience. Without adequate recovery, other interventions (breathing, focus, mindset) will have limited impact. Address the basics first.' },
    { type: 'multiple_choice', question: 'Which combination best supports daily mental resilience?', options: ['Morning routine, breathwork practice, journaling, and adequate sleep', 'Intense training every day with no rest days', 'Cold showers only', 'Reading motivational quotes'], correctAnswer: 0, explanation: 'A comprehensive resilience practice combines structure (morning routine), nervous system regulation (breathwork), self-reflection (journaling), and recovery (sleep).' },
    { type: 'multiple_choice', question: 'The parasympathetic nervous system is best activated by:', options: ['Rapid, shallow breathing', 'Intense exercise', 'Caffeine consumption', 'Extended, slow exhalation'], correctAnswer: 3, explanation: 'Extended exhalation activates the vagus nerve, stimulating the parasympathetic (rest and digest) branch of the autonomic nervous system.' },
    { type: 'scenario', question: 'What should you recommend?', scenario: 'Someone has been consistently building habits for 3 months but has just experienced a major life setback. They feel like giving up on all their progress.', options: ['Ignore the setback and continue as normal', 'Tell them to train harder to distract from the problem', 'Suggest scaling down to non-negotiable minimums while they navigate the setback', 'Suggest they take a complete break from everything'], correctAnswer: 2, explanation: 'During setbacks, scaling to non-negotiable minimums (e.g., 5-min walk, 2-min breathing) maintains identity and momentum without adding overwhelm. Full stops risk losing all progress.' },
    { type: 'multiple_choice', question: 'Box breathing is effective because it:', options: ['Creates equal inhale-hold-exhale-hold phases that balance the autonomic nervous system', 'Only works during meditation', 'Should only be done lying down', 'Is the fastest breathing technique'], correctAnswer: 0, explanation: 'Box breathing (4-4-4-4) creates balanced autonomic activation — the holds give the nervous system time to regulate, making it effective for both calming and focus.' },
    { type: 'multiple_choice', question: 'Cortisol is most elevated:', options: ['In the morning (cortisol awakening response) and during acute stress', 'Only during exercise', 'During deep sleep', 'Only when eating'], correctAnswer: 0, explanation: 'Cortisol follows a diurnal rhythm — highest in the morning (helping you wake up) and elevated acutely during stress. Chronic elevation is harmful.' },
    { type: 'multiple_choice', question: 'The habit loop consists of:', options: ['Cue, routine, reward', 'Start, middle, end', 'Goal, plan, execution', 'Thought, action, consequence'], correctAnswer: 0, explanation: 'The habit loop (cue → routine → reward) explains how habits form and persist. Understanding it allows you to redesign habits by changing the routine while keeping the cue and reward.' },
    { type: 'scenario', question: 'What would you suggest?', scenario: 'A client struggles with consistency — they do well for two weeks then fall off completely. They say they lack motivation.', options: ['Help them build discipline through habit stacking, non-negotiables, and environment design', 'Suggest they only train when they feel motivated', 'Tell them motivation is all they need', 'Double their training load to force commitment'], correctAnswer: 0, explanation: 'Motivation fluctuates. Discipline systems — habit stacking (linking new behaviours to existing ones), non-negotiable minimums, and environment design — create consistency regardless of motivation.' },
    { type: 'multiple_choice', question: 'Cold exposure should be introduced:', options: ['Gradually — starting with cold shower endings (30-60 seconds) and progressively increasing', 'By jumping into ice water on the first attempt', 'By staying in cold water until numbness', 'Only in winter'], correctAnswer: 0, explanation: 'Gradual progressive overload applies to cold exposure just like physical training. Start mild, build tolerance, and never push to dangerous extremes.' },
    { type: 'multiple_choice', question: 'A growth mindset leads to:', options: ['Avoiding all failure', 'Embracing challenges as learning opportunities and persisting through setbacks', 'Never asking for help', 'Believing effort is unnecessary if you have talent'], correctAnswer: 1, explanation: 'Growth mindset (Dweck) means seeing challenges as growth opportunities, valuing effort over innate talent, and learning from failure rather than being defined by it.' },
    { type: 'multiple_choice', question: 'Emotional regulation is best described as:', options: ['Never getting angry or upset', 'Only showing positive emotions', 'Suppressing all negative emotions', 'Managing emotional responses constructively without suppression or uncontrolled expression'], correctAnswer: 3, explanation: 'Emotional regulation means acknowledging emotions, understanding their source, and choosing constructive responses — not suppressing or being controlled by them.' },
    { type: 'multiple_choice', question: 'Deep sleep is critical for:', options: ['Rapid eye movement', 'Growth hormone release, tissue repair, and immune function', 'Dream processing only', 'Burning fat'], correctAnswer: 1, explanation: 'During deep (slow-wave) sleep, growth hormone peaks, tissues repair, the immune system strengthens, and memories consolidate — essential for physical and mental recovery.' },
    { type: 'scenario', question: 'What is the best approach?', scenario: 'You want to build a visualisation practice but find it difficult to concentrate for more than a few seconds.', options: ['Start with 30-second guided visualisations and gradually extend duration as the skill develops', 'Only visualise before competitions', 'Give up — visualisation is only for naturally imaginative people', 'Force yourself to visualise for 30 minutes immediately'], correctAnswer: 0, explanation: 'Visualisation is a skill that develops with practice. Starting with brief, guided sessions builds the neural pathways needed for longer, more vivid mental rehearsal.' },
    { type: 'multiple_choice', question: 'The 2-minute rule for building habits suggests:', options: ['Start any new habit by scaling it down to a version that takes less than 2 minutes', 'Time yourself for exactly 2 minutes then stop', 'Only commit to habits for 2 minutes per day forever', 'All habits must take exactly 2 minutes'], correctAnswer: 0, explanation: 'The 2-minute rule removes friction from starting. A scaled-down version (e.g., put on running shoes vs run 5k) builds consistency, which can then naturally expand.' },
    { type: 'multiple_choice', question: 'Stress inoculation training works by:', options: ['Only talking about stress without experiencing it', 'Gradually exposing individuals to controlled stressors, building coping skills and confidence', 'Creating maximum stress to force adaptation', 'Avoiding all stress entirely'], correctAnswer: 1, explanation: 'Stress inoculation training (Meichenbaum) systematically exposes individuals to manageable stressors while teaching coping strategies, building resilience through progressive challenge.' },
    { type: 'multiple_choice', question: 'Journaling is beneficial for mental resilience because:', options: ['It must be done for at least 1 hour daily', 'It is only useful for creative people', 'It replaces the need for any other practice', 'It helps externalise thoughts, identify patterns, and process emotions'], correctAnswer: 3, explanation: 'Journaling externalises internal mental content, helps identify emotional and behavioural patterns, provides perspective, and aids emotional processing — even in brief sessions.' },
    { type: 'multiple_choice', question: 'Mindfulness practice primarily develops:', options: ['Future planning skills', 'Competitive drive', 'Non-judgemental present-moment awareness', 'Physical strength'], correctAnswer: 2, explanation: 'Mindfulness is the practice of paying attention to the present moment without judgement — observing thoughts, feelings, and sensations as they arise without trying to change them.' },
    { type: 'scenario', question: 'What would you advise?', scenario: 'A friend wants to build mental resilience but says they have no time for a morning routine, meditation, journaling, and breathwork.', options: ['Tell them it is impossible without all four practices', 'Give them a 90-minute morning routine plan', 'Suggest picking one practice they can do for 5 minutes daily and building from there', 'Recommend they wake up 2 hours earlier immediately'], correctAnswer: 2, explanation: 'Consistency beats complexity. One practice done daily for 5 minutes builds more resilience than an ambitious plan that never happens. Start small, build gradually.' },
    { type: 'multiple_choice', question: 'Nasal breathing is preferred during rest and light activity because:', options: ['It filters, warms, and humidifies air while promoting nitric oxide production', 'It is faster than mouth breathing', 'It looks more professional', 'It only benefits athletes'], correctAnswer: 0, explanation: 'Nasal breathing filters pathogens, warms air to body temperature, maintains humidity, and produces nitric oxide — which aids blood vessel dilation and oxygen uptake.' },
    { type: 'multiple_choice', question: 'A personal resilience protocol is most effective when it:', options: ['Stays the same forever once established', 'Only includes physical training', 'Is copied exactly from a book or expert', 'Is personalised, covers physical and mental domains, and adapts as life changes'], correctAnswer: 3, explanation: 'Resilience is personal. An effective protocol is built around individual needs, covers multiple domains (physical, mental, social, recovery), and evolves as circumstances change.' },
  ],
};
