import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['1 minute', '5 seconds', '23 minutes', '2 minutes'], correctAnswer: 2, explanation: 'Research shows an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'Is true multitasking possible for cognitive tasks?', options: ['Yes', 'Only for experts', 'Only for women', 'No — it is rapid task switching'], correctAnswer: 3, explanation: 'The brain cannot perform two cognitively demanding tasks simultaneously.' },
    { type: 'multiple_choice', question: 'What is the Pomodoro technique?', options: ['A cooking method', 'A type of exercise', '25–50 minute focused work blocks with 5–10 minute breaks', 'A sleep protocol'], correctAnswer: 2, explanation: 'The Pomodoro technique structures work into focused blocks with strategic breaks.' },
    { type: 'multiple_choice', question: 'What is the two-minute rule?', options: ['Rest for 2 minutes', 'If a task takes less than 2 minutes, do it now; otherwise schedule it', 'Meditate for 2 minutes', 'Warm up for 2 minutes'], correctAnswer: 1, explanation: 'Quick tasks done immediately prevent them from fragmenting future attention.' },
    { type: 'multiple_choice', question: "What depletes the prefrontal cortex\'s capacity?", options: ['Exercise', 'Every decision, task switch, and distraction', 'Water intake', 'Sleep'], correctAnswer: 1, explanation: 'The prefrontal cortex operates like a battery depleted by decisions and cognitive demands.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'Why is motivation unreliable?', options: ['It is always low', 'It only works for some people', 'It does not exist', 'It is an emotion that naturally fluctuates'], correctAnswer: 3, explanation: 'Like all emotions, motivation rises and falls — systems and discipline are more consistent.' },
    { type: 'multiple_choice', question: 'What is environment design?', options: ['Interior decorating', 'Building a new house', 'Arranging your environment so desired actions are the easiest option', 'Organising your desk'], correctAnswer: 2, explanation: 'Environment design reduces willpower required by making good choices the default.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['Setting outcome goals', 'Acting consistently with who you want to become', 'Copying someone else', 'Tracking habits on an app'], correctAnswer: 1, explanation: 'Identity-based habits flow from self-concept: "I am someone who..." rather than "I want to..."' },
    { type: 'multiple_choice', question: 'What does "every action is a vote" mean?', options: ['You should vote more', 'Only big actions count', 'Actions do not matter', 'Each action reinforces the type of person you are becoming'], correctAnswer: 3, explanation: 'Small consistent actions accumulate into identity — each one is a vote for who you are becoming.' },
    { type: 'multiple_choice', question: 'What is the most effective way to train consistently?', options: ['Wait for motivation', 'Create systems that work regardless of how you feel', 'Only train when you feel great', 'Train twice as hard on good days'], correctAnswer: 1, explanation: 'Systems that operate independently of motivation produce the most consistent results.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What are the three parts of the habit loop?', options: ['Plan, Act, Review', 'Cue, Routine, Reward', 'Try, Fail, Retry', 'Start, Middle, End'], correctAnswer: 1, explanation: 'Every habit follows: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'Which brain region takes over once a habit is automatic?', options: ['Basal ganglia', 'Prefrontal cortex', 'Amygdala', 'Cerebellum'], correctAnswer: 0, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex.' },
    { type: 'multiple_choice', question: 'What is the best way to break an unwanted habit?', options: ['Punish yourself', 'Use willpower', 'Ignore it', 'Keep the cue and reward but replace the routine'], correctAnswer: 3, explanation: 'Replacing the routine while keeping the same cue and reward is the most effective strategy.' },
    { type: 'multiple_choice', question: 'What does "start absurdly small" mean?', options: ['Set tiny goals like one press-up to reduce resistance', 'Never progress', 'Only do easy things', 'Think small forever'], correctAnswer: 0, explanation: 'Absurdly small starts (one press-up, 2 minutes of journaling) build the neural pathway with minimal resistance.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Missing one day is fine but two consecutive days starts a pattern of absence', 'Always do double after missing', 'Train twice daily', 'Never miss any day'], correctAnswer: 0, explanation: 'One miss does not break a habit — but two consecutive misses establish a new pattern.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'Is emotional regulation the same as suppression?', options: ['Depends on the situation', 'No — regulation is conscious processing, not hiding emotions', 'Yes', 'Only for negative emotions'], correctAnswer: 1, explanation: 'Regulation means processing emotions consciously; suppression increases stress and impairs health.' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Changing your interpretation to change your emotional response', 'Denying reality', 'Ignoring the situation', 'Arguing with yourself'], correctAnswer: 0, explanation: 'Reappraisal changes interpretation, not facts, producing a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does STOP stand for?', options: ['Stop, Think, Observe, Proceed', 'Stop, Take a breath, Observe, Proceed', 'Slow, Think, Operate, Plan', 'Start, Try, Overcome, Persist'], correctAnswer: 1, explanation: 'Stop, Take a breath, Observe your feelings, Proceed with conscious choice.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Writing feelings on a label', 'Rating emotions 1-10', 'Naming your emotions to reduce their intensity', 'Describing emotions to others'], correctAnswer: 2, explanation: 'Naming emotions ("I notice I am feeling angry") activates the prefrontal cortex and reduces intensity.' },
    { type: 'multiple_choice', question: 'What creates the "space" between stimulus and response?', options: ['Distance', 'Time', 'Conscious awareness and deliberate pausing', 'Other people'], correctAnswer: 2, explanation: 'Conscious awareness — pausing before reacting — creates the space for intentional response.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'Why does visualisation work?', options: ['It activates the same neural pathways as physical performance', 'It replaces practice', 'It is magic', 'It only works for athletes'], correctAnswer: 0, explanation: 'Mental rehearsal activates motor cortex regions similar to actual movement.' },
    { type: 'multiple_choice', question: 'Which type of visualisation improves performance more?', options: ['Process visualisation', 'Outcome visualisation', 'Neither works', 'Both equally'], correctAnswer: 0, explanation: 'Process visualisation (imagining steps and challenges) is more effective than imagining the end result.' },
    { type: 'multiple_choice', question: 'Should you include challenges in your visualisation?', options: ['No — only positive outcomes', 'Only if you expect problems', 'Challenges are too negative', 'Yes — visualise encountering and overcoming difficulty'], correctAnswer: 3, explanation: 'Including challenges in visualisation prepares you to respond effectively during actual performance.' },
    { type: 'multiple_choice', question: 'How long should a visualisation session last?', options: ['1 hour', '1 minute', '5–10 minutes', '30 minutes'], correctAnswer: 2, explanation: '5–10 minutes per session, practised 3–5 times before an event, is the evidence-based approach.' },
    { type: 'multiple_choice', question: 'Can outcome visualisation actually reduce effort?', options: ['Yes — it can create a premature sense of achievement', 'It always increases effort', 'No', 'Only for lazy people'], correctAnswer: 0, explanation: 'Research shows imagining the end result can reduce effort by creating premature satisfaction.' },
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'How many times per day does the average person check their phone?', options: ['About 20 times', 'About 96 times', 'About 10 times', 'About 200 times'], correctAnswer: 1, explanation: 'Research shows the average person checks their phone approximately 96 times per day — roughly once every 10 minutes of waking time.' },
    { type: 'multiple_choice', question: 'Why is social media addictive from a neurochemical perspective?', options: ['It releases serotonin', 'It provides intermittent dopamine reinforcement — the same pattern as slot machines', 'It increases testosterone', 'It lowers cortisol'], correctAnswer: 1, explanation: 'Social media provides unpredictable rewards (likes, comments, interesting content) that trigger dopamine release through intermittent reinforcement — the most addictive reward pattern known.' },
    { type: 'multiple_choice', question: 'What is the "phone-free first hour" strategy?', options: ['Turning off your phone for 1 hour during the day', 'Not checking your phone for the first 60 minutes after waking', 'Limiting total phone use to 1 hour', 'Only using your phone for calls in the first hour'], correctAnswer: 1, explanation: 'Avoiding phone use for the first 60 minutes after waking protects your morning from being reactive and allows you to start the day with intention.' },
    { type: 'scenario', question: 'What is the most likely explanation for these symptoms?', scenario: 'A person reports difficulty concentrating on reading, constant urge to check notifications, and finding slow activities boring — despite previously enjoying them.', options: ['They have developed a reading disorder', 'Their dopamine baseline has been elevated by constant digital stimulation, making slower activities feel unrewarding', 'They need more caffeine', 'They are simply ageing'], correctAnswer: 1, explanation: 'Constant low-level dopamine stimulation from screens raises the baseline expectation for novelty, making naturally rewarding but slower activities feel boring by comparison.' },
    { type: 'multiple_choice', question: 'How does phone use between sets affect training quality?', options: ['It has no effect', 'It improves rest periods', 'It worsens mind-muscle connection, extends rest periods, and lowers session quality', 'It only affects beginners'], correctAnswer: 2, explanation: 'Scrolling between sets fragments attention, weakens the mind-muscle connection, and typically leads to longer, unstructured rest periods — all reducing overall session quality.' },
  ]),
  cq(3, 7, [
    { type: 'multiple_choice', question: 'Procrastination is most accurately an issue of what?', options: ['Time management', 'Laziness', 'Emotional regulation', 'Intelligence'], correctAnswer: 2, explanation: 'Research shows procrastination is an emotional regulation problem — the brain seeks relief from negative emotions by switching to pleasant tasks.' },
    { type: 'multiple_choice', question: 'What is the two-minute rule for overcoming procrastination?', options: ['Only work on tasks that take two minutes', 'Commit to starting for just two minutes to build momentum', 'Take a two-minute break every hour', 'Procrastinate for only two minutes'], correctAnswer: 1, explanation: 'Starting is the hardest part — committing to just two minutes often generates momentum that carries you forward.' },
    { type: 'multiple_choice', question: 'Why do vague tasks increase procrastination?', options: ['They are too easy', 'The brain resists starting because it does not know what to do', 'They take too long', 'They are more enjoyable'], correctAnswer: 1, explanation: 'Task ambiguity creates resistance because the brain cannot determine the first step, making the task feel overwhelming.' },
    { type: 'multiple_choice', question: 'What should you do when you catch yourself procrastinating?', options: ['Criticise yourself harshly to prevent it next time', 'Acknowledge it, understand the trigger, and restart without drama', 'Give up for the day', 'Switch to a completely different goal'], correctAnswer: 1, explanation: 'Self-criticism after procrastination makes it worse. Acknowledge, understand the emotional trigger, and restart.' },
    { type: 'multiple_choice', question: 'What generates motivation according to the chapter?', options: ['Watching motivational videos', 'Waiting until you feel ready', 'Taking action — action generates motivation, not the other way around', 'Having a clear goal'], correctAnswer: 2, explanation: 'You do not need to feel motivated to start — starting creates the motivation. Action precedes feeling.' },
    { type: 'multiple_choice', question: 'What is time-boxing?', options: ['Scheduling your entire day in 5-minute increments', 'Committing to a fixed time window rather than a fixed output', 'Only working during boxing training', 'Setting unrealistic deadlines'], correctAnswer: 1, explanation: 'Time-boxing means committing to a set period (e.g., 25 minutes) rather than a specific result, keeping the task manageable.' },
  ]),
  cq(3, 8, [
    { type: 'multiple_choice', question: 'What does having an accountability appointment increase goal completion probability to?', options: ['50%', '75%', '95%', '65%'], correctAnswer: 2, explanation: 'The American Society of Training and Development found accountability appointments increase goal completion from 65% to 95%.' },
    { type: 'multiple_choice', question: 'What type of accountability is most underrated?', options: ['Public accountability', 'Coach accountability', 'Environmental accountability — designing defaults', 'Self-accountability'], correctAnswer: 2, explanation: 'Environmental accountability works without requiring willpower — it makes the desired action the default.' },
    { type: 'multiple_choice', question: 'What should you track instead of just outcomes?', options: ['Only weight loss', 'Lead indicators — actions within your control', 'Social media followers', 'Nothing — tracking is unnecessary'], correctAnswer: 1, explanation: 'Lead indicators (sessions completed, hours studied) are within your control and predict outcomes better than tracking outcomes alone.' },
    { type: 'multiple_choice', question: 'What adherence level should you celebrate?', options: ['Only 100% perfection', '85% — demanding perfection creates all-or-nothing thinking', '50% is sufficient', 'Any level is fine'], correctAnswer: 1, explanation: 'Hitting 85% adherence is excellent. Demanding 100% creates all-or-nothing thinking that collapses at the first miss.' },
    { type: 'multiple_choice', question: 'What separates people who achieve goals from those who do not?', options: ['Talent', 'Motivation', 'Systems that make consistency the default', 'Willpower'], correctAnswer: 2, explanation: 'The difference is rarely talent or knowledge — it is systems that make consistency the default, making motivation optional.' },
  ]),
];
