import type { UnitAssessment } from '../types';

export const mindsetL2Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Practical Application & Daily Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most important factor in a morning routine?', options: ['Consistency', 'Waking early', 'Duration', 'Complexity'], correctAnswer: 0, explanation: 'A consistent short routine is far more effective than an elaborate one that is not sustained.' },
      { type: 'multiple_choice', question: "Why should you avoid checking your phone first thing in the morning?", options: ['Option D', 'Option C', 'Option A', 'Option B'], correctAnswer: 2, explanation: "Checking your phone floods your brain with external demands, preventing proactive intention-setting." },
    { type: 'multiple_choice', question: 'What is stress inoculation training?', options: ['Taking stress medication', 'Avoiding all stress', 'Extreme suffering', 'Controlled exposure to manageable stress to build resilience'], correctAnswer: 3, explanation: 'SIT builds resilience through progressive, controlled exposure — like a vaccine for your nervous system.' },
    { type: 'multiple_choice', question: 'What are the three phases of stress inoculation?', options: ['Breathe, Think, Act', 'Fight, Flight, Freeze', 'Education, Skill Acquisition, Application', 'Start, Stop, Restart'], correctAnswer: 2, explanation: 'SIT progresses through understanding stress, learning coping tools, then applying them under controlled challenge.' },
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Paying attention to the present moment without judgement', 'Ignoring your thoughts', 'Clearing your mind completely', 'Meditating for an hour daily'], correctAnswer: 0, explanation: 'Mindfulness is present-moment awareness without judgement — not thought suppression.' },
    { type: 'multiple_choice', question: 'What is the "mental bicep curl" in mindfulness?', options: ['Noticing when your mind has wandered and returning to the present', 'Concentrating without blinking', 'Thinking harder', 'Visualising lifting weights'], correctAnswer: 0, explanation: 'Each time you notice wandering and return attention to the present, you strengthen the attentional muscle.' },
    { type: 'multiple_choice', question: 'What is the minimum effective dose for a daily mindfulness practice?', options: ['10 seconds', '3 minutes', '1 hour', '30 minutes'], correctAnswer: 1, explanation: 'Even 3 minutes of daily practice produces measurable benefits when done consistently.' },
    { type: 'scenario', scenario: 'Someone designs a 90-minute morning routine including cold exposure, breathwork, journaling, meditation, and exercise. They abandon it after 5 days.', question: 'What was the primary mistake?', options: ['Not including enough activities', 'Waking too late', 'Starting too ambitiously — should have begun with 10–15 minutes', 'Not having the right equipment'], correctAnswer: 2, explanation: 'Overly ambitious protocols collapse quickly. Start small (10–15 min) and build as the habit solidifies.' },
    { type: 'multiple_choice', question: 'How often should you review and adjust your resilience protocol?', options: ['Daily', 'Weekly', 'Never', 'Monthly'], correctAnswer: 3, explanation: 'Monthly reviews allow enough time to assess what is working while keeping the protocol evolving.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of a resilience protocol?', options: ['To eliminate all stress', 'For the practices to become integrated into your identity and feel natural', 'To become invincible', 'To follow it perfectly forever'], correctAnswer: 1, explanation: 'The goal is integration — practices become as natural as brushing your teeth, not a forced protocol.' },
    { type: 'multiple_choice', question: 'Where does most mental suffering come from?', options: ['Other people', 'Physical pain', 'Ruminating about the past or worrying about the future', 'The present moment'], correctAnswer: 2, explanation: 'Most suffering comes from past rumination (regret) or future worry (anxiety), not the present moment.' },
    { type: 'multiple_choice', question: 'What is the key principle when progressing a resilience practice?', options: ['Change everything at once', 'Only progress when the current level feels manageable and consistent', 'Progress as fast as possible', 'Skip levels that feel easy'], correctAnswer: 1, explanation: 'Progress only when the current level is consistent — rushing leads to burnout and abandonment.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "A morning routine is beneficial because:", options: ["It eliminates decision fatigue and sets a positive tone for the day", "You should always wake up at 5am", "It must include cold showers", "Morning routines don't actually help"], correctAnswer: 0, explanation: "A structured morning routine reduces decision fatigue, creates positive momentum, and establishes consistent signals that prepare mind and body for the day." },
    { type: 'multiple_choice', question: "Stress inoculation training involves:", options: ['Only practising during crisis situations', 'Avoiding all stressful situations', 'Taking medication to reduce stress', 'Gradually exposing yourself to controlled stressors to build tolerance'], correctAnswer: 3, explanation: 'Stress inoculation training (SIT) deliberately exposes individuals to manageable levels of stress in controlled settings, building coping skills and resilience.' },
    { type: 'multiple_choice', question: "Mindfulness is best defined as:", options: ['A religious practice only', 'Thinking positively about the future', 'Clearing your mind of all thoughts', 'Paying attention to the present moment without judgement'], correctAnswer: 3, explanation: 'Mindfulness is non-judgemental present-moment awareness \u2014 observing thoughts, feelings, and sensations without trying to change them.' },
    { type: 'multiple_choice', question: "A personal resilience protocol should include:", options: ["Only physical training", "A combination of physical, mental, and recovery practices tailored to you", "Copying someone else's routine exactly", "Training as hard as possible every day"], correctAnswer: 1, explanation: "An effective resilience protocol integrates physical training, mental practice (breathing, visualisation), recovery strategies, and reflection \u2014 personalised to the individual." },
    { type: 'multiple_choice', question: "What is the '2-minute rule' for building habits?", options: ["Exercise for only 2 minutes a day forever", "Start any new habit with a version that takes less than 2 minutes", "Set a timer for 2 minutes and stop completely", "Only think about habits for 2 minutes"], correctAnswer: 1, explanation: "James Clear's 2-minute rule: scale any habit down to a version that takes less than 2 minutes. This removes resistance and builds consistency, which can then be expanded." },
    { type: 'multiple_choice', question: "Which practice is most effective for present-moment awareness?", options: ['Multi-tasking', 'Focused single-task attention with awareness of sensations', 'Thinking about past mistakes', 'Planning future activities'], correctAnswer: 1, explanation: 'Present-moment awareness is built by directing attention to one thing at a time \u2014 noticing physical sensations, sounds, or breath without drifting to past or future.' },
    { type: 'multiple_choice', question: "The biggest barrier to maintaining a resilience practice is:", options: ['Lack of equipment', 'Inconsistency and falling off when life gets busy', 'Training too often', 'Not having enough knowledge'], correctAnswer: 1, explanation: 'Most people understand the practices \u2014 the real challenge is consistency. Life disruptions derail routines, making it essential to build systems that survive busy periods.' },
    { type: 'multiple_choice', question: "'Non-negotiable' daily practices help because:", options: ['They create rigid, inflexible routines', 'They establish minimum standards that maintain progress even on bad days', 'They replace all other forms of training', 'They should be at least 2 hours long'], correctAnswer: 1, explanation: "Non-negotiables are minimum-viable daily actions (e.g., 5-minute walk, 2-minute breathwork) that maintain momentum even when full routines aren't possible." },

  ],
};
