import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What drives the urge to breathe?', options: ['Blood pressure', 'Low oxygen', 'Heart rate', 'Rising CO2 levels'], correctAnswer: 3, explanation: 'CO2 levels primarily control breathing rate via brainstem chemoreceptors.' },
    { type: 'multiple_choice', question: 'What is chronic mouth breathing associated with?', options: ['Higher CO2 tolerance', 'Better sleep', 'Better oxygen delivery', 'Increased stress activation and poor sleep'], correctAnswer: 3, explanation: 'Mouth breathing promotes sympathetic activation and bypasses nasal benefits.' },
    { type: 'multiple_choice', question: 'What is chest breathing?', options: ['Shallow breathing using accessory muscles that promotes stress', 'A relaxation technique', 'Diaphragmatic breathing', 'Efficient deep breathing'], correctAnswer: 0, explanation: 'Chest breathing is shallow, uses neck/upper chest muscles, and activates the sympathetic system.' },
    { type: 'multiple_choice', question: 'What does over-breathing (hyperventilation) cause?', options: ['Better oxygen delivery', 'Improved focus', 'Relaxation', 'Reduced CO2, paradoxically reducing oxygen delivery (Bohr effect)'], correctAnswer: 3, explanation: 'Hyperventilation lowers CO2, which impairs oxygen release to tissues via the Bohr effect.' },
    { type: 'multiple_choice', question: 'A BOLT score under 20 seconds suggests what?', options: ['You are an elite athlete', 'Room for improvement in CO2 tolerance', 'No action needed', 'Excellent breathing health'], correctAnswer: 1, explanation: 'A BOLT score under 20 seconds suggests low CO2 tolerance and likely dysfunctional breathing patterns.' },
    { type: 'multiple_choice', question: 'What is the Bohr effect?', options: ['Oxygen binds more tightly to haemoglobin when CO2 is low', 'CO2 facilitates oxygen release from haemoglobin to tissues', 'Breathing faster always improves oxygenation', 'Oxygen and CO2 are not related'], correctAnswer: 1, explanation: 'The Bohr effect means adequate CO2 is needed for haemoglobin to release oxygen — low CO2 from overbreathing paradoxically reduces oxygen delivery.' },
    { type: 'multiple_choice', question: 'What is a BOLT score?', options: ['A fitness test', 'Body Oxygen Level Test — measuring comfortable breath-hold time after a normal exhale', 'A blood test for oxygen', 'A VO2 max measurement'], correctAnswer: 1, explanation: 'The BOLT score measures how long you can comfortably hold your breath after a normal exhale — indicating CO2 tolerance.' },
    { type: 'multiple_choice', question: 'What BOLT score indicates good breathing health?', options: ['5 seconds', '10 seconds', '40+ seconds', '100 seconds'], correctAnswer: 2, explanation: 'A BOLT score of 40+ seconds indicates excellent CO2 tolerance and efficient breathing patterns.' },
    { type: 'multiple_choice', question: 'What muscles are used in chest breathing?', options: ['The diaphragm', 'Accessory muscles in the neck and upper chest (scalenes, sternocleidomastoid)', 'Abdominal muscles', 'Leg muscles'], correctAnswer: 1, explanation: 'Chest breathing relies on accessory neck and upper chest muscles, which are less efficient and promote tension.' },
    { type: 'multiple_choice', question: 'What percentage of people are estimated to have dysfunctional breathing patterns?', options: ['5%', 'Up to 80% of the general population', '100%', '1%'], correctAnswer: 1, explanation: 'Research suggests up to 80% of the general population has some degree of dysfunctional breathing — it is extremely common.' },
  
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What is the diaphragm?', options: ['A bone', 'A dome-shaped muscle at the base of the ribcage', 'A neck muscle', 'A chest muscle'], correctAnswer: 1, explanation: 'The diaphragm is the primary breathing muscle, positioned at the base of the ribcage.' },
    { type: 'multiple_choice', question: 'During diaphragmatic breathing, what should rise?', options: ['Belly', 'Chest', 'Shoulders', 'Head'], correctAnswer: 0, explanation: 'Proper diaphragmatic breathing causes the belly to rise as the diaphragm descends.' },
    { type: 'multiple_choice', question: 'The diaphragm also functions as what type of muscle?', options: ['Core stability muscle', 'Facial muscle', 'Arm muscle', 'Cardiac muscle'], correctAnswer: 0, explanation: 'Diaphragmatic breathing creates intra-abdominal pressure that stabilises the spine.' },
    { type: 'multiple_choice', question: 'How should you progress diaphragmatic breathing practice?', options: ['Progress from lying to seated to standing to walking', 'Only practise lying down', 'Only practise during exercise', 'Skip to walking immediately'], correctAnswer: 0, explanation: 'Progress through positions as the technique becomes natural: lying → seated → standing → walking.' },
    { type: 'multiple_choice', question: 'How often should you practise diaphragmatic breathing initially?', options: ['Once a week', 'Once a month', 'Only when stressed', 'Twice daily for 5 minutes'], correctAnswer: 3, explanation: 'Twice daily for 5 minutes builds the neural pathway for automatic diaphragmatic breathing.' },
    { type: 'multiple_choice', question: 'Where should you place your hands when learning diaphragmatic breathing?', options: ['On your head', 'One on your chest, one on your belly — belly should move, chest should stay still', 'Both on your chest', 'Behind your back'], correctAnswer: 1, explanation: 'Placing hands on chest and belly provides feedback — the goal is belly movement with minimal chest movement.' },
    { type: 'multiple_choice', question: 'What speed should diaphragmatic breathing be?', options: ['As fast as possible', '4–6 seconds inhale, 4–6 seconds exhale', '1 second per breath', 'Speed does not matter'], correctAnswer: 1, explanation: 'Slow, controlled breathing at 4–6 seconds per phase optimises gas exchange and activates the parasympathetic system.' },
    { type: 'multiple_choice', question: 'How long until diaphragmatic breathing becomes automatic?', options: ['1 day', 'Never — it always requires effort', '2–4 weeks of consistent practice', '1 year'], correctAnswer: 2, explanation: 'With consistent twice-daily practice, diaphragmatic breathing typically becomes the default pattern within 2–4 weeks.' },
    { type: 'multiple_choice', question: 'Why does diaphragmatic breathing reduce anxiety?', options: ['It distracts you', 'It directly stimulates the vagus nerve, activating the parasympathetic system', 'It increases adrenaline', 'It has no effect on anxiety'], correctAnswer: 1, explanation: 'The diaphragm physically contacts the vagus nerve during deep breathing, directly triggering parasympathetic activation.' },
    { type: 'multiple_choice', question: 'Can diaphragmatic breathing improve core stability?', options: ['No — breathing and core stability are unrelated', 'Yes — the diaphragm creates intra-abdominal pressure that stabilises the spine', 'Only during weightlifting', 'Only for athletes'], correctAnswer: 1, explanation: 'Proper diaphragmatic breathing creates intra-abdominal pressure, contributing to spinal stability during movement.' },
  
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'Who uses box breathing?', options: ['Nobody — it is unproven', 'Military special forces, emergency services, and athletes', 'Only yoga practitioners', 'Only children'], correctAnswer: 1, explanation: 'Box breathing is used across high-performance fields for maintaining composure under pressure.' },
    { type: 'multiple_choice', question: 'Why is the 4-7-8 technique effective before sleep?', options: ['It makes you tired', 'The extended exhale strongly activates parasympathetic tone', 'It increases heart rate', 'It raises cortisol'], correctAnswer: 1, explanation: 'The extended exhale maximises vagal stimulation, shifting toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: 'How many slow breaths can shift your nervous system state?', options: ['50', '1000', 'As few as 6', '100'], correctAnswer: 2, explanation: 'Even 6 slow, controlled breaths can measurably shift autonomic state during acute stress.' },
    { type: 'multiple_choice', question: 'When is box breathing most useful?', options: ['Only during meditation', 'During sleep', 'Never — it does not work', 'Before stressful events and during acute stress'], correctAnswer: 3, explanation: 'Box breathing is most effective for pre-event composure and acute stress management.' },
    { type: 'multiple_choice', question: 'What creates the calming effect of extended exhale breathing?', options: ['Increased oxygen', 'Increased CO2', 'Faster breathing', 'Spending more time in each cycle with decreasing heart rate'], correctAnswer: 3, explanation: 'Extended exhales maximise the time spent with naturally decreasing heart rate (respiratory sinus arrhythmia).' },
    { type: 'multiple_choice', question: 'What is the pattern for box breathing?', options: ['Inhale 2, hold 2, exhale 2', 'Inhale 4, hold 4, exhale 4, hold 4 — equal phases', 'Inhale 8, exhale 2', 'Random breathing'], correctAnswer: 1, explanation: 'Box breathing uses four equal phases — typically 4 counts each — creating a balanced, calming rhythm.' },
    { type: 'multiple_choice', question: 'What is the 4-7-8 breathing pattern?', options: ['Inhale 4, hold 7, exhale 8', 'Inhale 4, exhale 7, hold 8', '4 breaths, 7 seconds rest, 8 breaths', 'Breathe 4 times per minute for 7.8 minutes'], correctAnswer: 0, explanation: '4-7-8 breathing is inhale for 4 counts, hold for 7, exhale for 8 — the extended exhale maximises parasympathetic activation.' },
    { type: 'multiple_choice', question: 'Why is box breathing effective for pre-performance anxiety?', options: ['It eliminates all anxiety', 'It provides a structured focus point while physiologically reducing sympathetic activation', 'It makes you forget about the event', 'It increases heart rate for readiness'], correctAnswer: 1, explanation: 'Box breathing gives the anxious mind a structured task while simultaneously calming the nervous system.' },
    { type: 'multiple_choice', question: 'How quickly can calming breathwork techniques shift your nervous system state?', options: ['It takes at least 30 minutes', 'Within 60–90 seconds (as few as 6 slow breaths)', 'Only after weeks of practice', 'It varies too much to predict'], correctAnswer: 1, explanation: 'Even 6 slow, controlled breaths can measurably shift autonomic state within 60–90 seconds.' },
    { type: 'multiple_choice', question: 'Should you use calming breathwork only during emergencies?', options: ['Yes — save it for real stress', 'No — regular daily practice builds the neural pathways so they work better during stress', 'Only when instructed by a professional', 'It does not matter when you practise'], correctAnswer: 1, explanation: 'Daily practice builds the neural pathways, making the techniques more effective when you actually need them during stress.' },
  
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'How many deep breaths does the Wim Hof method start with?', options: ['5–10', '3', '30–40', '100'], correctAnswer: 2, explanation: 'The Wim Hof method begins with 30–40 deep, rapid breaths.' },
    { type: 'multiple_choice', question: 'What does the rapid breathing phase of Wim Hof cause?', options: ['Immediate sleep', 'Lowered CO2 and controlled adrenaline release', 'Muscle growth', 'Increased CO2'], correctAnswer: 1, explanation: 'Rapid breathing lowers CO2 (respiratory alkalosis) and triggers a controlled adrenaline response.' },
    { type: 'multiple_choice', question: 'What should you never do while practising hyperventilation breathwork?', options: ['Close your eyes', 'Be near water or standing where fainting is dangerous', 'Sit down', 'Listen to music'], correctAnswer: 1, explanation: 'Low CO2 can cause loss of consciousness — never practise near water or in dangerous positions.' },
    { type: 'multiple_choice', question: 'How many rounds should beginners start with?', options: ['10', '1', '3', '7'], correctAnswer: 2, explanation: 'Start with 3 rounds and build tolerance over weeks.' },
    { type: 'multiple_choice', question: 'Do retention times typically increase across rounds?', options: ['They stay the same', 'Yes — each round typically produces a longer hold', 'No — they decrease', 'Only for experienced practitioners'], correctAnswer: 1, explanation: 'Retention times typically increase with each round as CO2 tolerance temporarily improves.' },
    { type: 'multiple_choice', question: 'What is the purpose of energising breathwork?', options: ['To help you fall asleep', 'To deliberately activate the sympathetic nervous system for alertness and energy', 'To slow down your heart rate', 'To reduce blood pressure'], correctAnswer: 1, explanation: 'Energising breathwork deliberately activates sympathetic arousal — useful before training, competitions, or when you need alertness.' },
    { type: 'multiple_choice', question: 'What is respiratory alkalosis?', options: ['Normal breathing', 'A rise in blood pH caused by rapid breathing that lowers CO2', 'Low oxygen levels', 'A breathing disorder'], correctAnswer: 1, explanation: 'Rapid breathing expels CO2, raising blood pH (respiratory alkalosis) — this creates the tingling and lightheadedness during Wim Hof breathing.' },
    { type: 'multiple_choice', question: 'Why should you always sit or lie down during Wim Hof breathing?', options: ['It is more comfortable', 'The technique can cause lightheadedness or loss of consciousness — fainting while standing is dangerous', 'Standing reduces effectiveness', 'It is a tradition'], correctAnswer: 1, explanation: 'Low CO2 can cause dizziness or loss of consciousness — always practise seated or lying in a safe environment.' },
    { type: 'multiple_choice', question: 'What is the breath retention phase in Wim Hof?', options: ['Holding your breath after the rapid breathing rounds', 'Breathing normally', 'Slow exhale', 'Extended inhale'], correctAnswer: 0, explanation: 'After 30–40 rapid breaths, you exhale and hold — retention times typically increase across rounds as CO2 tolerance improves.' },
    { type: 'multiple_choice', question: 'When is the best time for energising breathwork?', options: ['Right before bed', 'Morning or pre-training — never within 3 hours of bedtime', 'During sleep', 'Any time — timing does not matter'], correctAnswer: 1, explanation: 'Energising breathwork activates the sympathetic system — use it in the morning or before training, not near bedtime.' },
  
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What hormones does cold water immersion release?', options: ['Oestrogen and progesterone', 'Insulin and glucagon', 'Melatonin and serotonin', 'Noradrenaline and dopamine'], correctAnswer: 3, explanation: 'Cold exposure triggers significant releases of noradrenaline (200–300%) and dopamine.' },
    { type: 'multiple_choice', question: 'How long should beginners start with cold exposure?', options: ['5 minutes', '10 minutes', '1 hour', '30 seconds'], correctAnswer: 3, explanation: 'Start with 30 seconds of cold at the end of your normal shower.' },
    { type: 'multiple_choice', question: 'What should you focus on during cold exposure?', options: ['Moving as fast as possible', 'Holding your breath', 'Screaming', 'Controlling your breathing — slow nasal breaths'], correctAnswer: 3, explanation: 'Maintaining slow, controlled breathing through the discomfort is the primary resilience training.' },
    { type: 'multiple_choice', question: 'What temperature range provides most cold exposure benefits?', options: ['20–25°C', '10–15°C', 'Below 0°C', '0–5°C'], correctAnswer: 1, explanation: 'Most benefits occur at 10–15°C in the first 1–3 minutes — extreme cold is unnecessary.' },
    { type: 'multiple_choice', question: 'What is the main psychological benefit of cold exposure?', options: ['It makes you immune to cold', 'It replaces therapy', 'It builds proof that you can choose and handle discomfort', 'It eliminates all discomfort'], correctAnswer: 2, explanation: 'Deliberately choosing discomfort builds transferable psychological resilience.' },
    { type: 'multiple_choice', question: 'How much can cold water immersion increase noradrenaline levels?', options: ['10%', '50%', '200–300%', '1000%'], correctAnswer: 2, explanation: 'Cold exposure triggers a 200–300% increase in noradrenaline, producing sustained alertness and mood elevation.' },
    { type: 'multiple_choice', question: 'What is the primary resilience benefit of cold exposure?', options: ['Building physical toughness', 'Training your ability to remain calm and controlled under acute stress', 'Burning calories', 'Building muscle'], correctAnswer: 1, explanation: 'The core benefit is training your nervous system to maintain composure under stress — the cold is just the vehicle.' },
    { type: 'multiple_choice', question: 'What is the recommended progression for cold exposure?', options: ['Jump straight into ice baths', '30 seconds cold shower → 1 min → 2 min → cold water immersion', 'Only use ice baths', 'No progression needed'], correctAnswer: 1, explanation: 'Start with 30-second cold shower endings, gradually increase duration, then progress to water immersion.' },
    { type: 'multiple_choice', question: 'Who should avoid cold exposure without medical clearance?', options: ['Nobody — it is safe for everyone', 'People with cardiovascular conditions, Raynaud\'s disease, or those who are pregnant', 'Only elderly people', 'Only children'], correctAnswer: 1, explanation: 'Cold exposure causes cardiovascular stress — people with heart conditions, Raynaud\'s, or pregnancy should consult a doctor first.' },
    { type: 'multiple_choice', question: 'How long do the mood benefits of cold exposure typically last?', options: ['5 minutes', 'Several hours due to sustained dopamine and noradrenaline elevation', '24 hours', 'Only during the exposure'], correctAnswer: 1, explanation: 'The neurochemical response to cold exposure produces sustained mood elevation lasting several hours after the session.' },
  
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'What mechanism makes journaling effective?', options: ['It improves handwriting', 'Cognitive processing — organising thoughts reduces emotional charge', 'It fills time', 'It replaces therapy'], correctAnswer: 1, explanation: 'Writing forces cognitive organisation, creating narrative coherence and reducing emotional intensity.' },
    { type: 'multiple_choice', question: 'What is the most important factor for effective journaling?', options: ['Consistency', 'Beautiful writing', 'Using an expensive notebook', 'Writing for at least 30 minutes'], correctAnswer: 0, explanation: 'A messy paragraph every day is infinitely more valuable than a perfect entry once a month.' },
    { type: 'multiple_choice', question: 'What is the three-question journaling framework?', options: ['Who, What, Where', 'Start, Stop, Continue', 'Grateful for, Biggest challenge, One action', 'Past, Present, Future'], correctAnswer: 2, explanation: 'What am I grateful for? What is my biggest challenge? What is one action I can take?' },
    { type: 'multiple_choice', question: 'How long is sufficient for daily journaling?', options: ['2 hours', '30 minutes minimum', '10 seconds', '5 minutes'], correctAnswer: 3, explanation: '5 minutes is sufficient for effective daily journaling — consistency beats duration.' },
    { type: 'multiple_choice', question: 'What type of journaling shifts attention toward positive life aspects?', options: ['Fantasy journaling', 'News journaling', 'Gratitude journaling', 'Complaint journaling'], correctAnswer: 2, explanation: 'Gratitude journaling (3 things daily) shifts attention toward positive aspects and improves wellbeing.' },
    { type: 'multiple_choice', question: 'What did James Pennebaker\'s research show about expressive writing?', options: ['It has no measurable benefits', 'Writing about emotional experiences improves immune function and reduces doctor visits', 'It only helps professional writers', 'It increases stress'], correctAnswer: 1, explanation: 'Pennebaker\'s research demonstrated that expressive writing measurably improves immune markers and reduces healthcare utilisation.' },
    { type: 'multiple_choice', question: 'What is the difference between structured and free-form journaling?', options: ['There is no difference', 'Structured uses prompts/frameworks; free-form is stream of consciousness — both are effective', 'Structured is always better', 'Free-form is always better'], correctAnswer: 1, explanation: 'Structured journaling (prompts, gratitude lists) and free-form (stream of consciousness) both provide benefits — choose what you will actually do.' },
    { type: 'multiple_choice', question: 'Why is gratitude journaling effective?', options: ['It makes problems disappear', 'It rewires attentional bias — training the brain to notice positive aspects it normally filters out', 'It is a placebo', 'It only works temporarily'], correctAnswer: 1, explanation: 'Gratitude journaling shifts what the brain notices — it does not ignore problems but rebalances the negativity bias.' },
    { type: 'multiple_choice', question: 'What is the biggest barrier to maintaining a journaling habit?', options: ['Cost of notebooks', 'Making it too complicated — expecting perfect, long entries', 'Lack of time', 'Not knowing how to write'], correctAnswer: 1, explanation: 'Most people quit because they make it too ambitious. Three honest sentences is better than three unwritten pages.' },
    { type: 'multiple_choice', question: 'When is the best time to journal?', options: ['Only in the morning', 'Only at night', 'Whatever time you will actually do it consistently', 'Only during weekends'], correctAnswer: 2, explanation: 'The best time is the time that becomes habitual — morning, evening, or lunch break. Consistency matters more than timing.' },
  
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What does the nose produce during nasal breathing that the mouth does not?', options: ['Carbon dioxide', 'Adrenaline', 'Nitric oxide', 'Cortisol'], correctAnswer: 2, explanation: 'Nasal breathing triggers nitric oxide production in the paranasal sinuses, which is a vasodilator that improves blood flow.' },
    { type: 'multiple_choice', question: 'What does chronic mouth breathing activate?', options: ['The parasympathetic nervous system', 'Sympathetic tone, keeping you in a low-level stress state', 'The immune system', 'Deep sleep'], correctAnswer: 1, explanation: 'Chronic mouth breathing maintains low-level sympathetic activation even at rest.' },
    { type: 'multiple_choice', question: 'What is a simple intervention for mouth breathing during sleep?', options: ['Sleeping with the window open', 'Medical-grade mouth tape', 'Drinking more water', 'Using a humidifier'], correctAnswer: 1, explanation: 'Medical-grade mouth tape during sleep gently encourages nasal breathing. Start with a small strip.' },
    { type: 'multiple_choice', question: 'How long does full adaptation to habitual nasal breathing typically take?', options: ['1 day', '2–6 weeks', '6–12 months', 'It never adapts'], correctAnswer: 1, explanation: 'Full adaptation to nasal breathing typically takes 2–6 weeks of consistent practice.' },
    { type: 'multiple_choice', question: 'What should you do if you cannot maintain nasal breathing during a walk?', options: ['Stop walking', 'Switch to mouth breathing permanently', 'Slow down', 'Breathe faster through the nose'], correctAnswer: 2, explanation: 'If you cannot maintain nasal breathing, slow down rather than switching to mouth breathing.' },
    { type: 'multiple_choice', question: 'What can habitual mouth breathing alter over time?', options: ['Only fitness levels', 'Facial structure, posture, and dental health', 'Nothing — it is harmless', 'Only lung capacity'], correctAnswer: 1, explanation: 'Long-term mouth breathing can alter facial development, cause forward head posture, and affect dental health.' },
    { type: 'multiple_choice', question: 'What is the BOLT test and how does it relate to nasal breathing?', options: ['It measures lung capacity', 'It measures CO2 tolerance — people with low BOLT scores often mouth-breathe', 'It measures running speed', 'It has no relation to nasal breathing'], correctAnswer: 1, explanation: 'Low BOLT scores indicate poor CO2 tolerance, which often causes the uncomfortable urge to mouth-breathe during exertion.' },
    { type: 'multiple_choice', question: 'How does nasal breathing affect exercise performance?', options: ['It always reduces performance', 'Initially pace may slow, but efficiency improves as CO2 tolerance adapts', 'It has no effect', 'It immediately improves performance'], correctAnswer: 1, explanation: 'Nasal breathing may slow you initially, but as CO2 tolerance improves, oxygen efficiency increases and performance catches up.' },
    { type: 'multiple_choice', question: 'What happens to the nasal passages when you consistently breathe through them?', options: ['Nothing changes', 'They widen and become more efficient over time', 'They close permanently', 'They shrink'], correctAnswer: 1, explanation: 'Like any pathway, consistent use widens the nasal passages and improves airflow efficiency.' },
    { type: 'multiple_choice', question: 'Why does nasal breathing filter air better than mouth breathing?', options: ['The nose has hair and mucous membranes that trap particles, bacteria, and allergens', 'It does not filter better', 'The mouth filters better', 'Filtering does not matter'], correctAnswer: 0, explanation: 'Nasal passages contain hair, mucous membranes, and turbinates that filter, warm, and humidify air before it reaches the lungs.' },
  
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'What is the recommended daily minimum breathwork practice?', options: ['30 minutes morning only', 'Morning activation (2 min) + evening wind-down (5 min)', 'Just one session per week', 'Only when stressed'], correctAnswer: 1, explanation: 'The non-negotiable baseline is morning activation (2 minutes) and evening wind-down (5 minutes).' },
    { type: 'multiple_choice', question: 'Which breathwork technique is best for immediate calming during acute stress?', options: ['Energising breathwork', 'Box breathing (4-4-4-4)', 'Morning activation breathing', 'Wim Hof-style rounds'], correctAnswer: 1, explanation: 'Box breathing (4-count inhale, hold, exhale, hold) is an immediate calming intervention during acute stress.' },
    { type: 'multiple_choice', question: 'How long before measurable changes in baseline stress levels appear from consistent breathwork?', options: ['One day', 'Two to four weeks', 'Six months', 'One year'], correctAnswer: 1, explanation: 'Consistent daily practice of 5–10 minutes produces measurable changes within two to four weeks.' },
    { type: 'multiple_choice', question: 'What is the purpose of a weekly longer breathwork session?', options: ['To make up for missed daily sessions', 'Deeper nervous system training', 'It is not recommended', 'To build cardiovascular fitness'], correctAnswer: 1, explanation: 'One 15–20 minute guided session per week provides deeper nervous system training beyond daily short practices.' },
    { type: 'multiple_choice', question: 'What is the difference between knowing techniques and having a practice?', options: ['There is no difference', 'A practice is structured, consistent, and progressive — not random', 'A practice requires expensive equipment', 'Techniques are better than practice'], correctAnswer: 1, explanation: 'Like physical training, breathwork benefits from structure, progression, and consistency — not haphazard application.' },
    { type: 'multiple_choice', question: 'What is the difference between reactive and proactive breathwork?', options: ['There is no difference', 'Reactive is used during stress; proactive is scheduled daily practice that prevents stress accumulation', 'Reactive is better', 'Proactive means never being stressed'], correctAnswer: 1, explanation: 'Reactive breathwork manages acute stress; proactive daily practice lowers baseline stress so you are less reactive overall.' },
    { type: 'multiple_choice', question: 'How should you choose which breathwork technique to use?', options: ['Always use the same one', 'Match the technique to the situation — calming for stress, energising for activation', 'It does not matter', 'Only use box breathing'], correctAnswer: 1, explanation: 'Different techniques serve different purposes — choose calming techniques for stress and energising techniques for activation.' },
    { type: 'multiple_choice', question: 'What is the minimum effective dose for daily breathwork?', options: ['60 minutes', '5–7 minutes split between morning and evening', '1 second', 'Only when you remember'], correctAnswer: 1, explanation: 'As little as 5–7 minutes daily (2 min morning activation + 5 min evening wind-down) produces measurable benefits.' },
    { type: 'multiple_choice', question: 'Why should breathwork be progressive like physical training?', options: ['It should not be progressive', 'The nervous system adapts — you need gradual increases in duration and intensity for continued development', 'To make it harder', 'Only advanced practitioners need progression'], correctAnswer: 1, explanation: 'Like physical training, the nervous system adapts to breathwork — progressive challenge drives continued improvement.' },
    { type: 'multiple_choice', question: 'What role does tracking play in breathwork practice?', options: ['No role — just do it', 'Recording sessions, BOLT scores, and subjective ratings helps identify what works and motivates consistency', 'Tracking is stressful and counterproductive', 'Only professionals need to track'], correctAnswer: 1, explanation: 'Simple tracking (session completion, BOLT scores, mood ratings) reveals patterns and sustains motivation through visible progress.' },
  
  ]),
];
