import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What drives the urge to breathe?', options: ['Blood pressure', 'Low oxygen', 'Heart rate', 'Rising CO2 levels'], correctAnswer: 3, explanation: 'CO2 levels primarily control breathing rate via brainstem chemoreceptors.' },
    { type: 'multiple_choice', question: 'What is chronic mouth breathing associated with?', options: ['Higher CO2 tolerance', 'Better sleep', 'Better oxygen delivery', 'Increased stress activation and poor sleep'], correctAnswer: 3, explanation: 'Mouth breathing promotes sympathetic activation and bypasses nasal benefits.' },
    { type: 'multiple_choice', question: 'What is chest breathing?', options: ['Shallow breathing using accessory muscles that promotes stress', 'A relaxation technique', 'Diaphragmatic breathing', 'Efficient deep breathing'], correctAnswer: 0, explanation: 'Chest breathing is shallow, uses neck/upper chest muscles, and activates the sympathetic system.' },
    { type: 'multiple_choice', question: 'What does over-breathing (hyperventilation) cause?', options: ['Better oxygen delivery', 'Improved focus', 'Relaxation', 'Reduced CO2, paradoxically reducing oxygen delivery (Bohr effect)'], correctAnswer: 3, explanation: 'Hyperventilation lowers CO2, which impairs oxygen release to tissues via the Bohr effect.' },
    { type: 'multiple_choice', question: 'A BOLT score under 20 seconds suggests what?', options: ['You are an elite athlete', 'Room for improvement in CO2 tolerance', 'No action needed', 'Excellent breathing health'], correctAnswer: 1, explanation: 'A BOLT score under 20 seconds suggests low CO2 tolerance and likely dysfunctional breathing patterns.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What is the diaphragm?', options: ['A bone', 'A dome-shaped muscle at the base of the ribcage', 'A neck muscle', 'A chest muscle'], correctAnswer: 1, explanation: 'The diaphragm is the primary breathing muscle, positioned at the base of the ribcage.' },
    { type: 'multiple_choice', question: 'During diaphragmatic breathing, what should rise?', options: ['Belly', 'Chest', 'Shoulders', 'Head'], correctAnswer: 0, explanation: 'Proper diaphragmatic breathing causes the belly to rise as the diaphragm descends.' },
    { type: 'multiple_choice', question: 'The diaphragm also functions as what type of muscle?', options: ['Core stability muscle', 'Facial muscle', 'Arm muscle', 'Cardiac muscle'], correctAnswer: 0, explanation: 'Diaphragmatic breathing creates intra-abdominal pressure that stabilises the spine.' },
    { type: 'multiple_choice', question: 'How should you progress diaphragmatic breathing practice?', options: ['Progress from lying to seated to standing to walking', 'Only practise lying down', 'Only practise during exercise', 'Skip to walking immediately'], correctAnswer: 0, explanation: 'Progress through positions as the technique becomes natural: lying → seated → standing → walking.' },
    { type: 'multiple_choice', question: 'How often should you practise diaphragmatic breathing initially?', options: ['Once a week', 'Once a month', 'Only when stressed', 'Twice daily for 5 minutes'], correctAnswer: 3, explanation: 'Twice daily for 5 minutes builds the neural pathway for automatic diaphragmatic breathing.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'Who uses box breathing?', options: ['Nobody — it is unproven', 'Military special forces, emergency services, and athletes', 'Only yoga practitioners', 'Only children'], correctAnswer: 1, explanation: 'Box breathing is used across high-performance fields for maintaining composure under pressure.' },
    { type: 'multiple_choice', question: 'Why is the 4-7-8 technique effective before sleep?', options: ['It makes you tired', 'The extended exhale strongly activates parasympathetic tone', 'It increases heart rate', 'It raises cortisol'], correctAnswer: 1, explanation: 'The extended exhale maximises vagal stimulation, shifting toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: 'How many slow breaths can shift your nervous system state?', options: ['50', '1000', 'As few as 6', '100'], correctAnswer: 2, explanation: 'Even 6 slow, controlled breaths can measurably shift autonomic state during acute stress.' },
    { type: 'multiple_choice', question: 'When is box breathing most useful?', options: ['Only during meditation', 'During sleep', 'Never — it does not work', 'Before stressful events and during acute stress'], correctAnswer: 3, explanation: 'Box breathing is most effective for pre-event composure and acute stress management.' },
    { type: 'multiple_choice', question: 'What creates the calming effect of extended exhale breathing?', options: ['Increased oxygen', 'Increased CO2', 'Faster breathing', 'Spending more time in each cycle with decreasing heart rate'], correctAnswer: 3, explanation: 'Extended exhales maximise the time spent with naturally decreasing heart rate (respiratory sinus arrhythmia).' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'How many deep breaths does the Wim Hof method start with?', options: ['5–10', '3', '30–40', '100'], correctAnswer: 2, explanation: 'The Wim Hof method begins with 30–40 deep, rapid breaths.' },
    { type: 'multiple_choice', question: 'What does the rapid breathing phase of Wim Hof cause?', options: ['Immediate sleep', 'Lowered CO2 and controlled adrenaline release', 'Muscle growth', 'Increased CO2'], correctAnswer: 1, explanation: 'Rapid breathing lowers CO2 (respiratory alkalosis) and triggers a controlled adrenaline response.' },
    { type: 'multiple_choice', question: 'What should you never do while practising hyperventilation breathwork?', options: ['Close your eyes', 'Be near water or standing where fainting is dangerous', 'Sit down', 'Listen to music'], correctAnswer: 1, explanation: 'Low CO2 can cause loss of consciousness — never practise near water or in dangerous positions.' },
    { type: 'multiple_choice', question: 'How many rounds should beginners start with?', options: ['10', '1', '3', '7'], correctAnswer: 2, explanation: 'Start with 3 rounds and build tolerance over weeks.' },
    { type: 'multiple_choice', question: 'Do retention times typically increase across rounds?', options: ['They stay the same', 'Yes — each round typically produces a longer hold', 'No — they decrease', 'Only for experienced practitioners'], correctAnswer: 1, explanation: 'Retention times typically increase with each round as CO2 tolerance temporarily improves.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What hormones does cold water immersion release?', options: ['Oestrogen and progesterone', 'Insulin and glucagon', 'Melatonin and serotonin', 'Noradrenaline and dopamine'], correctAnswer: 3, explanation: 'Cold exposure triggers significant releases of noradrenaline (200–300%) and dopamine.' },
    { type: 'multiple_choice', question: 'How long should beginners start with cold exposure?', options: ['5 minutes', '10 minutes', '1 hour', '30 seconds'], correctAnswer: 3, explanation: 'Start with 30 seconds of cold at the end of your normal shower.' },
    { type: 'multiple_choice', question: 'What should you focus on during cold exposure?', options: ['Moving as fast as possible', 'Holding your breath', 'Screaming', 'Controlling your breathing — slow nasal breaths'], correctAnswer: 3, explanation: 'Maintaining slow, controlled breathing through the discomfort is the primary resilience training.' },
    { type: 'multiple_choice', question: 'What temperature range provides most cold exposure benefits?', options: ['20–25°C', '10–15°C', 'Below 0°C', '0–5°C'], correctAnswer: 1, explanation: 'Most benefits occur at 10–15°C in the first 1–3 minutes — extreme cold is unnecessary.' },
    { type: 'multiple_choice', question: 'What is the main psychological benefit of cold exposure?', options: ['It makes you immune to cold', 'It replaces therapy', 'It builds proof that you can choose and handle discomfort', 'It eliminates all discomfort'], correctAnswer: 2, explanation: 'Deliberately choosing discomfort builds transferable psychological resilience.' },
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'What mechanism makes journaling effective?', options: ['It improves handwriting', 'Cognitive processing — organising thoughts reduces emotional charge', 'It fills time', 'It replaces therapy'], correctAnswer: 1, explanation: 'Writing forces cognitive organisation, creating narrative coherence and reducing emotional intensity.' },
    { type: 'multiple_choice', question: 'What is the most important factor for effective journaling?', options: ['Consistency', 'Beautiful writing', 'Using an expensive notebook', 'Writing for at least 30 minutes'], correctAnswer: 0, explanation: 'A messy paragraph every day is infinitely more valuable than a perfect entry once a month.' },
    { type: 'multiple_choice', question: 'What is the three-question journaling framework?', options: ['Who, What, Where', 'Start, Stop, Continue', 'Grateful for, Biggest challenge, One action', 'Past, Present, Future'], correctAnswer: 2, explanation: 'What am I grateful for? What is my biggest challenge? What is one action I can take?' },
    { type: 'multiple_choice', question: 'How long is sufficient for daily journaling?', options: ['2 hours', '30 minutes minimum', '10 seconds', '5 minutes'], correctAnswer: 3, explanation: '5 minutes is sufficient for effective daily journaling — consistency beats duration.' },
    { type: 'multiple_choice', question: 'What type of journaling shifts attention toward positive life aspects?', options: ['Fantasy journaling', 'News journaling', 'Gratitude journaling', 'Complaint journaling'], correctAnswer: 2, explanation: 'Gratitude journaling (3 things daily) shifts attention toward positive aspects and improves wellbeing.' },
  ]),
  cq(2, 7, [
    { type: 'multiple_choice', question: 'What does the nose produce during nasal breathing that the mouth does not?', options: ['Carbon dioxide', 'Adrenaline', 'Nitric oxide', 'Cortisol'], correctAnswer: 2, explanation: 'Nasal breathing triggers nitric oxide production in the paranasal sinuses, which is a vasodilator that improves blood flow.' },
    { type: 'multiple_choice', question: 'What does chronic mouth breathing activate?', options: ['The parasympathetic nervous system', 'Sympathetic tone, keeping you in a low-level stress state', 'The immune system', 'Deep sleep'], correctAnswer: 1, explanation: 'Chronic mouth breathing maintains low-level sympathetic activation even at rest.' },
    { type: 'multiple_choice', question: 'What is a simple intervention for mouth breathing during sleep?', options: ['Sleeping with the window open', 'Medical-grade mouth tape', 'Drinking more water', 'Using a humidifier'], correctAnswer: 1, explanation: 'Medical-grade mouth tape during sleep gently encourages nasal breathing. Start with a small strip.' },
    { type: 'multiple_choice', question: 'How long does full adaptation to habitual nasal breathing typically take?', options: ['1 day', '2–6 weeks', '6–12 months', 'It never adapts'], correctAnswer: 1, explanation: 'Full adaptation to nasal breathing typically takes 2–6 weeks of consistent practice.' },
    { type: 'multiple_choice', question: 'What should you do if you cannot maintain nasal breathing during a walk?', options: ['Stop walking', 'Switch to mouth breathing permanently', 'Slow down', 'Breathe faster through the nose'], correctAnswer: 2, explanation: 'If you cannot maintain nasal breathing, slow down rather than switching to mouth breathing.' },
    { type: 'multiple_choice', question: 'What can habitual mouth breathing alter over time?', options: ['Only fitness levels', 'Facial structure, posture, and dental health', 'Nothing — it is harmless', 'Only lung capacity'], correctAnswer: 1, explanation: 'Long-term mouth breathing can alter facial development, cause forward head posture, and affect dental health.' },
  ]),
  cq(2, 8, [
    { type: 'multiple_choice', question: 'What is the recommended daily minimum breathwork practice?', options: ['30 minutes morning only', 'Morning activation (2 min) + evening wind-down (5 min)', 'Just one session per week', 'Only when stressed'], correctAnswer: 1, explanation: 'The non-negotiable baseline is morning activation (2 minutes) and evening wind-down (5 minutes).' },
    { type: 'multiple_choice', question: 'Which breathwork technique is best for immediate calming during acute stress?', options: ['Energising breathwork', 'Box breathing (4-4-4-4)', 'Morning activation breathing', 'Wim Hof-style rounds'], correctAnswer: 1, explanation: 'Box breathing (4-count inhale, hold, exhale, hold) is an immediate calming intervention during acute stress.' },
    { type: 'multiple_choice', question: 'How long before measurable changes in baseline stress levels appear from consistent breathwork?', options: ['One day', 'Two to four weeks', 'Six months', 'One year'], correctAnswer: 1, explanation: 'Consistent daily practice of 5–10 minutes produces measurable changes within two to four weeks.' },
    { type: 'multiple_choice', question: 'What is the purpose of a weekly longer breathwork session?', options: ['To make up for missed daily sessions', 'Deeper nervous system training', 'It is not recommended', 'To build cardiovascular fitness'], correctAnswer: 1, explanation: 'One 15–20 minute guided session per week provides deeper nervous system training beyond daily short practices.' },
    { type: 'multiple_choice', question: 'What is the difference between knowing techniques and having a practice?', options: ['There is no difference', 'A practice is structured, consistent, and progressive — not random', 'A practice requires expensive equipment', 'Techniques are better than practice'], correctAnswer: 1, explanation: 'Like physical training, breathwork benefits from structure, progression, and consistency — not haphazard application.' },
  ]),
];
