import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What is the most important quality of a morning routine?', options: ['Length', 'Consistency', 'Complexity', 'Start time'], correctAnswer: 1, explanation: 'A consistent short routine beats an ambitious one that is abandoned.' },
    { type: 'multiple_choice', question: 'Why avoid checking your phone first thing?', options: ['It puts you in reactive mode', 'Screens are bad', 'It is impolite', 'Battery conservation'], correctAnswer: 0, explanation: 'Checking your phone immediately floods you with external demands and reactive thinking.' },
    { type: 'multiple_choice', question: 'How much water should you drink upon waking?', options: ['None', '500ml', '2 litres', 'A sip'], correctAnswer: 1, explanation: 'You wake mildly dehydrated — 500ml rehydrates and supports alertness.' },
    { type: 'multiple_choice', question: 'What is the recommended starting duration for a morning routine?', options: ['10–15 minutes', '5 seconds', '2 hours', '90 minutes'], correctAnswer: 0, explanation: 'Start with 10–15 minutes and build as the habit solidifies.' },
      { type: 'multiple_choice', question: "What is the core principle of morning routine design?", options: ['Option A', 'Option D', 'Option B', 'Option C'], correctAnswer: 0, explanation: "A sustainable short routine done daily transforms life; an ambitious one abandoned does not." },
    { type: 'multiple_choice', question: 'Why is a morning routine powerful for resilience?', options: ['It provides a controllable, positive start that sets the tone for the day regardless of what follows', 'It saves time', 'It makes mornings more fun', 'It is only useful for early risers'], correctAnswer: 0, explanation: 'A morning routine anchors your day in controllable actions, building momentum before external events can disrupt you.' },
    { type: 'multiple_choice', question: 'How long should a minimum morning routine take?', options: ['5 seconds', 'At least 1 hour', '2 hours', '10–15 minutes is sufficient if the elements are chosen well'], correctAnswer: 3, explanation: 'A focused 10–15 minute routine (movement + breathwork + intention setting) is more sustainable than an ambitious 2-hour ritual.' },
    { type: 'multiple_choice', question: 'What should a morning routine NOT start with?', options: ['Hydration', 'Movement', 'Checking your phone — it puts you in reactive mode immediately', 'Breathwork'], correctAnswer: 2, explanation: 'Checking your phone immediately means starting the day reacting to others\' priorities rather than setting your own.' },
    { type: 'multiple_choice', question: 'What is an intention-setting practice?', options: ['Choosing one or two priorities that would make the day successful', 'Wishing for things', 'Making a to-do list', 'Planning your entire week each morning'], correctAnswer: 0, explanation: 'Intention setting means identifying the 1–2 things that matter most today — providing focus and direction.' },
    { type: 'multiple_choice', question: 'Why is consistency more important than content in a morning routine?', options: ['Consistency does not matter', 'The specific activities do not matter at all', 'Only content matters', 'A simple routine you do every day builds more resilience than a complex one you skip most days'], correctAnswer: 3, explanation: 'The discipline of showing up daily matters more than the specific activities — start simple and add complexity only when the base is solid.' },
  
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What is stress inoculation training based on?', options: ['Avoiding stress', 'Medication', 'Controlled exposure to manageable stress builds resilience', 'Maximum stress exposure'], correctAnswer: 2, explanation: 'Like a vaccine, SIT uses controlled exposure to build capacity for handling larger stressors.' },
    { type: 'multiple_choice', question: 'What is the key difference between SIT and uncontrolled stress?', options: ['No difference', 'SIT is chosen and progressive with coping tools; uncontrolled stress overwhelms', 'SIT is harder', 'SIT only works for soldiers'], correctAnswer: 1, explanation: 'Controlled, chosen exposure with tools builds capacity; overwhelming stress causes harm.' },
    { type: 'multiple_choice', question: 'What is Phase 2 of SIT?', options: ['Education', 'Application', 'Recovery', 'Skill Acquisition — learning coping tools'], correctAnswer: 3, explanation: 'Phase 2 involves learning the tools (breathing, reappraisal, visualisation) before applying them.' },
    { type: 'multiple_choice', question: 'What does each successful stress exposure provide?', options: ['Evidence that you can handle hard things', 'Nothing', 'Physical strength', 'More stress'], correctAnswer: 0, explanation: 'Successful exposure builds experiential confidence that no theory can replicate.' },
    { type: 'multiple_choice', question: 'What is the enemy of growth in this context?', options: ['Comfort', 'Knowledge', 'Other people', 'Challenge'], correctAnswer: 0, explanation: 'Sustained comfort prevents the adaptive challenges needed for resilience growth.' },
    { type: 'multiple_choice', question: 'What is stress inoculation training (SIT)?', options: ['Only for military personnel', 'Avoiding all stress', 'Gradually exposing yourself to manageable stress to build tolerance — like a vaccine for stress', 'Taking supplements for stress'], correctAnswer: 2, explanation: 'SIT works like vaccination — small, controlled doses of stress build your capacity to handle larger stressors.' },
    { type: 'multiple_choice', question: 'What is the key principle of progressive stress exposure?', options: ['Start at your maximum capacity', 'Start below your current threshold and gradually increase', 'Avoid all stress', 'Random exposure is best'], correctAnswer: 1, explanation: 'Like progressive overload in training, start at a manageable level and increase gradually as tolerance builds.' },
    { type: 'multiple_choice', question: 'What makes cold showers an effective stress inoculation tool?', options: ['They are convenient, controllable, and create acute stress that you voluntarily manage', 'They only work in winter', 'They are dangerous', 'They have no stress benefit'], correctAnswer: 0, explanation: 'Cold showers provide a convenient, controlled stress that you choose to enter — training your nervous system to remain calm under pressure.' },
    { type: 'multiple_choice', question: 'What should you do if a stress exposure feels overwhelming?', options: ['Double the exposure next time', 'Push through regardless', 'Reduce intensity — the goal is challenge, not trauma', 'Give up permanently'], correctAnswer: 2, explanation: 'Overwhelming stress is counterproductive — reduce the intensity and build up gradually. Challenge, not trauma.' },
    { type: 'multiple_choice', question: 'How does stress inoculation transfer to real life?', options: ['Only for physical stress', 'The nervous system learns to manage acute arousal, which generalises to all stressful situations', 'It does not transfer', 'It only helps with the specific stressor practised'], correctAnswer: 1, explanation: 'The ability to remain calm under voluntary stress transfers broadly — cold shower composure helps in difficult conversations, presentations, and emergencies.' },
  
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Meditation only', 'Paying attention to the present moment without judgement', 'Thinking positive thoughts', 'Clearing your mind'], correctAnswer: 1, explanation: 'Mindfulness is present-moment awareness — not thought suppression or forced positivity.' },
    { type: 'multiple_choice', question: 'Where does most mental suffering come from?', options: ['Past rumination and future worry', 'Other people', 'Physical pain', 'The present'], correctAnswer: 0, explanation: 'Most suffering comes from dwelling on the past (regret) or worrying about the future (anxiety).' },
    { type: 'multiple_choice', question: 'What is the minimum effective daily mindfulness practice?', options: ['30 minutes', '3 minutes', '1 hour', '0 minutes — just think about it'], correctAnswer: 1, explanation: 'Even 3 minutes of consistent daily practice produces measurable benefits.' },
    { type: 'multiple_choice', question: 'When your mind wanders during meditation, what should you do?', options: ['Notice it wandered and gently return to the breath', 'Give up', 'Get frustrated', 'Try harder to stop thoughts'], correctAnswer: 0, explanation: 'Noticing and returning is the practice itself — each return strengthens the attention muscle.' },
    { type: 'multiple_choice', question: 'Can mindfulness be practised during daily activities?', options: ['Only in silence', 'No — only during formal meditation', 'Only during yoga', 'Yes — eating, walking, or commuting mindfully counts'], correctAnswer: 3, explanation: 'Informal mindfulness (eating, walking without distraction) is equally valuable practice.' },
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Emptying your mind completely', 'Thinking positive thoughts', 'A religious practice', 'Paying attention to the present moment without judgement'], correctAnswer: 3, explanation: 'Mindfulness is non-judgemental present-moment awareness — noticing what is happening right now without labelling it good or bad.' },
    { type: 'multiple_choice', question: 'What does "non-judgemental" mean in mindfulness?', options: ['Approving of everything', 'Observing thoughts and sensations without labelling them as good or bad', 'Having no opinions', 'Ignoring problems'], correctAnswer: 1, explanation: 'Non-judgemental awareness means observing without the automatic reaction of categorising — just noticing.' },
    { type: 'multiple_choice', question: 'What happens to the brain during regular meditation practice?', options: ['The prefrontal cortex thickens and the amygdala shrinks — improving regulation and reducing reactivity', 'The brain gets smaller', 'Only the amygdala changes', 'Nothing changes'], correctAnswer: 0, explanation: 'Regular meditation physically changes brain structure — strengthening areas for focus and regulation while reducing reactivity centres.' },
    { type: 'multiple_choice', question: 'How long should a beginner meditation session be?', options: ['2 minutes is too short to have any effect', '5 minutes — consistency matters more than duration', '30 minutes minimum', '1 hour'], correctAnswer: 1, explanation: 'Five minutes daily is sufficient for beginners — building the habit is more important than session length.' },
    { type: 'multiple_choice', question: 'What should you do when your mind wanders during meditation?', options: ['You have failed — stop and try again later', 'Notice it without judgement and gently return attention to your anchor — this IS the practice', 'Start over from the beginning', 'Force yourself to think of nothing'], correctAnswer: 1, explanation: 'Mind wandering is not failure — noticing it and returning attention is the actual exercise, like a bicep curl for your attention.' },
  
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the minimum effective dose for a daily protocol?', options: ['2 hours', 'Whatever you can do consistently', '30 seconds', '90 minutes'], correctAnswer: 1, explanation: 'The minimum effective dose is the shortest practice you can maintain every single day.' },
    { type: 'multiple_choice', question: 'How often should you adjust your resilience protocol?', options: ['Daily', 'Monthly', 'Never', 'Every hour'], correctAnswer: 1, explanation: 'Monthly reviews allow assessment of what works while keeping the protocol evolving.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of resilience training?', options: ['Becoming invincible', 'Following a strict protocol forever', 'Integration — practices feel as natural as brushing your teeth', 'Eliminating all emotions'], correctAnswer: 2, explanation: 'The goal is for practices to become automatic parts of your identity, not forced routines.' },
    { type: 'multiple_choice', question: 'When should you progress to harder challenges?', options: ['Immediately', 'After reading more theory', 'Never', 'When the current level feels manageable and consistent'], correctAnswer: 3, explanation: 'Only progress when the current level is consistent — rushing leads to burnout.' },
    { type: 'multiple_choice', question: 'What matters more than the specific practices chosen?', options: ['How impressive they sound', 'Consistency of doing them', 'How long each takes', 'The equipment used'], correctAnswer: 1, explanation: 'Consistent small practices beat sporadic impressive ones — always.' },
    { type: 'multiple_choice', question: 'What is a resilience protocol?', options: ['A personalised daily structure combining the tools from the course into sustainable habits', 'A one-time workshop', 'A set of rules imposed by someone else', 'A medical treatment'], correctAnswer: 0, explanation: 'A resilience protocol is your personalised daily system — combining breathwork, movement, mindfulness, journaling, and recovery into a sustainable routine.' },
    { type: 'multiple_choice', question: 'What is the most important quality of a resilience protocol?', options: ['Impressiveness', 'Sustainability — you must actually do it consistently', 'Complexity', 'Length'], correctAnswer: 1, explanation: 'The best protocol is one you will actually follow — a simple, sustainable routine beats an ambitious one you abandon after a week.' },
    { type: 'multiple_choice', question: 'How should you start building your protocol?', options: ['Include everything you have learned immediately', 'Start with 2–3 non-negotiable daily practices and add more once those are solid', 'Wait until you feel ready', 'Copy someone else\'s exactly'], correctAnswer: 1, explanation: 'Start with a minimal viable protocol — 2–3 practices — and add complexity only when the foundation is habitual.' },
    { type: 'multiple_choice', question: 'What are "non-negotiables" in a resilience protocol?', options: ['Optional extras', 'Things other people tell you to do', 'The 2–3 daily practices you commit to doing regardless of circumstances', 'Things you negotiate away when busy'], correctAnswer: 2, explanation: 'Non-negotiables are your absolute minimum — the practices you do even on your worst day, even if everything else gets dropped.' },
    { type: 'multiple_choice', question: 'Why should you review and adjust your protocol regularly?', options: ['To add more practices', 'Protocols never need changing', 'Life changes — what works now may not work in three months, and your needs evolve', 'To make it harder'], correctAnswer: 2, explanation: 'Regular review (monthly or quarterly) ensures your protocol stays relevant, challenging, and aligned with your current life.' },
  
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'How does one night of poor sleep (under 6 hours) affect testosterone?', options: ['Reduces it by up to 15%', 'Doubles it', 'Increases it by 10%', 'No effect'], correctAnswer: 0, explanation: 'A single night of poor sleep can reduce testosterone levels by up to 15%, impacting recovery, mood, and performance.' },
    { type: 'multiple_choice', question: 'Which sleep stage is most responsible for physical recovery and growth hormone release?', options: ['REM sleep', 'Stage 2 (N2)', 'Deep sleep / Stage 3 (N3)', 'Stage 1 (N1)'], correctAnswer: 2, explanation: 'Deep sleep (N3 / slow-wave sleep) is when growth hormone release peaks, muscle repair occurs, and immune function is restored.' },
    { type: 'multiple_choice', question: 'What is the optimal bedroom temperature for sleep?', options: ['16-19°C', 'As warm as possible', '20-24°C', '25-28°C'], correctAnswer: 0, explanation: 'The optimal sleep temperature is 16-19°C (60-67°F). Your body needs to drop its core temperature to initiate and maintain deep sleep.' },
    { type: 'scenario', question: 'Which habit is most likely causing the poor sleep?', scenario: 'A person drinks a coffee at 4pm, trains at 7pm, and then scrolls social media in bed from 10-11pm. They struggle to fall asleep before midnight.', options: ['They are not tired enough', 'Training at 7pm', 'All three habits are contributing — caffeine half-life means it is still active, and blue light from screens suppresses melatonin', 'They need a softer pillow'], correctAnswer: 2, explanation: 'Caffeine has a 5-6 hour half-life (still half-active at 10pm from a 4pm coffee), and blue light from screens suppresses melatonin production by up to 50%. Both significantly impair sleep onset.' },
    { type: 'multiple_choice', question: 'Why does morning sunlight exposure improve evening sleep quality?', options: ['It increases cortisol permanently', 'It wakes you up with a shock', 'It has no effect on sleep', 'It sets your circadian clock, which determines when melatonin production begins in the evening'], correctAnswer: 3, explanation: 'Bright morning light exposure sets the circadian clock via the suprachiasmatic nucleus, which determines the timing of melatonin release in the evening — improving sleep onset and quality.' },
    { type: 'multiple_choice', question: 'What is the purpose of an evening wind-down routine?', options: ['To check social media one last time', 'To signal to your brain and body that the day is ending, facilitating the transition to sleep', 'To squeeze in extra productivity', 'To waste time'], correctAnswer: 1, explanation: 'An evening routine creates a consistent transition signal — helping the nervous system shift from daytime sympathetic tone to parasympathetic rest mode.' },
    { type: 'multiple_choice', question: 'What is a brain dump before bed?', options: ['A medical procedure', 'Reading before sleep', 'Writing down all tasks, worries, and loose thoughts so your brain does not try to hold them overnight', 'Forgetting everything'], correctAnswer: 2, explanation: 'A pre-bed brain dump clears working memory — transferring open loops to paper so the brain can stop processing them during sleep.' },
    { type: 'multiple_choice', question: 'Why is a consistent bedtime routine more effective than just a consistent bedtime?', options: ['It is not more effective', 'The routine acts as a series of sleep cues that progressively lower arousal before you get into bed', 'Only the routine matters, not the time', 'Bedtime does not matter'], correctAnswer: 1, explanation: 'A routine creates conditioned sleep cues — dim lights, breathwork, reading — that gradually lower arousal, making sleep onset faster and deeper.' },
    { type: 'multiple_choice', question: 'What should an evening routine ideally include?', options: ['Watching exciting films', 'A heavy workout', 'Caffeine to stay alert', 'Screen time shutdown, brain dump, calming breathwork, and preparation for tomorrow'], correctAnswer: 3, explanation: 'An effective evening routine includes digital shutdown (60 min before bed), brain dump, breathwork (4-7-8 or extended exhale), and light preparation for tomorrow.' },
    { type: 'multiple_choice', question: 'How does sleep deprivation affect decision-making?', options: ['It has no effect', 'It impairs prefrontal cortex function, leading to poorer judgement, more impulsivity, and greater emotional reactivity', 'It improves creativity', 'It only affects physical performance'], correctAnswer: 1, explanation: 'Sleep deprivation hits the prefrontal cortex hardest — impairing the exact functions needed for good decisions: impulse control, risk assessment, and emotional regulation.' },
  
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Why does writing down thoughts improve mental clarity?', options: ['It does not — it is a waste of time', 'It is a form of exercise', 'Writing forces you to translate vague feelings into structured language, allowing the brain to process and release them', 'It improves handwriting'], correctAnswer: 2, explanation: 'When thoughts stay in your head, they loop. Writing forces translation into language, engaging the prefrontal cortex and allowing the brain to process and let go.' },
    { type: 'multiple_choice', question: 'Which type of journaling is best for processing difficult emotions?', options: ['Training logs only', 'Gratitude journaling', 'Goal setting', 'Free writing / stream of consciousness'], correctAnswer: 3, explanation: "Free writing — writing whatever comes to mind without structure — is the most effective journaling method for processing emotions, as shown by James Pennebaker\'s research." },
    { type: 'multiple_choice', question: 'What brain system does handwriting activate that increases attention?', options: ['The limbic system', 'The cerebellum', 'The reticular activating system (RAS)', 'The hippocampus only'], correctAnswer: 2, explanation: 'Handwriting activates the reticular activating system (RAS), which filters information and signals the brain to pay closer attention to what is being written.' },
    { type: 'multiple_choice', question: 'What is the most common reason people stop journaling?', options: ['Journaling stops working after a week', 'They make it too complicated or expect too much', 'They run out of paper', 'They have nothing to write about'], correctAnswer: 1, explanation: 'Overcomplicating the practice — expecting long entries, perfect writing, or deep insights every time — is the most common barrier. Three honest sentences is better than three unwritten pages.' },
    { type: 'scenario', question: 'Which journaling method would best help them?', scenario: "Someone lies awake at night with racing thoughts about tomorrow\'s tasks and unresolved worries from the day.", options: ['A brain dump — writing down all tasks, worries, and thoughts to get them out of their head', 'Goal setting for next year', 'Free writing about childhood', 'Gratitude journaling'], correctAnswer: 0, explanation: 'A brain dump before bed clears working memory by transferring thoughts from mind to paper, preventing the brain from trying to hold and process them during sleep.' },
    { type: 'multiple_choice', question: 'What does \"cognitive processing\" mean in the context of journaling?', options: ['Using a computer', 'Memorising information', 'Writing transforms vague emotional noise into structured thought, reducing its intensity', 'Processing speed of the brain'], correctAnswer: 2, explanation: 'Journaling forces translation of diffuse feelings into structured language — this cognitive processing reduces emotional charge and creates clarity.' },
    { type: 'multiple_choice', question: 'What is a \"worry dump\" and when should you use it?', options: ['Talking to friends about worries', 'Writing all current worries on paper to clear working memory — especially before bed or when overwhelmed', 'A type of exercise', 'Throwing away worries'], correctAnswer: 1, explanation: 'A worry dump transfers open loops from working memory to paper — preventing rumination and freeing cognitive resources for rest or focus.' },
    { type: 'multiple_choice', question: 'How does journaling about training improve performance?', options: ['Only professional athletes benefit', 'It does not help', 'It creates a feedback loop — recording sessions reveals patterns, progress, and areas for adjustment', 'It replaces actual training'], correctAnswer: 2, explanation: 'Training journals reveal patterns invisible in day-to-day experience — what works, what does not, and how external factors affect performance.' },
    { type: 'multiple_choice', question: 'What is the minimum effective journaling practice?', options: ['500 words minimum', 'Writing for 2 hours daily', 'Three honest sentences — what happened, how you feel, what you will do next', 'Only writing when something significant happens'], correctAnswer: 2, explanation: 'Three sentences is enough — the act of writing matters more than the volume. Consistency beats quantity.' },
    { type: 'multiple_choice', question: 'Why is handwriting often more effective than typing for journaling?', options: ['Typing is too difficult', 'Handwriting activates different brain regions and slows you down, increasing cognitive engagement', 'Handwriting is faster', 'It is not — typing is always better'], correctAnswer: 1, explanation: 'Handwriting engages the reticular activating system and slows processing — both increase depth of thought and emotional processing.' },
  
  ]),
  cq(4, 7, [
    { type: 'multiple_choice', question: 'What percentage of daily energy does the brain consume?', options: ['5%', '20%', '50%', '10%'], correctAnswer: 1, explanation: 'The brain accounts for roughly 2% of body weight but consumes approximately 20% of daily energy.' },
    { type: 'multiple_choice', question: 'What causes the common afternoon energy slump?', options: ['Often a blood glucose crash from lunch composition', 'Too much water', 'Natural circadian dip only', 'Lack of caffeine'], correctAnswer: 0, explanation: 'The afternoon slump is often a blood glucose crash, not a natural circadian dip — adjusting lunch composition can eliminate it.' },
    { type: 'multiple_choice', question: 'At what level of dehydration does cognitive performance measurably decline?', options: ['1–2% body weight loss', '5% body weight loss', '10% body weight loss', 'Only when you feel thirsty'], correctAnswer: 0, explanation: 'Even mild dehydration of 1–2% body weight loss measurably impairs attention, working memory, and mood.' },
    { type: 'multiple_choice', question: 'Which nutrient is essential for brain cell membrane integrity and neurotransmitter function?', options: ['Calcium', 'Iron', 'Vitamin C', 'Omega-3 fatty acids (EPA/DHA)'], correctAnswer: 3, explanation: 'Omega-3 fatty acids are essential for brain cell membranes, anti-inflammatory effects, and neurotransmitter function.' },
    { type: 'multiple_choice', question: 'What should you check before reaching for caffeine when focus drops?', options: ['Have I eaten recently? Am I hydrated? Did I sleep well?', 'The time of day', 'Your email inbox', 'Whether the coffee is fresh'], correctAnswer: 0, explanation: 'Before using caffeine, check the fundamentals: recent food intake, hydration status, and sleep quality.' },
    { type: 'multiple_choice', question: 'Why is magnesium important for mental performance?', options: ['It builds muscle', 'It supports nervous system function and sleep quality', 'It has no role in mental performance', 'It increases caffeine sensitivity'], correctAnswer: 1, explanation: 'Magnesium supports nervous system function and sleep quality — found in dark chocolate, nuts, seeds, and leafy greens.' },
    { type: 'multiple_choice', question: 'What is the connection between blood glucose and focus?', options: ['Stable blood glucose supports sustained focus; spikes and crashes impair concentration', 'High blood sugar improves focus', 'No connection', 'Low blood sugar is optimal'], correctAnswer: 0, explanation: 'The brain needs stable glucose — rapid spikes from refined carbs cause crashes that impair attention and mood.' },
    { type: 'multiple_choice', question: 'What is the gut-brain axis?', options: ['A type of supplement', 'A brain region', 'A yoga pose', 'The bidirectional communication system between the gut and the brain via the vagus nerve'], correctAnswer: 3, explanation: 'The gut and brain communicate constantly via the vagus nerve — gut health directly influences mood, focus, and mental clarity.' },
    { type: 'multiple_choice', question: 'How much water should you drink daily for cognitive function?', options: ['Only when thirsty', '8 cups is a myth — no amount matters', '2–3 litres, adjusted for body size, activity, and climate', 'As little as possible'], correctAnswer: 2, explanation: 'Most adults need 2–3 litres daily, but this varies — thirst is an unreliable indicator as cognitive effects begin before you feel thirsty.' },
    { type: 'multiple_choice', question: 'What breakfast composition supports sustained mental energy?', options: ['High sugar cereal', 'Skipping breakfast is always best', 'Protein + complex carbohydrate + healthy fat for slow, stable energy release', 'Only caffeine'], correctAnswer: 2, explanation: 'Combining protein, complex carbs, and healthy fat provides sustained energy without the blood glucose crashes of high-sugar breakfasts.' },
  
  ]),
  cq(4, 8, [
    { type: 'multiple_choice', question: 'What is the Japanese principle of kaizen?', options: ['Only working when motivated', 'Maximum effort at all times', 'Dramatic transformation', 'Continuous, incremental improvement'], correctAnswer: 3, explanation: 'Kaizen means continuous, incremental improvement — getting 1% better consistently rather than seeking dramatic change.' },
    { type: 'multiple_choice', question: 'How much does 1% daily improvement compound to over one year?', options: ['2× improvement', '37× improvement', '365% improvement', '12× improvement'], correctAnswer: 1, explanation: '1% daily improvement compounds to approximately 37× improvement over a year — showing the power of consistency.' },
    { type: 'multiple_choice', question: 'What should a weekly review primarily focus on?', options: ['Completely overhauling your plan', 'Comparing yourself to others', 'Punishing yourself for failures', 'Wins, lessons, and one or two targeted adjustments'], correctAnswer: 3, explanation: 'A weekly review identifies wins, extracts lessons, and makes small targeted adjustments — not dramatic overhauls.' },
    { type: 'multiple_choice', question: 'How long should a weekly review take?', options: ['An entire day', '10 minutes is sufficient', 'At least 2 hours', '30 seconds'], correctAnswer: 1, explanation: 'Ten minutes of honest reflection is sufficient — consistency beats complexity in weekly reviews.' },
    { type: 'multiple_choice', question: 'What is more important: goals or systems?', options: ['Goals are all that matter', 'Systems are unnecessary if you have goals', 'Neither matters — just work harder', 'Goals set direction; systems produce results'], correctAnswer: 3, explanation: 'Goals set direction, but systems produce results. The weekly review is a system for ensuring your systems work.' },
    { type: 'multiple_choice', question: 'What is the purpose of tracking lead indicators?', options: ['They are unnecessary', 'To compare with others', 'To measure outcomes', 'They are actions within your control that predict future outcomes'], correctAnswer: 3, explanation: 'Lead indicators (sessions done, sleep hours, meals prepared) are within your control and predict outcomes better than tracking outcomes alone.' },
    { type: 'multiple_choice', question: 'What should you do when a review shows poor adherence?', options: ['Punish yourself', 'Add more goals', 'Give up', 'Simplify the plan — poor adherence usually means the plan is too ambitious, not that you lack willpower'], correctAnswer: 3, explanation: 'Low adherence is usually a sign the plan needs simplifying — reduce to fewer, easier actions rather than blaming yourself.' },
    { type: 'multiple_choice', question: 'What is the compound effect?', options: ['A chemical reaction', 'A one-time big effort', 'Small consistent actions accumulating into dramatic results over time', 'A marketing strategy'], correctAnswer: 2, explanation: 'The compound effect shows how tiny daily improvements (1% better) accumulate exponentially — 37× improvement over a year.' },
    { type: 'multiple_choice', question: 'What are the three review questions recommended for weekly check-ins?', options: ['What went well? What did I learn? What will I adjust?', 'What did I buy? What did I watch? What did I eat?', 'How much weight did I lose? How fast did I run? How much did I lift?', 'What did others do? How do I compare? Am I falling behind?'], correctAnswer: 0, explanation: 'Three simple questions: What went well (celebrate wins), what did I learn (extract lessons), and what will I adjust (targeted improvement).' },
    { type: 'multiple_choice', question: 'Why should you celebrate small wins during reviews?', options: ['Acknowledging progress reinforces the behaviour loop and sustains motivation', 'Only big wins deserve celebration', 'To feel superior', 'Small wins do not matter'], correctAnswer: 0, explanation: 'Celebrating small wins activates the reward system, reinforcing the behaviours that produced them and sustaining long-term motivation.' },
  ]),
];
