import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'Is resilience an innate trait or a trainable skill?', options: ["Innate — you either have it or you don\'t", 'Determined by genetics alone', 'Only for athletes', 'Trainable — it develops through practice'], correctAnswer: 3, explanation: 'Research consistently shows resilience is a set of trainable skills, not a fixed trait.' },
    { type: 'multiple_choice', question: 'What are the three components of resilience?', options: ['Adaptability, Emotional Regulation, Recovery', 'Speed, Strength, Power', 'Courage, Endurance, Discipline', 'Intelligence, Creativity, Memory'], correctAnswer: 0, explanation: 'Resilience comprises adaptability, emotional regulation, and recovery capacity.' },
    { type: 'multiple_choice', question: 'Does resilience mean never feeling stressed?', options: ['Only under extreme conditions', 'No — resilient people still feel stress but process it effectively', 'It depends on personality', 'Yes'], correctAnswer: 1, explanation: 'Resilient people experience the full range of emotions but have better systems for processing them.' },
    { type: 'multiple_choice', question: 'What does growth orientation mean in the context of resilience?', options: ['Viewing challenges as opportunities for development', 'Ignoring problems', 'Getting taller', 'Always being positive'], correctAnswer: 0, explanation: 'Growth orientation means seeing challenges as development opportunities rather than threats.' },
    { type: 'multiple_choice', question: 'What is the misconception about resilience that causes harm?', options: ['That it can be learned', 'That it requires practice', 'That it means never breaking — which discourages seeking help', 'That it involves emotions'], correctAnswer: 2, explanation: 'The \'never break" myth frames normal emotional responses as weakness and discourages help-seeking.' },
    { type: 'multiple_choice', question: 'How is mental resilience built?', options: ['Through medication', 'Through deliberate exposure to manageable challenges and structured recovery', 'Through avoiding all stress', 'Through reading about it'], correctAnswer: 1, explanation: 'Like physical strength, resilience builds through progressive challenge and recovery.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'Can your brain distinguish between real and perceived threats?', options: ['No — both trigger the same fight-or-flight response', 'Yes, always', 'Only when you are calm', 'Only in adults'], correctAnswer: 0, explanation: 'The amygdala triggers the same physiological cascade for both real and perceived threats.' },
    { type: 'multiple_choice', question: 'What is the difference between acute and chronic stress?', options: ['Acute is short-term and beneficial; chronic is sustained and harmful', 'Acute only affects athletes', 'They are the same', 'Acute is bad, chronic is good'], correctAnswer: 0, explanation: 'Acute stress drives adaptation; chronic stress damages health and performance.' },
    { type: 'multiple_choice', question: 'What does elevated cortisol promote?', options: ['Muscle growth', 'Fat storage, immune suppression, and sleep disruption', 'Better focus', 'Faster recovery'], correctAnswer: 1, explanation: 'Chronic cortisol elevation promotes visceral fat storage, impairs immunity, and disrupts sleep.' },
    { type: 'multiple_choice', question: 'What hormone provides immediate energy during acute stress?', options: ['Insulin', 'Melatonin', 'Adrenaline', 'Cortisol'], correctAnswer: 2, explanation: 'Adrenaline provides the immediate energy and alertness burst during acute stress.' },
    { type: 'multiple_choice', question: 'What is the key message about stress management?', options: ['Ignore stress', 'Eliminate all stress', 'Control your relationship with stress — do not eliminate it', 'Only manage work stress'], correctAnswer: 2, explanation: 'The goal is managing your response to stress, not eliminating stress entirely.' },
    { type: 'multiple_choice', question: 'If you are constantly tired, frequently ill, and sleeping poorly, what is likely too high?', options: ['Your total stress load', 'Your motivation', 'Your happiness', 'Your protein intake'], correctAnswer: 0, explanation: 'These symptoms typically indicate an excessive total stress load across all life domains.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What are the two branches of the autonomic nervous system?', options: ['Somatic and reflex', 'Motor and sensory', 'Central and peripheral', 'Sympathetic and parasympathetic'], correctAnswer: 3, explanation: 'The ANS has sympathetic (accelerator) and parasympathetic (brake) branches.' },
    { type: 'multiple_choice', question: 'What is vagal tone?', options: ['The strength and efficiency of the vagus nerve', 'A type of meditation', 'A sound the vagus nerve makes', 'A breathing technique'], correctAnswer: 0, explanation: 'Higher vagal tone is associated with better stress recovery, emotional regulation, and resilience.' },
    { type: 'multiple_choice', question: 'What happens to heart rate during exhalation?', options: ['It stops', 'It increases', 'It stays the same', 'It decreases'], correctAnswer: 3, explanation: 'Heart rate naturally decreases during exhale — a phenomenon called respiratory sinus arrhythmia.' },
    { type: 'multiple_choice', question: 'Why is breathing unique among autonomic functions?', options: ['It can be controlled both voluntarily and involuntarily', 'It uses the most energy', 'It cannot be changed', 'It only works when conscious'], correctAnswer: 0, explanation: 'Breathing is the only autonomic function you can also control voluntarily — bridging conscious and unconscious systems.' },
    { type: 'multiple_choice', question: 'What type of breathing activates the sympathetic system?', options: ['Extended exhale breathing', 'Diaphragmatic breathing', 'Fast shallow chest breathing', 'Slow nasal breathing'], correctAnswer: 2, explanation: 'Fast, shallow chest breathing signals stress and activates sympathetic tone.' },
    { type: 'multiple_choice', question: 'What does nasal breathing produce that mouth breathing does not?', options: ['More CO2', 'Adrenaline', 'Nitric oxide', 'More oxygen'], correctAnswer: 2, explanation: 'Nasal breathing activates nitric oxide production, which aids blood flow and oxygen delivery.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What does a fixed mindset believe about abilities?', options: ['They improve with age', 'They do not exist', 'They are innate and unchangeable', 'They are developed through effort'], correctAnswer: 2, explanation: 'Fixed mindset assumes abilities are innate — you either have them or you do not.' },
    { type: 'multiple_choice', question: 'What is the most powerful single word for shifting to a growth mindset?', options: ['Yet', 'Always', 'No', 'Never'], correctAnswer: 0, explanation: '"Yet" transforms dead ends into directions: "I can\'t do this... yet."' },
    { type: 'multiple_choice', question: 'Can you hold different mindsets in different areas of life?', options: ['Yes — most people have different mindsets in different domains', 'Only if you are a beginner', 'No — you are either fixed or growth', 'Only children can'], correctAnswer: 0, explanation: 'Most people hold growth mindsets in some areas and fixed mindsets in others.' },
    { type: 'multiple_choice', question: 'How does a growth mindset respond to failure?', options: ['Gives up', "Pretends it didn\'t happen", 'Asks "what can I learn?" and adjusts approach', 'Blames others'], correctAnswer: 2, explanation: 'Growth mindset attributes failure to changeable behaviours and strategies, not fixed traits.' },
    { type: 'multiple_choice', question: 'Does growth mindset mean you can achieve anything?', options: ['Only with a coach', 'Yes, with enough effort', 'Only in sport', 'No — genetics and circumstances matter, but mindset influences what you do within your constraints'], correctAnswer: 3, explanation: 'Growth mindset means optimising within constraints, not ignoring reality.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'Which goal type is entirely within your control?', options: ['Process goal', 'Dream goal', 'Outcome goal', 'Performance goal'], correctAnswer: 0, explanation: 'Process goals (daily actions) are fully controllable regardless of external factors.' },
    { type: 'multiple_choice', question: 'Why do outcome goals become discouraging?', options: ['Progress is often slow or invisible, eroding motivation', 'They cost too much', 'They are too easy', 'They are unrealistic by definition'], correctAnswer: 0, explanation: 'When results are slow, outcome-dependent motivation collapses despite perfect process.' },
    { type: 'multiple_choice', question: 'What makes process goals sustain motivation?', options: ['They are easier to set', 'They are impressive to others', 'They provide daily wins that accumulate into habit formation', 'They require no effort'], correctAnswer: 2, explanation: 'Daily small wins from process goals build habits — which are more powerful than motivation.' },
    { type: 'multiple_choice', question: 'How often should you review performance goals?', options: ['Daily', 'Monthly', 'Weekly', 'Yearly'], correctAnswer: 1, explanation: 'Monthly reviews give enough time to see trends while allowing timely adjustments.' },
    { type: 'multiple_choice', question: 'How long should you try a new process before concluding it is not working?', options: ['1 year', '2–4 weeks', '6 months', '1 day'], correctAnswer: 1, explanation: 'Give each process adjustment at least 2–4 weeks before evaluating its effectiveness.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What is the single most powerful recovery tool?', options: ['Massage', 'Ice baths', 'Sleep', 'Supplements'], correctAnswer: 2, explanation: 'Sleep is the most powerful recovery tool — no supplement or technique can compensate for poor sleep.' },
    { type: 'multiple_choice', question: 'What predominates in the first half of the night?', options: ['No sleep stages dominate', 'REM sleep', 'Deep sleep (N3)', 'Light sleep only'], correctAnswer: 2, explanation: 'Deep sleep predominates in the first half; REM predominates in the second half.' },
    { type: 'multiple_choice', question: 'What does REM sleep support?', options: ['Bone density', 'Physical recovery only', 'Muscle growth', 'Emotional processing, creativity, and memory consolidation'], correctAnswer: 3, explanation: 'REM sleep is essential for emotional processing, creativity, and memory consolidation.' },
    { type: 'multiple_choice', question: 'Why does alcohol impair sleep despite helping you fall asleep?', options: ['It does not impair sleep', 'It disrupts sleep architecture, reducing REM and deep sleep', 'It only affects light sleep', 'It makes you sleep too long'], correctAnswer: 1, explanation: 'Alcohol significantly reduces the quality of sleep by disrupting both REM and deep sleep phases.' },
    { type: 'multiple_choice', question: 'What triggers melatonin release?', options: ['Darkness', 'Caffeine', 'Exercise', 'Bright light'], correctAnswer: 0, explanation: 'Darkness triggers melatonin release, which is why reducing light before bed aids sleep onset.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'What is self-compassion most accurately described as?', options: ['Making excuses for poor performance', 'Treating yourself with the same fairness you would offer a friend', 'Ignoring your mistakes', 'Lowering your standards'], correctAnswer: 1, explanation: 'Self-compassion means responding to yourself with the same perspective and fairness you would offer a friend in the same situation.' },
    { type: 'multiple_choice', question: 'What does constant harsh self-criticism activate?', options: ['The reward system', 'The threat system, flooding the body with cortisol', 'The parasympathetic nervous system', 'Creative thinking'], correctAnswer: 1, explanation: 'Harsh self-criticism activates the threat system, producing cortisol and suppressing cognitive functions needed for learning.' },
    { type: 'multiple_choice', question: 'What are the three components of self-compassion?', options: ['Self-kindness, common humanity, mindful awareness', 'Discipline, grit, determination', 'Confidence, ambition, success', 'Acceptance, avoidance, denial'], correctAnswer: 0, explanation: 'Kristin Neff identifies self-kindness, common humanity, and mindful awareness as the three pillars of self-compassion.' },
    { type: 'multiple_choice', question: 'What does research show about referring to yourself in the third person during stress?', options: ['It is a sign of mental illness', 'It reduces emotional reactivity and improves performance under pressure', 'It has no effect', 'It increases anxiety'], correctAnswer: 1, explanation: 'Third-person self-talk creates psychological distance from stressful situations, reducing reactivity and improving performance.' },
    { type: 'multiple_choice', question: 'What is the relationship between self-compassion and motivation?', options: ['Self-compassionate people are less motivated', 'Self-compassionate people are more motivated and more likely to take responsibility', 'There is no relationship', 'Self-compassion only works for beginners'], correctAnswer: 1, explanation: 'Research consistently shows self-compassionate people are more motivated, resilient, and willing to take responsibility for mistakes.' },
    { type: 'multiple_choice', question: 'What is the first step in restructuring inner dialogue?', options: ['Immediately replacing negative thoughts with positive ones', 'Noticing what your inner voice says during stress without judgement', 'Ignoring your thoughts completely', 'Reading motivational quotes'], correctAnswer: 1, explanation: 'The first step is simply noticing and recording your inner dialogue — awareness precedes change.' },
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'What did the Harvard Study of Adult Development find was the strongest predictor of health and wellbeing?', options: ['Wealth', 'IQ', 'Quality of relationships', 'Physical fitness'], correctAnswer: 2, explanation: 'The Harvard study, running since 1938, found relationship quality is the single strongest predictor of health and wellbeing.' },
    { type: 'multiple_choice', question: 'How does loneliness compare to smoking in terms of health risk?', options: ['Loneliness has no physical health impact', 'Loneliness is comparable to smoking 15 cigarettes per day', 'Loneliness is less harmful than any amount of smoking', 'Loneliness only affects mental health'], correctAnswer: 1, explanation: 'Research shows loneliness increases cardiovascular risk comparable to smoking 15 cigarettes per day.' },
    { type: 'multiple_choice', question: 'How many genuine relationships provide most of the resilience benefits of social connection?', options: ['At least 20', 'At least 50', 'Two or three', 'Only one'], correctAnswer: 2, explanation: 'Research suggests even two or three genuine, reciprocal relationships provide most of the resilience benefits of social connection.' },
    { type: 'multiple_choice', question: 'What is perceived loneliness?', options: ['Feeling disconnected even when around people', 'Being physically alone', 'Choosing to spend time alone', 'Not having social media'], correctAnswer: 0, explanation: 'Perceived loneliness — feeling disconnected despite being around others — is as harmful as actual isolation.' },
    { type: 'multiple_choice', question: 'Why is vulnerability important for authentic connection?', options: ['It makes others feel sorry for you', 'It is not important — always appear strong', 'Pretending everything is fine prevents people from actually supporting you', 'It only matters in romantic relationships'], correctAnswer: 2, explanation: 'Authentic connection requires showing up honestly — pretending everything is fine prevents genuine support.' },
  ]),
];
