import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What is the most important quality of a morning routine?', options: ['Length', 'Start time', 'Consistency', 'Complexity'], correctAnswer: 2, explanation: 'A consistent short routine beats an ambitious one that is abandoned.' },
    { type: 'multiple_choice', question: 'Why avoid checking your phone first thing?', options: ['Screens are bad', 'It is impolite', 'Battery conservation', 'It puts you in reactive mode'], correctAnswer: 3, explanation: 'Checking your phone immediately floods you with external demands and reactive thinking.' },
    { type: 'multiple_choice', question: 'How much water should you drink upon waking?', options: ['500ml', '2 litres', 'None', 'A sip'], correctAnswer: 0, explanation: 'You wake mildly dehydrated — 500ml rehydrates and supports alertness.' },
    { type: 'multiple_choice', question: 'What is the recommended starting duration for a morning routine?', options: ['10–15 minutes', '5 seconds', '2 hours', '90 minutes'], correctAnswer: 0, explanation: 'Start with 10–15 minutes and build as the habit solidifies.' },
    { type: 'multiple_choice', question: 'What is the core principle of morning routine design?', options: [', ', ', ', ', ', 'Copy someone else\'], correctAnswer: 0, explanation: 'A sustainable short routine done daily transforms life; an ambitious one abandoned does not.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What is stress inoculation training based on?', options: ['Avoiding stress', 'Maximum stress exposure', 'Medication', 'Controlled exposure to manageable stress builds resilience'], correctAnswer: 3, explanation: 'Like a vaccine, SIT uses controlled exposure to build capacity for handling larger stressors.' },
    { type: 'multiple_choice', question: 'What is the key difference between SIT and uncontrolled stress?', options: ['No difference', 'SIT only works for soldiers', 'SIT is harder', 'SIT is chosen and progressive with coping tools; uncontrolled stress overwhelms'], correctAnswer: 3, explanation: 'Controlled, chosen exposure with tools builds capacity; overwhelming stress causes harm.' },
    { type: 'multiple_choice', question: 'What is Phase 2 of SIT?', options: ['Education', 'Recovery', 'Application', 'Skill Acquisition — learning coping tools'], correctAnswer: 3, explanation: 'Phase 2 involves learning the tools (breathing, reappraisal, visualisation) before applying them.' },
    { type: 'multiple_choice', question: 'What does each successful stress exposure provide?', options: ['More stress', 'Physical strength', 'Evidence that you can handle hard things', 'Nothing'], correctAnswer: 2, explanation: 'Successful exposure builds experiential confidence that no theory can replicate.' },
    { type: 'multiple_choice', question: 'What is the enemy of growth in this context?', options: ['Other people', 'Challenge', 'Knowledge', 'Comfort'], correctAnswer: 3, explanation: 'Sustained comfort prevents the adaptive challenges needed for resilience growth.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Paying attention to the present moment without judgement', 'Clearing your mind', 'Thinking positive thoughts', 'Meditation only'], correctAnswer: 0, explanation: 'Mindfulness is present-moment awareness — not thought suppression or forced positivity.' },
    { type: 'multiple_choice', question: 'Where does most mental suffering come from?', options: ['Past rumination and future worry', 'Physical pain', 'The present', 'Other people'], correctAnswer: 0, explanation: 'Most suffering comes from dwelling on the past (regret) or worrying about the future (anxiety).' },
    { type: 'multiple_choice', question: 'What is the minimum effective daily mindfulness practice?', options: ['30 minutes', '3 minutes', '1 hour', '0 minutes — just think about it'], correctAnswer: 1, explanation: 'Even 3 minutes of consistent daily practice produces measurable benefits.' },
    { type: 'multiple_choice', question: 'When your mind wanders during meditation, what should you do?', options: ['Try harder to stop thoughts', 'Get frustrated', 'Give up', 'Notice it wandered and gently return to the breath'], correctAnswer: 3, explanation: 'Noticing and returning is the practice itself — each return strengthens the attention muscle.' },
    { type: 'multiple_choice', question: 'Can mindfulness be practised during daily activities?', options: ['No — only during formal meditation', 'Only in silence', 'Only during yoga', 'Yes — eating, walking, or commuting mindfully counts'], correctAnswer: 3, explanation: 'Informal mindfulness (eating, walking without distraction) is equally valuable practice.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the minimum effective dose for a daily protocol?', options: ['2 hours', 'Whatever you can do consistently', '90 minutes', '30 seconds'], correctAnswer: 1, explanation: 'The minimum effective dose is the shortest practice you can maintain every single day.' },
    { type: 'multiple_choice', question: 'How often should you adjust your resilience protocol?', options: ['Daily', 'Never', 'Every hour', 'Monthly'], correctAnswer: 3, explanation: 'Monthly reviews allow assessment of what works while keeping the protocol evolving.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of resilience training?', options: ['Following a strict protocol forever', 'Integration — practices feel as natural as brushing your teeth', 'Becoming invincible', 'Eliminating all emotions'], correctAnswer: 1, explanation: 'The goal is for practices to become automatic parts of your identity, not forced routines.' },
    { type: 'multiple_choice', question: 'When should you progress to harder challenges?', options: ['Never', 'When the current level feels manageable and consistent', 'After reading more theory', 'Immediately'], correctAnswer: 1, explanation: 'Only progress when the current level is consistent — rushing leads to burnout.' },
    { type: 'multiple_choice', question: 'What matters more than the specific practices chosen?', options: ['How impressive they sound', 'The equipment used', 'How long each takes', 'Consistency of doing them'], correctAnswer: 3, explanation: 'Consistent small practices beat sporadic impressive ones — always.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'How does one night of poor sleep (under 6 hours) affect testosterone?', options: ['No effect', 'Increases it by 10%', 'Reduces it by up to 15%', 'Doubles it'], correctAnswer: 2, explanation: 'A single night of poor sleep can reduce testosterone levels by up to 15%, impacting recovery, mood, and performance.' },
    { type: 'multiple_choice', question: 'Which sleep stage is most responsible for physical recovery and growth hormone release?', options: ['Stage 1 (N1)', 'Stage 2 (N2)', 'Deep sleep / Stage 3 (N3)', 'REM sleep'], correctAnswer: 2, explanation: 'Deep sleep (N3 / slow-wave sleep) is when growth hormone release peaks, muscle repair occurs, and immune function is restored.' },
    { type: 'multiple_choice', question: 'What is the optimal bedroom temperature for sleep?', options: ['20-24°C', '16-19°C', '25-28°C', 'As warm as possible'], correctAnswer: 1, explanation: 'The optimal sleep temperature is 16-19°C (60-67°F). Your body needs to drop its core temperature to initiate and maintain deep sleep.' },
    { type: 'scenario', question: 'Which habit is most likely causing the poor sleep?', scenario: 'A person drinks a coffee at 4pm, trains at 7pm, and then scrolls social media in bed from 10-11pm. They struggle to fall asleep before midnight.', options: ['Training at 7pm', 'All three habits are contributing — caffeine half-life means it is still active, and blue light from screens suppresses melatonin', 'They need a softer pillow', 'They are not tired enough'], correctAnswer: 1, explanation: 'Caffeine has a 5-6 hour half-life (still half-active at 10pm from a 4pm coffee), and blue light from screens suppresses melatonin production by up to 50%. Both significantly impair sleep onset.' },
    { type: 'multiple_choice', question: 'Why does morning sunlight exposure improve evening sleep quality?', options: ['It wakes you up with a shock', 'It sets your circadian clock, which determines when melatonin production begins in the evening', 'It has no effect on sleep', 'It increases cortisol permanently'], correctAnswer: 1, explanation: 'Bright morning light exposure sets the circadian clock via the suprachiasmatic nucleus, which determines the timing of melatonin release in the evening — improving sleep onset and quality.' },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Why does writing down thoughts improve mental clarity?', options: ['It does not — it is a waste of time', 'Writing forces you to translate vague feelings into structured language, allowing the brain to process and release them', 'It improves handwriting', 'It is a form of exercise'], correctAnswer: 1, explanation: 'When thoughts stay in your head, they loop. Writing forces translation into language, engaging the prefrontal cortex and allowing the brain to process and let go.' },
    { type: 'multiple_choice', question: 'Which type of journaling is best for processing difficult emotions?', options: ['Goal setting', 'Free writing / stream of consciousness', 'Training logs only', 'Gratitude journaling'], correctAnswer: 1, explanation: 'Free writing — writing whatever comes to mind without structure — is the most effective journaling method for processing emotions, as shown by James Pennebaker\'s research.' },
    { type: 'multiple_choice', question: 'What brain system does handwriting activate that increases attention?', options: ['The limbic system', 'The reticular activating system (RAS)', 'The hippocampus only', 'The cerebellum'], correctAnswer: 1, explanation: 'Handwriting activates the reticular activating system (RAS), which filters information and signals the brain to pay closer attention to what is being written.' },
    { type: 'multiple_choice', question: 'What is the most common reason people stop journaling?', options: ['They run out of paper', 'They make it too complicated or expect too much', 'They have nothing to write about', 'Journaling stops working after a week'], correctAnswer: 1, explanation: 'Overcomplicating the practice — expecting long entries, perfect writing, or deep insights every time — is the most common barrier. Three honest sentences is better than three unwritten pages.' },
    { type: 'scenario', question: 'Which journaling method would best help them?', scenario: 'Someone lies awake at night with racing thoughts about tomorrow\'s tasks and unresolved worries from the day.', options: ['Gratitude journaling', 'A brain dump — writing down all tasks, worries, and thoughts to get them out of their head', 'Goal setting for next year', 'Free writing about childhood'], correctAnswer: 1, explanation: 'A brain dump before bed clears working memory by transferring thoughts from mind to paper, preventing the brain from trying to hold and process them during sleep.' },
  ]),
];
