import type { UnitAssessment } from '../types';

export const mindsetL2Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Practical Application & Daily Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most important factor in a morning routine?', options: ['Duration', 'Complexity', 'Waking early', 'Consistency'], correctAnswer: 3, explanation: 'A consistent short routine is far more effective than an elaborate one that is not sustained.' },
    { type: 'multiple_choice', question: 'Why should you avoid checking your phone first thing in the morning?', options: ['It uses too much battery', 'It is a waste of time', 'It puts you in reactive mode, responding to others\' priorities', 'Phones are bad'], correctAnswer: 2, explanation: 'Checking your phone floods your brain with external demands, preventing proactive intention-setting.' },
    { type: 'multiple_choice', question: 'What is stress inoculation training?', options: ['Avoiding all stress', 'Controlled exposure to manageable stress to build resilience', 'Extreme suffering', 'Taking stress medication'], correctAnswer: 1, explanation: 'SIT builds resilience through progressive, controlled exposure — like a vaccine for your nervous system.' },
    { type: 'multiple_choice', question: 'What are the three phases of stress inoculation?', options: ['Education, Skill Acquisition, Application', 'Breathe, Think, Act', 'Start, Stop, Restart', 'Fight, Flight, Freeze'], correctAnswer: 0, explanation: 'SIT progresses through understanding stress, learning coping tools, then applying them under controlled challenge.' },
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Meditating for an hour daily', 'Clearing your mind completely', 'Ignoring your thoughts', 'Paying attention to the present moment without judgement'], correctAnswer: 3, explanation: 'Mindfulness is present-moment awareness without judgement — not thought suppression.' },
    { type: 'multiple_choice', question: 'What is the "mental bicep curl" in mindfulness?', options: ['Thinking harder', 'Concentrating without blinking', 'Noticing when your mind has wandered and returning to the present', 'Visualising lifting weights'], correctAnswer: 2, explanation: 'Each time you notice wandering and return attention to the present, you strengthen the attentional muscle.' },
    { type: 'multiple_choice', question: 'What is the minimum effective dose for a daily mindfulness practice?', options: ['1 hour', '3 minutes', '10 seconds', '30 minutes'], correctAnswer: 1, explanation: 'Even 3 minutes of daily practice produces measurable benefits when done consistently.' },
    { type: 'scenario', scenario: 'Someone designs a 90-minute morning routine including cold exposure, breathwork, journaling, meditation, and exercise. They abandon it after 5 days.', question: 'What was the primary mistake?', options: ['Starting too ambitiously — should have begun with 10–15 minutes', 'Not including enough activities', 'Waking too late', 'Not having the right equipment'], correctAnswer: 0, explanation: 'Overly ambitious protocols collapse quickly. Start small (10–15 min) and build as the habit solidifies.' },
    { type: 'multiple_choice', question: 'How often should you review and adjust your resilience protocol?', options: ['Daily', 'Weekly', 'Never', 'Monthly'], correctAnswer: 3, explanation: 'Monthly reviews allow enough time to assess what is working while keeping the protocol evolving.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of a resilience protocol?', options: ['To become invincible', 'To eliminate all stress', 'For the practices to become integrated into your identity and feel natural', 'To follow it perfectly forever'], correctAnswer: 2, explanation: 'The goal is integration — practices become as natural as brushing your teeth, not a forced protocol.' },
    { type: 'multiple_choice', question: 'Where does most mental suffering come from?', options: ['Physical pain', 'Ruminating about the past or worrying about the future', 'The present moment', 'Other people'], correctAnswer: 1, explanation: 'Most suffering comes from past rumination (regret) or future worry (anxiety), not the present moment.' },
    { type: 'multiple_choice', question: 'What is the key principle when progressing a resilience practice?', options: ['Only progress when the current level feels manageable and consistent', 'Progress as fast as possible', 'Change everything at once', 'Skip levels that feel easy'], correctAnswer: 0, explanation: 'Progress only when the current level is consistent — rushing leads to burnout and abandonment.' },
  ],
};
