import type { UnitAssessment } from '../types';

export const mindsetL2Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Focus, Discipline & Habit Formation',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['1 hour', '30 seconds', 'Average of 23 minutes', '2 minutes'], correctAnswer: 2, explanation: 'Research shows it takes an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'What is true multitasking?', options: ['Working on a laptop while watching TV', 'Performing two cognitive tasks simultaneously — which is neurologically impossible', 'Listening to music while studying', 'Switching quickly between tasks'], correctAnswer: 1, explanation: 'True cognitive multitasking is impossible — what people call multitasking is rapid task switching.' },
    { type: 'multiple_choice', question: 'Why is motivation unreliable for sustained behaviour?', options: ['It requires too much energy', 'It is an emotion that fluctuates like all emotions', 'It only works for beginners', 'It is always low'], correctAnswer: 1, explanation: 'Motivation fluctuates naturally — systems and discipline produce more consistent results.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['A habit based on who you want to become', 'A habit copied from someone else', 'A habit based on what you want to achieve', 'A habit based on rewards'], correctAnswer: 0, explanation: 'Identity-based habits focus on becoming the type of person who naturally does the desired behaviour.' },
    { type: 'multiple_choice', question: 'What are the three components of the habit loop?', options: ['Plan, Execute, Review', 'Trigger, Action, Outcome', 'Cue, Routine, Reward', 'Start, Continue, Stop'], correctAnswer: 2, explanation: 'The habit loop is: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Ignoring negative thoughts', 'Changing your interpretation of a situation to change how you feel about it', 'Suppressing difficult feelings', 'Arguing with your emotions'], correctAnswer: 1, explanation: 'Cognitive reappraisal changes interpretation, not facts, to produce a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does the "S" in the STOP method stand for?', options: ['Shift', 'Speak', 'Stop', 'Start'], correctAnswer: 2, explanation: 'S = Stop. Literally pause before speaking or acting.' },
    { type: 'multiple_choice', question: 'Why is process visualisation more effective than outcome visualisation?', options: ['It is easier', 'It prepares you for the actual steps and challenges involved', 'It is faster', 'Outcome visualisation does not work at all'], correctAnswer: 1, explanation: 'Process visualisation improves performance by mentally rehearsing the steps and responses needed.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['6 months', '4–8 weeks', '1 week', '1 year'], correctAnswer: 1, explanation: 'Most habits require approximately 4–8 weeks of consistent repetition to become automatic.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Always train twice a day', 'Always do double if you miss', 'Missing one day is acceptable but two consecutive days starts a new pattern of not doing it', 'Train even when injured'], correctAnswer: 2, explanation: 'One missed day does not break a habit — but two consecutive days establishes a pattern of absence.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Categorising people by personality', 'Putting sticky notes on emotions', 'Writing labels on a journal', 'Naming your emotions out loud to reduce their intensity'], correctAnswer: 3, explanation: 'Naming emotions activates the prefrontal cortex and measurably reduces emotional intensity.' },
    { type: 'multiple_choice', question: 'Which brain region handles automatic habits?', options: ['Basal ganglia', 'Amygdala', 'Prefrontal cortex', 'Hippocampus'], correctAnswer: 0, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex for other tasks.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "The 'habit loop' consists of:", options: ['Cue, routine, reward', 'Motivation, discipline, success', 'Thought, feeling, behaviour', 'Goal, plan, action'], correctAnswer: 0, explanation: "Charles Duhigg's habit loop identifies three stages: a cue (trigger), a routine (behaviour), and a reward (reinforcement)." },
    { type: 'multiple_choice', question: "What is the difference between discipline and motivation?", options: ['Discipline is consistent action regardless of feeling; motivation is emotion-dependent', 'Motivation is more reliable than discipline', 'Discipline only works for physical tasks', 'They are the same thing'], correctAnswer: 0, explanation: "Motivation fluctuates with mood and energy. Discipline is the ability to act consistently regardless of how you feel \u2014 it's the more reliable driver of long-term progress." },
    { type: 'multiple_choice', question: "Emotional regulation refers to:", options: ["Suppressing all emotions", "Never feeling angry or sad", "The ability to manage and respond to emotional experiences in healthy ways", "Ignoring your feelings completely"], correctAnswer: 2, explanation: "Emotional regulation is about managing \u2014 not eliminating \u2014 emotions. It involves recognising, understanding, and responding to emotions constructively." },
    { type: 'multiple_choice', question: "Visualisation improves performance because:", options: ['It only works for elite athletes', 'It activates similar neural pathways as physical execution', 'It replaces the need for real practice', 'It creates actual physical practice'], correctAnswer: 1, explanation: 'Neuroscience shows that mental rehearsal activates many of the same brain regions as physical practice, strengthening neural pathways and improving motor preparation.' },
    { type: 'multiple_choice', question: "Which of these is the most effective way to build a new habit?", options: ['Making huge changes all at once', 'Relying on willpower alone', 'Attaching the new behaviour to an existing routine (habit stacking)', 'Only doing it when you feel like it'], correctAnswer: 2, explanation: 'Habit stacking \u2014 linking a new behaviour to an established one \u2014 uses existing neural pathways as anchors, making the new habit easier to trigger consistently.' },
    { type: 'multiple_choice', question: "Deep focus is best sustained for periods of:", options: ["60\u201390 minutes before taking a break", "4\u20135 hours without any break", "10 minutes maximum", "Only during morning hours"], correctAnswer: 0, explanation: "Research on ultradian rhythms suggests deep focus works best in 60\u201390 minute blocks, followed by a break to allow the brain to consolidate and recover." },
    { type: 'multiple_choice', question: "Which neurotransmitter is most associated with focus and attention?", options: ['GABA', 'Dopamine', 'Serotonin', 'Melatonin'], correctAnswer: 1, explanation: "Dopamine plays a crucial role in attention, motivation, and reward-seeking behaviour \u2014 it's central to the brain's ability to sustain focus on tasks." },
    { type: 'multiple_choice', question: "The concept of 'keystone habits' refers to:", options: ['Physical exercise only', 'The most difficult habits to build', 'Habits that trigger a cascade of other positive behaviour changes', 'Habits that only work in the morning'], correctAnswer: 2, explanation: 'Keystone habits \u2014 like regular exercise or daily planning \u2014 create ripple effects that positively influence other areas of life.' },

  ],
};
