import type { UnitAssessment } from '../types';

export const mindsetL2Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Breathing Science & Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What primarily drives the urge to breathe?', options: ['Low oxygen levels', 'Heart rate', 'Blood pressure', 'Rising carbon dioxide levels'], correctAnswer: 3, explanation: 'CO2 levels, not oxygen, primarily trigger the urge to breathe via brainstem chemoreceptors.' },
    { type: 'multiple_choice', question: 'What is the BOLT score?', options: ['A breathing speed test', 'A lung capacity measure', 'Body Oxygen Level Test — comfortable pause after exhale', 'A fitness test'], correctAnswer: 2, explanation: 'BOLT measures CO2 tolerance by timing a comfortable breath hold after normal exhalation.' },
    { type: 'multiple_choice', question: 'What is the box breathing protocol?', options: ['Breathe as fast as possible', '4 seconds inhale, 4 hold, 4 exhale, 4 hold', 'Continuous deep breathing', 'Hold your breath for 4 minutes'], correctAnswer: 1, explanation: 'Box breathing uses equal 4-second phases: inhale, hold, exhale, hold.' },
    { type: 'multiple_choice', question: 'What makes the 4-7-8 technique effective for calming?', options: ['The extended exhale activates vagal tone', 'The breath hold increases oxygen', 'The long inhale', 'It requires no practice'], correctAnswer: 0, explanation: 'The extended exhale phase maximises parasympathetic activation through vagal stimulation.' },
    { type: 'multiple_choice', question: 'How does the Wim Hof method increase energy?', options: ['Through extended exhales', 'By increasing CO2', 'By slowing heart rate', 'Through rapid breathing that triggers controlled adrenaline release'], correctAnswer: 3, explanation: 'Rapid breathing lowers CO2, alters blood pH, and triggers a controlled adrenaline response.' },
    { type: 'multiple_choice', question: 'Where should you NEVER practise hyperventilation-based breathwork?', options: ['In bed', 'In a quiet room', 'In or near water', 'Sitting on a chair'], correctAnswer: 2, explanation: 'Loss of consciousness in water can be fatal — never practise near water.' },
    { type: 'multiple_choice', question: 'What does chronic mouth breathing promote?', options: ['Better sleep', 'Sympathetic nervous system activation and stress', 'Higher CO2 tolerance', 'Parasympathetic balance'], correctAnswer: 1, explanation: 'Mouth breathing bypasses nasal benefits and promotes sympathetic activation.' },
    { type: 'multiple_choice', question: 'Cold water immersion increases noradrenaline by approximately how much?', options: ['200–300%', '1000%', '50–100%', '10–20%'], correctAnswer: 0, explanation: 'Cold water immersion can increase noradrenaline by 200–300%, improving alertness and mood.' },
    { type: 'multiple_choice', question: 'What is the recommended starting protocol for cold exposure?', options: ['Swimming in a cold lake', '10 minutes in an ice bath', '5 minutes of cold water immersion', '30 seconds of cold water at the end of your shower'], correctAnswer: 3, explanation: 'Start with 30 seconds of cold at the end of a normal shower and gradually increase.' },
    { type: 'multiple_choice', question: 'What psychological benefit does cold exposure provide?', options: ['It replaces exercise', 'It makes you immune to cold', 'It proves you can choose discomfort and handle it', 'It eliminates stress'], correctAnswer: 2, explanation: 'Choosing voluntary discomfort builds the psychological muscle of doing hard things — transferable to all areas.' },
    { type: 'multiple_choice', question: 'What type of journaling is most effective for processing difficult experiences?', options: ['Copying motivational quotes', 'Free writing about thoughts and feelings', 'Writing to-do lists', 'Gratitude only'], correctAnswer: 1, explanation: 'Expressive free writing forces cognitive processing of experiences, reducing their emotional charge.' },
    { type: 'multiple_choice', question: 'How many breaths per minute may indicate over-breathing?', options: ['Above 12', '8–10', '6–8', 'Above 20'], correctAnswer: 0, explanation: 'A resting breathing rate above 12 breaths per minute may indicate chronic over-breathing.' },
  ],
};
