import type { UnitAssessment } from '../types';

export const mindsetL2Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Breathing Science & Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What primarily drives the urge to breathe?', options: ['Low oxygen levels', 'Blood pressure', 'Heart rate', 'Rising carbon dioxide levels'], correctAnswer: 3, explanation: 'CO2 levels, not oxygen, primarily trigger the urge to breathe via brainstem chemoreceptors.' },
    { type: 'multiple_choice', question: 'What is the BOLT score?', options: ['A breathing speed test', 'Body Oxygen Level Test — comfortable pause after exhale', 'A lung capacity measure', 'A fitness test'], correctAnswer: 1, explanation: 'BOLT measures CO2 tolerance by timing a comfortable breath hold after normal exhalation.' },
    { type: 'multiple_choice', question: 'What is the box breathing protocol?', options: ['Continuous deep breathing', 'Breathe as fast as possible', 'Hold your breath for 4 minutes', '4 seconds inhale, 4 hold, 4 exhale, 4 hold'], correctAnswer: 3, explanation: 'Box breathing uses equal 4-second phases: inhale, hold, exhale, hold.' },
    { type: 'multiple_choice', question: 'What makes the 4-7-8 technique effective for calming?', options: ['The long inhale', 'It requires no practice', 'The extended exhale activates vagal tone', 'The breath hold increases oxygen'], correctAnswer: 2, explanation: 'The extended exhale phase maximises parasympathetic activation through vagal stimulation.' },
    { type: 'multiple_choice', question: 'How does the Unbreakable Breathwork Method increase energy?', options: ['Through extended exhales', 'By increasing CO2', 'By slowing heart rate', 'Through rapid breathing that triggers controlled adrenaline release'], correctAnswer: 3, explanation: 'Rapid breathing lowers CO2, alters blood pH, and triggers a controlled adrenaline response.' },
    { type: 'multiple_choice', question: 'Where should you NEVER practise hyperventilation-based breathwork?', options: ['Sitting on a chair', 'In bed', 'In or near water', 'In a quiet room'], correctAnswer: 2, explanation: 'Loss of consciousness in water can be fatal — never practise near water.' },
    { type: 'multiple_choice', question: 'What does chronic mouth breathing promote?', options: ['Sympathetic nervous system activation and stress', 'Better sleep', 'Parasympathetic balance', 'Higher CO2 tolerance'], correctAnswer: 0, explanation: 'Mouth breathing bypasses nasal benefits and promotes sympathetic activation.' },
    { type: 'multiple_choice', question: 'Cold water immersion increases noradrenaline by approximately how much?', options: ['1000%', '50–100%', '200–300%', '10–20%'], correctAnswer: 2, explanation: 'Cold water immersion can increase noradrenaline by 200–300%, improving alertness and mood.' },
    { type: 'multiple_choice', question: 'What is the recommended starting protocol for cold exposure?', options: ['5 minutes of cold water immersion', '10 minutes in an ice bath', '30 seconds of cold water at the end of your shower', 'Swimming in a cold lake'], correctAnswer: 2, explanation: 'Start with 30 seconds of cold at the end of a normal shower and gradually increase.' },
    { type: 'multiple_choice', question: 'What psychological benefit does cold exposure provide?', options: ['It replaces exercise', 'It makes you immune to cold', 'It proves you can choose discomfort and handle it', 'It eliminates stress'], correctAnswer: 2, explanation: 'Choosing voluntary discomfort builds the psychological muscle of doing hard things — transferable to all areas.' },
    { type: 'multiple_choice', question: 'What type of journaling is most effective for processing difficult experiences?', options: ['Writing to-do lists', 'Gratitude only', 'Copying motivational quotes', 'Free writing about thoughts and feelings'], correctAnswer: 3, explanation: 'Expressive free writing forces cognitive processing of experiences, reducing their emotional charge.' },
    { type: 'multiple_choice', question: 'How many breaths per minute may indicate over-breathing?', options: ['Above 20', '6–8', '8–10', 'Above 12'], correctAnswer: 3, explanation: 'A resting breathing rate above 12 breaths per minute may indicate chronic over-breathing.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "The diaphragm is:", options: ['Part of the nervous system', 'The primary muscle of respiration, separating the chest and abdominal cavities', 'A bone in the ribcage', 'A type of breathing technique'], correctAnswer: 1, explanation: 'The diaphragm is a dome-shaped muscle that sits beneath the lungs and is the primary muscle responsible for breathing.' },
    { type: 'multiple_choice', question: "Box breathing follows which pattern?", options: ["Inhale 4s, exhale 4s", "Inhale 4s, hold 4s, exhale 4s, hold 4s", "Inhale 7s, hold 4s, exhale 8s", "Rapid breathing for 30 seconds"], correctAnswer: 1, explanation: "Box breathing uses equal phases of 4 seconds: inhale, hold, exhale, hold \u2014 creating a 'box' pattern that activates the parasympathetic system." },
    { type: 'multiple_choice', question: "Nasal breathing is generally preferred over mouth breathing because:", options: ['It allows faster breathing rates', 'It bypasses the diaphragm', 'It only works during sleep', 'It filters, warms, and humidifies air and promotes nitric oxide production'], correctAnswer: 3, explanation: 'Nasal breathing filters particles, warms and humidifies air, and produces nitric oxide which aids oxygen absorption and blood vessel dilation.' },
    { type: 'multiple_choice', question: "Cold exposure primarily stimulates:", options: ['The parasympathetic nervous system only', 'Fat storage', 'Muscle growth directly', 'A norepinephrine release and sympathetic activation'], correctAnswer: 3, explanation: 'Cold exposure triggers norepinephrine release, activating the sympathetic nervous system, increasing alertness, mood, and metabolic rate.' },
    { type: 'multiple_choice', question: "Journaling benefits mental health by:", options: ["Replacing professional therapy entirely", "Helping externalise thoughts, process emotions, and track patterns", "Avoiding difficult emotions", "Only recording positive events"], correctAnswer: 1, explanation: "Journaling helps externalise and process thoughts and emotions, identify patterns, build self-awareness, and reduce cognitive load." },
    { type: 'multiple_choice', question: "What is the primary physiological effect of slow, deep exhalation?", options: ["Increased heart rate", "Sympathetic nervous system activation", "Parasympathetic activation and vagal tone increase", "Increased cortisol production"], correctAnswer: 2, explanation: "Extended exhalation stimulates the vagus nerve, activating the parasympathetic system, lowering heart rate and promoting calm." },
    { type: 'multiple_choice', question: "Energising breathwork techniques typically involve:", options: ['Faster breathing rates with emphasis on inhalation', 'Breathing only through the mouth while lying down', 'Holding the breath for as long as possible', 'Slow, deep breathing with long exhales'], correctAnswer: 0, explanation: 'Energising breathwork (like Unbreakable Breathwork or kapalbhati) uses faster breathing rates with strong inhalations to increase sympathetic activation and alertness.' },
    { type: 'multiple_choice', question: "A safe starting protocol for cold exposure is:", options: ['Jumping into ice-cold water for 10 minutes', "Staying in cold water until you can't feel your limbs", 'Ending a warm shower with 30\u201360 seconds of cold water', 'Only practising in winter outdoors'], correctAnswer: 2, explanation: 'Starting with cold shower endings (30\u201360 seconds) builds tolerance safely. Gradual progression is key \u2014 extreme exposure without adaptation is dangerous.' },

  ],
};
