import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['1 minute', '5 seconds', '23 minutes', '2 minutes'], correctAnswer: 2, explanation: 'Research shows an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'Is true multitasking possible for cognitive tasks?', options: ['Yes', 'Only for experts', 'Only for women', 'No — it is rapid task switching'], correctAnswer: 3, explanation: 'The brain cannot perform two cognitively demanding tasks simultaneously.' },
    { type: 'multiple_choice', question: 'What is the Pomodoro technique?', options: ['A cooking method', 'A type of exercise', '25–50 minute focused work blocks with 5–10 minute breaks', 'A sleep protocol'], correctAnswer: 2, explanation: 'The Pomodoro technique structures work into focused blocks with strategic breaks.' },
    { type: 'multiple_choice', question: 'What is the two-minute rule?', options: ['Rest for 2 minutes', 'If a task takes less than 2 minutes, do it now; otherwise schedule it', 'Meditate for 2 minutes', 'Warm up for 2 minutes'], correctAnswer: 1, explanation: 'Quick tasks done immediately prevent them from fragmenting future attention.' },
    { type: 'multiple_choice', question: "What depletes the prefrontal cortex\'s capacity?", options: ['Exercise', 'Every decision, task switch, and distraction', 'Water intake', 'Sleep'], correctAnswer: 1, explanation: 'The prefrontal cortex operates like a battery depleted by decisions and cognitive demands.' },
    { type: 'multiple_choice', question: 'What is the prefrontal cortex responsible for?', options: ['Digestion', 'Executive function — planning, decision-making, and sustained attention', 'Heart rate', 'Balance'], correctAnswer: 1, explanation: 'The prefrontal cortex handles executive functions including focus, planning, and impulse control.' },
    { type: 'multiple_choice', question: 'What depletes focus throughout the day?', options: ['Sleep', 'Every decision and attention switch drains a finite daily resource', 'Exercise', 'Drinking water'], correctAnswer: 1, explanation: 'Focus is a depletable resource — every decision, notification, and context switch costs cognitive energy.' },
    { type: 'multiple_choice', question: 'How long does it take to fully refocus after a distraction?', options: ['2 seconds', 'Up to 23 minutes', '1 minute', '5 seconds'], correctAnswer: 1, explanation: 'Research shows it takes an average of 23 minutes to fully regain focus after an interruption.' },
    { type: 'multiple_choice', question: 'What is task switching?', options: ['Finishing one task before starting another', 'Rapidly alternating between tasks — which feels productive but reduces quality', 'Working on a single project', 'A time management technique'], correctAnswer: 1, explanation: 'Task switching gives an illusion of productivity but each switch incurs a cognitive cost that reduces overall quality.' },
    { type: 'multiple_choice', question: 'When is your focus typically strongest?', options: ['Late at night', 'In the first 2–4 hours after waking', 'After lunch', 'It is the same all day'], correctAnswer: 1, explanation: 'For most people, the cortisol awakening response makes the first 2–4 hours after waking the peak focus window.' },
  
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'Why is motivation unreliable?', options: ['It is always low', 'It only works for some people', 'It does not exist', 'It is an emotion that naturally fluctuates'], correctAnswer: 3, explanation: 'Like all emotions, motivation rises and falls — systems and discipline are more consistent.' },
    { type: 'multiple_choice', question: 'What is environment design?', options: ['Interior decorating', 'Building a new house', 'Arranging your environment so desired actions are the easiest option', 'Organising your desk'], correctAnswer: 2, explanation: 'Environment design reduces willpower required by making good choices the default.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['Setting outcome goals', 'Acting consistently with who you want to become', 'Copying someone else', 'Tracking habits on an app'], correctAnswer: 1, explanation: 'Identity-based habits flow from self-concept: "I am someone who..." rather than "I want to..."' },
    { type: 'multiple_choice', question: 'What does "every action is a vote" mean?', options: ['You should vote more', 'Only big actions count', 'Actions do not matter', 'Each action reinforces the type of person you are becoming'], correctAnswer: 3, explanation: 'Small consistent actions accumulate into identity — each one is a vote for who you are becoming.' },
    { type: 'multiple_choice', question: 'What is the most effective way to train consistently?', options: ['Wait for motivation', 'Create systems that work regardless of how you feel', 'Only train when you feel great', 'Train twice as hard on good days'], correctAnswer: 1, explanation: 'Systems that operate independently of motivation produce the most consistent results.' },
    { type: 'multiple_choice', question: 'Why is motivation unreliable?', options: ['It is always reliable', 'It fluctuates based on mood, sleep, stress, and circumstances', 'It only works for beginners', 'It is not real'], correctAnswer: 1, explanation: 'Motivation is an emotion that fluctuates with internal and external conditions — it cannot be your primary driver.' },
    { type: 'multiple_choice', question: 'What is discipline most accurately?', options: ['Punishment for bad behaviour', 'The ability to do what needs doing regardless of how you feel', 'Being strict with others', 'Never having fun'], correctAnswer: 1, explanation: 'Discipline is showing up and doing the work regardless of emotional state — it is a skill, not a personality trait.' },
    { type: 'multiple_choice', question: 'What makes discipline easier to maintain?', options: ['Willpower alone', 'Systems and environment design that make the desired behaviour the default', 'Watching motivational videos', 'Punishing yourself for failure'], correctAnswer: 1, explanation: 'Smart environment design reduces the need for willpower — making good choices the path of least resistance.' },
    { type: 'multiple_choice', question: 'What is the relationship between identity and discipline?', options: ['They are unrelated', 'When you identify as "someone who trains" rather than "someone trying to train," discipline becomes automatic', 'Identity prevents discipline', 'Only extroverts have discipline'], correctAnswer: 1, explanation: 'Identity-based habits are more sustainable — "I am a person who..." is more powerful than "I am trying to..."' },
    { type: 'multiple_choice', question: 'What should you do on days when motivation is zero?', options: ['Skip the session entirely', 'Do the minimum viable version — a 10-minute walk instead of a full session', 'Wait for motivation to return', 'Double tomorrow\'s session'], correctAnswer: 1, explanation: 'The minimum viable version protects the habit streak — showing up matters more than the intensity of any single session.' },
  
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What are the three parts of the habit loop?', options: ['Plan, Act, Review', 'Cue, Routine, Reward', 'Try, Fail, Retry', 'Start, Middle, End'], correctAnswer: 1, explanation: 'Every habit follows: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'Which brain region takes over once a habit is automatic?', options: ['Basal ganglia', 'Prefrontal cortex', 'Amygdala', 'Cerebellum'], correctAnswer: 0, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex.' },
    { type: 'multiple_choice', question: 'What is the best way to break an unwanted habit?', options: ['Punish yourself', 'Use willpower', 'Ignore it', 'Keep the cue and reward but replace the routine'], correctAnswer: 3, explanation: 'Replacing the routine while keeping the same cue and reward is the most effective strategy.' },
    { type: 'multiple_choice', question: 'What does "start absurdly small" mean?', options: ['Set tiny goals like one press-up to reduce resistance', 'Never progress', 'Only do easy things', 'Think small forever'], correctAnswer: 0, explanation: 'Absurdly small starts (one press-up, 2 minutes of journaling) build the neural pathway with minimal resistance.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Missing one day is fine but two consecutive days starts a pattern of absence', 'Always do double after missing', 'Train twice daily', 'Never miss any day'], correctAnswer: 0, explanation: 'One miss does not break a habit — but two consecutive misses establish a new pattern.' },
    { type: 'multiple_choice', question: 'What are the four stages of habit formation?', options: ['Plan, Do, Check, Act', 'Think, Feel, Act, Reflect', 'Cue, Craving, Response, Reward', 'Start, Continue, Maintain, Master'], correctAnswer: 2, explanation: 'James Clear\'s habit loop: Cue (trigger) → Craving (motivation) → Response (action) → Reward (satisfaction).' },
    { type: 'multiple_choice', question: 'How long does it actually take to form a habit?', options: ['21 days', 'Exactly 30 days', '18 to 254 days depending on the behaviour — average around 66 days', '7 days'], correctAnswer: 2, explanation: 'Research by Phillippa Lally found habit formation takes 18–254 days, averaging 66 — not the mythical 21 days.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Doing many habits simultaneously', 'Linking a new habit to an existing one — "After I [existing habit], I will [new habit]"', 'Stacking books about habits', 'Replacing all habits at once'], correctAnswer: 1, explanation: 'Habit stacking uses existing routines as triggers for new behaviours, leveraging established neural pathways.' },
    { type: 'multiple_choice', question: 'What does making a habit "obvious" mean?', options: ['Telling everyone about it', 'Designing environmental cues so the trigger is clearly visible (e.g., setting out gym clothes)', 'Making it the most difficult option', 'Writing it in large letters'], correctAnswer: 1, explanation: 'Making cues obvious — like placing gym clothes by your bed — removes the friction of remembering and deciding.' },
    { type: 'multiple_choice', question: 'Why do most habit-building attempts fail?', options: ['People lack willpower', 'They try to change too many things at once instead of focusing on one habit at a time', 'Habits cannot actually be built', 'They do not read enough about habits'], correctAnswer: 1, explanation: 'Attempting multiple habit changes simultaneously splits focus and depletes willpower — build one at a time.' },
  
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'Is emotional regulation the same as suppression?', options: ['Depends on the situation', 'No — regulation is conscious processing, not hiding emotions', 'Yes', 'Only for negative emotions'], correctAnswer: 1, explanation: 'Regulation means processing emotions consciously; suppression increases stress and impairs health.' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Changing your interpretation to change your emotional response', 'Denying reality', 'Ignoring the situation', 'Arguing with yourself'], correctAnswer: 0, explanation: 'Reappraisal changes interpretation, not facts, producing a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does STOP stand for?', options: ['Stop, Think, Observe, Proceed', 'Stop, Take a breath, Observe, Proceed', 'Slow, Think, Operate, Plan', 'Start, Try, Overcome, Persist'], correctAnswer: 1, explanation: 'Stop, Take a breath, Observe your feelings, Proceed with conscious choice.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Writing feelings on a label', 'Rating emotions 1-10', 'Naming your emotions to reduce their intensity', 'Describing emotions to others'], correctAnswer: 2, explanation: 'Naming emotions ("I notice I am feeling angry") activates the prefrontal cortex and reduces intensity.' },
    { type: 'multiple_choice', question: 'What creates the "space" between stimulus and response?', options: ['Distance', 'Time', 'Conscious awareness and deliberate pausing', 'Other people'], correctAnswer: 2, explanation: 'Conscious awareness — pausing before reacting — creates the space for intentional response.' },
    { type: 'multiple_choice', question: 'What is friction in the context of environment design?', options: ['Physical discomfort', 'The number of steps between you and a behaviour — more steps = less likely', 'Arguing with others', 'Wear and tear on equipment'], correctAnswer: 1, explanation: 'Friction is the effort required — adding steps to bad habits and removing steps from good ones shapes behaviour.' },
    { type: 'multiple_choice', question: 'What is an example of positive environment design?', options: ['Hiding your phone in another room during focused work', 'Buying more snacks', 'Adding more apps to your phone', 'Making your bed harder to find'], correctAnswer: 0, explanation: 'Putting your phone in another room removes the friction-free option of checking it, protecting your focus.' },
    { type: 'multiple_choice', question: 'Why is willpower a poor long-term strategy?', options: ['It is always effective', 'It is a finite resource that depletes throughout the day', 'It gets stronger with use', 'It is unlimited'], correctAnswer: 1, explanation: 'Willpower depletes with use (ego depletion) — environment design reduces the need for willpower by making defaults work for you.' },
    { type: 'multiple_choice', question: 'How does environment design relate to nutrition?', options: ['It has no application', 'If healthy food is visible and accessible and junk food is not, you eat better without relying on willpower', 'You should hide all food', 'Only willpower matters'], correctAnswer: 1, explanation: 'Food environment design — placing healthy options at eye level, removing junk from the house — shapes choices without effort.' },
    { type: 'multiple_choice', question: 'What is the "20-second rule"?', options: ['Meditate for 20 seconds', 'Make desired habits 20 seconds easier to start and undesired habits 20 seconds harder', 'Wait 20 seconds before eating', 'Exercise for 20 seconds daily'], correctAnswer: 1, explanation: 'Reducing startup friction by even 20 seconds dramatically increases the likelihood of performing a behaviour.' },
  
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'Why does visualisation work?', options: ['It activates the same neural pathways as physical performance', 'It replaces practice', 'It is magic', 'It only works for athletes'], correctAnswer: 0, explanation: 'Mental rehearsal activates motor cortex regions similar to actual movement.' },
    { type: 'multiple_choice', question: 'Which type of visualisation improves performance more?', options: ['Process visualisation', 'Outcome visualisation', 'Neither works', 'Both equally'], correctAnswer: 0, explanation: 'Process visualisation (imagining steps and challenges) is more effective than imagining the end result.' },
    { type: 'multiple_choice', question: 'Should you include challenges in your visualisation?', options: ['No — only positive outcomes', 'Only if you expect problems', 'Challenges are too negative', 'Yes — visualise encountering and overcoming difficulty'], correctAnswer: 3, explanation: 'Including challenges in visualisation prepares you to respond effectively during actual performance.' },
    { type: 'multiple_choice', question: 'How long should a visualisation session last?', options: ['1 hour', '1 minute', '5–10 minutes', '30 minutes'], correctAnswer: 2, explanation: '5–10 minutes per session, practised 3–5 times before an event, is the evidence-based approach.' },
    { type: 'multiple_choice', question: 'Can outcome visualisation actually reduce effort?', options: ['Yes — it can create a premature sense of achievement', 'It always increases effort', 'No', 'Only for lazy people'], correctAnswer: 0, explanation: 'Research shows imagining the end result can reduce effort by creating premature satisfaction.' },
    { type: 'multiple_choice', question: 'What is emotional regulation?', options: ['Suppressing all emotions', 'The ability to manage your emotional responses without being controlled by them', 'Never feeling negative emotions', 'Ignoring how you feel'], correctAnswer: 1, explanation: 'Emotional regulation means processing emotions effectively — not suppressing them, but not being overwhelmed either.' },
    { type: 'multiple_choice', question: 'What is the amygdala hijack?', options: ['A type of meditation', 'When the emotional brain overrides the rational brain, causing reactive behaviour before you can think', 'A breathing technique', 'A sleep disorder'], correctAnswer: 1, explanation: 'The amygdala can trigger a fight-or-flight response before the prefrontal cortex can evaluate the situation — leading to impulsive reactions.' },
    { type: 'multiple_choice', question: 'What is the "name it to tame it" technique?', options: ['Naming your emotions reduces their intensity by activating the prefrontal cortex', 'Giving names to your fears', 'Naming exercises in your workout', 'Labelling food containers'], correctAnswer: 0, explanation: 'Labelling an emotion ("I am feeling anxious") activates the prefrontal cortex, which dampens the amygdala response.' },
    { type: 'multiple_choice', question: 'Why is the gap between stimulus and response important?', options: ['There is no gap', 'It is where you choose your response rather than reacting automatically', 'It is too short to use', 'It only matters in emergencies'], correctAnswer: 1, explanation: 'Viktor Frankl: "Between stimulus and response there is a space. In that space is our freedom and power to choose."' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Avoiding negative thoughts', 'Reinterpreting a situation to change its emotional impact', 'Pretending nothing happened', 'Blaming others'], correctAnswer: 1, explanation: 'Cognitive reappraisal changes the meaning of a situation — "this is a catastrophe" becomes "this is a challenge I can learn from."' },
  
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'How many times per day does the average person check their phone?', options: ['About 20 times', 'About 96 times', 'About 10 times', 'About 200 times'], correctAnswer: 1, explanation: 'Research shows the average person checks their phone approximately 96 times per day — roughly once every 10 minutes of waking time.' },
    { type: 'multiple_choice', question: 'Why is social media addictive from a neurochemical perspective?', options: ['It releases serotonin', 'It provides intermittent dopamine reinforcement — the same pattern as slot machines', 'It increases testosterone', 'It lowers cortisol'], correctAnswer: 1, explanation: 'Social media provides unpredictable rewards (likes, comments, interesting content) that trigger dopamine release through intermittent reinforcement — the most addictive reward pattern known.' },
    { type: 'multiple_choice', question: 'What is the "phone-free first hour" strategy?', options: ['Turning off your phone for 1 hour during the day', 'Not checking your phone for the first 60 minutes after waking', 'Limiting total phone use to 1 hour', 'Only using your phone for calls in the first hour'], correctAnswer: 1, explanation: 'Avoiding phone use for the first 60 minutes after waking protects your morning from being reactive and allows you to start the day with intention.' },
    { type: 'scenario', question: 'What is the most likely explanation for these symptoms?', scenario: 'A person reports difficulty concentrating on reading, constant urge to check notifications, and finding slow activities boring — despite previously enjoying them.', options: ['They have developed a reading disorder', 'Their dopamine baseline has been elevated by constant digital stimulation, making slower activities feel unrewarding', 'They need more caffeine', 'They are simply ageing'], correctAnswer: 1, explanation: 'Constant low-level dopamine stimulation from screens raises the baseline expectation for novelty, making naturally rewarding but slower activities feel boring by comparison.' },
    { type: 'multiple_choice', question: 'How does phone use between sets affect training quality?', options: ['It has no effect', 'It improves rest periods', 'It worsens mind-muscle connection, extends rest periods, and lowers session quality', 'It only affects beginners'], correctAnswer: 2, explanation: 'Scrolling between sets fragments attention, weakens the mind-muscle connection, and typically leads to longer, unstructured rest periods — all reducing overall session quality.' },
    { type: 'multiple_choice', question: 'What is the average number of times people check their phones daily?', options: ['10', '50', '96+', '200+'], correctAnswer: 2, explanation: 'Research shows the average person checks their phone 96+ times per day — roughly every 10 minutes during waking hours.' },
    { type: 'multiple_choice', question: 'Why is infinite scroll so addictive?', options: ['It provides useful information', 'It exploits intermittent reinforcement — unpredictable rewards keep you scrolling', 'It improves focus', 'It is not addictive'], correctAnswer: 1, explanation: 'Infinite scroll delivers unpredictable rewards (interesting content mixed with boring content) — the same pattern that makes slot machines addictive.' },
    { type: 'multiple_choice', question: 'What is a digital detox?', options: ['Cleaning your devices', 'A planned period of reduced or eliminated device use to reset dopamine baseline', 'Updating software', 'Buying new devices'], correctAnswer: 1, explanation: 'A digital detox is a deliberate period of reduced screen use — even 24–48 hours can noticeably improve attention and reduce anxiety.' },
    { type: 'multiple_choice', question: 'How does comparison on social media affect mental health?', options: ['It has no effect', 'Comparing your behind-the-scenes to others\' highlight reels increases anxiety and reduces self-worth', 'It is motivating for everyone', 'It only affects teenagers'], correctAnswer: 1, explanation: 'Social media presents curated highlights, creating unrealistic comparisons that undermine satisfaction and self-esteem.' },
    { type: 'multiple_choice', question: 'What is notification batching?', options: ['Turning on all notifications', 'Checking notifications at set times rather than responding to each one immediately', 'Sending many messages at once', 'Ignoring all messages permanently'], correctAnswer: 1, explanation: 'Batching notifications to set times (e.g., 9am, 1pm, 5pm) prevents constant attention fragmentation.' },
  
  ]),
  cq(3, 7, [
    { type: 'multiple_choice', question: 'Procrastination is most accurately an issue of what?', options: ['Time management', 'Laziness', 'Emotional regulation', 'Intelligence'], correctAnswer: 2, explanation: 'Research shows procrastination is an emotional regulation problem — the brain seeks relief from negative emotions by switching to pleasant tasks.' },
    { type: 'multiple_choice', question: 'What is the two-minute rule for overcoming procrastination?', options: ['Only work on tasks that take two minutes', 'Commit to starting for just two minutes to build momentum', 'Take a two-minute break every hour', 'Procrastinate for only two minutes'], correctAnswer: 1, explanation: 'Starting is the hardest part — committing to just two minutes often generates momentum that carries you forward.' },
    { type: 'multiple_choice', question: 'Why do vague tasks increase procrastination?', options: ['They are too easy', 'The brain resists starting because it does not know what to do', 'They take too long', 'They are more enjoyable'], correctAnswer: 1, explanation: 'Task ambiguity creates resistance because the brain cannot determine the first step, making the task feel overwhelming.' },
    { type: 'multiple_choice', question: 'What should you do when you catch yourself procrastinating?', options: ['Criticise yourself harshly to prevent it next time', 'Acknowledge it, understand the trigger, and restart without drama', 'Give up for the day', 'Switch to a completely different goal'], correctAnswer: 1, explanation: 'Self-criticism after procrastination makes it worse. Acknowledge, understand the emotional trigger, and restart.' },
    { type: 'multiple_choice', question: 'What generates motivation according to the chapter?', options: ['Watching motivational videos', 'Waiting until you feel ready', 'Taking action — action generates motivation, not the other way around', 'Having a clear goal'], correctAnswer: 2, explanation: 'You do not need to feel motivated to start — starting creates the motivation. Action precedes feeling.' },
    { type: 'multiple_choice', question: 'What is time-boxing?', options: ['Scheduling your entire day in 5-minute increments', 'Committing to a fixed time window rather than a fixed output', 'Only working during boxing training', 'Setting unrealistic deadlines'], correctAnswer: 1, explanation: 'Time-boxing means committing to a set period (e.g., 25 minutes) rather than a specific result, keeping the task manageable.' },
    { type: 'multiple_choice', question: 'What is task decomposition and how does it help procrastination?', options: ['Making tasks bigger', 'Breaking a large overwhelming task into small, specific steps that feel manageable', 'Combining tasks together', 'Avoiding tasks by breaking them up'], correctAnswer: 1, explanation: 'The brain resists vague, large tasks — breaking them into specific, small steps removes the overwhelm that drives procrastination.' },
    { type: 'multiple_choice', question: 'Why does perfectionism fuel procrastination?', options: ['It does not', 'Fear of producing imperfect work leads to avoiding the work entirely', 'Perfectionism always leads to action', 'Only in creative fields'], correctAnswer: 1, explanation: 'Perfectionism creates paralysis — if you cannot do it perfectly, you do not start. "Done is better than perfect" breaks this cycle.' },
    { type: 'multiple_choice', question: 'What is the Pomodoro Technique?', options: ['A cooking method', '25 minutes of focused work followed by a 5-minute break — making tasks time-bound', 'A relaxation exercise', 'A type of meditation'], correctAnswer: 1, explanation: 'The Pomodoro Technique uses 25-minute focused blocks with 5-minute breaks, making work feel manageable and time-limited.' },
    { type: 'multiple_choice', question: 'What makes the biggest difference in overcoming procrastination?', options: ['Reading about procrastination', 'Simply starting — even for 2 minutes — because momentum builds naturally', 'Waiting for the right mood', 'Planning extensively before starting'], correctAnswer: 1, explanation: 'The hardest part is starting. Once you begin, the brain often shifts into flow and the urge to procrastinate fades.' },
  
  ]),
  cq(3, 8, [
    { type: 'multiple_choice', question: 'What does having an accountability appointment increase goal completion probability to?', options: ['50%', '75%', '95%', '65%'], correctAnswer: 2, explanation: 'The American Society of Training and Development found accountability appointments increase goal completion from 65% to 95%.' },
    { type: 'multiple_choice', question: 'What type of accountability is most underrated?', options: ['Public accountability', 'Coach accountability', 'Environmental accountability — designing defaults', 'Self-accountability'], correctAnswer: 2, explanation: 'Environmental accountability works without requiring willpower — it makes the desired action the default.' },
    { type: 'multiple_choice', question: 'What should you track instead of just outcomes?', options: ['Only weight loss', 'Lead indicators — actions within your control', 'Social media followers', 'Nothing — tracking is unnecessary'], correctAnswer: 1, explanation: 'Lead indicators (sessions completed, hours studied) are within your control and predict outcomes better than tracking outcomes alone.' },
    { type: 'multiple_choice', question: 'What adherence level should you celebrate?', options: ['Only 100% perfection', '85% — demanding perfection creates all-or-nothing thinking', '50% is sufficient', 'Any level is fine'], correctAnswer: 1, explanation: 'Hitting 85% adherence is excellent. Demanding 100% creates all-or-nothing thinking that collapses at the first miss.' },
    { type: 'multiple_choice', question: 'What separates people who achieve goals from those who do not?', options: ['Talent', 'Motivation', 'Systems that make consistency the default', 'Willpower'], correctAnswer: 2, explanation: 'The difference is rarely talent or knowledge — it is systems that make consistency the default, making motivation optional.' },
    { type: 'multiple_choice', question: 'What is the difference between internal and external accountability?', options: ['There is no difference', 'Internal is self-monitoring; external involves another person or system holding you accountable', 'External is always better', 'Internal is always better'], correctAnswer: 1, explanation: 'Both are valuable — internal accountability (tracking, self-monitoring) works best combined with external (coaches, partners, public commitments).' },
    { type: 'multiple_choice', question: 'What is a commitment device?', options: ['A fitness tracker', 'A pre-arranged consequence or constraint that makes it harder to skip the behaviour', 'A smartphone app', 'A written goal'], correctAnswer: 1, explanation: 'Commitment devices — like paying for a class in advance or scheduling with a partner — create costs for non-compliance.' },
    { type: 'multiple_choice', question: 'Why does tracking progress improve adherence?', options: ['It does not help', 'Visual evidence of consistency creates a streak effect — you do not want to break the chain', 'Tracking is stressful', 'It only works for fitness'], correctAnswer: 1, explanation: 'Seeing a streak of completed actions creates psychological momentum — missing one day feels like breaking a chain you have built.' },
    { type: 'multiple_choice', question: 'What is the best way to recover after breaking a habit streak?', options: ['Give up — the streak is broken', 'Never miss twice — get back on track immediately without self-punishment', 'Start a completely new habit', 'Take a week off to reset'], correctAnswer: 1, explanation: 'The "never miss twice" rule prevents a single miss from becoming a spiral — one bad day does not erase weeks of progress.' },
    { type: 'multiple_choice', question: 'How does public commitment increase follow-through?', options: ['It does not', 'Social pressure and identity consistency make you more likely to follow through', 'It only works for extroverts', 'It creates too much pressure'], correctAnswer: 1, explanation: 'Publicly stating a commitment creates social accountability and engages identity consistency — you want to be seen as someone who keeps their word.' },
  
  ]),
];
