import type { UnitAssessment } from '../types';

export const mindsetL2Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Focus, Discipline & Habit Formation',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['1 hour', 'Average of 23 minutes', '2 minutes', '30 seconds'], correctAnswer: 1, explanation: 'Research shows it takes an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'What is true multitasking?', options: ['Listening to music while studying', 'Working on a laptop while watching TV', 'Performing two cognitive tasks simultaneously — which is neurologically impossible', 'Switching quickly between tasks'], correctAnswer: 2, explanation: 'True cognitive multitasking is impossible — what people call multitasking is rapid task switching.' },
    { type: 'multiple_choice', question: 'Why is motivation unreliable for sustained behaviour?', options: ['It only works for beginners', 'It is an emotion that fluctuates like all emotions', 'It is always low', 'It requires too much energy'], correctAnswer: 1, explanation: 'Motivation fluctuates naturally — systems and discipline produce more consistent results.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['A habit copied from someone else', 'A habit based on who you want to become', 'A habit based on rewards', 'A habit based on what you want to achieve'], correctAnswer: 1, explanation: 'Identity-based habits focus on becoming the type of person who naturally does the desired behaviour.' },
    { type: 'multiple_choice', question: 'What are the three components of the habit loop?', options: ['Plan, Execute, Review', 'Trigger, Action, Outcome', 'Cue, Routine, Reward', 'Start, Continue, Stop'], correctAnswer: 2, explanation: 'The habit loop is: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Changing your interpretation of a situation to change how you feel about it', 'Ignoring negative thoughts', 'Arguing with your emotions', 'Suppressing difficult feelings'], correctAnswer: 0, explanation: 'Cognitive reappraisal changes interpretation, not facts, to produce a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does the "S" in the STOP method stand for?', options: ['Speak', 'Stop', 'Start', 'Shift'], correctAnswer: 1, explanation: 'S = Stop. Literally pause before speaking or acting.' },
    { type: 'multiple_choice', question: 'Why is process visualisation more effective than outcome visualisation?', options: ['It is easier', 'It is faster', 'It prepares you for the actual steps and challenges involved', 'Outcome visualisation does not work at all'], correctAnswer: 2, explanation: 'Process visualisation improves performance by mentally rehearsing the steps and responses needed.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['4–8 weeks', '1 week', '6 months', '1 year'], correctAnswer: 0, explanation: 'Most habits require approximately 4–8 weeks of consistent repetition to become automatic.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Always do double if you miss', 'Train even when injured', 'Always train twice a day', 'Missing one day is acceptable but two consecutive days starts a new pattern of not doing it'], correctAnswer: 3, explanation: 'One missed day does not break a habit — but two consecutive days establishes a pattern of absence.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Writing labels on a journal', 'Naming your emotions out loud to reduce their intensity', 'Categorising people by personality', 'Putting sticky notes on emotions'], correctAnswer: 1, explanation: 'Naming emotions activates the prefrontal cortex and measurably reduces emotional intensity.' },
    { type: 'multiple_choice', question: 'Which brain region handles automatic habits?', options: ['Prefrontal cortex', 'Hippocampus', 'Amygdala', 'Basal ganglia'], correctAnswer: 3, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex for other tasks.' },
    // ── Additional questions ──
    { type: 'multiple_choice', question: "The 'habit loop' consists of:", options: ['Motivation, discipline, success', 'Goal, plan, action', 'Cue, routine, reward', 'Thought, feeling, behaviour'], correctAnswer: 2, explanation: 'Charles Duhigg's habit loop identifies three stages: a cue (trigger), a routine (behaviour), and a reward (reinforcement)." },
    { type: 'multiple_choice', question: "What is the difference between discipline and motivation?", options: ['Discipline is consistent action regardless of feeling; motivation is emotion-dependent', 'They are the same thing', 'Motivation is more reliable than discipline', 'Discipline only works for physical tasks'], correctAnswer: 0, explanation: 'Motivation fluctuates with mood and energy. Discipline is the ability to act consistently regardless of how you feel \u2014 it's the more reliable driver of long-term progress." },
    { type: 'multiple_choice', question: "Emotional regulation refers to:", options: ["Suppressing all emotions", "Never feeling angry or sad", "The ability to manage and respond to emotional experiences in healthy ways", "Ignoring your feelings completely"], correctAnswer: 2, explanation: "Emotional regulation is about managing \u2014 not eliminating \u2014 emotions. It involves recognising, understanding, and responding to emotions constructively." },
    { type: 'multiple_choice', question: "Visualisation improves performance because:", options: ['It creates actual physical practice', 'It replaces the need for real practice', 'It activates similar neural pathways as physical execution', 'It only works for elite athletes'], correctAnswer: 2, explanation: 'Neuroscience shows that mental rehearsal activates many of the same brain regions as physical practice, strengthening neural pathways and improving motor preparation.' },
    { type: 'multiple_choice', question: "Which of these is the most effective way to build a new habit?", options: ['Attaching the new behaviour to an existing routine (habit stacking)', 'Making huge changes all at once', 'Relying on willpower alone', 'Only doing it when you feel like it'], correctAnswer: 0, explanation: 'Habit stacking \u2014 linking a new behaviour to an established one \u2014 uses existing neural pathways as anchors, making the new habit easier to trigger consistently.' },
    { type: 'multiple_choice', question: "Deep focus is best sustained for periods of:", options: ["60\u201390 minutes before taking a break", "4\u20135 hours without any break", "10 minutes maximum", "Only during morning hours"], correctAnswer: 0, explanation: "Research on ultradian rhythms suggests deep focus works best in 60\u201390 minute blocks, followed by a break to allow the brain to consolidate and recover." },
    { type: 'multiple_choice', question: "Which neurotransmitter is most associated with focus and attention?", options: ['Serotonin', 'GABA', 'Dopamine', 'Melatonin'], correctAnswer: 2, explanation: 'Dopamine plays a crucial role in attention, motivation, and reward-seeking behaviour \u2014 it's central to the brain's ability to sustain focus on tasks." },
    { type: 'multiple_choice', question: "The concept of 'keystone habits' refers to:", options: ['Habits that only work in the morning', 'Physical exercise only', 'The most difficult habits to build', 'Habits that trigger a cascade of other positive behaviour changes'], correctAnswer: 3, explanation: 'Keystone habits \u2014 like regular exercise or daily planning \u2014 create ripple effects that positively influence other areas of life.' },

  ],
};
