import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 }

export const mindsetL2Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['23 minutes', '5 seconds', '1 minute', '2 minutes'], correctAnswer: 0, explanation: 'Research shows an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'Is true multitasking possible for cognitive tasks?', options: ['Yes', 'Only for experts', 'Only for women', 'No — it is rapid task switching'], correctAnswer: 3, explanation: 'The brain cannot perform two cognitively demanding tasks simultaneously.' },
    { type: 'multiple_choice', question: 'What is the Pomodoro technique?', options: ['A cooking method', 'A type of exercise', '25–50 minute focused work blocks with 5–10 minute breaks', 'A sleep protocol'], correctAnswer: 2, explanation: 'The Pomodoro technique structures work into focused blocks with strategic breaks.' },
    { type: 'multiple_choice', question: 'What is the two-minute rule?', options: ['Rest for 2 minutes', 'If a task takes less than 2 minutes, do it now; otherwise schedule it', 'Meditate for 2 minutes', 'Warm up for 2 minutes'], correctAnswer: 1, explanation: 'Quick tasks done immediately prevent them from fragmenting future attention.' },
    { type: 'multiple_choice', question: 'What depletes the prefrontal cortex\'s capacity?', options: ['Every decision, task switch, and distraction', 'Exercise', 'Water intake', 'Sleep'], correctAnswer: 0, explanation: 'The prefrontal cortex operates like a battery depleted by decisions and cognitive demands.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'Why is motivation unreliable?', options: ['It is always low', 'It only works for some people', 'It does not exist', 'It is an emotion that naturally fluctuates'], correctAnswer: 3, explanation: 'Like all emotions, motivation rises and falls — systems and discipline are more consistent.' },
    { type: 'multiple_choice', question: 'What is environment design?', options: ['Interior decorating', 'Building a new house', 'Arranging your environment so desired actions are the easiest option', 'Organising your desk'], correctAnswer: 2, explanation: 'Environment design reduces willpower required by making good choices the default.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['Setting outcome goals', 'Acting consistently with who you want to become', 'Copying someone else', 'Tracking habits on an app'], correctAnswer: 1, explanation: 'Identity-based habits flow from self-concept: "I am someone who..." rather than "I want to..."' },
    { type: 'multiple_choice', question: 'What does "every action is a vote" mean?', options: ['Each action reinforces the type of person you are becoming', 'Only big actions count', 'Actions do not matter', 'You should vote more'], correctAnswer: 0, explanation: 'Small consistent actions accumulate into identity — each one is a vote for who you are becoming.' },
    { type: 'multiple_choice', question: 'What is the most effective way to train consistently?', options: ['Wait for motivation', 'Train twice as hard on good days', 'Only train when you feel great', 'Create systems that work regardless of how you feel'], correctAnswer: 3, explanation: 'Systems that operate independently of motivation produce the most consistent results.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What are the three parts of the habit loop?', options: ['Plan, Act, Review', 'Try, Fail, Retry', 'Cue, Routine, Reward', 'Start, Middle, End'], correctAnswer: 2, explanation: 'Every habit follows: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'Which brain region takes over once a habit is automatic?', options: ['Prefrontal cortex', 'Basal ganglia', 'Amygdala', 'Cerebellum'], correctAnswer: 1, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex.' },
    { type: 'multiple_choice', question: 'What is the best way to break an unwanted habit?', options: ['Keep the cue and reward but replace the routine', 'Use willpower', 'Ignore it', 'Punish yourself'], correctAnswer: 0, explanation: 'Replacing the routine while keeping the same cue and reward is the most effective strategy.' },
    { type: 'multiple_choice', question: 'What does "start absurdly small" mean?', options: ['Think small forever', 'Never progress', 'Only do easy things', 'Set tiny goals like one press-up to reduce resistance'], correctAnswer: 3, explanation: 'Absurdly small starts (one press-up, 2 minutes of journaling) build the neural pathway with minimal resistance.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Train twice daily', 'Always do double after missing', 'Missing one day is fine but two consecutive days starts a pattern of absence', 'Never miss any day'], correctAnswer: 2, explanation: 'One miss does not break a habit — but two consecutive misses establish a new pattern.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'Is emotional regulation the same as suppression?', options: ['Depends on the situation', 'No — regulation is conscious processing, not hiding emotions', 'Yes', 'Only for negative emotions'], correctAnswer: 1, explanation: 'Regulation means processing emotions consciously; suppression increases stress and impairs health.' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Changing your interpretation to change your emotional response', 'Denying reality', 'Ignoring the situation', 'Arguing with yourself'], correctAnswer: 0, explanation: 'Reappraisal changes interpretation, not facts, producing a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does STOP stand for?', options: ['Stop, Think, Observe, Proceed', 'Start, Try, Overcome, Persist', 'Slow, Think, Operate, Plan', 'Stop, Take a breath, Observe, Proceed'], correctAnswer: 3, explanation: 'Stop, Take a breath, Observe your feelings, Proceed with conscious choice.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Writing feelings on a label', 'Rating emotions 1-10', 'Naming your emotions to reduce their intensity', 'Describing emotions to others'], correctAnswer: 2, explanation: 'Naming emotions ("I notice I am feeling angry") activates the prefrontal cortex and reduces intensity.' },
    { type: 'multiple_choice', question: 'What creates the "space" between stimulus and response?', options: ['Distance', 'Conscious awareness and deliberate pausing', 'Time', 'Other people'], correctAnswer: 1, explanation: 'Conscious awareness — pausing before reacting — creates the space for intentional response.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'Why does visualisation work?', options: ['It activates the same neural pathways as physical performance', 'It replaces practice', 'It is magic', 'It only works for athletes'], correctAnswer: 0, explanation: 'Mental rehearsal activates motor cortex regions similar to actual movement.' },
    { type: 'multiple_choice', question: 'Which type of visualisation improves performance more?', options: ['Both equally', 'Outcome visualisation', 'Neither works', 'Process visualisation'], correctAnswer: 3, explanation: 'Process visualisation (imagining steps and challenges) is more effective than imagining the end result.' },
    { type: 'multiple_choice', question: 'Should you include challenges in your visualisation?', options: ['No — only positive outcomes', 'Only if you expect problems', 'Yes — visualise encountering and overcoming difficulty', 'Challenges are too negative'], correctAnswer: 2, explanation: 'Including challenges in visualisation prepares you to respond effectively during actual performance.' },
    { type: 'multiple_choice', question: 'How long should a visualisation session last?', options: ['1 hour', '5–10 minutes', '1 minute', '30 minutes'], correctAnswer: 1, explanation: '5–10 minutes per session, practised 3–5 times before an event, is the evidence-based approach.' },
    { type: 'multiple_choice', question: 'Can outcome visualisation actually reduce effort?', options: ['Yes — it can create a premature sense of achievement', 'It always increases effort', 'No', 'Only for lazy people'], correctAnswer: 0, explanation: 'Research shows imagining the end result can reduce effort by creating premature satisfaction.' },
  ]),
];
