import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const mindsetL2Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'Is resilience an innate trait or a trainable skill?', options: ['Innate — you either have it or you don\'t', 'Determined by genetics alone', 'Only for athletes', 'Trainable — it develops through practice'], correctAnswer: 3, explanation: 'Research consistently shows resilience is a set of trainable skills, not a fixed trait.' },
    { type: 'multiple_choice', question: 'What are the three components of resilience?', options: ['Courage, Endurance, Discipline', 'Speed, Strength, Power', 'Adaptability, Emotional Regulation, Recovery', 'Intelligence, Creativity, Memory'], correctAnswer: 2, explanation: 'Resilience comprises adaptability, emotional regulation, and recovery capacity.' },
    { type: 'multiple_choice', question: 'Does resilience mean never feeling stressed?', options: ['Only under extreme conditions', 'No — resilient people still feel stress but process it effectively', 'It depends on personality', 'Yes'], correctAnswer: 1, explanation: 'Resilient people experience the full range of emotions but have better systems for processing them.' },
    { type: 'multiple_choice', question: 'What does growth orientation mean in the context of resilience?', options: ['Viewing challenges as opportunities for development', 'Ignoring problems', 'Getting taller', 'Always being positive'], correctAnswer: 0, explanation: 'Growth orientation means seeing challenges as development opportunities rather than threats.' },
    { type: 'multiple_choice', question: 'What is the misconception about resilience that causes harm?', options: ['That it can be learned', 'That it requires practice', 'That it involves emotions', 'That it means never breaking — which discourages seeking help'], correctAnswer: 3, explanation: 'The "never break" myth frames normal emotional responses as weakness and discourages help-seeking.' },
    { type: 'multiple_choice', question: 'How is mental resilience built?', options: ['Through medication', 'Through avoiding all stress', 'Through deliberate exposure to manageable challenges and structured recovery', 'Through reading about it'], correctAnswer: 2, explanation: 'Like physical strength, resilience builds through progressive challenge and recovery.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'Can your brain distinguish between real and perceived threats?', options: ['Yes, always', 'No — both trigger the same fight-or-flight response', 'Only when you are calm', 'Only in adults'], correctAnswer: 1, explanation: 'The amygdala triggers the same physiological cascade for both real and perceived threats.' },
    { type: 'multiple_choice', question: 'What is the difference between acute and chronic stress?', options: ['Acute is short-term and beneficial; chronic is sustained and harmful', 'Acute only affects athletes', 'They are the same', 'Acute is bad, chronic is good'], correctAnswer: 0, explanation: 'Acute stress drives adaptation; chronic stress damages health and performance.' },
    { type: 'multiple_choice', question: 'What does elevated cortisol promote?', options: ['Muscle growth', 'Faster recovery', 'Better focus', 'Fat storage, immune suppression, and sleep disruption'], correctAnswer: 3, explanation: 'Chronic cortisol elevation promotes visceral fat storage, impairs immunity, and disrupts sleep.' },
    { type: 'multiple_choice', question: 'What hormone provides immediate energy during acute stress?', options: ['Insulin', 'Melatonin', 'Adrenaline', 'Cortisol'], correctAnswer: 2, explanation: 'Adrenaline provides the immediate energy and alertness burst during acute stress.' },
    { type: 'multiple_choice', question: 'What is the key message about stress management?', options: ['Ignore stress', 'Control your relationship with stress — do not eliminate it', 'Eliminate all stress', 'Only manage work stress'], correctAnswer: 1, explanation: 'The goal is managing your response to stress, not eliminating stress entirely.' },
    { type: 'multiple_choice', question: 'If you are constantly tired, frequently ill, and sleeping poorly, what is likely too high?', options: ['Your total stress load', 'Your motivation', 'Your happiness', 'Your protein intake'], correctAnswer: 0, explanation: 'These symptoms typically indicate an excessive total stress load across all life domains.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What are the two branches of the autonomic nervous system?', options: ['Somatic and reflex', 'Motor and sensory', 'Central and peripheral', 'Sympathetic and parasympathetic'], correctAnswer: 3, explanation: 'The ANS has sympathetic (accelerator) and parasympathetic (brake) branches.' },
    { type: 'multiple_choice', question: 'What is vagal tone?', options: ['A sound the vagus nerve makes', 'A type of meditation', 'The strength and efficiency of the vagus nerve', 'A breathing technique'], correctAnswer: 2, explanation: 'Higher vagal tone is associated with better stress recovery, emotional regulation, and resilience.' },
    { type: 'multiple_choice', question: 'What happens to heart rate during exhalation?', options: ['It stops', 'It decreases', 'It stays the same', 'It increases'], correctAnswer: 1, explanation: 'Heart rate naturally decreases during exhale — a phenomenon called respiratory sinus arrhythmia.' },
    { type: 'multiple_choice', question: 'Why is breathing unique among autonomic functions?', options: ['It can be controlled both voluntarily and involuntarily', 'It uses the most energy', 'It cannot be changed', 'It only works when conscious'], correctAnswer: 0, explanation: 'Breathing is the only autonomic function you can also control voluntarily — bridging conscious and unconscious systems.' },
    { type: 'multiple_choice', question: 'What type of breathing activates the sympathetic system?', options: ['Extended exhale breathing', 'Diaphragmatic breathing', 'Slow nasal breathing', 'Fast shallow chest breathing'], correctAnswer: 3, explanation: 'Fast, shallow chest breathing signals stress and activates sympathetic tone.' },
    { type: 'multiple_choice', question: 'What does nasal breathing produce that mouth breathing does not?', options: ['More CO2', 'Adrenaline', 'Nitric oxide', 'More oxygen'], correctAnswer: 2, explanation: 'Nasal breathing activates nitric oxide production, which aids blood flow and oxygen delivery.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What does a fixed mindset believe about abilities?', options: ['They improve with age', 'They are innate and unchangeable', 'They do not exist', 'They are developed through effort'], correctAnswer: 1, explanation: 'Fixed mindset assumes abilities are innate — you either have them or you do not.' },
    { type: 'multiple_choice', question: 'What is the most powerful single word for shifting to a growth mindset?', options: ['Yet', 'Always', 'No', 'Never'], correctAnswer: 0, explanation: '"Yet" transforms dead ends into directions: "I can\'t do this... yet."' },
    { type: 'multiple_choice', question: 'Can you hold different mindsets in different areas of life?', options: ['Only children can', 'Only if you are a beginner', 'No — you are either fixed or growth', 'Yes — most people have different mindsets in different domains'], correctAnswer: 3, explanation: 'Most people hold growth mindsets in some areas and fixed mindsets in others.' },
    { type: 'multiple_choice', question: 'How does a growth mindset respond to failure?', options: ['Gives up', 'Pretends it didn\'t happen', 'Asks "what can I learn?" and adjusts approach', 'Blames others'], correctAnswer: 2, explanation: 'Growth mindset attributes failure to changeable behaviours and strategies, not fixed traits.' },
    { type: 'multiple_choice', question: 'Does growth mindset mean you can achieve anything?', options: ['Only with a coach', 'No — genetics and circumstances matter, but mindset influences what you do within your constraints', 'Only in sport', 'Yes, with enough effort'], correctAnswer: 1, explanation: 'Growth mindset means optimising within constraints, not ignoring reality.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'Which goal type is entirely within your control?', options: ['Process goal', 'Dream goal', 'Outcome goal', 'Performance goal'], correctAnswer: 0, explanation: 'Process goals (daily actions) are fully controllable regardless of external factors.' },
    { type: 'multiple_choice', question: 'Why do outcome goals become discouraging?', options: ['They are unrealistic by definition', 'They cost too much', 'They are too easy', 'Progress is often slow or invisible, eroding motivation'], correctAnswer: 3, explanation: 'When results are slow, outcome-dependent motivation collapses despite perfect process.' },
    { type: 'multiple_choice', question: 'What makes process goals sustain motivation?', options: ['They are easier to set', 'They are impressive to others', 'They provide daily wins that accumulate into habit formation', 'They require no effort'], correctAnswer: 2, explanation: 'Daily small wins from process goals build habits — which are more powerful than motivation.' },
    { type: 'multiple_choice', question: 'How often should you review performance goals?', options: ['Daily', 'Monthly', 'Weekly', 'Yearly'], correctAnswer: 1, explanation: 'Monthly reviews give enough time to see trends while allowing timely adjustments.' },
    { type: 'multiple_choice', question: 'How long should you try a new process before concluding it is not working?', options: ['2–4 weeks', '1 year', '6 months', '1 day'], correctAnswer: 0, explanation: 'Give each process adjustment at least 2–4 weeks before evaluating its effectiveness.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What is the single most powerful recovery tool?', options: ['Massage', 'Ice baths', 'Supplements', 'Sleep'], correctAnswer: 3, explanation: 'Sleep is the most powerful recovery tool — no supplement or technique can compensate for poor sleep.' },
    { type: 'multiple_choice', question: 'What predominates in the first half of the night?', options: ['No sleep stages dominate', 'REM sleep', 'Deep sleep (N3)', 'Light sleep only'], correctAnswer: 2, explanation: 'Deep sleep predominates in the first half; REM predominates in the second half.' },
    { type: 'multiple_choice', question: 'What does REM sleep support?', options: ['Bone density', 'Emotional processing, creativity, and memory consolidation', 'Muscle growth', 'Physical recovery only'], correctAnswer: 1, explanation: 'REM sleep is essential for emotional processing, creativity, and memory consolidation.' },
    { type: 'multiple_choice', question: 'Why does alcohol impair sleep despite helping you fall asleep?', options: ['It disrupts sleep architecture, reducing REM and deep sleep', 'It does not impair sleep', 'It only affects light sleep', 'It makes you sleep too long'], correctAnswer: 0, explanation: 'Alcohol significantly reduces the quality of sleep by disrupting both REM and deep sleep phases.' },
    { type: 'multiple_choice', question: 'What triggers melatonin release?', options: ['Bright light', 'Caffeine', 'Exercise', 'Darkness'], correctAnswer: 3, explanation: 'Darkness triggers melatonin release, which is why reducing light before bed aids sleep onset.' },
  ]),
];
