import type { UnitAssessment } from '../types';

export const mindsetL2Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Focus, Discipline & Habit Formation',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['1 hour', '30 seconds', '2 minutes', 'Average of 23 minutes'], correctAnswer: 3, explanation: 'Research shows it takes an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'What is true multitasking?', options: ['Listening to music while studying', 'Working on a laptop while watching TV', 'Performing two cognitive tasks simultaneously — which is neurologically impossible', 'Switching quickly between tasks'], correctAnswer: 2, explanation: 'True cognitive multitasking is impossible — what people call multitasking is rapid task switching.' },
    { type: 'multiple_choice', question: 'Why is motivation unreliable for sustained behaviour?', options: ['It only works for beginners', 'It is an emotion that fluctuates like all emotions', 'It is always low', 'It requires too much energy'], correctAnswer: 1, explanation: 'Motivation fluctuates naturally — systems and discipline produce more consistent results.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['A habit based on who you want to become', 'A habit copied from someone else', 'A habit based on rewards', 'A habit based on what you want to achieve'], correctAnswer: 0, explanation: 'Identity-based habits focus on becoming the type of person who naturally does the desired behaviour.' },
    { type: 'multiple_choice', question: 'What are the three components of the habit loop?', options: ['Plan, Execute, Review', 'Trigger, Action, Outcome', 'Start, Continue, Stop', 'Cue, Routine, Reward'], correctAnswer: 3, explanation: 'The habit loop is: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Arguing with your emotions', 'Ignoring negative thoughts', 'Changing your interpretation of a situation to change how you feel about it', 'Suppressing difficult feelings'], correctAnswer: 2, explanation: 'Cognitive reappraisal changes interpretation, not facts, to produce a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does the "S" in the STOP method stand for?', options: ['Speak', 'Stop', 'Start', 'Shift'], correctAnswer: 1, explanation: 'S = Stop. Literally pause before speaking or acting.' },
    { type: 'multiple_choice', question: 'Why is process visualisation more effective than outcome visualisation?', options: ['It prepares you for the actual steps and challenges involved', 'It is faster', 'It is easier', 'Outcome visualisation does not work at all'], correctAnswer: 0, explanation: 'Process visualisation improves performance by mentally rehearsing the steps and responses needed.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['1 year', '1 week', '6 months', '4–8 weeks'], correctAnswer: 3, explanation: 'Most habits require approximately 4–8 weeks of consistent repetition to become automatic.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Always do double if you miss', 'Train even when injured', 'Missing one day is acceptable but two consecutive days starts a new pattern of not doing it', 'Always train twice a day'], correctAnswer: 2, explanation: 'One missed day does not break a habit — but two consecutive days establishes a pattern of absence.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Writing labels on a journal', 'Naming your emotions out loud to reduce their intensity', 'Categorising people by personality', 'Putting sticky notes on emotions'], correctAnswer: 1, explanation: 'Naming emotions activates the prefrontal cortex and measurably reduces emotional intensity.' },
    { type: 'multiple_choice', question: 'Which brain region handles automatic habits?', options: ['Basal ganglia', 'Hippocampus', 'Amygdala', 'Prefrontal cortex'], correctAnswer: 0, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex for other tasks.' },
  ],
};
