import type { UnitAssessment } from '../types';

export const nutritionL4Unit2Assessment: UnitAssessment = {
  unitNumber: 2,
  title: 'Clinical Nutrition & Special Populations — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What dietary pattern has the strongest evidence for reducing cardiovascular disease risk?', options: ['Low-fat diet', 'Mediterranean diet', 'Carnivore diet', 'Juice cleanse'], correctAnswer: 1, explanation: 'The PREDIMED trial showed a 30% reduction in major cardiovascular events with the Mediterranean diet.' },
    { type: 'multiple_choice', question: 'What is the most modifiable condition in clinical nutrition?', options: ['Type 1 diabetes', 'Pre-diabetes — 58% reduction in progression with lifestyle changes', 'Coeliac disease', 'Food allergy'], correctAnswer: 1, explanation: 'Pre-diabetes responds dramatically to weight loss and physical activity.' },
    { type: 'multiple_choice', question: 'Why is protein important for bone health?', options: ['It has no role in bone health', 'Protein provides amino acids for collagen synthesis — the structural matrix of bone', 'Protein weakens bones', 'Only calcium matters for bones'], correctAnswer: 1, explanation: 'Higher protein intakes improve net calcium balance and provide collagen building blocks.' },
    { type: 'multiple_choice', question: 'What folate dose is recommended from pre-conception through 12 weeks of pregnancy?', options: ['100μg', '400μg daily', '1000μg', 'No folate needed'], correctAnswer: 1, explanation: '400μg folate daily prevents neural tube defects during early foetal development.' },
    { type: 'multiple_choice', question: 'What is sarcopenia and why does it matter?', options: ['A type of diet', 'Age-related muscle loss — the primary driver of falls, fractures, and loss of independence', 'A bone condition', 'A vitamin deficiency'], correctAnswer: 1, explanation: 'Sarcopenia is more predictive of hospitalisation and death than obesity in older adults.' },
    { type: 'multiple_choice', question: 'What landmark trial demonstrated dietary improvement can reduce depression symptoms?', options: ['DASH trial', 'SMILES trial (2017)', 'Framingham Heart Study', 'PURE study'], correctAnswer: 1, explanation: 'The SMILES trial was the first RCT showing dietary improvement alone reduces depression.' },
    { type: 'multiple_choice', question: 'What should you do if you suspect a client has a clinical eating disorder?', options: ['Design a stricter meal plan', 'Refer to their GP — eating disorders require specialist treatment', 'Increase their exercise', 'Tell them to eat more'], correctAnswer: 1, explanation: 'Clinical eating disorders are outside nutrition coaching scope — always refer.' },
    { type: 'multiple_choice', question: 'Why are IgG food sensitivity tests unreliable?', options: ['They are too expensive', 'IgG antibodies to foods are a normal immune response to eating, not intolerance markers', 'They only detect allergies', 'They are too accurate'], correctAnswer: 1, explanation: 'A positive IgG result simply means you have eaten that food — it is normal.' },
    { type: 'multiple_choice', question: 'What is RED-S in young athletes?', options: ['A training method', 'Relative Energy Deficiency in Sport — insufficient energy intake for training demands', 'A recovery protocol', 'A type of supplement'], correctAnswer: 1, explanation: 'RED-S causes impaired growth, stress fractures, hormonal disruption, and mental health issues.' },
    { type: 'scenario', question: 'A 45-year-old client has just been diagnosed with pre-diabetes (HbA1c 44 mmol/mol). They are 15kg overweight and sedentary. What is your primary nutritional approach?', scenario: 'The client is motivated but overwhelmed. They have been told by their GP to "sort out their diet."', options: ['Prescribe metformin through dietary channels', 'Focus on moderate caloric deficit for 5-7% weight loss, increased fibre, protein at every meal, and refer to GP for monitoring', 'Put them on a ketogenic diet immediately', 'Tell them pre-diabetes is not serious'], correctAnswer: 1, explanation: 'Moderate weight loss with dietary quality improvement is the evidence-based approach, with medical monitoring.' },
    { type: 'scenario', question: 'A 16-year-old gymnast has lost her menstrual period and is frequently ill. Her coach says she needs to lose 2kg for competition. What do you do?', scenario: 'She trains 20 hours per week and reports eating 1,400 kcal/day. Her parents are supportive but unsure.', options: ['Help her lose the 2kg as requested', 'Flag RED-S concerns, refuse to support weight loss, discuss increasing energy intake with the family, and refer to GP', 'Tell her to train harder', 'Reduce her training load without addressing nutrition'], correctAnswer: 1, explanation: 'Amenorrhoea + recurrent illness + inadequate intake = RED-S. This requires medical referral and increased nutrition, not weight loss.' },
  ],
};
