import type { UnitAssessment } from '../types';

export const nutritionL4Unit1Assessment: UnitAssessment = {
  unitNumber: 1,
  title: 'Advanced Metabolic Science — Unit Assessment',
  passMarkPercent: 80,
  pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What are the three primary metabolic pathways for ATP production?', options: ['Digestion, Absorption, Excretion', 'Glycolysis, Krebs cycle, Electron transport chain', 'Lipolysis, Ketogenesis, Gluconeogenesis', 'Protein synthesis, Fat oxidation, Glycogen loading'], correctAnswer: 1, explanation: 'These pathways form the fundamental energy production system in human metabolism.' },
    { type: 'multiple_choice', question: 'What hormonal changes make weight regain likely after a prolonged diet?', options: ['Hormones remain stable', 'Leptin decreases, ghrelin increases, thyroid output falls, cortisol rises — creating a hormonal environment that promotes weight regain', 'Only insulin changes', 'Testosterone increases'], correctAnswer: 1, explanation: 'The body mounts a coordinated hormonal defence against weight loss.' },
    { type: 'multiple_choice', question: 'What is NEAT and why does it matter during dieting?', options: ['A supplement brand', 'Non-Exercise Activity Thermogenesis — unconscious movement that can decrease by 200-500 kcal/day during dieting', 'A type of exercise', 'Net Energy After Training'], correctAnswer: 1, explanation: 'NEAT reduction is one of the largest contributors to metabolic adaptation.' },
    { type: 'multiple_choice', question: 'What is the purpose of a reverse diet after prolonged caloric restriction?', options: ['Rapid weight gain', 'Gradually restoring metabolic rate, hormonal function, and appetite regulation while minimising fat regain', 'Building muscle', 'Eliminating food groups'], correctAnswer: 1, explanation: 'Reverse dieting transitions from deficit to maintenance with minimal fat rebound.' },
    { type: 'multiple_choice', question: 'How does calorie cycling match nutrition to training demands?', options: ['Same calories every day', 'Higher calories on training days for performance and recovery; lower on rest days for deficit creation — same weekly average', 'Only protein changes', 'Fasting on training days'], correctAnswer: 1, explanation: 'Calorie cycling optimises both performance and body composition simultaneously.' },
    { type: 'multiple_choice', question: 'What dietary strategy produces the greatest microbiome diversity?', options: ['High-protein, low-fibre', '30+ different plant foods per week with prebiotic and probiotic-rich foods', 'Processed food diet', 'Single-food elimination diets'], correctAnswer: 1, explanation: 'Diverse plant fibres feed different bacterial species, supporting gut health and immunity.' },
    { type: 'multiple_choice', question: 'Why should fat loss phases not coincide with competition seasons?', options: ['They can coincide safely', 'Caloric restriction impairs performance, recovery, and immune function — all critical during competition', 'It is too complex logistically', 'No reason'], correctAnswer: 1, explanation: 'Plan body composition work for off-season when performance consequences are minimised.' },
    { type: 'multiple_choice', question: 'What section of a research paper should you evaluate first to assess quality?', options: ['Abstract', 'Methods — study design determines whether results are trustworthy', 'Conclusion', 'Author list'], correctAnswer: 1, explanation: 'Perfect results from poor methods produce meaningless conclusions.' },
    { type: 'scenario', question: 'A client has been dieting at 1,500 kcal for 4 months with excellent compliance but weight loss has stalled for 3 weeks. Step count has dropped from 10,000 to 6,000 daily. What is your assessment?', scenario: 'They feel tired, cold, and irritable. Training performance has declined.', options: ['Reduce calories to 1,200 kcal', 'Diagnose metabolic adaptation — NEAT has dropped, hormones are likely suppressed. Recommend a 1-2 week diet break at maintenance before resuming a moderate deficit with restored step count', 'Double their cardio', 'Tell them to push through'], correctAnswer: 1, explanation: 'All signs point to metabolic adaptation. A diet break restores hormonal signalling before continuing.' },
    { type: 'scenario', question: 'A client says they want to simultaneously lose fat and build muscle. They are an intermediate lifter who has been training for 3 years. What is your advice?', scenario: 'They are at approximately 20% body fat. Current intake is at maintenance.', options: ['Tell them recomposition is impossible', 'Explain that recomposition is slower in intermediates but possible — recommend a slight deficit (200-300 kcal), high protein (2.0-2.2g/kg), progressive training, and patience with body weight as a metric', 'Recommend aggressive bulking then cutting', 'Suggest they stop training'], correctAnswer: 1, explanation: 'Recomposition is possible but requires patience, high protein, and progressive overload.' },
    { type: 'multiple_choice', question: 'What is the crossover concept in substrate utilisation?', options: ['Training two sports', 'As exercise intensity increases, fuel use shifts from predominantly fat to predominantly carbohydrate', 'Switching supplements', 'Cross-training methods'], correctAnswer: 1, explanation: 'Understanding the crossover point helps programme nutrition for different training intensities.' },
    { type: 'multiple_choice', question: 'Why does consistency matter more than optimisation?', options: ['It does not', 'A "good enough" plan followed consistently produces better results than an "optimal" plan followed inconsistently', 'Optimal plans are always better', 'Consistency has no scientific basis'], correctAnswer: 1, explanation: 'Adherence is the strongest predictor of nutrition outcomes — consistency beats perfection.' },
  ],
};
