import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const sportBasketballUnit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'How many jumps does a basketball player perform per game?', options: ['40-60', '5-10', '15-25', '100+'], correctAnswer: 0, explanation: 'Basketball involves 40-60 jumps per game.' },
    { type: 'multiple_choice', question: 'What is the average sprint distance in basketball?', options: ['50-60m', '5-10 metres', '20-30m', '100m'], correctAnswer: 1, explanation: 'Most sprints cover only 5-10 metres.' },
    { type: 'multiple_choice', question: 'What is the aerobic contribution to basketball?', options: ['90%+', '20-30%', '40-50%', '60-70%'], correctAnswer: 3, explanation: '60-70% aerobic with 30-40% anaerobic.' },
    { type: 'multiple_choice', question: 'What physical quality matters most for guards?', options: ['Agility and endurance', 'Maximum strength', 'Body mass', 'Height only'], correctAnswer: 0, explanation: 'Guards need exceptional agility and sustained aerobic fitness.' },
    { type: 'multiple_choice', question: 'Why does total distance understate basketball demands?', options: ['Players walk a lot', 'Distance is not tracked', 'It overstates demands', 'The sport includes jumps, direction changes, and sprints that distance does not capture'], correctAnswer: 3, explanation: 'Jumping, direction changes, and sprint frequency create greater demand than distance suggests.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What determines vertical jump height?', options: ['Relative strength, rate of force development, and reactive strength', 'Leg length', 'Calf size', 'Height alone'], correctAnswer: 0, explanation: 'Three physical qualities combine to determine jump height.' },
    { type: 'multiple_choice', question: 'What landing forces occur during depth jumps?', options: ['5-7x bodyweight', '3-4x bodyweight', '1-2x bodyweight', '10x bodyweight'], correctAnswer: 0, explanation: 'Depth jump landings can reach 5-7x bodyweight.' },
    { type: 'multiple_choice', question: 'What squat target should competitive basketball players aim for?', options: ['4.0x BW', '3.0x BW', '1.5-2.0x bodyweight', '0.5-1.0x BW'], correctAnswer: 2, explanation: '1.5-2.0x bodyweight provides sufficient force production.' },
    { type: 'multiple_choice', question: 'When should in-season gym sessions be scheduled?', options: ['No gym in-season', 'On rest days', 'On practice days to preserve recovery between games', 'Game days only'], correctAnswer: 2, explanation: 'Practice days allow rest days to remain true recovery.' },
    { type: 'multiple_choice', question: 'What is the correct strength development progression?', options: ['All simultaneously', 'Reactive → power → strength', 'Maximal strength → power → reactive ability', 'Power → strength → reactive'], correctAnswer: 2, explanation: 'Building maximal strength before developing power and reactive qualities.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What speed quality is most important for basketball defence?', options: ['Long-distance endurance', 'Flexibility', 'Top-end sprint speed', 'Defensive agility — lateral slides, closeouts, recovery sprints'], correctAnswer: 3, explanation: 'Staying in front of offensive players requires multidirectional agility.' },
    { type: 'multiple_choice', question: 'Why is first-step quickness more valuable than top speed in basketball?', options: ['It is not', 'Court distances are short (5-10m) — top speed is rarely reached', 'Top speed is easy to develop', 'First step looks better'], correctAnswer: 1, explanation: 'Short distances mean games are decided by initial acceleration.' },
    { type: 'multiple_choice', question: 'What makes change of direction training basketball-specific?', options: ['Using a treadmill', 'Running in straight lines', 'Combining movement with dribbling and ball control', 'Using cones only'], correctAnswer: 2, explanation: 'Ball control during direction changes mirrors game demands.' },
    { type: 'multiple_choice', question: 'What is repeated jump ability?', options: ['Maintaining jump height across 40-60 jumps per game', 'Jump training for height only', 'Jumping once very high', 'Jumping only in warm-up'], correctAnswer: 0, explanation: 'Sustaining jump quality across an entire game.' },
    { type: 'multiple_choice', question: 'Why should the last fast break equal the first?', options: ['Rules require it', 'Transition speed must be maintained through repeated sprint ability', 'Coaches demand it', 'It does not matter'], correctAnswer: 1, explanation: 'Repeated sprint quality ensures game-long transition effectiveness.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What VO2max should basketball players target?', options: ['70+ mL/kg/min', '35-40 mL/kg/min', '30 mL/kg/min', '50-60 mL/kg/min'], correctAnswer: 3, explanation: '50-60 mL/kg/min supports between-possession recovery.' },
    { type: 'multiple_choice', question: 'What provides the most basketball-specific conditioning?', options: ['Cycling', 'Small-sided games (3v3, 4v4) on reduced court', 'Long-distance running', 'Swimming'], correctAnswer: 1, explanation: 'Small-sided games develop fitness alongside tactical and technical skills.' },
    { type: 'multiple_choice', question: 'Why is RSA critical for basketball?', options: ['It sounds impressive', 'It determines whether sprint quality is maintained across 50-100 sprints per game', 'Only for track athletes', 'It is not important'], correctAnswer: 1, explanation: 'Game performance depends on maintaining sprint quality throughout.' },
    { type: 'multiple_choice', question: 'What game-specific interval structure matches basketball?', options: ['5-15s high intensity / 15-25s lower intensity in quarter-length sets', 'All-out for 48 minutes', '5min work / 5min rest', '30min continuous effort'], correctAnswer: 0, explanation: 'Matches the possession-based intensity pattern of the game.' },
    { type: 'multiple_choice', question: 'When is supplemental conditioning needed in-season?', options: ['Only pre-game', 'Never', 'Every day', 'Only when game schedule allows — maximum 1-2 additional sessions'], correctAnswer: 3, explanation: 'Practice and games maintain fitness; supplements are limited.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What is the most common basketball injury?', options: ['Concussion', 'Ankle sprain (25-30% of all injuries)', 'Hamstring strain', 'ACL tear'], correctAnswer: 1, explanation: 'Ankle sprains account for 25-30% of basketball injuries.' },
    { type: 'multiple_choice', question: 'How much do ACL prevention programmes reduce injury risk?', options: ['30-40%', '100%', '10-20%', '50-70%'], correctAnswer: 3, explanation: 'Prevention programmes reduce ACL injuries by 50-70%.' },
    { type: 'multiple_choice', question: "What percentage of basketball players experience jumper\'s knee?", options: ['30-45%', '70%+', '15-20%', '5-10%'], correctAnswer: 0, explanation: 'Patellar tendinopathy affects 30-45% of basketball players.' },
    { type: 'multiple_choice', question: 'What is the strongest predictor of future ankle sprain?', options: ['Body weight', 'Previous ankle sprain with residual weakness', 'Court surface', 'Shoe type'], correctAnswer: 1, explanation: 'Previous sprain creating residual weakness is the strongest predictor.' },
    { type: 'multiple_choice', question: 'Why are female players at greater ACL risk?', options: ['The sport is different', 'Biomechanical and hormonal factors create 2-4x higher risk', 'They do not warm up', 'They play harder'], correctAnswer: 1, explanation: 'Multiple factors contribute to higher ACL risk in female athletes.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What protein intake should basketball players target?', options: ['1.2g/kg', '1.6-2.2g/kg', '0.8g/kg', '4.0g/kg'], correctAnswer: 1, explanation: '1.6-2.2g/kg supports muscle repair and recovery.' },
    { type: 'multiple_choice', question: 'How much fluid can players lose per game?', options: ['Less than 500mL', '5 litres', 'None', '1-3 litres'], correctAnswer: 3, explanation: '1-3 litres of sweat loss in heated indoor arenas.' },
    { type: 'multiple_choice', question: 'What should half-time nutrition include?', options: ['A small snack — banana, gel, or energy bar bites', 'A full meal', 'Only water', 'Nothing'], correctAnswer: 0, explanation: 'Small, easily digestible snacks maintain energy.' },
    { type: 'multiple_choice', question: 'How much post-game fluid should be consumed?', options: ['As much as possible immediately', '150% of fluid lost', 'No rehydration needed', 'Equal to sweat loss'], correctAnswer: 1, explanation: '150% of lost fluid ensures complete rehydration.' },
    { type: 'multiple_choice', question: 'When should body composition changes be pursued?', options: ['Gradually during the off-season', 'During the competitive season', 'Only before games', 'Never'], correctAnswer: 0, explanation: 'Off-season changes avoid impairing competitive performance.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'What is short memory in basketball context?', options: ['Not remembering the score', 'Forgetting the play call', 'Forgetting practice', 'Immediately releasing missed shots and approaching the next with full confidence'], correctAnswer: 3, explanation: 'Short memory prevents missed shots from compounding into scoring slumps.' },
    { type: 'multiple_choice', question: 'Why do free throws vary under pressure if the skill is closed?', options: ['The ball changes', 'Defenders distract', 'Distance changes', 'Variation is almost entirely mental — pressure affects execution'], correctAnswer: 3, explanation: 'Free throws are a closed skill — performance variation is psychological.' },
    { type: 'multiple_choice', question: 'How is clutch performance developed?', options: ['Through process focus and pressure simulation in practice', 'Only through game experience', 'It is innate', 'It cannot be developed'], correctAnswer: 0, explanation: 'Simulated pressure and process focus build clutch ability.' },
    { type: 'multiple_choice', question: 'What should shooters focus on during a game?', options: ['Tracking shooting percentage', 'What the crowd thinks', 'Shot quality and shooting mechanics, not previous outcomes', 'How many points they have'], correctAnswer: 2, explanation: 'Process focus prevents outcome-driven confidence fluctuation.' },
    { type: 'multiple_choice', question: 'Why is visualization effective for basketball?', options: ['It replaces practice', 'It creates neural pathways that mirror physical practice of game situations', 'Only for beginners', 'It is not effective'], correctAnswer: 1, explanation: 'Mental rehearsal strengthens the neural patterns of physical execution.' },
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'Why is the off-season the most important training period?', options: ['It is the only time for significant physical development given the dense game schedule', 'Players need rest only', 'All improvement happens in-season', 'It is not'], correctAnswer: 0, explanation: 'Dense in-season schedules prevent meaningful physical development.' },
    { type: 'multiple_choice', question: 'How many gym sessions per week during the season?', options: ['Daily', 'None', '2 sessions structured around game schedule', '5 sessions'], correctAnswer: 2, explanation: '2 sessions maintain physical qualities without adding excessive fatigue.' },
    { type: 'multiple_choice', question: 'What should playoff preparation include?', options: ['Complete rest for 2 weeks', 'A mini-taper reducing volume 20-30% in final 1-2 weeks', 'Maximum training intensity', 'No changes'], correctAnswer: 1, explanation: 'Reduced volume with maintained intensity optimises playoff readiness.' },
    { type: 'multiple_choice', question: 'What is the goal of load management across a season?', options: ['Arriving at playoffs with the healthiest possible roster', 'Resting the best players', 'Reducing practice', 'Maximum fitness at all times'], correctAnswer: 0, explanation: 'Health and freshness for the playoff push.' },
    { type: 'multiple_choice', question: 'How should recovery days be structured?', options: ['Light activity — shooting, stretching, pool work', 'Heavy gym work only', 'Full training', 'Complete bed rest'], correctAnswer: 0, explanation: 'Light activity promotes recovery without adding training stress.' },
  ]),
];