import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const sportTennisUnit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'How many direction changes occur per set in tennis?', options: ['50-100', '150-200', '300-600', '1,000+'], correctAnswer: 2, explanation: 'Tennis involves 300-600 direction changes per set.' },
    { type: 'multiple_choice', question: 'What is the average sprint distance per point?', options: ['1-3 metres', '8-15 metres', '30-40 metres', '50+ metres'], correctAnswer: 1, explanation: 'Players cover 8-15 metres per point on average.' },
    { type: 'multiple_choice', question: 'What makes the serve the most injury-prone stroke?', options: ['It is slow', 'It involves the most explosive movement with highest forces on the shoulder', 'Only beginners get injured', 'The serve is not dangerous'], correctAnswer: 1, explanation: 'The serve is the most explosive overhead movement in tennis.' },
    { type: 'multiple_choice', question: 'What physical quality separates levels of tennis play?', options: ['Height', 'Reactive agility — decelerate, change direction, reaccelerate', 'Strength alone', 'Flexibility only'], correctAnswer: 1, explanation: 'Reactive agility is the primary physical differentiator.' },
    { type: 'multiple_choice', question: 'How does clay court affect rally length?', options: ['Shorter rallies', 'Longer rallies averaging 5-6 shots', 'No effect', 'Only affects serve speed'], correctAnswer: 1, explanation: 'Clay produces longer rallies requiring more endurance.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is the most tennis-specific strength quality?', options: ['Arm strength', 'Rotational power through the kinetic chain', 'Grip strength alone', 'Calf strength'], correctAnswer: 1, explanation: 'Rotational power from legs through trunk to arm powers all strokes.' },
    { type: 'multiple_choice', question: 'What speed does shoulder rotation reach during serving?', options: ['500 degrees/sec', '1,000 degrees/sec', '2,500 degrees per second', '5,000 degrees/sec'], correctAnswer: 2, explanation: '2,500 degrees per second of external rotation.' },
    { type: 'multiple_choice', question: 'What exercises develop court-covering movement?', options: ['Bicep curls', 'Lateral lunges, skater hops, and lateral sled drags', 'Bench press', 'Sit-ups'], correctAnswer: 1, explanation: 'Lateral movement exercises mirror court coverage patterns.' },
    { type: 'multiple_choice', question: 'How often should shoulder rotator cuff work be performed?', options: ['Once per month', 'Once per week', '3-4 times per week', 'Never'], correctAnswer: 2, explanation: '3-4 times per week protects against impingement and tendinopathy.' },
    { type: 'multiple_choice', question: 'What causes tennis elbow?', options: ['Playing too much', 'Insufficient grip and forearm strength combined with sudden volume increases', 'Wrong racquet colour', 'Court surface'], correctAnswer: 1, explanation: 'Weak grip/forearm muscles and sudden hitting volume increases.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What is the split step?', options: ['A stretching exercise', "A loaded hop timed to opponent\'s contact that pre-loads muscles for explosive first movement", 'A type of serve', 'Standing still'], correctAnswer: 1, explanation: 'The split step enables explosive reactive movement in any direction.' },
    { type: 'multiple_choice', question: 'What is the dominant movement pattern in tennis?', options: ['Forward sprinting', 'Lateral movement for court coverage', 'Backward running', 'Standing still'], correctAnswer: 1, explanation: 'Side-to-side groundstroke coverage dominates match movement.' },
    { type: 'multiple_choice', question: 'Why is first-step quickness more important than top-end speed?', options: ['It is not', 'Tennis movements average only 4-5 steps — top speed is rarely reached', 'First step looks better', 'Coaches prefer it'], correctAnswer: 1, explanation: 'Short distances mean maximum speed is never achieved.' },
    { type: 'multiple_choice', question: 'How should backward movement be executed in tennis?', options: ['Backpedalling', 'Turn and run — faster and more balanced', 'Walking backwards', 'Jumping backwards'], correctAnswer: 1, explanation: 'Turn-and-run is faster and maintains better balance.' },
    { type: 'multiple_choice', question: 'Why is recovery positioning important?', options: ['It looks professional', 'Returning to base position between shots ensures coverage for the next ball', 'It is a rule', 'It only matters in doubles'], correctAnswer: 1, explanation: 'Recovery ensures court coverage for subsequent shots.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What VO2max should tennis players target?', options: ['35-40 mL/kg/min', '50-60 mL/kg/min', '70+ mL/kg/min', '30 mL/kg/min'], correctAnswer: 1, explanation: '50-60 mL/kg/min supports between-point recovery.' },
    { type: 'multiple_choice', question: 'What work-to-rest ratio matches tennis point play?', options: ['30s work / 30s rest', '4-10s max effort / 20s rest', '5min work / 5min rest', 'Continuous work'], correctAnswer: 1, explanation: '4-10 seconds of maximal effort per point with 20 seconds rest.' },
    { type: 'multiple_choice', question: 'Why should tennis conditioning be running-based?', options: ['Running is the best exercise', 'Tennis requires running with direction changes — bikes and rowers are not specific enough', 'It burns more calories', 'No reason'], correctAnswer: 1, explanation: 'On-feet direction changes mirror match movement demands.' },
    { type: 'multiple_choice', question: 'What is repeated sprint ability?', options: ['Running one fast sprint', 'Maintaining sprint quality across multiple efforts with incomplete recovery', 'Sprinting once per game', 'Maximum speed only'], correctAnswer: 1, explanation: 'RSA measures the ability to sustain sprint quality across a match.' },
    { type: 'multiple_choice', question: 'Why is heat acclimation important for tennis?', options: ['It is not important', 'Major tournaments are often played in extreme heat affecting performance', 'It improves technique', 'Rules require it'], correctAnswer: 1, explanation: 'Heat acclimation reduces performance decline in hot tournament conditions.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What percentage of recreational players experience tennis elbow?', options: ['10-15%', '20-30%', '40-50%', '70-80%'], correctAnswer: 2, explanation: 'Tennis elbow affects 40-50% of recreational players.' },
    { type: 'multiple_choice', question: 'What is the gold-standard treatment and prevention for tennis elbow?', options: ['Ice', 'Eccentric wrist extensions', 'Surgery', 'Rest only'], correctAnswer: 1, explanation: 'Eccentric wrist extensions are both treatment and prevention.' },
    { type: 'multiple_choice', question: 'Why are running shoes unsuitable for tennis?', options: ['They are ugly', 'They lack the lateral support needed for direction changes on court', 'They are too heavy', 'No reason'], correctAnswer: 1, explanation: 'Court-specific shoes provide the lateral stability required for multidirectional movement.' },
    { type: 'multiple_choice', question: 'What is the most common acute tennis injury?', options: ['Shoulder tear', 'Tennis elbow', 'Ankle sprain from lateral movement', 'Hamstring strain'], correctAnswer: 2, explanation: 'Ankle sprains are the most common acute injury in tennis.' },
    { type: 'multiple_choice', question: 'What creates muscle imbalances in tennis players?', options: ['Poor nutrition', 'The asymmetric nature of playing — dominant side becomes stronger and tighter', 'Age', 'Surface type'], correctAnswer: 1, explanation: 'Repeated asymmetric loading creates progressive imbalances.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'Why is tennis nutrition uniquely challenging?', options: ['It is not challenging', 'Match duration is unpredictable — must fuel for any scenario', 'Players cannot eat during matches', 'Only affects professionals'], correctAnswer: 1, explanation: 'Unpredictable duration requires flexible fuelling strategies.' },
    { type: 'multiple_choice', question: 'How much fluid should be consumed per changeover?', options: ['A small sip', '200-400mL', '1 litre', 'Nothing during play'], correctAnswer: 1, explanation: '200-400mL at each changeover replaces sweat losses.' },
    { type: 'multiple_choice', question: 'When should carbohydrate consumption begin in matches?', options: ['Only in the final set', 'Early in the match — not waiting until late', 'Only if feeling tired', 'Before the match only'], correctAnswer: 1, explanation: 'Early fuelling prevents late-match glycogen depletion.' },
    { type: 'multiple_choice', question: 'What recovery nutrition is needed between tournament matches?', options: ['Nothing special', '20-30g protein + 1g/kg carbs within 30min, meals every 2-3 hours', 'Only water', 'Double normal intake'], correctAnswer: 1, explanation: 'Rapid recovery nutrition is critical with less than 24 hours between matches.' },
    { type: 'multiple_choice', question: 'How much body weight loss impairs tennis performance?', options: ['None', 'More than 2% through dehydration', 'More than 10%', 'Any weight loss helps'], correctAnswer: 1, explanation: '2% dehydration impairs concentration, reaction time, and physical output.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'What should the between-point routine include?', options: ['Nothing specific', 'Release (emotion) → reflect (tactics) → prepare (focus cue)', 'Just walking around', 'Talking to the crowd'], correctAnswer: 1, explanation: 'A deliberate three-part routine prevents dwelling on mistakes.' },
    { type: 'multiple_choice', question: 'Where does pressure in tennis come from?', options: ['The opponent', 'It is self-created from focusing on results rather than actions', 'The crowd', 'The umpire'], correctAnswer: 1, explanation: 'Pressure is generated internally by outcome-focused thinking.' },
    { type: 'multiple_choice', question: 'Why is emotional regulation critical in tennis?', options: ['It looks professional', 'Anger and frustration impair motor skills and signal vulnerability to opponents', 'Rules penalise emotions', 'It is not important'], correctAnswer: 1, explanation: 'Loss of composure impairs physical execution and gives opponents confidence.' },
    { type: 'multiple_choice', question: 'What is a reset technique?', options: ['Restarting the match', 'A consistent action (deep breath, string adjustment) that returns focus to calm composure', 'Changing racquet', 'Taking a bathroom break'], correctAnswer: 1, explanation: 'A trained reset response restores mental equilibrium.' },
    { type: 'multiple_choice', question: 'What drives tactical adjustments mid-match?', options: ['Random changes', 'Pattern recognition — reading opponent tendencies under pressure', 'Coach instructions', 'It cannot be done'], correctAnswer: 1, explanation: 'Observing opponent patterns informs strategic mid-match changes.' },
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'How long should the tennis off-season be?', options: ['1 week', '4-6 weeks', '3 months', 'No off-season needed'], correctAnswer: 1, explanation: '4-6 weeks allow physical development and mental refreshment.' },
    { type: 'multiple_choice', question: 'How many priority tournaments should be targeted per season?', options: ['All of them', '4-6 key events', 'Only 1', 'None — treat all equally'], correctAnswer: 1, explanation: '4-6 priority events allow strategic peaking.' },
    { type: 'multiple_choice', question: 'How long before a tournament should you arrive for adaptation?', options: ['Day of the event', '3-5 days early for surface and climate adjustment', '2 weeks early', 'Arrival time does not matter'], correctAnswer: 1, explanation: '3-5 days allows surface and climate adaptation.' },
    { type: 'multiple_choice', question: 'What should off-season training emphasise?', options: ['Maximum match play', 'Physical development — strength, aerobic conditioning, and addressing weaknesses', 'Complete rest', 'Technical work only'], correctAnswer: 1, explanation: 'Off-season is the only window for significant physical development.' },
    { type: 'multiple_choice', question: 'What is the jet lag rule for travel?', options: ['No adjustment needed', '1 day per time zone crossed for adaptation', '1 week regardless of distance', 'Caffeine solves jet lag'], correctAnswer: 1, explanation: 'Allow 1 day per time zone for proper adaptation.' },
  ]),
];