import type { ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

export const sportFootballUnit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'How much total distance does a footballer typically cover per match?', options: ['5-7 km', '10-13 km', '15-18 km', '20+ km'], correctAnswer: 1, explanation: 'Footballers cover approximately 10-13 kilometres per match.' },
    { type: 'multiple_choice', question: 'Which position typically performs the most maximal sprints?', options: ['Centre-back', 'Central midfielder', 'Winger/Forward', 'Goalkeeper'], correctAnswer: 2, explanation: 'Wingers and forwards perform the most maximal sprints and high-intensity accelerations.' },
    { type: 'multiple_choice', question: 'What is the best test for measuring football-specific aerobic fitness?', options: ['Cooper 12-min run', 'Beep test', 'Yo-Yo Intermittent Recovery Test', '5km time trial'], correctAnswer: 2, explanation: 'The Yo-Yo IR test mirrors football\'s stop-start nature.' },
    { type: 'multiple_choice', question: 'Most decisive moments in football happen within what time window?', options: ['10-15 seconds', '30-60 seconds', '1-5 seconds', '5-10 minutes'], correctAnswer: 2, explanation: 'Decisive moments happen in 1-5 second windows of explosive effort.' },
    { type: 'multiple_choice', question: 'High-intensity actions in professional football have increased by how much over the past 20 years?', options: ['5-10%', '15-20%', '30-50%', '70-80%'], correctAnswer: 2, explanation: 'High-intensity actions have increased 30-50% over two decades.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is the minimum squat strength target for a footballer?', options: ['0.5x bodyweight', '1x bodyweight', '1.5-2x bodyweight', '3x bodyweight'], correctAnswer: 2, explanation: '1.5-2x bodyweight squat provides the force production base for football movements.' },
    { type: 'multiple_choice', question: 'Why are hip thrusts important for footballers?', options: ['They build bigger glutes for appearance', 'They directly target the primary hip extensors used in sprinting', 'They improve flexibility', 'They are easier than squats'], correctAnswer: 1, explanation: 'Hip thrusts target the glutes, which are the primary hip extensors in sprinting.' },
    { type: 'multiple_choice', question: 'How should in-season gym volume change compared to pre-season?', options: ['Increase by 20%', 'Stay the same', 'Reduce by 40-60%', 'Reduce by 90%'], correctAnswer: 2, explanation: 'Volume drops 40-60% while intensity is maintained.' },
    { type: 'multiple_choice', question: 'When should the main gym session be scheduled relative to match day?', options: ['Match day morning', 'MD-1', 'MD-3 or MD-4', 'Any day is fine'], correctAnswer: 2, explanation: 'Main gym sessions should be placed MD-3 or MD-4 for recovery.' },
    { type: 'multiple_choice', question: 'What exercise is most important for hamstring injury prevention?', options: ['Leg press', 'Romanian deadlift', 'Leg extension', 'Calf raise'], correctAnswer: 1, explanation: 'RDLs build posterior chain resilience critical for hamstring injury prevention.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What is the most important speed quality for footballers?', options: ['Maximum velocity (top speed)', 'Acceleration (0-10m)', 'Speed endurance', 'Reaction time only'], correctAnswer: 1, explanation: 'Most football sprints cover less than 20m, making acceleration the priority.' },
    { type: 'multiple_choice', question: 'What drives horizontal force production in acceleration?', options: ['Pushing backwards against the ground at an aggressive lean', 'Running with high knees', 'Long stride length', 'Arm speed only'], correctAnswer: 0, explanation: 'Acceleration is driven by horizontal force production against the ground.' },
    { type: 'multiple_choice', question: 'What must you train BEFORE change of direction speed?', options: ['Sprint speed', 'Flexibility', 'Deceleration — you can only change direction as fast as you can stop', 'Upper body strength'], correctAnswer: 2, explanation: 'Deceleration is the foundation of effective direction change.' },
    { type: 'multiple_choice', question: 'What makes agility different from change of direction speed?', options: ['Agility is slower', 'Agility adds perception and decision-making', 'They are the same thing', 'Agility only applies to defenders'], correctAnswer: 1, explanation: 'True agility requires reactive decision-making, not just physical movement.' },
    { type: 'multiple_choice', question: 'What rest period is needed between maximal sprints for speed development?', options: ['30 seconds', '1 minute', '3-5 minutes', 'No rest needed'], correctAnswer: 2, explanation: 'Full neural recovery requires 3-5 minutes between maximal sprints.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What percentage of football energy demands are aerobic?', options: ['50%', '70%', '90%', '100%'], correctAnswer: 2, explanation: 'Football is approximately 90% aerobic, with decisive moments powered anaerobically.' },
    { type: 'multiple_choice', question: 'What is the most effective aerobic training tool for footballers?', options: ['Long slow distance running', 'Small-sided games (SSGs)', 'Swimming', 'Cycling'], correctAnswer: 1, explanation: 'SSGs develop aerobic fitness alongside tactical and technical skills.' },
    { type: 'multiple_choice', question: 'What does repeated sprint ability (RSA) training develop?', options: ['Maximum sprint speed', 'The ability to sprint, recover briefly, and sprint again', 'Flexibility', 'Technique'], correctAnswer: 1, explanation: 'RSA trains fatigue resistance for match-specific sprint patterns.' },
    { type: 'multiple_choice', question: 'What is the Helgerud HIIT protocol?', options: ['10×100m sprints', '4×4 minutes at 90-95% HRmax with 3min recovery', '30 minutes steady running', '1 hour slow jog'], correctAnswer: 1, explanation: 'The Helgerud protocol is an evidence-based method for improving VO2max.' },
    { type: 'multiple_choice', question: 'What is the biggest conditioning mistake in football?', options: ['Not running enough', 'Excessive running volume that interferes with strength and increases injury risk', 'Too much rest', 'Training too early in the day'], correctAnswer: 1, explanation: 'More running is not better — it reduces strength and raises injury risk.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What is the most common injury in football?', options: ['ACL rupture', 'Ankle sprain', 'Hamstring strain', 'Concussion'], correctAnswer: 2, explanation: 'Hamstring strains are responsible for more missed matches than any other injury.' },
    { type: 'multiple_choice', question: 'By how much do Nordic hamstring curls reduce hamstring injury rates?', options: ['10%', '25%', 'Up to 50%', 'They have no effect'], correctAnswer: 2, explanation: 'Nordic curls reduce hamstring injury rates by up to 50%.' },
    { type: 'multiple_choice', question: 'What ACWR level significantly increases injury risk?', options: ['0.5-0.8', '0.8-1.0', 'Above 1.3-1.5', 'Any ratio above 0.5'], correctAnswer: 2, explanation: 'When ACWR exceeds 1.3-1.5, injury risk increases significantly.' },
    { type: 'multiple_choice', question: 'Which exercise reduces groin injury risk by up to 40%?', options: ['Adductor machine', 'Copenhagen adductor exercise', 'Leg press', 'Calf raise'], correctAnswer: 1, explanation: 'The Copenhagen adductor exercise has strong evidence for groin injury prevention.' },
    { type: 'multiple_choice', question: 'What does the FIFA 11+ programme reduce total injuries by?', options: ['5-10%', '15-20%', '30-40%', '60-70%'], correctAnswer: 2, explanation: 'The FIFA 11+ reduces injuries by 30-40% when performed consistently.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'How much carbohydrate should a footballer consume before a match?', options: ['1-2g/kg/day', '3-4g/kg/day', '7-10g/kg/day', 'No carbs needed'], correctAnswer: 2, explanation: 'Carb loading at 7-10g/kg/day should begin 36-48 hours before match day.' },
    { type: 'multiple_choice', question: 'When does low glycogen most affect football performance?', options: ['First 15 minutes', 'At half-time', 'In the second half, especially the final 30 minutes', 'It does not affect performance'], correctAnswer: 2, explanation: 'Low glycogen causes slower sprints and poor decisions in the second half.' },
    { type: 'multiple_choice', question: 'When should post-match recovery nutrition begin?', options: ['The next morning', 'Within 30 minutes of the final whistle', '2-3 hours after the match', 'It does not matter'], correctAnswer: 1, explanation: 'Recovery nutrition should begin within 30 minutes post-match.' },
    { type: 'multiple_choice', question: 'What protein intake is recommended for footballers?', options: ['0.5-0.8g/kg/day', '1.0-1.2g/kg/day', '1.6-2.2g/kg/day', '3.0g/kg/day'], correctAnswer: 2, explanation: '1.6-2.2g/kg/day supports muscle repair and immune function.' },
    { type: 'multiple_choice', question: 'When should body composition changes be pursued in football?', options: ['During the season', 'During congested fixtures', 'During the off-season or reduced training periods', 'Never'], correctAnswer: 2, explanation: 'Weight management should only be attempted when training demands are reduced.' },
  ]),
  cq(1, 7, [
    { type: 'multiple_choice', question: 'What is task-relevant attention in football?', options: ['Watching the ball constantly', 'Actively scanning and processing tactical information during play', 'Ignoring distractions', 'Focusing only on your direct opponent'], correctAnswer: 1, explanation: 'Task-relevant attention involves constant scanning and information processing.' },
    { type: 'multiple_choice', question: 'What does the three-second rule for mistakes involve?', options: ['Ignoring the mistake completely', 'Feel the emotion, reset with a physical trigger, refocus on the next action', 'Dwelling on it for three seconds then moving on', 'Discussing it with teammates'], correctAnswer: 1, explanation: 'The three-second rule manages emotional response to errors without suppression.' },
    { type: 'multiple_choice', question: 'What builds confidence most effectively?', options: ['Positive self-talk alone', 'Mastery experiences — setting achievable targets and tracking success', 'Ignoring failures', 'Watching highlight videos'], correctAnswer: 1, explanation: 'Confidence comes from evidence of your own competence through mastery experiences.' },
    { type: 'multiple_choice', question: 'When should visualisation be performed?', options: ['Only before matches', 'Before every session — 5-10 minutes of key action rehearsal', 'Only after poor performances', 'Never — it does not work'], correctAnswer: 1, explanation: 'Regular pre-session visualisation activates neural pathways similar to physical practice.' },
    { type: 'multiple_choice', question: 'Why is communication an important mental performance tool?', options: ['It impresses coaches', 'It demands engagement and reduces the tendency to withdraw when things go wrong', 'It is only important for captains', 'It has no mental benefit'], correctAnswer: 1, explanation: 'Communication maintains engagement and prevents withdrawal during difficult periods.' },
  ]),
  cq(1, 8, [
    { type: 'multiple_choice', question: 'When is the most valuable period for physical development?', options: ['Pre-season only', 'The off-season (4-6 weeks without matches)', 'In-season', 'It does not matter'], correctAnswer: 1, explanation: 'The off-season allows focused physical development without match demands.' },
    { type: 'multiple_choice', question: 'What is the biggest pre-season mistake?', options: ['Not training enough', 'Cramming too much fitness work, creating excessive fatigue for early season', 'Starting too early', 'Only doing tactical work'], correctAnswer: 1, explanation: 'Excessive pre-season volume increases injury risk during the critical early season.' },
    { type: 'multiple_choice', question: 'How many gym sessions per week are recommended in-season?', options: ['None — focus on matches', '1 session', '2 sessions', '4 sessions'], correctAnswer: 2, explanation: 'Two gym sessions per week maintains strength without excessive fatigue.' },
    { type: 'multiple_choice', question: 'What happens if strength training is abandoned in October?', options: ['Nothing — match fitness is sufficient', 'Players arrive at the season finish depleted, injury-prone, and unable to sustain intensity', 'Strength is maintained through matches', 'It can be regained in one week'], correctAnswer: 1, explanation: 'Strength declines within 2-3 weeks without stimulus, affecting late-season performance.' },
    { type: 'multiple_choice', question: 'What is the training priority during congested fixture periods?', options: ['Maximum gym volume', 'Additional conditioning', 'Recovery, nutrition, and sleep quality', 'Tactical analysis only'], correctAnswer: 2, explanation: 'During congested periods, recovery becomes the primary constraint.' },
  ]),
];